### ISSUE TITLE
Segmentation Fault on "#{}:"

### ISSUE THREAD

**Issue by pocket7878** [sorbet/sorbet#1001]
I got Segmentation-Fault from activerecord code and found minimum reproducing code:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/inheritance.rb#L194

Ruby version: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`
Sorbet version: `Sorbet typechecker 0.4.4289 git 91b825ede856537064244202b688317bb00105ac built on 2019-06-21 23:19:41 GMT with debug symbols`
Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    sorbet (0.4.4289)
      sorbet-static (= 0.4.4289)
    sorbet-runtime (0.4.4289)
    sorbet-static (0.4.4289-universal-darwin-14)

PLATFORMS
  ruby

DEPENDENCIES
  sorbet
  sorbet-runtime

BUNDLED WITH
   1.16.2
```

Minimum Segmentation-fault reproducing input:

```
"#{}:"
```

Output:
```
/Users/pocket7878/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4289/bin/srb: line 43: 21015 Segmentation fault: 11  "${sorbet[0]}" "${args[@]}"
```

**Comment by DarkDimius** [comment]
Thank you for a great report and wonderful minimization.

```
./bazel-bin/main/sorbet --silence-dev-message -e \"#{}:\" 
ast/desugar/Desugar.cc:97:60: runtime error: member call on null pointer of type 'sorbet::ast::Literal'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ast/desugar/Desugar.cc:97:60 in
Abort trap: 6
```
