### ISSUE TITLE
`srb init --dir=app` should put args in the config file

### ISSUE THREAD

**Issue by olbrich** [sorbet/sorbet#1004]
### Problem

When setting up a new project with sorbet, it is sometimes useful to try multiple configurations.  Currently running `srb init` just creates a very plain config file which then needs to be hand edited.

### Proposed solution

When using `srb init` it would be helpful to generate the config file using any additional arguments passed in.  A syntax like `srb init --dir=app` would create a config file like...
```
--dir
app
```

**Comment by jez** [comment]
Hm, if this is what you want, we expect that you'd just `cd` into `app` before running `srb init`.

In general, Sorbet assumes that it's operating over your entire project, and any attempt to limit the scope to anything less than that is ~unsupported an likely to be met with difficulty.

Thanks for trying out Sorbet! Please keep your feedback coming.
