### ISSUE TITLE
`srb init` should prompt before overwriting existing config

### ISSUE THREAD

**Issue by olbrich** [sorbet/sorbet#1005]
### Problem

When setting up a new project it is not uncommon to need to run `srb init`, deal with some issue that is exposed, and then try again.  If changes have been made to the config file, those changes are overwritten.

### Proposed solution

`srb init` should detect that generated directories/files already exist and prompt for the right behavior (e.g., `sorbet/config exists, overwrite? [y/N]`)

**Comment by aprocter-stripe** [comment]
Looks like this one was effectively addressed by #1343 quite a while ago. (We no longer overwrite existing config files.)
