### ISSUE TITLE
Track method visibility and emit errors for violations

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#1011]
Sorbet completely ignores `private`, `protected` and `private_class_method` for the purpose of static checking. For example, when calling a `private` method from a non-private context, Sorbet will emit no errors, but the runtime will raise an exception.

Supporting this properly in Sorbet is going to be hard and invasive. Please talk to the team on Slack before attempting to undertake this feature.

**Comment by DarkDimius** [comment]
Awesome testcase by 
@nroman-stripe 
https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20class%20P%0A%20%20end%0A%20%20private_constant%20%3AP%0A%0A%20%20X%20%3D%20100%0A%20%20private_constant(%3AX)%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20def%20bar%0A%20%20%20%20P.new.to_s%0A%20%20end%0Aend%0A%0Aclass%20M%0A%20%20def%20main%0A%20%20%20%20A%3A%3AP.new%20%23%20Should%20be%20%60private%20constant%20A%3A%3AP%20referenced%20(NameError)%60%0A%20%20%20%20A%3A%3AX%20%23%20Should%20be%20%60private%20constant%20A%3A%3AX%20referenced%20(NameError)%60%0A%0A%20%20%20%20A.new.bar%20%23%20OK%0A%20%20end%0Aend%0AM.new.main

**Comment by jez** [comment]
^ this is for private_constant, which we might want to have a separate issue for (I imagine implementing one will not overlap with implementing the other)

**Comment by jez** [comment]
private methods were implemented in #3505

private constants were implemented in #3565
