### ISSUE TITLE
How does editor support work?

### ISSUE THREAD

**Issue by TobiasBales** [sorbet/sorbet#1013]
Before asking your question, please make sure these are true:

- [x] I have read the Troubleshooting guide.

  - https://sorbet.org/docs/troubleshooting

- [x] I have tried searching the docs for an answer.

  - https://sorbet.org/docs/overview

- [x] I have tried to reproduce the behavior I'm seeing on sorbet.run: - does not really apply

  - https://sorbet.run

- [x] I have read (or at least skimmed) *How to ask good questions* by Julia Evans

  - https://jvns.ca/blog/good-questions/

Great, thanks! Now by all means, ask away:

- - -

First off, I am super excited that sorbet is finally open source :D

I tried getting started with a fresh rails project and `srb tc` etc work just fine but in the talks
there were always references to it being supported in editors (via LSP). I tried searching for editor/ide/lsp/vs code in all docs I could find but didn't find anything.

So, how do I actually get the support into an editor (e.g. VS Code)? :D

Thanks so much for all the hard work that went intoi

**Comment by jhhb** [comment]
@TobiasBales I was looking around myself for this and found some discussion in the Solargraph repo from a few days ago involving one of the Sorbet maintainers:

https://github.com/castwide/solargraph/issues/194

> Editor plugin exists but it's currently closed source. It will get open-sourced when we stabilize LSP features.

**Comment by connorshea** [comment]
Per Twitter, essentially the same response as above: https://twitter.com/darkdimius/status/1141785271958167553

The extension isn't ready for prime-time yet, we'll have to wait until more of the LSP features are finished and the extension is a bit more polished. They're definitely working on it, they moved an LSP feature out of beta in this repo on Friday IIRC, so it'll just require some patience :)

**Comment by jez** [comment]
We're currently working on editor support at Stripe. Sorbet supports a bunch of experimental flags for enabling IDE features, but they're very experimental (read: they crash a lot). When they stop crashing, we'll tell people how to use them.

**Comment by peternixey** [comment]
Can I suggest that you guys just put something on the frontpage of Sorbet mentioning that the editor integration isn't actually available yet. It's a touch confusing at the moment as it pretty strongly suggests that it is. Really can't wait for it to be released!

<img width="1211" alt="Screenshot 2021-04-12 at 15 03 18" src="https://user-images.githubusercontent.com/168592/114407424-4767f500-9ba0-11eb-8b10-456df6b6aed0.png">

**Comment by peternixey** [comment]
Any update on this guys? I would imagine that there are many hundreds of us waiting to get our hands on your good work

**Comment by Xanthus** [comment]
I agree with @peternixey. If IDE support isn't ready that's understandable. Putting "_Sorbet works with your favourite editor to provide IDE features like autocomplete and jump to definition._" on the homepage and letting people search everywhere for the plugin isn't. How about just adding a 'Coming soon' sticker over it?

**Comment by ukd1** [comment]
Echoing this, it's misleading right now.

**Comment by guledali** [comment]
I remember looking at this project around 2018 November even back then they mostly showcasing the vscode plugin in all their talks. Today as write it's june 2021, almost 3 years has passed and the vscode plugin is still under development and not yet released

**Comment by trkoch** [comment]
An (updated) official statement wouldn't hurt?

**Comment by quinn** [comment]
![Screenshot from 2021-11-26 11-32-52](https://user-images.githubusercontent.com/3764/143610069-ce316316-4cdc-4bfe-9d16-4b3e49221920.png)

:(

**Comment by connorshea** [comment]
In case people come back to this issue later, the VS Code extension is now available: https://sorbet.org/blog/2022/01/06/open-sourcing-sorbet-vscode

**Comment by peternixey** [comment]
Amazing news - thank you @connorshea - very excited to start using it!
