### ISSUE TITLE
Class methods that dynamically define instance methods

### ISSUE THREAD

**Issue by janko** [sorbet/sorbet#1015]
The [dry-initializer](https://dry-rb.org/gems/dry-initializer/) gem provides class methods `param` and `option` that dynamically define instance methods (similar to `attr_reader`/`attr_writer`/`attr_accessor` do).

```rb
require "dry/initializer"

class Person
  extend Dry::Initializer

  option :first_name
  option :last_name

  def full_name
    "#{first_name} #{last_name}"
  end
end
```

However, Sorbet currently doesn't know about that:

```
person.rb:12: Method first_name does not exist on Person https://srb.help/7003
    12 |    "#{first_name} #{last_name}"
               ^^^^^^^^^^
    person.rb:11: Did you mean: Person#full_name?
    11 |  def full_name
          ^^^^^^^^^^^^^

person.rb:12: Method last_name does not exist on Person https://srb.help/7003
    12 |    "#{first_name} #{last_name}"
                             ^^^^^^^^^
    person.rb:11: Did you mean: Person#full_name?
    11 |  def full_name
          ^^^^^^^^^^^^^
```

How do I tell Sorbet in a `.rbi` file that `Dry::Initializer#option` and `Dry::Initializer#param` dynamically define methods named after the first argument?

**Comment by pocket7878** [comment]
Can we use sorbet-rails like code generating approach?
https://github.com/chanzuckerberg/sorbet-rails

**Comment by gogiel** [comment]
It should be possible using DSL API but it's still under development https://github.com/sorbet/sorbet/pull/1122/files

**Comment by gogiel** [comment]
You can also use `T::Struct` or `T::InexactStruct`.

For the class from your example:
```ruby
require "dry/initializer"

class Person
  extend Dry::Initializer

  option :first_name
  option :last_name

  def full_name
    "#{first_name} #{last_name}"
  end
end
```

rbi should look like this:

```ruby
# typed: true
class Person < T::InexactStruct
  prop :first_name, String
  prop :last_name, String
end
```

Docs: https://github.com/sorbet/sorbet/blob/master/website/docs/tstruct.md

**Comment by jez** [comment]
The suggestions from the Sorbet team are exactly what the other commenters have pointed out:

- Analyze the code manually to generate custom RBIs
- Use `srb init` to generate RBIs manually, without types
- Use `T::Struct`, which is basically the same as `dry`, but comes with better type safety.
