### ISSUE TITLE
When `compact.first` cannot be nil, incorrectly produces error 7005 

### ISSUE THREAD

**Issue by jaredbeck** [sorbet/sorbet#1022]
Generally, `compact.first` can return `nil`. However, consider this case where it is guaranteed not to.

In this example, there may or may not be an `apple`, but there is always a `banana`. Therefore, `compact.first` can never return `nil`.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%23%20frozen_string_literal%3A%20true%0A%0Aclass%20Chooser%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(hates_apples%3A%20T%3A%3ABoolean).void%20%7D%0A%20%20def%20initialize(hates_apples)%0A%20%20%20%20%40hates_apples%20%3D%20hates_apples%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(String)%20%7D%0A%20%20def%20best%0A%20%20%20%20candidates.compact.first%0A%20%20end%0A%0A%20%20private%0A%0A%20%20sig%20%7B%20returns(%3A%3AT.nilable(%3A%3AString))%20%7D%0A%20%20def%20apple%0A%20%20%20%20%40hates_apples%20%3F%20nil%20%3A%20'Malus%20domestica'%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(%3A%3AString)%20%7D%0A%20%20def%20banana%0A%20%20%20%20'Musa%20acuminata'%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T%3A%3AArray%5BT.nilable(String)%5D)%20%7D%0A%20%20def%20candidates%0A%20%20%20%20%5B%0A%20%20%20%20%20%20apple%2C%0A%20%20%20%20%20%20banana%0A%20%20%20%20%5D%0A%20%20end%0Aend%0A%0A%3A%3AChooser.new(true).best%0A)

```ruby
# typed: true
# frozen_string_literal: true

class Chooser
  extend T::Sig

  sig { params(hates_apples: T::Boolean).void }
  def initialize(hates_apples)
    @hates_apples = hates_apples
  end

  sig { returns(String) }
  def best
    candidates.compact.first
  end

  private

  sig { returns(::T.nilable(::String)) }
  def apple
    @hates_apples ? nil : 'Malus domestica'
  end

  sig { returns(::String) }
  def banana
    'Musa acuminata'
  end

  sig { returns(T::Array[T.nilable(String)]) }
  def candidates
    [
      apple,
      banana
    ]
  end
end

::Chooser.new(true).best
```

#### Observed output

```
editor.rb:14: Returning value that does not conform to method result type https://srb.help/7005
    14 |    candidates.compact.first
            ^^^^^^^^^^^^^^^^^^^^^^^^
  Expected String
    editor.rb:13: Method best has return type String
    13 |  def best
          ^^^^^^^^
  Got T.nilable(String) originating from:
    editor.rb:14:
    14 |    candidates.compact.first
            ^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Should pass `tc`.

#### Workaround

```
def best
  T.cast(candidates.compact.first, String)
end
```

**Comment by ptarjan** [comment]
Thanks for writing in! You are indeed correct that it could be possible to prove all sorts of things about the internal states of arrays, but Sorbet doesn't track things like emptyness as it processes. There is a future where it could, but these types of checks are traditionally very hard to get right and we haven't deemed the effort to be worth the value yet.

**Comment by jaredbeck** [comment]
> .. Sorbet doesn't track things like emptyness as it processes .. these types of checks are traditionally very hard to get right ..

Totally understandable. Some things that are easy for humans to see at a glance turn out to be really hard to handle with software. Maybe we won't all lose our jobs just yet. :grin:

One way to think about this issue is to say that the signature of `candidates` is incorrect.

```
sig { returns(T::Array[T.nilable(String)]) }
def candidates
```

We could instead give it the following hypothetical signature: 

> An array with exactly two elements, whose second element is a non-nilable string.

This is similar in my mind to the concept of "shapes". But, even with this improved signature, we still have the problem of, as you say, "tracking emptiness".

**Comment by jaredbeck** [comment]
> ... Sorbet doesn't track things like emptyness as it processes. There is a future where it could, but these types of checks are traditionally very hard to get right and we haven't deemed the effort to be worth the value yet.

Closing, given that `T.cast` is a reasonable workaround for this.

**Comment by jez** [comment]
`T.cast` requires that the type be repeated, and could actually get out of sync if for some reason the array changed from being an array of strings to an array of integers. To just remove the `T.nilable`, you can use `T.must(candidates.compact.first)` which is both shorter and more type safe.

**Comment by jez** [comment]
More information here:

https://sorbet.org/docs/type-assertions#tmust
