### ISSUE TITLE
A[Integer(42)] does not match A[Integer]

### ISSUE THREAD

**Issue by bolshakov** [sorbet/sorbet#1026]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20V%20%3D%20type_member%0A%0A%20%20sig%20%7B%20params(v%3A%20V).void%20%7D%0A%20%20def%20initialize(v)%0A%20%20end%0Aend%0A%0Aextend%20T%3A%3ASig%20%0A%0Asig%20do%0A%20%20type_parameters(%3AT)%0A%20%20.params(v%3A%20T.type_parameter(%3AT))%0A%20%20.returns(A%5BT.type_parameter(%3AT)%5D)%0Aend%0Adef%20build_a(v)%0A%20%20A.new(v)%0Aend%0A%0Asig%20%7B%20params(v%3A%20A%5BInteger%5D).void%20%7D%0Adef%20test_int(v)%0Aend%0A%0Aa%20%3D%20build_a(42)%0Atest_int(a))

```ruby
# typed: true
class A
  extend T::Sig
  extend T::Generic
  V = type_member

  sig { params(v: V).void }
  def initialize(v)
  end
end

extend T::Sig 

sig do
  type_parameters(:T)
  .params(v: T.type_parameter(:T))
  .returns(A[T.type_parameter(:T)])
end
def build_a(v)
  A.new(v)
end

sig { params(v: A[Integer]).void }
def test_int(v)
end

a = build_a(42)
test_int(a)
```

#### Observed output

```
editor.rb:28: A[Integer(42)] does not match A[Integer] for argument v https://srb.help/7002
    28 |test_int(a)
        ^^^^^^^^^^^
    editor.rb:23: Method Object#test_int has specified v as A[Integer]
    23 |sig { params(v: A[Integer]).void }
                     ^
  Got A[Integer(42)] originating from:
    editor.rb:27:
    27 |a = build_a(42)
            ^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

    No errors! Great job.

- - -

What does this type mean `Integer(42)`?

**Comment by elliottt** [comment]
Interestingly, this problem goes away when you replace
```ruby
a = build_a(42)
```
with
```ruby
a = build_a(T.let(42,Integer))
```
but this does indeed seem like a bug, thanks!

**Comment by bolshakov** [comment]
It also doesn't work if `test` function has generic argument ([run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20V%20%3D%20type_member%0A%0A%20%20sig%20%7B%20params(v%3A%20V).void%20%7D%0A%20%20def%20initialize(v)%0A%20%20end%0Aend%0A%0Aextend%20T%3A%3ASig%20%0A%0Asig%20do%0A%20%20type_parameters(%3AT)%0A%20%20.params(v%3A%20T.type_parameter(%3AT))%0A%20%20.returns(A%5BT.type_parameter(%3AT)%5D)%0Aend%0Adef%20build_a(v)%0A%20%20A.new(v)%0Aend%0A%0Asig%20do%0A%20%20type_parameters(%3AT)%0A%20%20.params(v%3A%20A%5BT.type_parameter(%3AT)%5D).void%0Aend%0Adef%20test(v)%0Aend%0A%0Av%20%3D%20T.let(42%2C%20Integer)%0Aa%20%3D%20build_a(v)%0Atest(a))):

```ruby
sig do
  type_parameters(:T)
  .params(v: A[T.type_parameter(:T)]).void
end
def test(v)
end

v = T.let(42, Integer)
a = build_a(v)
test(a)
```

Fails with error:

```
editor.rb:32: A[Integer] does not match A[T] for argument v https://srb.help/7002
    32 |test(a)
        ^^^^^^^
    editor.rb:25: Method Object#test has specified v as A[T]
    25 |  .params(v: A[T.type_parameter(:T)]).void
                  ^
  Got A[Integer] originating from:
    editor.rb:31:
    31 |a = build_a(v)
            ^^^^^^^^^^
Errors: 1
```

**Comment by jez** [comment]
I don't know that this is a bug. Generic type members are invariant by default, which means that since `Integer(42)` is a subtype of `Integer` (and not equivalent to `Integer`), that Sorbet correctly reports an error.

We could maybe be doing a better job about how invariant type members interact with literal types, or produce a better message that this is a problem with the variance, but I general I think this is expected behavior.

**Comment by bolshakov** [comment]
It's hard to imagine a situation where it may be useful ta have type `Integer(42)` instead of `Integer` for `42`. I expect 42 is an Integer.
