### ISSUE TITLE
Extract types from a gem into RBIs

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#1033]
### Problem

Sorbet already attempts to discover RBIs included with gems (by looking for an `rbi/` folder in the gem's top-level).

Right now, this folder has to be populated manually and kept in sync manually. Sorbet already has all the information about a codebase, including what classes exist, methods are defined, and what types they have. It would be easy for Sorbet to run in a mode that populates the `rbi` folder based on static information.

### Proposed solution

There are two ways to go about this:

- Build it in C++
  - This will run faster, be more accurate, easier to test, and benefit from all the infrastructure Sorbet has for writing tests.
- Build it in Bash / Ruby
  - An easier attempt to build this might be to use either a Ruby (`'parser'` or `'ripper'` or something else) or Bash (sed / grep / etc.) to find the sigs and copy / paste them into an RBI file.

Definitely the C++ route is preferred, but we'd prefer having the feature over not having it. Contributions welcome!

**Comment by michaelwebb76** [comment]
Does anyone have any workarounds to generate (even partially) the RBI to live in the root `rbi` folder of a gem? Maintaining this by hand is excruciating.

**Comment by AaronC81** [comment]
I've created a command line tool based on my [Parlour](https://github.com/AaronC81/parlour) library which can load an entire Sorbet project with inline signatures and generate an RBI for it. It's called [Brain Freeze](https://github.com/AaronC81/brain_freeze) and uses Parlour's type loader features, which use whitequark's parser internally.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
