### ISSUE TITLE
`sorbet -a` produces invalid ruby if LHS of op-equals is nilable

### ISSUE THREAD

**Issue by carl-stripe** [sorbet/sorbet#1034]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%20T.let(0%2C%20T.nilable(Integer))%0A%0Ax%20%2B%3D%202)

Given the following:
```ruby
x = T.let(0, T.nilable(Integer))
x += 2
```
Run `sorbet -a`

#### Observed output

```ruby
x = T.let(0, T.nilable(Integer))
T.must(x) += 2
# syntax error!
```

#### Expected behavior

I expect the result of running `sorbet -a` to be valid Ruby syntax

**Comment by elliottt** [comment]
We don't currently guarantee that `sorbet -a` will produce syntactically correct output, and in the short-term it's best to always run sorbet again to catch any errors.
