### ISSUE TITLE
`sorbet -a` produces invalid type syntax when changing variable type in loop

### ISSUE THREAD

**Issue by carl-stripe** [sorbet/sorbet#1035]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%2C%20y%20%3D%20nil%0A%0A1.times%20%7Bx%20%3D%204%7D)

```ruby
x, y = nil

1.times {x = 4}
```

#### Observed output

```
editor.rb:5: Changing the type of a variable in a loop is not permitted https://srb.help/7001
     5 |1.times {x = 4}
                     ^
  Existing variable has type: NilClass
  Attempting to change type to: Integer(4)

  Autocorrect: Use `-a` to autocorrect
    editor.rb:3: Replace with T.let(x, y = nil, T.nilable(Integer))
     3 |x, y = nil
        ^^^^^^^^^^
Errors: 1
```

If you accept this correction with `sorbet -a`, it produces type syntax that Sorbet doesn't understand

#### Expected behavior

I'd expect `sorbet -a` to only produce valid type syntax in its autocorrection pass

**Comment by elliottt** [comment]
We don't currently guarantee that `sorbet -a` will produce syntactically correct output, and in the short-term it's best to always run sorbet again to catch any errors.
