### ISSUE TITLE
--typed-override flag should support globs

### ISSUE THREAD

**Issue by jekozyra** [sorbet/sorbet#1041]
### Problem

We'd like to be able to set `typed` to `false` for entire directories. Right now, we have to explicitly include every file, which doesn't scale well.

Our specific use case is that by default, our CI tool (CircleCI) expects gems to be installed in the rails project directory and installing them elsewhere is difficult. However, since they end up in the project directory, when we try to run sorbet as part of the pipeline, it attempts to typecheck the gems and fails.

### Proposed solution

The proposed solution is to modify `extractStricnessOverrides` to support globs.

**Comment by jez** [comment]
@jekozyra `false` is the default level; overriding to `false` would be a no-op.

Are you trying to ignore these files? Have you seen:

https://sorbet.org/docs/cli#including-and-excluding-files

Specifically:

> ```bash
> # All *.rb / *.rbi files in the current folder,
> # minus any file in the vendor folder of the current directory.
> srb tc . --ignore=/vendor
> ```

**Comment by jez** [comment]
It seems like you could also use `find` to compute the typed-override file in CI:

```bash
echo 'ignore:' > vendor-ignores.yaml
find vendor -type f -exec echo '  - {}' \; >> vendor-ignores.yaml
```

**Comment by manhhung741** [comment]
It seems `ignore` level doesn't work for her, based on her post on Slack:

> we’re using circleCI for our rails app. as part of the circleCI workflow, gems are installed in vendor/bundle. if i run `srb tc`, i get a ton of errors from that directory. however, if i do `srb tc --ignore=/vendor`, i get fewer, but different errors (Method does not exist, Unable to resolve constant). what’s the recommended way for handling this?

> @jekozyra false is the default level; overriding to false would be a no-op.

If false is the default level, I don't know what's causing the error when typechecking the `vendor/` file.

I think it'll be useful to see what errors `bundle exec srb tc` print on CircleCI.

**Comment by jekozyra** [comment]
@jez Ignoring the vendor directory was my initial approach. `srb tc . --ignore=/vendor` yields a bunch of `Method x does not exist on Y` and `Unable to resolve constant` errors. None of these are present when I run `srb tc` locally.
