### ISSUE TITLE
Improve ::Google::Protobuf DSL support

### ISSUE THREAD

**Issue by djudd-stripe** [sorbet/sorbet#1056]
### Problem
The DSL pass could inform us that Proto-generated classes will always `include Google::Protobuf::MessageExts` and extend `Google::Protobuf::MessageExts::ClassMethods`. More context in linked PR.

### Proposed solution
https://github.com/sorbet/sorbet/pull/1053/files

**Comment by jez** [comment]
We have deleted the protobuf support from sorbet and replaced it with https://github.com/coinbase/protoc-gen-rbi
