### ISSUE TITLE
`Kernel::Integer` show allow for `exception` keyword argument

### ISSUE THREAD

**Issue by frewsxcv** [sorbet/sorbet#1060]
```
app/controllers/refunds_controller.rb:180: {exception: FalseClass} does not match Integer for argument base https://srb.help/7002
     180 |      refunds.keys.any? { |k| Integer(k, exception: false).nil? } ||
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Relevant code:

https://github.com/sorbet/sorbet/blob/217956999733b1488340006103111f9bd2c83c0c/rbi/core/kernel.rbi#L490-L497

Relevant docs:

https://ruby-doc.org/core-2.6.3/Kernel.html#method-i-Integer

If the user passes an `exception` keyword argument, the return type should be `T.nilable(Integer)`, otherwise the return type should be `Integer`

This should apply to other numeric types in `Kernel`, like `BigDecimal`

**Comment by elliottt** [comment]
It looks like this was introduced in 2.6.

**Comment by connorshea** [comment]
This is resolved now isn’t it?
