### ISSUE TITLE
`T.type_parameter(:U)`  being treated as `<any>` in `each_with_object`

### ISSUE THREAD

**Issue by jeffcarbs** [sorbet/sorbet#1098]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aarray%20%3D%20%5B1%2C2%2C3%5D%0Aenumerator%20%3D%20array.each%0A%0Aenumerator.each_with_object(%7B%7D)%20%7B%20%7Ci%2C%20memo%7C%20memo%5Bi%5D%20%3D%20i%20*%202%20%7D%0A)

```ruby
# typed: true

array = [1,2,3]
enumerator = array.each

enumerator.each_with_object({}) { |i, memo| memo[i] = i * 2 }
```

#### Observed output

```
editor.rb:6: Method []= does not exist on <any> https://srb.help/7003
     6 |enumerator.each_with_object({}) { |i, memo| memo[i] = i * 2 }
                                                    ^^^^^^^^^^^^^^^
Errors: 1
```

This works in a console:
```
> array = [1,2,3]
 => [1, 2, 3]
> enumerator = array.each
 => #<Enumerator: [1, 2, 3]:each>
> enumerator.each_with_object({}) { |i, memo| memo[i] = i * 2 }
 => {1=>2, 2=>4, 3=>6}
```

#### Expected behavior

`No errors! Great job.`

- - -

Here's the signature for `each_with_object`:
```ruby
sig do
  type_parameters(:U).params(
      arg0: T.type_parameter(:U),
      blk: T.proc.params(arg0: Elem, arg1: T.type_parameter(:U)).returns(BasicObject),
  )
  .returns(T.untyped)
end
```
which seems like it shouldn't have this issue.

Sidenote: I'm fixing up the signature for Enumerator and Enumerable in a separate PR (#1097) but that's unrelated to this bug.

**Comment by XrXr** [comment]
I think #38 is related

**Comment by jez** [comment]
Another example:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ahash_1%20%3D%20T.let(%7B%7D%2C%20T%3A%3AHash%5BString%2C%20Integer%5D)%0Ahash_2%20%3D%20T.let(%7B%7D%2C%20T%3A%3AHash%5BString%2C%20Integer%5D)%0Ahash_1.merge(hash_2)%20do%20%7C_%2C%20a%2C%20b%7C%0A%20%20a%20%2B%20b%0Aend)

```ruby
# typed: true

hash_1 = T.let({}, T::Hash[String, Integer])
hash_2 = T.let({}, T::Hash[String, Integer])
hash_1.merge(hash_2) do |_, a, b|
  a + b
end
```

Output:

```
editor.rb:6: Expected Integer but found <any> for argument arg0 https://srb.help/7002
     6 |  a + b
          ^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/integer.rbi#L148: Method Integer#+ has specified arg0 as Integer
     148 |        arg0: Integer,
                  ^^^^
  Got <any> originating from:
    editor.rb:5:
     5 |hash_1.merge(hash_2) do |_, a, b|
                                       ^
Errors: 1
```

Expected: no errors

**Comment by almcgo-stripe** [comment]
I'm hitting the same issue. [Example](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Channel%0A%20%20def%20read%0A%20%20end%0A%20%20def%20write%0A%20%20end%0Aend%0A%0Aclass%20JsonChannel%20%3C%20Channel%0A%20%20def%20read%0A%20%20end%0A%20%20def%20write%0A%20%20end%0Aend%0A%0Aclass%20Proc%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AT)%0A%20%20%20%20.params(channel%3A%20T.all(Channel%2C%20T.type_parameter(%3AT))%2C%20block%3A%20T.proc.params(channel%3A%20T.type_parameter(%3AT)).void)%0A%20%20%20%20.returns(%5BInteger%2C%20T.type_parameter(%3AT)%5D)%0A%20%20end%0A%20%20def%20self.fork_proc(channel%2C%20%26block)%0A%20%20%20%20%5B5%2C%20channel%5D%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20pid%2C%20channel%20%3D%20Proc.fork_proc(JsonChannel.new)%20do%20%7Cfork_channel%7C%0A%20%20%20%20fork_channel.read%0A%20%20end%0A%0Aend)

**Comment by jez** [comment]
Another example, from vinistock:

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3AItem%29.params%28%0A%20%20%20%20list%3A%20T%3A%3AArray%5BT.type_parameter%28%3AItem%29%5D%2C%0A%20%20%20%20block%3A%20T.proc.params%28arg0%3A%20T.type_parameter%28%3AItem%29%29.void%0A%20%20%29.void%0Aend%0Adef%20foo%28list%2C%20%26block%29%0Aend%0A%0Afoo%28%5B1%2C%202%2C%203%5D%29%20do%20%7Citem%7C%0A%20%20T.reveal_type%28item%29%0Aend%0A)

```ruby
# typed: true

extend T::Sig

sig do
  type_parameters(:Item).params(
    list: T::Array[T.type_parameter(:Item)],
    block: T.proc.params(arg0: T.type_parameter(:Item)).void
  ).void
end
def foo(list, &block)
end

foo([1, 2, 3]) do |item|
  T.reveal_type(item)
end

```

#### Observed output

```
editor.rb:15: Revealed type: <top> https://srb.help/7014
    15 |  T.reveal_type(item)
          ^^^^^^^^^^^^^^^^^^^
  Got <top> originating from:
    editor.rb:14:
    14 |foo([1, 2, 3]) do |item|
                           ^^^^
Errors: 1
```

#### Expected behavior

The type of the block parameter `item` in this case should be integer. The funny thing is that hovering over the `foo` invocation displays the correct type for the block's `arg0`, but for some reason inside the block the type information is lost.

**Comment by amomchilov** [comment]
This is awesome, thanks @jez!
