### ISSUE TITLE
Proc argument return type issus

### ISSUE THREAD

**Issue by bolshakov** [sorbet/sorbet#1100]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20do%20%0A%20%20type_parameters(%3AT)%0A%20%20%20%20.params(default%3A%20T.type_parameter(%3AT))%0A%20%20%20%20.returns(T.type_parameter(%3AT))%0Aend%0Adef%20return_value(default)%0A%20%20default%0Aend%0A%0Asig%20do%20%0A%20%20type_parameters(%3AT)%0A%20%20%20%20.params(default%3A%20T.proc.returns(T.type_parameter(%3AT)))%0A%20%20%20%20.returns(T.type_parameter(%3AT))%0Aend%0Adef%20return_block_call(%26default)%0A%20%20default.call%0Aend%0A%0Asig%20do%20%0A%20%20type_parameters(%3AT)%0A%20%20%20%20.params(default%3A%20T.proc.returns(T.type_parameter(%3AT)))%0A%20%20%20%20.returns(T.type_parameter(%3AT))%0Aend%0Adef%20return_lambda_call(default)%0A%20%20default.call%0Aend%0A%0A%23T.reveal_type(return_value(%22foo%22))%0A%23T.reveal_type(return_block_call%20%7B%20%22foo%22%20%7D)%0AT.reveal_type(return_lambda_call(-%3E%7B%20%22foo%22%20%7D)))

```ruby
# typed: true
extend T::Sig

sig do 
  type_parameters(:T)
    .params(default: T.proc.returns(T.type_parameter(:T)))
    .returns(T.type_parameter(:T))
end
def return_lambda_call(default)
  default.call
end

T.reveal_type(return_lambda_call(->{ "foo" }))
```

#### Observed output

```
editor.rb:34: Revealed type: T.untyped https://srb.help/7014
    34 |T.reveal_type(return_lambda_call(->{ "foo" }))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:34:
    34 |T.reveal_type(return_lambda_call(->{ "foo" }))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

```
editor.rb:33: Revealed type: String("foo") https://srb.help/7014
    33 |T.reveal_type(return_block_call { "foo" })
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:33:
    33 |T.reveal_type(return_block_call { "foo" })
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

**Comment by jez** [comment]
Sorbet does not do type inference for lambdas. To declare the type of a lambda, you'll need to annotate the lambda with a `T.let`:


```ruby
# typed: true
extend T::Sig

sig do 
  type_parameters(:T)
    .params(default: T.proc.returns(T.type_parameter(:T)))
    .returns(T.type_parameter(:T))
end
def return_lambda_call(default)
  default.call
end

fn = T.let(->{ "foo" }, T.proc.returns(String))
T.reveal_type(return_lambda_call(fn))
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%20%0A%20%20type_parameters(%3AT)%0A%20%20%20%20.params(default%3A%20T.proc.returns(T.type_parameter(%3AT)))%0A%20%20%20%20.returns(T.type_parameter(%3AT))%0Aend%0Adef%20return_lambda_call(default)%0A%20%20default.call%0Aend%0A%0Afn%20%3D%20T.let(-%3E%7B%20%22foo%22%20%7D%2C%20T.proc.returns(String))%0AT.reveal_type(return_lambda_call(fn)))
