### ISSUE TITLE
Allow automatic static checking of `new` on subclasses of `T::InexactStruct`

### ISSUE THREAD

**Issue by jeffcarbs** [sorbet/sorbet#1106]
### Problem

We've been using a `ValueObject` base class for a few years which has an interface identical to `T::Struct`. As we've adopted sorbet we removed the common implementation and just inherit from `T::InexactStruct`, so:
```ruby
class ValueObject < T::InexactStruct
  # custom functionality (e.g. #validate, #==)
end

class Period < ValueObject
  const :start_date, Date
end
```

I'm pretty excited about the automatic typing of `T::Struct.new` coming in #986 but it will only be available on direct subclasses of `T::Struct`. I understand (I think) this limitation is based on the implementation choice: synthesizing the sig for `initialize` will happen in the DSL pass so a) we must rely on actually seeing `T::Struct` being subclassed to know we can synthesize the sig and b) we only know about the props defined in that file.

### Proposed solution

It looks like `synthesizeInitialize` will get set to true [here](https://github.com/sorbet/sorbet/blob/093be99b968327a845d30581bbd1e19cce931f08/dsl/Prop.cc#L344-L350) if we're directly subclassing `T::Struct`. Could we support an alternate way to tell sorbet to synthesize initialize? I'd be happy to add some directive/flag to my value objects to avoid needing to manually define an initialize method for all of my value objects. For example:

```ruby
class Period < ValueObject
  T.synthesize_initialize_for_inexact_struct # Option 1
  # T.synthesize_initialize_from_props       # Option 2
  # include T::FinalStruct                   # Option 3 essentially saying that I won't subclass this anymore

  const :start_date, Date
end
```

I'm going to explore "Option 3" in a PR (see #1107). One con would be that this doesn't immediately surface the fact that it will only consider props defined in this file but I think sufficient documentation could address this.

Another proposal would be to maybe give my `ValueObject` the same property that it couldn't be subclassed and somehow tell sorbet to treat `ValueObject` the same as it would treat `T::Struct`?
```ruby
class ValueObject < T::InexactStruct
  def self.inherited(subclass)
    super(subclass)
    T::Private::ClassUtils.replace_method(subclass.singleton_class, :inherited) do |s|
      super(s)
      raise "#{self.name} is a subclass of T::Struct and cannot be subclassed"
    end
  end
end
```

And then in some configuration, maybe CLI?
```
srb tc --custom-struct-class=ValueObject
```
This feels a bit clunky though.

**Comment by azdavis** [comment]
As a slightly different flavor of workaround, would it work to refactor your code to do something like this?

```rb
module ValueObjectThings
  # ...
end

class Period < T::Struct
  include ValueObjectThings
  # ...
end
```

**Comment by jeffcarbs** [comment]
@azdavis - thanks for the suggestion! I've considered that and haven't ruled it out but I think would prefer the subclass approach. My thinking is that with:
```ruby
module ValueObjectThings
  # ...
end

class Foo < T::Struct
  include ValueObjectThings
  # ...
end
```
it's possible for someone to "forget" to `include ValueObjectThings` in which case things will behave subtly differently (e.g. we redefine `#==` so `Foo.new(x: 1) == Foo.new(x: 1)`). We could introduce a rubocop rule to enforce we always include this but it seems wrong to have the inclusion of critical behavior enforced by a linter.

**Comment by jez** [comment]
Given that we're trying to discourage use of `T::InexactStruct` (i.e., we wish we hadn't allowed non-final T::Struct subclasses to start with), I think the options that hack around synthesizing a constructor are not what we want.

It sounds like the biggest feature that you're trying to use inheritance for is value equality, which has an issue here: #1540 

Closing in favor of that one.
