### ISSUE TITLE
Kernel methods not avaiable for mixin modules

### ISSUE THREAD

**Issue by bmalinconico** [sorbet/sorbet#1109]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Foo%0A%20%20def%20bar%0A%20%20%20%20raise%20'foo'%0A%20%20end%0Aend%0A%0Aclass%20Fooer%0A%20%20include%20Foo%0Aend%0A%0AFooer.new.bar%20%23%20Raises%20an%20error%20when%20run)

```ruby
# typed: true
module Foo
  def bar
    raise 'foo'
  end
end

class Fooer
  include Foo
end

Fooer.new.bar # Raises an error when run
```

#### Observed output

```
editor.rb:4: Method raise does not exist on Foo https://srb.help/7003
     4 |    raise 'foo'
            ^^^^^^^^^^^
  Did you mean to `include Kernel` in this module?
    https://github.com/sorbet/sorbet/tree/90c20f728c528aa4a1a3dc1a137e4c9eae95716d/rbi/core/kernel.rbi#L870: Did you mean: Kernel#raise?
     870 |  def raise(arg0=T.unsafe(nil), arg1=T.unsafe(nil), arg2=T.unsafe(nil)); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

In real execution this code is perfectly valid, the call to the mixed-in method will raise an error.

#### Expected behavior

No error when running `typecheck`

Depending on the underlying system, this may be the same root cause as https://github.com/sorbet/sorbet/issues/397

**Comment by elliottt** [comment]
You should just need to `include Kernel` in the definition of `module Foo` to resolve this error during typechecking. For more information, see [including kernel](https://sorbet.org/docs/include-kernel.html)

**Comment by bmalinconico** [comment]
@elliottt Thanks for linking to that trouble shooting doc, my searching focused on others having the issue with `raise` not `Kernel`.

**Comment by paracycle** [comment]
@bmalinconico The reason why it is this was is because this would fail at runtime (note the subclassing from `BasicObject` here):
```ruby
# typed: true
module Foo
  def bar
    raise 'foo'
  end
end

class Baz < BasicObject
  include ::Foo
end

Baz.new.bar 
```
Basically, Sorbet cannot guarantee that the module would always be included into something that inherits from `Object`, so it tries to be safe.

**Comment by jez** [comment]
Because this is expected, documented behavior, I'm closing.

**Comment by nbdavies** [comment]
If there's no real danger of any of an app's modules being included in a basic object, is there a way to include Kernel in all modules at once? (Rather than the overhead of including `include Kernel` in every module definition)
