### ISSUE TITLE
Definition missing for Integer#to_d

### ISSUE THREAD

**Issue by frewsxcv** [sorbet/sorbet#1117]
#### Input

https://devdocs.io/ruby~2.5/integer#method-i-to_d

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strong%0A%0Arequire%20'bigdecimal'%0Arequire%20'bigdecimal%2Futil'%0A%0A42.to_d%20%20%20%23%20%3D%3E%200.42e2)

```ruby
# typed: strong

require 'bigdecimal'
require 'bigdecimal/util'

42.to_d   # => 0.42e2
```

#### Observed output

```
editor.rb:6: Method to_d does not exist on Integer component of Integer(42) https://srb.help/7003
     6 |42.to_d   # => 0.42e2
        ^^^^^^^
```

#### Expected behavior

It should typecheck

**Comment by elliottt** [comment]
`Integer#to_d` is provided by a monkey-patch from `bigdecimal/utils`. It's not entirely clear how we should treat monkey-patches in sorbet: currently all rbis for the stdlib are loaded at startup, so making this change would put the monkey-patch in scope even if `bigdecimal/utils` was not required.

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong

It's the same for `to_set` on Array. I think as long as the monkey patch is defined by requiring something in the standard library, it's fine to have it.

**Comment by frewsxcv** [comment]
this was resolved in https://github.com/sorbet/sorbet/pull/3027
