### ISSUE TITLE
Autocorrect untyped constants when RHS is "obvious"

### ISSUE THREAD

**Issue by carl-stripe** [sorbet/sorbet#1127]
### Problem

One primary reason many `typed: true` files in our legacy codebase cannot be upgraded to `typed: strict` is because there are many untyped constants in those files. However, these constants typically have "obvious" types that a computer could add for us (i.e., the `T.reveal_type` type is almost certainly the right one).

A few folks have recently spent a lot of time manually typing those constants, but I'd like Sorbet to help us automate this task.

### Proposed solution

I think we should augment `sorbet -a` to add typing annotations to constants when it can infer them with high confidence, optionally when that typing annotation would help the file achieve `typed: strict`.

**Comment by jez** [comment]
Fixed in #1469
