### ISSUE TITLE
T.proc.bind does not work with lambda

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1143]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20A%0A%20%20class%20B%0A%20%20end%0Aend%0Asig%20do%0A%20%20params(%0A%20%20%20%20blk%3A%20T.proc.bind(A%3A%3AB).params(args%3A%20T.untyped).returns(Integer)%0A%20%20)%0A%20%20.returns(String)%0Aend%0Adef%20foo(blk)%0A%20%20%22Done%22%0Aend%0A%0Afoo%20-%3E%20(a)%20%7B%0A%20%20T.reveal_type(self)%0A%20%20return%201%0A%7D)

```ruby
# typed: true
extend T::Sig

module A
  class B
  end
end
sig do
  params(
    blk: T.proc.bind(A::B).params(args: T.untyped).returns(Integer)
  )
  .returns(String)
end
def foo(blk)
  "Done"
end

foo -> (a) {
  T.reveal_type(self)
  return 1
}
```
#### Observed output

```
editor.rb:19: Revealed type: T.class_of(<root>) https://srb.help/7014
    19 |  T.reveal_type(self)
          ^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:2:
     2 |extend T::Sig
     3 |
     4 |module A
     5 |  class B
     6 |  end
       |...
    17 |
    18 |foo -> (a) {
    19 |  T.reveal_type(self)
    20 |  return 1
    21 |}
Errors: 1
```

#### Expected behavior

```ruby
editor.rb:19: Revealed type: A::B https://srb.help/7014
    19 |  T.reveal_type(self)
          ^^^^^^^^^^^^^^^^^^^
```
- - -

**Comment by DarkDimius** [comment]
I currently don't envision a way to fix this. Lambda's can be constructed in absence of the send and thus don't see the `T.bind`. They can also be passed to multiple locations and thus we need a single type for them.
Unless somebody proposed a (implementable & maitainable & fast) way to fix this, this is a "wontfix"

**Comment by DarkDimius** [comment]
One potential way is to fix this is introduce a replacement for `->` that's sorbet compatible, similarly how we already did with `T::Array`. I think this should effectively allow us to support arbitrary typed lambdas on-par with blocks.

**Comment by manhhung741** [comment]
That’d be cool. It might help solving another issue I filed about variable number of argument in proc/lambda too
