### ISSUE TITLE
`srb init` hangs in ruby 2.3.0 and 2.3.1 with activesupport 5.x

### ISSUE THREAD

**Issue by pariser** [sorbet/sorbet#1145]
#### Input

When running Ruby 2.3.0 or 2.3.1, `srb init` hangs during the `GemGeneratorTracepoint` step when executed on a project that depends on ActiveSupport 5.0.1 or above.

This does not happen in Ruby 2.2.8 or Ruby 2.3.2, nor does it happen in ActiveSupport 5.0.0 or earlier. ActiveSupport 6.x is still not fully released (as of issue reporting time) but will require Ruby 2.5+ and thus won't be affected. I have only tested this on OSX so can't speak to whether this also happens on other platforms.

The issue stems from [line 71 of `GemGeneratorTracepoint::TracepointSerializer`](                   https://github.com/pariser/sorbet/blob/b8b1546231bd45836c8698cf21c5bb41240f9782/gems/sorbet/lib/gem-generator-tracepoint/tracepoint_serializer.rb#L71) when it executes on `ActiveSupport::Deprecation` class with class method `:new`.

Specifically, this executes `ActiveSupport::Deprecation.method(:new)`. If you open up a ruby 2.3.0 or 2.3.1 console, `require 'active_support'` and execute the previous command, you'll see that this code causes the ruby process to become unresponsive. It also does not permit interactive debuggers stepping into the method call to introspect the behavior.

Digging into the internals of `ActiveSupport::Deprecation` and reducing as much cruft as possible, I've been able to reproduce the issue with the following snippet:
```ruby
# This class mimics the behavior of `ActiveSupport::Deprecation` class
class Foo
  private_class_method :new
  singleton_class.prepend(Module.new)
  public_class_method :new
end

# Executing the following command will halt the ruby process
# This command is effectively what's executed during Sorbet's TracepointSerializer
Foo.method(:new)
```
Note that my debugging steps and overall logic chain can be found [in this public gist](https://gist.github.com/pariser/691ff2e5e189683c762393add91ce408).

See [this thread on Sorbet's slack](https://sorbet-ruby.slack.com/archives/CHN2L03NH/p1561131945270600) for additional context. I'd love help figuring out a relevant workaround that doesn't involve upgrading my ruby version. Thanks kindly!

#### Observed output

Upon running `srb init` the process hangs indefinitely and needs a `kill -9` issued to stop the process.

#### Expected behavior

Sorbet init should not halt.

**Comment by DarkDimius** [comment]
Thank you for a lot of research that went into reproducing and minimizing this bug as well as finding necessary environment to trigger it.
Super impressive!

**Comment by jasnow** [comment]
@pariser - Can you share your repo mentioned above?

**Comment by jasnow** [comment]
I also reproduced it (in this repo: https://github.com/jasnow/rails_app5_2_231).
