### ISSUE TITLE
Nilable block params does not work consistently

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1147]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params(block%3A%20T.nilable(T.proc.void)).returns(String)%20%7D%0Adef%20with_block(block)%0A%20%20'asdf'%0Aend%0A%0AT.reveal_type(with_block())%0AT.reveal_type(with_block%20do%20'asd'%20end)%0A%0Aclass%20Site%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(a%3A%20T.untyped%2C%20block%3A%20T.nilable(T.proc.void)).returns(String)%20%7D%0A%20%20def%20self.where(*a%2C%20block)%0A%20%20%20%20%22String%22%0A%20%20end%0Aend%0A%0AT.reveal_type(Site.where(id%3A%201))%0AT.reveal_type(Site.where(id%3A%201)%20%7B%20'23'%20%7D%20))

```ruby
# typed: true

extend T::Sig

sig { params(block: T.nilable(T.proc.void)).returns(String) }
def with_block(block)
  'asdf'
end

T.reveal_type(with_block())
T.reveal_type(with_block do 'asd' end)

class Site
  extend T::Sig

  sig { params(a: T.untyped, block: T.nilable(T.proc.void)).returns(String) }
  def self.where(*a, block)
    "String"
  end
end

T.reveal_type(Site.where(id: 1))
T.reveal_type(Site.where(id: 1) { '23' } )
```

#### Observed output

```
editor.rb:10: Not enough arguments provided for method Object#with_block. Expected: 1, got: 0 https://srb.help/7004
    10 |T.reveal_type(with_block())
                      ^^^^^^^^^^^^
    editor.rb:6: Object#with_block defined here
     6 |def with_block(block)
        ^^^^^^^^^^^^^^^^^^^^^

editor.rb:10: Revealed type: String https://srb.help/7014
    10 |T.reveal_type(with_block())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:10:
    10 |T.reveal_type(with_block())
                      ^^^^^^^^^^^^

editor.rb:11: Not enough arguments provided for method Object#with_block. Expected: 1, got: 0 https://srb.help/7004
    11 |T.reveal_type(with_block do 'asd' end)
                      ^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:6: Object#with_block defined here
     6 |def with_block(block)
        ^^^^^^^^^^^^^^^^^^^^^

editor.rb:11: Revealed type: String https://srb.help/7014
    11 |T.reveal_type(with_block do 'asd' end)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:11:
    11 |T.reveal_type(with_block do 'asd' end)
                      ^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:22: Revealed type: String https://srb.help/7014
    22 |T.reveal_type(Site.where(id: 1))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:22:
    22 |T.reveal_type(Site.where(id: 1))
                      ^^^^^^^^^^^^^^^^^

editor.rb:23: Revealed type: String https://srb.help/7014
    23 |T.reveal_type(Site.where(id: 1) { '23' } )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:23:
    23 |T.reveal_type(Site.where(id: 1) { '23' } )
```

#### Expected behavior

It should work consistently. Either `method(block)` works in both cases or not work in both cases.

- - -

Using `&block` works in both cases

**Comment by DarkDimius** [comment]
Hi Harry, the code you've submitted doesn't work in Ruby and Sorbet correctly complains on it:
```
[1] pry(main)> def with_block(block)
[1] pry(main)*   'asdf'
[1] pry(main)* end
=> :with_block
[2] pry(main)> with_block()
ArgumentError: wrong number of arguments (given 0, expected 1)
from (pry):1:in `with_block'
```
(I think you're missing `&` from `def with_block(&block)`)

**Comment by DarkDimius** [comment]
Note that the "where" example actually _does_ evaluate, it just doesn't do what you seem to believe it does :-) `a` will be `nil` and block will be `{id: 1}`

**Comment by manhhung741** [comment]
> (I think you're missing & from def with_block(&block))

Yeah, it should have `&`. However, I was wondering why it didn't complain for the second case. 

> Note that the "where" example actually does evaluate, it just doesn't do what you seem to believe it does :-) a will be nil and block will be {id: 1}

Why is `a` nil and not `{id: 1}`? Will this work properly? [sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0A%0Aclass%20Site%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(args%3A%20T.untyped%2C%20block%3A%20T.nilable(T.proc.void)).returns(String)%20%7D%0A%20%20def%20self.where(*args%2C%20%26block)%0A%20%20%20%20%22String%22%0A%20%20end%0Aend%0A%0AT.reveal_type(Site.where(id%3A%201))%0AT.reveal_type(Site.where(id%3A%201)%20do%20%0A%20%20T.reveal_type(self)%0Aend))

**Comment by DarkDimius** [comment]
> Why is a nil and not {id: 1}? 

because that's how ruby works :-)
```
[7] pry(main)> def baz(*a, s)
[7] pry(main)*   puts "a = #{a}"
[7] pry(main)*   puts "s = #{s}"
[7] pry(main)* end
=> :baz
[8] pry(main)> baz(1)
a = []
s = 1
=> nil

baz(id: 2)
a = []
s = {:id=>2}
=> nil
```

> Will this work properly? 

sorbet & pry seem to agree that "yes" :-)

**Comment by manhhung741** [comment]
Ah ok. The catchall `*a` is always assigned later than the `block`. Ruby
reorders the params and it kind of make sense. Block is treated
differently, thats why `&block` work.

Sorry for my confusion!

**Comment by DarkDimius** [comment]
No worries, most folks on our team are past the point when we're no longer smarter than Sorbet. At the same time we get all sorts of weird reports so we ourselves get confused constantly ;-)
