### ISSUE TITLE
Shapes with optional key/value pairs

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1160]
### Problem

I'm trying to type an `options` Hash parameter in a method, with various key/value pairs. Currently, I'm using a [Shape](https://sorbet.org/docs/shapes) to do this.

```ruby
# Create a new Wait instance
#
# @param [Hash] opts Options for this instance
# @option opts [Numeric] :timeout (5) Seconds to wait before timing out.
# @option opts [Numeric] :interval (0.2) Seconds to sleep between polls.
# @option opts [String] :message Exception message if timed out.
# @option opts [Array, Exception] :ignore Exceptions to ignore while polling (default: Error::NoSuchElementError)
sig do
  params(opts: {
    timeout: Numeric,
    interval: Integer,
    message: String,
    ignore: T.any(T::Array, Exception)
  }).void
end
def initialize(opts = {})
  # If there's a timeout, use it. Otherwise, use the DEFAULT_TIMEOUT constant.
  @timeout  = opts.fetch(:timeout, DEFAULT_TIMEOUT)
  @interval = opts.fetch(:interval, DEFAULT_INTERVAL)
  @message  = opts[:message]
  @ignored  = Array(opts[:ignore] || Error::NoSuchElementError)
end
```

However, the `timeout`, `interval`, and `ignore` values are supposed to be optional. Sorbet doesn't have a way for me to tell it that they're optional, it assumes all key/value pairs in a Shape are required. So when I try to type this Hash with a Shape, Sorbet throws errors if I'm not providing all four key/value pairs all the time.

### Proposed solution

In [Typed Structs](https://sorbet.org/docs/tstruct), there's a way to provide a default value so the parameter becomes optional:

```ruby
class MyStruct < T::Struct
  const :x, Float, default: 0.5
end
```

I'd like some way to do this in a Shape, though I'm not really sure how it could be accomplished within the existing API, since it's currently defined as just a normal Ruby Hash.

The best I can come up with would be letting the value in the Shape definition be a hash with a `type` and a `default`:

```ruby
# Before
{ symbol1: Integer, symbol2: Symbol }

# After, symbol1 is now optional since a default is provided.
{ symbol1: { type: Integer, default: 2 }, symbol2: Symbol }
```

This has the downside that it would make it impossible - or at least significantly more difficult - to nest Shapes within Shapes.

**Comment by jez** [comment]
We consider tuple and shape types "best effort," as they are currently very limited and unlikely to improve in the near or even medium term. Specifically this feature to have optional keys in a shape is something we are unlikely to support.

As you mention, to get good type safety with optional keys, we recommend `T::Struct`, or just using a method with default arguments directly:

```ruby
# typed: true
extend T::Sig

DEFAULT_TIMEOUT = T.unsafe(nil)
DEFAULT_INTERVAL = T.unsafe(nil)

class Error::NoSuchElementError < Exception; end

sig do
  params(
    timeout: Numeric,
    interval: Integer,
    message: String,
    ignore: T.any(T::Array, T.class_of(Exception))
 ).void
end
def initialize(
  timeout: DEFAULT_TIMEOUT,
  interval: DEFAULT_INTERVAL,
  message:,
  ignore: Error::NoSuchElementError
)
  @timeout  = timeout
  @interval = interval
  @message  = message
  @ignored  = ignore
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0ADEFAULT_TIMEOUT%20%3D%20T.unsafe(nil)%0ADEFAULT_INTERVAL%20%3D%20T.unsafe(nil)%0A%0Aclass%20Error%3A%3ANoSuchElementError%20%3C%20Exception%3B%20end%0A%0Asig%20do%0A%20%20params(%0A%20%20%20%20timeout%3A%20Numeric%2C%0A%20%20%20%20interval%3A%20Integer%2C%0A%20%20%20%20message%3A%20String%2C%0A%20%20%20%20ignore%3A%20T.any(T%3A%3AArray%2C%20T.class_of(Exception))%0A%20).void%0Aend%0Adef%20initialize(%0A%20%20timeout%3A%20DEFAULT_TIMEOUT%2C%0A%20%20interval%3A%20DEFAULT_INTERVAL%2C%0A%20%20message%3A%2C%0A%20%20ignore%3A%20Error%3A%3ANoSuchElementError%0A)%0A%20%20%40timeout%20%20%3D%20timeout%0A%20%20%40interval%20%3D%20interval%0A%20%20%40message%20%20%3D%20message%0A%20%20%40ignored%20%20%3D%20ignore%0Aend)

**Comment by connorshea** [comment]
`options` Hashes are a really common pattern throughout the Ruby community, and even show up pretty often in the stdlib ([DateTime](https://github.com/sorbet/sorbet/blob/2275752e51604acfb79b30a0a96debc996c089d9/rbi/stdlib/date_time.rbi#L74), [Tempfile](https://github.com/sorbet/sorbet/blob/2275752e51604acfb79b30a0a96debc996c089d9/rbi/stdlib/tempfile.rbi#L29), [Regexp](https://github.com/sorbet/sorbet/blob/2275752e51604acfb79b30a0a96debc996c089d9/rbi/core/regexp.rbi#L85), etc.).

While I agree Structs are preferable for type safety in new code, when typing existing gems that need to consider backwards compatibility, switching to a Struct isn't really viable. Users are already passing hashes into the methods, and a breaking change just to get some improved typing from Sorbet is highly unlikely to happen. Just typing it as a `Hash` _works_, but it doesn't provide Sorbet the insights to automatically suggest keys when calling the code, which I think is a really important part of the benefit of Sorbet.

Ultimately, I respect the decision, but I really hope you eventually reconsider. :bow:

**Comment by connorshea** [comment]
I thought of a better syntax for this if anyone implements it in the future, and I don't have a better place to share it, so I guess I'll put it here :)

```ruby
{ symbol1: T.optional(Integer, default: 2), symbol2: Symbol }
```

**Comment by rattrayalex** [comment]
@jez I'm not sure what qualifies as "the medium term", but does the Sorbet team have the bandwidth to reconsider this? `T::Struct` is not germane in several cases where `Shape` is more idiomatic or applicable.

I shared [this example](https://github.com/microsoft/pylance-release/issues/2508#issuecomment-1078272992) on the similar topic of comparing Python's `TypedDict` (like a Shape) to `dataclass` (like a `T::Struct`). 

Compare these:
```rb
require 'myapi'

client = MyAPI::Client.new()

params = MyAPI::CustomerCreateParams(
  name: "Jake",
  employer: MyAPI::CustomerCreateParams::Employer(
    name: "Stripe",
    address: MyAPI::CustomerCreateParams::Employer::Address(
      line1: "123 Main St",
      # …
    ),
  )
)
client.customers.create(params, timeout=10)
```
With Shapes instead:
```rb
client.customers.create({
  name: "Jake",
  employer: {
    name: "Stripe",
    address: {
      line1: "123 Main St",
    }
  }
}, timeout: 10)
```

In my quest to convert non-Sorbet-using Rubyists to Sorbet-using Rubyists, I do not think I can offer an API like the former for a library and win folks over. But the latter can't be typed with Sorbet today, primarily because of this issue, and well-typed params (especially autocomplete & docstrings-on-hover) are the most compelling value-add for folks adopting a typed library (especially type-skeptics).

**Comment by rattrayalex** [comment]
Re; implementation, a suggestion inspired by Python's `TypedDict`:

```rb
T::Shape({
  foo: String,
  bar: T.required(String),
}, total: false)

# equivalent to:
T::Shape({
  foo: T.optional(String),
  bar: String,
})
```

**Comment by sentientmonkey** [comment]
Also adding a ➕ to reconsider here. We have a React/Typescript frontend that talks to a Rails app with Sorbet sprinkled in. We have a few tree objects that we pass from front-end to backend, and save as json in Postgresql.

In typescript, I can define an interface to help the shape for these objects.

Here's an example json value for one of these objects passed back and forth over the REST API:

```json
{ 
  "type": "mention",
  "item": {
     "id": "1",
      "groupId": "groupOne"
    },
    "children": [
      { "text": ""}
    ]
}
```

In typescript, the interface for this object is:

```typescript
export interface MentionNode {
  type: 'mention';
  item: { id: string; groupId?: string };
  children: [{ text: '' }];
}
```

In ruby, we have a small helper class that makes it easier to generate this json.

```ruby
class Tree
  class Node::Mention
    delegate :as_json, to: :to_tree

    def initialize(id, group_id: nil)
      @id = id
      @group_id = group_id
    end

    def to_tree
      item = { id: @id }
      item.merge!({ groupId: @group_id }) if @group_id.present?
      { type: 'mention', item: item, children: [{ text: '' }] }
    end
  end
end
```

In adding Sorbet types, We'd like to define a similar `MentionNode` to help describe what the json structure looks that matches the Typescript definition. I don't quite know how to specify literal values just yet in Sorbet, so I am missing those.

The best I can come up with is providing a `T.any` with and without the optional key.

```ruby
# typed: true
class Tree
  class Node::Mention
    extend T::Sig

    MentionNode = T.type_alias do
      {
        type: String,
        item: T.any({ id: String }, { id: String, groupId: String }),
        children: [{ text: String }],
      }
    end

    sig { returns(MentionNode) }
    def to_tree; end
  end
end
```

But this isn't very sustainable as we add more optional params. A `T.optional` syntax-wise would be pretty nice, since we don't have the `?` Optional Parameter syntax of Typescript), but I'm not sure what limitations Sorbet has here for matching Shape.
 
 ```ruby
 MentionNode = T.type_alias do
  {
    type: String,
    item: { id: String, groupId: T.optional(String) }),
    children: [{ text: String }],
  }
end
 ```

**Comment by abraham** [comment]
I would find this useful adding shims describing existing dependencies. I think it's fairly common for gems to return a hash with a grabbag of values. I had hoped using `T.any` would work but [everything is marked as `T.untyped`](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0AFoo%20%3D%20T.type_alias%20do%0A%20%20T.any%28%0A%20%20%20%20%7B%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20city%3A%20String%2C%20%0A%20%20%20%20%20%20region%3A%20String%2C%0A%20%20%20%20%7D%0A%20%20%29%0Aend%0A%0Afoo%20%3D%20T.let%28%7B%7D%2C%20Foo%29%0A%0AT.reveal_type%28foo%5B%3Acity%5D%29%0AT.reveal_type%28foo%5B%3Aregion%5D%29%0AT.reveal_type%28foo%5B%3Aother%5D%29).

```ruby
Foo = T.type_alias do
  T.any(
    {},
    {
      city: String, 
      region: String,
    }
  )
end
```
