### ISSUE TITLE
Sorbet doesn't type the sigs of inherited methods based on super classes (it used to)

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1162]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).returns(String)%7D%0A%20%20def%20bar(x)%0A%20%20%20%20x.to_s%0A%20%20end%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20def%20bar(x)%0A%20%20%20%20super%0A%20%20end%0Aend%0A%0AT.reveal_type(B.new.bar(12)))

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: Integer).returns(String)}
  def bar(x)
    x.to_s
  end
end

class B < A
  def bar(x)
    super
  end
end

T.reveal_type(B.new.bar(12))
```

#### Observed output

```
editor.rb:17: Revealed type: T.untyped https://srb.help/7014
    17 |T.reveal_type(B.new.bar(12))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:17:
    17 |T.reveal_type(B.new.bar(12))
                      ^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Sorbet should assume the sig from the parent class, unless it's overridden in the child class.

- - -

It used to work at an earlier version of sorbet, but not at the recent release.

**Comment by jez** [comment]
> It used to work at an earlier version of sorbet, but not at the recent release.

This has never been the case. If a method is mentioned in a class and does not have a sig, it does not have types. Even if it dispatches to `super`.

Sorbet learns about types in three phases:

1. figure out all the constants. these are needed by the sigs
2. figure out all the sigs. these are needed by the methods
3. use the constants and the sigs to type check the method

This process always flows forwards—at no later phase do we go back and use something we learned to invalidate what we learned by an earlier phase.

**Comment by md-work** [comment]
Nevertheless, this kind of "inheritance inference" would be very handy.

Is there any chance, this might be added somehow in future?
E.g. by loosening that step 1. > 2. > 3. scheme?

Alternatively, what about an override/implementation syntax for methods defined with overridable/abstract?
E.g.:
```
class A
  extend T::Sig

  sig {overridable.params(n: Integer).returns(Integer)}
  def foo(n); n+1; end
end


class B < A
  # Mind the missing params and return type.
  # Proposal is, to inherit these from the overridden method.
  sig {override}
  def foo(n); n+1; end
end
```
