### ISSUE TITLE
Issues with srb tc reading from sorbet generated gems rbi

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1184]
#### Input

```ruby
-- site.rb
class Site < ActiveRecord::Base # actually it's ApplicationRecord, but ApplicationRecord subclass ActiveRecord::Base
end

-- in gems/activerecord.rbi
class ActiveRecord::Base
  include ActiveRecord::AttributeMethods::Dirty
end

module ActiveRecord::AttributeMethods::Dirty
  def saved_change_to_attribute?(attr_name, **options); end
end
```

#### Observed output

```
./sorbet-test.rb:10: Method saved_change_to_attribute? does not exist on Site https://srb.help/7003
    10 |T.reveal_type(Site.last!.saved_change_to_attribute?(:name))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

#### Expected behavior

No error because the method is present in a Site object
- - -

**Comment by manhhung741** [comment]
Found out that some gems file was marked as `# typed: ingore` due to `srb tc suggest-type`

**Comment by jez** [comment]
@manhhung741 do you have an idea why the RBI was being ignored? We should probably make it so that no autogenerated RBI ever introduces an error in `typed: false`.

**Comment by manhhung741** [comment]
It's probably my fault when I run `srb rbi suggest-typed` when it was in an error state. 
I think it may be a good idea to not let this changes generated files.

More context:
- We add "Elem" to ActiveRecord::Base
- Some generated code define classes that subclass ActiveRecord::Base
- Running `srb rbi suggest-typed` mark those files and dependent files as `# typed: ignore`

Separately, I also have an issue with the `Elem = type_member(fixed: ...)` affecting `srb init`. I wonder why subclasses can't inherit this attribute. If it isn't possible, what workaround can I apply?
