### ISSUE TITLE
Can't bundle install sorbet

### ISSUE THREAD

**Issue by ianklatzco** [sorbet/sorbet#1200]
Pretty new to the Ruby ecosystem, so apologies if I'm missing something trivial.

I started following the [Adopting Sorbet](https://sorbet.org/docs/adopting) page and tried setting up my Gemfile as follows:

```
source 'https://rubygems.org'
gem 'sinatra'

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
```

I run `bundle install` and get **the following error**:
```
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Could not find sorbet-static-0.4.4387-universal-darwin-14 in any of the sources
```
OS is mac, 10.14.4.

Output of `rbenv local`:
```
2.6.3
```

**Comment by DarkDimius** [comment]
https://buildkite.com/sorbet/sorbet/builds/3973#472ebcad-323c-41cf-a9b7-e2840db48786
RubyGems 502'd when we were publishing

Try using `0.4.4386`

**Comment by jez** [comment]
specifically:

```ruby
source 'https://rubygems.org'
gem 'sinatra'

gem 'sorbet', '0.4.4386', :group => :development
gem 'sorbet-runtime', '0.4.4386'
```

**Comment by ianklatzco** [comment]
that fixed it. thanks for the specific instruction! helps me a lot as a newcomer c:

**Comment by phansch** [comment]
I also ran into this just now on Travis CI, because I did not specify a specific version. It seems like a lot of linux releases are missing on rubygems: https://rubygems.org/gems/sorbet-static/versions.
