### ISSUE TITLE
A command to clear sorbet existing cache, like `srb rbi clear-cache`

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1205]
### Problem

I update `sorbet-rails` gem and people upgrading it may run into problem with sorbet's existing cache. I remove the `rbi/` folder from the gem and sorbet doesn't detect that, instead, it raises error.

### Proposed solution

A command to clear sorbet existing cache, like `srb rbi clear-cache`

**Comment by jez** [comment]
It seems to me that this is a bug. I think we're computing the list of `rbi/` folders that ship inside a project's gems and cache it based on an md5 hash of the `Gemfile.lock`. In the cases where the weird caching behavior happens, is the `Gemfile.lock`'s md5 changing?

**Comment by manhhung741** [comment]
It’s been awhile & I no longer ship rbis in `rbi` folder so I can’t confirm
the behavior. Please feel free to close this issue.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
