### ISSUE TITLE
When a gem remove `rbi/` folder, sorbet will raise error

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1206]
#### Input

1. Remove `rbi/` folder from `sorbet-rails`. 
2. Reinstall the gem.
3. Run `srb tc`

#### Observed output

It raises error: "cannot find sorbet-rails/rbi/` folder 

#### Expected behavior

It shouldn't raise error at all, by rebuilding the cache due to Gemfile change.. 
Or there should be an easy way to resolve the error  (eg `srb rbi clear-cache`)
- - -

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
