### ISSUE TITLE
Singleton class objects and typed instance variables

### ISSUE THREAD

**Issue by gmalette** [sorbet/sorbet#121]
[Sorbet.run example here](https://sorbet.run/#class%20A%0A%20%20class%20%3C%3C%20self%0A%20%20%20%20extend(T%3A%3ASig)%0A%20%20%20%20%0A%20%20%20%20sig%20%7B%20returns(A)%20%7D%0A%20%20%20%20def%20current%0A%20%20%20%20%20%20%40current%20%7C%7C%3D%20T.let(A.new%2C%20A)%0A%20%20%20%20end%0A%20%20end%0Aend)

```ruby
class A
  class << self
    extend(T::Sig)
    
    sig { returns(A) }
    def current
      @current ||= T.let(A.new, A)
    end
  end
end
```

```
-e:7: Instance variables must be declared inside `initialize` 
     7 |      @current ||= T.let(A.new, A)
              ^^^^^^^^
```

Singleton classes don't use the `initialize` method, making it impossible (?) to type ivars. I'm not sure why all ivars must be declared in the `initialize` method for all object, but if this reason still holds, should class objects be exempted?

**Comment by jez** [comment]
I'm going to call this closed now that instance variables can be declared outside of initialize as long as they're nilable (https://sorbet.org/docs/type-annotations#declaring-class-and-instance-variables)

**Comment by gmalette** [comment]
Perfect! Thanks!
