### ISSUE TITLE
Use T.untyped as the default type argument for all enumerable generics, not just Array and Hash

### ISSUE THREAD

**Issue by AaronC81** [sorbet/sorbet#1220]
### Problem

Sorbet has a selection of enumerable generic types, all documented [here](https://sorbet.org/docs/stdlib-generics), including common ones like `T::Array` and `T::Hash` and also less common ones such as `T::Set` or `T::Range`.

As mentioned in the docs, if `T::Array` or `T::Hash` are not given type parameters, they default to `T.untyped`:

> Inside a sig, just writing `Array` or `Hash` will be treated as `T::Array[T.untyped]` and `T::Hash[T.untyped, T.untyped]` respectively.

However, this behaviour exists only for `Array` and `Hash`, and not for the other generic types which Sorbet supports. If this signature is permitted:

```ruby
sig { returns(Array) }
def bar; end
```

Then this also should be:

```ruby
sig { returns(Range) }
def bar; end
```

### Proposed solution

All supported enumerable generic types have their arguments defaulted to `T.untyped`, even if used without the `T::` prefix:

  - `Array` -> `T::Array[T.untyped]` _(already implemented)_
  - `Hash` -> `T::Hash[T.untyped, T.untyped]` _(already implemented)_
  - `Set` -> `T::Set[T.untyped]` _(already implemented)_
  - `Enumerable` -> `T::Enumerable[T.untyped]`
  - `Enumerator` -> `T::Enumerator[T.untyped]`
  - `Range` -> `T::Range[T.untyped]`

**Comment by connorshea** [comment]
Actually, looking at this it seems like it should _already_ work that way, but for some reason it doesn't: https://github.com/sorbet/sorbet/blob/88ccf2d5dcbf29e53a3d11dde965cd252cb7782c/gems/sorbet-runtime/lib/types/utils.rb#L6-L33

Either it's hitting the T::Types::Base bit at the start or there's some other place where the coercion needs to be used that I'm not finding.

**Comment by connorshea** [comment]
It looks like this actually does work for Sets as well.

```ruby
# typed: true
class Test
  extend T::Sig

  sig do
    params(
      hash: Hash,
      array: Array,
      enumerable: Enumerable,
      enumerator: Enumerator,
      set: Set,
      range: Range
    ).void
  end
  def method_name(hash, array, enumerable, enumerator, set, range)
    puts hash
    puts array
    puts enumerable
    puts enumerator
    puts set
    puts range
  end
end

enumerator = %w(one two three).each

Test.new.method_name(
  {key: 'value'},
  [1, 2, 3],
  [1, 2, 3],
  enumerator,
  Set[1, 2],
  1..3
)
```

[See on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Test%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20hash%3A%20Hash%2C%0A%20%20%20%20%20%20array%3A%20Array%2C%0A%20%20%20%20%20%20enumerable%3A%20Enumerable%2C%0A%20%20%20%20%20%20enumerator%3A%20Enumerator%2C%0A%20%20%20%20%20%20set%3A%20Set%2C%0A%20%20%20%20%20%20range%3A%20Range%0A%20%20%20%20).void%0A%20%20end%0A%20%20def%20method_name(hash%2C%20array%2C%20enumerable%2C%20enumerator%2C%20set%2C%20range)%0A%20%20%20%20puts%20hash%0A%20%20%20%20puts%20array%0A%20%20%20%20puts%20enumerable%0A%20%20%20%20puts%20enumerator%0A%20%20%20%20puts%20set%0A%20%20%20%20puts%20range%0A%20%20end%0Aend%0A%0Aenumerator%20%3D%20%25w(one%20two%20three).each%0A%0ATest.new.method_name(%0A%20%20%7Bkey%3A%20'value'%7D%2C%0A%20%20%5B1%2C%202%2C%203%5D%2C%0A%20%20%5B1%2C%202%2C%203%5D%2C%0A%20%20enumerator%2C%0A%20%20Set%5B1%2C%202%5D%2C%0A%20%201..3%0A))

**Comment by AaronC81** [comment]
Ah, good find - I'll update the issue.

**Comment by connorshea** [comment]
It looks like the errors are silenced here when they apply to certain specific types, note Array, Hash, and Set being included but not the other 3: https://github.com/sorbet/sorbet/blob/29671ccab58ab37daa8fb478494c3af42170ee08/resolver/type_syntax.cc#L555
