### ISSUE TITLE
Add a script to help the new test/update test workflow for snapshot tests

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#1221]
### Problem
Adding a new snapshot test is difficult now, as it requires that you have already populated the `expected` directory if you need one.

### Proposed solution
Add a script that uses a combination of `@gems//bundler:bundle` and the `//gems/sorbet/test/snapshot:actual_*/actual.tar.gz` targets to bootstrap a new `expected` directory from a minimal example test. This could subsume the functionality in `tools/scripts/update_exp_files.sh`.

**Comment by jez** [comment]
https://sorbet.org/blog/2022/07/27/srb-tapioca
