### ISSUE TITLE
Debugging snapshot tests 

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#1222]
### Problem
After switching the snapshot tests to bazel, we lost the functionality to attach a debugger.

### Proposed solution
Modify `//gems/sorbet/test/snapshot/run_one_bazel.sh` to be aware of `bindings.pry`, and have some environmental switch to know when it's being run in that mode.

**Comment by jez** [comment]
https://sorbet.org/blog/2022/07/27/srb-tapioca
