### ISSUE TITLE
Sorbet doesn't notice gems defined in gemspec file

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1238]
#### Input

I've created an example repository to demonstrate the problem: https://github.com/connorshea/sorbet-gemspec-issue-example

Note how the `yard.rbi` file changes with [this commit that adds yard explicitly in the Gemfile](https://github.com/connorshea/sorbet-gemspec-issue-example/commit/ffe6b7be32772278a365349c065736d70716f2d3).

If you use a gemspec to define dependencies, instead of defining the dependencies in a `Gemfile` explicitly, Sorbet (I suspect `gem_loader.rb` specifically) doesn't seem to find as many module definitions. I assume this is because `gem_loader.rb` for whatever reason doesn't handle the `gemspec` keyword correctly in a Gemfile.

Works:

```ruby
# Gemfile
source "https://rubygems.org"

gem 'yard'
```

Doesn't work:

```ruby
# Gemfile
source "https://rubygems.org"

gemspec
```
```ruby
# example.gemspec
Gem::Specification.new do |s|
  s.name        = 'example'
  s.version     = '0.0.1'
  s.date        = '2019-07-27'
  s.summary     = "Example"
  s.description = "A simple hello world gem"
  s.authors     = ["Connor Shea"]
  s.files       = ["lib/example.rb"]
  s.homepage    =
    'https://rubygems.org/gems/example'
  s.license       = 'MIT'

  s.add_dependency 'yard'
end
```

#### Observed output

The file at `sorbet/rbi/gems/yard.rbi` is only 300 lines vs. 1200 lines when `yard` is required explicitly via the Gemfile.

#### Expected behavior

I'd expect Sorbet to output the same `yard.rbi` either way.

~~It doesn't seem like any other gems' generated rbis differ when Sorbet is initialized, only YARD (and presumably any other gems that have requires specified in `gem_loader.rb`.~~ I think this does actually effect all gems defined in a gemspec. If they're not explicitly `require`d by a file in the project, Sorbet won't notice them. Whereas if they're defined in the `Gemfile`, Sorbet will notice them regardless of any `require`.

**Comment by connorshea** [comment]
You can also see this issue in the `sorbet/rbi/gems/` directory with [Sord](https://github.com/AaronC81/sord/tree/1c791d8c0b136514474a5107b556620bcb238d3b/sorbet/rbi/gems) and [Parlour](https://github.com/AaronC81/parlour/tree/837a98abb12a34d5ddeaae6bb9f94bc02feae6f4/sorbet/rbi/gems). Sord has the problem where YARD's rbi isn't fully generated and Parlour has the problem where not all the gems depended on in the gemspec have their rbis generated.

**Comment by jasnow** [comment]
Big problem

**Comment by johngun3** [comment]
I just encountered this with the latest version`0.5.5551`. Is the workaround to also list gem dependencies in `Gemfile` and put up with annoying messages like this?

    Your Gemfile lists the gem sorbet (= 0.5.5551) more than once.
    You should probably keep only one of them.
    Remove any duplicate entries and specify the gem only once (per group).
    While it's not a problem now, it could cause errors if you change the version of one of them later.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
