### ISSUE TITLE
Regression to untyped inside block

### ISSUE THREAD

**Issue by azdavis** [sorbet/sorbet#1243]
#### Input

```rb
# typed: true
class A
  extend T::Sig
  sig do
    params(
      blk: T.nilable(
        T.proc
        .params(x: Integer)
        .returns(Integer)
      )
    )
    .returns(Integer)
  end
  def self.foo(&blk)
    if block_given?
      blk.call(3)
    else
      3
    end
  end
end

ans = A.foo do |x|
  T.reveal_type(x)
  x + 1
end

p ans
```

#### Observed output

On every commit in the range `29671cca..master`:
```
foo.rb:25: Revealed type: T.untyped https://srb.help/7014
    25 |  T.reveal_type(x)
          ^^^^^^^^^^^^^^^^
  From:
    foo.rb:24:
    24 |ans = A.foo do |x|
                        ^
Errors: 1
```

On `29671cca~`:
```
foo.rb:25: Revealed type: Integer https://srb.help/7014
    25 |  T.reveal_type(x)
          ^^^^^^^^^^^^^^^^
  From:
    foo.rb:24:
    24 |ans = A.foo do |x|
                        ^
Errors: 1
```

#### Expected behavior

The revealed type should be `Integer`.

**Comment by azdavis** [comment]
@DarkDimius this may be related to 29671cca?

**Comment by DarkDimius** [comment]
Likely it is

**Comment by connorshea** [comment]
I just hit this as well. I think it only happens when the block is nilable?

**Comment by connorshea** [comment]
https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20blk%3A%20T.nilable(%0A%20%20%20%20%20%20%20%20T.proc%0A%20%20%20%20%20%20%20%20.params(x%3A%20Integer)%0A%20%20%20%20%20%20%20%20.returns(Integer)%0A%20%20%20%20%20%20)%0A%20%20%20%20)%0A%20%20%20%20.returns(Integer)%0A%20%20end%0A%20%20def%20self.foo(%26blk)%0A%20%20%20%20if%20block_given%3F%0A%20%20%20%20%20%20blk.call(3)%0A%20%20%20%20else%0A%20%20%20%20%20%203%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Aans%20%3D%20A.foo%20do%20%7Cx%7C%0A%20%20T.reveal_type(x)%0A%20%20x%20%2B%201%0Aend%0A%0Ap%20ans

It looks like this is resolved now 👏

**Comment by azdavis** [comment]
🎉
