### ISSUE TITLE
String#match? is not in the type repository

### ISSUE THREAD

**Issue by sebas-stripe** [sorbet/sorbet#1249]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20bar(x)%0A%20%20%20%20%22this%22.match%3F(%22a%22)%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  def bar(x)
    "this".match?("a")
  end
end
```

#### Observed output

```
 Did you mean: String#match ?
     469 |  def match(arg0, arg1=T.unsafe(nil)); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

#### Expected behavior

I expected to correctly find the method String#match? in https://ruby-doc.org/core-2.4.0/String.html

- - -

I'm happy to submit a PR with the fix.

**Comment by DarkDimius** [comment]
@sebas-stripe 
> I'm happy to submit a PR with the fix.

please do!
Thank you!

**Comment by sebas-stripe** [comment]
Added PR https://github.com/sorbet/sorbet/pull/1295

**Comment by connorshea** [comment]
I think this is fixed now?

**Comment by sebas-stripe** [comment]
Yes, closing.
