### ISSUE TITLE
Proc#[] doesn't exist?

### ISSUE THREAD

**Issue by carl-stripe** [sorbet/sorbet#1251]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Afoo%20%3D%20T.let(-%3E(x)%20%7Bx%7D%2C%20Proc)%0Afoo%5B4%5D)

```ruby
# typed: true

foo = T.let(->(x) {x}, Proc)
foo[4]
```

#### Observed output

```
editor.rb:4: Method [] does not exist on Proc https://srb.help/7003
     4 |foo[4]
        ^^^^^^
Errors: 1
```

#### Expected behavior

This method does exist! As far as I know it works just like `#call`

**Comment by jez** [comment]
Just need to duplicate this:

https://github.com/sorbet/sorbet/blob/cb4dd69d53faae9aa962050fd97b26481da3fbff/rbi/core/proc.rbi#L10-L17
