### ISSUE TITLE
Support ignoring files/folders during init.

### ISSUE THREAD

**Issue by shidel-dev** [sorbet/sorbet#1259]
### Problem

When initializing a project with Sorbet, it would be useful to be able to exclude certain files/folders so that they do not get executed. A use case would be for a situation where It is not possible to modify these files, as they are not owned by the parent repo (think third party code that is included via a submodule/vendor dir, etc..).

### Proposed solution
Ideally this would be both a command line flag, and could also be specified in a config file. The config file is useful, because the command line flags would then not need to be used every time.

example usage
```bash
srb init --ignore=vendor/third_party_lib
```

This would work very similar to how the ignore flag works with the `tc` command.
```bash
srb tc --ignore=vendor/third_party_lib
```

The command line flag on `init` would be a bit hard to discovery until https://github.com/sorbet/sorbet/issues/1003 is fixed.

**Comment by connorshea** [comment]
I have this problem with discordrb, which has a file that loops indefinitely when running `srb init`. Short of removing the gem entirely, I don't have a way to initialize sorbet in that repository.

**Comment by jaredbeck** [comment]
All users of `webpacker` will encounter this problem. Its dependency `node-sass` includes a ruby script, `extconf.rb` which, when `required` will generate a `Makefile` in the current directory. `srb init` will produce the following output:

```
require_relative './node_modules/node-sass/src/libsass/extconf.rb' \
creating Makefile
```

Having a way to ignore the `node_modules` directory would solve this problem.

We discussed this briefly in https://github.com/sorbet/sorbet/pull/943#issuecomment-509387986

**Comment by fbartho** [comment]
We think we have the same problem that @connorshea described. -- We *just* started experimenting with Sorbet and one of the gems we have (louisville) Leads to a SystemStackError due to what looks like infinite recursion.

Also, it'd be great to be able to artificially limit the potential stack depth to catch this problem quicker, haha.

**Comment by jaredbeck** [comment]
### Workaround: Add the ignore sigil

Run the following script before `srb init`:

```bash
#!/usr/bin/env bash
# usage sorbet_ignore.sh [directory]

if [ ! -d $1 ]; then
  echo 'Directory not found:' $1
  exit 1
fi

set -e

RUBY_FILES=$(find $1 -type f -name '*.rb')
NUM_FILES=$(wc -w <<< "$RUBY_FILES" | tr -d '[:space:]')
echo "Adding the ignore sigil to $NUM_FILES ruby files in $1"
for F in $RUBY_FILES
do
  echo '# typed: ignore' > /tmp/646e25ca
  cat $F >> /tmp/646e25ca
  cp /tmp/646e25ca $F
done
```

**Comment by robertsimoes** [comment]
Thanks for the script @jaredbeck, however, sorbet doesn't seem to be respecting the files I attach the sigils to. 

Have you found any other work arounds.

**Comment by ricksuggs** [comment]
@robertsimoes I wanted to ignore some directories in my project, but the options didn't work with the `srb init` command. As a workaround, instead I supplied the `--dir` option in the` sorbet/config` file as follows, to specify the directories that I wanted to type check.
```
--dir
./app
./lib
./test
```

**Comment by ricksuggs** [comment]
@robertsimoes I wanted to ignore some directories in my project, but the options didn't work with the `srb init` command. As a workaround, instead I supplied the `--dir` option in the` sorbet/config` file as follows, to specify the directories that I wanted to type check.
```
--dir
./app
./lib
./test
```

**Comment by StanBright** [comment]
Thanks @ricksuggs, that worked for me. Exactly what I wanted.

**Comment by dorianmariefr** [comment]
You can also use the `--ignore` flag, e.g.

```
--dir
.
--ignore=/vendor/bundle
--ignore=/node_modules
--ignore=/react-native
```

**Comment by jaredbeck** [comment]
AFAICT `--ignore` is a good technique for e.g. `node_modules`, but not for app code, because (AFAICT) file sigils take precedence over single-file `--ignore`s. 

For example, `# typed: true` in `danger.rb` seems to take precedence over `--ignore danger.rb`.

For now, I'd still recommend [sigil downgrade](https://github.com/sorbet/sorbet/issues/1259#issuecomment-516523043) prior to e.g. `srb init`.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
