### ISSUE TITLE
Mutex isn't included in the stdlib

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1262]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Asemaphore%20%3D%20Mutex.new%0A%0Aa%20%3D%20Thread.new%20%7B%0A%20%20semaphore.synchronize%20%7B%0A%20%20%20%20%23%20access%20shared%20resource%0A%20%20%7D%0A%7D)

```ruby
# typed: true

semaphore = Mutex.new

a = Thread.new {
  semaphore.synchronize {
    # access shared resource
  }
}
```

This file is taken directly from the [Mutex](https://ruby-doc.org/core-2.5.0/Mutex.html) documentation, so it should work fine.

#### Observed output

```


editor.rb:3: Unable to resolve constant Mutex https://srb.help/5002
     3 |semaphore = Mutex.new
                    ^^^^^
    https://github.com/sorbet/sorbet/tree/beecfbcc014c33282ea65f03a61fbb74535a5435/rbi/core/thread.rbi#L46: Did you mean: Thread::Mutex?
    46 |class Thread::Mutex < Object
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/beecfbcc014c33282ea65f03a61fbb74535a5435/rbi/stdlib/date.rbi#L3: Did you mean: Date?
     3 |class Date
        ^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/beecfbcc014c33282ea65f03a61fbb74535a5435/rbi/core/math.rbi#L3: Did you mean: Math?
     3 |module Math
        ^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Mutex would be a defined part of the stdlib (or core? I'm not sure I understand what goes where)

- - -

Mutex_m is in the `rbi/stdlib/` directory, but not Mutex: https://github.com/sorbet/sorbet/blob/ded82d2d625b97950fa63f43518676fee101c5eb/rbi/stdlib/mutex_m.rbi

I'm not really sure what Mutex_m is, honestly.

**Comment by Morriar** [comment]
Mutex in in `core/thread.rbi`.

I think you need to use the qualified name here: `Thread::Mutex`.

But the RBI is missing the definition for `synchronize`.

**Comment by connorshea** [comment]
I think `Thread::Mutex` might have been moved to `Mutex` in Ruby 2.5?

- 2.4.1, `Thread::Mutex`: https://ruby-doc.org/core-2.4.1/Thread/Mutex.html
- 2.5.0: `Mutex`: https://ruby-doc.org/core-2.5.0/Mutex.html
- 2.6.0: `Mutex`: https://ruby-doc.org/core-2.6/Mutex.html

But 2.4.1 doesn't have `Mutex` and 2.5/2.6 don't have `Thread::Mutex`, or at least they don't have the explicitly named docs for them. I assume either is valid, so maybe it should be an alias?

**Comment by connorshea** [comment]
`Mutex = Thread::Mutex` does indeed show up in hidden-definitions.rbi on Ruby 2.6, so I think it was renamed with 2.5.
