### ISSUE TITLE
Implement formatting-related LSP features

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#1287]
### Problem
`textDocument/formatting`, `textDocument/rangeFormatting` and `textDocument/onTypeFormatting`.
### Proposed solution
Take Sorbet desugared tree(one just before namer) and build a canonical pretty-printer for it.
The pretty printer will need to do some kind of search for a best formatting decision and should work for incomplete code(that may not fully parse yet).

https://docplayer.net/36427352-Scalafmt-opinionated-code-formatter-for-scala.html
and 
https://www.youtube.com/watch?v=s7JmdCfI__c are good things to consult with.

Doing this properly is hard.

**Comment by DarkDimius** [comment]
I'd expect that minimal integration can also be done based on https://github.com/prettier/plugin-ruby . If we build on it, we'll need to assess if it can do:

 - formatting for incomplete files;
 - range formatting;
 - fast formatting for millions of lines of code.

**Comment by numbcoder** [comment]
There are 2 ruby formatters which are implemented by pure ruby may be more easy  to integrate

https://github.com/ruby-formatter/rufo
https://github.com/rubocop-hq/rubocop

**Comment by jez** [comment]
There is rudimentary support for this behind `--enable-experimental-lsp-document-formatting`. See the rubyfmt repo for further formatting questions.
