### ISSUE TITLE
Refining implementation return type raises an exception in runtime

### ISSUE THREAD

**Issue by smt116** [sorbet/sorbet#1296]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0A%23%20Sorbet%20won't%20complain%20about%20the%20following%20code%20while%20analyzing.%0A%23%20However%2C%20it%20will%20raise%20an%20exception%20in%20runtime%3A%0A%0A%23%20%20%20RuntimeError%3A%20Incompatible%20return%20type%20in%20implementation%20of%20method%20%60params%60%3A%0A%23%20%20%20%20*%20Base%3A%20%60T%3A%3AHash%5BT.untyped%2C%20T.untyped%5D%60%20(in%20%23%3CClass%3ABase%3E%20at%20%2FUsers%2Fsmefju%2Ftmp%2Ffoo.rb%3A12)%0A%23%20%20%20%20*%20Implementation%3A%20%60%7Bfoo%3A%20Integer%7D%60%20(in%20%23%3CClass%3AFoo%3E%20at%20%2FUsers%2Fsmefju%2Ftmp%2Ffoo.rb%3A19)%0A%23%20%20%20%20(The%20types%20must%20be%20covariant.)%0A%23%20%20%20%20from%20%2FUsers%2Fsmefju%2F.rbenv%2Fversions%2F2.6.3%2Flib%2Fruby%2Fgems%2F2.6.0%2Fgems%2Fsorbet-runtime-0.4.4405%2Flib%2Ftypes%2Fprivate%2Fmethods%2Fsignature_validation.rb%3A211%3Ain%20%60validate_override_types'%0A%0Aclass%20Base%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.params(flag%3A%20T%3A%3ABoolean).returns(Hash)%20%7D%0A%20%20def%20self.params(flag)%3B%20end%20%0Aend%20%0A%0Aclass%20Foo%20%3C%20Base%0A%20%20Params%20%3D%20T.type_alias(foo%3A%20Integer)%0A%0A%20%20sig%20%7B%20implementation.params(flag%3A%20T%3A%3ABoolean).returns(Params)%20%7D%0A%20%20def%20self.params(flag)%20%0A%20%20%20%20if%20flag%0A%20%20%20%20%20%20%7B%20foo%3A%201%20%7D%0A%20%20%20%20else%0A%20%20%20%20%20%20%7B%20foo%3A%2010%20%7D%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Aclass%20Bar%20%3C%20Base%0A%20%20Params%20%3D%20T.type_alias(bar%3A%20String)%0A%0A%20%20sig%20%7B%20implementation.params(flag%3A%20T%3A%3ABoolean).returns(Params)%20%7D%0A%20%20def%20self.params(flag)%20%0A%20%20%20%20%7B%20bar%3A%20flag%20%3F%20%22Yes%22%20%3A%20%22No%22%20%7D%0A%20%20end%0Aend%0A%0AFoo.params(true)%0ABar.params(false))

```ruby
# typed: strict

class Base
  extend T::Helpers
  extend T::Sig

  abstract!

  sig { abstract.params(flag: T::Boolean).returns(Hash) }
  def self.params(flag); end 
end 

class Foo < Base
  Params = T.type_alias(foo: Integer)

  sig { implementation.params(flag: T::Boolean).returns(Params) }
  def self.params(flag) 
    if flag
      { foo: 1 }
    else
      { foo: 10 }
    end
  end
end

class Bar < Base
  Params = T.type_alias(bar: String)

  sig { implementation.params(flag: T::Boolean).returns(Params) }
  def self.params(flag) 
    { bar: flag ? "Yes" : "No" }
  end
end

Foo.params(true)
Bar.params(false)
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

The static analyze check does not complain about the code (and it is correct!). However, the code raises the exception in the runtime:

```
RuntimeError: Incompatible return type in implementation of method `params`:
* Base: `T::Hash[T.untyped, T.untyped]` (in #<Class:Base> at /Users/smefju/tmp/foo.rb:12)
* Implementation: `{foo: Integer}` (in #<Class:Foo> at /Users/smefju/tmp/foo.rb:19)
(The types must be covariant.)
from /Users/smefju/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4405/lib/types/private/methods/signature_validation.rb:211:in `validate_override_types'
```

The usecase for this is to have a single abstract class for communicating with the external service. Then, you can inherit from it to implement different actions. In my case, actions have different body param which is calculated using `self.body` method that takes `user` param.

**Comment by DarkDimius** [comment]
When implementing an interface, the implementation needs to be "at least as good" as the interface.

In your case, `Base.params` was promised to return a `Hash` while in child it returns `Integer`, which violates promises of parent.

If you're curios for more reasoning behind this, have a look at https://en.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by smt116** [comment]
@DarkDimius but the type in the interface is "at least as good". `Base.params` is a `Hash` while child **does not** return an `Integer` but `{foo: Integer}` which is `Hash`! It means that implementation's signature is more specific than in the abstract.

Also, if this is the expected behavior, than why `srb t` passes while runtime raises an exception?

**Comment by smt116** [comment]
@DarkDimius ping --^

**Comment by smt116** [comment]
@DarkDimius ping --^

**Comment by smt116** [comment]
@jez @ptarjan could some of you guys take a look? The issue is valid but has been closed. Dmitry has closed the issue because he probably misread types.
