### ISSUE TITLE
srb init fails if git fetch origin fails in sorbet-typed

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#1306]
#### Input
When running `srb init`, if `git fetch origin` in `${XDG_CACHE_DIR}/sorbet/sorbet-typed` fails, the whole operation will fail. This operation can fail for a number of reasons:

* There is no network connection
* The `sorbet-typed` cache was populated manually, and isn't a git repository

#### Observed output

`srb init` fails, passing out the failure message from `git`.

#### Expected behavior

If the `sorbet-typed` directory exists and `git fetch origin` fails, exit the block in `fetch-rbis.rb:39` instead of raising an exception.

- - -

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
