### ISSUE TITLE
Use file-table-json when processing files in srb

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#1340]
### Problem
There's duplicated functionality in `require_everything.rb` and sorbet for file discovery. A result of this is that functionality we would like to have in `srb` already exists in sorbet, and we can't take advantage of it now.

### Proposed solution
Switching from using [`Dir.glob`](https://github.com/sorbet/sorbet/blob/1e939954f10443473f442246bf38d9ae34fded0e/gems/sorbet/lib/require_everything.rb#L46) to parsing the output of `sorbet -p file-table-json` would allow us to take advantage of additional flags from sorbet like `--typed-override` to give typed sigils to generated files. Additionally, we could remove some text processing from `require_everything.rb` that looks for `typed: ignore` in source files.

**Comment by jez** [comment]
Fixed in #1351
