### ISSUE TITLE
[sorbet-runtime] Defining `singleton_method_added` after a sig'd method can cause subsequent sigs to not apply correctly

### ISSUE THREAD

**Issue by jzhou-stripe** [sorbet/sorbet#1348]
#### Input

```ruby
class Command
  extend T::Sig

  sig {params(method_name: Symbol).void}
  def self.method_added(method_name); end

  def self.singleton_method_added(method_name); end
end

class Foo < Command
  sig {void}
  def a; end

  sig {void}
  def b; end

  sig {void}
  def c; end
end
```

#### Observed runtime output

```
/Users/jzhou/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:37:in `declare_sig': You called sig twice without declaring a method inbetween (RuntimeError)
        from /Users/jzhou/stripe/sorbet/gems/sorbet-runtime/lib/types/sig.rb:28:in `sig'
        from foo.rb:21:in `<class:Foo>'
        from foo.rb:14:in `<main>
```

#### Expected behavior

There should be no output.

- - -

(Internally, this bug exists on `Opus::Command`.)

I've isolated the problem down to incorrect `DeclState#skip_next_on_method_added` due to the `singleton_method_added` method clobbering the one defined by `T::Private::Methods.install_singleton_method_added_hook`:

```ruby
class Command
  extend T::Sig

  sig {void}
  def self.foobar; end

  def self.singleton_method_added(method_name); end

  foobar
end

raise Exception.new("expected to not skip next!") if T::Private::DeclState.current.skip_next_on_method_added # raises
```

The workaround is to place the definition of `singleton_method_added` above any `sig`'d method:

```ruby
class Command
  extend T::Sig

  def self.singleton_method_added(method_name); end

  sig {void}
  def self.foobar; end

  foobar
end

raise Exception.new("expected to not skip next!") if T::Private::DeclState.current.skip_next_on_method_added # doesn't raise
```

**Comment by azdavis** [comment]
Thanks for investigating.

Should we consider this a bug in sorbet-runtime, or in Command? That is, should we require people to define their own singleton_method_added before using sig, or find a way to allow people to define their own singleton_method_added whenever they want?

The short-term easier solution would be the former, but the more robust solution would be the latter. I lean towards preferring the latter.

**Comment by jez** [comment]
I dug up an old version of sorbet-runtime (0.4.4439) which doesn't have the final methods changes nor the `skip_next_on_method_added` bit, and the issue still reproduces. So this doesn't seem to be a recent regression, but rather something that's been the case for a while.

**Comment by jez** [comment]
jk i wasn't using `bundle exec`. This doesn't reproduce on `0.4.4439`.

**Comment by jez** [comment]
I just git bisected with this reproducer:

```ruby
require_relative './lib/sorbet-runtime'

class Parent
  extend T::Sig

  sig {params(method_name: Symbol).void}
  def self.method_added(method_name); end

  def self.singleton_method_added(method_name); end
end

class Child < Parent
  sig {void}
  def a; end

  sig {void}
  def b; end

  sig {void}
  def c; end
end
```

and git said

```
e6f1d7bea7a9ada9011819557a9728c5211d02a8 is the first bad commit
commit e6f1d7bea7a9ada9011819557a9728c5211d02a8
Date:   Tue Jul 16 15:06:06 2019 -0700

    Add final method runtime (#1181)
```

**Comment by azdavis** [comment]
In a similar vein:

```rb
require './gems/sorbet-runtime/lib/sorbet-runtime.rb'

class Parent
  extend T::Sig

  sig {params(method_name: Symbol).void}
  def self.method_added(method_name); end

  def self.singleton_method_added(method_name); end

  sig {returns(Integer)}
  def self.foo
    "no"
  end
end

Parent.foo
```

Should raise but gives no errors on e2998407661d635b538f5f928313aefb6bca56e3 (the parent of e6f1d7bea7a9ada9011819557a9728c5211d02a8).

**Comment by azdavis** [comment]
The problem here seems to be that users can override method_added and singleton_method_added to not do the sig-wrapping logic.
