### ISSUE TITLE
Match performance of `T::Array[T.untyped]` is equivalent to `Array` at runtime 

### ISSUE THREAD

**Issue by zanker-stripe** [sorbet/sorbet#1352]
### Problem

The performance of enumerable types, `T::Array`, `T::Hash, `T::Set` and so on are less performant than their class version when using `T.untyped`. This is because `T::Array[T.untyped]` will cause the runtime checker to iterate over each entry of the array, verifying that the entries are untyped and it will never fail.

Given the strict type checker requires `T::Array[T.untyped]`, we should ensure runtime checking of that is equivalent to `Array`, as the runtime checker is not adding any value with the `[T.untyped]` portion.

When I tried to make this change internally a while back, I did it via converting `T::Array[T.untyped]` -> `Array`, `T::Hash[T.untyped, T.untyped]` -> `Hash` and so on, but it broke some areas where we explicitly checked that it was `T::Array`.

It might be easier to have a short circuit per typed class which defines whether or not the inner type is no-op and then `TypedEnumerable` can short circuit its own `valid?` check based on that.

(If that seems reasonable, I might be able to find some hacking time and can toss together a PR)

**Comment by jez** [comment]
Fixed in #1440
