### ISSUE TITLE
sorbet -a suggests unreasonable types for methods defined in supertype

### ISSUE THREAD

**Issue by carl-stripe** [sorbet/sorbet#1362]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(FalseClass)%7D%0A%20%20def%20foo%0A%20%20%20%20false%0A%20%20end%0A%0A%20%20sig%20%7Bgenerated.returns(FalseClass)%7D%0A%20%20def%20bar%0A%20%20%20%20false%0A%20%20end%0Aend%0A%0A%0Aclass%20B%20%3C%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20foo%0A%20%20%20%20true%0A%20%20end%0A%20%20%0A%20%20def%20bar%0A%20%20%20%20true%0A%20%20end%0Aend)

```ruby
# typed: strict

class A
  extend T::Sig

  sig {returns(FalseClass)}
  def foo
    false
  end

  sig {generated.returns(FalseClass)}
  def bar
    false
  end
end


class B < A
  extend T::Sig

  def foo
    true
  end
  
  def bar
    true
  end
end
```

#### Observed output

```
editor.rb:12: This function does not have a `sig` https://srb.help/7017
    12 |  def bar
          ^^^^^^^

editor.rb:21: This function does not have a `sig` https://srb.help/7017
    21 |  def foo
          ^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:21: Insert sig {returns(FalseClass)}
  
    21 |  def foo
          ^

editor.rb:25: This function does not have a `sig` https://srb.help/7017
    25 |  def bar
          ^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:25: Insert sig {returns(FalseClass)}
  
    25 |  def bar
          ^
Errors: 3
```

#### Expected behavior

I would expect Sorbet to infer `T.any(TrueClass, FalseClass)` (aka `T::Boolean`), or to infer `returns(TrueClass)`, or to (extra bonus points) suggest changing the superclass to `T::Boolean`

Note, this happens for things that aren't Booleans, so a narrow solution will only be partially helpful

Interestingly, Sorbet does something much more reasonable if you remove all the sigs. It's one case I know of where the existence of a bad `generated` type significantly hampers Sorbet's ability to

**Comment by jez** [comment]
I think this is most likely a relic of a time when we had a lot of bad `generated` signatures. We've removed `generated`, which means that if a sig is specified as `returns(FalseClass)`, the parent method really means it, in which case the suggested sigs in the Child are actually correct.

Closing this as won't do
