### ISSUE TITLE
T.any makes generic wider than expected

### ISSUE THREAD

**Issue by XrXr** [sorbet/sorbet#1363]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aa%20%3D%20T.let(%7B%7D%2C%20T.any(T%3A%3AHash%5BSymbol%2C%20Symbol%5D%2C%20T%3A%3AHash%5BString%2C%20String%5D))%0AT.reveal_type(a)%0Aa%20%3D%20%7B%20wider%3A%20'than%20expected'%20%7D%20%23%20I%20would%20expect%20this%20to%20error%0A)

```ruby
# typed: strict
a = T.let({}, T.any(T::Hash[Symbol, Symbol], T::Hash[String, String]))
T.reveal_type(a)
a = { wider: 'than expected' } # I would expect this to error
```

#### Observed output

```
Revealed type: T::Hash[T.any(String, Symbol), T.any(String, Symbol)]
```

#### Expected behavior

`Revealed type: T.any(T::Hash[Symbol, Symbol], T::Hash[String, String])` -- what is written in the source. Aren't these two types different?

**Comment by jez** [comment]
Sorbet models arrays and hashes as covariant intentionally, so this relaxation is valid under that assumption.

**Comment by jez** [comment]
e.g., it happens for arrays too:

https://sorbet.run/#%23%20typed%3A%20strict%0Aa%20%3D%20T.let(%5B%5D%2C%20T.any(T%3A%3AArray%5BString%5D%2C%20T%3A%3AArray%5BInteger%5D))%0AT.reveal_type(a)

**Comment by XrXr** [comment]
I think in this particular case the transformation widens the result of `T.any` much more compared to array. With array the transformation allows heterogeneous elements where as in the case of Hash it allows for two entire different pairs of types in each type_member. (`T::Hash[Symobl, String] and T::Hash[String, Symbol]` in this case, neither of which are sub-types of the components of the union...)

**Comment by DarkDimius** [comment]
I think this is intentional. We're trying to collapse types aggressively for sake of performance.
Could you give an example where this poses a problem?

**Comment by XrXr** [comment]
My concern is that sorbet-runtime doesn't do this transformation, so the following crashes:
```
require 'sorbet-runtime'
T.let({ wider: 'than expected' }, T.any(T::Hash[Symbol, Symbol], T::Hash[String, String]))
```
But is okay statically.
Internally we have a Result class that's basically `std::result` from Rust and `scala.util.Either` which is used at API boundaries. I'm a bit concerned about this inconsistency.

**Comment by DarkDimius** [comment]
Runtime and static typesystems age "best effort" identical.
There will always be errors that aren't catched statically and that's fine.
