### ISSUE TITLE
In LSP mode, in slowpath, typecheck files that had errors & were modified first

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#1380]
This will allow to help folks to iterate faster, as most likely the files with errors are the most impacted in edits.

**Comment by jvilk-stripe** [comment]
Implementation note: LSP currently waits for typechecking to finish completely before sending all results back to the client. For this change to be impactful, LSP would need to send typechecking results as they arrive.

**Comment by DarkDimius** [comment]
Marking this as hard as this will interact badly with cancellation

**Comment by jvilk-stripe** [comment]
@vilhena-stripe has already done this.
