### ISSUE TITLE
LSP bug: doesn't correctly update error on sig dissapearing

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#1381]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%7Breturns(String)%7D%0A%20%20def%20bar(x)%0A%20%20%20%201%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig
  sig{returns(String)} # delete this line as a single edit
  def bar(x)
    1
  end
end
```

#### Observed output
Continues to complain about wrong return type after deleting sig

#### Expected behavior
Stops complaining

**Comment by DarkDimius** [comment]
So, the bug appeared after https://github.com/sorbet/sorbet/pull/366
There we started taking fastpath for signature changes of methods. We assume that the resolver will overwrite the `sig`, with a new one and this works correctly if  `sig` is either changed or introduced, as the `sig` is still there.

In case of deletion of `sig`, we correctky make decision to take fastpath too and we run over correct set of files, but there's no code in Sorbet that currently resets the return type of `bar`.

One way I see this error being addressed is through the refactor that we've postponed for quite a while, where we'll start having tombstones in filetable.

Related: https://github.com/sorbet/sorbet/issues/1064

**Comment by sushain97** [comment]
Note that if this file is made `typed: strict`, deleting the sig -> no error -> no sig suggestion code action.

[sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20%23%20delete%20the%20sig%20and%20sig%20missing%20error%20will%20not%20be%20visible%20here%0A%20%20sig%7Breturns(String)%7D%0A%20%20def%20bar(x)%0A%20%20%20%201%0A%20%20end%0Aend)

**Comment by DarkDimius** [comment]
Let's just hash it as a boolean if it has a sig
