### ISSUE TITLE
Improve "Failed to load" messages in gems/sorbet/lib directory

### ISSUE THREAD

**Issue by jasnow** [sorbet/sorbet#1384]
I do not understand this message: "Failed to load" and Sorbet has 4 places to trigger it.

May I please reword "Failed to load" messages to be more descriptive and unique. Here are my suggested changes.

**Very open to alternative rewordings.**

If approved, I will do create a PR 1 file at a time using GitHub.

Thanks
```
1st choice:
gems/sorbet/lib/constant_cache.rb
    -139- Nested name #{name}::#{nested} not needed by app
    -142- Nested name #{name}::#{nested} not needed by app_
gems/sorbet/lib/serialize.rb
    -106- Class constant symbol #{class_name}::#{const_sym} not needed by app
    -120- Class constant symbol #{class_name}::#{const_sym} not needed by app_

2nd choice:
gems/sorbet/lib/constant_cache.rb
    -139- Failed to load nested name #{name}::#{nested}
    -142- Failed to load nested name #{name}::#{nested}_
gems/sorbet/lib/serialize.rb
    -106- Failed to load class constant symbol #{class_name}::#{const_sym}
    -120- Failed to load class constant symbol #{class_name}::#{const_sym}_
```

**Comment by elliottt** [comment]
Thanks for the feedback, some internal polling showed preference for your second suggestion.

**Comment by jez** [comment]
Why not just say what we're actually doing in those places?

"Got {LoadError,NameError,ArgumentError} when trying to get constant ..."

**Comment by jasnow** [comment]
@elliottt @jez - I will PR either one - once I get the "GO" signal.
