### ISSUE TITLE
Typo in the `--counters` output

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1398]
There is a typo in the `--counters` output:
```
  types.input.methods.typechecke :      6570
```

I couldn't find any reference to "typechecke" in the codebase. I suppose it's soemthign to do with the padding of the `:`

Is this file where I can change the padding of the output? Also I didn't see any spec related
https://github.com/sorbet/sorbet/blob/d64ba77f3d50f5f4b9340458523fc3959e500a2e/common/Counters.cc

**Comment by jez** [comment]
https://github.com/sorbet/sorbet/blob/5ff564a853559fb871a14114dde45ab0634db3c2/common/Counters.cc#L290-L293


The format string truncates strings into 30 characters. Feel free to change it.

**Comment by DarkDimius** [comment]
Feel free to raise the limit of width :-)
