### ISSUE TITLE
return statement in class or module def shouldn't parse

### ISSUE THREAD

**Issue by alexsnaps** [sorbet/sorbet#14]
See [this test](https://sorbet.run/#class%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20{params(x%3A%20Integer).returns(String)}%0A%20%20def%20bar(x)%0A%20%20%20%20return%20%22Hello%22%0A%20%20end%0A%0A%20%20module%20M%0A%20%20%20%20%20%20return%20%23%20error%3A%20Parse%20Error%3A%20Invalid%20return%20in%20class%2Fmodule%20body%0A%20%20end%0A%20%20%20%20%0A%20%20return%20%23%20error%3A%20Parse%20Error%3A%20Invalid%20return%20in%20class%2Fmodule%20body%0Aend%0A) as to how it should behave. This stems from a bug in the (parser gem|ruby) parser that was "ported" to typedruby. Would be worthwhile to catch these with Sorbet. It got fixed in parser gem [here](https://github.com/whitequark/parser/commit/3d588f42a67235828744e458e45daa963a0d24a8#diff-5267493af36869d868502e7fd1f342bd)

**Comment by iliabylich** [comment]
Fixed in https://github.com/sorbet/sorbet/pull/1670

**Comment by jaredbeck** [comment]
@alexsnaps @jez seems this can be closed?
