### ISSUE TITLE
Widening singleton types without errors in a loop leads to confusing(wrong) behavior 

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#142]
https://sorbet.run/#class%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).returns(String)%7D%0A%20%20def%20bar(x)%0A%20%20%20%20x%20%3D%20%22a%22%0A%20%20%20%20%23%20workaround%0A%20%20%20%20%23%20x%20%3D%20T.let(%22a%22%2C%20String)%0A%20%20%20%20%5B1%2C%202%2C%203%5D.each%20do%20%7Ci%7C%0A%20%20%20%20%20%20if%20x%20!%3D%20%22a%22%0A%20%20%20%20%20%20%20%20if%20x%20%3D%3D%20%22b%22%0A%20%20%20%20%20%20%20%20%20%20puts%20%22foo%22%0A%20%20%20%20%20%20%20%20end%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20x%20%3D%20%22b%22%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20%20%20''%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20A.new.bar(91)%0Aend

**Comment by jez** [comment]
Duplicate of #2348
