### ISSUE TITLE
Props (e.g., in T::Struct) don't declare their corresponding instance variables

### ISSUE THREAD

**Issue by carl-stripe** [sorbet/sorbet#1427]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20prop%20%3Afoo%2C%20String%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20def%20bar%0A%20%20%20%20%40foo%0A%20%20end%0Aend)

```ruby
# typed: strict
class A < T::Struct
  extend T::Sig

  prop :foo, String

  sig {returns(String)}
  def bar
    @foo
  end
end
```

#### Observed output

```
editor.rb:9: Use of undeclared variable @foo https://srb.help/6002
     9 |    @foo
            ^^^^
Errors: 1
```

#### Expected behavior

I expect this instance variable to already be declared and already have type `String`

**Comment by azdavis** [comment]
I'm not sure if we want to let users depend on the fact that props on a `T::Struct` are backed by instance variables of the same name. This is currently true but we may want to treat it as merely an implementation detail that may change at any time.

Is there a situation where using the getter/setter methods for the struct class doesn't work? As far as I can tell, every time you would want use an ivar generated by a `prop`, you could just use the getter/setter methods generated by that `prop`.

**Comment by carl-stripe** [comment]
https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20prop%20%3Afoo%2C%20String%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20flip!%0A%20%20%20%20foo%20%3D%20foo.reverse%0A%20%20end%0Aend

```ruby
# typed: strict
class A < T::Struct
  extend T::Sig

  prop :foo, String

  sig {void}
  def flip!
    foo = foo.reverse
  end
end
```

```
editor.rb:9: Method reverse does not exist on NilClass https://srb.help/7003
     9 |    foo = foo.reverse
                  ^^^^^^^^^^^
Errors: 1
```

**Comment by carl-stripe** [comment]
Although I suppose I can work around this by using `self.foo = foo.reverse`

**Comment by carl-stripe** [comment]
In any event, we have a ton of legacy code that relies on this behavior that someone is going to have to fix at some point

**Comment by jez** [comment]
This works now for T::Struct.

**Comment by levibuzolic** [comment]
Would it be possible to have this same behaviour expanded to `T::InexactStruct`?
