### ISSUE TITLE
Struct constructors and instance variable type declarations don't play nice

### ISSUE THREAD

**Issue by carl-stripe** [sorbet/sorbet#1431]
### Problem

[sorbet.run example](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20prop%20%3Afoo%2C%20String%0A%20%20prop%20%3Abar%2C%20String%0A%0A%20%20sig%20%7Bparams(hash%3A%20T%3A%3AHash%5BT.untyped%2C%20T.untyped%5D).void%7D%0A%20%20def%20initialize(hash%3D%7B%7D)%0A%20%20%20%20super%0A%20%20%20%20%40baz%20%3D%20T.let(4%2C%20Integer)%0A%20%20end%0Aend)

Super high level: I often have `T::Struct`s with instance variables. I'd like to make the file `strict`. It's very annoying to define `initialize` functions on those structs because I need to duplicate all the props / types as arguments to the constructor.

To dig a layer deeper, I often have instance variables on `T::Struct`s because there's some function that wants to memoize itself.

### Proposed solution

I think we should have a syntax for declaring the types of instance variables that doesn't force you to declare an `initialize` function.

Alternatively, Stripe internally needs to find a way to eliminate these use cases for instance variables (e.g., a standard memoization mechanism)

**Comment by jez** [comment]
Fixed in #1645
