### ISSUE TITLE
Unexpected code is unreachable

### ISSUE THREAD

**Issue by oliver-stripe** [sorbet/sorbet#1438]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20T%3A%3ABoolean).void%7D%0A%20%20def%20testing(x)%0A%20%20%20%20bar%20%3D%20!x%0A%20%20%20%20zap%20%3D%20!bar%20%7C%7C%20123%0A%0A%20%20%20%20if%20x%0A%20%20%20%20%20%20raise%0A%20%20%20%20end%0A%0A%20%20%20%20bar%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: T::Boolean).void}
  def testing(x)
    bar = !x
    zap = !bar || 123

    if x
      raise
    end

    bar
  end
end
```

#### Observed output

```
editor.rb:11: This code is unreachable https://srb.help/7006
    11 |      raise
              ^^^^^

editor.rb:14: This code is unreachable https://srb.help/7006
    14 |    bar
            ^^^
Errors: 2
```

#### Expected behavior

Code should not be unreachable

**Comment by azdavis** [comment]
I wasn't sure how the `raise` was interacting with the unreachable errors and I also wanted to see what would happen if an `else`-branch was added. The result:

```rb
# typed: true
class A
  extend T::Sig

  sig {params(x: T::Boolean).void}
  def testing(x)
    bar = !x
    zap = !bar || 123

    if x
      puts
    else
      puts
    end

    bar
  end
end
```

Both of the puts, as well as the bar, are unreachable. However, removing the bar results in no errors.
