### ISSUE TITLE
Changing strictlevel of a file doesn't cause report errors that were previously silenced at that level

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#1447]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0AA%20%3D%20%27foo%27.freeze)

```ruby
# typed: true

A = 'foo'.freeze
```

#### Steps to reproduce

1. Open the URL above
2. Edit `true` to `strict`
3. Observe that there’s a pipeline error but no red squiggle in the editor

#### Expected behavior

The pipeline output (showing an error saying that a constant needs a type) should show up in the editor as well.

**Comment by jvilk-stripe** [comment]
Cannot reproduce. I believe this was broken but is now fixed. I'll keep open until I add a test to the test suite to cover this edge case.

**Comment by jvilk-stripe** [comment]
This is no longer a problem.
