### ISSUE TITLE
Support for Ruby 2.6's String#lines

### ISSUE THREAD

**Issue by openbl** [sorbet/sorbet#1462]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aputs%20%22hello%5Cnworld%22.lines(chomp%3A%20true))

```ruby
# typed: true
puts "hello\nworld".lines(chomp: true)
```

#### Observed output

```
editor.rb:2: Expected String but found {chomp: TrueClass} for argument arg0 https://srb.help/7002
     2 |puts "hello\nworld".lines(chomp: true)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/0c6bdf75780d2f5dd627c7054ce09c67a938304f/rbi/core/string.rbi#L435: Method String#lines has specified arg0 as String
     435 |        arg0: String,
                  ^^^^
  Got {chomp: TrueClass} originating from:
    editor.rb:2:
     2 |puts "hello\nworld".lines(chomp: true)
                                  ^^^^^^^^^^^
Errors: 1
```

Observed at 2019-08-01 04:59:46 UTC.

#### Expected behavior

I would expect `String#lines` to support its keyword arguments, `getline_args`<sup>[1]</sup>

[1]: https://ruby-doc.org/core-2.6.3/String.html#method-i-lines

---

P.S. Feel free to close if you're tracking 2.6 support elsewhere. Thanks for the tool!

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
