### ISSUE TITLE
error on strong typed abstract! classes

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#1489]
https://sorbet.run/#%23%20typed%3A%20strong%0Aclass%20Test%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0Aend
```
$ cat test.rb
# typed: strong
class Test
  extend T::Helpers
  abstract!
end
$ srb tc test.rb
test.rb:4: This code is untyped https://srb.help/7018
     4 |        abstract!
         ^^^^^^^^^
Errors: 1
```

If `# typed: strict` or less, everything is fine.

Maybe slightly related: #274 _Missing type error for interface! or abstract!_

**Comment by aisamanra** [comment]
This is genuinely an error, but I should warn that we're deeply unlikely get around to a fix for it in the short term. As of right now, the `# typed: strong` level is effectively impossible to use for almost anything but the most trivial Ruby code, and we'll need to do a lot more work to get into practical usable shape—something that we would like to do but is not on our short-term roadmap. Our current practical advice is to stick to `# typed: strict` or below for the time being.
