### ISSUE TITLE
Annotate function return value type.

### ISSUE THREAD

**Issue by sgxadhith** [sorbet/sorbet#1490]
### Problem

In TypeScript, you can annotate a function like the below example.
```
function add(x: number, y: number): number {
    return x + y;
}

let myAdd = function(x: number, y: number): number { return x + y; };
```

Pardon me as I am extremely new to using Sorbet, but it would be incredibly useful to be able to annotate the return value of a function in or outside a class. Please do inform me if I am ignorant of such a feature already existing in sorbet.

**Comment by jasnow** [comment]
@sgxadhith - What have you tried?

**Comment by sgxadhith** [comment]
I do not know how to get this to work. The ```sig ``` helps me to annotate parameters but I have no idea how to get the return value to be annotated.

**Comment by jasnow** [comment]
Here is an example from sorbet.org web site with **sig {returns(Integer)}** https://sorbet.run/#%23%20typed%3A%20true%0A%23%20typed%3A%20true%0Arequire%20'sorbet-runtime'%0A%0Aclass%20Main%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(Integer)%7D%0A%20%20def%20self.main%0A%20%20%20%2042%0A%20%20end%0Aend

**Comment by azdavis** [comment]
You can learn more about `sig` on the [website](https://sorbet.org/docs/sigs).

**Comment by aisamanra** [comment]
The Ruby+Sorbet equivalent to your example is
```ruby
sig { params(x: Integer, y: Integer).returns(Integer) }
def add(x, y)
  x + y
end
```
How to annotate return types in Sorbet is documented [in our online documentation](https://sorbet.org/docs/sigs#returns-void-annotating-return-types).

I'm going to close this issue, but if you have future questions, we'd be happy to answer them.
