### ISSUE TITLE
Support table-driven tests with minitest it / describe blocks

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#1504]
I've seen this in particular when using `Minitest`:

#### Input

```ruby
class MyTest < Minitest::Spec
    def foo(x); end

    [1,2].each do |x|
      it "is happy with #{x}"
          foo(x) # sorbet complains about `foo` not existing, although runtime works just fine
      end
    end
end
```

#### Observed output
Sorbet complains about `foo` not existing while typechecking (runtime has no issues)

#### Expected behavior
Sorbet should not complain about `foo`

**Comment by jez** [comment]
This is specific to minitest. We have a DSL that looks for `it` and `describe` blocks. Putting them inside an `Array#each` call hides them from the DSL pass. The file that handles this is here:

https://github.com/sorbet/sorbet/blob/master/dsl/Minitest.cc

Marking this as good first issue.

**Comment by axyjo** [comment]
Ran into this at work today (cc @akshay-stripe)
