### ISSUE TITLE
Better formatting for LSP sigs on hover

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1516]
### Problem

Once a signature gets sufficiently complex, it's very hard to read:
![image](https://user-images.githubusercontent.com/2977353/62671763-59b67800-b955-11e9-9eae-4e0eab6ef0d6.png)

I know ideally we wouldn't have signatures like this at all, but that's not really possible with Rails. The API can't be changed significantly at this point :)

You can see this on [sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20name%3A%20Symbol%2C%0A%20%20%20%20%20%20scope%3A%20T.nilable(T.proc.void)%2C%0A%20%20%20%20%20%20after_add%3A%20T.nilable(T.any(Symbol%2C%20String%2C%20T.proc.void))%2C%0A%20%20%20%20%20%20after_remove%3A%20T.nilable(T.any(Symbol%2C%20String%2C%20T.proc.void))%2C%0A%20%20%20%20%20%20anonymous_class%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20as%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20autosave%3A%20T.nilable(T%3A%3ABoolean)%2C%0A%20%20%20%20%20%20before_add%3A%20T.nilable(T.any(Symbol%2C%20String%2C%20T.proc.void))%2C%0A%20%20%20%20%20%20before_remove%3A%20T.nilable(T.any(Symbol%2C%20String%2C%20T.proc.void))%2C%0A%20%20%20%20%20%20class_name%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20counter_cache%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20dependent%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20extend%3A%20T.nilable(T.any(Module%2C%20T%3A%3AArray%5BModule%5D))%2C%0A%20%20%20%20%20%20foreign_key%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20foreign_type%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20index_errors%3A%20T.nilable(T%3A%3ABoolean)%2C%0A%20%20%20%20%20%20inverse_of%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20join_table%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20primary_key%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20source%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20source_type%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20table_name%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20through%3A%20T.nilable(T.any(Symbol%2C%20String))%2C%0A%20%20%20%20%20%20validate%3A%20T.nilable(T%3A%3ABoolean)%2C%0A%20%20%20%20%20%20blk%3A%20T.nilable(T.proc.void)%0A%20%20%20%20).void%0A%20%20end%0A%20%20def%20has_many(%0A%20%20%20%20name%2C%0A%20%20%20%20scope%20%3D%20nil%2C%0A%20%20%20%20after_add%3A%20nil%2C%0A%20%20%20%20after_remove%3A%20nil%2C%0A%20%20%20%20anonymous_class%3A%20nil%2C%0A%20%20%20%20as%3A%20nil%2C%0A%20%20%20%20autosave%3A%20nil%2C%0A%20%20%20%20before_add%3A%20nil%2C%0A%20%20%20%20before_remove%3A%20nil%2C%0A%20%20%20%20class_name%3A%20nil%2C%0A%20%20%20%20counter_cache%3A%20nil%2C%0A%20%20%20%20dependent%3A%20nil%2C%0A%20%20%20%20extend%3A%20nil%2C%0A%20%20%20%20foreign_key%3A%20nil%2C%0A%20%20%20%20foreign_type%3A%20nil%2C%0A%20%20%20%20index_errors%3A%20nil%2C%0A%20%20%20%20inverse_of%3A%20nil%2C%0A%20%20%20%20join_table%3A%20nil%2C%0A%20%20%20%20primary_key%3A%20nil%2C%0A%20%20%20%20source%3A%20nil%2C%0A%20%20%20%20source_type%3A%20nil%2C%0A%20%20%20%20table_name%3A%20nil%2C%0A%20%20%20%20through%3A%20nil%2C%0A%20%20%20%20validate%3A%20nil%2C%0A%20%20%20%20%26blk%0A%20%20)%3B%20end%0Aend%0A%0Amodule%20B%0A%20%20extend%20A%0A%0A%20%20has_many%20%3Apeople%0Aend) if you hover over the `has_many` at the bottom of the file.

### Proposed solution

I'd like if the signatures were formatted so that – either for every parameter no matter what or once a signature gets to a certain length - the parameters were each separated onto their own lines, like so:

```ruby
sig do
  params(
    name: Symbol,
    scope: T.nilable(T.proc.void),
    after_add: T.nilable(T.any(Symbol, String, T.proc.void)),
    after_remove: T.nilable(T.any(Symbol, String, T.proc.void)),
    anonymous_class: T.nilable(T.any(Symbol, String)),
    as: T.nilable(T.any(Symbol, String)),
    autosave: T.nilable(T::Boolean),
    before_add: T.nilable(T.any(Symbol, String, T.proc.void)),
    before_remove: T.nilable(T.any(Symbol, String, T.proc.void)),
    class_name: T.nilable(T.any(Symbol, String)),
    counter_cache: T.nilable(T.any(Symbol, String)),
    dependent: T.nilable(T.any(Symbol, String)),
    extend: T.nilable(T.any(Module, T::Array[Module])),
    foreign_key: T.nilable(T.any(Symbol, String)),
    foreign_type: T.nilable(T.any(Symbol, String)),
    index_errors: T.nilable(T::Boolean),
    inverse_of: T.nilable(T.any(Symbol, String)),
    join_table: T.nilable(T.any(Symbol, String)),
    primary_key: T.nilable(T.any(Symbol, String)),
    source: T.nilable(T.any(Symbol, String)),
    source_type: T.nilable(T.any(Symbol, String)),
    table_name: T.nilable(T.any(Symbol, String)),
    through: T.nilable(T.any(Symbol, String)),
    validate: T.nilable(T::Boolean),
    blk: T.nilable(T.proc.void)
  ).void
end
```

**Comment by DarkDimius** [comment]
@connorshea, this should be easy to fix, do you want to take a stab at it?

**Comment by DarkDimius** [comment]
Seems like https://github.com/sorbet/sorbet/blob/898570aae6cbffcba4778ee254639c0b1ab1acc1/main/lsp/lsp_helpers.cc#L225 is the method that needs updating
