### ISSUE TITLE
Fast path: Autocorrect for rbi methods with code does not appear

### ISSUE THREAD

**Issue by sushain97** [sorbet/sorbet#1518]
#### Input

```ruby
# typed: true
class C
  def foo; 42 end
end
```

#### Observed output

![image](https://user-images.githubusercontent.com/4211838/62675102-4d80e980-b95a-11e9-80a5-7bf56c4640fb.png)

#### Expected behavior

Should have the autocorrect in code actions.

**Comment by jvilk-stripe** [comment]
Note: You need to set this setting to tell VS Code that rbi is a Ruby file. Otherwise, it won't use the Sorbet extension in the file. I'm guessing it's not sending the `codeAction` request (you should check in the log).

```
"files.associations": {
    // Enables syntax highlighting for Sorbet type definition files.
    "*.rbi": "ruby"
  },
```

**Comment by sushain97** [comment]
pebcak
