### ISSUE TITLE
Metaprogramming plugin causes suggest-typed and TODO commands to hang

### ISSUE THREAD

**Issue by panthomakos** [sorbet/sorbet#1519]
#### Input

I am unable to provide a link to `sorbet.run`, but you can find the files for this example here: https://gist.github.com/panthomakos/ef5264269bcd568755a5d01182433417

Using this simple project, running `srb init` will hang on the TODO step. If you remove the `triggers.yml` config, initialize the project, then add it back and run `srb rbi suggest-typed`, the command will hang or not converge after 50 tries.

#### Expected behavior

Suggested types are able to work with a basic meta-programming example.

**Comment by jez** [comment]
We deleted metaprogramming plugins in #3983
