### ISSUE TITLE
Metaprogramming Ergonmics

### ISSUE THREAD

**Issue by deecewan** [sorbet/sorbet#1520]
### Problem

There are a couple of things I've noticed when trying to use the metaprogramming DSL plugin interface. I understand that it's still early days, but I want to get in before you lock it down completely.

- Generating the surrounding `class Name` and `end` is cute, but it doesn't make it easy to, for instance, add a sigil to the generated file. This bit me because I tried to add a sig to a method I was generating.

- I don't always want to generate method on the class that i'm currently inside of. In my case, I was adding types for `pg_search_scope`, which generates `ActiveRecord` scopes. So, I needed to open the `Name::ActiveRecord_Relation` class and add some types in there.

- Because the plugins generate `.rb`, and not `.rbi` files, I had to add in dummy method definitions (`T.unsafe(1)` was an easy one). I can't see a reason why these would ever have to generate non-`rbi` files - the code can never (I hope) be used at runtime.

### Proposed solution

- Metaprogramming plugins generate `.rbi` files
- They provide no surrounding `class` information, _or_ provide a way to say "I'm going to do all of the output this time", in which case, it's disabled
- Add a way to add the sigil to the file. If I have enough information to generate safe types in those files, I should be able to without hacks.

Speaking of hacks, this is what I came up with for `pg_search_scope`. It might give you an idea of the ergonomics I'm talking about. Note the comments in the output are for the sanity of the next person who works on this file.

```rb
klass = ARGV[1] # the name of the class we're inside of
source = ARGV[5] # the source code that caused this plugin to run

/pg_search_scope[\( ]\n?:(\w+)/.match(source) do |match_data|
  puts <<~RUBY
  # class #{klass} <- inserted by macro
    sig { params(arg: String).returns(#{klass}::ActiveRecord_Relation) }
    def self.#{match_data[1]}(arg); T.unsafe(1); end
  end
  # typed: strict
  class #{klass}::ActiveRecord_Relation
    sig { params(arg: String).returns(#{klass}::ActiveRecord_Relation) }
    def #{match_data[1]}(arg); self; end
  # end <- inserted by macro
  RUBY
end
```

**Comment by manhhung741** [comment]
FYI if you’re trying to generate methods for rails models, `sorbet-rails` now support a plugin system that makes it easy to add your own generation logic to models. I still need to document it more, but there are examples in the PR & the source code. Lmk if you’re interested, I can give you more details.

**Comment by deecewan** [comment]
@manhhung741 very keen to see this, please. I was thinking about just forking the repo.

**Comment by manhhung741** [comment]
This is an example that Connor added a plugin for Kaminari. He was adding a
method to the shared relation scope that lets you chain relation methods
(seems to be similar to what you’re trying to do).

https://github.com/chanzuckerberg/sorbet-rails/pull/109/files

If it’s what you're looking for, here is the actual plugin that generate
sig for named scopes in rails model.

https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/model_plugins/active_record_named_scope.rb

To define your plugin, just subclass the Base class and implement
`generate(root)` method. We use parlour gem for rbi generation and it is
pretty easy to use: https://github.com/AaronC81/parlour

This is an example of how you can register a plugin in initializer

https://github.com/chanzuckerberg/sorbet-rails/blob/de41f8acb87404ed85c2f535333825f8a7677be6/spec/support/rails_shared/config/initializers/sorbet_rails.rb

If you generate methods for a public gem, feel free to send me a PR to
share it with others!

**Comment by DarkDimius** [comment]
@deecewan , the approach that sorbet-rails takes would work better than Ruby based DSL plugins for multiple reasons, in particular, it'll work better for IDE. I'd suggest having a look how it works and cargo culting it.

**Comment by manhhung741** [comment]
Let me know if you run into any issues. I’m in the process of documenting
all this. I just haven’t had time to finish it yet.

**Comment by panthomakos** [comment]
Related to #1519 (the meta-programming DSL use causes a few commands to hang). I took the advice from this issue and wrote a Rake task to generate full RBI files instead of using the meta-programming plugin and that resolved the issues and feels much more sustainable.

**Comment by manhhung741** [comment]
Yay. Awesome. Curious what meta-programming thingy you’re dealing with?

**Comment by panthomakos** [comment]
We have a DSL for feature toggles that generates a few methods per toggle: for example to turn on/off the toggles or check if they are flipped. While it's possible to generate the methods using hidden definitions this process takes waaay too long and is not something we would be able to run on a regular basis or after updating code to add a new toggle. In contrast, the RBI generation is super fast even by loading the entire code base and generating the methods from scratch. Would love for this general framework to be built into sorbet itself. It seems superior to existing meta-programming approach. I am currently using something similar to what `sorbet-rails` does to accomplish this.

**Comment by XrXr** [comment]
Thanks for trying out the plugin system. As others have pointed out, generating rbi files is pretty much *the way* to deal with metaprogramming right now. Here's what I the status quo of the two approaches are:

|                | Typecheck performance | Compatibility with unreleased editor integration | Accuracy                        | Ease of authoring               |
|----------------|-----------------------|--------------------------------|---------------------------------|---------------------------------|
| Plugins        | horrendous            | no                             | Always up to date with your code | Okay if you use `instance_eval` |
| rbi generation | great                 | yes                            | Could go out-of-sync            | okay                            |
|                |                       |                                |                                 |                                 |


 
> Generating the surrounding class Name and end is cute, but it doesn't make it easy to, for instance, add a sigil to the generated file. This bit me because I tried to add a sig to a method I was generating.

Sorbet picks up sigils anywhere in the file so you don't need to do the end trick:
https://sorbet.run/#class%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20bar(x)%0A%20%20%20%20%23%20typed%3A%20strict%0A%20%20%20%20x.to_s%0A%20%20end%0Aend%0A

> I don't always want to generate method on the class that i'm currently inside of. In my case, I was adding types for pg_search_scope, which generates ActiveRecord scopes. So, I needed to open the Name::ActiveRecord_Relation class and add some types in there.

You can define/reopen a class in the global scope from anywhere by saying `class ::Thing`: https://sorbet.run/#class%20A%0A%20%20class%20%3A%3AFoo%0A%20%20%20%20extend%20T%3A%3ASig%0A%0A%20%20%20%20sig%20%7Breturns(Integer)%7D%0A%20%20%20%20def%20self.bar%0A%20%20%20%20%20%20%23%20typed%3A%20strict%0A%20%20%20%20%20%203%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0AT.reveal_type(Foo.bar)%0A
(this works at runtime too)

> Because the plugins generate .rb, and not .rbi files, I had to add in dummy method definitions (T.unsafe(1) was an easy one).

Good call! I submitted #1605 to make this change.

---

Overall I'm quite pessimistic about Sorbet getting strong support for arbitrary metaprogramming anytime soon. It doesn't seem to be a priority for the Sorbet team (correct me if I'm wrong). Assuming this is true, rbi generation will remain the way to go for the foreseeable future.

**Comment by deecewan** [comment]
@XrXr thanks for the response! It's really well thought out - I appreciate it.

I would _love_ if Sorbet would give access to the AST and let me generate an RBI based on hooks in the AST, similar to how Babel works to transform JS code. I started playing with this idea as a third-party plugin, which I'll likely end up building, but there is not a (super nice) way of generating that AST, as far as I could tell. There is not, in my research, anything that generates an AST and provides hooks into it to generate new code.

**Comment by XrXr** [comment]
> I started playing with this idea as a third-party plugin, which I'll likely end up building

Cool stuff! I would love to see a performant plugin system for Sorbet that's more convenient to work with than C++. I lost motivation for trying to improve Sorbet's plugin system because I couldn't get feedback from Stripe readily. I wish I had #1485 when I tried to implement my things.

Ideally the plugin system would have type information in addition to the AST. I made the current plugin system for ActiveRecord's `attribute` but could not proceed as we use too many metaprogramming APIs that are called `attribute`. The different APIs also had similar usages. Basically, the [first caveat](https://sorbet.org/docs/metaprogramming-plugins#caveats) in the docs is a fatal limitation for me. As far as I can tell, anything built with #1485 suffers from the same problem.

Just to hit the point home, Sorbet makes some decisions without type info and so can be tricked to accept the following buggy program:
```ruby
# typed: true
module M
  def hoho; end
end
class A
  def self.extend; end
  extend M # runtime crash 1
end
A.hoho # runtime crash 2
```
But this is more a pragmatic simplification than a show stopper like it is for the plugin system.

This is not to say that a great AST based plugin system would not be useful for many use cases and users. My ideal plugin system departs very far from how Sorbet currently works, perhaps in fundamental ways. I don't think Stripe is very interested in this area and fundamental changes go through Stripe. It might never be built.

**Comment by deecewan** [comment]
i essentially want to generate rbi files for `graphql-ruby`-based files. They have a lot of implicit data, based on the `field` method, and I want to be able to model that, more or less. If I had an AST, even without type info, I'd be able to generate that.

Also, the `pg_search_scope` example I covered here could easily be done by trying to find a method call of that name. Ideally, having the runtime available as well would let me do stuff like `@model_class.ancestors`, like you can do with the `sorbet-rails` system. However, the limitation of _that_ system for this example is there is no way for me to figure out what method calls are made, and in this particular example, there is nothing attached to the model that tells me the scope is of a particular kind. I'm sure @manhhung741 can let me know if the file source is available inside a `sorbet-rails` plugin.

**Comment by manhhung741** [comment]
@david: would you mind describe the situation you have to deal with? I’m
not familiar with graphql-ruby but we might start using it at EOY so I’m
keen to know what are the challenges with sorbet.

Essentially `sorbet-rails` is a runtime environment, and everything in ruby
is constructed at runtime. I’m sure we can figure something out. Recently I
had to resort to `method_added` hook for example to deal with a case. You
can also invoke methods, find callers etc. Those things aren’t built into
the system yet, but I’d like to think we can do something about that.

We have documentation for the plugin system now btw:
https://github.com/chanzuckerberg/sorbet-rails/blob/master/README.md#extending-model-generation-task-with-custom-plugins

@dmitry: I’m interested to learn more about the plugin system supported by
SemanticExtensions #1485. It could be useful for some stuff we defined
internally. Is there any documentation for it yet?

**Comment by deecewan** [comment]
@manhhung741 it's not for `graphql-ruby` - in this case it's for `pg_search_scope`. It's a method that adds an activerecord scope. If I know what scope it's added, I can created good types for it, but I can't see the source code from within the `sorbet-rails` AFAIK, so I can't do anything there. I would need, essentially, a hook to say 'this method was called with these arguments'. I am not a rubyist so I'm not sure how viable that is.

**Comment by manhhung741** [comment]
@deecewan: can you give me an example of how `pg_search_scope` is called, what scope would it add?

I wonder if you look up `@model_class.methods`, the scope is added there?

I looked up `pg_search` gem, but I only found that it would add a `search_for` method/scope.

**Comment by deecewan** [comment]
@manhhung741 the link is here: https://github.com/Casecommons/pg_search#pg_search_scope

it's used like

```rb
class MyModel < ApplicationRecord
  pg_search_scope :search_by_name, { other: 'stuff' }
end
```

The `search_by_name` method shows up, but unfortunately there is no way (that I can see) to figure out that it's a `pg_search_scope` invocation :(

**Comment by manhhung741** [comment]
@deecewan: you can find the source_location of a method. It should come
from the gem. You can see how we do similar thing in the NamedScope plugin

https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/model_plugins/active_record_named_scope.rb#L17

**Comment by manhhung741** [comment]
Based on my quick search, the source_location of the method should be here

lib/pg_search/model.rb

The actual code that adds the method is this

https://github.com/Casecommons/pg_search/blob/b55d01a34a54e73b443faf49a6b3d961b4da08a3/lib/pg_search/model.rb#L17

**Comment by deecewan** [comment]
oh cool! i'll take a look at that 😄

**Comment by manhhung741** [comment]
@deecewan: do you manage to make it work?

If yes, would you like to make a PR to contribute the plugin to
`sorbet-rails` repo? I know another person working on a pg search plugin
that I think you can collaborate.

If not, feel free to ping me for any issue. You’re welcome to post on the
#rails channel on sorbet-ruby slack group!

**Comment by jez** [comment]
Thanks everyone for the conversation! Love to see it. I'm going to close this issue so that open issues can represent "work that needs to be done." if anything comes out of this conversation that fits the bill, feel free to make a separate issue with a minimal explanation.

And feel free to keep using this issue to chat, or to chat on the sorbet-ruby slack group.
