### ISSUE TITLE
Refining implementation return type as more specified raises an exception in runtime

### ISSUE THREAD

**Issue by smt116** [sorbet/sorbet#1543]
## Note

This has been initially reported as https://github.com/sorbet/sorbet/issues/1296 but has been misread and closed. I've pinged DarkDimius twice but without any response.

---

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0A%23%20Sorbet%20won't%20complain%20about%20the%20following%20code%20while%20analyzing.%0A%23%20However%2C%20it%20will%20raise%20an%20exception%20in%20runtime%3A%0A%0A%23%20%20%20RuntimeError%3A%20Incompatible%20return%20type%20in%20implementation%20of%20method%20%60params%60%3A%0A%23%20%20%20%20*%20Base%3A%20%60T%3A%3AHash%5BT.untyped%2C%20T.untyped%5D%60%20(in%20%23%3CClass%3ABase%3E%20at%20%2FUsers%2Fsmefju%2Ftmp%2Ffoo.rb%3A12)%0A%23%20%20%20%20*%20Implementation%3A%20%60%7Bfoo%3A%20Integer%7D%60%20(in%20%23%3CClass%3AFoo%3E%20at%20%2FUsers%2Fsmefju%2Ftmp%2Ffoo.rb%3A19)%0A%23%20%20%20%20(The%20types%20must%20be%20covariant.)%0A%23%20%20%20%20from%20%2FUsers%2Fsmefju%2F.rbenv%2Fversions%2F2.6.3%2Flib%2Fruby%2Fgems%2F2.6.0%2Fgems%2Fsorbet-runtime-0.4.4405%2Flib%2Ftypes%2Fprivate%2Fmethods%2Fsignature_validation.rb%3A211%3Ain%20%60validate_override_types'%0A%0Aclass%20Base%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.params(flag%3A%20T%3A%3ABoolean).returns(Hash)%20%7D%0A%20%20def%20self.params(flag)%3B%20end%20%0Aend%20%0A%0Aclass%20Foo%20%3C%20Base%0A%20%20Params%20%3D%20T.type_alias(foo%3A%20Integer)%0A%0A%20%20sig%20%7B%20implementation.params(flag%3A%20T%3A%3ABoolean).returns(Params)%20%7D%0A%20%20def%20self.params(flag)%20%0A%20%20%20%20if%20flag%0A%20%20%20%20%20%20%7B%20foo%3A%201%20%7D%0A%20%20%20%20else%0A%20%20%20%20%20%20%7B%20foo%3A%2010%20%7D%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Aclass%20Bar%20%3C%20Base%0A%20%20Params%20%3D%20T.type_alias(bar%3A%20String)%0A%0A%20%20sig%20%7B%20implementation.params(flag%3A%20T%3A%3ABoolean).returns(Params)%20%7D%0A%20%20def%20self.params(flag)%20%0A%20%20%20%20%7B%20bar%3A%20flag%20%3F%20%22Yes%22%20%3A%20%22No%22%20%7D%0A%20%20end%0Aend%0A%0AFoo.params(true)%0ABar.params(false))

```ruby
# typed: strict

class Base
  extend T::Helpers
  extend T::Sig

  abstract!

  sig { abstract.params(flag: T::Boolean).returns(Hash) }
  def self.params(flag); end 
end 

class Foo < Base
  # Params is still a `Hash` from abstract
  Params = T.type_alias(foo: Integer)

  sig { implementation.params(flag: T::Boolean).returns(Params) }
  def self.params(flag) 
    if flag
      { foo: 1 }
    else
      { foo: 10 }
    end
  end
end

class Bar < Base
  # Params is still a `Hash` from abstract
  Params = T.type_alias(bar: String)

  sig { implementation.params(flag: T::Boolean).returns(Params) }
  def self.params(flag) 
    { bar: flag ? "Yes" : "No" }
  end
end

Foo.params(true)
Bar.params(false)
```

#### Observed output

The static analyze does not report any errors (correct!):

```
No errors! Great job.
```

However, the code raises an exception in the runtime:

```
RuntimeError: Incompatible return type in implementation of method `params`:
* Base: `T::Hash[T.untyped, T.untyped]` (in #<Class:Base> at /Users/smefju/tmp/foo.rb:12)
* Implementation: `{foo: Integer}` (in #<Class:Foo> at /Users/smefju/tmp/foo.rb:19)
(The types must be covariant.)
from /Users/smefju/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4405/lib/types/private/methods/signature_validation.rb:211:in `validate_override_types'
```

#### Expected behavior

Runtime should be consistent with static analyze and do not raise any errors when abstract defines return type as untyped hash and the implementation specifies the hash.

**Comment by jez** [comment]
It looks like in the runtime we make FixedHash invariant with TypedHash.

It's probably ok to make FixedHash in the runtime a subtype of TypedHash, but in particular we really shy away from shape types / hashes in general, because we have ~terrible support for them across the board. See https://sorbet.org/docs/shapes for more examples of where they're broken.

In general, you'll probably have a more pleasant time just not using shape types.
