### ISSUE TITLE
not checking missing instance variable initialization on overridden initialize

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#1545]
If the static checker encounters an instance variable (e.g. `@name`), it requires the `initialize` method to declare that variable.

But if the `initialize` method is overridden by the child, the static checker won't get that.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20attr_reader%20%3Aname%0A%0A%20%20sig%20%7Bparams(new_name%3A%20String).void%7D%0A%20%20def%20initialize(new_name)%0A%20%20%20%20%40name%20%3D%20T.let(new_name%2C%20String)%0A%20%20end%0Aend%0A%0A%0Aclass%20Child%20%3C%20Parent%0A%20%20%23%20ERROR!%20-%20Forgot%20to%20initialize%20name.%0A%20%20sig%20%7Bparams(new_name%3A%20String).void%7D%0A%20%20def%20initialize(new_name)%3B%20end%0Aend%0A%0Aputs%20Parent.new('Test').name%20%20%23%20Test%0Aputs%20Child.new('Test').name%20%20%23%20%3D%3E%20Expected%20type%20String%2C%20got%20type%20NilClass%20(TypeError))

```ruby
# typed: strict


class Parent
  extend T::Sig

  sig {returns(String)}
  attr_reader :name

  sig {params(new_name: String).void}
  def initialize(new_name)
    @name = T.let(new_name, String)
  end
end


class Child < Parent
  # ERROR! - Forgot to initialize name.
  sig {params(new_name: String).void}
  def initialize(new_name); end
end

puts Parent.new('Test').name  # Test
puts Child.new('Test').name  # => Expected type String, got type NilClass (TypeError)
```

&nbsp;

--

&nbsp;

Another problem evolves from this bug.
You might want to write an abstract class, containing an attr_reader for an instance variable which the child must provide.
Again, the static checker misses to check the child's `initialize` for the `@name` declaration.

&nbsp;
Workarounds - but I consider both ugly.
- Write a dummy `initialize` in `Abs`,  which is never called. So you can declare `@name` in that dummy `initialize`.
- Replace `attr_reader :name` with `sig {abstract.returns(String)}; def name; end` and write `attr_reader :name` manually into every child. 

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0A%0Aclass%20Abs%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20attr_reader%20%3Aname%0A%20%20%23%20%3D%3E%20Use%20of%20undeclared%20variable%20%40name%0A%0A%20%20sig%20%7Babstract.params(new_name%3A%20String).void%7D%0A%20%20def%20initialize(new_name)%3B%20end%0Aend%0A%0A%0Aclass%20ImplA%20%3C%20Abs%0A%20%20sig%20%7Bimplementation.params(new_name%3A%20String).void%7D%0A%20%20def%20initialize(new_name)%0A%20%20%20%20%40name%20%3D%20T.let(new_name.upcase%2C%20String)%0A%20%20end%0Aend%0A%0Aclass%20ImplB%20%3C%20Abs%0A%20%20sig%20%7Bimplementation.params(new_name%3A%20String).void%7D%0A%20%20def%20initialize(new_name)%0A%20%20%20%20%40name%20%3D%20T.let(new_name.downcase%2C%20String)%0A%20%20end%0Aend)

```ruby
# typed: strict


class Abs
  extend T::Sig
  extend T::Helpers
  abstract!

  sig {returns(String)}
  attr_reader :name
  # => Use of undeclared variable @name

  sig {abstract.params(new_name: String).void}
  def initialize(new_name); end
end


class ImplA < Abs
  sig {implementation.params(new_name: String).void}
  def initialize(new_name)
    @name = T.let(new_name.upcase, String)
  end
end

class ImplB < Abs
  sig {implementation.params(new_name: String).void}
  def initialize(new_name)
    @name = T.let(new_name.downcase, String)
  end
end
```

**Comment by jez** [comment]
The proper solution here is to rubocop to require that constructors must call `super`. This assumption is central to pretty much all object-oriented languages.
