### ISSUE TITLE
documentSymbols many wrong symbols with syntax error

### ISSUE THREAD

**Issue by azdavis** [sorbet/sorbet#1554]
## input

```rb
# typed: true
class C
  @@foo = T.let(3, Integer)

  def bar
    @@quz
  end
end
```

1. Start with this file
1. Delete `quz` but not the leading `@@` (this produces a syntax error)
1. Put cursor directly after `@@foo`
1. Type `d`

## Expected symbols

Either replace the `@@foo` symbol with `@@food`, resulting in

- `C`
- `@@food`

Or don't change anything, resulting in

- `C`
- `@@foo`

Since there's a syntax error later in the file, it's arguable that we don't want
to both trying to figure out the symbols for this file.

## Actual symbols

- `C`
- `@@foo`
- `@@food`

---

Note that for every `d` press, we keep adding a new symbol.

**Comment by DarkDimius** [comment]
This is a bug in global state hashing. It should also hash fields but it doesn't.
