### ISSUE TITLE
T.proc doesn't match method(:bar).proc

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#1564]
This should match, but it doesn't.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bparams(b%3A%20T.proc.void).void%7D%0Adef%20foo(b)%3B%20end%0A%0Asig%20%7Bvoid%7D%0Adef%20bar%3B%20end%0A%0Afoo(method(%3Abar).proc)%0A)
```
# typed: true
extend T::Sig

sig {params(b: T.proc.void).void}
def foo(b); end

sig {void}
def bar; end

foo(method(:bar).proc)
# Expected T.proc.returns(Sorbet::Private::Static::Void) but found Proc for argument b
```

**Comment by DarkDimius** [comment]
This is intentional. 
`T.proc.returns(Sorbet::Private::Static::Void)` is a Proc of _known_ arity - it takes 0 arguments.
While `method(:bar).proc` is known to be a Proc but it's arity isn't known.

**Comment by md-work** [comment]
> This is intentional.
> `T.proc.returns(Sorbet::Private::Static::Void)` is a Proc of _known_ arity - it takes 0 arguments.
> While `method(:bar).proc` is known to be a Proc but it's arity isn't known.

I understand :-/

Is there another way than manually building a proc, where Sorbet can work? Because manually building a proc really gets ugly if there are parameters.
```
sig {params(s: String, i: Integer).void}
def bar(s, i); end

foo(proc { |a,b| bar(a, b) })

# This also seems to be not possible for Sorbet.
foo(proc { |*a| bar(*a) })
```

As said, I understand why.
I'm just asking if there's maybe a more beautiful alternative I didn't thought of.
