### ISSUE TITLE
Support __ENCODING__

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#1629]
#### Input

```ruby
# typed: true

__ENCODING__
```

#### Observed output

```
parse_encoding_.rb:3: Unsupported node type EncodingLiteral https://srb.help/3003
     3 |__ENCODING__
        ^^^^^^^^^^^^
```

#### Expected behavior

works, maybe even has a type(not strictly required)

- - -

This is https://github.com/sorbet/sorbet/blob/master/test/testdata/disabled/whitequark/parse_encoding_.rb

**Comment by Morriar** [comment]
Fixed by https://github.com/sorbet/sorbet/pull/3319.
