### ISSUE TITLE
LSP: Include method def in hover text

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#1640]
### Problem

Hover text for a method only shows a sig, which doesn't indicate if an argument is a position parameter or a named parameter.

[Check it out on Sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).returns(String)%7D%0A%20%20def%20self.bar(x%3A)%0A%20%20%20%20%22%22%0A%20%20end%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).returns(String)%7D%0A%20%20def%20self.bat(x)%0A%20%20%20%20%22%22%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20%23%20Hover%20over%20the%20two%20methods%20below.%20They%20look%20identical%2C%0A%20%20%23%20but%20one%20uses%20a%20named%20argument%20rather%20than%20a%20position%20argument!%0A%20%20A.bar%0A%20%20A.bat%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: Integer).returns(String)}
  def self.bar(x:)
    ""
  end

  sig {params(x: Integer).returns(String)}
  def self.bat(x)
    ""
  end
end

def main
  # Hover over the two methods below. They look identical,
  # but one uses a named argument rather than a position argument!
  A.bar
  A.bat
end
```

### Proposed solution

Include the `def` of the method in the hover text.

**Comment by mkillianey-stripe** [comment]
As per review comments in PR #1786 , also consider including method def in hover text for method definitions.

**Comment by mkillianey-stripe** [comment]
I believe this work is finished as of merging #1796 .
