### ISSUE TITLE
Improve error message for dangling comma in method params

### ISSUE THREAD

**Issue by atty-stripe** [sorbet/sorbet#1644]
The error in this code sample is the dangling comma, but the error message doesn't clearly point that out. Ideally the comma would be underlined and the error message would say something to the effect of "SyntaxError: dangling comma not allowed at the end of params list".

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).returns(String)%7D%0A%20%20def%20foo(%0A%20%20%20%20%23%20The%20real%20problem%20is%20this%20dangling%20comma%2C%0A%20%20%20%20%23%20but%20the%20error%20messages%20are%20not%20super%20clear.%0A%20%20%20%20x%3A%2C%0A%20%20)%0A%20%20%20%20x.to_s%0A%20%20end%0Aend

**Comment by jez** [comment]
Thanks for the feedback!

Given that this is ~identical to the error message that Ruby gives, I'm not sure if it's going to be worth our time to muck with the parser to make it better than what Ruby gives:

<img width="601" alt="Screen Shot 2019-08-23 at 2 50 50 PM" src="https://user-images.githubusercontent.com/5544532/63625779-80abb580-c5b5-11e9-9ddd-8639e30a773a.png">

Thus, closing for now. Thanks again!
