### ISSUE TITLE
Sorbet fails to run on OSX

### ISSUE THREAD

**Issue by mattgrande** [sorbet/sorbet#1647]
Following the docs here: https://sorbet.org/docs/adopting

I added both gems to my Gemfile:

```
gem 'sorbet'
gem 'sorbet-runtime'
```

Ran the install:

```
$ bundle install
[snip]
Using sorbet 0.4.4250
Using sorbet-runtime 0.4.4275
Bundle complete! 53 Gemfile dependencies, 151 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

But nothing seems to actually be installed:

```
$ bundle exec srb
bundler: command not found: srb
Install missing gem executables with `bundle install`
```

This may be related to #946. Any thoughts/ideas on what could be going wrong?

Version info:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87
```

**Comment by jasnow** [comment]
Is it possible to share your repo with me? I use MacOS Sierra as my daily runner.

**Comment by jasnow** [comment]
Try to upgrade the sorbet-related gems - we are currently on 0.4.4679.

**Comment by mattgrande** [comment]
I can't share the repo, unfortunately. I'll try creating a new repository with a reproduce case.

Strange that I got an old version; I installed them just now.

**Comment by jasnow** [comment]
Do you use rails or not in this repo?

**Comment by mattgrande** [comment]
Yes, I use rails.

I updated the gemfile:

```
gem 'sorbet', '0.4.4679'
gem 'sorbet-runtime', '0.4.4679'
```

And got this when I ran bundle install:

```
Bundler could not find compatible versions for gem "sorbet-static":
  In Gemfile:
    sorbet (= 0.4.4679) was resolved to 0.4.4679, which depends on
      sorbet-static (= 0.4.4679)

Could not find gem 'sorbet-static (= 0.4.4679)', which is required by gem 'sorbet
(= 0.4.4679)', in any of the sources.
```

**Comment by jasnow** [comment]
Compare my repo https://github.com/jasnow/rails_5.2_new with yours.

**Comment by mattgrande** [comment]
Will do, thanks.

I just tried a brand new repo, and it installed fine. I'm guessing that I've got a gemfile conflict or something. I'm going to try some stuff out, and I'll get back to you if I discover anything.

**Comment by jasnow** [comment]
check Gemfile or delete Gemfile.lock and run "bundle" again

**Comment by mattgrande** [comment]
1. Delete Gemfile.lock
2. Run bundle
3. Oh god, everything's broken! Failing tests! Deprecation warnings!
4. Revert Gemfile.lock changes
5. Re-install everything (including sorbet)
6. Now sorbet works

/shrug

Thanks for your help!
