### ISSUE TITLE
Misleading `sends` and `sends.typed` metrics

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#1669]
#### Problem

The metrics `sends` and `sends.typed` produced by Sorbet with the option `--metrics-file` can be really misleading as they give a false idea of how much sends are actually typed.

#### Should we count Sorbet signatures related methods in sends?

Sorbet counts `sig`, `void` etc. as `sends`:

```ruby
# typed: true

sig {void}
def foo; end
```

Produces the following metrics:

```json
  {
   "name": "types.input.sends.total",
   "value": 2
  }, {
   "name": "types.input.sends.typed",
   "value": 1
  }
```

#### Should we only consider `typed >= true` files?

The sigil used can also badly impact the metrics collection.

For example, with `typed: true`:

```ruby
# typed: true

sig {void}
def foo
end

def bar
end

foo
foo
bar
bar
```

Sorbet produces:

```json
  {
   "name": "ruby_typer.unknown..types.input.sends.total",
   "value": 6
  }, {
   "name": "ruby_typer.unknown..types.input.sends.typed",
   "value": 3
  }
```

While with `typed: false` is does not count any call.

#### Expected behaviors

* I would expect for Sorbet to produce accurate `sends` and `sends.typed` metrics whatever the sigil used.

* I would also expect Sorbet to not count `sig`, `void` etc calls as `sends` or `sends.typed`.

I pin-pointed the problem to this if: https://github.com/sorbet/sorbet/blob/master/main/pipeline/pipeline.cc#L50-L52. I wonder if we could extract the metrics computation to be ran even if the file is `typed < true`?

**Comment by jez** [comment]
Given that this is now at least documented, I'm going to close it:

https://sorbet.org/docs/metrics#call-site-level-typedness

I'm down to add a new metric for all calls, even in `typed: false` files, but i'd prefer to give it a new name so that our graphs don't have a big discontinuity in them.
