### ISSUE TITLE
Abstract/Implementation checks check against all parents instead of the most recent one

### ISSUE THREAD

**Issue by aisamanra** [sorbet/sorbet#1711]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20M1%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20interface!%0A%20%20sig%20%7B%20abstract.returns(Integer)%20%7D%0A%20%20def%20foo%3B%20end%0Aend%0Amodule%20M2%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20returns(Integer)%20%7D%0A%20%20def%20foo%3B%200%3B%20end%0Aend%0A%0Aclass%20X%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20M1%0A%20%20include%20M2%0A%20%20sig%20%7B%20implementation.returns(Integer)%20%7D%0A%20%20def%20foo%3B%201%3B%20end%0Aend)

```ruby
# typed: true
module M1
  extend T::Helpers
  extend T::Sig
  interface!
  sig { abstract.returns(Integer) }
  def foo; end
end
module M2
  extend T::Helpers
  extend T::Sig
  sig { returns(Integer) }
  def foo; 0; end
end

class X
  extend T::Sig
  include M1
  include M2
  sig { implementation.returns(Integer) }
  def foo; 1; end
end
```

#### Observed output

Statically, we'll get
```
No errors! Great job.
```
but dynamically this fails with an unnecessary `implementation` error.

#### Expected behavior

When we do abstract checks, we check against _all_ possible parent methods, but the runtime behavior is that the last parent method 'wins'. Consequently, the above program at runtime treats `X#foo` as overriding `M2.foo`, which is not `abstract` and therefore it doesn't need `override`. However, Sorbet will still statically require an `implementation` because of `M1.foo`. One way to fix this is to swap the order of `M2` and `M1`, at which point `M1.foo` 'wins' at runtime and `implementation` is allowed, but Sorbet should probably be able to figure out which parent method is the operative one.

- - -

**Comment by jez** [comment]
I think that #1763 fixed this.
