### ISSUE TITLE
Can't use T.let with T.type_parameter to fix pinning error

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#1715]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Btype_parameters(%3AU).params(x%3A%20T.type_parameter(%3AU)).void%7D%0A%20%20def%20pinning_error(x)%0A%20%20%20%20result%20%3D%20nil%0A%20%20%20%20%5B%5D.each%20do%0A%20%20%20%20%20%20result%20%3D%20x%20%23%20pinning%20error%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20sig%20%7Btype_parameters(%3AU).params(x%3A%20T.type_parameter(%3AU)).void%7D%0A%20%20def%20generics_error(x)%0A%20%20%20%20%23%20Can't%20fix%20pinning%20error%20because%20generics%20bug!%0A%20%20%20%20result%20%3D%20T.let(nil%2C%20T.nilable(T.type_parameter(%3AU)))%0A%20%20%20%20%5B%5D.each%20do%0A%20%20%20%20%20%20result%20%3D%20x%0A%20%20%20%20end%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {type_parameters(:U).params(x: T.type_parameter(:U)).void}
  def pinning_error(x)
    result = nil
    [].each do
      result = x # pinning error
    end
  end

  sig {type_parameters(:U).params(x: T.type_parameter(:U)).void}
  def generics_error(x)
    # Can't fix pinning error because generics bug!
    result = T.let(nil, T.nilable(T.type_parameter(:U)))
    [].each do
      result = x
    end
  end
end
```

#### Observed output

```
editor.rb:16: Unspecified type parameter https://srb.help/5004
    16 |    result = T.let(nil, T.nilable(T.type_parameter(:U)))
                                                           ^^

editor.rb:9: Changing the type of a variable in a loop is not permitted https://srb.help/7001
     9 |      result = x # pinning error
                       ^
  Existing variable has type: NilClass
  Attempting to change type to: A#pinning_error#U

  Autocorrect: Use `-a` to autocorrect
    editor.rb:7: Replace with T.let(nil, T.nilable(A#pinning_error#U))
     7 |    result = nil
                     ^^^
Errors: 2
```

#### Expected behavior

The pinning error is expected.

The error when trying to use `T.type_parameter` in the method body is not. I'm pretty sure that type_parameters should be in scope in the method body.

- - -

**Comment by manhhung741** [comment]
Just when I run into this problem XD I need this feature too

**Comment by elliottt** [comment]
We always parse types present in `T.let` with an `emptySig` parameter. As a result, the type parameters aren't available at this point.

https://github.com/sorbet/sorbet/blob/652e0d73a11d85a0c899f345ff9511b2354656ec/resolver/resolver.cc#L1613-L1615

**Comment by elliottt** [comment]
An additional wrinkle is that casts are resolved during `ResolveTypeMembersAndFieldsWalk`, which happens before signatures have been parsed.
