### ISSUE TITLE
Equality Operators (==) outputs T.untyped

### ISSUE THREAD

**Issue by donaldong** [sorbet/sorbet#1735]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns(T.nilable(T.untyped))%20%7D%0Adef%20a%0Aend%0A%0Asig%20%7B%20returns(T.nilable(T.untyped))%20%7D%0Adef%20b%0Aend%0A%0Asig%20%7B%20returns(T%3A%3ABoolean)%20%7D%0Adef%20this_is_fine%0A%20%20c%20%3D%20a%20%3D%3D%20b%0A%20%20T.reveal_type(c)%20%23%20Revealed%20type%3A%20T.untyped%0A%20%20c%0Aend)

```ruby
# typed: strict
extend T::Sig

sig { returns(T.nilable(T.untyped)) }
def a
end

sig { returns(T.nilable(T.untyped)) }
def b
end

sig { returns(T::Boolean) }
def this_is_fine
  c = a == b
  T.reveal_type(c) # Revealed type: T.untyped
  c
end
```

#### Observed output

```
editor.rb:15: Revealed type: T.untyped https://srb.help/7014
    15 |  T.reveal_type(c) # Revealed type: T.untyped
          ^^^^^^^^^^^^^^^^
  From:
    editor.rb:14:
    14 |  c = a == b
              ^^^^^^
Errors: 1
```

#### Expected behavior

- Expect it to be `T::Boolean`
```
15 |  T.reveal_type(c) # Revealed type: T.untyped
```

- Expect it to error since `c` reveals to `T.untyped`
```
sig { returns(T::Boolean) }
def this_is_fine
  c = a == b
  T.reveal_type(c) # Revealed type: T.untyped
  c
end
```

**Comment by jez** [comment]
This is expected. In Ruby, this code:

```ruby
a == b
```

is the same as

```
a.==(b)
```

If `a` is untyped, we have no idea what method `.==(...)` corresponds to. In particular, it could be the case that `a` is something which redefines `==` to not return a boolean:

```ruby
# typed: strict
require 'sorbet-runtime'

class MisbehavedA
  extend T::Sig
  sig {params(other: T.untyped).returns(Integer)}
  def ==(other)
    0
  end
end

a = T.let(MisbehavedA.new, T.untyped)
puts T.reveal_type(a)

puts T.reveal_type(a == a) # static type: T.untyped; runtime result: 0
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Arequire%20'sorbet-runtime'%0A%0Aclass%20MisbehavedA%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Bparams(other%3A%20T.untyped).returns(Integer)%7D%0A%20%20def%20%3D%3D(other)%0A%20%20%20%200%0A%20%20end%0Aend%0A%0Aa%20%3D%20T.let(MisbehavedA.new%2C%20T.untyped)%0Aputs%20T.reveal_type(a)%0A%0Aputs%20T.reveal_type(a%20%3D%3D%20a)%20%23%20static%20type%3A%20T.untyped%3B%20runtime%20result%3A%200)

**Comment by jez** [comment]
In particular, for this example Sorbet is even smart enough to know that **if** it knows that `a` has type `MisbehavedA`, that the result of the comparison has type `Integer`:

https://sorbet.run/#%23%20typed%3A%20strict%0Arequire%20'sorbet-runtime'%0A%0Aclass%20MisbehavedA%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Bparams(other%3A%20T.untyped).returns(Integer)%7D%0A%20%20def%20%3D%3D(other)%0A%20%20%20%200%0A%20%20end%0Aend%0A%0Aa%20%3D%20MisbehavedA.new%0A%0Aputs%20T.reveal_type(a%20%3D%3D%20a)%20%23%20static%20type%3A%20T.untyped%3B%20runtime%20result%3A%200

**Comment by donaldong** [comment]
Thanks for the quick response and great explanation!
