### ISSUE TITLE
Add an srb init test using a rails app

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1738]
To prevent issues like #1727 from reaching master, Sorbet should have a test where it runs `srb init` on a Rails app to make sure it passes typechecking.

- `gem install rails`
- `rails new test`
- `cd test`
- `bundle add sorbet` - or whatever is necessary to make it use the local sorbet
- `bundle exec srb init`
- `bundle exec srb tc` - make sure this passes.

**Comment by jasnow** [comment]
This would function as a smoke test.

**Comment by Morriar** [comment]
It should be possible now that https://github.com/sorbet/sorbet/pull/3357 is merged.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
