### ISSUE TITLE
Update srb snapshot harness to allow testing other subcommands

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#1764]
### Problem

Right now, it is only possible to possible to test the result of `srb init`. We'd probably like to be able to test other subcommands too, like `srb rbi update` or `srb rbi gems`.

We had to pass on writing tests for this recent change: #1721 because it was out of scope to expand the test harness to be able to test such changes.

**Comment by Morriar** [comment]
This feature was introduced in https://github.com/sorbet/sorbet/pull/3357.
