### ISSUE TITLE
Strict mode with chained Enumerable's results in the wrong type 

### ISSUE THREAD

**Issue by zanker-stripe** [sorbet/sorbet#1771]
#### Input

https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20self.test%0A%20%20%20%20data%20%3D%20T.let(%7B%7D%2C%20T%3A%3AHash%5BString%2C%20TrueClass%5D)%0A%20%20%20%20data%5B'bar'%5D%20%3D%20true%0A%0A%20%20%20%20key%20%3D%20data.each_key.map%20%7B%7Ckey%7C%20key%7D%0A%20%20%20%20T.reveal_type(key)%0A%20%20end%0Aend%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bvoid%7D%0Adef%20main%0A%20%20A.test%0Aend

```ruby
# typed: strict
class A
  extend T::Sig

  sig {void}
  def self.test
    data = T.let({}, T::Hash[String, TrueClass])
    data['bar'] = true

    key = data.each_key.map {|key| key}
    T.reveal_type(key)
  end
end

extend T::Sig

sig {void}
def main
  A.test
end
```

#### Observed output

```
editor.rb:11: Revealed type: T::Array[[String, TrueClass]] https://srb.help/7014
    11 |    T.reveal_type(key)
            ^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:10:
    10 |    key = data.each_key.map {|key| key}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

The revealed type should actually be `String` since `each_key` will mean we're only returning the `String` part.

https://github.com/sorbet/sorbet/blob/master/rbi/core/hash.rbi#L461
https://github.com/sorbet/sorbet/blob/master/rbi/core/hash.rbi#L412

Looks like these should be typed as `T::Enumerator[K]` and `T::Enumerator[V]` respectively. I'll try and toss a PR together tomorrow if I have a moment.

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong

**Comment by Morriar** [comment]
I think this is fixed since https://github.com/sorbet/sorbet/pull/2952.

**Comment by jez** [comment]
Thanks!
