### ISSUE TITLE
Hover shows a sig for tuple types

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#1777]
#### Input & observed output

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20main%0A%20%20T.reveal_type(%5B%200%20%5D)%20%23%20error%3A%20%5BInteger(0)%5D%20(1-tuple)%0A%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%20hover%3A%20sig%20%7Bparams(arg0%3A%20T.untyped).returns(%5BInteger(0)%5D)%7D%0Aend)

```ruby
# typed: true

def main
  T.reveal_type([ 0 ]) # error: [Integer(0)] (1-tuple)
#               ^ hover: sig {params(arg0: T.untyped).returns([Integer(0)])}
end
```

#### Expected behavior

The reveal type and the hover should show the same thing. At the very least, the hover should **not** show `params(arg0: T.untyped)`. It should probably also not even show the sig, and ideally it shows the helpful `1-tuple` parenthetical.

**Comment by mkillianey-stripe** [comment]
Verified fixed by #1834 using sorbet.run.
