### ISSUE TITLE
T.all with more than two parameters results in weird hover information

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1794]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Foo%3B%20end%0Amodule%20Bar%3B%20end%0Amodule%20Baz%3B%20end%0A%0Amodule%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns(T.all(Foo%2C%20Bar%2C%20Baz))%20%7D%0A%20%20def%20helpers%0A%20%20%20%20return%20T.unsafe(nil)%0A%20%20end%0Aend%0A%0Aclass%20B%0A%20%20include%20A%0A%20%20%0A%20%20def%20main%0A%20%20%20%20helpers%0A%20%20end%0Aend)

```ruby
# typed: true
module Foo; end
module Bar; end
module Baz; end

module A
  extend T::Sig

  sig { returns(T.all(Foo, Bar, Baz)) }
  def helpers
    return T.unsafe(nil)
  end
end

class B
  include A
  
  def main
    helpers
  end
end
```

Hover over `helpers` to see the weird hover info, `T.all(Foo, Bar, Baz)` is represented as `T.all(T.all(Foo, Bar), Baz)`.

#### Observed output

You can see this by hovering over a method which returns `T.all()` 

<img width="714" alt="Screen Shot 2019-09-16 at 7 22 20 PM" src="https://user-images.githubusercontent.com/2977353/65003818-5d73dd80-d8b7-11e9-9767-77df610406af.png">

#### Expected behavior

I'd expect it to return `T.all(ApplicationHelper, UsersHelper, GamesHelper, ActivityHelper)`

**Comment by connorshea** [comment]
The same thing can be seen with `T.reveal_type` as well.

**Comment by elliottt** [comment]
Good find! I think that we just need to apply the same collapsing logic to `T.all` that we do to `T.any` in `core/types/printing.cc`.
