### ISSUE TITLE
`strict` typing doesn't work for test files

### ISSUE THREAD

**Issue by jackson-stripe** [sorbet/sorbet#1801]
#### Input

Sorbet seems to throw a runtime error `You called sig twice without declaring a method inbetween` when using both a `before` and an `it` block in a test like in https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20describe%20'%23migrate'%20do%0A%20%20%20%20sig%20%7Bvoid%7D%0A%20%20%20%20before%20do%0A%20%20%20%20%20%20%40a%20%3D%20T.let(5%2C%20Integer)%0A%20%20%20%20end%0A%0A%20%20%20%20sig%20%7Bvoid%7D%0A%20%20%20%20it%20'does%20delete%20skus%20with%20legacy%20ids%20and%20old%20merchant'%20do%0A%20%20%20%20%20%20puts(5%20%3D%3D%20%40a)%0A%20%20%20%20end%0A%20%20end%0Aend
[→ View on sorbet.run](TODO_replace_this_with_your_sorbet_run_link)
```
# typed: strict
class A
  extend T::Sig

  describe '#migrate' do
    sig {void}
    before do
      @a = T.let(5, Integer)
    end

    sig {void}
    it 'does delete skus with legacy ids and old merchant' do
      puts(5 == @a)
    end
  end
end
```
#### Observed output

```
TODO: Replace this with the output in sorbet.run
(sorbet.run output changes over time)
```
sorbet.run doesn't throw an error but the runtime environment does

#### Expected behavior

It should not throw this error
- - -

**Comment by jasnow** [comment]
Should the "@a" be "@A" in example?

**Comment by jackson-stripe** [comment]
@jasnow oops the auto-formatting was tagging someone with the `@` character. I made it code-formatted instead.
