### ISSUE TITLE
Document generics

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#1803]
I know it still is a work-in-progress feature but in practice they are used a lot in the RBIs and required to type a lot of things.

Hiding them doesn't work as developers will find they exist and try to use them anyway. We have more and more questions about them. Pointing users to some kind of documentation would be super useful.

Can we have a bit of doc about this? Even if it states that everything is beta / work in progress / bleeding edge or might disappear at any time.

This would be super useful for Sorbet contributors too as the documentation would show part of the spec and help us decide what is an issue or not.

**Comment by paracycle** [comment]
Btw, you guys are way more knowledgable about the current state of generics, the design, etc, but we are also willing to contribute to such a documentation as much as we can. So this isn't just an empty ask, it is more of a dialogue starter. Let us know if and how we can be helpful.

**Comment by connorshea** [comment]
I'd really appreciate this! I'm trying to create type signatures for Rails' HashWithIndifferentAccess (which descends from Hash) and I'm having trouble because I don't really understand how to use `type_member` or `type_parameters` 😥

**Comment by kirbycool** [comment]
+1
There's some internal Stripe doc referenced in the source [here](ActiveRecord_Associations_CollectionProxy). Would it be possible to clean that up and release it?

**Comment by kumar303** [comment]
I couldn't understand what the magical [`type_member`](https://github.com/sorbet/sorbet/blob/b301c739b7463b655770249246e4c92774657f22/gems/sorbet-runtime/lib/types/generic.rb#L16) calls were doing. This and other uses of `T::Generic` should be documented. I finally found an explanation [here](https://jdkaplan.dev/blog/learn-sorbet-in-y-minutes/).

```ruby
  # A generic class uses `T::Generic.type_member` to define type variables that
  # can be like regular type names.
```

This looked promising! https://github.com/sorbet/sorbet/pull/3477

**Comment by amomchilov** [comment]
There's some docs published on this now, FYI https://sorbet.org/docs/generics

**Comment by Morriar** [comment]
Closed by https://github.com/sorbet/sorbet/pull/5723 🎉
