### ISSUE TITLE
Sorbet static should not show `Sorbet::Private` types

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#1806]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(a%3A%20T.proc.void).void%20%7D%0A%20%20def%20foo(a)%3B%20end%0Aend%0A%0AA.new.foo(10))

```ruby
# typed: true

class A
  extend T::Sig

  sig { params(a: T.proc.void).void }
  def foo(a); end
end

A.new.foo(10)
```

#### Observed output

```
editor.rb:10: Expected T.proc.returns(Sorbet::Private::Static::Void) but found Integer(10) for argument a https://srb.help/7002
    10 |A.new.foo(10)
        ^^^^^^^^^^^^^
    editor.rb:6: Method A#foo has specified a as T.proc.returns(Sorbet::Private::Static::Void)
     6 |  sig { params(a: T.proc.void).void }
                       ^
  Got Integer(10) originating from:
    editor.rb:10:
    10 |A.new.foo(10)
                  ^^
Errors: 1
```

#### Expected behavior

I would expect the error to show the type of the proc as `T.proc.void` instead of `T.proc.returns(Sorbet::Private::Static::Void)`.

**Comment by connorshea** [comment]
This is resolved now
