### ISSUE TITLE
Autoloading a constant forces potentially non-existent gem to be required

### ISSUE THREAD

**Issue by ilyakatz** [sorbet/sorbet#1820]
Initialization fails if a file cannot be required (eg. throws an exception) 

For example, in my case, I use `semantic_logger` which allows different logging destinations (eg. bugsnang, newrelic, mongodb). If I do not use `mongodb` as a logger, I don't need to require `semantic_logger/appender/mongodb`. 

What happens with `sorbet init` is that it requires all the files that since my `semantic_logger/appender/mongodb` is not supposed to be loaded, it throws an exception. This in turn, fails `sorbet init`

#### Observed output

```ruby
% bundle exec srb init 
...
	 2: from /Users/ilya/.rvm/gems/ruby-2.5.1@courier/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	 1: from /Users/ilya/.rvm/gems/ruby-2.5.1@courier/gems/semantic_logger-4.3.1/lib/semantic_logger/appender/mongodb.rb:2:in `<top (required)>'
/Users/ilya/.rvm/gems/ruby-2.5.1@courier/gems/semantic_logger-4.3.1/lib/semantic_logger/appender/mongodb.rb:5:in `rescue in <top (required)>': Gem mongo is required for logging to MongoDB. Please add the gem "mongo" v2.0 or greater to your Gemfile. (RuntimeError)
```

**Comment by ilyakatz** [comment]
I think the problem is this. 

This is the code that handles missing gems in the library.

```
begin
  require 'mongo'
rescue LoadError
  raise 'Gem mongo is required for logging to MongoDB. Please add the gem "mongo" v2.0 or greater to your Gemfile.'
end
```

Sorbet seems to handle a subset of exceptions in https://github.com/sorbet/sorbet/blob/master/gems/sorbet/lib/constant_cache.rb#L138

**Comment by jez** [comment]
This seems like it's easier to fix upstream

https://github.com/rocketjob/semantic_logger/pull/139

**Comment by ilyakatz** [comment]
Yes, this particular problem should be solve upstream ( as you see I raised an issue with them). However, a bigger problem is that it may happen in other gems as well. That's why I'm raising the issue here

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
