### ISSUE TITLE
Dir[] with multiple paths return a type error.

### ISSUE THREAD

**Issue by khongor-stripe** [sorbet/sorbet#1822]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20main%0A%20%20Dir%5B%27a%27%2C%20%27b%27%5D%0Aend)

```ruby
# typed: true

def main
  Dir['a', 'b']
end
```

#### Observed output

```
editor.rb:4: Expected Integer but found String("b") for argument flags https://srb.help/7002
     4 |  Dir['a', 'b']
          ^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/dir.rbi#L518: Method Dir.[] has specified flags as Integer
     518 |        flags: Integer,
                  ^^^^^
  Got String("b") originating from:
    editor.rb:4:
     4 |  Dir['a', 'b']
                   ^^^
Errors: 1
```

#### Expected behavior

This should work without an error
- - -

**Comment by elliottt** [comment]
The signature for `Dir#[]` doesn't seem to match the docs, as it can take multiple string arguments.

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
