### ISSUE TITLE
`type_member` isn't type-checked at runtime when used as part of a sig

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1828]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20B%3B%20end%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member(fixed%3A%20B)%0A%0A%20%20sig%20%7B%20returns(Elem)%20%7D%0A%20%20def%20bar%0A%20%20%20%20T.unsafe(1)%0A%20%20end%0Aend%0A%0A%23%20This%20doesn't%20trigger%20a%20runtime%20error%0AA.new.bar%0A)

```ruby
# typed: true
class B; end
class A
  extend T::Sig
  extend T::Generic

  Elem = type_member(fixed: B)

  sig { returns(Elem) }
  def bar
    T.unsafe(1)
  end
end

# This doesn't trigger a runtime error
A.new.bar
```

#### Observed output

```
It doesn't trigger a TypeError at runtime
```

#### Expected behavior

I should be able to use `type_member` to type check at runtime, especially when it's used with `fixed`

- - -

**Comment by manhhung741** [comment]
FWIW I have this monkey-patching module that makes it work for `fixed`
```
module TypeMemberRuntimeCheck
  def type_member(variance=:invariant, fixed: nil, lower: T.untyped, upper: BasicObject)
    ret = super
    fixed.nil? ? ret : fixed
  end
end
```

**Comment by elliottt** [comment]
As far as I know we don't have plans to stop erasing generic parameters at runtime, as it would incur a performance penalty to do so. We rely on the static part of sorbet to check that generics are used correctly so that we can avoid the cost of checking them at runtime.

**Comment by jez** [comment]
As Trevor mentions, we have chosen to implement erased generics, which means that we will not be implementing runtime type checking for generic type members.
