### ISSUE TITLE
Missing definitions for Etc public class methods in etc.rbi

### ISSUE THREAD

**Issue by DanGe42** [sorbet/sorbet#1829]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire%20'etc'%0A%0Adef%20main%0A%20%20username%20%3D%20Etc%3A%3Agetlogin%20%7C%7C%20Etc%3A%3Agetpwuid.name%0Aend)

```ruby
# typed: true
require 'etc'

def main
  username = Etc::getlogin || Etc::getpwuid.name
end
```

#### Observed output

```
editor.rb:5: Method getlogin does not exist on T.class_of(Etc) https://srb.help/7003
     5 |  username = Etc::getlogin || Etc::getpwuid.name
                     ^^^^^^^^^^^^^

editor.rb:5: Method getpwuid does not exist on T.class_of(Etc) https://srb.help/7003
     5 |  username = Etc::getlogin || Etc::getpwuid.name
                                      ^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

Neither of these method calls should be errors because these are [public class methods](https://ruby-doc.org/stdlib-2.5.3/libdoc/etc/rdoc/Etc.html) on the `Etc` module.

I poked around the RBI files in this project and noticed that [etc.rbi](https://github.com/sorbet/sorbet/blob/master/rbi/stdlib/etc.rbi) is missing all these public class methods.

My current workaround for these missing definitions (under strict typing):

```ruby
username = T.let(T.unsafe(Etc).getlogin, String)
```

**Comment by jez** [comment]
RBI contributions welcome!

**Comment by connorshea** [comment]
I think these have been added now?

**Comment by Morriar** [comment]
> I think these have been added now?

Yes, in #1940 and #2237.

I think it can be closed.
