### ISSUE TITLE
Unsupported usage of bare type when typechecking `sig`

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#183]
https://sorbet.run/#class%20A%0A%23%20SimpleReconciler%20interface%0Aextend%20T%3A%3AGeneric%0Aextend%20T%3A%3ASig%0A%0A%0AReconcilableRecord%20%3D%20type_member(fixed%3A%20Integer)%0A%0Asig%20%7Boverride.returns(T%3A%3AArray%5BReconcilableRecord%5D)%7D%0Adef%20unreconciled%0A%20%20T.unsafe(nil)%0Aend%0Aend%0A

**Comment by jez** [comment]
Dupe of #68
