### ISSUE TITLE
Quick fixes suggest T.let on a type parameter

### ISSUE THREAD

**Issue by sushain97** [sorbet/sorbet#1848]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters(%3AU)%0A%20%20.params(%0A%20%20%20%20bar%3A%20T.type_parameter(%3AU)%2C%0A%20%20)%0A%20%20.returns(T.nilable(T.type_parameter(%3AU)))%0Aend%0Adef%20foo(bar)%0A%20%20baz%20%3D%20nil%0A%20%203.times%20do%0A%20%20%20%20baz%20%3D%20bar%0A%20%20end%0A%20%20baz%0Aend%0A)

```ruby
# typed: strict

extend T::Sig

sig do
  type_parameters(:U)
  .params(
    bar: T.type_parameter(:U),
  )
  .returns(T.nilable(T.type_parameter(:U)))
end
def foo(bar)
  baz = nil
  3.times do
    baz = bar
  end
  baz
end
```

#### Observed output

```
editor.rb:15: Changing the type of a variable in a loop is not permitted https://srb.help/7001
    15 |    baz = bar
                  ^^^
  Existing variable has type: NilClass
  Attempting to change type to: Object#foo#U

  Autocorrect: Use `-a` to autocorrect
    editor.rb:13: Replace with T.let(nil, T.nilable(Object#foo#U))
    13 |  baz = nil
                ^^^
Errors: 1
```

#### Expected behavior

There should be no suggestion since it isn't possible to `T.let` this currently inside a function body. It just results in nonsense code.

- - -

cc @jvilk-stripe

**Comment by jez** [comment]
Maybe... I'm of the mind here that the code action is actually correct, but the problem is that `T.type_parameter(:U)` **should** be allowed in a method body, and it's not currently.

We have an issue for that (#1715). If you really want to work around that bug in the mean time, sure, but like, it seems kind of beside the point to me.
