### ISSUE TITLE
 Unsupported node type Backref

### ISSUE THREAD

**Issue by bubaflub** [sorbet/sorbet#1856]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20def%20foo%0A%20%20%20%20'asdf'.gsub(%2F(a)%2F)%20%7B%20%24%26%20%7D%0A%20%20end%0Aend)

```ruby
# typed: true

class A
  def foo
    'asdf'.gsub(/(a)/) { $& }
  end
end
```

#### Observed output

```
editor.rb:5: Unsupported node type Backref https://srb.help/3003
     5 |    'asdf'.gsub(/(a)/) { $& }
                                 ^^
Errors: 1
```

#### Expected behavior

I expected Sorbet to handle `$&` and typecheck it as a String.

- - -

Found this while trying to apply this an existing Ruby on Rails codebase.  I'd be happy to help implement a fix but I'll need some guidance on how to help.

**Comment by jez** [comment]
https://github.com/sorbet/sorbet/blob/4bef9ab4572a5e4eef714cca9c7586de94eb051f/ast/desugar/Desugar.cc#L1669-L1672

These would be the lines to change. You'll want to transform the parse tree that we get from Ruby into an AST suitable for Sorbet. The easiest way to do this is to convert it into another existing node type. For example, if it's guaranteed that `Backref` is always a term of type `String`, you could just cheat and say something like `Backref` -> `String.new`.

If that's not always the case, then you could do something like `Backref` -> `T.unsafe(nil)`

It might be the case that other members of the team care about modeling this more carefully, which would require more work so you should come talk to us on Slack (https://sorbet.org/slack) in the #internals channel before trying to implement this.

**Comment by bubaflub** [comment]
Everything I'm reading from the docs for [`Regexp`](https://ruby-doc.org/core-2.4.5/Regexp.html) and [`MatchData`](https://ruby-doc.org/core-2.4.5/MatchData.html) indicates that `$&` is a `String` and is equivalent to `Regexp.last_match[0]`.  It seems like sorbet happily type checks `Regexp.last_match[0]` so that's an okay work-around.

I'd like to try and tackle this ticket next week -- mind if I assign it to myself?

**Comment by bubaflub** [comment]
Looking at https://github.com/sorbet/sorbet/blob/586a106954f17f27655455dcf6580424583d6b1e/parser/tools/generate_ast.cc#L66-L71

I think the `Backref` node refers to more than just `$&`.  Looking at https://github.com/sorbet/sorbet/blob/586a106954f17f27655455dcf6580424583d6b1e/third_party/parser/cc/lexer.rl#L1452-L1453

It looks like we parse out a `Backref` node for:
```
$&
$`
$'
$+
```

Each of these appear to be `String`s according to the Regexp docs.

**Comment by bubaflub** [comment]
Reading the internals docs and thinking about this a bit more, unless I can distinguish between the different `Backref` nodes (e.g. `$&` vs `$'`) I don't think I can actually Desugar this into `Regexp.last_match[something]` but I can have Desugar treat it as a `String`.
