### ISSUE TITLE
VS Code: Clicking on error code (click for more information) should display information about error

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#1867]
### Problem

Clicking on:
![Screen Shot 2019-09-27 at 11 17 05 AM](https://user-images.githubusercontent.com/43145439/65792329-5e5b0980-e118-11e9-9883-b5bf32586752.png)

Doesn't work, as VS Code doesn't support opening web links:
![Screen Shot 2019-09-27 at 11 17 41 AM](https://user-images.githubusercontent.com/43145439/65792367-6fa41600-e118-11e9-8a68-346d2ee5546e.png)

### Proposed solution

The solution depends on what is possible.

If it is possible to have a uri open a web view, we could send these links encoded in a `sorbet-docs://` URI. In the extension and register a URI handler for `sorbet-docs://` that opens the proper URL in a web view. Due to the nature of VS Code web views, we would have to iframe the actual webpage, as they only support displaying a local HTML file as the root document.

Otherwise, is there an easy way to pipe the documentation into a read-only text document?

**Comment by jez** [comment]
fwiw, i'd consider not sending a web link to be a sort of regression. sending them as weblinks works just fine in for example Vim

**Comment by jez** [comment]
(accidental close)

**Comment by jvilk-stripe** [comment]
@jez To clarify: Behavior would only change for VS Code. The `https:` solution works in Sorbet.run, too!

VS Code client would opt-in to these URIs during the initialization handshake w/ a custom options parameter. We already do this to opt-in to `sorbet://` URIs to support viewing payload files in-editor.

**Comment by jez** [comment]
I think this was fixed with #5714
