### ISSUE TITLE
Abstract and Interface are checked only for `include`

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#1872]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20I%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0Aend%0A%0Amodule%20A%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0Aend%0A%0Aclass%20C1%0A%20%20include%20I%0A%20%20include%20A%0Aend%0A%0Aclass%20C2%0A%20%20extend%20I%0A%20%20extend%20A%0Aend%0A%0Aclass%20C3%0A%20%20prepend%20I%0A%20%20prepend%20A%0Aend%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns(I)%20%7D%0A%20%20def%20ok1%0A%20%20%20%20C1.new%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(I)%20%7D%0A%20%20def%20error1%0A%20%20%20%20C2.new%20%23%20Should%20work%3F%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(I)%20%7D%0A%20%20def%20error2%0A%20%20%20%20C3.new%20%23%20Should%20work%3F%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(A)%20%7D%0A%20%20def%20ok2%0A%20%20%20%20C1.new%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(A)%20%7D%0A%20%20def%20error3%0A%20%20%20%20C2.new%20%23%20Should%20work%3F%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(A)%20%7D%0A%20%20def%20error4%0A%20%20%20%20C3.new%20%23%20Should%20work%3F%0A%20%20end%0Aend)

```ruby
# typed: true

module I
  extend T::Helpers
  interface!
end

module A
  extend T::Helpers
  abstract!
end

class C1
  include I
  include A
end

class C2
  extend I
  extend A
end

class C3
  prepend I
  prepend A
end

class Foo
  extend T::Sig

  sig { returns(I) }
  def ok1
    C1.new
  end

  sig { returns(I) }
  def error1
    C2.new # Should work?
  end

  sig { returns(I) }
  def error2
    C3.new # Should work?
  end

  sig { returns(A) }
  def ok2
    C1.new
  end

  sig { returns(A) }
  def error3
    C2.new # Should work?
  end

  sig { returns(A) }
  def error4
    C3.new # Should work?
  end
end
```

#### Observed output

```
editor.rb:38: Returning value that does not conform to method result type https://srb.help/7005
    38 |    C2.new # Should work?
            ^^^^^^
  Expected I
    editor.rb:37: Method error1 has return type I
    37 |  def error1
          ^^^^^^^^^^
  Got C2 originating from:
    editor.rb:38:
    38 |    C2.new # Should work?
            ^^^^^^

editor.rb:43: Returning value that does not conform to method result type https://srb.help/7005
    43 |    C3.new # Should work?
            ^^^^^^
  Expected I
    editor.rb:42: Method error2 has return type I
    42 |  def error2
          ^^^^^^^^^^
  Got C3 originating from:
    editor.rb:43:
    43 |    C3.new # Should work?
            ^^^^^^

editor.rb:53: Returning value that does not conform to method result type https://srb.help/7005
    53 |    C2.new # Should work?
            ^^^^^^
  Expected A
    editor.rb:52: Method error3 has return type A
    52 |  def error3
          ^^^^^^^^^^
  Got C2 originating from:
    editor.rb:53:
    53 |    C2.new # Should work?
            ^^^^^^

editor.rb:58: Returning value that does not conform to method result type https://srb.help/7005
    58 |    C3.new # Should work?
            ^^^^^^
  Expected A
    editor.rb:57: Method error4 has return type A
    57 |  def error4
          ^^^^^^^^^^
  Got C3 originating from:
    editor.rb:58:
    58 |    C3.new # Should work?
            ^^^^^^
Errors: 4
```

#### Expected behavior

I would expect all those examples to pass without any error.

- - -

Maybe related issues: #1317, #1711.

**Comment by DarkDimius** [comment]
This is intentional.
Instances of C2 do not inhabit type of I.
'C2.new.is_a? I' will fail
'C2.new.instance_method_fromI()' will also fail

**Comment by Morriar** [comment]
TIL about the `extend` behavior in Ruby. So `C2` is indeed not a subtype of `I` nor `A`.

But the `prepend` should work since:

```
module M
  def foo
    puts "Foo"
  end
end

class A
  prepend M
end

class B
  include M
end

A.new.foo # Foo
B.new.foo # Foo
```
