### ISSUE TITLE
Unreachable code error when calling `Array(...)` with a `T.untyped`

### ISSUE THREAD

**Issue by robertjlooby** [sorbet/sorbet#1904]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20main%0A%20%20arr%20%3D%20T.let(%5B1%2C%202%2C%203%5D%2C%20T.untyped)%0A%20%20Array(arr).each%7B%7Ca%7C%20puts%20a%7D%0Aend)

```ruby
# typed: true

def main
  arr = T.let([1, 2, 3], T.untyped)
  Array(arr).each{|a| puts a}
end
```

#### Observed output

```
editor.rb:5: This code is unreachable https://srb.help/7006
     5 |  Array(arr).each{|a| puts a}
                              ^^^^^^
    editor.rb:5: This expression always raises or can never be computed
     5 |  Array(arr).each{|a| puts a}
                           ^
Errors: 1
```

#### Expected behavior

I would expect that since `Array(...)` always returns an `Array`, calling it with something that is `T.untyped` would infer the type as `T::Array[T.untyped]`. Instead it's resolving to `[] (0-tuple)` and leading to an unreachable code error.

**Comment by jez** [comment]
Thanks for the minimal repro!

**Comment by akshay1992kalbhor** [comment]
Looks like this has been resolved. Tried running it in the playground and it works fine

**Comment by robertjlooby** [comment]
Yep! This looks to be resolved now.
