### ISSUE TITLE
Stabilize workspace/symbol

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#1911]
### Problem

The [workspace/symbol request](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#workspace_symbol) is "sent from the client to the server to list project-wide symbols matching the query string." It includes location information for each symbol, so the user can navigate to them, along with a symbol type that influences the icon used to display the result in-editor.

The query string is just a string with no special formatting or query. It can be fuzzily matched or exact matched; whatever seems to work best.

You can search for symbols in VS Code with `⌘T`, which opens up the search box with `#`. VS Code will send `workspace/symbol` requests as you type. e.g. searching for `#foo` will send three separate workspace/symbol requests with query strings `"f"`, `"fo"`, and `"foo"` to the language server. (It probably cancels intermediate requests that haven't yet been processed; Sorbet's language server correctly supports cancelation.)

### Proposed solution

We have a straightforward implementation of `workspace/symbol`:

https://github.com/sorbet/sorbet/blob/master/main/lsp/requests/workspace_symbols.cc#L29

However, it has a few problems:
* It doesn't "appear" to work in Stripe's large Ruby codebase, but one look at the log suggests that it might be because it sends back way too many symbols.
  * VS Code doesn't appear to be hung, so I _suspect_ but did not _confirm_ that VS Code refuses to display results until the query is specific enough to return a manageable set of symbols.
* It is effectively untested.\*
* Search results aren't ranked in any particular order.
* Some internal Sorbet names (e.g. `<root>`) appear in the description of search results:

![Screen Shot 2019-10-07 at 10 44 41 AM](https://user-images.githubusercontent.com/43145439/66341303-cf11db00-e8fb-11e9-8394-82179cd61187.png)
*This is from a small test workspace.*

We should:

* Determine what 'good' sorting and fuzzy matching behavior should be.
  * For sorting, I've used [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) before, but it might be worth seeing what TypeScript does.
* Add testing support to `test_corpus`.
* Write tests that search for many symbol types and that expose existing bugs (e.g., showing `<root>`, not ranking things, etc).
* Fix the code so it passes those tests.

The tests for workspace/symbol can likely [cargo-cult part of the design from @jez's autocomplete tests](https://github.com/sorbet/sorbet#testing-completion). I'm thinking something like:

```ruby
# symbolSearch: foo  result1, result2, result3, ...
```

\* There's a "recorded test", but it should be deleted once we have proper `test_corpus` tests.

**Comment by jvilk-stripe** [comment]
If it's not fast, we could memoize the results of last few searches and filter those if a new query is a superset of an old query, e.g. f => fo => foo).

**Comment by jvilk-stripe** [comment]
Update: It looks like we're not fuzzy matching anymore, we're exact matching.

**Comment by jvilk-stripe** [comment]
I benchmarked workspace/symbol on Stripe's large codebase; it takes only 80 milliseconds to iterate through the symbol table looking for exact string matches. I think we can make this run quickly without an index!

**Comment by DarkDimius** [comment]
Awesome!
