### ISSUE TITLE
Sorbet fails when including module in main object

### ISSUE THREAD

**Issue by ivoanjo** [sorbet/sorbet#1914]
#### Input

[→ View on sorbet.run](https://sorbet.run/#module%20Hello%0A%20%20def%20foo%0A%20%20%20%20%3Afoo%0A%20%20end%0Aend%0A%0Ainclude%20Hello%0A)

```ruby
module Hello
  def foo
    :foo
  end
end

include Hello
```

#### Observed output

```ruby
editor.rb:7: Parent of class <root> redefined from Object to Hello https://srb.help/5012
     7 |include Hello
                ^^^^^
Errors: 1
```

#### Expected behavior

There should be no error -- including a module in the main object should be supported, although it's a bit uncommon :)

**Comment by marianosimone** [comment]
This is no longer an issue 🎉

**Comment by Morriar** [comment]
> This is no longer an issue 🎉

Then closing. Thanks :)
