### ISSUE TITLE
Rest params are untyped if there is at least one other param to a block

### ISSUE THREAD

**Issue by neil-stripe** [sorbet/sorbet#192]
[Sorbet.run link](https://sorbet.run/#%5B1%2C%202%5D.inject%20%7B%20%7C*rest%7C%0A%20%20T.reveal_type(rest)%3B%0A%20%201%0A%7D%0A%0A%5B1%2C%202%5D.inject%20%7B%20%7Ca%2C%20*rest%7C%0A%20%20T.reveal_type(a)%0A%20%20T.reveal_type(rest)%20%23%20Should%20be%20%5BInteger%5D%3F%0A%20%201%0A%7D)

**Comment by neilparikh** [comment]
See #6408
