### ISSUE TITLE
runtime: top level `extend T::sig` is not supported

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#199]
In the sorbet documentation, a lot of examples are presented directly on the top level:

```ruby
# typed: true

require_relative '../test_helper.rb'

extend T::Sig

sig { returns(String) }
def foo
  "foo"
end

foo # Should be OK
```

This is accepted by `sorbet`:
https://sorbet.run/#%23%20typed%3A%20true%0A%0Arequire%20'sorbet-runtime'%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns(String)%20%7D%0Adef%20foo%0A%20%20%22foo%22%0Aend%0A%0Afoo%20%23%20Should%20be%20OK

But makes the `sorbet-runtime` crash:

```bash
`instance_method': undefined method `method_added' for class `#<Class:#<Object:0x00007fd5ef0da2b0>>' (NameError)
Did you mean?  method_defined?
```

**Comment by jez** [comment]
Closing in favor of #923 which has more context and research.
