### ISSUE TITLE
T::Struct props silently dropped if they contain tuples

### ISSUE THREAD

**Issue by daviddoran-stripe** [sorbet/sorbet#1991]
#### Input

[Sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Thing%3B%20end%0Aclass%20Thing2%3B%20end%0A%0Aclass%20A%20<%20T%3A%3AStruct%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20const%20%3Aarr_things%2C%20T%3A%3AArray%5BThing%5D%0A%20%20const%20%3Aarr_arr_things%2C%20T%3A%3AArray%5BT%3A%3AArray%5BThing%5D%5D%0A%20%20const%20%3Atuples%2C%20%5BThing%2C%20Thing2%5D%0A%20%20const%20%3Aarr_tuples%2C%20T%3A%3AArray%5B%5BThing%2C%20Thing2%5D%5D%20%20%0Aend%0A%0Adef%20main%0A%20%20A.new(%0A%20%20%20%20arr_things%3A%20%5B%5D%2C%20%23%20OK%0A%20%20%20%20arr_arr_things%3A%20%5B%5D%2C%20%23%20OK%0A%20%20%20%20tuples%3A%20%5BThing.new%2C%20Thing2.new%5D%2C%20%23%20Fails%0A%20%20%20%20arr_tuples%3A%20%5B%5D%2C%20%23%20Fails%0A%20%20)%0Aend)

```ruby
# typed: true

class Thing; end
class Thing2; end

class A < T::Struct
  extend T::Sig

  const :arr_things, T::Array[Thing]
  const :arr_arr_things, T::Array[T::Array[Thing]]
  const :tuples, [Thing, Thing2]
  const :arr_tuples, T::Array[[Thing, Thing2]]  
end

def main
  A.new(
    arr_things: [], # OK
    arr_arr_things: [], # OK
    tuples: [Thing.new, Thing2.new], # Fails
    arr_tuples: [], # Fails
  )
end
```

#### Observed output

```
editor.rb:16: Unrecognized keyword argument tuples passed for method A#initialize https://srb.help/7004
    16 |  A.new(
    17 |    arr_things: [], # OK
    18 |    arr_arr_things: [], # OK
    19 |    tuples: [Thing.new, Thing2.new], # Fails
    20 |    arr_tuples: [], # Fails
    21 |  )

editor.rb:16: Unrecognized keyword argument arr_tuples passed for method A#initialize https://srb.help/7004
    16 |  A.new(
    17 |    arr_things: [], # OK
    18 |    arr_arr_things: [], # OK
    19 |    tuples: [Thing.new, Thing2.new], # Fails
    20 |    arr_tuples: [], # Fails
    21 |  )
Errors: 2
```

#### Expected behavior

Sorbet DSL pass should error when it comes across tuples in prop definition, as opposed to silently dropping them and then erroring at the site where they're referenced.ee

- - -

**Comment by penelope-stripe** [comment]
Another example I encountered:

```
#typed: true
class Event < T::Struct
  prop :foo, String
  prop :bees, T::Array[[Integer]]
end

Event.new(
  foo: "a",
  bees: []
)
```

**Comment by jigarius** [comment]
I am new to Sorbet, so I'm not sure if the problem I'm facing is the same one as this issue is talking about. Here's a [link to sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%20%3C%20T%3A%3AStruct%0A%20%20prop%20%3Acolor%2C%20%5BInteger%2C%20Integer%2C%20Integer%5D%0Aend%0A%0AFoo.new(color%3A%20%5B0%2C%200%2C%200%5D)%0A) that shows my issue.

Basically, all I try to do is:
```ruby
# typed: true

class Foo < T::Struct
  prop :color, [Integer, Integer, Integer]
end

Foo.new(color: [0, 0, 0])
```

But I get errors like:
```
editor.rb:7: Too many arguments provided for method Foo#initialize. Expected: 0, got: 1 https://srb.help/7004
     7 |Foo.new(color: [0, 0, 0])
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:3: initialize defined here
     3 |class Foo < T::Struct
     4 |  prop :color, [Integer, Integer, Integer]
     5 |end
Errors: 1
```

Is this a known bug? Or am I doing something wrong?

**Comment by jez** [comment]
This is related to #3485
