### ISSUE TITLE
Destructuring array of unknown size incorrectly infers nil

### ISSUE THREAD

**Issue by jzhou-stripe** [sorbet/sorbet#2020]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20T%3A%3AArray%5BString%5D).returns(T%3A%3AArray%5BString%5D)%7D%0A%20%20def%20bar(x)%0A%20%20%20%20*a%2C%20b%20%3D%20x%0A%20%20%20%20a%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: T::Array[String]).returns(T::Array[String])}
  def bar(x)
    *a, b = x
    a
  end
end
```

#### Observed output

```
# typed: true
editor.rb:8: Returning value that does not conform to method result type https://srb.help/7005
     8 |    a
            ^
  Expected T::Array[String]
    editor.rb:6: Method bar has return type T::Array[String]
     6 |  def bar(x)
          ^^^^^^^^^^
  Got T.nilable(T::Array[String]) originating from:
    editor.rb:7:
     7 |    *a, b = x
            ^^^^^^^^^
Errors: 1
```

#### Expected behavior

Should not be an error.

- - -

**Comment by paracycle** [comment]
We encountered this today and I dug in a little bit. It seems the desugaring Sorbet uses here is not exactly semantically equivalent to what destructuring does:

```
$ bundle exec srb tc --no-config -p ast -e "# typed: strict
first, *rest = [1, 2, 3]
T.reveal_type(rest)"

begin
  <emptyTree>
  class <emptyTree><<C <root>>> < (::<todo sym>)
    def self.<static-init><<static-init>$112>(<blk>)
      begin
        begin
          <assignTemp>$2 = [1, 2, 3]
          <assignTemp>$3 = ::<Magic>.<expand-splat>(<assignTemp>$2, 1, 0)
          first = <assignTemp>$3.[](0)
          rest = <assignTemp>$3.slice(::Range.new(1, -1, false))
          <assignTemp>$2
        end
        ::T.reveal_type(rest)
        <emptyTree>
      end
    end
  end
  <emptyTree>
```

Calling `.slice` on the given array returns a nilable array as a result, but `rest` should always be an empty array of the given type.

I am not sure what the best way to fix this is but my first reaction would be to wrap the whole `.slice` call with a `::T.must` to tell Sorbet that it should not consider `rest` as a nilable type. If that sounds right, I can make the patch. @jez, any thoughts?

**Comment by jez** [comment]
I think a better approach might be to make `<Magic>` intrinsics that do something that we think more accurately models this sort of destructuring. That's what we were trying to do with `<Magic>.<expand-splat>` (the return type of that method is computed based on the types of the input arguments in `calls.cc`). It's clear that `<Magic>.<expand-splat>` doesn't capture what we want it to, nor does the call to `.slice`.

So I think the best solution would be to get rid of the `.slice` and change / introduce some intrinsics that model Ruby more accurately.

But if you think that the `T.must` change is quick and want to see if it gets close enough, I'm happy for you to try it and see if it complains on Stripe's codebase.

**Comment by Tim-Willard** [comment]
Should this issue be re-opened given that the fix was reverted in #2878?

**Comment by davidstosik** [comment]
Confirming this still seems to be a problem:

```rb
ary = []
first, rest = *ary
T.reveal_type(rest) #=> T.nilable(T::Array[T.untyped])
```
([Check on Sorbet.run.](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0Aextend%20T%3A%3AHelpers%0A%0Aary%20%3D%20%5B%5D%0Afirst%2C%20*rest%20%3D%20ary%0AT.reveal_type%28rest%29))

**Comment by paracycle** [comment]
> Confirming this still seems to be a problem:
> 
> ```ruby
> ary = []
> first, rest = *ary
> T.reveal_type(rest) #=> T.nilable(T::Array[T.untyped])
> ```
> 
> ([Check on Sorbet.run.](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0Aextend%20T%3A%3AHelpers%0A%0Aary%20%3D%20%5B%5D%0Afirst%2C%20*rest%20%3D%20ary%0AT.reveal_type%28rest%29))

@davidstosik In your example Sorbet is correct, though:
```ruby
first, rest = *[]
rest #=> nil
```

Did you mean to put a `*` before `rest`?

**Comment by davidstosik** [comment]
@paracycle Sorry I didn't get back to you, I missed that notification.
I was a bit confused but then I checked the example I linked on Sorbet.run and you are right, I meant to put the `*` before `rest`.
```rb
# typed: true
extend T::Sig
extend T::Helpers

ary = []
first, *rest = ary
T.reveal_type(rest)
# Revealed type: T.nilable(T::Array[NilClass])
```

`rest` is not supposed to be nilable, correct?
