### ISSUE TITLE
Type alias resolution with constant assignments

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#2038]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20A%0A%20%20Result%20%3D%20T.type_alias%20%7BB%3A%3AResult%5BInteger%5D%7D%0Aend%0A%0Amodule%20B%0A%20%20Result%20%3D%20C%3A%3AResult%0Aend%0A%0Amodule%20C%0A%20%20module%20Result%0A%20%20%20%20extend%20T%3A%3AGeneric%0A%0A%20%20%20%20X%20%3D%20type_member(%3Aout)%0A%20%20end%0Aend%0A)

```ruby
# typed: true

module A
  Result = T.type_alias {B::Result[Integer]}
end

module B
  Result = C::Result
end

module C
  module Result
    extend T::Generic

    X = type_member(:out)
  end
end
```

#### Observed output

```

module C
  module Result
    extend T::Generic

    X = type_member(:out)
  end
end

editor.rb:4: Integer cannot be used for type member ::C::Result::X https://srb.help/7028
     4 |  Result = T.type_alias {B::Result[Integer]}
                                           ^^^^^^^
    editor.rb:4: Integer is not a subtype of <todo sym>
     4 |  Result = T.type_alias {B::Result[Integer]}
                                           ^^^^^^^

editor.rb:4: Integer cannot be used for type member ::C::Result::X https://srb.help/7028
     4 |  Result = T.type_alias {B::Result[Integer]}
                                           ^^^^^^^
    editor.rb:4: <todo sym> is not a subtype of Integer
     4 |  Result = T.type_alias {B::Result[Integer]}
                                           ^^^^^^^
Errors: 2
```

#### Expected behavior

No errors
- - -

This is a problem in the `ResolveTypeParamsWalk` of the resolver, as it should be tracking the dependency between the `Result` constant assignment, and the type alias. This could be as simple as making sure to walk through aliases when checking if a type has been fully resolved.

**Comment by elliottt** [comment]
cc @Morriar 
cc @paracycle

**Comment by Morriar** [comment]
🎉
