### ISSUE TITLE
Only one workaround to get "srb init" to work with Ruby 2.7.0-preview1

### ISSUE THREAD

**Issue by jasnow** [sorbet/sorbet#2040]
Had to change "VOID = Module.new.freeze" to "VOID = Module.new #.freeze"
in /Users/USER/.rvm/gems/ruby-2.7.0-preview1@ruby2.7-no-rails/gems/sorbet-runtime-0.4.4933/lib/types/private/types/void.rb file to get "srb init" to work with Ruby 2.7.0-preview1.
Unclear how to fix it correctly.

Other "srb" options not tried yet.

Sorbet: 0.4.4933
Ruby:   2.7.0preview1 (2019-05-31 trunk c55db6aa271df4a689dc8eb0039c929bf6ed43ff) [x86_64-darwin16]
Rails:  6.1.0.alpha or 6.0.0

**Comment by DarkDimius** [comment]
Why did you have to change that?
What was the error?

**Comment by jasnow** [comment]
Ran "SRB_YES=1 bundle exec srb init" and got: https://gist.github.com/jasnow/3b64231769ab41cc072a3a201b4faea3

**Comment by jez** [comment]
I chatted with @XrXr  and he said this is a known issue with 2.7.0-preview1 and that it's fixed in 2.7.0-preview2.

Thanks Alan!

**Comment by jasnow** [comment]
2.7.0-preview2 will be a much harder upgrade.
