### ISSUE TITLE
Lazy Enumerable Typed Incorrectly

### ISSUE THREAD

**Issue by bmalinconico** [sorbet/sorbet#2048]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0AT.reveal_type(%5B1%5D.lazy.select(%26%3Aeven%3F)))

#### Observed output
```ruby
# typed: true
T.reveal_type([1].lazy.select(&:even?))
# => Revealed type: T::Array[Integer] 
irb(main):001:0> [1].lazy.select(&:even?).class
# => Enumerator::Lazy
```

#### Expected behavior

The [Enumerable RBI](https://github.com/sorbet/sorbet/blob/fd537c1af87d87915198ed1808a82ac30f66109a/rbi/core/enumerable.rbi) file contains methods definitions which all return arrays of `Elem`. Most of the methods, actually return another Lazy Enumerable. (#chunk, #chunk_while, #collect, #collect_concat, #drop, #drop_while, #enum_for, #find_all, #flat_map, #grep, #grep_v, #lazy, #map, #reject, #select, #slice_after, #slice_before, #slice_when, #take, #take_while, #to_enum, #uniq, #zip) 

I should be able to make this change if it only requires making a duplicate `Enumerable` module returning the correct values and mixing it in [here](https://github.com/sorbet/sorbet/blob/c843cfad7156eaea0abc27e21e10154266b3d557/rbi/core/enumerator.rbi#L413). I'd just like to ensure I make an acceptable change before I submit a PR.

**Comment by jez** [comment]
@bmalinconico I think we already have a definition for `Enumerator::Lazy`:

https://github.com/sorbet/sorbet/blob/d2f2e3d5a0233ad6a7562b778726111aa96c964a/rbi/core/enumerator.rbi#L413

It correctly models the inheritance hierarchy, according to `irb`:

```
irb(main):001:0> Enumerator::Lazy.ancestors
=> [Enumerator::Lazy, Enumerator, Enumerable, Object, Kernel, BasicObject]
```

I think the thing that's missing is that in fact, there are actually methods defined on this class that don't have the same signatures as they do in the parent class definitions. 

The Ruby docs echo what you mention w.r.t. `chunk` et al having their own definitions on Enumerator::Lazy:

https://docs.ruby-lang.org/en/2.6.0/Enumerator/Lazy.html

So I think the solution here is to update the existing definition of the `Enumerator::Lazy` class to override the parent class definitions such that they return lazy enumerators.

**Comment by bmalinconico** [comment]
@jez if adding them to the existing class is the preferable method, that should be something I can tackle at lunch.
