### ISSUE TITLE
Spurious Enumerable#inject/reduce "Not enough arguments provided" error

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#21]
This shouldn't be a type error:

https://sorbet.run/#%5B%7Bfoo%3A%20'bar'%7D%2C%20%7Bbaz%3A%20'bat'%7D%5D.inject(%26%3Amerge)%0A

`inject` will pass each enumerable member in turn as the argument to `merge` (with the memo or initial member as receiver), so the "Not enough arguments provided" error is spurious.

see https://ruby-doc.org/core-2.4.0/Enumerable.html#method-i-reduce

Originally reported by @dug-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1565

**Comment by axyjo** [comment]
Just ran into this in the Stripe codebase as well 

cc @akshay-stripe

**Comment by marianosimone** [comment]
This seems to be fixed now 🤷‍♂
