### ISSUE TITLE
srb init hangs

### ISSUE THREAD

**Issue by andrewbaxter** [sorbet/sorbet#2110]
#### Input
On Linux, Ruby 2.6.3p62.

Our Gemfile looks like:
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 2.5.1'

gem 'sidekiq'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # style checking
  gem 'rubocop', '~> 0.57.2', require: false
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'devise'
gem 'activeadmin'
gem 'activeadmin_addons'
gem 'httparty', '~> 0.16.2'
gem 'paper_trail', '~> 9.2.0'
gem 'addressable', '~> 2.5.2'
gem 'sidekiq-scheduler', '~> 3.0.0'
gem 'tod', '~> 2.1.1'
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'sorbet-rails'

gem "pundit", "~> 2.1"

gem "cancan", "~> 1.6"
```

pundit and cancan were added as a workaround for #925.

#### Observed output

`srb init` has been running for 4 hours, using 2 cores 100%.

`du -sb sorbet/` stays still at `1721753` bytes.

#### Expected behavior

So, I'd expect this to have completed within maybe 10 minutes tops.  I've used Typescript and MyPy and neither have an init step nor do they take any real time to perform analyses.

I should probably ask first though:
1. How long is this generally expected to take?
2. Is there a way to get more detailed progress information?

**Comment by jasnow** [comment]
Can you share the "srb init" output (even if you have to ^C it) as a gist?

You can also save the output using this command:
```
SRB_YES=1 srb init 2>&1 |tee file.txt
```

**Comment by andrewbaxter** [comment]
I left it running for now, all the output was still in my buffer: https://gist.github.com/andrewbaxter/e15e1360c1acb8a9fc5099f9574ead4c

**Comment by jasnow** [comment]
Looked at the gist - everything looks okay. Is it possible to share the repo?

**Comment by andrewbaxter** [comment]
Thanks for taking a look at this, by the way!

It's customer code so that might be difficult, I'd be glad to do debugging on my side though if there's diagnostics or anything we could provide.  It's a pretty straightforward project, although we're probably not using all the correct idioms in the code.

**Comment by jasnow** [comment]
Try this:
  1. Clone my repo: https://github.com/jasnow/rails_5.2_new26.git
     * Your Gemfile file is included. I added sqlite3 gem to the bottom of your/my Gemfile.
  2. Run "bundle"/"rake"/etc - they should work. It worked on my Mid-2014 MacBook Pro running Sierra.
  3. Run "srb init" and it should finish in less than a minute.
  4. If not, tell me what to change on my repo.

**Comment by jasnow** [comment]
Which linux dist are you using?

**Comment by andrewbaxter** [comment]
I'm using Arch locally.  Thanks, I'll try the above!

**Comment by jasnow** [comment]
Another idea: Add "--debug-log-file=file.log" and share it (if not sensitive) as a gist.

**Comment by jasnow** [comment]
Any update?

**Comment by jasnow** [comment]
@andrewbaxter - Any update?

**Comment by andrewbaxter** [comment]
Sorry, I had to prioritize other tasks but I'm hoping I'll have a chance to get back to this this week.

**Comment by andrewbaxter** [comment]
Thank you, reinstalling from your fork made me remember that the `vendor/` directory was in the project directory.  I think that rather than hanging, it was just trying to generate spec files for everything in `vendor/`... Placing the vendor directory outside the project directory made `srv init` complete (in finite time).

If it would be possible, it would be great if `srb` could ignore the vendor directory automatically.  Bundle itself could be understood to suggest placing it in the project directory if you aren't using a system-wide gem cache:
>       bundle install --path vendor/bundle
>
>  to install the gems into ./vendor/bundle/, ...
so I would expect this is a fairly common situation.

If not though I believe this issue can be closed.

**Comment by jasnow** [comment]
# Update
 * At 11:10am today, I posted question  to Slack/Sorbet/discuss channel.
   * Tried suggestion: Tried adding --ignore=/vendor" to sorbet/config file before "src init" did not work for me.
 * Itemize options I see
        -1- Add this warning to "srb init" initial paragraph.
```
3.  If you do NOT want to include your "vendor" directory, you will
    need to moved it outside the project before running 'srb init'.
    Then after "srb init" runs, move "vendor" directory back and
    add "--ignore=/vendor" to sorbet/config file.
```
       -2- Add to FAQ web page
       -3- Add to Troubleshooting web page
       -4- Keep it AS-IS

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
