### ISSUE TITLE
Bug with sorbet parser for custom `and`, `or`, `not` method

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#2122]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(x%3A%20T.untyped).returns(A)%20%7D%0A%20%20def%20and(x)%0A%20%20%20%20self%0A%20%20end%0A%0A%20%20sig%20%7B%20params(x%3A%20T.untyped).returns(A)%20%7D%0A%20%20def%20or(x)%0A%20%20%20%20self%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20a%20%3D%20A.new%0A%20%20%23%20fine%0A%20%20a.and(1).or(2)%0A%0A%20%20%23%20unexpected%0A%20%20a.and(1).%0A%20%20%20%20or(2)%0A%0A%20%20%23%20things%20start%20to%20go%20wrong%20after%20this%0A%20%20a.and(1).or(2)%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig { params(x: T.untyped).returns(A) }
  def and(x)
    self
  end

  sig { params(x: T.untyped).returns(A) }
  def or(x)
    self
  end
end

def main
  a = A.new
  # fine
  a.and(1).or(2)

  # unexpected
  a.and(1).
    or(2)

  # things start to go wrong after this
  a.and(1).or(2)
end
```

#### Observed output

```
editor.rb:23: unexpected token kOR https://srb.help/2001
    23 |    or(2)
            ^^

editor.rb:26: Method and does not exist on NilClass https://srb.help/7003
    26 |  a.and(1).or(2)
          ^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:26: Replace with rand
    26 |  a.and(1).or(2)
            ^^^

Errors: 2
```

#### Expected behavior

When `and`, `or`, `not` are defined as method and used in a chain method as a start of a function, sorbet will parse it wrongly. It works when the .or is on the same line with the rest of the chain.

Rails define these methods for their AREL so people using it with chaining may find sorbet reporting false negative

- - -

**Comment by jez** [comment]
This is an explicit break with Ruby compatibility:

https://github.com/sorbet/sorbet/pull/1993

Alternatives:

- write it on one line
- write it like

```ruby
a.and(1)
  .or(2)
```

- use `public_send`:

```
a.and(1).
  public_send(:or, 2)
```

- rename the method

**Comment by orangethunder** [comment]
https://srb.help/2001 still says "If you encounter this error but your code is accepted by Ruby itself, this is a bug in our parser", but according to this ticket's resolution it's intentional. As such, either the help needs to be updated or Sorbet needs to be updated to display a different error in these cases. I think this ticket should stay open until it's resolved, unless a follow-up ticket exists.
