### ISSUE TITLE
Detect unnecessary safe navigation

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#2124]
### Problem
I was expecting this to already be a feature (I vaguely remember seeing it before, and I see at least one improvement request for it in #36), but the following example doesn't seem to work.

[See in sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Amy_nilable_thing%20%3D%20T.let(''%2C%20T.nilable(String))%0Amy_non_nilable_thing%20%3D%20T.let(''%2C%20String)%0A%0Areversed_nilable%20%3D%20my_nilable_thing%26.reverse%0Areversed_non_nilable%20%3D%20my_non_nilable_thing%26.reverse%0A%0Amy_result%20%3D%20reversed_non_nilable%20%7C%7C%20reversed_nilable)

```ruby
# typed: strict
my_nilable_thing = T.let('', T.nilable(String))
my_non_nilable_thing = T.let('', String)

reversed_nilable = my_nilable_thing&.reverse
reversed_non_nilable = my_non_nilable_thing&.reverse # here the sage navigation is unnecessary, and I'm not being told about it :(

my_result = reversed_non_nilable || reversed_nilable # which made me confidently write this line, which will never hit the reversed_nilable variable
```

### Proposed solution

Warn or error out on unnecessary safe navigations

**Comment by dduugg** [comment]
Sorbet can sometimes flag unnecessary use of safe navigation. This is via a somewhat confusing "unreachable code" message (see https://github.com/sorbet/sorbet/issues/36 ). I would also like to see this applied more broadly. 

For instance, [this](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%20Time.at(0)%0Aif%20x%26.sec%0A%20%20puts%20x%0Aend) is flagged for containing unreachable code (more correctly, it uses safe navigation unnecessarily):
```ruby
x = Time.at(0)
if x&.sec
  puts x
end
```
while [this](https://sorbet.run/#Time.at(0)%26.sec%0A) simpler case is undetected:
```ruby
Time.at(0)&.sec
```

**Comment by marianosimone** [comment]
This was partially fixed by https://github.com/sorbet/sorbet/pull/3277 (my initial examples now work)

`Time.at(0)&.sec` is still undetected

**Comment by marianosimone** [comment]
Oh, actually... I think the problem is actually different:

Safe navigation is not detected on standalone expressions:

```ruby

x = Time.at(0)

a = x&.sec # This detected!
if x&.sec # This is, too
  puts 'ok'
end
x&.sec # But this is not

```

See full example in [sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%20Time.at(0)%0A%0Aa%20%3D%20x%26.sec%20%23%20This%20detected!%0Aif%20x%26.sec%20%23%20This%20is%2C%20too%0A%20%20puts%20'ok'%0Aend%0Ax%26.sec%20%23%20But%20this%20is%20not%0A)

**Comment by Morriar** [comment]
Fixed on current master.
