### ISSUE TITLE
Exception matcher reports that message does not exist

### ISSUE THREAD

**Issue by International** [sorbet/sorbet#2126]
Hi, I noticed the following behaviour today, and I looked through the documentation, but I wasn't able to find something mentioning the usecase below.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0APotatoException%20%3D%20Class.new(StandardError)%0AEXCEPTION_MATCHER%20%3D%20Class.new%20do%0A%20%20def%20self.%3D%3D%3D(exception)%0A%20%20%20%20exception.class%20!%3D%20PotatoException%0A%20%20end%0Aend%0A%0Adef%20try_me%0A%20%20raise%20PotatoException%2C%20%22no%22%0Arescue%20EXCEPTION_MATCHER%20%3D%3E%20e%0A%20%20puts%20%22error%3A%20%23%7Be.message%7D%22%0Aend)

```ruby
# typed: true
PotatoException = Class.new(StandardError)
EXCEPTION_MATCHER = Class.new do
  def self.===(exception)
    exception.class != PotatoException
  end
end

def try_me
  raise PotatoException, "no"
rescue EXCEPTION_MATCHER => e
  puts "error: #{e.message}"
end
```

#### Observed output

```
editor.rb:12: Method message does not exist on EXCEPTION_MATCHER https://srb.help/7003
    12 |  puts "error: #{e.message}"
                         ^^^^^^^^^
Errors: 1
```

#### Expected behavior

Do not show an error on the call to `.message`, as `e` responds to `.message`.

**Comment by jez** [comment]
`EXCEPTION_MATCHER` is not a subclass of `Exception`, so this is working as intended.

Sorbet does not support (and probably will not support) defining arbitrarily complicated overrides of `===`.

The suggested work around is to filter out exceptions you don't care about inside the rescue block, not inside the `===` of the rescue:

```ruby
class PotatoException < StandardError; end

def try_me
  raise PotatoException, "no"
rescue StandardError => e
  raise if e.class == PotatoException

  puts "error: #{e.message}"
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20PotatoException%20%3C%20StandardError%3B%20end%0A%0Adef%20try_me%0A%20%20raise%20PotatoException%2C%20%22no%22%0Arescue%20StandardError%20%3D%3E%20e%0A%20%20raise%20if%20e.class%20%3D%3D%20PotatoException%0A%0A%20%20puts%20%22error%3A%20%23%7Be.message%7D%22%0Aend)

**Comment by sorra** [comment]
The workaround does not work when I need the next `rescue` block to catch any unmatched exception.
The next `rescue` cannot catch a reraised exception.
```ruby
# typed: true
class PotatoException < StandardError; end

def try_me
  raise PotatoException, "no"
rescue StandardError => e
  raise if e.class == PotatoException
rescue => e
  puts "rescued: #{e.message}"
end

try_me
```
