### ISSUE TITLE
experimental LSP documentHighlight (and textDocument/refererences) returns results that are not ideal

### ISSUE THREAD

**Issue by lgo** [sorbet/sorbet#2133]
## Issue
See #1623 (https://github.com/sorbet/sorbet/pull/1623#issuecomment-522358192) / #2105 for context. This blocks #1149, a GA of the documentHighlight LSP features. 

In particular, the locations used are not specific enough for usable results.
- When showing locations for declarations the entire declaration is included in the range, such as `def foo(bar: ..., ...)`.
- When showing method calls, the entire parameters are included in the range, such as the image below.

This also affects `textDocument/references` but the fault isn't as prominent because editors like VSCode show the results separately. In fact, it may be desirable to include more info like the parameters lines, but this is diverging behaviour from other LSPs such as type-script.

![image (1)](https://user-images.githubusercontent.com/1161183/68631386-8374c300-049f-11ea-9e41-d11530e51afe.png)

## Solution

There was some discussion about what the best approach to address this would be. There's two options:

1. Retaining locations for other parts, such as symbols / names during parsing, and carrying those through the AST nodes.

2. During the LSP method, narrow the location down by doing regex/parsing on the declaration / reference location.

There's a preference for (2) because we can scope the change to just LSP code, and it'll be simple to prototype. In particular, we can do regexes on just the intermediate string to attempt to find the location of the symbol.

It's not likely we can parse the AST ranges for the desired symbol, because many of the locations won't contain valid code. eg: declarations can contain the text `def foo`, which won't parse.

There are edge cases we'll need to handle with care, such as results with lines such as `attr_accessor :foo` or friends.

In order to test this change, we may also need to make changes to the existing tests to match on the exact ranges specified by the test-corpus `# ^^^^ ref:` lines. Otherwise, we'll need to come up with alternative ways to test it.

**Comment by lgo** [comment]
@jez, this is related to the issue you pointed out that you noticed on https://sorbet.run.

Because this is a known issue in the experimental feature, do you think it might make sense to explicitly not use this flag for sorbet.run?

We could also explicitly remove the flag, although I am using it to see any edge-cases so it is handy.

**Comment by lgo** [comment]
for example, this is undesired behaviour, where any of the method `Foo` tokens are highlighted.

https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%0A%20%20def%20self.Foo%0A%20%20end%0A%0Aend%0A%0AFoo.Foo%20do%0A%20%20%23%20...%0A%20%20%23%20...%0Aend%0A%0AFoo.Foo
<img width="206" alt="Screen Shot 2019-11-11 at 16 49 44" src="https://user-images.githubusercontent.com/1161183/68632419-50ccc980-04a3-11ea-9663-171ae76ad724.png">

whereas highlighting only `foo` in this case would be desirable, such as how typescript does it
![image (2)](https://user-images.githubusercontent.com/1161183/68632324-f92e5e00-04a2-11ea-9a12-0c382a504729.png)

**Comment by jez** [comment]
The problems with highlighting block regions were fixed.

It's not clear to me that the current behavior for highlighting the whole declLoc line is particularly bad?

But either way, I think we can make a more targeted issue for just that, and close this one.
