### ISSUE TITLE
Enforce triggered for signature

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#2149]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20params(spec%3A%20T.any(%0A%20%20%20%20%20%20Symbol%2C%0A%20%20%20%20%20%20%5BSymbol%2C%20Integer%5D%2C%0A%20%20%20%20%20%20%5BSymbol%5D%2C%0A%20%20%20%20))%0A%20%20%20%20.void%0A%20%20end%0A%20%20def%20foo(spec)%0A%20%20%20%20spec%20%3D%20%5Bspec%5D%20unless%20spec.is_a%3F%20Array%0A%20%20%20%20directive%20%3D%20spec.first%0A%20%20end%0Aend)

```ruby
# typed: true

class A
  extend T::Sig

  sig do
    params(spec: T.any(
      Symbol,
      [Symbol, Integer],
      [Symbol],
    ))
    .void
  end
  def foo(spec)
    spec = [spec] unless spec.is_a? Array
    directive = spec.first
  end
end
```

#### Observed output

```
Exception::raise(): core/types/subtyping.cc:18 enforced condition Types::isSubType(ctx, t1, ret) has failed:
TupleType {
  0 = Symbol
}
is not a super type of
AppliedType {
      klass = <C <U Array>>
      targs = [
        <C <U Elem>> = T.untyped
      ]
    } & (Symbol | TupleType {
              0 = Symbol
              1 = Integer
            } | AppliedType {
          klass = <C <U Array>>
          targs = [
            <C <U Elem>> = Symbol
          ]
        })
was lubbing with TupleType {
  0 = Symbol
}
```

#### Expected behavior

No enforce should be triggered.

- - -

**Comment by jez** [comment]
This doesn't reproduce anymore, I'm guessing this was fixed in #6079.
