### ISSUE TITLE
net.rbi missing alternate spellings of "Timeout" response code classes

### ISSUE THREAD

**Issue by bradleybuda** [sorbet/sorbet#2162]
In Ruby's `net/http`, there are two response subclasses that have aliases: `Net::HTTPGatewayTimeOut` [is also defined as](https://github.com/ruby/ruby/blob/master/lib/net/http/responses.rb#L207) `Net::HTTPGatewayTimeout` and `Net::HTTPRequestTimeOut` [is also defined as](https://github.com/ruby/ruby/blob/master/lib/net/http/responses.rb#L125) `Net::HTTPRequestTimeout`. Sorbet is only aware of the `TimeOut` version of these classes. The `Timeout` versions are not in the rdocs (they were added in [this change](https://github.com/ruby/ruby/commit/660740a75dd9526ad9a2732ea87c8ab5a385ef1f)), but it's not clear to me that they are intended to be internal or hidden and code that uses them fails to type check:

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Arequire%20'net%2Fhttp'%0A%0Ap%20Net%3A%3AHTTPGatewayTimeout%0Ap%20Net%3A%3AHTTPGatewayTimeOut)

```ruby
# typed: true

require 'net/http'

p Net::HTTPGatewayTimeout
p Net::HTTPGatewayTimeOut
```

#### Observed output

```
editor.rb:5: Unable to resolve constant HTTPGatewayTimeout https://srb.help/5002
     5 |p Net::HTTPGatewayTimeout
          ^^^^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:5: Replace with Net::HTTPFatalError
     5 |p Net::HTTPGatewayTimeout
          ^^^^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:5: Replace with Net::HTTPBadGateway
     5 |p Net::HTTPGatewayTimeout
          ^^^^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:5: Replace with Net::HTTPGatewayTimeOut
     5 |p Net::HTTPGatewayTimeout
          ^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/stdlib/net.rbi#L3541: Did you mean: Net::HTTPFatalError?
    3541 |class Net::HTTPFatalError < Net::ProtoFatalError
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/stdlib/net.rbi#L3480: Did you mean: Net::HTTPBadGateway?
    3480 |class Net::HTTPBadGateway < Net::HTTPServerError
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/stdlib/net.rbi#L3553: Did you mean: Net::HTTPGatewayTimeOut?
    3553 |class Net::HTTPGatewayTimeOut < Net::HTTPServerError
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

No error

- - -

I would include a patch but it looks like [net.rbi](https://github.com/sorbet/sorbet/blob/master/rbi/stdlib/net.rbi) is generated by a tool that is not (AFAICT) open source?

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
