### ISSUE TITLE
ENVClass rbi is currently missing many methods on ENV

### ISSUE THREAD

**Issue by andrew-stripe** [sorbet/sorbet#2174]
#### Input
[→ View on sorbet.run](https://sorbet.run/#ENV.replace(%7B%7D)%0AENV.assoc(%22HOME%22))

```ruby
ENV.replace({})
ENV.assoc("HOME")
```

#### Observed output

```
editor.rb:1: Method replace does not exist on Sorbet::Private::Static::ENVClass https://srb.help/7003
     1 |ENV.replace({})
        ^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:1: Replace with reduce
     1 |ENV.replace({})
            ^^^^^^^


editor.rb:2: Method assoc does not exist on Sorbet::Private::Static::ENVClass https://srb.help/7003
     2 |ENV.assoc("HOME")
        ^^^^^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior
Both of these methods should be defined. There are also several other missing methods on ENV but I didn't work through manually diffing the whole method list since I was hoping there's an automated way to regenerate this.

RBI for reference: https://github.com/sorbet/sorbet/blob/bec5b685d1a806711cd3e0a88b9dfda286700968/rbi/sorbet/sorbet.rbi#L68-L215

I'm also not sure `T.nilable[String]` is the right type for the element value:
https://github.com/sorbet/sorbet/blob/bec5b685d1a806711cd3e0a88b9dfda286700968/rbi/sorbet/sorbet.rbi#L71

In Ruby 2.6.5:
```
ENV["abc"] = nil
ENV.to_h.key?("abc") # false
```

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong

ENVClass support in Sorbet is a hack, because it's IMO a hack in Ruby too. Anything we do in Sorbet is likely to be an approximation, so we welcome approximate solutions here.
