### ISSUE TITLE
`missing_methods` negates `const` checking

### ISSUE THREAD

**Issue by nelhage-stripe** [sorbet/sorbet#219]
Sorbet [deliberately does not generate](https://github.com/stripe/sorbet/blob/0bd8e2d8e3ee63980afe1edb3b034fe2c872e160/dsl/ChalkODMProp.cc#L174-L180) mutators for `const` props in `T::Struct`, since they can't be mutated.

However, at runtime, `T::Struct` [does do so](https://github.com/stripe/sorbet/blob/0bd8e2d8e3ee63980afe1edb3b034fe2c872e160/runtime/lib/types/props/decorator.rb#L450-L452) in order to raise a more-specific error message.

This results in `missing_methods.rbi` shim-generation reifying these methods, destroying the valuable static checking that users would have gotten out of Sorbet not creating those methods! This just bit me in a surprising way, where a bug I would have expected sorbet to catch passed through.

**Comment by jez** [comment]
Woo @pjsk-stripe fixed this 🎉

**Comment by jez** [comment]
Fixed in #1835
