### ISSUE TITLE
Abstract method implementations on a `final!` class cannot accept default arguments

### ISSUE THREAD

**Issue by zanemiller-stripe** [sorbet/sorbet#2229]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Iface%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20sig%20do%0A%20%20%20%20abstract%0A%20%20%20%20.params(%0A%20%20%20%20%20%20bar%3A%20String%2C%0A%20%20%20%20).void%0A%20%20end%0A%20%20def%20foo(bar%3D%27%27)%3B%20end%0Aend%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20include%20Iface%0A%20%20final!%0A%0A%20%20sig(%3Afinal)%20do%0A%20%20%20%20override%0A%20%20%20%20.params(%0A%20%20%20%20%20%20bar%3A%20String%0A%20%20%20%20).void%0A%20%20end%0A%20%20def%20foo(%0A%20%20%20%20%23%20This%20causes%20a%20pretty%20hard%20to%20understand%20error%0A%20%20%20%20bar%3D%27%27%0A%20%20)%3B%20end%0A%0A%20%20sig(%3Afinal)%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20bar%3A%20String%0A%20%20%20%20).void%0A%20%20end%0A%20%20def%20non_interface_method(%0A%20%20%20%20%23%20This%20is%20fine%2C%20apparently%0A%20%20%20%20bar%3D%27%27%0A%20%20)%3B%20end%0Aend%0A)

```ruby
# typed: true
module Iface
  extend T::Sig
  extend T::Helpers
  interface!

  sig do
    abstract
    .params(
      bar: String,
    ).void
  end
  def foo(bar=''); end
end

class A
  extend T::Sig
  extend T::Helpers
  include Iface
  final!

  sig(:final) do
    override
    .params(
      bar: String
    ).void
  end
  def foo(
    # This causes a pretty hard to understand error
    bar=''
  ); end

  sig(:final) do
    params(
      bar: String
    ).void
  end
  def non_interface_method(
    # This is fine, apparently
    bar=''
  ); end
end

```

#### Observed output

```
editor.rb:30: A was declared as final but its method foo<defaultArg>1 was not declared as final https://srb.help/5048
    30 |    bar=''
                ^^
Errors: 1
```

#### Expected behavior

This example should pass type checking. In the provided example there is no way to implement the interface in a `final!` class.

- - -

I tested this example in a variety of styles and none of the following behaved as expected:
- Positional argument defaulted in the interface
- Keyword argument defaulted in the interface
- Positional argument defaulted only in the implementation
- Keyword argument defaulted only in the implementation

**Comment by jez** [comment]
We reworked how default args are checked in #3366.
