### ISSUE TITLE
Sorbet flags String slicing with open-ended ranges

### ISSUE THREAD

**Issue by mkillianey-stripe** [sorbet/sorbet#2239]
String slicing using open-ended ranges seems to be fairly idiomatic Ruby.  Ideally, Sorbet would support this use.  If it doesn't, it would be helpful for the error message to suggest a workaround, like replacing `"example"[x..]` with `"example"[x..-1]`.

#### Input

https://sorbet.run/#%23%20typed%3A%20true%0A%0A%23%20Should%20parse%3A%0As%20%3D%20%22this%20example%22%5B5..-1%5D%0As%20%3D%20%22this%20example%22%5B5..%5D%0As%20%3D%20%22this%20example%22%5B5...%5D%0A%0A%23%20Related%3A%0AT.reveal_type(%5B5..-1%5D)%20%23%20T%3A%3ARange%5BInteger%5D%0AT.reveal_type(%5B5..%5D)%20%20%20%23%20T%3A%3ARange%5BT.nilable(Integer)%5D%5D%0AT.reveal_type(%5B5...%5D)%20%20%23%20T%3A%3ARange%5BT.nilable(Integer)%5D%5D

```ruby
# typed: true

# Should parse:
s = "this example"[5..-1]
s = "this example"[5..]    # <== flags as type error in 0.4.5073
s = "this example"[5...]   # <== flags as type error in 0.4.5073

# Related:
T.reveal_type([5..-1]) # T::Range[Integer]
T.reveal_type([5..])   # T::Range[T.nilable(Integer)]]
T.reveal_type([5...])  # T::Range[T.nilable(Integer)]]
```

#### Observed output

```
editor.rb:5: Expected T.any(T::Range[Integer], Regexp) but found T::Range[T.nilable(Integer)] for argument arg0 https://srb.help/7002
     5 |s = "this example"[5..]
            ^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/string.rbi#L264: Method String#[] (overload.1) has specified arg0 as T.any(T::Range[Integer], Regexp)
     264 |        arg0: T.any(T::Range[Integer], Regexp),
                  ^^^^
  Got T::Range[T.nilable(Integer)] originating from:
    editor.rb:5:
     5 |s = "this example"[5..]
                           ^^^

editor.rb:6: Expected T.any(T::Range[Integer], Regexp) but found T::Range[T.nilable(Integer)] for argument arg0 https://srb.help/7002
     6 |s = "this example"[5...]
            ^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/string.rbi#L264: Method String#[] (overload.1) has specified arg0 as T.any(T::Range[Integer], Regexp)
     264 |        arg0: T.any(T::Range[Integer], Regexp),
                  ^^^^
  Got T::Range[T.nilable(Integer)] originating from:
    editor.rb:6:
     6 |s = "this example"[5...]
                           ^^^^
```

#### Expected behavior

I expect the example to parse...if not, I expect it to advise me to fix the problem by closing the range on my slice.

**Comment by jez** [comment]
> seems to be fairly idiomatic Ruby

On the contrary, this feature is nearly brand new to Ruby (2.6), and as such Sorbet doesn't support it yet.

**Comment by jez** [comment]
#972

**Comment by aisamanra** [comment]
It actually looks like Sorbet is parsing this correctly and typing it incorrectly. If I write `T.reveal_type(5..)` Sorbet tells me that it has the type `T::Range[T.nilable(Integer)]`. It looks like this is because we desugar `(5..)` into `Range.new(5, nil)`, which is _also_ correct:
```ruby
irb(main):001:0> (5..)
=> 5..
irb(main):002:0> Range.new(5, nil)
=> 5..
```
but the problem is that we treat that as though it's defining a range of nilable integers, and we instead should treat it as a range of integers. What this means is: this is actually a small matter of updating the RBI for `Range`, which is an easy fix!
