### ISSUE TITLE
The signature of Time.initialize(..) seems incorrect

### ISSUE THREAD

**Issue by tanin47** [sorbet/sorbet#2245]
Sorbet tags this signature to `Time.new(..)`:

```
def initialize(year=T.unsafe(nil), month=T.unsafe(nil), day=T.unsafe(nil), hour=T.unsafe(nil), min=T.unsafe(nil), sec=T.unsafe(nil), usec_with_frac=T.unsafe(nil)); end
```

Ref: https://github.com/sorbet/sorbet/blob/master/rbi/core/time.rbi#L620

According to Rubydoc, the signature of Time.new(..) is:

```
new(year, month=nil, day=nil, hour=nil, min=nil, sec=nil, tz=nil) 
```

Ref: https://ruby-doc.org/core-2.6.3/Time.html#method-c-new

`usec_with_frac` doesn't seem to exist in Rubydoc.

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
