### ISSUE TITLE
Superclasses are not checked to be classes

### ISSUE THREAD

**Issue by AaronC81** [sorbet/sorbet#2252]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20A%3B%20end%0Aclass%20B%20%3C%20A%3B%20end%0A)

```ruby
# typed: true

module A; end
class B < A; end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

I would expect this to raise some kind of type error when `srb tc` is run, as subclassing a non-Class is always illegal (to my knowledge) and will throw an exception in the Ruby interpreter. I found this by forgetting to change `module` to `class` after refactoring an interface into an abstract class.

**Comment by DarkDimius** [comment]
Hi Aaron,

We're unlikely to prioretize implementing discovery of errros that are reliably discovered by RubyVM(as you point out, this is always illegal and thus Ruby will always complain on this).

That said, this would be a welcome enhancement that is easy to add for external contributors.
