### ISSUE TITLE
Reveal_type raises a different error

### ISSUE THREAD

**Issue by neil-stripe** [sorbet/sorbet#226]
https://sorbet.run/#class%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20T.nilable(Integer)%2C%20y%3A%20T.nilable(Integer)).void%7D%0A%20%20def%20bar(x%2C%20y)%0A%20%20%20%20if%20x%20%7C%7C%20y%0A%20%20%20%20%20%20if%20x%0A%20%20%20%20%20%20%20%20T.reveal_type(y)%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20T.let(y%2C%20Integer)%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend

**Comment by jez** [comment]
Closing in favor of #649
