### ISSUE TITLE
Behavior of any + nilable + type parameter

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#2288]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20extend(T%3A%3ASig)%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AA)%0A%20%20%20%20%20%20.params(object%3A%20T.type_parameter(%3AA))%0A%20%20%20%20%20%20.returns(T.type_parameter(%3AA))%0A%20%20end%0A%20%20def%20self.foo(object)%3B%20end%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AA)%0A%20%20%20%20%20%20.params(object%3A%20T.nilable(T%3A%3AArray%5BT.type_parameter(%3AA)%5D))%0A%20%20%20%20%20%20.returns(T.type_parameter(%3AA))%0A%20%20end%0A%20%20def%20self.bar(object)%3B%20end%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AA)%0A%20%20%20%20%20%20.params(object%3A%20T.any(T%3A%3AArray%5BT.type_parameter(%3AA)%5D%2C%20T.type_parameter(%3AA)))%0A%20%20%20%20%20%20.returns(T.type_parameter(%3AA))%0A%20%20end%0A%20%20def%20self.baz(object)%3B%20end%0Aend%0A%0AT.reveal_type%20Foo.foo(T.let(%5B%5D%2C%20T.nilable(T%3A%3AArray%5BInteger%5D)))%0A%23%20%3D%3E%20T.nilable(T%3A%3AArray%5BInteger%5D)%0A%0AT.reveal_type%20Foo.bar(T.let(%5B%5D%2C%20T.nilable(T%3A%3AArray%5BInteger%5D)))%0A%23%20%3D%3E%20Integer%0A%0AT.reveal_type%20Foo.baz(T.let(%5B%5D%2C%20T.nilable(T%3A%3AArray%5BInteger%5D)))%0A%23%20%3D%3E%20T.nilable(Integer)%20%3F%3F%3F)

```ruby
# typed: true

class Foo
  extend(T::Sig)

  sig do
    type_parameters(:A)
      .params(object: T.type_parameter(:A))
      .returns(T.type_parameter(:A))
  end
  def self.foo(object); end

  sig do
    type_parameters(:A)
      .params(object: T.nilable(T::Array[T.type_parameter(:A)]))
      .returns(T.type_parameter(:A))
  end
  def self.bar(object); end

  sig do
    type_parameters(:A)
      .params(object: T.any(T::Array[T.type_parameter(:A)], T.type_parameter(:A)))
      .returns(T.type_parameter(:A))
  end
  def self.baz(object); end
end

T.reveal_type Foo.foo(T.let([], T.nilable(T::Array[Integer])))
# => T.nilable(T::Array[Integer])

T.reveal_type Foo.bar(T.let([], T.nilable(T::Array[Integer])))
# => Integer

T.reveal_type Foo.baz(T.let([], T.nilable(T::Array[Integer])))
# => T.nilable(Integer) ???
```

#### Observed output

```
T.reveal_type Foo.baz(T.let([], T.nilable(T::Array[Integer])))
# => T.nilable(Integer) ???
```

#### Expected behavior

I was expecting `T.nilable(T::Array[Integer])` since `T.nilable(T::Array[Integer])` will not match with the first member of the `any`: `T::Array[T.type_parameter(:A)]`, so it's supposed to match with the second part `T.type_parameter(:A)`?

**Comment by jez** [comment]
I don't think that Sorbet is wrong here—it has found a solution to the type variables that allows the check to happen. Substituting the solution into the type:

```ruby
solution: T.type_parameter(:A) == T.nilable(Integer)

    T.any(T::Array[T.type_parameter(:A)], T.type_parameter(:A))
    # substituting into type for object:
=>  T.any(T::Array[T.nilable(Integer)], T.nilable(Integer))
    # rewrite the type using just one `T.any`
=>  T.any(T::Array[T.nilable(Integer)], NilClass, Integer)
    # factor out the `NilClass` to `T.nilable`
=>  T.nilable(T.any(T::Array[T.nilable(Integer)], Integer)
```

Given that `T.nilable(T::Array[Integer]))` is a subtype of `T.nilable(T.any(T::Array[T.nilable(Integer)], Integer)`, the solution is indeed valid, and the call proceeds.

Note that TypeScript finds the same solution, given a similar setup:

https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAgEYEMBeAeAggPgAoFUArAU1gC5lDcBtAXQEpkAfZXZm3ZAb2DIhyGAAsATggDuyAKLjJ4wgHJlzYAF9goSLEQpyAD3QBbAA4AbcoUMBnGhDAWL7Wo5Opy4ps1YDhyFYwyOLktsgAvGhYNrbMANyaQA
