### ISSUE TITLE
Add documentation for T::Props

### ISSUE THREAD

**Issue by fzakaria** [sorbet/sorbet#2303]
### Problem

A discussion in Slack regarding adding a `sig` to `attr_reader`

### Proposed solution

Turns out you can do `include T::Props` in your class to leverage it.

It would be great to add this to the documentation.
I believe there was some work to also not have to `T.let` on constructor arguments too now so it should make for terse classes.

I think the following would be an [example](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20T%3A%3AProps%0A%20%20%0A%20%20prop%20%3Ax%2C%20Integer%0A%0A%20%20sig%20%7B%20params(x%3A%20Integer).void%20%7D%0A%20%20def%20initialize(x)%0A%20%20%20%20%40x%20%3D%20x%0A%20%20end%0A%0Aend%0A%0Adef%20main%0A%20%20A.new(91)%20%20%20%23%20error%3A%20Typo!%0A%20%20x%20%3D%20A.x%0A%20%20y%20%3D%20x%20%2B%201%0Aend):

```
# typed: true
class A
  extend T::Sig
  include T::Props
  
  prop :x, Integer

  sig { params(x: Integer).void }
  def initialize(x)
    @x = x
  end

end

def main
  A.new(91)   # error: Typo!
  x = A.x
end
```
Note: I couldn't get the sorbet.run example to work. The accessor wasn't being created.

**Comment by jez** [comment]
Relying on `T::Props` instead of `T::Struct` is definitely a "I know what I'm doing" kind of change. We're not comfortable documenting it visibly, because we don't really want to encourage its use. Our recommendation is to use `T::Struct`, or to manually write getters and setters.
