### ISSUE TITLE
Docs for constants on hover is broken for some symbol kinds

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#2311]
#### Input

[→ View on sorbet.run](TODO_replace_this_with_your_sorbet_run_link)

```ruby
# TODO: In addition to the sorbet.run link, replace this comment with your code
# (makes it easier to search for issues)
```

#### Observed output

```
TODO: Replace this with the output in sorbet.run
(sorbet.run output changes over time)
```

#### Expected behavior

- - -

**Comment by aisamanra** [comment]
@jez Do you have an example or any other content you can add here? (I assume you added this as a placeholder, but it'd be nice to have a bit more detail here just in case.)

**Comment by jez** [comment]
Context was in #2312; i forgot to move it over to this issue after merging that.

The incorrect behavior had to do with the handling of type members. I thought we were wrong at first. I don't know why I thought that, because the test passed in CI that I thought would fail, and then I confirmed that it also worked in the editor manually.

The only thing left that could be construed as "wrong" is that for class aliases we show the docs for the dealiased symbol, which I think is actually preferable in some cases, so I'm going to close this.
