### ISSUE TITLE
`sig` leaking allocations when `T.untyped` in params or returns

### ISSUE THREAD

**Issue by robertjlooby** [sorbet/sorbet#2326]
I've made a simple repo that reproduces the issue [here](https://github.com/robertjlooby/sorbet_sig_leak). Essentially I'm seeing a major performance hit whenever the params/return in a sig has a `T.untyped`. Not sure if it's the root cause or not (or even if it's expected), but a method with a type signature like

```ruby
sig {params(num: Integer).returns(T.untyped)}
def self.test(num)
  ...
end
```

is performing an allocation [here](https://github.com/sorbet/sorbet/blob/b4d2c1a0f78a6694ecdc75d3e83431e1ad50c474/gems/sorbet-runtime/lib/types/private/methods/call_validation.rb#L126) every time it is called.

**Comment by DarkDimius** [comment]
It's not a bug but a feature ;-). We have custom wrappers for runtime for 
what we consider simple types for common method arities, based on 
experience in Stripe's codebase.

That code doesn't consider T.untyped as a simple type(you'll see a similar 
result for other complex types).

How much overhead do you see in practice? As long as method does something 
useful, we see under 7% overhead averaged over all of Stripe API for all 
runtime typechecking.

**Comment by robertjlooby** [comment]
Interesting. The allocation thing is probably a red herring then. Our actual type is more complicated. It's essentially:

```ruby
sig do
  params(
    arg1: T::Hash[String, T.untyped],
    arg2: T::Hash[String, T.any(Type1, Type2)],
  ).void
end
```

That method get's called in a loop on the order of ~300k times and is ~1000x slower with the `sig` vs no `sig` or adding a `.checked(:never)` (666 sec vs 0.74 sec). Is there anything specific that jumps out as obviously a performance issue? i.e. is it the `T::Hash`es, the `T.untyped`, the `T.any`, or just the combination of all of them?

I'll try to see if I can fiddle with the reproduction scripts and get it to reproduce the performance hit we're seeing.

**Comment by robertjlooby** [comment]
So I think I finally got to the bottom of this and in retrospect it should have been obvious: runtime type checks for `T::Array` and `T::Hash` are `O(n)`. So it's nothing to do with the allocations or `T.untyped`s. In the example sig above `arg2` is a hash with a couple thousand keys which explains calling it with vs. without runtime type checks being ~1000x slower.
