### ISSUE TITLE
Cannot assert on left-hand values

### ISSUE THREAD

**Issue by andrewbaxter** [sorbet/sorbet#2330]
#### Input

```ruby
# typed: true
def main
  x = T.let(4, T.nilable(Integer))
  T.must(x) += 4
end
```

#### Observed output

```
editor.rb:4: unexpected token tOP_ASGN https://srb.help/2001
     4 |  T.must(x) += 4
                    ^^
Errors: 1
```

#### Expected behavior

I don't expect this to work as is, but the alternative (`x += 4`) is also clearly wrong.  In other languages prior assertions affect the flow analysis, but I don't think Sorbet does this (the assertion must be done at the location of usage).

Is there any way to handle this, other than rewriting the code to not use `+=`?

**Comment by XrXr** [comment]
How about [this](https://sorbet.run/#%23%20typed%3A%20true%0Adef%20main%0A%20%20x%20%3D%20T.let(4%2C%20T.nilable(Integer))%0A%20%20x%20%3D%20T.must(x)%0A%20%20T.reveal_type(x)%0A%20%20x%20%2B%3D%204%0Aend%0A)?
```ruby
# typed: true
def main
  x = T.let(4, T.nilable(Integer))
  x = T.must(x)
  T.reveal_type(x)
  x += 4
end
```

**Comment by DarkDimius** [comment]
This is a ruby parser restriction. You can't have a method call on left hand of assign
