### ISSUE TITLE
Disabling runtime checks

### ISSUE THREAD

**Issue by rendaw** [sorbet/sorbet#2331]
The documentation has a section called "Enabling runtime checks" which implies that these are not enabled by default, or at least that it is possible to disable them, but it doesn't actually describe this.  It only describes the nature of the runtime checks.

I couldn't find any documentation for disabling the runtime checks.  In our case, we have working code.  We'd like to add types, gradually, but due to missing type information and Sorbet bugs/not yet implemented things the runtime checks are raising false positives where the code would have otherwise run fine, reducing the reliability of our software.

I found WithoutRuntime via https://evilmartians.com/chronicles/sorbetting-a-gem, but trying it out:
```
# typed: true
require 'sorbet-runtime'

module A
  extend T::Sig::WithoutRuntime

  sig { params(x: T::Hash[String, String]).void }
  def self.som(x)
  end
end
```
yields
```
Traceback (most recent call last):
	1: from a.rb:4:in `<main>'
a.rb:7:in `<module:A>': undefined method `sig' for A:Module (NoMethodError)
```
(might be doing things wrong here)

Even if this did work though, I expect we'll still be at risk of runtime errors due to all the automatically generated typings, typings pulled in from dependencies, inferred typings, etc.

So this is kind of feedback, kind of a bug report, kind of a request for more documentation (on WithoutRuntime), kind of a request for a new feature (globally disabling runtime checks).

**Comment by XrXr** [comment]
https://sorbet.org/docs/runtime#checked-whether-to-check-in-the-first-place describes `T::Configuration.default_checked_level`, which can be used to disable type checking. As an alternative to disabling run time verification all together, you can configure `sorbet-runtime`'s behavior when it finds a type mismtach: https://sorbet.org/docs/tconfiguration

**Comment by DarkDimius** [comment]
^^^ Allan in right

> extend T::Sig::WithoutRuntime

It should probably have internal in the name. It's supposed to be a low level "I know what I'm doing" module.

**Comment by rendaw** [comment]
Thanks, default_checked_level was what I was looking for!

**Comment by manhhung741** [comment]
You can also configure the runtime check so that it doesn't run on production, or only do logging on production.

**Comment by SolaWing** [comment]
@DarkDimius Can WithoutRuntime support extend so that I can disable all runtime checks in the file at once, and it's more consistent with T::Sig. Now withoutRuntime must be written in full, which is tedious. In addition, Runtime has some performance loss and some bugs. I only want to enable it at the place where I want to check at runtime.
