### ISSUE TITLE
Make passing a block to method that doesn't accept a block an error in typed: strict

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#236]
https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bparams(s%3A%20String).void%7D%0Adef%20hello(s)%0A%20%20puts(s)%0Aend%0A%0Asig%20%7Bvoid%7D%0Adef%20main%0A%20%20hello('foo')%20do%0A%20%20%20%20puts('bar')%0A%20%20end%0Aend

**Comment by jez** [comment]
This was implemented at some point, but I don't remember which PR. The example in the issue correctly errors, as requested.
