### ISSUE TITLE
LSP: findMethodDocumentation should include docs that come before the `sig`

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#237]
<img width="797" alt="Screen Shot 2019-03-29 at 3 51 08 PM" src="https://user-images.githubusercontent.com/1084930/55266520-9f8e6180-523a-11e9-8e09-482114450d47.png">

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%0A%20%20%23%20kinda%20a%20doc%3F%0A%20%20sig%20%7Bparams(x%3A%20Integer).returns(String)%7D%0A%20%20%23%20DOC%0A%20%20%23%20%40deprecated%0A%20%20def%20bar(x)%0A%20%20%20%20x.to_s%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20A.new.barr(91)%20%20%20%23%20error%3A%20Typo!%0A%20%20A.new.bar(1)%20%20%23%20error%3A%20Type%20mismatch!%0A%20%20A.new.b%0Aend

**Comment by jvilk-stripe** [comment]
Fixed.
