### ISSUE TITLE
`alias` and `alias_method` unable to alias method from parent class

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#2378]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20TSortableHash%20%3C%20Hash%0A%20%20include%20TSort%0A%20%20alias_method%20%3Atsort_each_node%2C%20%3Aeach_key%0A%20%20def%20tsort_each_child(node%2C%20%26block)%0A%20%20%20%20fetch(node).each(%26block)%0A%20%20end%0Aend%0A%0Aclass%20TSortableHash_2%20%3C%20Hash%0A%20%20include%20TSort%0A%20%20alias%20tsort_each_node%20each_key%0A%20%20def%20tsort_each_child(node%2C%20%26block)%0A%20%20%20%20fetch(node).each(%26block)%0A%20%20end%0Aend%0A%0Aclass%20Hash%0A%20%20include%20TSort%0A%20%20alias%20tsort_each_node%20each_key%0A%20%20def%20tsort_each_child(node%2C%20%26block)%0A%20%20%20%20fetch(node).each(%26block)%0A%20%20end%0Aend%0A)

```ruby
# typed: true

class TSortableHash < Hash
  include TSort
  alias_method :tsort_each_node, :each_key
  def tsort_each_child(node, &block)
    fetch(node).each(&block)
  end
end

class TSortableHash_2 < Hash
  include TSort
  alias tsort_each_node each_key
  def tsort_each_child(node, &block)
    fetch(node).each(&block)
  end
end

class Hash
  include TSort
  alias tsort_each_node each_key
  def tsort_each_child(node, &block)
    fetch(node).each(&block)
  end
end
```

#### Observed output

```
editor.rb:5: Can't make method alias from tsort_each_node to non existing method each_key https://srb.help/5037
     5 |  alias_method :tsort_each_node, :each_key
                                         ^^^^^^^^^

editor.rb:13: Can't make method alias from tsort_each_node to non existing method each_key https://srb.help/5037
    13 |  alias tsort_each_node each_key
                                ^^^^^^^^
Errors: 2
```

#### Expected behavior

`alias` and `alias_method` shouldn't complain when I try to alias a method defined in the parent class (each_key is defined in Hash)
- - -

**Comment by jez** [comment]
This is intentional. See this previous closed PR where I implemented it for more context:

https://github.com/sorbet/sorbet/pull/1443

**Comment by jez** [comment]
I just thought of a workaround which i think is pretty agreeable:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20TSortableHash%20%3C%20Hash%0A%20%20include%20TSort%0A%20%20def%20each_key(%26blk)%3B%20super(%26blk)%3B%20end%0A%20%20alias_method%20%3Atsort_each_node%2C%20%3Aeach_key%0A%20%20def%20tsort_each_child(node%2C%20%26block)%0A%20%20%20%20fetch(node).each(%26block)%0A%20%20end%0Aend%0A%0Aclass%20TSortableHash_2%20%3C%20Hash%0A%20%20include%20TSort%0A%20%20def%20each_key(%26blk)%3B%20super(%26blk)%3B%20end%0A%20%20alias%20tsort_each_node%20each_key%0A%20%20def%20tsort_each_child(node%2C%20%26block)%0A%20%20%20%20fetch(node).each(%26block)%0A%20%20end%0Aend%0A%0Aclass%20Hash%0A%20%20include%20TSort%0A%20%20alias%20tsort_each_node%20each_key%0A%20%20def%20tsort_each_child(node%2C%20%26block)%0A%20%20%20%20fetch(node).each(%26block)%0A%20%20end%0Aend%0A)

```ruby
  # ...

  # Define an instance method that overrides the parent class and does nothing but call `super`
  def each_key(&blk); super(&blk); end

  # Now the alias_method / alias works:
  alias_method :tsort_each_node, :each_key

  # ...
```

**Comment by manhhung741** [comment]
Thanks @jez. That workaround seems reasonable to me too
