### ISSUE TITLE
Wrong signature for CSV.parse

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#2379]
#### Input

Sorbet thinks that CSV.parse always returns a nilable Array, following the signature defined here.

https://github.com/sorbet/sorbet/blob/master/rbi/stdlib/csv.rbi#L300

However, when given {headers: true} option, it should return CSV::Table

[→ View on sorbet.run](TODO_replace_this_with_your_sorbet_run_link)

```ruby
irb(main):024:0> CSV.parse("a,b\n1,2", {headers: true})
=> #<CSV::Table mode:col_or_row row_count:2>
irb(main):025:0> CSV.parse("a,b\n1,2")
=> [["a", "b"], ["1", "2"]]
```

#### Observed output

Sorbet thinks that CSV.parse always returns a nilable Array, following the signature defined here.

https://github.com/sorbet/sorbet/blob/master/rbi/stdlib/csv.rbi#L300

#### Expected behavior

When given {headers: true} option, it should return CSV::Table

- - -

**Comment by manhhung741** [comment]
I found the same problem apply to `CSV.foreach`. When `headers: true`, row can be a hash
```
CSV.foreach(path, headers: true) do |row| 
...
end
```
https://github.com/sorbet/sorbet/blob/master/rbi/stdlib/csv.rbi#L277

**Comment by manhhung741** [comment]
Also, CSV::Table is marked as Generic, but there is no run-time component added. When I try `CSV::Table[T.untyped]" it breaks at runtime.

```
undefined method `[]' for CSV::Table:Class
```

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong

**Comment by marianosimone** [comment]
Closing this a opening https://github.com/sorbet/sorbet/issues/3311 to deal with the remaining issue of the runtime not matching the static declaration.
