### ISSUE TITLE
Incorrect flow sensitivity behavior when inverting result of Module#<

### ISSUE THREAD

**Issue by neal-stripe** [sorbet/sorbet#2380]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20T.class_of(Integer)).void%7D%0A%20%20def%20foo(x)%0A%20%20%20%20T.reveal_type(x)%20unless%20x%20%3C%20Integer%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: T.class_of(Integer)).void}
  def foo(x)
    T.reveal_type(x) unless x < Integer
  end
end
```

#### Observed output

```
editor.rb:7: This code is unreachable https://srb.help/7006
     7 |    T.reveal_type(x) unless x < Integer
            ^
Errors: 1
```

#### Expected behavior

Revealed type should be `T.class_of(Integer)`, since the code is reachable if `x` is `Integer` (and not a subclass).

**Comment by jez** [comment]
Related but not the same: #1910
