### ISSUE TITLE
Incorrect signature for Range#step that rejects Float type

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#2387]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0ARange.new(0.5%2C%202.5).step(0.5))

```ruby
# typed: true
Range.new(0.5, 2.5).step(0.5)
```

#### Observed output

```
editor.rb:2: Expected Integer but found Float(0.500000) for argument n https://srb.help/7002
     2 |Range.new(0.5, 2.5).step(0.5)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/range.rbi#L501: Method Range#step (overload.1) has specified n as Integer
     501 |        n: Integer,
                  ^
  Got Float(0.500000) originating from:
    editor.rb:2:
     2 |Range.new(0.5, 2.5).step(0.5)
                                 ^^^
Errors: 1
```

#### Expected behavior
Sorbet shouldn't complain the use of float in Range.new and Range.step
```
irb(main):015:0> Range.new(0.5, 2.5)
=> 0.5..2.5
irb(main):016:0> Range.new(0.5, 2.5).step(0.5)
=> #<Enumerator: 0.5..2.5:step(0.5)>
irb(main):017:0> Range.new(0.5, 2.5).step(0.5).to_a
=> [0.5, 1.0, 1.5, 2.0, 2.5]
```
- - -
The signature is defined here that `step` takes in an Integer input, but it can takes float input as well
https://github.com/sorbet/sorbet/blob/6c8cd4fa41fafa395285bd7676e02dd8cd5914ed/rbi/core/range.rbi#501,9

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
