### ISSUE TITLE
F#-style type providers

### ISSUE THREAD

**Issue by atty-stripe** [sorbet/sorbet#2397]
### Problem

When querying a database from Ruby, I would like to write SQL or GraphQL directly in my code (rather than use an ORM, for example). While this is great because it lets me use the full power of the database, it can result in runtime errors due to misformatted queries, missing references, etc. 

Further, the result of a successful query is typically `T.untyped`, and requires runtime deserialization and checks to go from the raw response to typed data structures.

### Proposed solution

It would be great if Sorbet could provide static typechecking when writing the query as well as types for the result of the query. Assuming we have access to a static database schema when writing the code and running it, we could automatically check query strings and show errors when the query does not typecheck (for example, the table name is misspelled, or a join operation is being performed on incompatible columns). We could also infer the types of the result, since we know the exact fields or aggregations being returned.

This has been implemented in F# via [type providers](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/). 

A good example is the SQL provider here: https://github.com/rspeele/Rezoom.SQL. The README includes a GIF of the desired behavior. 

More examples are listed here: https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/#commonly-used-type-providers.

A similar request was raised for TypeScript: https://github.com/microsoft/TypeScript/issues/3136.

I know very little about type systems, so can't comment on whether this is the right approach or not. However, the desired behavior would definitely improve my productivity quite a bit!

**Comment by jez** [comment]
Thanks for the idea. F#'s type providers are pretty cool.

The way we suggest implementing something similar is using code generation to create RBI files with more specific types.
