### ISSUE TITLE
editor support (again)

### ISSUE THREAD

**Issue by modosc** [sorbet/sorbet#2434]
(see also #1013)

### Problem

just chiming in again on editor support - it's been > 6 months since the last update, is this still planned or something that could use help? without this adoption is difficult.

**Comment by jez** [comment]
It's great to know you're looking forward to this! It's the foremost thing we're working on.

There are currently many rough edges with LSP support, and we're actively prioritizing addressing them so we can open source.

We talked a little bit about our plans most recently in our talk at RubyConf back in November:

https://youtu.be/jielBIZ40mw

Thanks again! We hope to have things in your hands soon.

**Comment by DarkDimius** [comment]
If you're looking to help, the following issues could be a good start
https://github.com/sorbet/sorbet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+label%3A%22ide%22+
