### ISSUE TITLE
Incorrect autocorrect when using += - causes invalid syntax

### ISSUE THREAD

**Issue by ghiculescu** [sorbet/sorbet#2490]
`srb tc -a` inserts invalid syntax, in a case where you're using `+=` (or `-=` etc) on something that is nilable.

Code like `self.foo += 1` is replaced with code like `T.must(self.foo) += 1`, which is invalid ruby.

The correct solution in this case is to write `self.foo = T.must(self.foo) + 1`. I don't expect sorbet to do that, but it would be good if it didn't autocorrect in cases that would create a syntax error.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20BEFORE%0A%23%20typed%3A%20true%0Arequire%20'sorbet-runtime'%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%201%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T.nilable(Integer)%20)%7D%0A%20%20attr_accessor%20%3Afoo%0A%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20main%0A%20%20%20%20self.foo%20%2B%3D%201%0A%20%20end%0Aend%0A%0Aa%20%3D%20A.new%0Aa.main%0Aputs%20a.foo%0A)

```ruby
# test1.rb
# BEFORE
# typed: true
require 'sorbet-runtime'
class A
  extend T::Sig

  def initialize
    @foo = 1
  end

  sig { returns(T.nilable(Integer) )}
  attr_accessor :foo

  sig { void }
  def main
    self.foo += 1
  end
end

a = A.new
a.main
puts a.foo
```

#### Observed output

```
test1.rb:15: Method + does not exist on NilClass component of T.nilable(Integer) https://srb.help/7003
    15 |    self.foo += 1
            ^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    test1.rb:15: Replace with T.must(self.foo)
    15 |    self.foo += 1
            ^^^^^^^^
```

#### Expected behavior

If you run `srb tc -a`, or make the change instructed, you get a program with invalid syntax. See [sorbet.run](https://sorbet.run/#%23%20AFTER%0A%23%20typed%3A%20true%0Arequire%20'sorbet-runtime'%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%201%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T.nilable(Integer)%20)%7D%0A%20%20attr_accessor%20%3Afoo%0A%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20main%0A%20%20%20%20T.must(self.foo)%20%2B%3D%201%0A%20%20end%0Aend%0A%0Aa%20%3D%20A.new%0Aa.main%0Aputs%20a.foo%0A)

Differences between the two files:

![image](https://user-images.githubusercontent.com/509837/72454143-efb4c100-3785-11ea-956a-b3ca1127d132.png)

**Comment by DarkDimius** [comment]
We don't expect autocorrects to be perfect, they are expected to be reviewed by users. That said, patches to improve them are welcome.
