### ISSUE TITLE
In instance_exec block, self type should be the receiver

### ISSUE THREAD

**Issue by SolaWing** [sorbet/sorbet#2497]
#### Input

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: Integer).returns(String)}
  def bar(x)
    x.to_s
  end
end

def main
  A.instance_exec do |v|
    T.reveal_type(self) # untyped
  end
end
```

#### Expected behavior

instance_exec block's self should be the receiver's type

**Comment by DarkDimius** [comment]
1. In our experience typing highly generic metaprogrammig code isn't worth it: it makes a lot of assumptions that aren't expressible in a user-friendly type system. And thus errors have low signal to noise ratio
2. We don't keep bugs open about specific methods, if you want to add a Sig to it,please open a pull request. Note that Stripe, Shopify and few others may need to verify how does it behave in practice in those codebase before merging(or after and revert if weren't diligent enough).

**Comment by SolaWing** [comment]
@DarkDimius currently sig seems not support specify a type for block self with receiver type？

I tried use T.self_type，but it can only be return type
