### ISSUE TITLE
Support literal types

### ISSUE THREAD

**Issue by LandonSchropp** [sorbet/sorbet#2504]
Please let me know if I'm missing something here. Thanks!

### Problem

I'd like to define a method that takes one of a few possible constant values. For example:

``` ruby
class Fruit
  extend T::Sig

  BANANA = T.let("banana", String)
  APPLE = T.let("apple", String)

  sig { params(value: T.any(BANANA, APPLE)).returns(T::Boolean) }
  def self.banana?(value)
    value == BANANA
  end
end
```

I'd expect to be able to do this:

``` ruby
Fruit.banana?("banana")
```

But not this:

``` ruby
Fruit.banana?("monster truck")
```

I *could* use an enum. But in my real example, I'm already using these string values in other places. They can be returned from my model attributes and can be provided as params from a user. I don't want to have to convert these values every time I interact with them.

### Proposed solution

My suggestion would be for Sorbet to support literal values in type declarations.

**Comment by LandonSchropp** [comment]
CC @optijon

**Comment by LandonSchropp** [comment]
To help clarify our intent, we're not using the static type checking features of Sorbet. We're only using the dynamic features.

**Comment by jez** [comment]
You can use `T::Enum` for this purpose:

```ruby
# typed: true
class Fruit < T::Enum
  extend T::Sig

  enums do
    BANANA = new("banana")
    APPLE = new("apple")
  end
  
  sig { params(value: T.any(BANANA, APPLE)).returns(T::Boolean) }
  # alternatively:
  # sig { params(value: Fruit).returns(T::Boolean) }
  def self.banana?(value)
    value == BANANA
  end
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Fruit%20%3C%20T%3A%3AEnum%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20enums%20do%0A%20%20%20%20BANANA%20%3D%20new(%22banana%22)%0A%20%20%20%20APPLE%20%3D%20new(%22apple%22)%0A%20%20end%0A%20%20%0A%20%20sig%20%7B%20params(value%3A%20T.any(BANANA%2C%20APPLE)).returns(T%3A%3ABoolean)%20%7D%0A%20%20%23%20alternatively%3A%0A%20%20%23%20sig%20%7B%20params(value%3A%20Fruit).returns(T%3A%3ABoolean)%20%7D%0A%20%20def%20self.banana%3F(value)%0A%20%20%20%20value%20%3D%3D%20BANANA%0A%20%20end%0Aend)

Docs: https://sorbet.org/docs/tenum

**Comment by LandonSchropp** [comment]
@jez I commented above that while I could use `T::Enum`, I'd rather not. I personally don't like the wrapper objects provided by Sorbet, and I think Sorbet should support literals explicitly.

**Comment by thegorgon** [comment]
I'd like to express support for this as well. Literal types are incredibly useful, especially given the way symbols and strings are used in ruby.
