### ISSUE TITLE
recursive lambda capture infer to NilClass

### ISSUE THREAD

**Issue by SolaWing** [sorbet/sorbet#2511]
#### Input

```ruby
  recursive = lambda do 
    recursive[] # here recursive is NilClass
  end
```

#### Expected behavior

infer the right type for recursive lambda

**Comment by jez** [comment]
This is due to a fundamental limitation in sorbet's type inference, and thus is unlikely to change. You will need to pre-declare your lambda's type:

```ruby
  recursive = T.let(-> {}, T.proc.void)
  recursive = lambda do 
    recursive[] # here recursive is NilClass
  end
```

**Comment by smackesey** [comment]
Please add  a note on this to the [Blocks, Procs, and Lambdas](https://sorbet.org/docs/procs) docs page.
