### ISSUE TITLE
Support repos larger than 64K files

### ISSUE THREAD

**Issue by mkillianey-stripe** [sorbet/sorbet#2526]
### Problem

As of 2020-Jan-22, the limit on `FileRef::id()` is 64K:
https://github.com/sorbet/sorbet/blob/36d8ec0009e7efe0123b8dc3a6541ca6147695e6/core/Files.h#L42

This is problematic for repos larger than 64K (Ruby) files.

### Proposed solution

To support more than 64K files, Sorbet should use a larger type (presumably `u4`).

**Comment by jez** [comment]
We did this. Fake internet points to the person who gets Sorbet to overflow the new size in a real codebase

https://github.com/sorbet/sorbet/pull/2791
