### ISSUE TITLE
Unable to annotation a lambda’s self type

### ISSUE THREAD

**Issue by SolaWing** [sorbet/sorbet#2534]
### Problem

when create a lambda for later use, currently no way to annotate the self and parma type directly.
have to create a dummy function with block annotation and return it.

### Proposed solution
`T.let lamba {} T.proc ` can infer the lambda self and parma type. also have runtime check too

**Comment by paracycle** [comment]
Seems to work fine already: https://sorbet.run/#%23%20typed%3A%20true%0A%0Acallback%20%3D%20T.let(%0A%20%20lambda%20%7B%20%7Ca%2Cb%7C%20puts%20%22Hello%22%7D%2C%20%0A%20%20T.proc.params(a%3A%20Integer%2C%20b%3A%20String).void%0A)%0A%0Acallback.call(1%2C%202)%20%23%20Expected%20String%20but%20found%20Integer(2)%20for%20argument%20arg1%20

**Comment by SolaWing** [comment]
> Seems to work fine already: https://sorbet.run/#%23%20typed%3A%20true%0A%0Acallback%20%3D%20T.let(%0A%20%20lambda%20%7B%20%7Ca%2Cb%7C%20puts%20%22Hello%22%7D%2C%20%0A%20%20T.proc.params(a%3A%20Integer%2C%20b%3A%20String).void%0A)%0A%0Acallback.call(1%2C%202)%20%23%20Expected%20String%20but%20found%20Integer(2)%20for%20argument%20arg1%20

call validation is ok， but the lambda body’s self type can’t change, and parma type is untyped

**Comment by SolaWing** [comment]
here is a demo:

https://sorbet.run/ace/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20def%20hello%3B%20end%0Aend%0Acallback%20%3D%20T.let(%0A%20%20lambda%20%7B%20%7Ca%2Cb%7C%20%0A%20%20%20%20hello%0A%20%20%20%20T.reveal_type%20a%0A%20%20%20%20T.reveal_type%20b%0A%20%20%20%20T.reveal_type%20self%0A%20%20%7D%2C%20%0A%20%20T.proc.bind(A).params(a%3A%20Integer%2C%20b%3A%20String).void%0A)%0A%0AA.new.instance_exec(%5B1%2C%202%5D%2C%20%26callback)%0Acallback.call(1%2C%202)%20%23%20Expected%20String%20but%20found%20Integer(2)%20for%20argument%20arg1%20

**Comment by SolaWing** [comment]
find a way to annotation the lambda by define a dummy method, and annotate it's blk. then the pass in block can be infered. but the dummy method is uggly

**Comment by jez** [comment]
Thanks for the report. Sorbet's support for `instance_exec` and `instance_eval` is best effort; we don't have plans to improve it soon.
