### ISSUE TITLE
Instrumentation of hidden-definitions generator

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#2540]
### Problem

hidden-definitions is taking at least 5 minutes on my medium-sized Rails app, and some other people in Slack have reported 40-45 minute generations for their large apps. Right now, it's essentially a black box and we don't have any insight into what's causing these to take so long.

For example, I have some seeders that fill the database with randomly-generated records for games, users, etc. By default, it gets user profile pictures from an external source but it's been acting up lately and the requests to the profile picture generation site take ~2 minutes to timeout. This causes the generation task to get stuck on my users seeder for a while, and I had a bit of trouble figuring out the source of that problem without instrumentation. (Thankfully I figured it out because the `srb rbi update` command prints the files it runs - only sometimes, though? - so I noticed it had gotten stuck for a while on `db/seeds/users.rb`).

The point is, I'd like to know how much time is being spent running each file in my project and dependencies, and then how long the resolver is taking to generate the hidden-definitions.rbi file, and anything else is generates.

### Proposed solution

I'd like to have some means of getting instrumentation data out of the hidden definitions generator (and the sorbet rbi init/update process in general), that'd tell the user where time is being spent (e.g. it took 30 seconds to run the file in `vendor/bundler/foo/bar/baz.rb`, etc.).

From dmitriy in Slack:
> we manually add prints with timing to it, but we never commited it. We'll be happy to merge a pr with some kind of tracing
>
> web-trace-file is what we use

**Comment by modosc** [comment]
just wanted to chime in here and say we're seeing this too. we have a large rails 5.2 app that takes 5-10 minutes to finish `srb rbi hidden-definitions`. i'm in the process of upgrading to rails 6, and on that branch `srb rbi hidden-definitions` doesn't ever seem to finish. i have no idea how or why this is, so having some output would be super useful.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
