### ISSUE TITLE
ENV#filter is incorrectly typed as an `Array` instead of a `Hash`

### ISSUE THREAD

**Issue by sushain97** [sorbet/sorbet#2547]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0AT.reveal_type(ENV.filter%20%7B%7C%7C%20true%7D)%0A)

```ruby
# typed: true

T.reveal_type(ENV.filter {|| true})
```

#### Observed output

```
editor.rb:3: Revealed type: T::Array[[String, T.nilable(String)]] https://srb.help/7014
     3 |T.reveal_type(ENV.filter {|| true})
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:3:
     3 |T.reveal_type(ENV.filter {|| true})
                      ^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

It should be a `Hash`:

```
[dev] main:0> ENV.filter {|| true}.class
=> Hash
```

This is probably the issue: https://github.com/sorbet/sorbet/blob/master/rbi/sorbet/sorbet.rbi#L70

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
