### ISSUE TITLE
LSP: usage of key-value store should save half of startup time

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#255]
Cold start in LSP mode on pay-server currently takes ~28 seconds.
 - 7 seconds are spent in `index`[1]
 - 1.6 seconds in namer
 - 2.7 seconds in resolver
 - 6.5 seconds in infer
 - 8 seconds are spent computing state hashes for files.[2]
 - 1.2 seconds not covered by timers(copying global state?)

KV store can be used to speed up both [1] [2], and most of the code that for this is already implemented. [1] is cached in KV-store in non-LSP mode, state hashes for [2] are burned into payload, but not into kv-store.  

Extending kv-store usage to this should allow IDE to start faster.
@jvilk-stripe , it's not clear for how to prioritize this. This would only matter in case of crashes / restarts / bad connections to wifi. Thus I'm just dropping this idea to you so that you know that there are pretty easy wins available here if we need them.

**Comment by jez** [comment]
Implemented in #2762.
