### ISSUE TITLE
`srb rbi gems` flags gems in rvm as jruby

### ISSUE THREAD

**Issue by bubaflub** [sorbet/sorbet#2558]
#### Input

Running `srb rbi gems` in my Rails app at work.  We're using `rvm` and `bundler`.

#### Observed output

`srb rbi gems` throws a few warnings about Gems that can't be loaded but it eventually completes without an error.

#### Expected behavior

I expected there to be a new folder `sorbet/rbi/gems` and files in that folder for each gem it could successfully load and parse.

----

After stepping through in a debugger I found that Gems that were handled by RVM were matching this regular expression:

https://github.com/sorbet/sorbet/blob/b4b405a5e4576bb9980c4400d037ccca6fd22dee/gems/sorbet/lib/gem-generator-tracepoint/tracepoint_serializer.rb#L219

And so were being flagged as being part of the jruby standard library and thus none of my gems were written out to disk.

When I step through the loop that calls `gem_from_location` I see locations like:

```
"/Users/bob/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/x86_64-darwin18/io/nonblock.bundle"
```

Which are correctly matching the Ruby standard library regular expression.

But after getting through all of the standard library I see locations like

```
"/Users/bob/.rvm/gems/ruby-2.4.9/gems/activesupport-4.2.11.1/lib/active_support/core_ext/array/prepend_and_append.rb"
```

This is matching against jRuby and short-circuiting:

```
(byebug) location
"/Users/bob/.rvm/gems/ruby-2.4.9/gems/activesupport-4.2.11.1/lib/active_support/core_ext/array/prepend_and_append.rb"
(byebug) location&.match(/^.*\/(j?ruby)-([\d.]+)\//)
#<MatchData "/Users/bob/.rvm/gems/ruby-2.4.9/" 1:"ruby" 2:"2.4.9">
```

It would match against the last regular expression:

```
(byebug) location&.match(/^.*\/gems\/(?:ruby-)?[\d.]+(?:@[^\/]+)?(?:\/bundler)?\/gems\/([^\/]+)-([^-\/]+)\//i)
#<MatchData "/Users/bob/.rvm/gems/ruby-2.4.9/gems/activesupport-4.2.11.1/" 1:"activesupport" 2:"4.2.11.1">
```

But we've short-circuited before we get there.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
