### ISSUE TITLE
Support Bundler/Gemfile "require as"

### ISSUE THREAD

**Issue by bubaflub** [sorbet/sorbet#2563]
#### Input

In our Gemfile we have this line:

```
gem 'sprockets-rails', '~> 3.0', :require => 'sprockets/railtie'
```

According to https://bundler.io/man/gemfile.5.html#REQUIRE-AS

> Require As
> 
> Each gem MAY specify files that should be used when autorequiring via Bundler.require. You may pass an array with multiple files or true if file you want required has same name as gem or false to prevent any file from being autorequired.

In this example the Gem is called `'sprockets-rails'` but we don't `require 'sprocket-rails'` but rather `require 'sprockets/railtie'`.  Another example is the `yajl-ruby` Gem which should be loaded as `require 'yajl'` and not as `require 'yajl-ruby'`.

#### Observed output

We get errors like

```
LoadError: cannot load such file -- archive-zip
LoadError: cannot load such file -- aws-sdk
...
LoadError: cannot load such file -- sprockets-rails
```

from

 https://github.com/sorbet/sorbet/blob/e2afb16e14f5931e9a7f1f214a1b65e86eb71918/gems/sorbet/lib/gem_loader.rb#L570

and more specifically

https://github.com/sorbet/sorbet/blob/e2afb16e14f5931e9a7f1f214a1b65e86eb71918/gems/sorbet/lib/gem_loader.rb#L587

#### Expected behavior

I think we can avoid these LoadErrors if we require the supplied name or names in the Gemfile.

- - -

In #1104 we skip Gems that are marked `require: false` since those are not auto-loaded at all.  Many of our test dependencies (e.g. `rubocop`, `simplecov`) are marked as `required: false` so we only load them explicitly and as we need them.

Something that I don't fully understand: when we've executed https://github.com/sorbet/sorbet/blob/e2afb16e14f5931e9a7f1f214a1b65e86eb71918/gems/sorbet/lib/gem_loader.rb#L574

The `deps` array contains `autorequire` information.  For example, from my setup:

```
(byebug) deps[12]
<Bundler::Dependency type=:runtime name="sprockets-rails" requirements="~> 3.0">
(byebug) deps[12].autorequire
["sprockets/railtie"]
```

But by the time we reach https://github.com/sorbet/sorbet/blob/e2afb16e14f5931e9a7f1f214a1b65e86eb71918/gems/sorbet/lib/gem_loader.rb#L585 where we do the `require` that `autorequire` information is gone:

```
(byebug) l =

[580, 589] in /Users/bob/.rvm/gems/ruby-2.4.9/gems/sorbet-0.4.4794/lib/gem_loader.rb
   580:     specs.sort_by(&:name).each do |gemspec|
   581:       begin
   582:         require_gem(gemspec.name)
   583:       rescue LoadError => e
   584:         byebug
=> 585:         puts "LoadError: #{e}"
   586:       rescue NameError => e
   587:         puts "NameError: #{e}"
   588:       end
   589:     end
(byebug) gemspec.name
"sprockets-rails"
(byebug) gemspec.autorequire
nil
```

Full gemspec below:
```
(byebug) gemspec
#<Gem::Specification:0x00007fc85c5b70d0 @extension_dir=nil, @full_gem_path=nil, gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir=nil, @base_dir=nil, @loaded=false, activated=false, @loaded_from="/Users/bob/.rvm/gems/ruby-2.4.9/specifications/sprockets-rails-3.2.1.gemspec", @original_platform=nil, @installed_by_version=#<Gem::Version "2.7.10">, autorequire=nil, @description=nil, @email="josh@joshpeek.com", homepage="https://github.com/rails/sprockets-rails", @name="sprockets-rails", post_install_message=nil, @rubyforge_project=nil, @signing_key=nil, @summary="Sprockets Rails integration", @version=#<Gem::Version "3.2.1">, @authors=["Joshua Peek"], bindir="bin", @cert_chain=[], @date=2017-08-31 00:00:00 UTC, @dependencies=[<Gem::Dependency type=:runtime name="sprockets" requirements=">= 3.0.0">, <Gem::Dependency type=:runtime name="actionpack" requirements=">= 4.0">, <Gem::Dependency type=:runtime name="activesupport" requirements=">= 4.0">, <Gem::Dependency type=:development name="railties" requirements=">= 4.0">, <Gem::Dependency type=:development name="rake" requirements=">= 0">, <Gem::Dependency type=:development name="sass" requirements=">= 0">, <Gem::Dependency type=:development name="uglifier" requirements=">= 0">], @executables=[], @extensions=[], @extra_rdoc_files=[], @files=[], licenses=["MIT"], @metadata={}, @platform="ruby", @rdoc_options=[], @require_paths=["lib"], required_ruby_version=#<Gem::Requirement:0x00007fc85c5b52a8 @requirements=[[">=", #<Gem::Version "1.9.3">]]>, @required_rubygems_version=#<Gem::Requirement:0x00007fc85c5b6018 @requirements=[[">=", #<Gem::Version "0">]]>, requirements=[], @rubygems_version="2.7.10", @specification_version=4, @test_files=[], new_platform="ruby", @full_name="sprockets-rails-3.2.1", @source=#<Bundler::Source::Rubygems:0x70249139788600 rubygems repository https://rails-assets.org/, https://rubygems.org/ or installed locally> sprockets-rails-3.2.1>
```

**Comment by DarkDimius** [comment]
Stripe doesn't use this, so we won't be able to prioritize this.
Contributions are very welcome

**Comment by bubaflub** [comment]
I'm happy to help with this but will need some pointers.  Are there existing `srb rbi gems` tests I could look at?

> Stripe doesn't use this

Oh, that's news to me.  Does Stripe use something else (like https://github.com/Shopify/tapioca)?  Or is it that this is just used for bootstraping or getting started and you no longer need it?

**Comment by jez** [comment]
I believe dmitry meant that Stripe doesn't use `require: ...` so we'd have no intrinsic motivation to implement it.

**Comment by paracycle** [comment]
> ... Does Stripe use something else (like [Shopify/tapioca](https://github.com/Shopify/tapioca))? ...

Did you try `tapioca`? It should be doing the right thing out of the box. Let us know on the repo if you are having problems with `tapioca` for some reason.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
