### ISSUE TITLE
Date.new returns T.untyped

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#2574]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adate%20%3D%20Date.new%0AT.reveal_type(date))

```ruby
# typed: true

date = Date.new
T.reveal_type(date) # Got `T.untyped`, expected `Date`
```

#### Observed output

```
editor.rb:4: Revealed type: T.untyped https://srb.help/7014
     4 |T.reveal_type(date)
        ^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:3:
     3 |date = Date.new
               ^^^^^^^^
Errors: 1
```

#### Expected behavior

I was expecting the type to be `Date`.

**Comment by elliottt** [comment]
It looks like there's a signature for `Date.new`. I think it would be good to replace this with a signature for `Date#initialize`.

**Comment by ghiculescu** [comment]
Would the solution be to change https://github.com/sorbet/sorbet/blob/master/rbi/stdlib/date.rbi#L926 to `returns(Date)`?

**Comment by ghiculescu** [comment]
i can do this ^

**Comment by elliottt** [comment]
I think we should just remove the sig for `self.new` completely.
