### ISSUE TITLE
Initialize sorbet in rails project causes an error

### ISSUE THREAD

**Issue by rafaelcgs10** [sorbet/sorbet#2583]
**Describe the bug:**
This problem is related to using Sobert in a Ruby on Rails 6 project!
I opened an [issue](https://github.com/chanzuckerberg/sorbet-rails/issues/264) in the Sorbet-Rails repo, but perhaps this repo is more appropriated.
The first step of the Sorbet-Rails **[Initial Setup](https://github.com/chanzuckerberg/sorbet-rails#initial-setup)** requires to run the basic [Sorbet initialization](https://sorbet.org/docs/adopting). But following it doesn't conclude well.

**Steps to reproduce:**

1. run:` rails new app`

2. add to the Gemfile:

```
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
```
3. run: `bundle install`

4. Do the **[Verify installation](https://sorbet.org/docs/adopting#verify-initialization)**
~ No problems until here.

5. run: `srb init`
This step gives an error:
```
/usr/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5316/lib/hidden-definition-finder.rb:149:in `write_constants': /tmp/d20200131-18296-1s6k0uv/reflection.rbi had unexpected errors.
```
More data:
[Full output](https://gist.github.com/rafaelcgs10/4c8c71edf546e48e299be985a6c82dce)
[reflection.json.err](https://gist.github.com/rafaelcgs10/3eb78ae8d1e81c6c68b08bb764b2a698)

**Expected behavior:**
The last step should complete and initialize the folder sorbet/, but it stops with an error.

**Versions:**

- Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
- Rails: Rails 6.0.2.1
- Sorbet: Sorbet typechecker 0.5.5316 git 84b84770d0646e3e313f83d2785e547c41e6cefd-dirty built on 2020-01-31 06:27:04 GMT debug_symbols=true

I'm not using rvm, I'm using Ruby from Arch Linux repo.

**Comment by elliottt** [comment]
Thanks for the bug report!

We haven't tested with ruby-2.7, is it possible for you to run with ruby-2.6 instead?

**Comment by rafaelcgs10** [comment]
@elliottt  With ruby-2.6 the process ends fine. It seems this is an issue with ruby-2.7!

**Comment by elliottt** [comment]
Glad to hear that it's working, it sounds like we will have some work to do once we start work on 2.7 support!
