### ISSUE TITLE
Ruby 2.7: Keyword parameters deprecation warning

### ISSUE THREAD

**Issue by HashNotAdam** [sorbet/sorbet#2625]
Ruby 2.7 includes deprecation warning to help with future compatibility with Ruby 3.0.

These warnings seem to be occurring when a method that has a Sorbet signature calls another method with a Sorbet signature.

```
sorbet-runtime-0.5.5357/lib/types/private/methods/call_validation.rb:126: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Given that the docs show that 2.7 is not currently supported, this isn't really a bug but something that will need to be addressed before 2.7 can be added to the support list.

**Comment by connorshea** [comment]
FYI, this is a duplicate of #2388

**Comment by HashNotAdam** [comment]
@connorshea very true, although the title on this one is far more searchable 😄
