### ISSUE TITLE
Exception with code that previously worked

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#2627]
#### Input

An exception occurs with code in sorbet-typed that previously worked perfectly fine.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20GraphQL%3A%3ASchema%3A%3AMember%3A%3AHasFields%0A%20%20def%20field(*args%2C%20**kwargs%2C%20%26block)%3B%20end%0Aend%0A%0Amodule%20GraphQL%3A%3ASchema%3A%3AMember%3A%3AHasArguments%0A%20%20def%20argument(*args%2C%20**kwargs%2C%20%26block)%3B%20end%0Aend%0A%0Aclass%20GraphQL%3A%3ASchema%3A%3AObject%20%3C%20GraphQL%3A%3ASchema%3A%3AMember%0A%20%20extend%20GraphQL%3A%3ASchema%3A%3AMember%3A%3AHasFields%0A%0A%20%20%23%20srb%20rbi%20gems%20does%20*not*%20add%20the%20next%20line%2C%20which%20means%20arguments%20don't%20work%20out%20of%20the%20box%0A%20%20%23%20Note%20this%20isn't%20strictly%20correct.%20see%20https%3A%2F%2Fgithub.com%2Fsorbet%2Fsorbet-typed%2Fpull%2F166%0A%20%20extend%20GraphQL%3A%3ASchema%3A%3AMember%3A%3AHasArguments%0Aend%0A%0Aclass%20GraphQL%3A%3ASchema%3A%3AEnum%20%3C%20GraphQL%3A%3ASchema%3A%3AMember%0A%20%20%23%20Define%20a%20value%20for%20this%20enum%0A%20%20%23%0A%20%20%23%20_%40param_%20%60graphql_name%60%20-%20the%20GraphQL%20value%20for%20this%2C%20usually%20%60SCREAMING_CASE%60%0A%20%20%23%0A%20%20%23%20_%40param_%20%60description%60%20-%20the%20GraphQL%20description%20for%20this%20value%2C%20present%20in%20documentation%0A%20%20%23%0A%20%20%23%20_%40param_%20%60value%60%20-%20%2C%20the%20translated%20Ruby%20value%20for%20this%20object%20(defaults%20to%20%60graphql_name%60)%0A%20%20%23%0A%20%20%23%20_%40param_%20%60deprecation_reason%60%20-%20if%20this%20object%20is%20deprecated%2C%20include%20a%20message%20here%0A%20%20%23%0A%20%20%23%20_%40see_%20%60%7BSchema%3A%3AEnumValue%7D%60%20%E2%80%94%20which%20handles%20these%20inputs%20by%20default%0A%20%20sig%20%7B%20params(graphql_name%3A%20T.any(String%2C%20Symbol)%2C%20value%3A%20Object%2C%20description%3A%20String%2C%20deprecation_reason%3A%20String%2C%20block%3A%20T.untyped).void%20%7D%0A%20%20def%20self.value(graphql_name%2C%20value%3A%20nil%2C%20description%3A%20nil%2C%20deprecation_reason%3A%20nil%2C%20%26block)%3B%20end%0Aend%0A%0Amodule%20GraphqlTest%0A%20%20class%20User%20%3C%20GraphQL%3A%3ASchema%3A%3AObject%0A%20%20end%0A%0A%20%20class%20Query%20%3C%20GraphQL%3A%3ASchema%3A%3AObject%0A%20%20%20%20field%20%3Auser%2C%20User%2C%20%22The%20current%20user%22%2C%20null%3A%20true%20do%0A%20%20%20%20%20%20argument%20%3Aid%2C%20ID%2C%20%22The%20ID%20of%20the%20user%20to%20find%22%2C%20required%3A%20true%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20class%20CardinalDirectionType%20%3C%20GraphQL%3A%3ASchema%3A%3AEnum%0A%20%20%20%20value%20%22NORTH%22%2C%20value%3A%20'north'%0A%20%20%20%20value%20%22EAST%22%2C%20value%3A%20'east'%2C%20description%3A%20%22Lorem%20ipsum%22%0A%20%20%20%20value%20%22SOUTH%22%2C%20value%3A%20'south'%2C%20deprecation_reason%3A%20%22We%20just%20don't%20like%20south%20that%20much.%22%0A%20%20%20%20value%20%22WEST%22%2C%20value%3A%20'west'%0A%20%20%20%20value%20%22THE_SECRET_DIRECTION%22%20%23%20no%20value%0A%20%20end%0Aend%0A)

You'll see that Sorbet freaks out when it runs this. I think it might be because the file defines `GraphQL::Schema::Member::HasFields` without defining the ancestors, `GraphQL`, `GraphQL::Schema`, etc.

```ruby
# typed: true

module GraphQL::Schema::Member::HasFields
  def field(*args, **kwargs, &block); end
end

module GraphQL::Schema::Member::HasArguments
  def argument(*args, **kwargs, &block); end
end

class GraphQL::Schema::Object < GraphQL::Schema::Member
  extend GraphQL::Schema::Member::HasFields

  # srb rbi gems does *not* add the next line, which means arguments don't work out of the box
  # Note this isn't strictly correct. see https://github.com/sorbet/sorbet-typed/pull/166
  extend GraphQL::Schema::Member::HasArguments
end

class GraphQL::Schema::Enum < GraphQL::Schema::Member
  # Define a value for this enum
  #
  # _@param_ `graphql_name` - the GraphQL value for this, usually `SCREAMING_CASE`
  #
  # _@param_ `description` - the GraphQL description for this value, present in documentation
  #
  # _@param_ `value` - , the translated Ruby value for this object (defaults to `graphql_name`)
  #
  # _@param_ `deprecation_reason` - if this object is deprecated, include a message here
  #
  # _@see_ `{Schema::EnumValue}` — which handles these inputs by default
  sig { params(graphql_name: T.any(String, Symbol), value: Object, description: String, deprecation_reason: String, block: T.untyped).void }
  def self.value(graphql_name, value: nil, description: nil, deprecation_reason: nil, &block); end
end

module GraphqlTest
  class User < GraphQL::Schema::Object
  end

  class Query < GraphQL::Schema::Object
    field :user, User, "The current user", null: true do
      argument :id, ID, "The ID of the user to find", required: true
    end
  end

  class CardinalDirectionType < GraphQL::Schema::Enum
    value "NORTH", value: 'north'
    value "EAST", value: 'east', description: "Lorem ipsum"
    value "SOUTH", value: 'south', deprecation_reason: "We just don't like south that much."
    value "WEST", value: 'west'
    value "THE_SECRET_DIRECTION" # no value
  end
end
```

#### Observed output

```
Loading...
```

```
$ ruby .ci/run.rb

testing graphql all

Exception::raise(): Should never happen

Backtrace:

  #3 0x938382 sorbet::resolver::(anonymous namespace)::ResolveConstantsWalk::resolveConstants()::{lambda()#1}::operator()()

  #4 0x91e6fb sorbet::resolver::(anonymous namespace)::ResolveConstantsWalk::resolveConstants()

  #5 0x91ba63 sorbet::resolver::Resolver::run()

  #6 0x6a4885 sorbet::realmain::pipeline::resolve()

  #7 0x4ada0e sorbet::realmain::realmain()

  #8 0x4a814b main

  #9 0x7fd557c75830 __libc_start_main

  #10 0x46502a _start

/home/travis/.rvm/gems/ruby-2.5.7/gems/sorbet-0.5.5358/bin/srb: line 46:  6033 Segmentation fault      (core dumped) "${sorbet}" "${args[@]}"
```

#### Expected behavior

It wouldn't throw an exception.

- - -

I noticed this when I opened https://github.com/sorbet/sorbet-typed/pull/206 and CI failed, see [the log here](https://travis-ci.org/sorbet/sorbet-typed/builds/648129736#L219)

You can reproduce it like this:

- Clone `https://github.com/sorbet/sorbet-typed`
- Run `gem install sorbet`
- Run `ruby .ci/run.rb`

It happens with Sorbet 0.5.5358 and Ruby 2.5/2.6, probably other Ruby versions as well.

**Comment by connorshea** [comment]
Simpler piece of code that causes the issue:

```ruby
# typed: true

module GraphQL::Schema::Member::HasFields
  def field(*args, **kwargs, &block); end
end

class GraphQL::Schema::Object < GraphQL::Schema::Member
  extend GraphQL::Schema::Member::HasFields
end

module GraphqlTest
  class Query < GraphQL::Schema::Object
    field :user, User, "The current user", null: true
  end
end
```

**Comment by connorshea** [comment]
Simpler bit of code that'll do it:
```ruby
# typed: true
module Foo::Bar::Baz; end
class Foo::Bar::Qux < Foo::Bar; end
```

**Comment by jez** [comment]
@DarkDimius This doesn't reproduce when I revert #2527

**Comment by DarkDimius** [comment]
Reproduced & I understand the cause(we currently mark classes that don't have definitions as modules _after_ resolver fixed point, but this snippet requires that information before).

**Comment by DarkDimius** [comment]
@connorshea thank you for great reproducer. It tremendously helped.
