### ISSUE TITLE
Runtime breaks `Method#arity`

### ISSUE THREAD

**Issue by paracycle** [sorbet/sorbet#2643]
The runtime component wraps methods with a declared `sig` block and, in doing so, seems to break the result of calling `Method#arity` on those methods.

I am not sure if there is a way the wrapper method can impersonate the `arity` result of the wrapped method, but the current state throws off some code that is expecting to act on the proper `arity` result.

#### Input

Given the following definition:

```ruby
require 'sorbet-runtime'

class Example
  extend(T::Sig)

  sig { params(name: String).void }
  def hello(name)
  end

  def world(name)
  end
end
```

#### Observed output

The `arity` results for the two methods are observed as the following:

```ruby
e = Example.new

e.method(:hello).arity # => -1
e.method(:world).arity # => 1
```

#### Expected behavior

However, the expected result would be:

```ruby
e = Example.new

e.method(:hello).arity # => 1
e.method(:world).arity # => 1
```

/cc @masom

**Comment by jez** [comment]
The way we handle this internally is to use a private helper which looks up the sig, which holds a reference to the underlying method:

```ruby
# typed: true
require 'sorbet-runtime'

class Example
  extend(T::Sig)

  def bare(name)
  end

  sig { params(name: String).void }
  def has_sig(name)
  end
end

def real_arity(method)
  signature = T::Private::Methods.signature_for_method(method)
  if signature
    signature.method.arity
  else
    method.arity
  end
end

e = Example.new

p(e.method(:bare).arity)           # => 1
p(real_arity(e.method(:bare)))     # => 1

p(e.method(:has_sig).arity)        # => -1
p(real_arity(e.method(:has_sig)))  # => 1
```

I don't know that there's a way to change `sorbet-runtime` to preserve the arity of the wrapped method.

Here's where the method is redefined with `*args`:

https://github.com/sorbet/sorbet/blob/08cc35ec3db2142db1cb7089d492b99617056d2d/gems/sorbet-runtime/lib/types/private/methods/_methods.rb#L208

**Comment by ric2b** [comment]
Just ran into this issue myself. What about prepending `Method.arity` to do what the helper does?

https://ruby-doc.org/core-2.7.0/Module.html#method-i-prepend

```ruby
# typed: true
require 'sorbet-runtime'

class Example
  extend T::Sig

  def bare(name)
  end

  sig { params(name: String).void }
  def has_sig(name)
  end
end

module SorbetArity
  def arity
    signature = T::Private::Methods.signature_for_method(self)
    if signature
      signature.method.arity
    else
      super
    end
  end
end

class Method
  prepend SorbetArity
end

e = Example.new

p(e.method(:bare).arity)           # => 1
p(e.method(:has_sig).arity)        # => 1
```
