### ISSUE TITLE
`return` keyword defined in a proc is being interpreted as returning from the method

### ISSUE THREAD

**Issue by robdimarco-stripe** [sorbet/sorbet#2651]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns%20T.proc.params(arg1%3A%20String).returns(T%3A%3ABoolean)%7D%0A%20%20def%20foo%0A%20%20%20%20lambda%20do%20%7Cstr%7C%0A%20%20%20%20%20%20if%20str%20%3D%3D%20'bar'%0A%20%20%20%20%20%20%20%20return%20true%20%23%20this%20return%20is%20returning%20from%20the%20lambda%20not%20the%20method%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20return%20false%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20sig%20%7Breturns%20T.proc.params(arg1%3A%20String).returns(T%3A%3ABoolean)%7D%0A%20%20def%20bar%0A%20%20%20%20lambda%20do%20%7Cstr%7C%0A%20%20%20%20%20%20if%20str%20%3D%3D%20'bar'%0A%20%20%20%20%20%20%20%20next%20true%20%23%20this%20is%20functionally%20equivalent%20to%20the%20above%20method%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20next%20false%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {returns T.proc.params(arg1: String).returns(T::Boolean)}
  def foo
    lambda do |str|
      if str == 'bar'
        return true # this return is returning from the lambda not the method
      else
        return false
      end
    end
  end

  sig {returns T.proc.params(arg1: String).returns(T::Boolean)}
  def bar
    lambda do |str|
      if str == 'bar'
        next true # this is functionally equivalent to the above method
      else
        next false
      end
    end
  end
end
```

#### Observed output

```
editor.rb:11: Returning value that does not conform to method result type https://srb.help/7005
    11 |        return false
                ^^^^^^^^^^^^
  Expected T.proc.params(arg0: String).returns(T::Boolean)
    editor.rb:6: Method foo has return type T.proc.params(arg0: String).returns(T::Boolean)
     6 |  def foo
          ^^^^^^^
  Got FalseClass originating from:
    editor.rb:11:
    11 |        return false
                       ^^^^^

editor.rb:9: Returning value that does not conform to method result type https://srb.help/7005
     9 |        return true # this return is returning from the lambda not the method
                ^^^^^^^^^^^
  Expected T.proc.params(arg0: String).returns(T::Boolean)
    editor.rb:6: Method foo has return type T.proc.params(arg0: String).returns(T::Boolean)
     6 |  def foo
          ^^^^^^^
  Got TrueClass originating from:
    editor.rb:9:
     9 |        return true # this return is returning from the lambda not the method
                       ^^^^
Errors: 2
```

#### Expected behavior

I would expect there to be no errors. The `return` statements on line 9 and 11 are returning from the `lambda`, not from the method.

- - -

**Comment by jbeker** [comment]
I am seeing this same issue with similar code. Any workarounds?

**Comment by rspeicher** [comment]
I'm seeing something similar with this (contrived) example:

```ruby
    sig { returns(Symbol) }
    def example
      _test = lambda do |foo|
        return true if foo.nil?

        foo
      end

      some_other_method(test)

      :bar
    end
```

**Comment by skatenerd** [comment]
I see this pretty frequently when my code looks something like

```
sig { returns(T::Array[Integer]) }
def go(ids)
  for_id = lambda do |id|
    if id > 10
      return
    end
    helper(id)
  end
  ids.filter_map { |id| for_id.(id) }
end

```

**Comment by yannickgloster** [comment]
Still running into this same issue

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Breturns%28Proc%29%7D%0Adef%20foo%28%29%0A%20%20lambda%20do%20%7Cfoo%7C%0A%20%20%20%20return%20false%0A%20%20end%0Aend%0A)

```ruby
# typed: strict
extend T::Sig

sig {returns(Proc)}
def foo()
  lambda do |foo|
    return false
  end
end
```

**Comment by paracycle** [comment]
@yannickgloster 

From the changes in the [PR](https://github.com/sorbet/sorbet/commit/11dffff9b12680b74fcb1c9f45fd088706898e51#diff-c9b037996e9c16464e031136abe5d9df567c72f283d572b070d108228b733127R122-R125), it is obvious that only `Kernel.lambda` and `-> ()` calls are special cased, not a bare `lambda` call, which could refer to any method named `lambda`:

> ```
> Only handle `-> () {}` and `Kernel.lambda` lambdas for now, because there's nothing stopping
> someone from defining a method called `lambda` on their own that behaves differently.
> 
> We could revisit this in the future but for now let's be conservative.
> ```

You can see that the following version of your example [works as you expect](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Breturns%28Proc%29%7D%0Adef%20foo%28%29%0A%20%20Kernel.lambda%20do%20%7Cfoo%7C%0A%20%20%20%20return%20false%0A%20%20end%0Aend%0A):
```ruby
# typed: strict
extend T::Sig

sig {returns(Proc)}
def foo()
  Kernel.lambda do |foo|
    return false
  end
end
```

**Comment by yannickgloster** [comment]
> @yannickgloster
> 
> From the changes in the [PR](https://github.com/sorbet/sorbet/commit/11dffff9b12680b74fcb1c9f45fd088706898e51#diff-c9b037996e9c16464e031136abe5d9df567c72f283d572b070d108228b733127R122-R125), it is obvious that only `Kernel.lambda` and `-> ()` calls are special cased, not a bare `lambda` call, which could refer to any method named `lambda`:
> 
> > ```
> > Only handle `-> () {}` and `Kernel.lambda` lambdas for now, because there's nothing stopping
> > someone from defining a method called `lambda` on their own that behaves differently.
> > 
> > We could revisit this in the future but for now let's be conservative.
> > ```
> 
> You can see that the following version of your example [works as you expect](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Breturns%28Proc%29%7D%0Adef%20foo%28%29%0A%20%20Kernel.lambda%20do%20%7Cfoo%7C%0A%20%20%20%20return%20false%0A%20%20end%0Aend%0A):
> 
> ```ruby
> # typed: strict
> extend T::Sig
> 
> sig {returns(Proc)}
> def foo()
>   Kernel.lambda do |foo|
>     return false
>   end
> end
> ```

Ah great, sorry I must've missed that. Thanks
