### ISSUE TITLE
Ruby 2.8.0dev: ArgumentError when declaring const props in `T::Struct`s

### ISSUE THREAD

**Issue by donaldong** [sorbet/sorbet#2668]
#### Input
```
require 'sorbet-runtime'
class MyParams < T::Struct
  const :name, String
end
```

#### Observed output
```
Failure/Error: const :name, String
ArgumentError:
  wrong number of arguments (given 2, expected 1; required keywords: array, enum)
```
travis-ci:
https://travis-ci.com/chanzuckerberg/sorbet-coerce/jobs/288224784

#### Expected behavior
No errors.

**Comment by trevor-stripe** [comment]
I'm unable to reproduce this locally, what version of sorbet and ruby are you using?

**Comment by donaldong** [comment]
Hi, it's using `sorbet-runtime-0.4.5173` (retrieved via a fresh bundle install).
```
$ ruby --version
ruby 2.8.0dev (2020-02-17T04:20:51Z master 3fbcdac3e4) [x86_64-linux]
```

**Comment by trevor-stripe** [comment]
There are problems with sorbet and ruby >= 2.7, could you try with ruby 2.6?

**Comment by donaldong** [comment]
Yep, it works fine with ruby 2.6. I want to flag this issue because I find `T::Struct` to be a very useful feature and the error on the current ruby-head seems a little interesting :)

**Comment by jez** [comment]
This doesn't reproduce with 3.0.0-preview1.

I'm guessing you found a bug in 2.8.0 that has since been fixed upstream.

I tested the snippet in the first post with

```
❯ ruby --version
ruby 3.0.0preview1 (2020-09-25 master 0096d2b895) [x86_64-linux]
```
