### ISSUE TITLE
T::Enum#each_value

### ISSUE THREAD

**Issue by dduugg** [sorbet/sorbet#2671]
### Problem

The current idiomatic pattern to iterate through each value of an enum is:
```ruby
MyEnum.values.each do |enum|
  # …
end
```
This is suboptimal from a performance perspective, as it has to materialize all the enum values at once, and also triggers false positives for the rubocop `Style/HashEachMethods` [cop](https://rubocop.readthedocs.io/en/latest/cops_style/#stylehasheachmethods) 

### Proposed solution

Introduce `T::Enum#each_value`, which allows efficient iteration over an enum's values. The above example could then be re-written as:
```ruby
MyEnum.each_value do |enum|
  # …
end
```
As an added bonus, rubocop could (correctly, though from an invalid assumption) autocorrect existing code.

**Comment by elliottt** [comment]
`values.each` should be the same cost as `each_value`, as the `values` method is just an accessor for the `@values` array held by the enum implementation. Were you seeing some performance problems stemming from a use of `values.each`?
