### ISSUE TITLE
File::ALT_SEPARATOR it not always NilClass

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#2688]
`file.rbi` specifies `File::ALT_SEPARATOR` as `NilClass`. But it should be `T.nilable(String)`, because on Windows `ALT_SEPARATOR` is `\`.
(just tested on Windows-10-1703 with Ruby-2.7.0-1)

Note: `File::SEPARATOR` is `/` on Windows.
&nbsp;

https://github.com/sorbet/sorbet/blob/84b84770d0646e3e313f83d2785e547c41e6cefd/rbi/core/file.rbi#L33

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
