### ISSUE TITLE
Support unnamed (positional) method parameter signatures

### ISSUE THREAD

**Issue by ric2b** [sorbet/sorbet#2689]
### Problem

Currently method parameter signatures must include the names of all parameters, including positional ones. This leads to much longer signatures that need to be broken into multiple lines even with just a few parameters, for example:

```ruby
      sig do
        params(
          product_id: String,
          status: String,
          comment: T.nilable(String),
          attribute_errors: T::Enumerable[AttributeFeedback],
        ).void
      end
      def initialize(product_id, status, comment, attribute_errors)
        @product_id = product_id
        @status = status
        @comment = comment
        @attribute_errors = attribute_errors
      end
```

### Proposed solution

Allow typing positional arguments by position instead of naming:

```ruby
      sig { params(String, String, T.nilable(String), T::Enumerable[AttributeFeedback]).void }
      def initialize(product_id, status, comment, attribute_errors)
        @product_id = product_id
        @status = status
        @comment = comment
        @attribute_errors = attribute_errors
      end
```

This is similar to how the Contracts gem does it, and it can be much cleaner and less repetitive in simpler methods: https://egonschiele.github.io/contracts.ruby/

**Comment by elliottt** [comment]
Thanks for the suggestion! This would involve a substantial rework of the runtime and static parts of sorbet, so it's unlikely that we will change the way it behaves currently.
