### ISSUE TITLE
Duplicate classes generated in hidden.rbi

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#2703]
I spent a bit of time today messing with Sorbet's hidden definitions generation code because I was hoping I could figure out how to deduplicate the classes that the hidden definitions generator was creating for instance methods and singleton methods.

```ruby
class Array
  include ::JSON::Ext::Generator::GeneratorMethods::Array
  def bsearch(); end

  def bsearch_index(); end

  def collect!(); end

  def dig(*_); end

  def flatten!(*_); end

  def pack(*_); end

  def replace(_); end

  def shelljoin(); end

  def to_h(); end
end

class Array
  def self.try_convert(_); end
end
```

`source_by_name` in [`hidden-definition-finder.rb`](https://github.com/sorbet/sorbet/blob/29a967a22cc8cfcccb3d6a502b9ccb99cace0f5c/gems/sorbet/lib/hidden-definition-finder.rb#L194) is a hash of all the classes and their methods/includes/etc that Sorbet was able to find. Represented by JSON, it looks roughly like this:

```jsonc
{
  "Array": {
    "id": 12,
    "name": {
      "kind": "CONSTANT",
      "name": "Array"
    },
    "kind": "CLASS_OR_MODULE",
    "superClass": 7,
    "mixins": [
      36
    ],
    "children": [
      // ...
    ]
  },
  "<Class:Array>": {
    "id": 125,
    "name": {
      "kind": "UNIQUE",
      "name": "<Class:Array>",
      "unique": "SINGLETON"
    },
    "kind": "CLASS_OR_MODULE",
    "superClass": 115,
    "mixins": [
      57,
      69
    ],
    "children": [
      // ...
    ]
  }
}
```

This is my understanding of how it works, anyway. I could be wrong.

Is there a good reason for these to be separated like this, or is it just something that isn't handled right now? Unfortunately I think fixing this would require a change in the C++ code, so I'm not particularly comfortable doing it myself. And that's assuming we actually want to fix it, there's probably some weird reason to do it this way that I'm not aware of.

**Comment by elliottt** [comment]
This is an effect of how we represent the singleton classes internally. I'm not aware of any consumer of the JSON output that relies on this distinction, but I'll look into it.

**Comment by DarkDimius** [comment]
@connorshea 
> Duplicate classes generated in hidden.rbi

Could you explain why this is problematic?
Ruby allows reopenning classes like this and sorbet supports it, right?

**Comment by connorshea** [comment]
@DarkDimius there's not really a problem with it, it just makes adds more noise to the hidden.rbi, which is already quite big as is it.

**Comment by bhargavrpatel** [comment]
This is also the case for todo.rbi

```
module ::Anonymous_Delegator_6; end
module ActionMailer::Base::Mail::Message; end
module ActiveRecord::CollectionCacheKey; end
module ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods; end
module ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods; end
module ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods; end
module ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods; end
module ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods; end
module ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods; end
```

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca

**Comment by Raylokoo** [comment]
#6178
