### ISSUE TITLE
T.attached_class can't be used in modules that are `extend`ed into a class and become singleton methods

### ISSUE THREAD

**Issue by theorygeek** [sorbet/sorbet#2718]
### Problem

I have a class method. It's defined inside of a module that uses `mixes_in_class_methods`:
```ruby
module Foo
  module ClassMethods
    sig {returns(T.self_type)}
    def load; end
  end
  mixes_in_class_methods(ClassMethods)
end

class Invoice
  include Foo
end
```

Sorbet thinks that `Invoice.load` returns `T.class_of(Invoice)`, but it actually returns `Invoice`.

### Proposed solution

I'd like to be able to use `T.attached_class`, but Sorbet doesn't realize that I'm in a singleton context. 

I'd like to add `class_methods!` as an annotation, similar to `interface!`:
```ruby
module Foo
  module ClassMethods
    # Sorbet now knows that this is in a singleton context
    class_methods!

    # You can correctly type the method:
    sig {returns(T.attached_class)}
    def load; end
  end
end
```

Sorbet would make it illegal to `include` the module. Instead, you must either `extend` it or use `mixes_in_class_methods`.

**Comment by jez** [comment]
This is also how all the `ActiveRecord::FinderMethods` work:

https://github.com/rails/rails/blob/f33d52c95217212cbacc8d5e44b5a8e3cdc6f5b3/activerecord/lib/active_record/relation/finder_methods.rb#L67

**Comment by theorygeek** [comment]
> Also I don't think the proposed solution of `class_methods!` is the right approach

Out of curiosity, what would be a better solution?

**Comment by bjacobso** [comment]
@theorygeek I'm running into a similar issue, wondering if you found a solution?
