### ISSUE TITLE
Place constants in gem RBIs instead of hidden.rbi

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#2728]
### Problem

My `hidden.rbi` has a lot of classes that look like this:

```ruby
class SXP::Reader::SPARQL
  A = ::T.let(nil, ::T.untyped)
  BASE = ::T.let(nil, ::T.untyped)
  BNODE_ID = ::T.let(nil, ::T.untyped)
  BNODE_NEW = ::T.let(nil, ::T.untyped)
  DECIMAL = ::T.let(nil, ::T.untyped)
  DOUBLE = ::T.let(nil, ::T.untyped)
  EVAR_ID = ::T.let(nil, ::T.untyped)
  EXPONENT = ::T.let(nil, ::T.untyped)
  FALSE = ::T.let(nil, ::T.untyped)
  ND_EVAR = ::T.let(nil, ::T.untyped)
  ND_VAR = ::T.let(nil, ::T.untyped)
  NIL = ::T.let(nil, ::T.untyped)
  PNAME = ::T.let(nil, ::T.untyped)
  PREFIX = ::T.let(nil, ::T.untyped)
  RDF_TYPE = ::T.let(nil, ::T.untyped)
  TRUE = ::T.let(nil, ::T.untyped)
  VAR_ID = ::T.let(nil, ::T.untyped)
end
```

These are all constants from the SXP gem, but they're not being put in `sxp.rbi` because the hidden definitions finder doesn't seem to associate constants properly with their. @jez mentioned in Slack that Stripe has something internal that does this correctly, but the hidden-definitions finder for open source Sorbet doesn't have this functionality.

My `hidden.rbi` has over 5000 instances of `::T.let(nil, ::T.untyped)`, almost 20% of the file.

### Proposed solution

Constants should be included in the individual gem's RBIs rather than `hidden.rbi`.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
