### ISSUE TITLE
Nested `flatten` with a custom Enumerable class doesn't work

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#2767]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%20%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20include%20Enumerable%0A%0A%20%20Elem%20%3D%20type_member(fixed%3A%20String)%0A%20%20%0A%20%20sig%20%7B%20override.params(blk%3A%20T.proc.params(e%3A%20Elem).void).void%20%7D%0A%20%20def%20each(%26blk)%0A%20%20%20%20T.unsafe(nil)%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T%3A%3AArray%5BElem%5D)%7D%0A%20%20def%20flatten%0A%20%20%20%20T.unsafe(nil)%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20a%20%3D%20A.new%0A%20%20b%20%3D%20%5BA.new%2C%20A.new%5D%0A%0A%20%20T.reveal_type(a.flatten)%0A%20%20T.reveal_type(b.flatten)%0Aend%0)

```ruby
# typed: true
class A 
  extend T::Sig
  extend T::Generic
  include Enumerable

  Elem = type_member(fixed: String)
  
  sig { override.params(blk: T.proc.params(e: Elem).void).void }
  def each(&blk)
    T.unsafe(nil)
  end

  sig { returns(T::Array[Elem])}
  def flatten
    T.unsafe(nil)
  end
end

def main
  a = A.new
  b = [A.new, A.new]

  T.reveal_type(a.flatten)
  T.reveal_type(b.flatten)
end
```

#### Observed output

```
Revealed type: T::Array[A] 
```

#### Expected behavior

```
Revealed type: T::Array[String]
```
Flatten is called on subsequent objects of the collection. I'd expect that sorbet know flatten will call `flatten` in the custom enumerable.

See convo on slack:
https://sorbet-ruby.slack.com/archives/CJL5B3CEN/p1583892614100500

**Comment by manhhung741** [comment]
cc @wpride

**Comment by elliottt** [comment]
Unfortunately, encoding the fact that flatten will be called recursively down, yielding elements of the leaf enumerable-values would require more type-level machinery than we have currently. Given the complexity of implementing type-level features like this, it's unlikely that we'll be able to type this method correctly.
