### ISSUE TITLE
`Enumerable#reduce` loses type information inside of block

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#2770]
#### Input

[→ View on sorbet.run](https://sorbet.run/#my_regexes%20%3D%20%5B%2Fa%2F%2C%20%2Fb%2F%5D%0Amy_strings%20%3D%20%5B'a'%2C%20'b'%5D%0Amy_str%20%3D%20'abc'%0A%0Amy_regexes.reduce(my_str)%20do%20%7Cprevious%2C%20to_remove%7C%0A%20%20%20%20T.assert_type!(previous%2C%20String)%0A%20%20%20%20previous.wrong_gsub(to_remove%2C%20'')%0Aend%0A%0Amy_strings.reduce(my_str)%20do%20%7Cprevious%2C%20to_remove%7C%0A%20%20%20%20T.assert_type!(previous%2C%20String)%0A%20%20%20%20previous.gsub(to_remove%2C%20'')%0Aend%0A)

```ruby
my_regexes = [/a/, /b/]
my_strings = ['a', 'b']
my_str = 'abc'

my_regexes.reduce(my_str) do |previous, to_remove|
    T.assert_type!(previous, String)
    previous.wrong_gsub(to_remove, '')
end

my_strings.reduce(my_str) do |previous, to_remove|
    T.assert_type!(previous, String) # this works just fine! Note that `initial` matches `Elem`
    previous.gsub(to_remove, '')
end
```

#### Observed output

```
editor.rb:6: The typechecker was unable to infer the type of the asserted value https://srb.help/7007
     6 |    T.assert_type!(previous, String)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.untyped originating from:
    editor.rb:5:
     5 |my_regexes.reduce(my_str) do |previous, to_remove|
                                      ^^^^^^^^
  You may need to add additional `sig` annotations
Errors: 1
```

#### Expected behavior
No errors

- - -

I suspect the problem is around this signature: https://github.com/sorbet/sorbet/blob/fdb18367a187f0e33772e1ebabb4df6693f967bc/rbi/core/enumerable.rbi#L1232-L1245

If I'm not mistaken, `initial` shouldn't be restricted to `Elem`, but it could actually be of any type.

I tried changing the signature to what I think is the correct type definition:

```
sig do
    type_parameters(:U)
    .params(
        initial: T.type_parameter(:U),
        blk: T.proc.params(arg0: T.type_parameter(:U), arg1: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T.type_parameter(:U))
end
```

However, this still doesn't solve the problem, as when trying something like:

```
my_regexes.reduce(my_str) do |previous, to_remove|
    T.assert_type!(previous, String)
    previous.wrong_gsub(to_remove, '')
end
```

I get:

```
~/sorbet/test/testdata/rbi/enumerable.rb:33: Argument does not have asserted type String https://srb.help/7007
    33 |  T.assert_type!(previous, String)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got <any> originating from:
    ~/sorbet/test/testdata/rbi/enumerable.rb:32:
    32 |['/a/', ' /b/'].reduce('abc') do |previous, to_remove|
                                          ^^^^^^^^
Errors: 1
```

**Comment by elliottt** [comment]
The fix you're suggesting is likely running into the same problems present in issue #38.

**Comment by marianosimone** [comment]
Another related issues seems to be https://github.com/sorbet/sorbet/issues/1361
