### ISSUE TITLE
srb init fails on Ruby 2.7 because of argument delegation

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#2771]
#### Input

`srb init` fails when used on Ruby 2.7 with Capybara. I'm fairly certain it's because of code like this, which uses the new `...` syntax: https://github.com/teamcapybara/capybara/blob/5d24424b135be8539810f4e65b7bc920b40ede8f/lib/capybara/rack_test/node.rb#L122-L139

You can reproduce this issue pretty simply, like so:

- `git clone https://github.com/connorshea/sorbet-capybara-27`
- Make sure you're on Ruby 2.7, e.g. `rbenv local 2.7.0`
- `bundle install`
- `bundle exec srb init`
- See that it crashes

#### Observed output

It ends up crashing when generating the reflection.rbi`

```
Printing /var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20200314-21062-gaqeqd/reflection.rbi's symbol table into /var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20200314-21062-gaqeqd/reflection.json
Traceback (most recent call last):
	6: from /Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5439/bin/srb-rbi:237:in `<main>'
	5: from /Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5439/bin/srb-rbi:196:in `main'
	4: from /Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5439/bin/srb-rbi:121:in `init'
	3: from /Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5439/bin/srb-rbi:232:in `block in make_step'
	2: from /Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5439/lib/hidden-definition-finder.rb:38:in `main'
	1: from /Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5439/lib/hidden-definition-finder.rb:47:in `main'
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5439/lib/hidden-definition-finder.rb:149:in `write_constants': /var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20200314-21062-gaqeqd/reflection.rbi had unexpected errors. Check this file for a clue: /var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20200314-21062-gaqeqd/reflection.json.err (RuntimeError)
```

`reflection.json.err` has lines like this:

```
/var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20200314-20791-17d8u9b/reflection.rbi:19468: unexpected token tCOLON https://srb.help/2001
       19468 |      *: ::T.untyped,
                     ^

/var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20200314-20791-17d8u9b/reflection.rbi:19473: unexpected token tAMPER https://srb.help/2001
       19473 |  def [](**, &&); end
                            ^
```

And generates methods like this in `reflection.rbi`:

```ruby
  sig do
    params(
      *: ::T.untyped,
      &: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def [](**, &&); end
```

#### Expected behavior

I'd expect this to be generated the same as it looks in the actual code, like `def method_name(...); end`. Unfortunately, there's not currently a way of distinguishing between `(*args, &blk)` and `(...)` via the `parameters` method because of this upstream issue: https://bugs.ruby-lang.org/issues/16456

We could determine it by checking for `Method#parameters` returning something like this:

```ruby
def foo(...); end
p method(:foo).parameters
# => [[:rest, :*], [:block, :&]]
```

**Comment by connorshea** [comment]
See also #2618, which reported this issue a few weeks ago.

**Comment by DarkDimius** [comment]
Unfortunately, we're not yet working on 2.7 support at Stripe.
We will love to review PRs implementing 2.7 support, but we're not putting effort into it just yet

**Comment by jaredbeck** [comment]
I got the same error with the latest sorbet (currently 0.5.5622) and ruby 2.7:

```
Traceback (most recent call last):
	6: from /Users/.../sorbet-0.5.5622/bin/srb-rbi:237:in `<main>'
	5: from /Users/.../sorbet-0.5.5622/bin/srb-rbi:196:in `main'
	4: from /Users/.../sorbet-0.5.5622/bin/srb-rbi:121:in `init'
	3: from /Users/.../sorbet-0.5.5622/bin/srb-rbi:232:in `block in make_step'
	2: from /Users/.../sorbet-0.5.5622/lib/hidden-definition-finder.rb:38:in `main'
	1: from /Users/.../sorbet-0.5.5622/lib/hidden-definition-finder.rb:47:in `main'
/Users/.../sorbet-0.5.5622/lib/hidden-definition-finder.rb:149:in `write_constants': 
/var/folders/sb/69c3...t6qms0/reflection.rbi had unexpected errors. 
Check this file for a clue: /var/folders/sb/69c3drbd4pl_0j0xydlssh200000gn/T/d20200514-22232-t6qms0/reflection.json.err (RuntimeError)
```

> Unfortunately, we're not yet working on 2.7 support at Stripe.

Can you please clarify, it sounds like people using sorbet should stay on 2.6 for now?

FYI, https://sorbet.org/docs/faq#what-platforms-does-sorbet-support says:

>  Ruby 2.7 should mostly work, but feel free to open issues for it.

But, if `srb init` crashes, we should probably rephrase it.

**Comment by connorshea** [comment]
FWIW I was able to fix a lot of the deprecation warnings from `tracer.rb:40` (except one) when running srb init by changing this bit of code in `tracer.rb`:

```ruby
module ClassOverride
  def new(*)
    result = super
    Sorbet::Private::GemGeneratorTracepoint::Tracer.on_module_created(result)
    result
  end
end
```

to this:

```ruby
module ClassOverride
  def new(*)
    result = super
    Sorbet::Private::GemGeneratorTracepoint::Tracer.on_module_created(result)
    result
  end

  ruby2_keywords(:new) if respond_to?(:ruby2_keywords, true)
end
```

Before this fix I was getting a ton of warnings like this:

```
/Users/connorshea/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5737/lib/gem-generator-tracepoint/tracer.rb:40: warning: Using the last argument as keyword parameters is deprecated
```

Now I only get one, not really sure how to fix that last one.
