### ISSUE TITLE
Allow having T.untyped in strong strictness mode (without allowing using it)

### ISSUE THREAD

**Issue by L-as** [sorbet/sorbet#2804]
### Problem

I really enjoy the safety I get from Sorbet, but often I have to deal with untyped code. In such cases, I have to set my mode to just "strict" to allow T.untyped values, but the issue is that by allowing free use of T.untyped, bugs can pop up silently since static checks can't be applied to untyped values. Untyped values often have a type that is obvious to the user but just not to Sorbet.

### Proposed solution

I propose that there can **be** values of type T.untyped in some strictness mode higher than "strict" (e.g. the strong mode), but that you can't *use* them. You'd have to first cast them to another type, or pass it to something else that expects an untyped value. Instead of being forbidden, it could be treated like BasicObject or some more restrictive type.

**Comment by L-as** [comment]
This would also solve not being able to define structs in strong mode.

**Comment by drx** [comment]
Flow has a `strict-local` option: https://flow.org/en/docs/strict/#toc-strict-local

> `@flow strict-local` is the same as `@flow strict`, except it does not require its dependencies to also be strict (i.e. it is “locally” strict). It does not have a separate configuration: it uses the same configuration as Flow Strict, just without the nonstrict-import rule.

What you're asking for could be done by introducing a `typed: strong-local` directive to sorbet.

**Comment by jez** [comment]
Thanks for the suggestion.

We are not prioritizing strong mode right now.
