### ISSUE TITLE
Bug/gotcha with standard String == Integer comparison? Need for stricter RBI's?

### ISSUE THREAD

**Issue by emilebosch** [sorbet/sorbet#2819]
Hi! All hope you're all safe out there! We're thinking of adopting Sorbet for making our math and calculations on payments more safe. For this reason I was doing a simple **string** to int **check**. And to my surprise it shows no errors.

I can sort of guess that this has to do with the fact that that Integer `==` can accept everything so  it might be 'technically correct' but totally not what one might expect, coming from languages such as C# as this is a strict no-go. 

Is there a path towards more stricter library / RBI for these built in types?

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Arequire%20%22sorbet-runtime%22%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20returns(Integer)%20%7D%0A%20%20def%20amount%0A%20%20%20%201%0A%20%20end%0Aend%0A%0Aa%20%3D%20A.new%0Aif%20a.amount%20%3D%3D%20%22wtf%22%20%23%20why%20is%20this%20possible%3F%0A%20%20p%20%22asd%22%0Aend%0A)

```ruby
# typed: strict
require "sorbet-runtime"

class A
  extend T::Sig
  sig { returns(Integer) }
  def amount
    1
  end
end

a = A.new
if a.amount == "wtf" # why is this possible?
  p "Hi"
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

Would expect that the type system would fail or at least warn me about doing a String to integer comparison. 

- - -

**Comment by elliottt** [comment]
The [`==` operator](https://github.com/sorbet/sorbet/blob/066c2148756bd09917fa88e1ac1a40beea1791ad/rbi/core/kernel.rbi#L307-L313) accepts an argument of type `BasicObject`, so you're allowed to compare against anything else. The program you provided is fine, as the comparison will always be false.

**Comment by emilebosch** [comment]
Imma close this for now and Integer/Num/float RBI without these overly accepting/kind `==`
