### ISSUE TITLE
srb rbi hidden-definitions takes 100% longer in rails 6 with zeitwerk enabled

### ISSUE THREAD

**Issue by modosc** [sorbet/sorbet#2834]
#### Input

i first noticed this behavior in my employer's codebase when we upgraded rails from 5.2 to 6.0 but i can reproduce it with two empty rails apps generated via `rails new`.  the only change from the generated apps was the addition of `sorbet` to the `Gemfile`. 

i'm also using `ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]`  and `sorbet 0.5.5480`

### Update 

i've verified that with `config.autoloader = :classic` in rails 6.0 the time is similar to 5.2, so i'm thinking that's the issue?

#### Observed output

both apps were primed with `SRB_YES=1 bundle exec srb init` but i narrowed down the main time difference to `hidden-definitions`:
rails 5.2
```
work ~/git/app-5.2 [master]$ time  bundle exec srb rbi hidden-definitions
# ...
real	0m21.344s
user	0m18.972s
sys	0m2.975s
```

rails 6 with `config.autoloader = :zeitwerk`
```
work ~/git/app-6.0 [master]$ time  bundle exec srb rbi hidden-definitions
# ...
real	0m44.041s
user	0m42.196s
sys	0m2.805s
```

rails 6 with `config.autoloader = :classic`

```
work ~/git/app-6.0 [master]$ time  bundle exec srb rbi hidden-definitions
# ...
real	0m26.522s
user	0m22.209s
sys	0m3.415s
```

#### Expected behavior

i'd assume the times should be more or less identical.

**Comment by trevor-stripe** [comment]
Do you see the same slowdown with `srb tc`? Could you try following the instructions at [https://github.com/sorbet/sorbet/blob/master/docs/tracing.md] to produce traces for each run? That might give you a sense for where the slowdown is coming from.

**Comment by modosc** [comment]
> Do you see the same slowdown with srb tc?

the times are identical on both projects but they don't have any code in them beyond the defaults so i'm not sure how to interpret that. 

i'm going to try the trace now.

**Comment by modosc** [comment]
i can't seem to get a trace output from `srb rbi hidden-definitions`. 

for `srb tc` the times are almost identical (and so are the traces).

**Comment by modosc** [comment]
also tested this in a project which actually has a few models ([sorbet-rails](https://github.com/chanzuckerberg/sorbet-rails)) - same almost identical results with `srb tc`, same 100% slowdown with `srb rbi hidden-definitions`.

**Comment by modosc** [comment]
i added some instrumentation locally - here's a comparison of each call from [HiddenMethodFinder#main](https://github.com/sorbet/sorbet/blob/1f0647d69e565e6968a7a209139180b32c626794/gems/sorbet/lib/hidden-definition-finder.rb#L41) running against a default new rails 6.0 app with only the autoloader settings differing:
| method  | zeitwerk (time in s)| classic (time in s)|
| ---------| ---------|--------|
| `mk_dir` | 1.1000000085914508e-05 |  1.1000000085914508e-05 |
| `require_everything` | 3.4498960000018997 | 3.4909159999988333 |
| `all_modules_and_aliases` | 1.4463419999992766 | 1.2837059999983467 | 
| `gen_source_rbi` | 7.089869999999792 | 6.460298999998486 | 
| `rm_rbis` | 0.000477999998111045 | 0.0008149999994202517 | 
| `write_constants` | 2.1840460000021267 | 2.1413200000024517 | 
| `read_constants` | 1.6297340000019176 | 1.8633130000016536 | 
| `write_diff` | 24.90110300000015 | 6.672700000002806 |
| `split_rbi` | 0.023199999999633292  | 0.02332600000227103 | 
| `rm_dir` | 0.004639000002498506 | 0.0036760000002686866 |

seems like `write_diff` is the main culprit, i'm going to keep digging here.

**Comment by modosc** [comment]
from `write_diff`:
| method  | zeitwerk (time in s)| classic (time in s)|
| ---------| ---------|--------|
| `symbols_id_to_name(rbi,'')` | 0.09919500000250991 | 0.09102900000289083 |
| `symbols_id_to_name(source,'')` | 0.08275000000139698 | 0.07706899999902816 |
| `serialize_constants` | 27.363100999999006 | 6.681972999998834 |
| `File.write` | 0.0006210000028659124 | 0.009410000002390007 |

**Comment by modosc** [comment]
getting deeper into `serialize_constants`, it looks like the amount of time spent in `serialize_alias` and `serialize_class` is almost exactly double when using `zeitwerk` vs 'classic'

**Comment by modosc** [comment]
here's a call stack profile of this chunk of code with classic mode:
<img width="707" alt="classic call stack" src="https://user-images.githubusercontent.com/2231664/78936167-e8d6db00-7a62-11ea-983e-6d6bac962431.png">
and with zeitwerk:
<img width="714" alt="zeitwerk call stack" src="https://user-images.githubusercontent.com/2231664/78936166-e7a5ae00-7a62-11ea-9eed-70c5164b1a1d.png">

**Comment by modosc** [comment]
is there anything else i can do do to help track this down?

**Comment by fxn** [comment]
Hey! I am not familiar with this code, but could try to help.

What does

```
bundle exec srb rbi hidden-definitions
```

do? What does "serializing a constant" mean? How is that serialization performed?

**Comment by modosc** [comment]
i just checked and i can't reproduce this anymore. it must have been fixed, thanks!

**Comment by elliottt** [comment]
Glad it's fixed, but sorry that we didn't get to the bottom of what was causing the slowdown :(
