### ISSUE TITLE
Second argument to Enumerable#zip block is typed incorrectly

### ISSUE THREAD

**Issue by seachel** [sorbet/sorbet#2848]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Asig%7Bparams(array1%3A%20T%3A%3AArray%5BInteger%5D%2C%20array2%3A%20T%3A%3AArray%5BInteger%5D).void%7D%0Adef%20self.test_elements(array1%2C%20array2)%0A%0A%20%20%23%20accessed%20elements%20in%20the%20arrays%20have%20the%20correct%20type%0A%20%20test_type%20%3D%20T.must(array1%5B0%5D)%20%2B%20T.must(array2%5B0%5D)%0A%0A%20%20%23%20incorrect%20type%20for%20second%20block%20argument%0A%20%20array1.zip(array2)%20do%20%7Ce1%2C%20e2%7C%0A%20%20%20%20T.reveal_type(e2)%20%23%20is%20%3Cany%3E%2C%20but%20should%20be%20T.nilable(Integer)%3F%0A%20%20end%0A%0A%20%20%23%20elements%20have%20correct%20type%0A%20%20array1.zip(array2).each%20do%20%7Cpair%7C%0A%20%20%20%20T.reveal_type(pair%5B1%5D)%20%23%20is%20T.nilable(Integer)%0A%20%20end%0Aend)

```ruby
# typed: true
sig{params(array1: T::Array[Integer], array2: T::Array[Integer]).void}
def self.test_elements(array1, array2)

  # accessed elements in the arrays have the correct type
  test_type = T.must(array1[0]) + T.must(array2[0])

  # incorrect type for second block argument
  array1.zip(array2) do |e1, e2|
    T.reveal_type(e2) # is <any>, but should be T.nilable(Integer)?
  end

  # elements have correct type
  array1.zip(array2).each do |pair|
    T.reveal_type(pair[1]) # is T.nilable(Integer)
  end
end
```

#### Observed output

```
editor.rb:10: Revealed type: <any> https://srb.help/7014
    10 |    T.reveal_type(e2) # is <any>, but should be T.nilable(Integer)?
            ^^^^^^^^^^^^^^^^^
  From:
    editor.rb:9:
     9 |  array1.zip(array2) do |e1, e2|
                                     ^^

editor.rb:15: Revealed type: T.nilable(Integer) https://srb.help/7014
    15 |    T.reveal_type(pair[1]) # is T.nilable(Integer)
            ^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:15:
    15 |    T.reveal_type(pair[1]) # is T.nilable(Integer)
                          ^^^^^^^
Errors: 2
```

#### Expected behavior

I expect that when using the block version of zip, the arguments in the block have a type that matches the type argument to the corresponding array type, but the second argument has type `<any>` (line 10 in the example).

- - -

I think this might be similar to issues #2770 or #38, but I don't quite understand how they're described. I don't see the same problem when I use `zip` then iterate again with `each` or `map`.

**Comment by jez** [comment]
This is fixed as of #6076
