### ISSUE TITLE
`abstract!` in T::Helpers method collides with `abstract!` method in AbstractController::Base

### ISSUE THREAD

**Issue by rafaelfranca** [sorbet/sorbet#2854]
http://api.rubyonrails.org/classes/AbstractController/Base.html#method-c-abstract-21

This is only an issue in Rails applications that defines abstract controllers.

Rails use the `abstract!` method to change the behavior of controllers.

When trying to type abstract controllers including `T::Helpers` the behavior of Rails is lost since the original method is not called.

This is a naming conflict that is likely hard to avoid given the way sorbet works we need to include the `T::Helpers` in the class.

Not sure how to fix this problem without renaming that method to something that has less chance of colliding.

**Comment by rafaelfranca** [comment]
How about adding aliases to `abstract!` like `abstract_class!`? That way you could continue using `abstract!` if you don't use Rails, but allow Rails users to use `abstract_class!`.

**Comment by paracycle** [comment]
If `sorbet-runtime` calls `super` in its `abstract!` implementation, isn't that enough to trigger the Rails controller method?

**Comment by rafaelfranca** [comment]
Yes, that would call the `super` implementation.

**Comment by unterkoefler** [comment]
Hi. I ran into this today, but the opposite problem. I wanted to call the sorbet `abstract!` but not the rails `abstract!`. Any ideas for a workaround?

**Comment by amomchilov** [comment]
@unterkoefler Not pretty, but here's a temporary workaround to unblock you.

You can put an intermediate module in the ancestor chain that's above `T::Helpers` and below `AbstractController::Base`, which intercepts [that `super` call](https://github.com/sorbet/sorbet/pull/6240/files#diff-c97218e8db476840f772e06215caf8daef376f4a473832c01184c7a9beda55f6R18) from Sorbet, and swallows it (i.e. doesn't delegate it up to `AbstractController::Base.abstract!`)

```ruby
module NotActuallyAbstract
  def abstract!
    # no-op.
    # This allows this controller to be Sorbet's definition of abstract,
    # without also being `AbstractController::Base`'s definition of abstract.
  end
end


class YourController < ActionController::Base
  extend NotActuallyAbstract # Important: must come before `T::Sig`
  extend T::Sig
   
  abstract!
   
  # ...
end
```

**Comment by lavoiesl** [comment]
If a controller is abstract in Sorbet, it should likely also be abstract for routing.

However, we ran into an issue that making a controller abstract in Rails makes all methods hidden.

For example, this doesn't work, the `user_proxy#index` method is not visible:
```rb
class AbstractProxyController < ActionController::Base
  extend T::Helper
  
  def index
    proxy.pass(request)
  end

  sig { abstract.returns(Proxy) }
  def proxy
  end
end

class UserProxyController < AbstractProxyController
  extend T::Sig

  private

  sig { override.returns(Proxy) }
  def proxy
    # ...
  end
end

Rails.application.routes.draw do
  post "/user", to: "user_proxy#index"
end
```

It's because of [`internal_methods`](https://api.rubyonrails.org/v7.0.8/classes/AbstractController/Base.html#method-c-internal_methods)

This works:
```rb
class AbstractProxyController < ActionController::Base
  extend T::Helper

  def self.internal_methods
    super - [:index]
  end
  
  def index
    proxy.pass(request)
  end

  private

  sig { abstract.returns(Proxy) }
  def proxy
  end
end
```
