### ISSUE TITLE
Types parameters are not subtypes of BasicObject

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#2860]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Asig%20%7B%20params(a%3A%20BasicObject).void%20%7D%0Adef%20foo(a)%3B%20end%0A%0Aclass%20Bar%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20type_parameters(%3AU).params(a%3A%20T.type_parameter(%3AU)).void%20%7D%0A%20%20def%20bar(a)%0A%20%20%20%20foo(a)%0A%20%20end%0Aend)

```ruby
# typed: true

sig { params(a: BasicObject).void }
def foo(a); end

class Bar
  extend T::Sig

  sig { type_parameters(:U).params(a: T.type_parameter(:U)).void }
  def bar(a)
    foo(a)
  end
end
```

#### Observed output

```
editor.rb:11: Expected BasicObject but found Bar#bar#U for argument a https://srb.help/7002
    11 |    foo(a)
            ^^^^^^
    editor.rb:3: Method Object#foo has specified a as BasicObject
     3 |sig { params(a: BasicObject).void }
                     ^
  Got Bar#bar#U originating from:
    editor.rb:10:
    10 |  def bar(a)
                  ^
Errors: 1
```

#### Expected behavior

Should this example work?

**Comment by samdoiron** [comment]
It was brought up internally that `⊥` (`T.noreturn`) might be the issue here -- that said, it's very surprising and not obvious if so.
