### ISSUE TITLE
`tap` in a nilable context leads to wrong typing

### ISSUE THREAD

**Issue by jusleg** [sorbet/sorbet#2877]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Afoo%20%3D%20T.let(nil%2C%20T.nilable(Integer))%0AT.reveal_type(foo.tap%20%7B%7D))

```ruby
foo = T.let(nil, T.nilable(Integer))
T.reveal_type(foo.tap {})
```

#### Observed output

```
editor.rb:3: Revealed type: Integer https://srb.help/7014
     3 |T.reveal_type(foo.tap {})
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:3:
     3 |T.reveal_type(foo.tap {})
                      ^^^^^^^^^^
```

This can lead to runtime errors as `srb tc` would pass on the following code but the runtime checks would raise `Return value: Expected type Integer, got type NilClass (RuntimeError)`

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Bparams(x%3A%20T.nilable(Integer)).returns(Integer)%7D%0A%20%20def%20foo(x)%0A%20%20%20%20x.tap%20do%20%7Cstuff%7C%0A%20%20%20%20end%0A%20%20end%0Aend%0AA.new.foo(nil))
```ruby
class A
  extend T::Sig
  sig {params(x: T.nilable(Integer)).returns(Integer)}
  def foo(x)
    x.tap do |stuff|
    end
  end
end
A.new.foo(nil)
```

#### Expected behavior

The revealed type should be `T.nilable(Integer)`

This behaviour seem to be present on all released versions of sorbet (0.4.4230 to 0.5.5510)

**Comment by ric2b** [comment]
Might this be a bug with `T.self_type`, since that's that kernel#tap returns?

https://github.com/sorbet/sorbet/blob/026a5c437d269267bf99608a4be61d1385631d11/rbi/core/kernel.rbi#L581-L587

**Comment by elliottt** [comment]
I think that you're right, and that something funny is happening with `T.self_type` in the presence of `T.any`. Here's another example:

```ruby
# typed: true

x = T.let(1, T.any(NilClass, Integer))
T.reveal_type(x.tap{}) # NilClass

y = T.let(1, T.any(Integer, NilClass))
T.reveal_type(y.tap{}) # Integer
```
[sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%20T.let(1%2C%20T.any(NilClass%2C%20Integer))%0AT.reveal_type(x.tap%7B%7D)%0A%0Ay%20%3D%20T.let(1%2C%20T.any(Integer%2C%20NilClass))%0AT.reveal_type(y.tap%7B%7D))

**Comment by jez** [comment]
For what it's worth I don't think this is related to `T.self_type`. The same issue appears for other methods too:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Aclass%20Left%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20returns%28Integer%29%0A%20%20end%0A%20%20def%20foo%0A%20%20%20%200%0A%20%20end%0Aend%0A%0Aclass%20Right%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20returns%28NilClass%29%0A%20%20end%0A%20%20def%20foo%0A%20%20%20%20nil%0A%20%20end%0Aend%0A%0Asig%20%7Bparams%28x%3A%20T.any%28Left%2C%20Right%29%29.void%7D%0Adef%20example1%28x%29%0A%20%20%23%20This%20shows%20the%20bug%3A%0A%20%20result%20%3D%20x.foo%20%7B%7D%0A%20%20T.reveal_type%28result%29%0A%0A%20%20%23%20This%20doesn't%3A%0A%20%20result%20%3D%20x.foo%0A%20%20T.reveal_type%28result%29%0Aend)

```ruby
# typed: true

extend T::Sig

class Left
  extend T::Sig

  sig do
    returns(Integer)
  end
  def foo
    0
  end
end

class Right
  extend T::Sig

  sig do
    returns(NilClass)
  end
  def foo
    nil
  end
end

sig {params(x: T.any(Left, Right)).void}
def example1(x)
  # This shows the bug:
  result = x.foo {}
  T.reveal_type(result)

  # This doesn't:
  result = x.foo
  T.reveal_type(result)
end
```

#### Observed output

```
editor.rb:31: Revealed type: Integer https://srb.help/7014
    31 |  T.reveal_type(result)
          ^^^^^^^^^^^^^^^^^^^^^
  Got Integer originating from:
    editor.rb:30:
    30 |  result = x.foo {}
                   ^^^^^^^^

editor.rb:35: Revealed type: T.nilable(Integer) https://srb.help/7014
    35 |  T.reveal_type(result)
          ^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(Integer) originating from:
    editor.rb:34:
    34 |  result = x.foo
                   ^^^^^
Errors: 2
```

With that in mind, I'm going to close this in favor of #5409
