### ISSUE TITLE
We seem to loose generic instantiation of fixed class templates

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#29]
https://sorbet.run/#class%20Bookkeeper%0A%20%20extend%20T%3A%3AHelpers%0A%20%20%0A%20%20Instance%20%3D%20type_template%0A%20%20%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20block%3A%20T.proc.params(arg0%3A%20Instance).void%0A%20%20%20%20)%0A%20%20%20%20.void%0A%20%20end%0A%20%20def%20self.bookkeep(%26block)%0A%20%20end%0Aend%0A%0Aclass%20BookkeeperChild%20%3C%20Bookkeeper%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3AGeneric%0A%20%20%0A%20%20Instance%20%3D%20type_template(fixed%3A%20self)%0Aend%0A%0Aclass%20Test%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20%23%20This%20works%3A%0A%20%20def%20test%0A%20%20%20%20BookkeeperChild.bookkeep%20do%20%7Cb%7C%0A%20%20%20%20%20%20%23%20commit%20stuff%0A%20%20%20%20end%0A%20%20%20%20T.let(BookkeeperChild%2C%20T.class_of(BookkeeperChild)).bookkeep%20do%20%7Cb%7C%0A%20%20%20%20%20%20%23%20commit%20stuff%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20end

Comments: 18/Dec/18 6:25 PM;fidel;@dmitry-stripe do we have an estimate on when this will be fixed? That would help us gauge if we should reconsider our current implementation.

 

Thanks!

18/Dec/18 6:57 PM;jez;This is likely to not be fixed anytime soon, as we're working on adding sigs to existing code before enabling new kinds of code to be typed. I'd recommend that you proceed assuming that this will not be fixed before you need to land your feature.

Originally reported by @dmitry-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1514

**Comment by jez** [comment]
Seems to be fixed?
