### ISSUE TITLE
Emit error if void used in conditional branch

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#2913]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20self.foo%3B%20end%0Aend%0A%0Aif%20A.foo%0A%20%20puts%20%22Dead%20code%22%0Aend)

```ruby
# typed: true

class A
  extend T::Sig

  sig { void }
  def self.foo; end
end

if A.foo
  puts "Dead code"
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

There should be an error for attempting to use `A.foo` in a conditional.
At runtime, void values are always truthy.
When people branch on void, it means they think that the type could be falsy, which it never can be.

- - -

Using `unless` will show a [dead code error](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20self.foo%3B%20end%0Aend%0A%0Aunless%20A.foo%0A%20%20puts%20%22Dead%20code%22%0Aend):

```ruby
# typed: true

class A
  extend T::Sig

  sig { void }
  def self.foo; end
end

unless A.foo
  puts "Dead code"
end
```

```
editor.rb:11: This code is unreachable https://srb.help/7006
    11 |  puts "Dead code"
               ^^^^^^^^^^^
Errors: 1
```

but we would like to reliably show an error in both cases by making the error show up at the conditional itself.

**Comment by Morriar** [comment]
Related: https://github.com/sorbet/sorbet/issues/1367

**Comment by elliottt** [comment]
Thanks for tracking this down!
