### ISSUE TITLE
Can't alias `new`

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#2928]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20class%20%3C%3C%20self%0A%20%20%20%20alias%20%3Afoo%20%3Anew%0A%20%20end%0Aend)

```ruby
# typed: true

class A
  extend T::Sig

  class << self
    alias_method :foo, :new
  end
end
```

#### Observed output

```
editor.rb:7: Can't make method alias from foo to non existing method new https://srb.help/5037
     7 |    alias_method :foo, :new
                               ^^^^
Errors: 1
```

#### Expected behavior

Since `A` is a non-abstract class I can't see a reason why the `new` method wouldn't be defined.

The current workaround is to redeclare locally the `new` method:

```ruby
# typed: true

class A
  extend T::Sig

  class << self
    alias_method :foo, :new

    def new
      super
    end
  end
end

A.foo
```

**Comment by jez** [comment]
This is not specific to `new`:

https://github.com/sorbet/sorbet/issues/2378
