### ISSUE TITLE
Autocorrect return type of `initialize` to void

### ISSUE THREAD

**Issue by dbalatero** [sorbet/sorbet#2929]
### Problem

When making a constructor, Sorbet wants you to explicitly mark the return type as `void`:

```ruby
class Foo
  sig do
    params(x: Integer)
    .void # errors without this line
  end
  def initialize(x)
    @x = x
  end
end
```

All constructors should be `void` until the end of time, unless there's a dark corner of Ruby I've missed (which is totally possible!).

### Proposed solution

We should just automatically set the `void` return type on all constructors!

**Comment by jez** [comment]
The very first design principle of Sorbet, in the README:

> 1.  Explicit
>
>     We're willing to write annotations, and in fact see them as beneficial; they make code more readable and predictable. We're here to help readers as much as writers.

If all `initialize` are `void`, then we benefit from being explicit about that every time.

Happy to introduce an error with an autocorrect when someone has forgotten to put a `void` on the constructor of initialize, but I'd be hesitant to make this special case for little apparent value (consider: it becomes harder inside sorbet to say that all `sig`s have a consistent shape).

**Comment by dbalatero** [comment]
> If all initialize are void, then we benefit from being explicit about that every time.

I agree with the premise of the design principle. I don't know if anyone ever thinks about the return type of constructors though, nor should they – there aren't any real "gotchas" here.

> Happy to introduce an error with an autocorrect when someone has forgotten to put a void on the constructor of initialize

This definitely seems useful!

> (consider: it becomes harder inside sorbet to say that all sigs have a consistent shape).

Sounds good.

How about the autocorrect then?

**Comment by jez** [comment]
> How about the autocorrect then?

Works for me. PR's welcome, but since it's not blocking something else we can't prioritize it right now.
