### ISSUE TITLE
Passing optional keyword arguments can hide missing positional arguments error.

### ISSUE THREAD

**Issue by ric2b** [sorbet/sorbet#2935]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Asig%20%7B%20params(key%3A%20Symbol%2C%20value%3A%20T.untyped%2C%20option1%3A%20T%3A%3ABoolean).void%20%7D%0Adef%20set(key%2C%20value%2C%20option1%3A%20false)%0Aend%0A%0Aset(%3Asome_key%2C%20option1%3A%20false)%0A)

```ruby
# typed: true

sig { params(key: Symbol, value: T.untyped, option1: T::Boolean).void }
def set(key, value, option1: false)
end

set(:some_key, option1: false)
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

Sorbet should statically be able to tell that there's a missing positional argument, `value`.

I would expect the output to be similar to when I call the method without the keyword arguments:

```ruby
set(:some_key)
```

```
editor.rb:7: Not enough arguments provided for method Object#set. Expected: 2, got: 1 https://srb.help/7004
     7 |set(:some_key)
        ^^^^^^^^^^^^^^
    editor.rb:4: Object#set defined here
     4 |def set(key, value, option1: false)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

- - -

I know that this is related to how (pre-3.0) Ruby handles keyword arguments, passing them as an additional hash parameter that can be confused with a positional parameter, but it seems to me that Sorbet has enough information to detect the error: it can match the keyword argument names from the sig to the method call.

**Comment by jez** [comment]
There's not much Sorbet can do here. It's modeling what happens at runtime correctly:

```

❯ cat foo.rb
def set(key, value, option1: false)
  p key
  p value
  p option1
end

set(:some_key, option1: false)

❯ ruby foo.rb
:some_key
{:option1=>false}
false
```

The solution here is to not use `T.untyped`, in which case if `value` isn't allowed to be a hash, then Sorbet will flag an error as you expected.

**Comment by ric2b** [comment]
I see it as an opportunity to catch simple errors and this behavior is deprecated as of ruby 2.7 anyway:

```
❯ cat foo.rb
def set(key, value, option1: false)
  p key
  p value
  p option1
end

set(:some_key, option1: false)

❯ ruby foo.rb
foo.rb:7: warning: Passing the keyword argument as the last hash parameter is deprecated
foo.rb:1: warning: The called method `set' is defined here
:some_key
{:option1=>false}
false
```

But I understand if you disagree or this is not considered important. Thank you for Sorbet, it's a great project! :)

**Comment by amomchilov** [comment]
For future readers, this can now be caught using the `--experimental-ruby3-keyword-args` setting.

Be warned, it's still considered experimental (#6224)
