### ISSUE TITLE
type members on modules accept invalid overrides

### ISSUE THREAD

**Issue by danwang** [sorbet/sorbet#2947]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20Fooable%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20extend%20T%3A%3AGeneric%0A%20%20U%20%3D%20type_member%0A%0A%20%20sig%20%7Babstract.returns(U)%7D%0A%20%20def%20foo%3B%20end%0A%0A%20%20sig%20%7Babstract.params(u%3A%20U).void%7D%0A%20%20def%20bar(u)%3B%20end%0Aend%0A%0Aclass%20A%0A%20%20extend%20T%3A%3AGeneric%0A%20%20include%20Fooable%0A%0A%20%20U%20%3D%20type_member(upper%3A%20Integer)%0A%0A%20%20%23%20Returns%20String%20instead%20of%20U%0A%20%20sig%20%7Boverride.returns(String)%7D%0A%20%20def%20foo%3B%20%270%27%3B%20end%0A%0A%20%20%23%20Accepts%20String%20instead%20of%20U%0A%20%20sig%20%7Boverride.params(u%3A%20String).void%7D%0A%20%20def%20bar(u)%3B%20end%0Aend)

```ruby
# typed: true

module Fooable
  extend T::Helpers
  interface!

  extend T::Generic
  U = type_member

  sig {abstract.returns(U)}
  def foo; end

  sig {abstract.params(u: U).void}
  def bar(u); end
end

class A
  extend T::Generic
  include Fooable

  U = type_member(upper: Integer)

  # Returns String instead of U
  sig {override.returns(String)}
  def foo; '0'; end

  # Accepts String instead of U
  sig {override.params(u: String).void}
  def bar(u); end
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

I would expect Sorbet to tell me that the class has invalid signatures for `foo` and `bar` because they don't match the overridden methods on `Fooable`

**Comment by jez** [comment]
Another test case—this reproduces without even needing the `upper:` constraint on the type_member:

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20IFoo%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20abstract!%0A%0A%20%20X%20%3D%20type_member%0A%0A%20%20sig%20%7Babstract.returns%28X%29%7D%0A%20%20def%20foo%3B%20end%0Aend%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3AGeneric%0A%20%20%0A%20%20extend%20IFoo%0A%0A%20%20X%20%3D%20type_template%0A%0A%20%20sig%20%7Boverride.returns%28Integer%29%7D%0A%20%20def%20self.foo%3B%200%3B%20end%0Aend)

```ruby
# typed: true

module IFoo
  extend T::Sig
  extend T::Helpers
  extend T::Generic

  abstract!

  X = type_member

  sig {abstract.returns(X)}
  def foo; end
end

class Foo
  extend T::Sig
  extend T::Helpers
  extend T::Generic
  
  extend IFoo

  X = type_template

  sig {override.returns(Integer)}
  def self.foo; 0; end
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

The type `Integer` is not compatible with `IFoo::X`, so the definition of `Foo.foo` is an invalid override.

**Comment by jez** [comment]
Here are some more test cases:

[→ reference example on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20IFoo%3B%20end%0Amodule%20U%3B%20end%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20abstract!%0A%0A%20%20sig%20%7Babstract.returns%28IFoo%29%7D%0A%20%20def%20example_returns_1%3B%20end%0A%20%20sig%20%7Babstract.returns%28IFoo%29%7D%0A%20%20def%20example_returns_2%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28x%3A%20IFoo%29.void%7D%0A%20%20def%20example_params_1%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20IFoo%29.void%7D%0A%20%20def%20example_params_2%28x%29%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28blk%3A%20T.proc.params%28x%3A%20IFoo%29.void%29.void%7D%0A%20%20def%20example_proc_1%28%26blk%29%3B%20end%0A%20%20sig%20%7Babstract.params%28blk%3A%20T.proc.params%28x%3A%20IFoo%29.void%29.void%7D%0A%20%20def%20example_proc_2%28%26blk%29%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28x%3A%20T.all%28IFoo%2C%20Kernel%29%29.void%7D%0A%20%20def%20example_params_all_1%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20T.all%28IFoo%2C%20Kernel%29%29.void%7D%0A%20%20def%20example_params_all_2%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20T.all%28IFoo%2C%20Kernel%29%29.void%7D%0A%20%20def%20example_params_all_3%28x%29%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28x%3A%20U%29.void%7D%0A%20%20def%20example_type_param_1%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20U%29.void%7D%0A%20%20def%20example_type_param_2%28x%29%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28x%3A%20Kernel%29.void%7D%0A%20%20def%20example_type_param_child_1%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20Kernel%29.void%7D%0A%20%20def%20example_type_param_child_2%28x%29%3B%20end%0Aend%0A%0Aclass%20Child%20%3C%20Parent%0A%20%20sig%20%7Boverride.returns%28T.nilable%28IFoo%29%29%7D%0A%20%20def%20example_returns_1%3B%20end%0A%20%20sig%20%7Boverride.returns%28T.all%28IFoo%2C%20Kernel%29%29%7D%0A%20%20def%20example_returns_2%3B%20raise%3B%20end%0A%0A%20%20sig%20%7Boverride.params%28x%3A%20T.nilable%28IFoo%29%29.void%7D%0A%20%20def%20example_params_1%28x%29%3B%20end%0A%20%20sig%20%7Boverride.params%28x%3A%20T.all%28IFoo%2C%20Kernel%29%29.void%7D%0A%20%20def%20example_params_2%28x%29%3B%20end%0A%0A%20%20%23%20it%20looks%20like%20this%20maybe%20be%20broken%20independently%20of%20generics%3F%0A%20%20%23%20https%3A%2F%2Fgithub.com%2Fsorbet%2Fsorbet%2Fissues%2F6009%0A%20%20sig%20%7Boverride.params%28blk%3A%20T.proc.params%28x%3A%20T.nilable%28IFoo%29%29.void%29.void%7D%0A%20%20def%20example_proc_1%28%26blk%29%3B%20end%0A%20%20sig%20%7Boverride.params%28blk%3A%20T.proc.params%28x%3A%20T.all%28IFoo%2C%20Kernel%29%29.void%29.void%7D%0A%20%20def%20example_proc_2%28%26blk%29%3B%20end%0A%0A%20%20sig%20%7Boverride.params%28x%3A%20IFoo%29.void%7D%0A%20%20def%20example_params_all_1%28x%29%3B%20end%0A%20%20sig%20%7Boverride.params%28x%3A%20Kernel%29.void%7D%0A%20%20def%20example_params_all_2%28x%29%3B%20end%0A%20%20sig%20%7Boverride.params%28x%3A%20Integer%29.void%7D%0A%20%20def%20example_params_all_3%28x%29%3B%20end%0A%0A%20%20sig%20%7Boverride.params%28x%3A%20T.any%28U%2C%20Integer%29%29.void%7D%0A%20%20def%20example_type_param_1%28x%29%3B%20end%0A%20%20sig%20%7Boverride.params%28x%3A%20Integer%29.void%7D%0A%20%20def%20example_type_param_2%28x%29%3B%20end%0A%0A%20%20sig%20%7Boverride.params%28x%3A%20T.any%28Kernel%2C%20U%29%29.void%7D%0A%20%20def%20example_type_param_child_1%28x%29%3B%20end%0A%20%20sig%20%7Boverride.params%28x%3A%20T.all%28Kernel%2C%20U%29%29.void%7D%0A%20%20def%20example_type_param_child_2%28x%29%3B%20end%0Aend)

[→ failing behavior on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20abstract!%0A%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7Babstract.returns%28Elem%29%7D%0A%20%20def%20example_returns_1%3B%20end%0A%20%20sig%20%7Babstract.returns%28Elem%29%7D%0A%20%20def%20example_returns_2%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28x%3A%20Elem%29.void%7D%0A%20%20def%20example_params_1%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20Elem%29.void%7D%0A%20%20def%20example_params_2%28x%29%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28blk%3A%20T.proc.params%28x%3A%20Elem%29.void%29.void%7D%0A%20%20def%20example_proc_1%28%26blk%29%3B%20end%0A%20%20sig%20%7Babstract.params%28blk%3A%20T.proc.params%28x%3A%20Elem%29.void%29.void%7D%0A%20%20def%20example_proc_2%28%26blk%29%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28x%3A%20T.all%28Elem%2C%20Kernel%29%29.void%7D%0A%20%20def%20example_params_all_1%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20T.all%28Elem%2C%20Kernel%29%29.void%7D%0A%20%20def%20example_params_all_2%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20T.all%28Elem%2C%20Kernel%29%29.void%7D%0A%20%20def%20example_params_all_3%28x%29%3B%20end%0A%0A%20%20sig%20%7Babstract.type_parameters%28%3AU%29.params%28x%3A%20T.type_parameter%28%3AU%29%29.void%7D%0A%20%20def%20example_type_param_1%28x%29%3B%20end%0A%20%20sig%20%7Babstract.type_parameters%28%3AU%29.params%28x%3A%20T.type_parameter%28%3AU%29%29.void%7D%0A%20%20def%20example_type_param_2%28x%29%3B%20end%0A%0A%20%20sig%20%7Babstract.params%28x%3A%20Kernel%29.void%7D%0A%20%20def%20example_type_param_child_1%28x%29%3B%20end%0A%20%20sig%20%7Babstract.params%28x%3A%20Kernel%29.void%7D%0A%20%20def%20example_type_param_child_2%28x%29%3B%20end%0Aend%0A%0Aclass%20Child%20%3C%20Parent%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7Boverride.returns%28T.nilable%28Elem%29%29%7D%0A%20%20def%20example_returns_1%3B%20end%0A%20%20sig%20%7Boverride.returns%28T.all%28Elem%2C%20Kernel%29%29%7D%0A%20%20def%20example_returns_2%3B%20raise%3B%20end%0A%0A%20%20sig%20%7Boverride.params%28x%3A%20T.nilable%28Elem%29%29.void%7D%0A%20%20def%20example_params_1%28x%29%3B%20end%0A%20%20sig%20%7Boverride.params%28x%3A%20T.all%28Elem%2C%20Kernel%29%29.void%7D%0A%20%20def%20example_params_2%28x%29%3B%20end%0A%0A%20%20sig%20%7Boverride.params%28blk%3A%20T.proc.params%28x%3A%20T.nilable%28Elem%29%29.void%29.void%7D%0A%20%20def%20example_proc_1%28%26blk%29%3B%20end%0A%20%20sig%20%7Boverride.params%28blk%3A%20T.proc.params%28x%3A%20T.all%28Elem%2C%20Kernel%29%29.void%29.void%7D%0A%20%20def%20example_proc_2%28%26blk%29%3B%20end%0A%0A%20%20sig%20%7Boverride.params%28x%3A%20Elem%29.void%7D%0A%20%20def%20example_params_all_1%28x%29%3B%20end%0A%20%20sig%20%7Boverride.params%28x%3A%20Kernel%29.void%7D%0A%20%20def%20example_params_all_2%28x%29%3B%20end%0A%20%20sig%20%7Boverride.params%28x%3A%20Integer%29.void%7D%0A%20%20def%20example_params_all_3%28x%29%3B%20end%0A%0A%20%20sig%20%7Boverride.type_parameters%28%3AU%29.params%28x%3A%20T.any%28T.type_parameter%28%3AU%29%2C%20Integer%29%29.void%7D%0A%20%20def%20example_type_param_1%28x%29%3B%20end%0A%20%20sig%20%7Boverride.type_parameters%28%3AU%29.params%28x%3A%20Integer%29.void%7D%0A%20%20def%20example_type_param_2%28x%29%3B%20end%0A%0A%20%20sig%20%7Boverride.type_parameters%28%3AU%29.params%28x%3A%20T.any%28Kernel%2C%20T.type_parameter%28%3AU%29%29%29.void%7D%0A%20%20def%20example_type_param_child_1%28x%29%3B%20end%0A%20%20sig%20%7Boverride.type_parameters%28%3AU%29.params%28x%3A%20T.all%28Kernel%2C%20T.type_parameter%28%3AU%29%29%29.void%7D%0A%20%20def%20example_type_param_child_2%28x%29%3B%20end%0Aend)

**Comment by jez** [comment]
Another example:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20IFoo%3B%20end%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20do%0A%20%20%20%20overridable%0A%20%20%20%20%20%20.type_parameters%28%3AU%29%0A%20%20%20%20%20%20.params%28x%3A%20T.type_parameter%28%3AU%29%29%0A%20%20%20%20%20%20.returns%28T.type_parameter%28%3AU%29%29%0A%20%20end%0A%20%20def%20id%28x%29%3B%20x%3B%20end%0Aend%0A%0Aclass%20ChildGood%20%3C%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20do%0A%20%20%20%20override%0A%20%20%20%20%20%20.type_parameters%28%3AV%29%0A%20%20%20%20%20%20.params%28x%3A%20T.nilable%28T.type_parameter%28%3AV%29%29%29%0A%20%20%20%20%20%20.returns%28T.all%28T.type_parameter%28%3AV%29%2C%20IFoo%29%29%0A%20%20end%0A%20%20def%20id%28x%29%0A%20%20%20%20case%20x%0A%20%20%20%20when%20nil%20then%20raise%0A%20%20%20%20when%20IFoo%20then%20x%0A%20%20%20%20else%20raise%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Aclass%20ChildBad%20%3C%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20do%0A%20%20%20%20override%0A%20%20%20%20%20%20.type_parameters%28%3AW%29%0A%20%20%20%20%20%20.params%28x%3A%20T.all%28T.type_parameter%28%3AW%29%2C%20IFoo%29%29%0A%20%20%20%20%20%20.returns%28T.nilable%28T.type_parameter%28%3AW%29%29%29%0A%20%20end%0A%20%20def%20id%28x%29%3B%20x%3B%20end%0Aend)

```ruby
# typed: true

module IFoo; end

class Parent
  extend T::Sig
  sig do
    overridable
      .type_parameters(:U)
      .params(x: T.type_parameter(:U))
      .returns(T.type_parameter(:U))
  end
  def id(x); x; end
end

class ChildGood < Parent
  extend T::Sig
  sig do
    override
      .type_parameters(:V)
      .params(x: T.nilable(T.type_parameter(:V)))
      .returns(T.all(T.type_parameter(:V), IFoo))
  end
  def id(x)
    case x
    when nil then raise
    when IFoo then x
    else raise
    end
  end
end

class ChildBad < Parent
  extend T::Sig
  sig do
    override
      .type_parameters(:W)
      .params(x: T.all(T.type_parameter(:W), IFoo))
      .returns(T.nilable(T.type_parameter(:W)))
  end
  def id(x); x; end
end
```

#### Observed output

```
No errors! Great job.
```



#### Expected behavior

`ChildGood` should be accepted, `ChildBad` should be rejected (both for the bad arg, and for the bad return).
