### ISSUE TITLE
Type checking fails on multi-line method chains when the method name matches a keyword name and the dot position is end of line

### ISSUE THREAD

**Issue by wfarr** [sorbet/sorbet#2957]
#### Input

[→ View on sorbet.run](https://sorbet.run/#class%20Array%0A%20%20%23%20edge-case%20method%20name%0A%20%20def%20and(e)%0A%20%20%20%20self%20%3C%3C%20e%0A%20%20end%0A%0A%20%20%23%20another%20method%20name%0A%20%20def%20foo(e)%0A%20%20%20%20self%20%3C%3C%20e%0A%20%20end%0Aend%0A%0A%23%20this%20works%0A%221%2C2%2C3%22.split(%22%2C%22).foo(%224%22)%0A%0A%23%20this%20works%0A%221%2C2%2C3%22.split(%22%2C%22)%0A%20%20.foo(%224%22)%0A%0A%23%20this%20works%0A%221%2C2%2C3%22.split(%22%2C%22).%0A%20%20foo(%224%22)%0A%0A%23%20this%20works%0A%221%2C2%2C3%22.split(%22%2C%22).and(%224%22)%0A%0A%23%20this%20works%0A%221%2C2%2C3%22.split(%22%2C%22)%0A%20%20.and(%224%22)%0A%0A%23%20this%20does%20NOT%20work%0A%221%2C2%2C3%22.split(%22%2C%22).%0A%20%20and(%224%22)%0A%0A)

``` ruby
class Array
  # edge-case method name
  def and(e)
    self << e
  end

  # another method name
  def foo(e)
    self << e
  end
end

# this works
"1,2,3".split(",").foo("4")

# this works
"1,2,3".split(",")
  .foo("4")

# this works
"1,2,3".split(",").
  foo("4")

# this works
"1,2,3".split(",").and("4")

# this works
"1,2,3".split(",")
  .and("4")

# this does NOT work
"1,2,3".split(",").
  and("4")
```

#### Observed output

```
editor.rb:33: unexpected token kAND https://srb.help/2001
    33 |  and("4")
          ^^^
Errors: 1
```

#### Expected behavior

Should not fail type checking with a parse error.

- - -

The above code example passes `ruby -c` on Ruby 2.6.x, but fails in type checking with Sorbet. It appears to be related specifically to the method in the chain being a keyword. in this case `and` (though it also reproduces for `ensure`, `or`, etc.).

Interestingly, this particular layout also appears to confuse the syntax highlighting GitHub uses.

I encountered this initially in the wild with Sequel, where they define the following method, used for query chaining:

``` ruby
module Sequel
  class Dataset
    # Alias for where.
    def and(*cond, &block)
      where(*cond, &block)
    end
  end
end
```

**Comment by DarkDimius** [comment]
This is an intentional change that was done because it leads to much better experience with autocomplete in IDE. You can read more about motivation behind this deviation in https://github.com/sorbet/sorbet/pull/1993
Workaround is to put `.` on prior line, as you discovered.

**Comment by wfarr** [comment]
Ah, that's disappointing to hear.

Thank you for the quick response.
