### ISSUE TITLE
Abstract methods example in docs errors

### ISSUE THREAD

**Issue by michaelmcchen** [sorbet/sorbet#2965]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23typed%3A%20strong%0Amodule%20Runnable%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20(1)%0A%20%20interface!%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20(2)%0A%0A%20%20sig%20%7Babstract.params(args%3A%20T%3A%3AArray%5BString%5D).void%7D%20%20%20%23%20(3)%0A%20%20def%20main(args)%3B%20end%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20(4)%0Aend)

```
#typed: strong
module Runnable
  extend T::Sig
  extend T::Helpers                                    # (1)
  interface!                                           # (2)

  sig {abstract.params(args: T::Array[String]).void}   # (3)
  def main(args); end                                  # (4)
end
```

#### Observed output

```
editor.rb:8: This code is untyped https://srb.help/7018
     8 |  def main(args); end                                  # (4)
          ^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

The [docs](https://sorbet.org/docs/abstract#creating-an-abstract-method) state that this is the expected manner to define an interface, but it seems to error out when using `typed: strong`.

Is this a considered to be a bug, or has the expected behavior changed (and the docs are just simply out of date)?  

- - -

**Comment by jez** [comment]
Duplicate of #3410 

strong is not generally supported and is provided merely as a curiosity.
