### ISSUE TITLE
Ability to cast a value at runtime but not statically

### ISSUE THREAD

**Issue by kbacha** [sorbet/sorbet#2989]
### Problem

We'd like to provide an API for a user of our gem to declare a type as part of a structure or api. Such as declaring the return value of some arbitrary execution.

This type would be returned as a value and then used to assert that the return value of one of it's abstract methods is valid. Currently, this fails because using `T.case(value, return_type)` errors if the `return_type` is not a type literal (such as `Class` or `T::Boolean`). This is a static error as the code it self properly asserts the runtime values. The below example is contrived to demonstrate the use-case.

```ruby
class Step < T::Struct
  prop :result, T.untyped
  prop :action, Action
end

class Action
  extend T::Helpers
  extend T::Sig

  abstract!

  sig { abstract.returns(T.untyped) }
  def perform; end
 
  sig { abstract.returns(T.any(Class, T::Type::Base)) }
  def return_type; end
end

class MyBooleanAction < Action
  def perform
    true
  end

  def return_type
    T::Boolean
  end
end

class MyStringAction < Action
  def perform
    "string"
  end

  def return_type
    String
  end
end

def MyBrokenAction < Action
  def perform
    123
  end

  def return_type
    String
  end
end

class Executor
  extend T::Sig
  sig { params(steps: T::Array[Step]).void }
  def execute(action)
    steps.each do |step|
      step.result = T.cast(action.perform, action.result_type)
  end
end

# This should raise a type error on the last action.
Executor.new.execute([MyBooleanAction.new, MyStringAction.new, MyBrokenAction.new])
```

[It does *not* pass the type checker](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Step%20%3C%20T%3A%3AStruct%0A%20%20prop%20%3Aresult%2C%20T.untyped%0A%20%20prop%20%3Aaction%2C%20Action%0Aend%0A%0Aclass%20Action%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.returns(T.untyped)%20%7D%0A%20%20def%20perform%0A%20%20end%0A%20%0A%20%20sig%20%7B%20abstract.returns(T.any(Class%2C%20T%3A%3AType%3A%3ABase))%20%7D%0A%20%20def%20return_type%0A%20%20end%0Aend%0A%0Aclass%20MyBooleanAction%20%3C%20Action%0A%20%20def%20perform%0A%20%20%20%20true%0A%20%20end%0A%0A%20%20def%20return_type%0A%20%20%20%20T%3A%3ABoolean%0A%20%20end%0Aend%0A%0Aclass%20MyStringAction%20%3C%20Action%0A%20%20def%20perform%0A%20%20%20%20%22string%22%0A%20%20end%0A%0A%20%20def%20return_type%0A%20%20%20%20String%0A%20%20end%0Aend%0A%0Aclass%20MyBrokenAction%20%3C%20Action%0A%20%20def%20perform%0A%20%20%20%20123%0A%20%20end%0A%0A%20%20def%20return_type%0A%20%20%20%20String%0A%20%20end%0Aend%0A%0Aclass%20Executor%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20params(steps%3A%20T%3A%3AArray%5BStep%5D).void%20%7D%0A%20%20def%20execute(action)%0A%20%20%20%20steps.each%20do%20%7Cstep%7C%0A%20%20%20%20%20%20step.result%20%3D%20T.cast(action.perform%2C%20action.result_type)%0A%20%20end%0Aend%0A%0A%23%20This%20should%20raise%20a%20type%20error%20on%20the%20last%20action.%0AExecutor.new.execute(%5BMyBooleanAction.new%2C%20MyStringAction.new%2C%20MyBrokenAction.new%5D))

### Workaround solution

To use `cast` without needing the static type checker, we have created a file:

```ruby
# typed: ignore
module Utils::Unsafe
  def self.cast(value, type)
    T.cast(value, type)
  end
end
```

We load this module in a "clever" way:

```ruby
# typed: true
module Utils
  module Unsafe
  end

  def self.unsafe
    T.unsafe(Unsafe)
  end
end
```

This returns a type erased module that can then have `cast` called on it without issue.

### Proposed solution

Provide either a new runtime-only type assertion method. Here are some ways it could work:

#### A new function
```
value = T.assert(value, type)
```

#### A "check" function that returns boolean
```
T.is_a?(value, type)
T.is_type?(value, type)
```

#### A kwarg for cast similar to `checked`

```
value = T.cast(value, type, static: false)
```

**Comment by jez** [comment]
We're not interested (at this time) in features that let people treat types as values and process them.

The fact that there happens to be a `T::Types::Base` class for all runtime types is an implementation detail of sorbet-runtime that leaks.

Thanks for taking the time to this up, and sorry I couldn't answer differently.
