### ISSUE TITLE
Abstract methods cause `This code is untyped` errors with `typed: strong`

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#2999]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strong%0A%0Amodule%20Foo%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20interface!%0A%0A%20%20sig%20%7B%20abstract.returns(String)%20%7D%0A%20%20def%20bar%3B%20end%0Aend)

```ruby
# typed: strong

module Foo
  extend T::Helpers
  extend T::Sig

  interface!

  sig { abstract.returns(String) }
  def bar; end
end
```

#### Observed output

```
editor.rb:10: This code is untyped https://srb.help/7018
    10 |  def bar; end
          ^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

This code should not create an error.

- - -

This was introduced in `d53818d77599c62746d4cec4f89f993f92e13d63` by #2950.

Reported by @paracycle.

**Comment by elliottt** [comment]
I've updated the language about [`# typed: strong`](https://sorbet.org/docs/static#typed-strong) on sorbet.org, but the summary is that we've considered it to be unstable for some time. It can be hard to avoid introducing intermediate `T.untyped` values in the rewrite phases, so for that reason I'd suggest using `# typed: strict` instead.

**Comment by paracycle** [comment]
@elliottt Agreed, that makes total sense. However, I think we should also make `# typed: strong` not be a suggested strictness level by Sorbet tools, in that case. Otherwise, any changes in Sorbet ends up needing a strictness level change for files that used to be fine.

**Comment by paracycle** [comment]
And I just saw the PR from you that does exactly that: https://github.com/sorbet/sorbet/pull/3020 Thanks!

**Comment by paracycle** [comment]
I guess we can close this issue now, since there isn't anything actionable here.
