### ISSUE TITLE
Calls to functions taking blocks with generic arguments do not typecheck

### ISSUE THREAD

**Issue by jmikkola-stripe** [sorbet/sorbet#3053]
### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Asig%20do%0A%20%20type_parameters(%3AX)%0A%20%20.params(%0A%20%20%20%20items%3A%20T%3A%3AArray%5BT.type_parameter(%3AX)%5D%2C%0A%20%20%20%20blk%3A%20T.proc.params(x%3A%20T.type_parameter(%3AX)).void%2C%0A%20%20)%0A%20%20.void%0Aend%0Adef%20my_each(items%2C%20%26blk)%0A%20%20next_item%20%3D%20items%5B0%5D%0A%20%20return%20if%20next_item.nil%3F%0A%0A%20%20blk.call(next_item)%0A%0A%20%20my_each(items.drop(0)%2C%20%26blk)%0Aend)

```ruby
# typed: true

sig do
  type_parameters(:X)
  .params(
    items: T::Array[T.type_parameter(:X)],
    blk: T.proc.params(x: T.type_parameter(:X)).void,
  )
  .void
end
def my_each(items, &blk)
  next_item = items[0]
  return if next_item.nil?

  blk.call(next_item)

  my_each(items.drop(0), &blk)
end
```

### Observed output

```
editor.rb:17: Expected T.proc.params(arg0: <any>).void but found T.proc.params(arg0: Object#my_each#X).void for block argument https://srb.help/7002
    17 |  my_each(items.drop(0), &blk)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:7: Method Object#my_each has specified blk as T.proc.params(arg0: <any>).void
     7 |    blk: T.proc.params(x: T.type_parameter(:X)).void,
            ^^^
Errors: 1
```

### Expected behavior

It seems like it ought to be able to typecheck.

**Comment by jmikkola-stripe** [comment]
This is not limited to recursive calls.

See [this example](https://sorbet.run/#%23%20typed%3A%20true%0A%0Asig%20do%0A%20%20type_parameters(%3AX)%0A%20%20.params(%0A%20%20%20%20items%3A%20T%3A%3AArray%5BT.type_parameter(%3AX)%5D%2C%0A%20%20%20%20blk%3A%20T.proc.params(x%3A%20T.type_parameter(%3AX)).void%2C%0A%20%20)%0A%20%20.void%0Aend%0Adef%20my_each(items%2C%20%26blk)%0A%20%20T.reveal_type(blk)%0A%20%20next_item%20%3D%20items%5B0%5D%0A%20%20return%20if%20next_item.nil%3F%0A%0A%20%20blk.call(next_item)%0A%0A%20%20%23my_each(items.drop(0)%2C%20%26blk)%0Aend%0A%0Asig%20do%0A%20%20type_parameters(%3AX)%0A%20%20.params(%0A%20%20%20%20blk%3A%20T.proc.params(x%3A%20T.type_parameter(%3AX)).void%0A%20%20)%0A%20%20.void%0Aend%0Adef%20foo(%26blk)%0A%20%20T.reveal_type(blk)%0A%20%20my_each%20%5B%5D%2C%20%26blk%0Aend%20)

```ruby
# typed: true

sig do
  type_parameters(:X)
  .params(
    items: T::Array[T.type_parameter(:X)],
    blk: T.proc.params(x: T.type_parameter(:X)).void,
  )
  .void
end
def my_each(items, &blk)
  T.reveal_type(blk)
  next_item = items[0]
  return if next_item.nil?

  blk.call(next_item)

  #my_each(items.drop(0), &blk)
end

sig do
  type_parameters(:X)
  .params(
    blk: T.proc.params(x: T.type_parameter(:X)).void
  )
  .void
end
def foo(&blk)
  T.reveal_type(blk)
  my_each [], &blk
end 
```

output:

```

# typed: true

sig do
  type_parameters(:X)
  .params(
    items: T::Array[T.type_parameter(:X)],
    blk: T.proc.params(x: T.type_parameter(:X)).void,
  )
  .void
end
…end 
editor.rb:12: Revealed type: T.proc.params(arg0: Object#my_each#X).void https://srb.help/7014
    12 |  T.reveal_type(blk)
          ^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:11:
    11 |def my_each(items, &blk)
                            ^^^

editor.rb:29: Revealed type: T.proc.params(arg0: Object#foo#X).void https://srb.help/7014
    29 |  T.reveal_type(blk)
          ^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:28:
    28 |def foo(&blk)
                 ^^^

editor.rb:30: Expected T.proc.params(arg0: <any>).void but found T.proc.params(arg0: Object#foo#X).void for block argument https://srb.help/7002
    30 |  my_each [], &blk
          ^^^^^^^^^^^^^^^^
    editor.rb:7: Method Object#my_each has specified blk as T.proc.params(arg0: <any>).void
     7 |    blk: T.proc.params(x: T.type_parameter(:X)).void,
            ^^^
Errors: 3
```

**Comment by jmikkola-stripe** [comment]
[Better example](https://sorbet.run/#%23%20typed%3A%20true%0A%0Asig%20do%0A%20%20type_parameters(%3AX)%0A%20%20.params(blk%3A%20T.proc.params(x%3A%20T.type_parameter(%3AX)).void)%0A%20%20.void%0Aend%0Adef%20takes_generic_block(%26blk)%3B%20end%0A%0Asig%20do%0A%20%20type_parameters(%3AX)%0A%20%20.params(blk%3A%20T.proc.params(x%3A%20T.type_parameter(%3AX)).void)%0A%20%20.void%0Aend%0Adef%20passes_along_generic_block(%26blk)%0A%20%20takes_generic_block(%26blk)%0Aend)

```ruby
# typed: true

sig do
  type_parameters(:X)
  .params(blk: T.proc.params(x: T.type_parameter(:X)).void)
  .void
end
def takes_generic_block(&blk); end

sig do
  type_parameters(:X)
  .params(blk: T.proc.params(x: T.type_parameter(:X)).void)
  .void
end
def passes_along_generic_block(&blk)
  takes_generic_block(&blk)
end
```

output:

```ruby

# typed: true

sig do
  type_parameters(:X)
  .params(blk: T.proc.params(x: T.type_parameter(:X)).void)
  .void
end
def takes_generic_block(&blk); end

sig do
  type_parameters(:X)
  .params(blk: T.proc.params(x: T.type_parameter(:X)).void)
  .void
end
def passes_along_generic_block(&blk)
  takes_generic_block(&blk)
end
editor.rb:16: Expected T.proc.params(arg0: <any>).void but found T.proc.params(arg0: Object#passes_along_generic_block#X).void for block argument https://srb.help/7002
    16 |  takes_generic_block(&blk)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:5: Method Object#takes_generic_block has specified blk as T.proc.params(arg0: <any>).void
     5 |  .params(blk: T.proc.params(x: T.type_parameter(:X)).void)
                  ^^^
Errors: 1
```

**Comment by jacobobq** [comment]
I think this is a similar case but with the generic on the return type of the block instead.

[Sorbet.run example](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Box%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7Bparams%28x%3A%20Elem%29.void%7D%0A%20%20def%20initialize%28x%29%0A%20%20%20%20%40x%3Dx%0A%20%20end%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters%28%3AU%29%0A%20%20%20%20.params%28%0A%20%20%20%20%20%20blk%3A%20T.proc.params%28arg0%3A%20Elem%29.returns%28Box%5BT.type_parameter%28%3AU%29%5D%29%2C%0A%20%20%20%20%29%0A%20%20%20%20.returns%28Box%5BT.type_parameter%28%3AU%29%5D%29%0A%20%20end%0A%20%20def%20bind%28%26blk%29%0A%20%20%20%20blk.call%28%40x%29%0A%20%20end%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters%28%3AU%29%0A%20%20%20%20.params%28%0A%20%20%20%20%20%20blk%3A%20T.proc.params%28arg0%3A%20Elem%29.returns%28Box%5BT.untyped%5D%29%2C%0A%20%20%20%20%29%0A%20%20%20%20.returns%28Box%5BT.untyped%5D%29%0A%20%20end%0A%20%20def%20bind_untyped%28%26blk%29%0A%20%20%20%20blk.call%28%40x%29%0A%20%20end%0Aend%0A%0ABox%5BInteger%5D.new%280%29.bind%20%7B%7Cvalue%7C%20Box.new%28value%29%20%7D%0A%0ABox%5BInteger%5D.new%280%29.bind%20%7B%7Cvalue%7C%20Box%5BInteger%5D.new%28value%29%20%7D%0A%0ABox%5BInteger%5D.new%280%29.bind_untyped%20%7B%7Cvalue%7C%20Box%5BInteger%5D.new%28value%29%20%7D%0A)
