### ISSUE TITLE
Values after `attr_accessor` return guards should not be considered `nil`

### ISSUE THREAD

**Issue by saxxi** [sorbet/sorbet#3064]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Book%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(price%3A%20T.nilable(Integer)).void%20%7D%0A%20%20def%20initialize(price%3A%20nil)%0A%20%20%20%20%40price%20%3D%20price%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T.nilable(Integer))%20%7D%0A%20%20def%20total_cost%0A%20%20%20%20return%20unless%20price%0A%0A%20%20%20%20price%20%2B%2030%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T.nilable(Integer))%20%7D%0A%20%20attr_reader%20%3Aprice%0Aend%0A%0ABook.new(price%3A%2030).total_cost%0A)

```ruby
# typed: true
class Book
  extend T::Sig

  sig { params(price: T.nilable(Integer)).void }
  def initialize(price: nil)
    @price = price
  end

  sig { returns(T.nilable(Integer)) }
  def total_cost
    return unless price

    price + 30 # <- Method + does not exist on NilClass
  end

  sig { returns(T.nilable(Integer)) }
  attr_reader :price
end

Book.new(price: 30).total_cost
```

#### Observed output

```
Method + does not exist on NilClass component of T.nilable(Integer) 
```

#### Expected behavior

I believe the compiler should report no errors.

#### Current fix

[→ View on sorbet.run](https://sorbet.run/ace/#%23%20typed%3A%20true%0Aclass%20Book%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(price%3A%20T.nilable(Integer)).void%20%7D%0A%20%20def%20initialize(price%3A%20nil)%0A%20%20%20%20%40price%20%3D%20price%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T.nilable(Integer))%20%7D%0A%20%20def%20total_cost%0A%20%20%20%20local_price%20%3D%20price%0A%20%20%20%20return%20if%20local_price.nil%3F%0A%0A%20%20%20%20local_price%20%2B%2030%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T.nilable(Integer))%20%7D%0A%20%20attr_reader%20%3Aprice%0Aend%0A%0ABook.new(price%3A%2030).total_cost%0A)

```
# typed: true
class Book
  extend T::Sig

  sig { params(price: T.nilable(Integer)).void }
  def initialize(price: nil)
    @price = price
  end

  sig { returns(T.nilable(Integer)) }
  def total_cost
    tmp_variable = price
    return if tmp_variable.nil?

    tmp_variable + 30 # no errors
  end

  sig { returns(T.nilable(Integer)) }
  attr_reader :price
end

Book.new(price: 30).total_cost
```

**Comment by jez** [comment]
Methods defined like with attr_accessor are no different to the type system than any other methood. There's more on this at https://sorbet.org/docs/why-nil . In particular, this is working as expected.
