### ISSUE TITLE
Sorbet does not detect the non-existence of the "sig" method

### ISSUE THREAD

**Issue by AlexEvanczuk** [sorbet/sorbet#3068]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20sig%20%7B%20returns(String)%7D%0A%20%20def%20bar%0A%20%20%20%20'test'%0A%20%20end%0Aend%0A%0AA.new.bar)

```ruby
# typed: strict
class A
  sig { returns(String)}
  def bar
    'test'
  end
end

A.new.bar
```

#### Observed output

```
No errors! Great job
```

#### Expected behavior

Sorbet should say:
```

editor.rb:3: Method sig does not exist on T.class_of(A) https://srb.help/7003
     3 |  sig { returns(String)}
          ^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L554: Did you mean: Kernel#send?
     554 |  def send(arg0, *arg1, &blk); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

#### Context
Context from slack:
1) https://sorbet-ruby.slack.com/archives/CJL5B3CEN/p1589999692123900
2) https://sorbet-ruby.slack.com/archives/CHN2L03NH/p1590000596388800

**Comment by jez** [comment]
#2836 introduced this regression.

**Comment by jez** [comment]
A potential solution would be to instead translate all sigs to an intrinsic like

```
sig(...) {...}

# becomes

<Magic>.sig(self, ...) {...}
```

and then to have special handling in `calls.cc` to ensure that if we ever did see such a `<Magic>.sig` call, that `sig` must be a valid method on `self` when given the same args.

**Comment by marianosimone** [comment]
This was fixed in https://github.com/sorbet/sorbet/pull/3083
