### ISSUE TITLE
Problem when using Hash class method constructor

### ISSUE THREAD

**Issue by johngun3** [sorbet/sorbet#3090]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Adef%20main%0A%20%20name_list%20%3D%20%5B'john'%2C%20'john'%2C%20'joe'%5D%0A%20%20hash%20%3D%20Hash%5Bname_list.map%20%7B%20%7Cname%7C%20%5Bname%2C%20'not_found'%5D%7D%5D%0A%20%20name_list.each%20do%20%7Cname%7C%0A%20%20%20%20hash%5Bname%5D%20%3D%20if%20hash%5Bname%5D%20%3D%3D%20'not_found'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'found'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'duplicate'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20end%0A%20%20end%0Aend)

```ruby
def main
  name_list = ['john', 'john', 'joe']
  hash = Hash[name_list.map { |name| [name, 'not_found']}]
  name_list.each do |name|
    hash[name] = if hash[name] == 'not_found'
                   'found'
                 else
                   'duplicate'
                 end
  end
end
```

#### Observed output

```
editor.rb:7: Expected String("not_found") but found String for argument arg1 https://srb.help/7002
     7 |                   'found'
                           ^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/hash.rbi#L214: Method Hash#[]= has specified arg1 as String("not_found")
     214 |        arg1: V,
                  ^^^^
  Got String originating from:
    editor.rb:7:
     7 |                   'found'
                           ^^^^^^^
    editor.rb:9:
     9 |                   'duplicate'
                           ^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

I don't think this should cause any type check errors. The values of the hash should be mutable even if key, value pairs are specified when constructing the hash.
- - -

A slightly modified version of this code, constructing the hash manually, results in the correct behavior
```ruby
def main
  name_list = ['john', 'john', 'joe']
  hash = { 'john' => 'not_found', 'joe' => 'not_found' }
  name_list.each do |name|
    hash[name] = if hash[name] == 'not_found'
                   'found'
                 else
                   'duplicate'
                 end
  end
end
```
[Sorbet run](https://sorbet.run/#%23%20typed%3A%20true%0Adef%20main%0A%20%20name_list%20%3D%20%5B'john'%2C%20'john'%2C%20'joe'%5D%0A%20%20hash%20%3D%20%7B%20'john'%20%3D%3E%20'not_found'%2C%20'joe'%20%3D%3E%20'not_found'%20%7D%0A%20%20name_list.each%20do%20%7Cname%7C%0A%20%20%20%20hash%5Bname%5D%20%3D%20if%20hash%5Bname%5D%20%3D%3D%20'not_found'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'found'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20'duplicate'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20end%0A%20%20end%0Aend)

**Comment by jez** [comment]
This was fixed in #6080
