### ISSUE TITLE
Sorbet runtime does not support limitless ranges properly

### ISSUE THREAD

**Issue by AlexEvanczuk** [sorbet/sorbet#3093]
#### Input

[→ View on sorbet.run](https://sorbet.run/#class%20Test%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20returns(T%3A%3ARange%5BT.nilable(Date)%5D)%20%7D%0A%20%20def%20range%0A%20%20%20%20Range.new(nil%2C%20nil)%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(T%3A%3ARange%5BT.nilable(Date)%5D)%20%7D%0A%20%20def%20range_1%0A%20%20%20%20Range.new(nil%2C%20Date.today)%0A%20%20end%0Aend (edited) )

```ruby
class Test
  extend T::Sig
  sig { returns(T::Range[T.nilable(Date)]) }
  def range
    Range.new(nil, nil)
  end

  sig { returns(T::Range[T.nilable(Date)]) }
  def range_1
    Range.new(nil, Date.today)
  end

  sig { returns(T::Range[T.nilable(Date)]) }
  def range_1
    Range.new(nil, nil)
  end
end
```

##### Static Output
```
No errors! Great job.
```

##### Runtime output
```
development 25> Test.new.range
RangeError: cannot get the last element of endless range
from /Users/alex.evanczuk/workspace/app/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.5585/lib/types/types/typed_enumerable.rb:127:in `last'
```

#### Expected behavior

No error when validating runtime signatures.

**Comment by jez** [comment]
Probably just a matter of editing this:

https://github.com/sorbet/sorbet/blob/ba767ec5f9eed32a18b05a295b3fd3d2d9779ad8/gems/sorbet-runtime/lib/types/types/typed_enumerable.rb#L52-L53

to check if `obj.begin` / `obj.end` is `nil` before checking `first` / `last`

**Comment by AlexEvanczuk** [comment]
I created a PR for this: https://github.com/sorbet/sorbet/pull/3094

I'll wait until tests pass before assigning it out.

The main documentation doesn't say how to run tests -- how am I able to run these tests? I want to verify locally these tests fail with the old code and pass with the new.
