### ISSUE TITLE
Missing sig error reported for `attr_accessor` with `.checked` in its sig

### ISSUE THREAD

**Issue by pb-stripe** [sorbet/sorbet#3104]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%23%20attr_accessor%20with%20.checked%20in%20the%20sig%20errors%0A%20%20sig%20%7Breturns(String).checked(%3Aalways)%7D%0A%20%20attr_accessor%20%3Astr1%0A%0A%20%20%23%20without%20the%20.checked%20it's%20fine%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20attr_accessor%20%3Astr2%0A%0A%20%20%23%20attr_reader%20with%20.checked%20is%20also%20OK%0A%20%20sig%20%7Breturns(String).checked(%3Aalways)%7D%0A%20%20attr_reader%20%3Astr3%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20initialize%0A%20%20%20%20%40str1%20%3D%20T.let(''%2C%20String)%0A%20%20%20%20%40str2%20%3D%20T.let(''%2C%20String)%0A%20%20%20%20%40str3%20%3D%20T.let(''%2C%20String)%0A%20%20end%0Aend)

```ruby
# typed: strict

class A
  extend T::Sig

  # attr_accessor with .checked in the sig errors
  sig {returns(String).checked(:always)}
  attr_accessor :str1

  # without the .checked it's fine
  sig {returns(String)}
  attr_accessor :str2

  # attr_reader with .checked is also OK
  sig {returns(String).checked(:always)}
  attr_reader :str3

  sig {void}
  def initialize
    @str1 = T.let('', String)
    @str2 = T.let('', String)
    @str3 = T.let('', String)
  end
end
```

#### Observed output

```
editor.rb:8: This function does not have a sig https://srb.help/7017
     8 |  attr_accessor :str1
          ^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

I believe this should not be an error.

- - -

**Comment by sonologico** [comment]
This just bit me and I have a fix for it. Will make a PR as soon I clean it up.
