### ISSUE TITLE
Using each_index.select results in type of element in select block incorrectly identified. 

### ISSUE THREAD

**Issue by johngun3** [sorbet/sorbet#3110]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20main%0A%20%20list%20%3D%20%5B'hello'%2C%20'bye'%5D%0A%20%20indexes%20%3D%20list.each_index.select%20%7B%20%7Ci%7C%20list%5Bi%5D%20%3D%3D%20'hello'%20%7D%0Aend)

```ruby
def main
  list = ['hello', 'bye']
  indexes = list.each_index.select { |i| list[i] == 'hello' }
end
```

#### Observed output

```
editor.rb:5: Expected T.any(Integer, Float) but found String for argument arg0 https://srb.help/7002
     5 |  indexes = list.each_index.select { |i| list[i] == 'hello' }
                                                 ^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/array.rbi#L533: Method Array#[] has specified arg0 as T.any(Integer, Float)
     533 |        arg0: T.any(Integer, Float),
                  ^^^^
  Got String originating from:
    editor.rb:5:
     5 |  indexes = list.each_index.select { |i| list[i] == 'hello' }
                                              ^
Errors: 1
```

#### Expected behavior

This should not result in a type check error. Sorbet seems to incorrectly identify the element in the select block as a string when it is actually an integer.
- - -

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbets-types-for-the-stdlib-are-wrong
