### ISSUE TITLE
Error using `T::Struct` fields in .rbi files

### ISSUE THREAD

**Issue by robertjlooby** [sorbet/sorbet#3118]
#### Input
In versions 0.5.5560 and lower, we've been able to put `T::Struct` definitions in the `.rbi` file the same as they are in the source code like

```ruby
# lib/gem_1/struct.rb
module Gem1
  class Struct < T::Struct
    const :field, String
  end
end

# rbi/gem_1.rbi
module Gem1
  class Struct < T::Struct
    const :field, String
  end
end

```

There's a full minimal example [here](https://github.com/robertjlooby/sorbet_monorepo/tree/rbi-t-struct-error)

#### Observed output

Starting in version 0.5.5563, doing this will generate an error when running `srb init` or `srb rbi update`

```
<path>/sorbet-0.5.5703/lib/hidden-definition-finder.rb:149:in `write_constants': <path>/reflection.rbi had unexpected errors. Check this file for a clue: <path>/reflection.json.err (RuntimeError)
```

The `reflection.json.err` file has

```
<path>/gem_1/rbi/gem_1.rbi:7: The instance variable `@field` must be declared inside `initialize` or declared nilable https://srb.help/5005
     7 |    const :field, String
                   ^^^^^
```

#### Expected behavior

I would expect `srb init` or `srb rbi update` to complete without error.

**Comment by DarkDimius** [comment]
Strong level of typing has a lot of known bugs. This isn't specific to `rbi`, this is spefic to `strong`.
https://sorbet.org/docs/static documents that `strong` isn't yet supported for user code.
