### ISSUE TITLE
How do I find the source location of a sorbet decorated method

### ISSUE THREAD

**Issue by leosurwiki** [sorbet/sorbet#3123]
I was trying to use `.method(:my_method).source_location` when setting up some polymorphic class logging. But since we're using sorbet, the location was showed up as `/.rvm/gems/ruby-2.6.2/gems/sorbet-runtime-0.5.5510/lib/types/private/methods/_methods.rb`.

Can sorbet help display the original `source_location` method?

**Comment by jeffcarbs** [comment]
You should be able to fix this by running the following:
```
require 'sorbet-runtime'
::Method.prepend(T::CompatibilityPatches::MethodExtensions)
```

You can see the source here: https://github.com/sorbet/sorbet/blob/master/gems/sorbet-runtime/lib/types/compatibility_patches.rb#L54-L95

**Comment by DarkDimius** [comment]
Thank you, Jeff

**Comment by serioushaircut** [comment]
mmh that patch doesn't work (anymore)?
`(Unbound)Method.prepend(T::CompatibilityPatches::MethodExtensions)` causes an infinite loop in itself :
```
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:107:in `signature_for_method'
     # sorbet-runtime-0.5.11221/lib/types/compatibility_patches.rb:94:in `parameters'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/signature.rb:39:in `initialize'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:374:in `new'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:374:in `build_sig'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:343:in `run_sig'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:243:in `block in _on_method_added'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:444:in `run_sig_block_for_key'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:424:in `maybe_run_sig_block_for_key'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:111:in `signature_for_key'
     # sorbet-runtime-0.5.11221/lib/types/private/methods/_methods.rb:107:in `signature_for_method'
     ... and again and again
```

**Comment by KaanOzkan** [comment]
You can use [T::Utils.signature_for_method](https://github.com/sorbet/sorbet/blob/666a9573da051eab46f7c81a55d580c48236e6e4/gems/sorbet-runtime/lib/types/utils.rb#L68) to access the signature and then get its method which should be the underlying method.

```ruby
m = Foo.method(:method_name) # method wrapped by sorbet-runtime
user_defined_method = T::Utils.signature_for_method(m).method # Note the method call on the return value
```

**Comment by paracycle** [comment]
> mmh that patch doesn't work (anymore)?
> `(Unbound)Method.prepend(T::CompatibilityPatches::MethodExtensions)` causes an infinite loop in itself :

Yeah, unfortunately, that patch has always caused an infinite loop, but only when prepended to `UnboundMethod`. Sorbet runtime ends up doing a `parameters` call on unbound method instances internally when you call `signature_for_method`, which causes the infinite loop.

I have an idea for how to fix it, but haven't gotten around to making a PR for it yet.
