### ISSUE TITLE
Incorrect nil detection with &&

### ISSUE THREAD

**Issue by orangethunder** [sorbet/sorbet#3148]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20%7B%20params(arr%3A%20Array).returns(T%3A%3ABoolean)%20%7D%0A%20%20def%20does_not_work%3F(arr)%0A%20%20%20%20arr%5B0%5D%20%3D%3D%201%20%26%26%20true%0A%20%20end%0A%0A%20%20sig%20%7B%20params(arr%3A%20Array).returns(T%3A%3ABoolean)%20%7D%0A%20%20def%20but_this_works%3F(arr)%0A%20%20%20%20arr%5B0%5D%20%3D%3D%201%0A%20%20end%0A%0A%20%20sig%20%7B%20params(arr%3A%20Array).returns(T%3A%3ABoolean)%20%7D%0A%20%20def%20and_this_works_too%3F(arr)%0A%20%20%20%20true%0A%20%20end%0Aend%0A%0A)

```ruby
# typed: true
class A
  extend T::Sig
  
  sig { params(arr: Array).returns(T::Boolean) }
  def does_not_work?(arr)
    arr[0] == 1 && true
  end

  sig { params(arr: Array).returns(T::Boolean) }
  def but_this_works?(arr)
    arr[0] == 1
  end

  sig { params(arr: Array).returns(T::Boolean) }
  def and_this_works_too?(arr)
    true
  end
end
```

#### Observed output

```
editor.rb:6: Returning value that does not conform to method result type https://srb.help/7005
     6 |  def does_not_work?(arr)
     7 |    arr[0] == 1 && true
     8 |  end
  Expected T::Boolean
    editor.rb:6: Method does_not_work? has return type T::Boolean
     6 |  def does_not_work?(arr)
          ^^^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(T::Boolean) originating from:
    editor.rb:7:
     7 |    arr[0] == 1 && true
            ^^^^^^^^^^^
    editor.rb:7:
     7 |    arr[0] == 1 && true
            ^^^^^^^^^^^^^^^^^^^
    editor.rb:7:
     7 |    arr[0] == 1 && true
                           ^^^^
Errors: 1
```

#### Expected behavior

Sorbet knows that `arr[0] == 1` can't be nil, and obviously it knows `true` can't be nil, but somehow, when you `&&` them together, it thinks that it can be nil. It should not think this, as applying `&&` to two operands that can't be nil will give a result that is never nil.

**Comment by DarkDimius** [comment]
```
    arr[0] == 1 && true
```
is equivalent to 
```
  temp = (arr[0] == 1)
  if temp
    return true
  else 
    return temp
  end
```

We do not know the type of `temp`(as we don't know the type of `arr[0]`). It can be `false` or `nil`. Thus, return type of this method is `T.nilable(Boolean)` as we believe all thee values `true, false, nil` can be returned.

This is expected behavior.

**Comment by orangethunder** [comment]
Hi @DarkDimius, thanks for your thoughtful reply. You might want to look at the part I posted that does work:

`
  sig { params(arr: Array).returns(T::Boolean) }
  def but_this_works?(arr)
    arr[0] == 1
  end
`
What you're telling me above is that the above method should fail typechecking, because we don't know the tyupe of `arr[0]`. But it passes. Why is the expected behaviour not occurring in this case? Surely behaviour is either expected or unexpected. It can't be both. One of these is behaving in an unexpected manner (or your explanation is incomplete).

**Comment by orangethunder** [comment]
I think I figured it out. I forgot that Sorbet is optimistic when using `typed: true`, hence `but_this_works?` passing. Changing to `typed: strict` results in behaviour that's logically consistent.
