### ISSUE TITLE
Logger::Initialize logdev parameter definition

### ISSUE THREAD

**Issue by benhayehudi** [sorbet/sorbet#3149]
Hi there,

This is my first time encountering this sort of issue with Sorbet, and if I am misunderstanding, please just let me know! :) 

It appears that Sorbet has a [definition](https://github.com/sorbet/sorbet/blob/8677db8d7933ad1b21330253cd8aa313b9f492b1/rbi/stdlib/logger.rbi#L432:) for the `logdev` parameter of `Logger` as `T.any(String, IO)`, whereas according to the [documentation for Logger](https://github.com/ruby/logger/blob/master/lib/logger.rb#L351) it accepts `nil` as well: 

```
# +logdev+::
  #   The log device.  This is a filename (String), IO object (typically
  #   +STDOUT+, +STDERR+, or an open file), +nil+ (it writes nothing) or
  #   +File::NULL+ (same as +nil+).
```

As it stands providing `nil` to `Logger.new` surfaces the following error in Sorbet:

```
Expected T.any(IO, String) but found NilClass for argument logdev https://srb.help/7002
                               ^^^^^^^^^^^^^^^^^
 https://github.com/sorbet/sorbet/tree/8677db8d7933ad1b21330253cd8aa313b9f492b1/rbi/stdlib/logger.rbi#L432: Method Logger#initialize has specified logdev as T.any(IO, String)
     432 |      logdev: T.any(String, IO),
```

If the Logger documentation is accurate, should this parameter be redefined to allow for `nil` as an argument?

Thanks for your time!

**Comment by marianosimone** [comment]
Indeed, this seems to be a problem with the `rbi` definition.

You can contribute by fixing the definition. Read more about contributing [here|https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong]

**Comment by benhayehudi** [comment]
Thanks, @marianosimone. In this case, what do you recommend the RBI gets updated with to include the possibility for `nil` to be the argument?

**Comment by marianosimone** [comment]
There are a couple of different ways to express this in sorbet. IMO, the cleanest one would be something like:

```
logdev: T.any(String, IO, NilClass)
```

Alternatively (but less clean, IMO):

```
logdev: T.nilable(T.any(String, IO))
```

I like the first one more, because it tells you that it either accepts a `String`, an `IO` object or `nil`, while the second seems to say: it accepts a nilable `String` or `IO` object.

**Comment by benhayehudi** [comment]
Thanks, that's exactly what I was trying to figure out, which way would be the preferred way. I think the first option is cleaner as well. I'll go ahead and make a PR with this. Appreciate the help!
