### ISSUE TITLE
`srb rbi gems` deletes `sorbet/rbi/gems`

### ISSUE THREAD

**Issue by endgame** [sorbet/sorbet#3166]
#### Input

Running `srb rbi gems` in a rails app.
Using ruby 2.6.0, bundler 2.1.4.
Gems seem to be installed in `$HOME/.gem/ruby/2.6.0/`

#### Observed output

`sorbet/rbi/gems` is deleted. 
Seems similar to: #2558

#### Expected behavior

Typing information on gems is updated.

- - -

By replacing the regexes at
https://github.com/sorbet/sorbet/blob/e7ca0cb2e1bcdd8b8ed69bab6f8a696520bbbca1/gems/sorbet/lib/gem-generator-tracepoint/tracepoint_serializer.rb#L218-L221

with:
```ruby
        match =
          location&.match(/^.*\/gems\/([^\/]+)-([^-\/]+)\//i) || # Hax
          location&.match(/^.*\/(ruby)\/([\d.]+)\//) || # ruby stdlib
          location&.match(/^.*\/(j?ruby)-([\d.]+)\//) || # jvm ruby stdlib
          location&.match(/^.*\/(site_ruby)\/([\d.]+)\//) || # rubygems
          location&.match(/^.*\/gems\/(?:j?ruby-)?[\d.]+(?:@[^\/]+)?(?:\/bundler)?\/gems\/([^\/]+)-([^-\/]+)\//i) # gem
```
I was able to get something that worked. It's not clear that this regex is good enough or tight enough to be added to master.

CC: @lrworth, who helped me track this down.

**Comment by praagyajoshi** [comment]
I saw the same behaviour when running `srb rbi gems`.  
One thing to note is that I recently updated the Ruby version in the project and added a new gem.
While running `srb rbi gems` I was expecting to see definitions for this new gem.
Even running `srb init` is causing the whole `sorbet/rbi/gems` directory to be deleted.

**Comment by orangethunder** [comment]
Massive +1 for this. We use bundler, and my gems are stored in `/home/my_user/gems/ProjectName/ruby/2.5.0/gems/gem_name-x.x.x`. The existing code hits the `ruby stdlib` regex, but adding the `Hax` regex above to it fixes the issue.

**Comment by lrworth** [comment]
@orangethunder Could you please try the changes here https://github.com/sorbet/sorbet/pull/3257/files? (To get more evidence that it works)

**Comment by fdr** [comment]
@lrworth wanted to let you know that I found this bug after having been bitten by it kind of continuously on this machine (I use asdf-vm and bundler on linux). I was relying on colleagues to generate rbis and never got around to digging. Your patch makes it much better.

**Comment by fsateler** [comment]
I believe the correct approach would be to use `Bundler.bundle_path` if bundler is available.

**Comment by lrworth** [comment]
https://github.com/sorbet/sorbet/pull/3257 was just merged, which ought to fix this for a few people.
