### ISSUE TITLE
Adding T.proc type definitions leads to weaker inferred types than T.untyped

### ISSUE THREAD

**Issue by samdoiron** [sorbet/sorbet#3169]
#### Input

[→ View on sorbet.run](https://sorbet.run/#extend%20T%3A%3ASig%0A%0Aclass%20Box%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Inner%20%3D%20type_member%0A%20%20sig%20%7B%20params(inner%3A%20Inner).void%20%7D%0A%20%20def%20initialize(inner)%0A%20%20%20%20%23%0A%20%20end%0Aend%0A%0Asig%20do%0A%20%20type_parameters(%3AI)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20inner%3A%20T.type_parameter(%3AI)%2C%0A%20%20%20%20%20%20my_block%3A%20T.proc.params(resource%3A%20T.type_parameter(%3AI))%0A%20%20%20%20%20%20%20%20.returns(T.type_parameter(%3AI))%0A%20%20%20%20)%0A%20%20%20%20.returns(Box%5BT.type_parameter(%3AI)%5D)%0Aend%0Adef%20make_box(inner%2C%20%26my_block)%0A%20%20Box.new(inner)%0Aend%0A%0Asig%20do%0A%20%20type_parameters(%3AI)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20inner%3A%20T.type_parameter(%3AI)%2C%0A%20%20%20%20%20%20my_block%3A%20T.untyped%0A%20%20%20%20)%0A%20%20%20%20.returns(Box%5BT.type_parameter(%3AI)%5D)%0Aend%0Adef%20make_box_unsafe(inner%2C%20%26my_block)%0A%20%20Box.new(inner)%0Aend%0A%0AT.reveal_type(make_box('hi')%20%7B%20%7Cr%7C%20r%20%7D)%20%0AT.reveal_type(make_box_unsafe('hi')%20%7B%20%7Cr%7C%20r%20%7D))

```ruby
extend T::Sig

class Box
  extend T::Sig
  extend T::Generic
  Inner = type_member
  sig { params(inner: Inner).void }
  def initialize(inner)
    #
  end
end

sig do
  type_parameters(:I)
    .params(
      inner: T.type_parameter(:I),
      my_block: T.proc.params(resource: T.type_parameter(:I))
        .returns(T.type_parameter(:I))
    )
    .returns(Box[T.type_parameter(:I)])
end
def make_box(inner, &my_block)
  Box.new(inner)
end

sig do
  type_parameters(:I)
    .params(
      inner: T.type_parameter(:I),
      my_block: T.untyped # NOTE: change here.
    )
    .returns(Box[T.type_parameter(:I)])
end
def make_box_unsafe(inner, &my_block)
  Box.new(inner)
end

T.reveal_type(make_box('hi') { |r| r }) 
T.reveal_type(make_box_unsafe('hi') { |r| r })
```

#### Observed output

```
editor.rb:38: Revealed type: Box[<any>] https://srb.help/7014
    38 |T.reveal_type(make_box('hi') { |r| r }) 
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:38:
    38 |T.reveal_type(make_box('hi') { |r| r }) 
                      ^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:39: Revealed type: Box[String("hi")] https://srb.help/7014
    39 |T.reveal_type(make_box_unsafe('hi') { |r| r })
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:39:
    39 |T.reveal_type(make_box_unsafe('hi') { |r| r })
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

Since the former (`make_box`) type definition more strictly defines the typing of the method, and is compatible with the type inferred type of `Box[String("hi")]`, I would expect both to be deduced to be the same type.

**Comment by jez** [comment]
This has been fixed in the recent improvements to Sorbet's support for generics.
