### ISSUE TITLE
Calling T.unsafe on a return value in a begin/rescue block also disables static typechecking on other return values

### ISSUE THREAD

**Issue by pb-stripe** [sorbet/sorbet#3174]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(Integer)%7D%0A%20%20def%20foo%0A%20%20%20%20begin%0A%20%20%20%20%20%20T.unsafe(5)%0A%20%20%20%20rescue%0A%20%20%20%20%20%20'wrong%20type'%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20sig%20%7Breturns(Integer)%7D%0A%20%20def%20bar%0A%20%20%20%20begin%0A%20%20%20%20%20%20'wrong%20type'%0A%20%20%20%20rescue%0A%20%20%20%20%20%20begin%0A%20%20%20%20%20%20%20%20T.unsafe(5)%0A%20%20%20%20%20%20rescue%0A%20%20%20%20%20%20%20%20'also%20wrong%20type'%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend%0A)

```ruby
# typed: strict
class A
  extend T::Sig

  sig {returns(Integer)}
  def foo
    begin
      T.unsafe(5)
    rescue
      'wrong type'
    end
  end

  sig {returns(Integer)}
  def bar
    begin
      'wrong type'
    rescue
      begin
        T.unsafe(5)
      rescue
        'also wrong type'
      end
    end
  end
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

I expected the `T.unsafe` to only apply to the expression on which it is called, and so was expecting to see errors for all the string values in the example above. Instead, it seems like the presence of `T.unsafe` caused the type checker to ignore the types of the other return values as well.

Trying the example locally, it _does_ error at runtime, as expected.

- - -

**Comment by jez** [comment]
Sorbet models all return from a function through a single exit. Another way of saying that is that Sorbet models all methods like this:

```ruby
def foo
  result = begin
    # ...
  end
  # type check result
  result
end
```

Thus, from Sorbet's perspective there's always a single return from a function.
Ultimately, this is how all variables and all components of a method work in Sorbet.
It's a sad reality of working with T.untyped that sometimes normal values will become untyped unknowningly.

That said, I don't think there's anything to be done here.
