### ISSUE TITLE
Array#+ signature is too restrictive

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#3237]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aints%20%3D%20T.let(%5B%5D%2C%20T%3A%3AArray%5BInteger%5D)%0Afloats%20%3D%20T.let(%5B%5D%2C%20T%3A%3AArray%5BFloat%5D)%0Anumbers%20%3D%20ints%20%2B%20floats)

```ruby
ints = T.let([], T::Array[Integer])
floats = T.let([], T::Array[Float])
numbers = ints + floats # unexpected error here
```

#### Observed output

```
Expected T::Enumerable[Integer] but found T::Array[Float] for argument arg0 https://srb.help/7002
```

#### Expected behavior

No errors

#### Potential solution
It seems like the problem is here:

https://github.com/sorbet/sorbet/blob/dd140356ee753b26a6a7273397bf8e3e1d93fb2e/rbi/core/array.rbi#L444-L456

`T::Enumerator[Elem]` it's too restrictive, as the addition should allow for any types.

**Comment by jez** [comment]
This one specifically is intentional. We think that it's more frequently a cause of bugs than it is intentional on the hand of the programmer. If the behavior is desirable, the recommendation  is to explicitly widen the receiver type first, like

```ruby
ints = T.let([], T::Array[T.any(Integer, Float)])
floats = T.let([], T::Array[Float])
numbers = ints + floats
```
