### ISSUE TITLE
Enumerable#detect not as specific as it could be

### ISSUE THREAD

**Issue by thegedge** [sorbet/sorbet#3240]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Asig%20%7B%20returns(String)%20%7D%0Adef%20foo%0A%20%20%5B1%2C%202%2C%203%5D.detect(-%3E%20%7B%20%22%22%20%7D)%20%7B%20%7Cx%7C%20break%20%22test%22%20if%20x%20%3D%3D%202%20%7D%0Aend)

```ruby
# typed: true

sig { returns(String) }
def foo
  [1, 2, 3].detect(-> { "" }) { |x| break "test" if x == 2 }
end
```

#### Observed output

```
editor.rb:5: Returning value that does not conform to method result type https://srb.help/7005
     5 |  [1, 2, 3].detect(-> { "" }) { |x| break "test" if x == 2 }
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Expected String
    editor.rb:4: Method foo has return type String
     4 |def foo
        ^^^^^^^
  Got T.nilable(T.any(Integer, String)) originating from:
    editor.rb:5:
     5 |  [1, 2, 3].detect(-> { "" }) { |x| break "test" if x == 2 }
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:5:
     5 |  [1, 2, 3].detect(-> { "" }) { |x| break "test" if x == 2 }
                                                  ^^^^^^

editor.rb:3: Method sig does not exist on T.class_of(<root>) https://srb.help/7003
     3 |sig { returns(String) }
        ^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:3: Method returns does not exist on T.class_of(<root>) https://srb.help/7003
     3 |sig { returns(String) }
              ^^^^^^^^^^^^^^^
Errors: 3
```

#### Expected behavior

I would expect this to typecheck successfully. Given:

```
array.inject(lambda) do
  ...
end
```

I would expect the type signature to ~be~ match the signature of `lambda`, combined with any distinct signatures from any break `variable`.

**Comment by marianosimone** [comment]
I think the problem here is that the `ifnone` block is only declared as `Proc` in the `rbi`:

https://github.com/sorbet/sorbet/blob/a73037943a7281d532f01c3cade93264e45fb3fe/rbi/core/enumerable.rbi#L376-L389

So sorbet doesn't know that it could return something different.

https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
