### ISSUE TITLE
Redundant conditional send shows misleading error message

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#3281]
Note: The examples below only show problems after https://github.com/sorbet/sorbet/pull/3277 is applied

```ruby
class Dog
  extend T::Sig
  sig {returns(String)}
  attr_reader :breed
end

module Animal
  class Cat
    extend T::Sig
    sig {returns(String)}
    attr_reader :breed
  end
end

cat_breed = Animal::Cat.new&.breed # here the unreachable code is at Animal
maybe_dog_breed_forced = T.must(maybeDog)&.breed # here the unreachable code is at T
@dog = dog
own_dog_breed = @dog&.breeed # here the unreachable code is at @
```

The problem seems to be in the desugaring step. You can see the outputs by doing something like: `bazel-bin/main/sorbet -p desugar-tree <testcase>`

**Comment by jez** [comment]
The code looks sort of like this after it's been desugared:

```ruby
# typed: true

class Dog
  extend T::Sig

  sig {returns(String)}
  def breed; 'dog'; end
end


def main
  dog = Dog.new
  str_breed = begin
    assignTemp = dog.breed
    if NilClass.===(assignTemp)
      nil
    else
      assignTemp.to_s
    end
  end
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Dog%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20def%20breed%3B%20'dog'%3B%20end%0Aend%0A%0A%0Adef%20main%0A%20%20dog%20%3D%20Dog.new%0A%20%20str_breed%20%3D%20begin%0A%20%20%20%20assignTemp%20%3D%20dog.breed%0A%20%20%20%20if%20NilClass.%3D%3D%3D(assignTemp)%0A%20%20%20%20%20%20nil%0A%20%20%20%20else%0A%20%20%20%20%20%20assignTemp.to_s%0A%20%20%20%20end%0A%20%20end%0Aend)

which shows that it's not so much that the Loc is wrong, but that there's not really a good loc to put for the `nil` that gets synthesized as a result of desugaring a CSend node.

**Comment by jez** [comment]
Arguably, the problem here is "the error message for redundant csend is bad" and the solution is "the error message for redundant csend should say 'redundant csend' and not 'unreachable code'". Because every bit of code the user wrote was reachable. It's only the synthetic part of the program that sorbet uses internally to model it that's unreachable.

**Comment by marianosimone** [comment]
This is actually a dupe of https://github.com/sorbet/sorbet/issues/36
