### ISSUE TITLE
`break` with argument on infinite loop

### ISSUE THREAD

**Issue by kddeisz** [sorbet/sorbet#3286]
#### Input

[→ View on sorbet.run](https://sorbet.run/#T.let((1..).detect%20%7B%20%7Ci%7C%20break%20'over%205'%20if%20i%20%3E%205%20%7D%2C%20String))

```ruby
T.let((1..).detect { |i| break 'over 5' if i > 5 }, String)
```

#### Observed output

```
editor.rb:1: Argument does not have asserted type String https://srb.help/7007
     1 |T.let((1..).detect { |i| break 'over 5' if i > 5 }, String)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(T.any(Integer, String)) originating from:
    editor.rb:1:
     1 |T.let((1..).detect { |i| break 'over 5' if i > 5 }, String)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:1:
     1 |T.let((1..).detect { |i| break 'over 5' if i > 5 }, String)
                                       ^^^^^^^^
Errors: 1
```

#### Expected behavior

The only type that can escape from this block is a string, since it will just continue to loop until that predicate is matched. I recognize this is probably a difficult one to tackle, but I figured I'd report it just in case.

**Comment by elliottt** [comment]
I'm not sure that we can handle this case without pretty substantial static analysis. For example, this case is only slightly different, but produces a `nil` value:

```ruby
T.let((1..4).detect { |i| break 'over 5' if i > 5 }, String)
```

We would need to have a way of knowing that the predicate in the block would eventually become true, and sorbet doesn't have the ability to reason about runtime behavior at that depth.

**Comment by kddeisz** [comment]
@elliottt Thanks for the feedback!

I wonder if there's a simpler case that could be addressed?

```ruby
[1].detect { break 'foo' }
```

That actually gives you `T.nilable(T.any(Integer, String))`, which is definitely not true.

**Comment by elliottt** [comment]
What about:

```ruby
[].detect { break 'foo' }
```

When the expression in the position of `[]` is arbitrary, I think it would require a lot of machinery to know whether or not the block would be executed.

**Comment by paracycle** [comment]
@elliottt For the case where the block is not executed, we, as programmers, know that the return value of the `detect` call would be `nil`, so if Sorbet knew that too, it could at least return the type as `T.nilable(String)`. So it is not impossible to refine the return value without doing more static analysis.

Of course, that would imply a way to tell Sorbet what methods would return if the block was executed or not, so I understand the complication.
