### ISSUE TITLE
Do not disable the mouse-hover code completion tooltip in typed: false files

### ISSUE THREAD

**Issue by almcgo-stripe** [sorbet/sorbet#3291]
If a file is `typed: false` can we show the code completion tooltip on mouse-hover and make it say something like:

`This file is typed: false, set it to 'typed: true' or better if you want code completion`

**Comment by jeffcarbs** [comment]
It would be cool if sorbet still showed the type information it knew in `typed: false` files, just did not give you any errors when running `srb tc`.

We have a large codebase where we're slowly increasing typed levels and there are times during code spelunking where I come across a file that's `typed: false` and would be non-trivial to get to `typed: true` but having type information would help understand what the code is doing.
