### ISSUE TITLE
CSV::Table requires type arguments statically, but fails during runtime if supplied

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#3311]
Rescuing this from a comment deep down in another issue: https://github.com/sorbet/sorbet/issues/2379#issuecomment-571807741

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire%20'CSV'%0A%0Amy_file%20%3D%20'test.csv'%0A%0Aplain_parsed%20%3D%20CSV.parse(my_file)%0AT.reveal_type(plain_parsed)%20%23%20This%20is%20OK...%20I%20don't%20care%20about%20the%20type%0A%0Aarray_parsed%20%3D%20T.cast(CSV.parse(my_file)%2C%20T%3A%3AArray%5BT%3A%3AArray%5BString%5D%5D)%0AT.reveal_type(plain_parsed)%20%23%20This%20is%20also%20OK...%20I%20know%20it's%20going%20to%20return%20an%20Array%20and%20I%20cast%20to%20it%20to%20be%20able%20to%20use%20as%20an%20Array%0A%0A%23%20Here%20is%20where%20the%20problems%20start%0Atable_parsed_no_generic%20%3D%20T.cast(CSV.parse(my_file%2C%20headers%3A%20true)%2C%20CSV%3A%3ATable)%20%23%20statically%2C%20I%20need%20to%20provide%20a%20type%20%3A(%0A%0Atable_parsed_generic%20%3D%20T.cast(CSV.parse(my_file%2C%20headers%3A%20true)%2C%20CSV%3A%3ATable%5BCSV%3A%3ARow%5D)%20%23%20this%20works%20statically%2C%20but%20fails%20at%20runtime%0A )

```ruby
# typed: true
require 'CSV'

my_file = 'test.csv'

plain_parsed = CSV.parse(my_file)
T.reveal_type(plain_parsed) # This is OK... I don't care about the type

array_parsed = T.cast(CSV.parse(my_file), T::Array[T::Array[String]])
T.reveal_type(plain_parsed) # This is also OK... I know it's going to return an Array and I cast to it to be able to use as an Array

# Here is where the problems start
table_parsed_no_generic = T.cast(CSV.parse(my_file, headers: true), CSV::Table) # statically, I need to provide a type :(

table_parsed_generic = T.cast(CSV.parse(my_file, headers: true), CSV::Table[CSV::Row]) # this works statically, but fails at runtime
```

#### Observed output

```
Malformed type declaration. Generic class without type arguments CSV::Table https://srb.help/5045
```

But the interesting part is during runtime for the declaration WITH a generic type:

```
undefined method `[]' for CSV::Table:Class
```

#### Expected behavior

The static complaint is OK, but the runtime should accept the generic type as well

**Comment by Morriar** [comment]
Fixed since https://github.com/sorbet/sorbet/pull/3404
