### ISSUE TITLE
Missing error: Calling .new on a type alias (metatype) should not be allowed statically

### ISSUE THREAD

**Issue by shale-stripe** [sorbet/sorbet#3335]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0Aend%0A%0AB%20%3D%20T.type_alias%20%7BA%7D%0A%0Adef%20main%0A%20%20A.new%0A%20%20B.new%20%23%20Raises%20an%20exception%20at%20runtime%0Aend)

```ruby
# typed: true
class A
end

B = T.type_alias {A}

def main
  A.new
  B.new # Raises an exception at runtime
end
```

#### Observed output

`B.new` raises an exception at runtime:
```
NoMethodError: undefined method `new' for #<T::Private::Types::TypeAlias:0x0000...>
```

#### Expected behavior

Sorbet should statically tell me that `B.new` cannot be invoked on a `TypeAlias`

**Comment by jez** [comment]
I'm going to close this one and re open the other one because i think the other one is a little more detailed.
