### ISSUE TITLE
Error "Expression does not have a fully-defined type" with default argument value for type_template

### ISSUE THREAD

**Issue by benbuckman-stripe** [sorbet/sorbet#334]
I’m confused by this error with a `type_template`, `Expression does not have a fully-defined type`

This is fine –
https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20View%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20abstract!%0A%0A%20%20Model%20%3D%20type_template%0A%0A%20%20sig%20%7Bparams(model%3A%20T.nilable(Model)).void%7D%0A%20%20def%20initialize(model)%0A%20%20end%0Aend%0A%0Aclass%20MyView%20%3C%20View%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Model%20%3D%20type_template(fixed%3A%20MyView)%0Aend%0A

but if I add a default `=nil` argument value (the type is `T.nilable`), then I get the error –

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20View%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20abstract!%0A%0A%20%20Model%20%3D%20type_template%0A%0A%20%20sig%20%7Bparams(model%3A%20T.nilable(Model)).void%7D%0A%20%20def%20initialize(model%3Dnil)%0A%20%20end%0Aend%0A%0Aclass%20MyView%20%3C%20View%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Model%20%3D%20type_template(fixed%3A%20MyView)%0Aend%0A

> editor.rb:11: Expression does not have a fully-defined type (Did you reference another class's type members?) 
    11 |  def initialize(model=nil)

It doesn’t seem like adding `=nil` is changing the type, hence my confusion.
Thanks

**Comment by jez** [comment]
It looks like this behavior has been "fixed" in the sense that we have now made the error more explicit and consistent.

Both the plain and `=nil` versions of the snippet report the same error now:

```
editor.rb:10: type_template type Model used in an instance method definition https://srb.help/5072
    10 |  sig {params(model: T.nilable(Model)).void}
                                       ^^^^^
    editor.rb:8: Model defined here
     8 |  Model = type_template
          ^^^^^^^^^^^^^^^^^^^^^
  Note:
    Only a type_member can be used in an instance method definition.
Errors: 1
```

which is correct, this code should be rejected. So we can close this for now.

But maybe what the question is really asking for is some way to have some sort of type_template-ish thing that can be used from both instance methods and singleton class methods. Solving that would let us solve #4035, so if you're curious, you can follow that issue for further updates. No immediate work is planned for that issue at the moment.
