### ISSUE TITLE
A T.untyped attr_accessor requires the instance variable to be defined, in contrast to a T.nilable accessor

### ISSUE THREAD

**Issue by univerio** [sorbet/sorbet#3347]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Breturns(T.untyped)%7D%0A%20%20attr_accessor%20%3Afoo%0Aend)

```ruby
# typed: strict
class A
  extend T::Sig
  sig {returns(T.untyped)}
  attr_accessor :foo
end
```

#### Observed output

```
editor.rb:5: Use of undeclared variable @foo https://srb.help/6002
     5 |  attr_accessor :foo
                         ^^^

editor.rb:5: Use of undeclared variable @foo https://srb.help/6002
     5 |  attr_accessor :foo
                         ^^^
Errors: 2
```

#### Expected behavior

There should be no errors since sorbet this works properly for `T.nilable` attrs:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Breturns(T.nilable(Integer))%7D%0A%20%20attr_accessor%20%3Afoo%0Aend)

```ruby
# typed: strict
class A
  extend T::Sig
  sig {returns(T.nilable(Integer))}
  attr_accessor :foo
end
```

- - -

The workaround is to use `T.nilable(T.untyped)`, which is a bit clunky IMO:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Breturns(T.nilable(T.untyped))%7D%0A%20%20attr_accessor%20%3Afoo%0Aend)

```ruby
# typed: strict
class A
  extend T::Sig
  sig {returns(T.nilable(T.untyped))}
  attr_accessor :foo
end
```

**Comment by serpilacar** [comment]
It seems untyped definitions are not allowed in strict mode. Examples you've provided are all have `typed: strict`. 

> It may seem counterintuitive that Sorbet does not require type annotations in a file marked # typed: true, but this is an intentional part of Sorbet’s implementation of gradual typing. In the # typed: true strictness level, unannotated methods, instance variables, and constants are assumed to be T.untyped. This allows a programmer to write untyped or partially-typed definitions while still benefiting from type checking when static type information is present.

https://sorbet.org/docs/type-annotations#type-annotations-and-strictness-levels

**Comment by univerio** [comment]
@serpilacar It's true that sorbet requires type annotations for instance variable in strict mode, but in this particular case, sorbet itself injects an instance variable annotation for `attr_writer` and `attr_accessor` (but only if it's `T.nilable`).
