### ISSUE TITLE
Add `Sorbet::RakeTask`

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [sorbet/sorbet#3350]
### Problem

I usually run my rakefile on CI where I've got specs and rubocop and I'd like to include typecheck there as well.

### Proposed solution

Introuduce `Sorbet::RakeTask` for that purpose

**Comment by jez** [comment]
Thanks for the proposal. There's not much benefit to this. Just write code in your Rakefile to call `srb tc`.
