### ISSUE TITLE
Uniformize how CLI tests are run

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#3385]
For tests in `cli/` we end up executing them and comparing the output with the expected one  in different ways.

For example between [`suggest-sig`](https://github.com/sorbet/sorbet/tree/master/test/cli/suggest-sig) and [`autocorrect-abstract`](https://github.com/sorbet/sorbet/tree/master/test/cli/autocorrect-abstract).

As noted by @jez [here](https://github.com/sorbet/sorbet/pull/3381#discussion_r476015233), the approach used in `suggest-sig` is better:

> Can you capture stderr here so that it shows up in autocorrect-helpers.out?
>
> https://github.com/sorbet/sorbet/blob/master/test/cli/suggest-sig/suggest-sig.sh
> 
> ^ also, this is a good CLI test to copy. This test uses cat to capture the edited file in the output, which means that any future diff can be updated by the script (e.g. right now post.rb must be edited by hand, or we have to record a diff in autocorrect-helpers.out, and diffs are trickier to read)
> 
> and it uses mktemp -d to get around a problem where tmpfile names show up in the .out output.

We should clean the way those test are ran so they always follow the same pattern.

**Comment by jez** [comment]
I did this in #5178
