### ISSUE TITLE
Constants are not propagated on module inclusion

### ISSUE THREAD

**Issue by fsateler** [sorbet/sorbet#3391]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20A%0A%20%20CONSTANT%20%3D%20'a%20constant'.freeze%0Aend%0A%0Aclass%20B%0A%20%20include%20A%0Aend%0A%0AB%3A%3ACONSTANT%0A%0A)

```ruby
# typed: true

module A
  CONSTANT = 'a constant'.freeze
end

class B
  include A
end

B::CONSTANT
```

#### Observed output

```
editor.rb:11: Unable to resolve constant CONSTANT https://srb.help/5002
    11 |B::CONSTANT
        ^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:11: Replace with A::CONSTANT
    11 |B::CONSTANT
        ^^^^^^^^^^^
    editor.rb:4: Did you mean: A::CONSTANT?
     4 |  CONSTANT = 'a constant'.freeze
          ^^^^^^^^
Errors: 1
```

#### Expected behavior

No errors, as `B` inherits the constants from `A`.

**Comment by Morriar** [comment]
:wave: @fsateler,

This is another instance of https://github.com/sorbet/sorbet/issues/8 and this will be non-trivial to fix. I'll close this one as it's a duplicate.

In the mean time, you can fully qualify the constant using the introduction class: `A::CONSTANT`.

Thanks for reporting!
