### ISSUE TITLE
Serialization of T::Struct operates differently to Hash or Struct

### ISSUE THREAD

**Issue by hlascelles** [sorbet/sorbet#3392]
It is clear [in the documentation](https://sorbet.org/docs/tstruct#converting-structs-to-other-types) that when serializing a `T::Struct` with values that are `nil` (or missing), it will yield a `Hash` where that key is missing altogether.

```ruby
require 'sorbet-runtime'

class MyTStruct < T::Struct
  const :bar, T.nilable(String)
end

# With T::Struct (and no value) we do not see a `bar` key
obj = MyTStruct.new
obj.serialize # => { }

# With T::Struct (and nil value) we do not see a `bar` key
obj = MyTStruct.new(bar: nil)
obj.serialize # => { }
```

This behaviour may be a surprise to those who may be expecting `T::Struct` to work either like a "more principled" `Hash`, or even like a `Struct` (which confusingly work differently to each other too).

```ruby
# With Hash (and no value) we do not see a `bar` key
obj = { }
# => { }
# With Hash (and nil value) we *do* see a `bar` key
obj = { bar: nil }
# => { :bar=>nil }


MyStruct = Struct.new(:bar)
# With Struct (and no value) we *do* see a `bar` key
my_struct = MyStruct.new
my_struct.to_h # => {:bar=>nil}
# With Struct (and nil value) we *do* see a `bar` key
my_struct = MyStruct.new(nil)
my_struct.to_h # => {:bar=>nil}
```

I can see [in the codebase](https://github.com/sorbet/sorbet/blob/b8b35b39c8f6c4c3e5b14ce606f07fd4b7687569/gems/sorbet-runtime/lib/types/props/private/serializer_generator.rb#L54) that was done for payload space reasons.  Stripe's requirements are almost certainly different to mine, but was it worth introducing a third way for a "structish" object to work for this performance requirement?

Digression: `Hash` says "if you tell me the value is `nil`, then I know it is `nil` and can say so when serialized, otherwise I will not claim to know what it is". ie, no information is lost. Setting something to `nil` is not the same as "not setting a value to anything". I find the `Hash` implementation the most sensible _if_ we group all these tools together as "tools providing the same function", which I know they aren't of course.

My main question would be: would you accept a PR to make this behaviour configurable, or at least provide easier access to that part of the code flow so it could be altered by using [a mixin](https://github.com/tricycle/sorbet-struct-comparable)? Or are we just using them wrong? 

I can well understand that adding this feature to match `Hash` would require not only holding `nil` values, but also tracking which values "have been set". We would probably get sufficient benefit for our needs if we changed it to match `Struct` so we get explicit keys with "defaults of `nil`".

**Comment by jeffcarbs** [comment]
In a slack thread from a few months ago the authors have said that `T::Struct` serialize/deserialize is a legacy internal-only API and it's recommended you implement it yourself if you need it:
> (the fact that T::Struct has a serialize method is somewhat a legacy part of stripe’s codebase evolution; it doesn’t make sense to attempt to serialize all structs, for example consider structs whose props contain Proc objects)

And:
> if you want a specific serialization / deserialization we recommend you build the solution you need

----

Full thread at: https://sorbet-ruby.slack.com/archives/CHN2L03NH/p1589411981323500
<img width="726" alt="Screen Shot 2020-08-31 at 9 06 50 AM" src="https://user-images.githubusercontent.com/847027/91735404-80031300-eb69-11ea-990d-c8e5079265a7.png">

**Comment by hlascelles** [comment]
Great, thank you for the detail. We will add our own :+1:.

**Comment by connorshea** [comment]
@DarkDimius @jez If what @jeffcarbs is saying is true, we should probably update [the T::Struct docs](https://sorbet.org/docs/tstruct) to no longer mention `serialize`
