### ISSUE TITLE
srb commands modifying/ignoring gem rbi file

### ISSUE THREAD

**Issue by robertjlooby** [sorbet/sorbet#3403]
#### Input / Observed output

I have a gem that has an rbi file included with it. The path to the gem is like `/Users/user/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/my_gem-version` so the rbi file is `/Users/user/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/my_gem-version/rbi/my_gem.rbi`.

Sorbet finds the gem rbi just fine and includes the path in the `~/.cache/sorbet/gem-rbis/<sha>` cache.

When I run `srb rbi gems` or `srb rbi update`, that rbi file has it's typed comment changed to `# typed: ignore` and it generates a `sorbet/rbi/gems/my_gem.rbi` file with all the autogenerated method stubs in the project and changes a bunch of bunch of typed comments to `false` in the project.

If I remove the generated rbi file, change the typed comment back to `strong` in the gem rbi file, and check out the typed comment changes in the project, then `srb tc` passes just fine.

If I `chmod 044 /Users/user/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/my_gem-version/rbi/my_gem.rbi` to prevent sorbet from modifying the gem rbi file, then it still generates the `sorbet/rbi/gems/my_gem.rbi` file in the project with a `# typed: ignore` comment, but otherwise everything works fine and it doesn't change the typed level on any of the files in the project and continues to typecheck.

#### Expected behavior

I would expect that an rbi file included in a gem would be used instead of generating the `sorbet/rbi/gems/my_gem.rbi` file. I would certainly _not_ expect for any `srb` commands to edit a file in an installed gem outside of the current project.

**Comment by garybethea** [comment]
I'm experiencing this as well. After upgrading to sorbet 0.5.6198, some gem RBI files are being generated with `typed: ignore`, causing multiple 5002 (`Unable to resolve constant`) errors. When I change these files back to `typed: strict`, the errors go away. Why would Sorbet ever ignore an autogenerated RBI file?

**Comment by reidab** [comment]
I've also seen this with the latest version of sorbet and the [parlour](https://github.com/AaronC81/parlour) gem used by [sorbet-rails](https://github.com/chanzuckerberg/sorbet-rails).

Here's a minimal reproduction.

* In an empty directory, create this `Gemfile`:

  ```ruby
  # frozen_string_literal: true

  source "https://rubygems.org"

  git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

  gem 'sorbet', :group => :development
  gem 'sorbet-runtime'
  gem 'parlour'
  ```

* Bundle, then ensure the parlour gem's RBI file is pristine and has the expected type:

  ```shell
  $ bundle
  $ bundle pristine parlour
  $ head `bundle info --path parlour`/rbi/parlour.rbi
  ```

* You should see that the included RBI file is `typed: strong`:

  ```ruby
  # typed: strong
  module Kernel
  end

  module Parlour
    VERSION = '5.0.0'
  ...
  ```

* Update gem RBIs and re-check Parlour's RBI file:

  ```shell
  $ bundle exec srb rbi gems
  $ head `bundle info --path parlour`/rbi/parlour.rbi
  ```
 
* Parlour's embedded RBI file has now been modified:

  ```ruby
  # typed: ignore
  module Kernel
  end

  module Parlour
    VERSION = '5.0.0'
  ...
  ```

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
