### ISSUE TITLE
Incorrectly suggests that a variable is changing type in a loop

### ISSUE THREAD

**Issue by wakeless** [sorbet/sorbet#3436]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%3B%20end%0Adef%20main(x)%0A%20%20if%20x%0A%20%20%20%20f%20%3D%20Foo.new%0A%20%20else%0A%20%20%20%20(1..3).each%20do%20%7Ci%7C%0A%20%20%20%20%20%20f%20%3D%20Foo.new%0A%20%20%20%20end%0A%20%20end%0Aend)

```ruby
# typed: true

class Foo; end
def main(x)
  if x
    f = Foo.new
  else
    (1..3).each do |i|
      f = Foo.new
    end
  end
end
```

#### Observed output

```
editor.rb:9: Changing the type of a variable in a loop is not permitted https://srb.help/7001
     9 |      f = Foo.new
                  ^^^^^^^
  Existing variable has type: NilClass
  Attempting to change type to: Foo

  Autocorrect: Use `-a` to autocorrect
    editor.rb:4: Replace with T.let(def main(x), T.nilable(Foo))
     4 |def main(x)
        ^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Really 2 errors here. Firstly, there is 2 different scopes here, thus the fact that the 2 references to f should not interact.

Secondly, the type does not change In this case they are both instances of `Foo`

- - -

**Comment by Morriar** [comment]
I believe this is the same problem as [this example](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%3B%20end%0Adef%20main(x)%0A%20%20f%20%3D%20nil%0A%20%20(1..3).each%20do%20%7Ci%7C%0A%20%20%20%20f%20%3D%20Foo.new%0A%20%20end%0Aend) where the type of the variable changes from `nil` to `Foo`.

The solution is to use a `T.let` to let Sorbet know that this type might contain something else than `nil`:

```rb
def main(x)
  f = T.let(nil, T.nilable(Foo))
  (1..3).each do |i|
    f = Foo.new
  end
end
```

You example can be corrected like [this](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%3B%20end%0Adef%20main(x)%0A%20%20f%20%3D%20T.let(nil%2C%20T.nilable(Foo))%0A%20%20if%20x%0A%20%20%20%20f%20%3D%20Foo.new%0A%20%20else%0A%20%20%20%20(1..3).each%20do%20%7Ci%7C%0A%20%20%20%20%20%20f%20%3D%20Foo.new%0A%20%20%20%20end%0A%20%20end%0Aend).
