### ISSUE TITLE
Bring back flow-sensitive typing for singleton values

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#3457]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire%20'singleton'%0A%0Aclass%20MySingleton%0A%20%20include%20Singleton%0A%0A%20%20extend%20T%3A%3AHelpers%0A%20%20final!%0Aend%0A%0Aclass%20Main%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20T.any(MySingleton%2C%20Integer)).void%7D%0A%20%20def%20self.test1(x)%0A%20%20%20%20if%20x.equal%3F(MySingleton.instance)%0A%20%20%20%20%20%20T.reveal_type(x)%20%23%20%3D%3E%20not%20working%20(MySingleton)%0A%20%20%20%20elsif%20x.is_a%3F(Integer)%0A%20%20%20%20%20%20T.reveal_type(x)%20%23%20%3D%3E%20working%20ok%20(Integer)%0A%20%20%20%20else%0A%20%20%20%20%20%20T.absurd(x)%20%23%20%3D%3E%20not%20working%20(should%20not%20error)%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20sig%20%7Bparams(x%3A%20T.any(MySingleton%2C%20Integer)).void%7D%0A%20%20def%20self.test2(x)%0A%20%20%20%20if%20x%20%3D%3D%20MySingleton.instance%0A%20%20%20%20%20%20T.reveal_type(x)%20%23%20%3D%3E%20not%20working%20(MySingleton)%0A%20%20%20%20elsif%20x.is_a%3F(Integer)%0A%20%20%20%20%20%20T.reveal_type(x)%20%23%20%3D%3E%20working%20ok%20(Integer)%0A%20%20%20%20else%0A%20%20%20%20%20%20T.absurd(x)%20%23%20%3D%3E%20not%20working%20(should%20not%20error)%0A%20%20%20%20end%0A%20%20end%0Aend)

```ruby
# typed: true
require 'singleton'

class MySingleton
  include Singleton

  extend T::Helpers
  final!
end

class Main
  extend T::Sig

  sig {params(x: T.any(MySingleton, Integer)).void}
  def self.test1(x)
    if x.equal?(MySingleton.instance)
      T.reveal_type(x) # => not working (MySingleton)
    elsif x.is_a?(Integer)
      T.reveal_type(x) # => working ok (Integer)
    else
      T.absurd(x) # => not working (should not error)
    end
  end

  sig {params(x: T.any(MySingleton, Integer)).void}
  def self.test2(x)
    if x == MySingleton.instance
      T.reveal_type(x) # => not working (MySingleton)
    elsif x.is_a?(Integer)
      T.reveal_type(x) # => working ok (Integer)
    else
      T.absurd(x) # => not working (should not error)
    end
  end
end
```

#### Observed output

```
editor.rb:21: Control flow could reach T.absurd because the type MySingleton wasn't handled https://srb.help/7026
    21 |      T.absurd(x) # => not working (should not error)
              ^^^^^^^^^^^
  Originating from:
    editor.rb:15:
    15 |  def self.test1(x)
                         ^
    editor.rb:18:
    18 |    elsif x.is_a?(Integer)
                  ^^^^^^^^^^^^^^^^

editor.rb:19: Revealed type: Integer https://srb.help/7014
    19 |      T.reveal_type(x) # => working ok (Integer)
              ^^^^^^^^^^^^^^^^
  From:
    editor.rb:15:
    15 |  def self.test1(x)
                         ^
    editor.rb:18:
    18 |    elsif x.is_a?(Integer)
                  ^^^^^^^^^^^^^^^^

editor.rb:17: Revealed type: T.any(MySingleton, Integer) https://srb.help/7014
    17 |      T.reveal_type(x) # => not working (MySingleton)
              ^^^^^^^^^^^^^^^^
  From:
    editor.rb:15:
    15 |  def self.test1(x)
                         ^

editor.rb:32: Control flow could reach T.absurd because the type MySingleton wasn't handled https://srb.help/7026
    32 |      T.absurd(x) # => not working (should not error)
              ^^^^^^^^^^^
  Originating from:
    editor.rb:26:
    26 |  def self.test2(x)
                         ^
    editor.rb:29:
    29 |    elsif x.is_a?(Integer)
                  ^^^^^^^^^^^^^^^^

editor.rb:30: Revealed type: Integer https://srb.help/7014
    30 |      T.reveal_type(x) # => working ok (Integer)
              ^^^^^^^^^^^^^^^^
  From:
    editor.rb:26:
    26 |  def self.test2(x)
                         ^
    editor.rb:29:
    29 |    elsif x.is_a?(Integer)
                  ^^^^^^^^^^^^^^^^

editor.rb:28: Revealed type: T.any(MySingleton, Integer) https://srb.help/7014
    28 |      T.reveal_type(x) # => not working (MySingleton)
              ^^^^^^^^^^^^^^^^
  From:
    editor.rb:26:
    26 |  def self.test2(x)
                         ^
Errors: 6
```

#### Expected behavior

Expected reveal typed are annotated in comments.

- - -

This feature used to work, but was removed in #3213 

It was removed because piggy-backing on `Singleton` to model `T::Enum` was a lie—the runtime of `T::Enum` is not implemented using `Singleton`, and this mismatch between how it was modeled statically vs what actually happened at runtime was problematic.

There's no fundamental reason why Sorbet couldn't support this feature properly, so I'm adding it back as a good first issue in case people want to learn about Sorbet's flow-sensitive typing.

**Comment by jez** [comment]
This is related to #3456, which can be fixed separately, but will have an impact on the test case mentioned here.

**Comment by sharpobject** [comment]
If I understand correctly, the issue here is actually that `MySingleton.instance` has type `T.untyped`. I am not sure how that happened in #3213, but I'll take a look.

**Comment by sharpobject** [comment]
It seems like the example code should be some other code rather than what it is. As written it did not work even prior to #3213 because `MySingleton.instance` still hat type `T.untyped` at the time. After replacing `MySingleton.instance` with `T.Let(MySingleton.instance, MySingleton` and using the latest master plus my changes from #3458, the expected types are revealed.

If the intention of this issue is to make it so that `MySingleton.instance` has return type `MySingleton`, I read [here](https://github.com/sorbet/sorbet/commit/5ea787524fc593054f83f6291cbcab758a2ef23e) that we need #62 first.

**Comment by sharpobject** [comment]
It seems like we now have `T.attached_class` but we may not use it in the return type of `Singleton#instance`:

```
ERROR: /Users/sharpobject/repos/sorbet/payload/binary/BUILD:71:8: Executing genrule //payload/binary:generate-state-payload-raw failed (Exit 1)
https://github.com/sorbet/sorbet/tree/master/rbi/stdlib/singleton.rbi#L112: `T.attached_class` may only be used in a singleton class method context https://srb.help/5004
     112 |    sig {returns(T.attached_class)}
                           ^^^^^^^^^^^^^^^^
```

**Comment by jez** [comment]
looks like #3639 fixed this.
