### ISSUE TITLE
incorrect typing of generics in method body

### ISSUE THREAD

**Issue by djudd-stripe** [sorbet/sorbet#3461]
#### Input

[→ View on sorbet.run](https://sorbet.run/#class%20Future%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Value%20%3D%20type_member%0A%0A%20%20%23%20Given%20Future%5BA%5D%20and%20function%20A%20-%3E%20B%2C%20return%20Future%5BB%5D%0A%20%20sig(%3Afinal)%20do%0A%20%20%20%20type_parameters(%3AT)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20blk%3A%20T.proc.params(value%3A%20Value).returns(T.type_parameter(%3AT))%0A%20%20%20%20)%0A%20%20%20%20.returns(Future%5BT.type_parameter(%3AT)%5D)%0A%20%20end%0A%20%20def%20map(%26blk)%0A%20%20%20%20flat_map%20do%20%7Cvalue%7C%0A%20%20%20%20%20%20transformed%20%3D%20yield%20value%0A%20%20%20%20%20%20Future.of%20%7Btransformed%7D%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20%23%20Given%20Future%5BA%5D%20and%20function%20A%20-%3E%20Future%5BB%5D%2C%20return%20Future%5BB%5D%0A%20%20sig(%3Afinal)%20do%0A%20%20%20%20type_parameters(%3AT)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20blk%3A%20T.proc.params(value%3A%20Value).returns(Future%5BT.type_parameter(%3AT)%5D)%0A%20%20%20%20)%0A%20%20%20%20.returns(Future%5BT.type_parameter(%3AT)%5D)%0A%20%20end%0A%20%20def%20flat_map(%26blk)%0A%20%20%20%20raise%20%22TODO%22%0A%20%20end%0A%0A%20%20%23%20Create%20a%20Future%20from%20a%20block%2C%20which%20will%20be%20called%20lazily%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AT)%0A%20%20%20%20.params(blk%3A%20T.proc.returns(T.type_parameter(%3AT)))%0A%20%20%20%20.returns(Future%5BT.type_parameter(%3AT)%5D)%0A%20%20end%0A%20%20def%20self.of(%26blk)%0A%20%20%20%20raise%20%22TODO%22%0A%20%20end%0Aend)

```ruby
class Future
  extend T::Sig

  extend T::Generic
  Value = type_member

  # Given Future[A] and function A -> B, return Future[B]
  sig(:final) do
    type_parameters(:T)
    .params(
      blk: T.proc.params(value: Value).returns(T.type_parameter(:T))
    )
    .returns(Future[T.type_parameter(:T)])
  end
  def map(&blk)
    flat_map do |value|
      transformed = yield value
      Future.of {transformed}
    end
  end

  # Given Future[A] and function A -> Future[B], return Future[B]
  sig(:final) do
    type_parameters(:T)
    .params(
      blk: T.proc.params(value: Value).returns(Future[T.type_parameter(:T)])
    )
    .returns(Future[T.type_parameter(:T)])
  end
  def flat_map(&blk)
    raise "TODO"
  end

  # Create a Future from a block, which will be called lazily
  sig do
    type_parameters(:T)
    .params(blk: T.proc.returns(T.type_parameter(:T)))
    .returns(Future[T.type_parameter(:T)])
  end
  def self.of(&blk)
    raise "TODO"
  end
end
```

#### Observed output

```
editor.rb:16: Returning value that does not conform to block result type https://srb.help/7005
    16 |    flat_map do |value|
    17 |      transformed = yield value
    18 |      Future.of {transformed}
    19 |    end
  Expected Future[T]
  Got Future[Future#map#T] originating from:
    editor.rb:18:
    18 |      Future.of {transformed}
              ^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:16: Returning value that does not conform to method result type https://srb.help/7005
    16 |    flat_map do |value|
    17 |      transformed = yield value
    18 |      Future.of {transformed}
    19 |    end
  Expected Future[Future#map#T]
    editor.rb:15: Method map has return type Future[Future#map#T]
    15 |  def map(&blk)
          ^^^^^^^^^^^^^
  Got Future[T.noreturn] originating from:
    editor.rb:16:
    16 |    flat_map do |value|
    17 |      transformed = yield value
    18 |      Future.of {transformed}
    19 |    end
Errors: 2
```

#### Expected behavior

This should typecheck; it doesn't. It appears that we fail to thread through the identity of the type parameter between the different functions; instead we end up with a `T.noreturn` somehow.

**Comment by djudd-stripe** [comment]
Possibly simpler reproduction:

https://sorbet.run/#extend%20T%3A%3ASig%0A%0Aclass%20Burrito%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Value%20%3D%20type_member%0Aend%0A%0Asig%20do%0A%20%20type_parameters(%3AT)%0A%20%20.params(%0A%20%20%20%20blk%3A%20T.proc.returns(Burrito%5BT.type_parameter(%3AT)%5D)%0A%20%20)%0A%20%20.returns(Burrito%5BT.type_parameter(%3AT)%5D)%0Aend%0Adef%20unwrap(%26blk)%0A%20%20blk.call%0Aend%0A%0Av%20%3D%20T.cast(nil%2C%20Burrito%5BInteger%5D)%20%23%20hack%20to%20demonstrate%0Ax%20%3D%20unwrap%20%7Bv%7D%0A

**Comment by masylum** [comment]
@djudd-stripe I'm facing the same issue, have you found a workaround?

**Comment by djudd-stripe** [comment]
I've just used `T.unsafe`

**Comment by jez** [comment]
I think this is fixed as of #6017
