### ISSUE TITLE
T.absurd permits more than just a variable as its argument

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#3462]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0AT.absurd(%3Afoo)%20if%20T.unsafe(false))

```ruby
# typed: true

T.absurd(:foo) if T.unsafe(false)
```

#### Observed output

```
editor.rb:3: Control flow could reach T.absurd because the type Symbol(:"foo") wasn't handled https://srb.help/7026
     3 |T.absurd(:foo) if T.unsafe(false)
        ^^^^^^^^^^^^^^
  Originating from:
    editor.rb:3:
     3 |T.absurd(:foo) if T.unsafe(false)
                 ^^^^
Errors: 1
```

#### Expected behavior

This should be a different error: `T.absurd` only makes sense when used with a variable.

https://github.com/sorbet/sorbet/blob/2e01c34cdf0190e0a372368a9d6ac45fac1de36d/cfg/builder/builder_walk.cc#L347-L355
- - -

**Comment by aprocter-stripe** [comment]
Fixed by #3531
