### ISSUE TITLE
Order dependency in generic classes

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#347]
https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20ActiveRecord%3A%3ARelation%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7Breturns(Elem)%7D%0A%20%20def%20e()%3BT.unsafe(1)%3B%20end%0Aend%0A%0Amodule%20ThisClassIsNeverUsed%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%23%20uncommenting%20this%20causes%20a%20bug%0A%20%20%23%20sig%20%7Bparams(args%3A%20T.untyped).returns(Site%3A%3ARelation)%7D%0A%20%20def%20unused(*args)%0A%20%20%20%20%20T.unsafe(nil)%0A%20%20%20end%0Aend%0A%0A%23%20moving%20this%20class%20above%20%60ThisClassIsNeverUsed%60%20fixes%20the%20bug%0Aclass%20Site%3A%3ARelation%20%3C%20ActiveRecord%3A%3ARelation%0A%20%20Elem%20%3D%20type_member(fixed%3A%20Site)%0Aend%0A%0A%0AT.reveal_type(T.cast(nil%2C%20Site%3A%3ARelation).e)

reported by @manhhung741

**Comment by elliottt** [comment]
I think that this is fixed in master now, as uncommenting the problematic signature doesn't change the revealed type.
