### ISSUE TITLE
incorrect type definition for Net::SSH::KnownHosts.search_in

### ISSUE THREAD

**Issue by will** [sorbet/sorbet#3478]
https://github.com/net-ssh/net-ssh/blob/v6.1.0/lib/net/ssh/known_hosts.rb#L60
has 
``` ruby 
class Net::SSH::KnownHosts
  def self.search_in(files, host); end
end
```

However this is incompatible with net-ssh v6.1.0 https://github.com/net-ssh/net-ssh/blob/v6.1.0/lib/net/ssh/known_hosts.rb#L60

``` ruby
   def search_in(files, host, options = {})
```

This conflict breaks tapioca generated rbi files, which generates the signature correctly, but then has a mismatch with the included sorbet rbi: https://github.com/Shopify/tapioca/issues/142

Sorbet versions 
```
Using sorbet-static 0.5.5933 (universal-darwin-19)
Using sorbet 0.5.5933
```

Thanks to @KaanOzkan for tracking down the problem

**Comment by jez** [comment]
believe this was fixed in #3516
