### ISSUE TITLE
Inconsistent reporting of errors for methods that might return nil

### ISSUE THREAD

**Issue by ghiculescu** [sorbet/sorbet#3483]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20ret%0A%20%20%20%20%22ret%22%0A%20%20end%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20def%20typed_ret%0A%20%20%20%20%22ret%22%0A%20%20end%0A%0A%20%20sig%20%7B%20params(location_id%3A%20T.nilable(T.any(String%2C%20Integer))).returns(String)%20%7D%0A%20%20def%20should_sorbet_error_but_also_does_not(location_id%20%3D%20nil)%0A%20%20%20%20%23%20this%20should%20error%2C%20because%20of%20location_id%20is%20nil%20then%20it%20will%20return%20nil%0A%20%20%20%20ret%20if%20!location_id.nil%3F%0A%20%20end%0A%0A%20%20sig%20%7B%20params(location_id%3A%20T.nilable(T.any(String%2C%20Integer))).returns(String)%20%7D%0A%20%20def%20should_sorbet_error_but_also_does_not(location_id%20%3D%20nil)%0A%20%20%20%20%23%20this%20should%20error%2C%20because%20of%20location_id%20is%20nil%20then%20it%20will%20return%20nil%0A%20%20%20%20typed_ret%20if%20!location_id.nil%3F%0A%20%20end%0A%0A%20%20sig%20%7B%20params(location_id%3A%20T.nilable(T.any(String%2C%20Integer))).returns(String)%20%7D%0A%20%20def%20should_error_and_does!(location_id%20%3D%20nil)%0A%20%20%20%20%22ret%22%20if%20!location_id.nil%3F%0A%20%20end%0Aend%0A)

```ruby
# typed: true
module Foo
  extend T::Sig

  def ret
    "ret"
  end

  sig {returns(String)}
  def typed_ret
    "ret"
  end

  sig { params(location_id: T.nilable(T.any(String, Integer))).returns(String) }
  def should_sorbet_error_but_also_does_not(location_id = nil)
    # this should error, because of location_id is nil then it will return nil
    ret if !location_id.nil?
  end

  sig { params(location_id: T.nilable(T.any(String, Integer))).returns(String) }
  def should_error_and_also_does(location_id = nil)
    typed_ret if !location_id.nil?
  end

  sig { params(location_id: T.nilable(T.any(String, Integer))).returns(String) }
  def should_error_and_does!(location_id = nil)
    "ret" if !location_id.nil?
  end
end


```

#### Observed output

```

# typed: true
editor.rb:21: Returning value that does not conform to method result type https://srb.help/7005
    21 |  def should_error_and_also_does(location_id = nil)
    22 |    # this should error, because of location_id is nil then it will return nil
    23 |    typed_ret if !location_id.nil?
    24 |  end
  Expected String
    editor.rb:21: Method should_error_and_also_does has return type String
    21 |  def should_error_and_also_does(location_id = nil)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(String) originating from:
    editor.rb:21:
    21 |  def should_error_and_also_does(location_id = nil)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:23:
    23 |    typed_ret if !location_id.nil?
            ^^^^^^^^^

editor.rb:27: Returning value that does not conform to method result type https://srb.help/7005
    27 |  def should_error_and_does!(location_id = nil)
    28 |    "ret" if !location_id.nil?
    29 |  end
  Expected String
    editor.rb:27: Method should_error_and_does! has return type String
    27 |  def should_error_and_does!(location_id = nil)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(String) originating from:
    editor.rb:27:
    27 |  def should_error_and_does!(location_id = nil)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:28:
    28 |    "ret" if !location_id.nil?
            ^^^^^
Errors: 2
```

#### Expected behavior

All methods should have the same sorbet error. I'm guessing the first one doesn't because `ret` is a `T.untyped`. But that shouldn't change the fact that `if !location_id.nil?` could return false at which point the method would return nil.

- - -

If you expand the method out you get the same behaviour:

```ruby
  sig { params(location_id: T.nilable(T.any(String, Integer))).returns(String) }
  def should_sorbet_error_but_also_does_not(location_id = nil)
    # doesn't error
    if location_id.nil?
      nil
    else
      ret
    end
  end
```

```ruby
  sig { params(location_id: T.nilable(T.any(String, Integer))).returns(String) }
  def should_error(location_id = nil)
    # errors!
    if location_id.nil?
      nil
    else
      "ret"
    end
  end
```

**Comment by jez** [comment]
> But that shouldn't change the fact that `if !location_id.nil?` could return false at which point the method would return nil.

In fact, it does. It forces Sorbet to see the result as `T.any(T.untyped, NilClass)` which in all contexts—this one included—is equivalent to `T.untyped`.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20ret%0A%20%20%20%20%22ret%22%0A%20%20end%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20def%20typed_ret%0A%20%20%20%20%22ret%22%0A%20%20end%0A%0A%20%20sig%20%7B%20params(location_id%3A%20T.nilable(T.any(String%2C%20Integer))).returns(String)%20%7D%0A%20%20def%20should_sorbet_error_but_also_does_not(location_id%20%3D%20nil)%0A%20%20%20%20%23%20this%20should%20error%2C%20because%20of%20location_id%20is%20nil%20then%20it%20will%20return%20nil%0A%20%20%20%20result%20%3D%20(ret%20if%20!location_id.nil%3F)%0A%20%20%20%20T.reveal_type(result)%0A%20%20%20%20result%0A%20%20end%0A%0A%20%20sig%20%7B%20params(location_id%3A%20T.nilable(T.any(String%2C%20Integer))).returns(String)%20%7D%0A%20%20def%20should_sorbet_error_but_also_does_not(location_id%20%3D%20nil)%0A%20%20%20%20%23%20this%20should%20error%2C%20because%20of%20location_id%20is%20nil%20then%20it%20will%20return%20nil%0A%20%20%20%20typed_ret%20if%20!location_id.nil%3F%0A%20%20end%0A%0A%20%20sig%20%7B%20params(location_id%3A%20T.nilable(T.any(String%2C%20Integer))).returns(String)%20%7D%0A%20%20def%20should_error_and_does!(location_id%20%3D%20nil)%0A%20%20%20%20%22ret%22%20if%20!location_id.nil%3F%0A%20%20end%0Aend%0A)
