### ISSUE TITLE
Autocorrect inserts T.let into method definition

### ISSUE THREAD

**Issue by bhuga** [sorbet/sorbet#3497]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Bparams(path%3A%20String).returns(Integer)%7D%0A%20%20def%20for_file(path)%0A%20%20%20%20while%20!path.empty%3F%0A%20%20%20%20%20%20return%205%20if%20rand%20%3E%200.5%0A%20%20%20%20%20%20path%20%3D%20path%5B0...(path.rindex('%2F')%20%7C%7C%200)%5D%0A%20%20%20%20end%0A%20%20%20%201%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig
  sig {params(path: String).returns(Integer)}
  def for_file(path)
    while !path.empty?
      return 5 if rand > 0.5
      path = path[0...(path.rindex('/') || 0)]
    end
    1
  end
end
```

#### Observed output

Sorbet would like to auto-correct to `def for_file(T.let(path, T.nilable(String)))`, which is invalid syntax.

```

# typed: true
class A
  extend T::Sig
  sig {params(path: String).returns(Integer)}
  def for_file(path)
    while !path.empty?
      return 5 if rand > 0.5
      path = path[0...(path.rindex('/') || 0)]
    end
    1
  end
end
editor.rb:8: Changing the type of a variable in a loop is not permitted https://srb.help/7001
     8 |      path = path[0...(path.rindex('/') || 0)]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Existing variable has type: String
  Attempting to change type to: T.nilable(String)

  Autocorrect: Use `-a` to autocorrect
    editor.rb:5: Replace with T.let(path, T.nilable(String))
     5 |  def for_file(path)
                       ^^^^
Errors: 1
```

#### Expected behavior

Sorbet should not suggest a `T.let` annotation when the first definition of the variable comes from a sig.
Or it should suggest widening the type of the argument in the sig, but getting the location information for that is harder.
- - -

**Comment by jez** [comment]
Relates to #1474

**Comment by jez** [comment]
I fixed this recently, but I don’t have a link to the pull request that fixed it handy.
