### ISSUE TITLE
Incorrect sig (missing NilClass) for Thread.join return value

### ISSUE THREAD

**Issue by djrodgerspryor** [sorbet/sorbet#3499]
The sig for `Thread.join` has it always returning a `Thread`, but the result should be nilable if a `limit` parameter is specified.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(T.untyped)%7D%0A%20%20def%20self.bar%0A%20%20%20%20Thread.new%20%7B%20sleep%202%3B%2042%20%7D.join(1)%26.value%0A%20%20end%0Aend%0A%0AFoo.bar)

```ruby
module Foo
  extend T::Sig

  sig {returns(T.untyped)}
  def self.bar
    Thread.new { sleep 2; 42 }.join(1)&.value
  end
end

Foo.bar
```

#### Observed output

```
editor.rb:8: This code is unreachable https://srb.help/7006
     8 |    Thread.new { sleep 2; 42 }.join(1)&.value
            ^
Errors: 1
```

#### Expected behavior

This code should type check correctly, because the return value of `.join(1)` will in fact be nil. See:

```
irb(main):001:1* module Foo
irb(main):002:1*
irb(main):003:2*   def self.bar
irb(main):004:2*     Thread.new { sleep 2; 42 }.join(1)&.value
irb(main):005:1*   end
irb(main):006:0> end
=> :bar
irb(main):007:0>
irb(main):008:0> Foo.bar
=> nil
```

**Comment by jez** [comment]
Fixed in #3500
