### ISSUE TITLE
Better error message on unnecessary safe navigation

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#36]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bparams(x%3A%20Integer).void%7D%0Adef%20foo(x)%0A%20%20x%26.to_s%0Aend)

```ruby
# typed: strict
extend T::Sig

sig {params(x: Integer).void}
def foo(x)
  x&.to_s
end
```

#### Observed output

```
editor.rb:6: This code is unreachable https://srb.help/7006
     6 |  x&.to_s
          ^
Errors: 1
```

#### Expected behavior

Better error message pointing to the fact that the unreachable code is fake code synthesized as a part of the way Sorbet models Ruby's conditional send mechanism ("safe navigation" / `&.`).

- - -

Sorbet treats this construct as if the user wrote:

```ruby
# typed: strict
extend T::Sig

sig {params(x: Integer).void}
def foo(x)
  magic_tmp_var = x
  if NilClass === magic_tmp_var
    nil
  else
    magic_tmp_var.to_s
  end
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bparams(x%3A%20Integer).void%7D%0Adef%20foo(x)%0A%20%20magic_tmp_var%20%3D%20x%0A%20%20if%20NilClass%20%3D%3D%3D%20magic_tmp_var%0A%20%20%20%20nil%0A%20%20else%0A%20%20%20%20magic_tmp_var.to_s%0A%20%20end%0Aend)

Which shows that in fact the error message is coming from the synthetic `nil` in the `if` condition:

```
editor.rb:8: This code is unreachable https://srb.help/7006
     8 |    nil
            ^^^
Errors: 1
```

One idea here might be: when we're creating the `if ... nil` branch, synthesize a call to something new like

```
if NilClass === magic_tmp_var
  <Magic>.<nilForCsend>(magic_tmp_var)
else
  # ...
end
```

and if we're about to report a dead code error but the first instruction of the basic block is this magic, internal intrinsic, then we report a better error message. Taking the `magic_tmp_var` as an argument to this intrinsic means that it will be easy to get a `TypeAndOrigins` for `magic_tmp_var`, so we can show what knowledge Sorbet has to know that `magic_tmp_var` is never `nil`.

**Comment by jekozyra** [comment]
Fwiw, I'd very much like to see a better message here. This confused me for a good 20 minutes.

**Comment by streeter** [comment]
Adding [a test case on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20def%20bar%0A%20%20%20%20%22bar%22%0A%20%20end%0Aend%0A%0Aclass%20B%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(A)%7D%0A%20%20def%20foo%0A%20%20%20%20A.new%0A%20%20end%0Aend%0A%0Aclass%20Command%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(b%3A%20T.nilable(B)).returns(A)%7D%0A%20%20def%20call(b%3A%20nil)%0A%20%20%20%20some_local_var%20%3D%20!b.nil%3F%20%26%26%20true%0A%20%20%20%20other_local_var%20%3D%20nil%0A%0A%20%20%20%20if%20!b.nil%3F%0A%20%20%20%20%20%20other_local_var%20%3D%20b%26.foo%26.bar%0A%20%20%20%20end%0A%0A%20%20%20%20A.new%0A%20%20end%0Aend%0A).

**Comment by Morriar** [comment]
Fixed since https://github.com/sorbet/sorbet/pull/3620
