### ISSUE TITLE
Create type aliases of T::Enum values

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#3602]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20MyEnum%20%3C%20T%3A%3AEnum%0A%20%20enums%20do%0A%20%20%20%20X%20%3D%20new%0A%20%20%20%20Y%20%3D%20new%0A%20%20%20%20Z%20%3D%20new%0A%20%20end%0Aend%0A%0Aextend%20T%3A%3ASig%0Asig%20%7Bparams(xy%3A%20T.any(MyEnum%3A%3AX%2C%20MyEnum%3A%3AY)).void%7D%20%23%20ok%0Adef%20foo(xy)%0Aend%0A%0AXY%20%3D%20T.type_alias%20%7BT.any(MyEnum%3A%3AX%2C%20MyEnum%3A%3AY)%7D%20%23%20error)

```ruby
# typed: true
class MyEnum < T::Enum
  enums do
    X = new
    Y = new
    Z = new
  end
end

extend T::Sig
sig {params(xy: T.any(MyEnum::X, MyEnum::Y)).void} # ok
def foo(xy)
end

XY = T.type_alias {T.any(MyEnum::X, MyEnum::Y)} # error
```

#### Observed output

```
editor.rb:15: Constant MyEnum::X is not a class or type alias https://srb.help/5004
    15 |XY = T.type_alias {T.any(MyEnum::X, MyEnum::Y)} # error
                                 ^^^^^^^^^
    editor.rb:4: If you are trying to define a type alias, you should use T.type_alias here
     4 |    X = new
            ^

editor.rb:15: Constant MyEnum::Y is not a class or type alias https://srb.help/5004
    15 |XY = T.type_alias {T.any(MyEnum::X, MyEnum::Y)} # error
                                            ^^^^^^^^^
    editor.rb:5: If you are trying to define a type alias, you should use T.type_alias here
     5 |    Y = new
            ^
Errors: 2
```

#### Expected behavior

The only reason why this is an error is because it's hard to implement, and when we implemented `T::Enum` at first, we punted on supporting this.

It would be a good feature to add, but it's tricky to get the implementation to fit into resolver.

- - -

**Comment by jvilk-stripe** [comment]
Fixed in https://github.com/sorbet/sorbet/pull/3762
