### ISSUE TITLE
Method with more than one parameter starting with an underscore creates invalid RBI

### ISSUE THREAD

**Issue by colinramsay** [sorbet/sorbet#3603]
This is when running `srb init`.

#### Input

I found this due to: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/stubbing/protocols/rest_json.rb#L8

``` ruby
def body_for(_a, _b, rules, data)
end
```

#### Observed output

```
  sig do
    params(
      _: ::T.untyped,
      _: ::T.untyped,
      rules: ::T.untyped,
      data: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def body_for(_, _, rules, data); end
```

#### Expected behavior

I think the correct definition should be:

```
sig do
    params(
      _a: ::T.untyped,
      _b: ::T.untyped,
      rules: ::T.untyped,
      data: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def body_for(_a, _b, rules, data); end
```

**Comment by jez** [comment]
srb init is deprecated in favor of tapioca:

https://sorbet.org/blog/2022/07/27/srb-tapioca
