### ISSUE TITLE
IDE: Place limit on number of diagnostics to report

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#3604]
### Problem

If the user makes a big change to a key symbol in a big project, Sorbet can report thousands of errors that cause VS Code to drag to a crawl (and network bottlenecks if Sorbet is running remotely). This has caused issues internally for teams doing cross-cutting changes.

### Proposed solution

Sorbet's LSP server should place a (configurable) limit on the maximum number of diagnostics to report. We should experiment to understand what the default upper bound should be (500?).

A simple implementation could enforce this restriction within Sorbet's language server. If errors are sorted prior to filtering, then Sorbet will show a consistent set of errors to the user after a slow path.

A more complex implementation could enforce this restriction within Sorbet's typechecking passes and prevent them from constructing error messages the user doesn't see. This would be a meaningful performance improvement when dealing with thousands of errors (iirc, Sorbet's fuzzy lookup strategy for close matches can be expensive), but will require dealing with error reporting in a multithreaded context. One UX downside of this approach is that the user will not see a consistent set of errors, which honestly might outweigh the performance benefits.

**Comment by akshay1992kalbhor** [comment]
Hey! Can I try this one? Can you guys help me with it?

**Comment by jvilk-stripe** [comment]
Hey @akshay1992kalbhor! Sorry, I didn't see your comment until now. I think this is easily implemented in `ErrorCollector`'s `drainErrors` method:
https://github.com/sorbet/sorbet/blob/4ae08bf2/core/ErrorCollector.cc#L20

We could change `ErrorCollector` to:
1. Accept a limit in the constructor.
2. Perform a `stable_sort` on the errors in `drainErrors` and only report the first `limit`.

Then, we can add a new command line option to `options.cc` to set the limit and pipe it through to `ErrorCollector` construction.
