### ISSUE TITLE
Using non-`fixed` constraints with `self` in `type_member` locks up sorbet.run

### ISSUE THREAD

**Issue by zanemiller-stripe** [sorbet/sorbet#3613]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20A%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member(upper%3A%20self)%0Aend)

```ruby
module A
  extend T::Generic
  # Also crashes if using `upper: self`
  Elem = type_member(lower: self)
end
```

#### Observed output
In sorbet.run the editor hard locks, presumptively crashes on the CLI.

#### Expected behavior

Should not crash

- - -

**Comment by elliottt** [comment]
I'm unable to reproduce this on sorbet.run, or the current master. Are you on an older version of sorbet?

**Comment by zanemiller-stripe** [comment]
Opening the linked `sorbet.run` consistently hard locks the tab in my browser. I haven't been able to test against the CLI yet to see what the specific behavior is in that case.
