### ISSUE TITLE
Symbol rename treats classes and modules differently

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#3664]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Base%0A%20%20%23%20does%20not%20contain%20method%20foo%0Aend%0A%0Amodule%20BaseWithMethod%0A%20%20include%20Base%0A%20%20def%20foo%0A%20%20end%0Aend%0A%0Aclass%20A%0A%20%20include%20BaseWithMethod%0A%20%20def%20foo%0A%23%20%20%20%20%20%5E%20apply-rename%3A%20%5BA%5D%20newName%3A%20bar%0A%20%20end%0Aend%0A%0Aclass%20B%0A%20%20include%20BaseWithMethod%0A%20%20def%20foo%0A%20%20end%0Aend%0A%0Aclass%20C%0A%20%20include%20Base%0A%20%20def%20foo%0A%20%20%20%20%23%20this%20one%20should%20not%20be%20renamed!%0A%20%20end%0Aend%0A%0AA.new.bar)

```ruby
# typed: true
module Base
  # does not contain method foo
end

module BaseWithMethod
  include Base
  def foo
  end
end

class A
  include BaseWithMethod
  def foo
#     ^ apply-rename: [A] newName: bar
  end
end

class B
  include BaseWithMethod
  def foo
  end
end

class C
  include Base
  def foo
    # this one should not be renamed!
  end
end

A.new.bar
```

#### Observed output

Using sorbet.run to apply the indicated rename, the output becomes

```ruby
# typed: true
module Base
  # does not contain method foo
end

module BaseWithMethod
  include Base
  def foo
  end
end

class A
  include BaseWithMethod
  def bar
#     ^ apply-rename: [A] newName: bar
  end
end

class B
  include BaseWithMethod
  def foo
  end
end

class C
  include Base
  def foo
    # this one should not be renamed!
  end
end

A.new.bar
```

Here is the diff between the original and changed:

```diff
--- before.rb   2020-11-15 21:10:18.506309379 -0800
+++ after.rb    2020-11-15 21:10:29.602258972 -0800
@@ -11,7 +11,7 @@

 class A
   include BaseWithMethod
-  def foo
+  def bar
 #     ^ apply-rename: [A] newName: bar
   end
 end
@@ -29,4 +29,4 @@
   end
 end

-A.new.foo
+A.new.bar
```

#### Expected behavior

There is no reason why modules should be treated differently from classes.
There is an existing test that shows how classes behave:

https://github.com/sorbet/sorbet/blob/2d6dde035288dda97015a53ee03ea8fd1c99f2e4/test/testdata/lsp/rename/method_class_hierarchy.rb

- - -

**Comment by jez** [comment]
cc @soam-stripe

**Comment by vilhena-stripe** [comment]
I think this is resolved by https://github.com/sorbet/sorbet/pull/3747

**Comment by soam-stripe** [comment]
Yup, your change should resolve this!
