### ISSUE TITLE
Rename symbol fails to consider all components of a method call

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#3665]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20def%20foo%3B%20end%0Aend%0Aclass%20B%0A%20%20def%20foo%3B%20end%0Aend%0A%0Aextend%20T%3A%3ASig%0Asig%20%7Bparams(x%3A%20T.any(A%2C%20B)).void%7D%0Adef%20example(x)%0A%20%20x.foo%0A%23%20%20%20%5E%20apply-rename%3A%20%5BA%5D%20newName%3A%20bar%0Aend)

```ruby
# typed: true
class A
  def foo; end
end
class B
  def foo; end
end

extend T::Sig
sig {params(x: T.any(A, B)).void}
def example(x)
  x.foo
#   ^ apply-rename: [A] newName: bar
end
```

#### Observed output

Making the indicated rename request in sorbet.run only applies the rename to the first component of the dispatch result.

Namely, it only renames `A#foo` → `A#bar`, and neglects the fact that the LSP query returned that the method call could have also been to `B#foo`.

#### Expected behavior

Either:

- We should rename each method in the dispatch result, or
- We should detect the case where there are multiple dispatch results, and abort (better than doing the wrong thing).

- - -

**Comment by jez** [comment]
cc @soam-stripe

**Comment by soam-stripe** [comment]
Thanks @jez, thanks for filing this! Yes, union types are currently not handled correctly, I'm planning to address this in upcoming changes.
