### ISSUE TITLE
Enumerable to_h is not handling all variants

### ISSUE THREAD

**Issue by garuma** [sorbet/sorbet#3668]
#### Input

[→ View on sorbet.run](https://sorbet.run/#(1..5).to_h%20%7B%7Cx%7C%20%5Bx%2C%20x%20**%202%5D%7D)

```ruby
(1..5).to_h {|x| [x, x ** 2]}
```
Extracted from second example in documentation: https://rubyapi.org/2.6/o/enumerable#method-i-to_h

#### Observed output

```
editor.rb:1: Expected T::Enumerable[[U, V]] but found T::Range[Integer] for argument arg0 https://srb.help/7002
     1 |(1..5).to_h {|x| [x, x ** 2]}
         ^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/sorbet/sorbet.rbi#L55: Method Sorbet::Private::Static.enumerable_to_h has specified arg0 as T::Enumerable[[U, V]]
    55 |      arg0: T::Enumerable[[T.type_parameter(:U), T.type_parameter(:V)]],
              ^^^^
  Got T::Range[Integer] originating from:
    editor.rb:1:
     1 |(1..5).to_h {|x| [x, x ** 2]}
         ^^^^
Errors: 1
```

#### Expected behavior

`Enumerable.to_h` supports two styles of operation, the first one (which is correctly encoded by the special definition in sorbet.rbi) is to work on an enumerable of pairs, the second (which is valid but will currently trip Sorbet) is to pass a block to transform an enumerable of any shape to the one with pairs.

- - -

While you can certainly fix this by moving the block to a preceding `map` it's still technically incorrect to encode this only restriction in Sorbet. Ideally the typecheck could intelligently apply two separate definitions of `to_h` (currently [only the one](https://github.com/sorbet/sorbet/blob/2d6dde035288dda97015a53ee03ea8fd1c99f2e4/rbi/sorbet/sorbet.rbi#L53-L59)) with the right typing information based on a block presence or not.

**Comment by elliottt** [comment]
Fixed in #4527
