### ISSUE TITLE
Hidden definitions cannot be generated for methods with more than one anonymous variable

### ISSUE THREAD

**Issue by ajoneil** [sorbet/sorbet#3674]
Methods with more than one anonymous/unnamed variable generate invalid method definitions in hidden definitions. For example, if you include the `statsd-instrument` gem in your project, there are issues:

Statsd-instrument generates a number of methods with unnamed parameters, see https://github.com/Shopify/statsd-instrument/blob/2772e56f10ca614238817167f10be86ff4a4bbb6/lib/statsd/instrument/datagram_builder.rb#L22.

This causes the hidden definitions generation to put this in `reflection.rbi`:
```ruby
class StatsD::Instrument::StatsDDatagramBuilder < StatsD::Instrument::DatagramBuilder
  sig do
    params(
      _: ::T.untyped,
      _: ::T.untyped,
      _: ::T.untyped,
      _: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def d(_, _, _, _); end

  sig do
    params(
      _: ::T.untyped,
      _: ::T.untyped,
      _: ::T.untyped,
      _: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def h(_, _, _, _); end

  sig do
    params(
      _: ::T.untyped,
      _: ::T.untyped,
      _: ::T.untyped,
      _: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def kv(_, _, _, _); end

end
```

This then causes a bunch of the following errors in `reflection.json.err`:
```
/tmp/d20201117-13-f33zr2/reflection.rbi:753996: Hash key `_` is duplicated https://srb.help/3011
      753996 |      _: ::T.untyped,
                    ^
    /tmp/d20201117-13-f33zr2/reflection.rbi:753994: First occurrence of `_` hash key
      753994 |      _: ::T.untyped,
                    ^

/tmp/d20201117-13-f33zr2/reflection.rbi:753997: Hash key `_` is duplicated https://srb.help/3011
      753997 |      _: ::T.untyped,
                    ^
    /tmp/d20201117-13-f33zr2/reflection.rbi:753994: First occurrence of `_` hash key
      753994 |      _: ::T.untyped,
```

This issue with `statsd-instrument` as well as related issue #3603 with `aws-sdk-core` has meant we've had to lock our project to sorbet 0.5.5944, which is the last known release without these issues. It's broken in 0.5.6001, so the issues must've been introduced between those two versions.

**Comment by jez** [comment]
Thanks. We should probably stop emitting those useless `sig` annotations when generating the intermediate reflection.rbi.

**Comment by aprocter-stripe** [comment]
@jez I think this should be the scene of the crime, right?

https://github.com/sorbet/sorbet/blob/614a7dfe496ecc4817e19d36cb0e93649b0f3ed1/gems/sorbet/lib/serialize.rb#L168-L178

If I understand correctly, just tweaking this loop to _not_ emit signatures should be sufficient. Should be a pretty easy fix for anyone who has a few spare cycles.

**Comment by franciscoj** [comment]
Maybe this issue is related https://github.com/sorbet/sorbet/issues/3561
