### ISSUE TITLE
Ternary operator not filtering out NilClass.

### ISSUE THREAD

**Issue by jcoyne** [sorbet/sorbet#3689]
#### Input

```ruby
    sig { returns(String) }
    def embargo_date
      work.embargo_date ? work.embargo_date.to_formatted_s(:long) : 'Immediately'
    end

    sig { returns(Work) }
    attr_reader :work
```

#### Observed output

```
```
srb tc
app/components/works/detail_component.rb:42: Method to_formatted_s does not exist on NilClass component of T.nilable(Date) https://srb.help/7003
    42 |      work.embargo_date ? work.embargo_date.to_formatted_s(:long) : 'Immediately'
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    app/components/works/detail_component.rb:42: Replace with T.must(work.embargo_date)
    42 |      work.embargo_date ? work.embargo_date.to_formatted_s(:long) : 'Immediately'
                                  ^^^^^^^^^^^^^^^^^
Errors: 1
```
```

#### Expected behavior

The ternary should ensure that we're not looking at the NilClass.

```
Sorbet typechecker 0.5.5994 git 83fcb0939893f7a328dc75962a23479eca4e9422 debug_symbols=true clean=1
```

**Comment by jcoyne** [comment]
Changing the code to
```ruby
    def embargo_date
      if work.embargo_date
        work.embargo_date.to_formatted_s(:long)
      else
        'Immediately'
      end
    end
```
 does not change the result:

```
$ be srb
app/components/works/detail_component.rb:43: Method to_formatted_s does not exist on NilClass component of T.nilable(Date) https://srb.help/7003
    43 |        work.embargo_date.to_formatted_s(:long)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    app/components/works/detail_component.rb:43: Replace with T.must(work.embargo_date)
    43 |        work.embargo_date.to_formatted_s(:long)
                ^^^^^^^^^^^^^^^^^
Errors: 1
```

**Comment by froydnj** [comment]
See:

https://sorbet.org/docs/faq#why-does-sorbet-think-this-is-nil-i-just-checked-that-its-not
https://sorbet.org/docs/flow-sensitive#limitations-of-flow-sensitivity

Rewriting your example to:

```ruby
def embargo_date
  date = work.embargo_date
  if date
    date.to_formatted_s(:long)
  else
    'Immediately'
  end
end
```

should work properly.

**Comment by jcoyne** [comment]
@froydnj Thank you for taking the time to explain it to me.  It is unfortunate that sorbet can't handle this.
