### ISSUE TITLE
"Did you mean" suggestions are suggesting "PkgRoot::" prefix when they shouldn't

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#3697]
#### Input & observed output

I don't know how to reproduce packaging related errors on sorbet.run

![out](https://user-images.githubusercontent.com/5544532/99712134-7c3fa800-2a57-11eb-9684-a6e11ba18da5.gif)

#### Expected behavior

It should not put `PkgRoot::` in the suggestion.

- - -

**Comment by damolina-stripe** [comment]
+1
