### ISSUE TITLE
Instance variables within threads

### ISSUE THREAD

**Issue by theorygeek** [sorbet/sorbet#3741]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20initialize%0A%20%20%20%20%40stopped%20%3D%20T.let(false%2C%20T%3A%3ABoolean)%0A%20%20end%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20start%0A%20%20%20%20%40stopped%20%3D%20false%0A%20%20%20%20Thread.new%20do%0A%20%20%20%20%20%20loop%20do%0A%20%20%20%20%20%20%20%20break%20if%20%40stopped%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20stop%0A%20%20%20%20%40stopped%20%3D%20true%0A%20%20end%0Aend%0A)

```ruby
# typed: strict

class Foo
  extend T::Sig

  sig {void}
  def initialize
    @stopped = T.let(false, T::Boolean)
  end

  sig {void}
  def start
    @stopped = false
    Thread.new do
      loop do
        break if @stopped
      end
    end
  end

  sig {void}
  def stop
    @stopped = true
  end
end
```

#### Observed output

```
editor.rb:16: This code is unreachable https://srb.help/7006
    16 |        break if @stopped
                ^^^^^
Errors: 1
```

#### Expected behavior

Sorbet treats instance variables similarly to local variables. But it's possible for an instance variable's value to change, particularly when threads are involved.

Sorbet should probably treat instance variables more like method calls, where the value isn't guaranteed to be the same unless it's extracted to a local variable.

- - -

**Comment by DarkDimius** [comment]
Dupe of https://github.com/sorbet/sorbet/issues/42
