### ISSUE TITLE
Accepts `nil` as default in `T::Struct`

### ISSUE THREAD

**Issue by thor27** [sorbet/sorbet#3748]
### Problem
Hi,

Imagine I have in my project a `T::Struct` class:

```ruby
class Car < T::Struct
  const :color, String, default: "black"
  const :model, String, default: "civic"
  const :year, Integer, default: 2020
end
```

and we have in the code the following:

```ruby
sig do
  params(
    color: T.nilable(String),
    model: T.nilable(String),
    year: T.nilable(Integer)
  ).returns(Car)
end
def buy_car(color: nil, model: nil, year: nil)
  Car.new(
    color: color,
    model: model,
    year: year
  )
end
```

Example in [Sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Car%20%3C%20T%3A%3AStruct%0A%20%20const%20%3Acolor%2C%20String%2C%20default%3A%20%22black%22%0A%20%20const%20%3Amodel%2C%20String%2C%20default%3A%20%22civic%22%0A%20%20const%20%3Ayear%2C%20Integer%2C%20default%3A%202020%0Aend%0A%0Aclass%20MyCar%0A%20%20extend(T%3A%3ASig)%0A%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20color%3A%20T.nilable(String)%2C%0A%20%20%20%20%20%20model%3A%20T.nilable(String)%2C%0A%20%20%20%20%20%20year%3A%20T.nilable(Integer)%0A%20%20%20%20).returns(Car)%0A%20%20end%0A%20%20def%20buy_car(color%3A%20nil%2C%20model%3A%20nil%2C%20year%3A%20nil)%0A%20%20%20%20Car.new(%0A%20%20%20%20%20%20color%3A%20color%2C%0A%20%20%20%20%20%20model%3A%20model%2C%0A%20%20%20%20%20%20year%3A%20year%0A%20%20%20%20)%0A%20%20end%0Aend%0A%0A)

What is the best way to fix this code, **keeping static and dynamic sorbet validation** on this, and without  copying the default values from the `Car < T::Struct` inside the `buy_car` method?

Basically how can we consider that passing `nil` is the same as not passing the value (as if we do a `compact` on the arguments)?

Things we tried and don't work:
[Overiding the intialize](https://sorbet.run/#%23typed%3A%20strict%0Aclass%20SomeStruct%20%3C%20T%3A%3AStruct%0A%20%20extend(T%3A%3ASig)%0A%0A%20%20const(%3Aarg1%2C%20String)%0A%20%20const(%3Aarg2%2C%20T%3A%3AArray%5BString%5D)%0A%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20arg1%3A%20T.nilable(String)%2C%0A%20%20%20%20%20%20arg2%3A%20T.nilable(T%3A%3AArray%5BString%5D)%0A%20%20%20%20).void%0A%20%20end%0A%20%20def%20initialize(%0A%20%20%20%20arg1%3A%20nil%2C%0A%20%20%20%20arg2%3A%20nil%0A%20%20)%0A%20%20%20%20%40arg1%20%3D%20T.let(arg1%20%7C%7C%20%22DEFAULT_VALUE%22%2C%20String)%0A%20%20%20%20%40arg2%20%3D%20T.let(arg2%20%7C%7C%20%5B%5D%2C%20T%3A%3AArray%5BString%5D)%0A%20%20end%0Aend%0A)
[Using super](https://sorbet.run/#%23typed%3A%20strict%0Aclass%20SomeStruct%20%3C%20T%3A%3AStruct%0A%20%20extend(T%3A%3ASig)%0A%0A%20%20const(%3Aarg1%2C%20String)%0A%20%20const(%3Aarg2%2C%20T%3A%3AArray%5BString%5D)%0A%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20arg1%3A%20T.nilable(String)%2C%0A%20%20%20%20%20%20arg2%3A%20T.nilable(T%3A%3AArray%5BString%5D)%0A%20%20%20%20).void%0A%20%20end%0A%20%20def%20initialize(%0A%20%20%20%20arg1%3A%20nil%2C%0A%20%20%20%20arg2%3A%20nil%0A%20%20)%0A%20%20%20%20super(%0A%20%20%20%20%20%20arg1%3A%20arg1%20%7C%7C%20%22DEFAULT_VALUE%22%2C%0A%20%20%20%20%20%20arg2%3A%20arg2%20%7C%7C%20%20T%3A%3AArray%5BString%5D%2C%0A%20%20%20%20)%0A%20%20end%0Aend%0A)

The only way around I found, is doing something like this:

[sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Car%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20const%20%3Acolor%2C%20String%0A%20%20const%20%3Amodel%2C%20String%0A%20%20const%20%3Ayear%2C%20Integer%0A%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20color%3A%20T.nilable(String)%2C%0A%20%20%20%20%20%20model%3A%20T.nilable(String)%2C%0A%20%20%20%20%20%20year%3A%20T.nilable(Integer)%0A%20%20%20%20).returns(Car)%0A%20%20end%0A%20%20def%20self.create(color%3A%20%2C%20model%3A%20%2C%20year%3A%20)%0A%20%20%20%20Car.new(%0A%20%20%20%20%20%20color%3A%20color.nil%3F%20%3F%20%22black%22%20%3A%20color%2C%0A%20%20%20%20%20%20model%3A%20model.nil%3F%20%3F%20%22civic%22%20%3A%20model%2C%0A%20%20%20%20%20%20year%3A%20year.nil%3F%20%3F%202020%20%3A%20year%0A%20%20%20%20)%0A%20%20end%0Aend%0A%0A%0A%0Aclass%20MyCar%0A%20%20extend(T%3A%3ASig)%0A%0A%20%20sig%20do%0A%20%20%20%20params(%0A%20%20%20%20%20%20color%3A%20T.nilable(String)%2C%0A%20%20%20%20%20%20model%3A%20T.nilable(String)%2C%0A%20%20%20%20%20%20year%3A%20T.nilable(Integer)%0A%20%20%20%20).returns(Car)%0A%20%20end%0A%20%20def%20buy_car(color%3A%20nil%2C%20model%3A%20nil%2C%20year%3A%20nil)%0A%20%20%20%20Car.create(%0A%20%20%20%20%20%20color%3A%20color%2C%0A%20%20%20%20%20%20model%3A%20model%2C%0A%20%20%20%20%20%20year%3A%20year%0A%20%20%20%20)%0A%20%20end%0Aend)

```ruby
# typed: true
class Car < T::Struct
  extend T::Sig

  const :color, String
  const :model, String
  const :year, Integer

  sig do
    params(
      color: T.nilable(String),
      model: T.nilable(String),
      year: T.nilable(Integer)
    ).returns(Car)
  end
  def self.create(color: , model: , year: )
    Car.new(
      color: color.nil? ? "black" : color,
      model: model.nil? ? "civic" : model,
      year: year.nil? ? 2020 : year
    )
  end
end



class MyCar
  extend(T::Sig)

  sig do
    params(
      color: T.nilable(String),
      model: T.nilable(String),
      year: T.nilable(Integer)
    ).returns(Car)
  end
  def buy_car(color: nil, model: nil, year: nil)
    Car.create(
      color: color,
      model: model,
      year: year
    )
  end
end
```

The problem is that this is too verbose and could really increase in size as we add more attributes to this `T::Struct`

### Proposed solution

Add a flag on the attribute that informs it should accepts `nil` as default, something like:

```ruby
class Car < T::Struct
  const :color, String, default: "black", accepts_nil_as_default: true
  const :model, String, default: "civic", accepts_nil_as_default: true
  const :year, Integer, default: 2020, accepts_nil_as_default: true
end
```

**Comment by jez** [comment]
Your suggested workaround is what we recommend.

Thanks for the suggestion! But I think we'll pass. It adds complexity for a little less typing. Sorbet prefers being explicit to being concise.
