### ISSUE TITLE
Sorbet thinks empty array literal (`[]`) is T::Array[T.untyped] instead of a zero-tuple

### ISSUE THREAD

**Issue by jeffcarbs** [sorbet/sorbet#3751]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20%7B%20params(x%3A%20T%3A%3AArray%5BString%5D).void%20%7D%0A%20%20def%20foo1(x)%0A%20%20%20%20T.reveal_type(x)%20%23%20T%3A%3AArray%5BString%5D%20(as%20expected)%0A%20%20end%0A%0A%20%20sig%20%7B%20params(x%3A%20T%3A%3AArray%5BString%5D).void%20%7D%0A%20%20def%20foo2(x%20%3D%20%5B%5D)%0A%20%20%20%20T.reveal_type(x)%20%23%20T%3A%3AArray%5BT.untyped%5D%20(expected%20T%3A%3AArray%5BString%5D)%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig
  
  sig { params(x: T::Array[String]).void }
  def foo1(x)
    T.reveal_type(x) # T::Array[String] (as expected)
  end

  sig { params(x: T::Array[String]).void }
  def foo2(x = [])
    T.reveal_type(x) # T::Array[T.untyped] (expected T::Array[String])
  end
end
```

#### Observed output

```
editor.rb:7: Revealed type: T::Array[String] https://srb.help/7014
     7 |    T.reveal_type(x) # T::Array[String] (as expected)
            ^^^^^^^^^^^^^^^^
  From:
    editor.rb:6:
     6 |  def foo1(x)
                   ^

editor.rb:12: Revealed type: T::Array[T.untyped] https://srb.help/7014
    12 |    T.reveal_type(x) # T::Array[T.untyped] (expected T::Array[String])
            ^^^^^^^^^^^^^^^^
  From:
    editor.rb:11:
    11 |  def foo2(x = [])
                   ^
    editor.rb:11:
    11 |  def foo2(x = [])
                       ^^
Errors: 2
```

#### Expected behavior

Expected `x` to be `T::Array[String]` in both methods (i.e. regardless of the default value).

**Comment by jez** [comment]
https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20%7B%20params(x%3A%20T%3A%3AArray%5BString%5D).void%20%7D%0A%20%20def%20foo1(x)%0A%20%20%20%20x%20%3D%20%5B%5D%0A%20%20%20%20T.reveal_type(x)%0A%20%20end%0Aend

This has nothing to do with defaults, this is just more or less how sorbet works.

**Comment by jeffcarbs** [comment]
That's kind of what I figured was going on. In that case, the workaround could be:
```ruby
sig { params(x: T::Array[String]).void }
def foo2(x = T.let([], T::Array[String]))
```

It's a bit counter-intuitive from a user perspective though. While I understand what's happening based on how sorbet works, in my head the type in the `sig` is me telling sorbet the type of `x` so why do I need to tell it again via `T.let`?

I wonder if would be possible (or advisable) for sorbet to be smarter here 🤔 Similar to how sorbet is able to infer the types of instance variables in the initializer: https://sorbet.org/docs/type-annotations#limitations-on-instance-variable-inference.

**Comment by jez** [comment]
There are some changes in #3822 that fix this issue. We might be able to break out those changes in a way that let us fix this issue while avoiding the mess that is landing the rest of that PR.
