### ISSUE TITLE
Nested generics lose type information

### ISSUE THREAD

**Issue by chae-stripe** [sorbet/sorbet#3791]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%0A%20%20%20%20type_parameters(%3AU)%0A%20%20%20%20.params(x%3A%20T.type_parameter(%3AU))%0A%20%20%20%20.returns(T.type_parameter(%3AU))%0A%20%20%7D%0A%20%20def%20generic_nested(x)%0A%20%20%20%20x%0A%20%20end%0A%0A%20%20sig%20%7B%0A%20%20%20%20type_parameters(%3AU)%0A%20%20%20%20.params(x%3A%20T.all(T.type_parameter(%3AU)%2C%20T.any(String%2C%20Integer)))%0A%20%20%20%20.returns(T.all(T.type_parameter(%3AU)%2C%20T.any(String%2C%20Integer)))%0A%20%20%7D%0A%20%20def%20generic(x)%0A%20%20%20%20generic_nested(x)%0A%20%20end%0A%0A%20%20def%20test%0A%20%20%20%20v1%20%3D%20T.let(generic(1017)%2C%20Integer)%0A%20%20%20%20v2%20%3D%20T.let(generic(%22hi%22)%2C%20String)%0A%20%20end%0Aend)

```ruby
# typed: true

class A
  extend T::Sig

  sig {
    type_parameters(:U)
    .params(x: T.type_parameter(:U))
    .returns(T.type_parameter(:U))
  }
  def generic_nested(x)
    x
  end

  sig {
    type_parameters(:U)
    .params(x: T.all(T.type_parameter(:U), T.any(String, Integer)))
    .returns(T.all(T.type_parameter(:U), T.any(String, Integer)))
  }
  def generic(x)
    generic_nested(x)
  end

  def test
    v1 = T.let(generic(1017), Integer)
    v2 = T.let(generic("hi"), String)
  end
end
```

#### Observed output

```
editor.rb:21: Returning value that does not conform to method result type https://srb.help/7005
    21 |    generic_nested(x)
            ^^^^^^^^^^^^^^^^^
  Expected T.all(A#generic#U, T.any(String, Integer))
    editor.rb:20: Method generic has return type T.all(A#generic#U, T.any(String, Integer))
    20 |  def generic(x)
          ^^^^^^^^^^^^^^
  Got T.any(String, Integer) originating from:
    editor.rb:21:
    21 |    generic_nested(x)
            ^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Successful sorbet check
- - -

**Comment by jez** [comment]
It looks like this was fixed a while ago. I've made a PR to include this test in Sorbet's test suite. Thanks for the report, and sorry for the delay in acknowledging.
