### ISSUE TITLE
T::Struct causes false errors during `srb init`

### ISSUE THREAD

**Issue by AaronC81** [sorbet/sorbet#3792]
This was spotted by @manhhung741 and @jsmestad trying to use Parlour with recent versions of Sorbet: [related Parlour issue](https://github.com/AaronC81/parlour/issues/110)

To reproduce:

1. Create a Gemfile containing Parlour 4.0.1 (the latest non-prerelease version) and the latest Sorbet
2. `bundle install`
3. `bundle exec srb init` and `y`

I get:

```
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
Generating: sorbet/rbi/hidden-definitions/
Requiring all of your code
Naming all Modules
Naming Bundler::ThorGot LoadError when trying to get nested name Bundler::Thor::RakeCompat
Naming Struct/home/aaron/src/sorbet/gems/sorbet/lib/real_stdlib.rb:77: warning: constant Struct::Tms is deprecated
Generating /tmp/d20201214-74918-bjoxsq/reflection.rbi with 1077 modules and 43 aliases
Printing your code's symbol table into /tmp/d20201214-74918-bjoxsq/from-source.json
Printing /tmp/d20201214-74918-bjoxsq/reflection.rbi's symbol table into /tmp/d20201214-74918-bjoxsq/reflection.json
Traceback (most recent call last):
        6: from /home/aaron/src/sorbet/gems/sorbet/bin/srb-rbi:237:in `<main>'
        5: from /home/aaron/src/sorbet/gems/sorbet/bin/srb-rbi:196:in `main'
        4: from /home/aaron/src/sorbet/gems/sorbet/bin/srb-rbi:121:in `init'
        3: from /home/aaron/src/sorbet/gems/sorbet/bin/srb-rbi:232:in `block in make_step'
        2: from /home/aaron/src/sorbet/gems/sorbet/lib/hidden-definition-finder.rb:38:in `main'
        1: from /home/aaron/src/sorbet/gems/sorbet/lib/hidden-definition-finder.rb:47:in `main'
/home/aaron/src/sorbet/gems/sorbet/lib/hidden-definition-finder.rb:151:in `write_constants': /tmp/d20201214-74918-bjoxsq/reflection.rbi had unexpected errors. Check this file for a clue: /tmp/d20201214-74918-bjoxsq/reflection.json.err (RuntimeError)
```

...where that .err file contains:

```
/home/aaron/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parlour-4.0.1/rbi/parlour.rbi:166: The instance variable `@overridable` must be declared inside `initialize` or declared nilable https://srb.help/5005
     166 |      prop :overridable, T::Boolean
                      ^^^^^^^^^^^

/home/aaron/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parlour-4.0.1/rbi/parlour.rbi:167: The instance variable `@override` must be declared inside `initialize` or declared nilable https://srb.help/5005
     167 |      prop :override, T::Boolean
                      ^^^^^^^^

/home/aaron/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parlour-4.0.1/rbi/parlour.rbi:168: The instance variable `@abstract` must be declared inside `initialize` or declared nilable https://srb.help/5005
     168 |      prop :abstract, T::Boolean
                      ^^^^^^^^

/home/aaron/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parlour-4.0.1/rbi/parlour.rbi:169: The instance variable `@final` must be declared inside `initialize` or declared nilable https://srb.help/5005
     169 |      prop :final, T::Boolean
                      ^^^^^
```

These `prop`s are within a `T::Struct` - I don't think these errors should be occurring, since `T::Struct` should handle the instance variables for me. The very same RBI also passes `srb tc` just fine, so it seems to just be an issue for `srb init` :confused: 

This issue started occurring on Sorbet 0.5.6140 - a bisect narrows the cause down to 6dff224791eed56739f4e331ecc635faf309a983.

**Comment by jaredbeck** [comment]
> This issue started occurring on Sorbet 0.5.6140 ..

I can confirm that downgrading to `< 0.5.6140` worked for me.

```ruby
# Gemfile

  # sorbet 0.5.6140 has a bug: `srb init` crashes
  # - https://github.com/sorbet/sorbet/issues/3792
  # - https://github.com/AaronC81/parlour/issues/110
  gem 'sorbet', '< 0.5.6140'
```

**Comment by jvilk-stripe** [comment]
Thanks for the report! I've reproduced the issue today and will dig in next week.

**Comment by jvilk-stripe** [comment]
Here's the root cause of the error we're seeing here:

[View on Sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0A%23%20From%20parlour.rbi%0Amodule%20Parlour%0A%20%20class%20TypeParser%0A%20%20%20%20class%20IntermediateSig%20%3C%20T%3A%3AStruct%0A%20%20%20%20%20%20prop%20%3Aoverridable%2C%20T%3A%3ABoolean%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0A%23%20From%20reflection.rbi%0Aclass%20Parlour%3A%3ATypeParser%3A%3AIntermediateSig%20%3C%20T%3A%3AStruct%0A%20%20sig%20%7Breturns(%3A%3AT.untyped)%7D%0A%20%20def%20overridable()%3B%20end%0Aend%0A)
```ruby
# typed: true

# From parlour.rbi
module Parlour
  class TypeParser
    class IntermediateSig < T::Struct
      prop :overridable, T::Boolean
    end
  end
end

# From reflection.rbi
class Parlour::TypeParser::IntermediateSig < T::Struct
  sig {returns(::T.untyped)}
  def overridable(); end
end
````

This causes a problem even in the version of Sorbet that works with `srb init` as it's redefining the same method twice, and it seems like the working version of Sorbet generates `reflection.rbi` the same way.

**Comment by jvilk-stripe** [comment]
Either way, Sorbet should _not_ be pulling in RBI files while generating `reflection.json`, so https://github.com/sorbet/sorbet/pull/3828 will fix it.

**Comment by jaredbeck** [comment]
> .. #3828 will fix it.

I tried to test this, but it looks like the nightly builds are broken? There hasn't been a nightly since Saturday. Not complaining, just letting you know in case the nightly build needs attention.

**Comment by jvilk-stripe** [comment]
@jaredbeck it looks like we published a build today:

https://rubygems.org/gems/sorbet/versions

**Comment by jez** [comment]
https://buildkite.com/sorbet/sorbet/builds/14056#23e95448-78f4-47d4-92b4-b68b111474b8/123-145

Dec 20 there was no new commits to publish, so the version 0.5.6173 was already published

**Comment by AaronC81** [comment]
Thanks all, looks like the corresponding Parlour issue has been fixed by this!

**Comment by jaredbeck** [comment]
> Dec 20 there was no new commits to publish ..

Ah, that makes sense. Sorry for the false alarm.

**Comment by jaredbeck** [comment]
After updating to 0.5.6187, I am able to run `init` again. 

It still takes 15 minutes and 4GB of RAM, but that's [another story](https://github.com/sorbet/sorbet/issues/3753). 😄
