### ISSUE TITLE
Provide more partial type information to blocks of generic methods

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#38]
will allow to typecheck https://sorbet.run/#extend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters(%3AU)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20x%3A%20T.type_parameter(%3AU)%2C%0A%20%20%20%20%20%20cb%3A%20T.proc.params(arg0%3A%20T.type_parameter(%3AU)).void)%0A%20%20%20%20.void%0Aend%0Adef%20foo(x%2C%20%26cb)%0A%20%20yield%20x%0Aend%0A%0Afoo(1)%20%7B%7Cx%7C%20T.reveal_type(x)%7D

 

originally reported by @dlee-stripe.

Comments:
16/Nov/18 8:29 PM;dmitry;We currently approximate type of block argument in

[https://git.corp.stripe.com/stripe-internal/sorbet/blob/f6c88da9420989275a2884f70d91c1b025c19608/core/types/typemaps.cc#L53-L63]

 In this case, for type variable we only have a lower bound(the function _should_ accept arrays), thus, when asked about upper bound we say it can be whatever, as long as it's a supertype of array, which is "whatever".

16/Nov/18 8:35 PM;dmitry;A workaround: https://sorbet.run/#extend%20T%3A%3AHelpers%0A%0A%0Aclass%20Store%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Value%20%3D%20type_member%0A%20%20%0A%20%20sig%20%7Bparams(data%3A%20T%3A%3AArray%5BValue%5D).void%7D%0A%20%20def%20initialize(data)%0A%20%20%20%20%40data%20%3D%20T.let(data%2C%20T%3A%3AArray%5BValue%5D)%0A%20%20end%0A%20%20%0A%20%20sig%20do%0A%20%20%20%20params(keyer%3A%20T.proc.params(value%3A%20Value).returns(String))%0A%20%20%20%20.returns(T%3A%3AHash%5BString%2C%20Value%5D)%0A%20%20end%0A%20%20def%20key_by(%26keyer)%0A%20%20%20%20%20result%20%3D%20%7B%7D%0A%20%20%20%20%20%40data.each%20do%20%7Citem%7C%0A%20%20%20%20%20%20%20result%5Byield%20item%5D%20%3D%20item%0A%20%20%20%20%20end%0A%20%20%20%20%20%20result%0A%20%20end%0Aend%0A%0A%0Asig%20%7Bparams(people%3A%20T%3A%3AArray%5B%7Bname%3A%20String%7D%5D).returns(T%3A%3AHash%5BString%2C%20%7Bname%3A%20String%7D%5D)%7D%0Adef%20by_name(people)%0A%20%20Store%5B%7Bname%3A%20String%7D%5D.new(people).key_by%20%7B%7Cx%7C%20x%5B%3Aname%5D%7D%0Aend%0A%0A

29/Nov/18 12:40 AM;dmitry;Another way to trigger this outside blocks https://sorbet.run/#class%20Monoid%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%0A%20%20%0A%20%20sig%20%7Bparams(zero%3A%20Elem%2C%20add%3A%20T.proc.params(x%3A%20Elem%2C%20y%3A%20Elem).returns(Elem)).void%7D%0A%20%20def%20initialize(zero%2C%20add)%0A%20%20%20%20%40zero%20%3D%20zero%0A%20%20%20%20%40add%20%3D%20add%0A%20%20end%0A%0A%20%20sig%20%7Breturns(Elem)%7D%0A%20%20attr_reader%20%3Azero%0A%20%20%0A%20%20sig%20%7Breturns(T.proc.params(x%3A%20Elem%2C%20y%3A%20Elem).returns(Elem))%7D%0A%20%20attr_reader%20%3Aadd%0Aend%0A%0A%0A%0Amodule%20Program%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AU)%0A%20%20%20%20.params(m%3A%20Monoid%5BT.type_parameter(%3AU)%5D%2C%20x%3A%20T.type_parameter(%3AU)%2C%20y%3A%20T.type_parameter(%3AU))%0A%20%20%20%20.returns(T.type_parameter(%3AU))%0A%20%20end%0A%20%20def%20run(m%2C%20x%2C%20y)%0A%20%20%20%20m.add.call(x%2C%20y)%0A%20%20end%0A%20%20%0A%20%20%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AU)%0A%20%20%20%20.params(xs%3A%20T%3A%3AArray%5BT.type_parameter(%3AU)%5D%2C%20m%3A%20Monoid%5BT.type_parameter(%3AU)%5D)%0A%20%20%20%20.returns(T.type_parameter(%3AU))%0A%20%20end%0A%20%20def%20reduce(xs%2C%20m)%0A%20%20%20%20if%20xs.empty%3F%0A%20%20%20%20%20%20m.zero%0A%20%20%20%20else%0A%20%20%20%20%20%20curr%20%3D%20m.zero%0A%20%20%20%20%20%20for%20x%20in%20xs%0A%20%20%20%20%20%20%20%20curr%20%3D%20m.add.call(curr%2C%20x)%0A%20%20%20%20%20%20end%0A%20%20%20%20%20%20curr%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20def%20main()%0A%20%20%20%20monoidForInteger%20%3D%20Monoid%5BInteger%5D.new(0%2C%20Proc2.new%20%7B%20%7Cx%2C%20y%7C%20x%20%2B%20y%20%7D)%0A%20%20%20%20integers%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%0A%0A%20%20%20%20%23%23%20this%20does%20not%20work%0A%20%20%20%20res1%20%3D%20reduce(integers%2C%20monoidForInteger)%0A%0A%20%20%20%20%23%20this%20works%0A%20%20%20%20res2%20%3D%20reduce(integers%2C%20Monoid.new(0%2C%20Proc2.new%20%7B%20%7Cx%2C%20y%7C%20x%20%2B%20y%20%7D))%0A%20%20end%0Aend%0A%0A

Originally reported by @jez-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1435

**Comment by alexander-stripe** [comment]
Here's another example:
https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AT)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20arr%3A%20T%3A%3AArray%5BT.type_parameter(%3AT)%5D%2C%0A%20%20%20%20%20%20blk%3A%20T.proc.params(el%3A%20T.type_parameter(%3AT)).returns(T%3A%3ABoolean)%0A%20%20%20%20)%0A%20%20%20%20.returns(%5BT%3A%3AArray%5BT.type_parameter(%3AT)%5D%2C%20T%3A%3AArray%5BT.type_parameter(%3AT)%5D%5D)%0A%20%20end%0A%20%20def%20self.partition(arr%2C%20%26blk)%0A%20%20%20%20x%20%3D%20arr.select(%26blk)%0A%20%20%20%20y%20%3D%20arr.reject(%26blk)%0A%20%20%20%20%5Bx%2C%20y%5D%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20x%2C%20y%20%3D%20A.partition(%5B1%2C%202%2C%203%2C%204%5D%2C%20%26%3Aeven%3F)%0Aend
