### ISSUE TITLE
Explicitly declaring `initialize` `private` results in an error despite the fact that `initialize` is always `private` anyway

### ISSUE THREAD

**Issue by JoergWMittag** [sorbet/sorbet#3837]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).void%7D%0A%20%20private%20def%20initialize(x)%20end%0Aend%0A%0AA.new(0)%20%20%0A%0Ap%20A.private_instance_methods(false).include%3F(%3Ainitialize)%0A%23%3D%3E%20true)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: Integer).void}
  private def initialize(x) end
end

A.new(0)  

p A.private_instance_methods(false).include?(:initialize)
#=> true
```

#### Observed output

```
editor.rb:9: Non-private call to private method initialize on A https://srb.help/7031
     9 |A.new(0)  
        ^^^^^^^^
    editor.rb:6: Defined in A here
     6 |  private def initialize(x) end
                  ^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

This should not be an error, since it does not fail at runtime:

```sh
ruby editor.rb
# true
```

In fact, since [`#initialize` is *always* `private`](https://www.ruby-forum.com/t/private-initialize/154334/3) even when not explicitly declared so, unless *explicitly* being declared `protected` or `public`, this would essentially mean that *every* use of [`Class#new`](https://ruby-doc.org/core/Class.html#method-i-new) would *always* be an error, which is clearly not the case.

If I slightly modify the code, it passes:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).void%7D%0A%20%20def%20initialize(x)%20end%0Aend%0A%0AA.new(0)%20%20%0A%0Ap%20A.private_instance_methods(false).include%3F(%3Ainitialize)%0A%23%3D%3E%20true)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: Integer).void}
  def initialize(x) end
end

A.new(0)  

p A.private_instance_methods(false).include?(:initialize)
#=> true
```

Despite the fact that this code is 100% semantically identical to the first one, since `#initialize` is *still* `private` here anyway.

- - -

My *guess* is that Sorbet doesn't "know" about the special treatment of `initialize` in Ruby and thus treats it as a normal method. My second guess is that Sorbet contains a definition of `Class#new` that looks like this:

```ruby
class Class
  def new(...)
    obj = allocate
    obj.initialize(...)
    obj
  end
end
```

This means that as long as Sorbet *thinks* `initialize` is `public`, everything is honky-dory, but as soon as it *thinks* it is `private`, it fails.

However, the *actual* implementation of `Class#new` are more like this:

```ruby
class Class
  def new(...)
    obj = allocate
    obj.__send__(:initialize, ...)
    obj
  end
end
```

If my assumptions are correct, there are two bugs in Sorbet that *normally* cancel each other out:

* The definition of `Class#new` is wrong. This *would* mean that you would always get an error because `initialize` is always `private`, except 
* The default visibility for `initialize` is also wrong.

*However*, I have not checked those assumptions, so I could be completely off.

**Comment by paracycle** [comment]
Indeed, this has started causing problems with our Sorbet version bump at Shopify as well. I think the root cause is that the `new` intrinsic in Sorbet is respecting the `private` label of `initialize` when it really shouldn't since that does not match the runtime behaviour of Ruby.

**Comment by alekstorm** [comment]
The existing behavior has actually come in handy for us; explicitly declaring `initialize` private is a common mistake, when the user means to use `private_class_method :new`. When this bug gets fixed, it would be nice to have a dedicated error/warning for explicitly-private `initialize`.

**Comment by jez** [comment]
> The existing behavior has actually come in handy for us; explicitly declaring `initialize` private is a common mistake, when the user means to use `private_class_method :new`. When this bug gets fixed, it would be nice to have a dedicated error/warning for explicitly-private `initialize`.

Unfortunately to fix this bug I'm going to have to regress this "nice to have" side effect.

In any case, I think this is better left to a custom Rubocop rule, rather than trying to build it into Sorbet.
