### ISSUE TITLE
Master tests failures when rubyfmt disabled

### ISSUE THREAD

**Issue by dpkp** [sorbet/sorbet#3854]
#### Input

On clean master w/o enabling rubyfmt:
```
./bazel test //test/lsp:test_incremental-lsp-changes
```

#### Observed output

```
==================== Test output for //test/lsp:test_incremental-lsp-changes:
--- /dev/fd/63	2020-12-30 17:04:36.000000000 +0000
+++ /dev/fd/62	2020-12-30 17:04:36.000000000 +0000
@@ -16,7 +16,7 @@
                 ]
             },
             "definitionProvider": true,
-            "documentFormattingProvider": true,
+            "documentFormattingProvider": false,
             "documentHighlightProvider": true,
             "documentSymbolProvider": true,
             "hoverProvider": true,
================================================================================
```

#### Expected behavior

This caused some confusion when working on a patch locally. I assumed that clean master passed all tests, and found these failures when testing my patch. After some headscratching and investigation it looks like these are caused by rubyfmt being disabled, which was recently changed to an experimental feature in #3566 .

Same issue applies to:
```
//test/lsp:test_workspaceSymbol
//test/lsp:test_alias-incremental
//test/lsp:test_no-trailing-newline
```

**Comment by izquierdo** [comment]
I've also experienced this issue today on clean master with:

```sh
bazel test //test/lsp:test_incremental-lsp-changes --config=test-sanitized-linux
```

**Comment by jez** [comment]
We've since disabled the rubyfmt integration, and make the `documentFormattingProvider` test only say `true` based on a command line flag.

This should be fixed now.
