### ISSUE TITLE
`srb rbi gems` fails with vendored gems

### ISSUE THREAD

**Issue by dduugg** [sorbet/sorbet#3884]
To repro, first clone https://github.com/dduugg/yard-sorbet

Next, confirm normal behavior:

```
bundle install
bundle exec srb rbi gems
```

Confirm that `srb/rbi/gems` exists as expected.

Now, switch to vendored gems:
```
bundle config set --local deployment 'true'
```

And repeat the sequence from above:
```
bundle install
bundle exec srb rbi gems
```

The command now exits unsuccessfully, the last part of the output being:
```
[567/2329] require_relative './vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/rake_test_loader.rb'
File does not exist: /path/to/yard-sorbet/gems
```

(I thought I could outsmart this, as one does with `srb tc`, by appending `--ignore=vendor/`, but that does not seem to be supported here.)

**Comment by jez** [comment]
> I thought I could outsmart this, as one does with srb tc, by appending --ignore=vendor/, but that does not seem to be supported here.

Does that mean you tried appending that to `srb rbi gems`? or did you add that to your `sorbet/config` file?

**Comment by dduugg** [comment]
Ah, thanks for the suggestion suggestion! It seems one can indeed work around this by including the following lines in `sorbet/config`
```
--ignore
vendor/
```

I think there's still a bug in the inconsistency in CLI support of `--ignore`, but feel free to close this one out. (I'd also suggest including the above lines in the default `sorbet/config`.)

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
