### ISSUE TITLE
`alias_method` fails to alias methods included by modules

### ISSUE THREAD

**Issue by paracycle** [sorbet/sorbet#3888]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20Foo%0A%20%20def%20foo%0A%20%20end%0Aend%0A%0Aclass%20Bar%0A%20%20include%20Foo%0A%0A%20%20alias_method%20%3Abar%2C%20%3Afoo%0Aend)

```ruby
# typed: true

module Foo
  def foo
  end
end

class Bar
  include Foo

  alias_method :bar, :foo
end
```

#### Observed output

```
editor.rb:11: Can't make method alias from bar to non existing method foo https://srb.help/5037
    11 |  alias_method :bar, :foo
                             ^^^^
Errors: 1
```

#### Expected behavior

There should be no errors about non-existing method `foo` since it is defined by `Foo` in `Bar`.

- - -

**Comment by jez** [comment]
https://github.com/sorbet/sorbet/issues/2378

**Comment by paracycle** [comment]
🤦 thanks, makes sense.

**Comment by paracycle** [comment]
Actually @jez, is there a special reason why `alias_method` is not implemented as a Rewriter. If it was implemented as a rewriter that just did delegation, i.e. converted:
```ruby
alias_method :bar, :foo
```
to
```ruby
def bar(*args, **kwargs, &blk)
  foo(*args, **kwargs, &blk)
end
```
then this would work properly without introducing order dependency.
