### ISSUE TITLE
Can't alias equality operator (==) when spaceship operator (<=>) is defined

### ISSUE THREAD

**Issue by SeekingMeaning** [sorbet/sorbet#3890]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Thing%0A%20%20def%20%3C%3D%3E(other)%0A%20%20%20%200%0A%20%20end%0A%20%20alias%20eql%3F%20%3D%3D%0Aend)

```ruby
# typed: true
class Thing
  def <=>(other)
    0
  end
  alias eql? ==
end
```

#### Observed output

```
editor.rb:6: Can't make method alias from eql? to non existing method == https://srb.help/5037
     6 |  alias eql? ==
                     ^^
```

#### Expected behavior

No error (not sure what to put here)

- - -

This is used in Homebrew's [`version.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/version.rb)

**Comment by jez** [comment]
this is the same bug that was just reported and closed before you https://github.com/sorbet/sorbet/issues/3888

**Comment by SeekingMeaning** [comment]
Oops
