### ISSUE TITLE
Cannot define return types based on arguments

### ISSUE THREAD

**Issue by maxfurman** [sorbet/sorbet#3918]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bparams(x%3A%20String).returns(T%3A%3AArray%5BString%5D)%7D%0Asig%20%7Bparams(x%3A%20Integer).returns(Integer)%7D%0Adef%20foo(x)%0A%20%20case%20x%0A%20%20when%20Integer%0A%20%20%20%20return%20x%0A%20%20when%20String%0A%20%20%20%20return%20x.split('%20')%0A%20%20end%0Aend%0A%0Asig%20%7Bparams(x%3A%20T.any(Integer%2C%20String)).returns(T.any(Integer%2C%20T%3A%3AArray%5BString%5D))%7D%0Adef%20foo2(x)%0A%20%20case%20x%0A%20%20when%20Integer%0A%20%20%20%20return%20x%0A%20%20when%20String%0A%20%20%20%20return%20x.split('%20')%0A%20%20end%0Aend%0A%0Az%20%3D%20T.let(foo2(0)%2C%20Integer)%0Azz%20%3D%20T.let(foo2(%22not%20an%20int%22)%2C%20T%3A%3AArray%5BString%5D))

```ruby
# typed: true
extend T::Sig

sig {params(x: String).returns(T::Array[String])}
sig {params(x: Integer).returns(Integer)}
def foo(x)
  case x
  when Integer
    return x
  when String
    return x.split(' ')
  end
end

sig {params(x: T.any(Integer, String)).returns(T.any(Integer, T::Array[String]))}
def foo2(x)
  case x
  when Integer
    return x
  when String
    return x.split(' ')
  end
end

z = T.let(foo2(0), Integer)
zz = T.let(foo2("not an int"), T::Array[String])
```

#### Observed output

```
editor.rb:4: Unused type annotation. No method def before next annotation https://srb.help/5040
     4 |sig {params(x: String).returns(T::Array[String])}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:5: Type annotation that will be used instead
     5 |sig {params(x: Integer).returns(Integer)}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:10: This code is unreachable https://srb.help/7006
    10 |  when String
               ^^^^^^

editor.rb:11: This code is unreachable https://srb.help/7006
    11 |    return x.split(' ')
                           ^^^

editor.rb:25: Argument does not have asserted type Integer https://srb.help/7007
    25 |z = T.let(foo2(0), Integer)
            ^^^^^^^^^^^^^^^^^^^^^^^
  Got T.any(T::Array[String], Integer) originating from:
    editor.rb:25:
    25 |z = T.let(foo2(0), Integer)
                  ^^^^^^^

editor.rb:26: Argument does not have asserted type T::Array[String] https://srb.help/7007
    26 |zz = T.let(foo2("not an int"), T::Array[String])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.any(T::Array[String], Integer) originating from:
    editor.rb:26:
    26 |zz = T.let(foo2("not an int"), T::Array[String])
                   ^^^^^^^^^^^^^^^^^^
Errors: 5
```

#### Expected behavior

I should be able to define a signature for a method that takes in multiple argument types and has multiple return types, but the return types correspond 1-to-1 with the argument types. T.type_parameter AFAICT is only useful if the return type is the same as the argument type. In this example, Sorbet should be able to statically determine that an argument of type String always returns a T::Array[String], or provide a way to express this sort of override within a sig block.

**Comment by jez** [comment]
Sorbet only supports overloading for methods defined in the standard library.

There is more context here:

https://sorbet.org/docs/error-reference#5040
