### ISSUE TITLE
unexpected token "or"

### ISSUE THREAD

**Issue by jcoyne** [sorbet/sorbet#3982]
I've got this Rails code:
```ruby
  scope :awaiting_review_by, ->(user) {
    with_state(:pending_approval).
      left_outer_joins(collection: :reviewed_by).
      left_outer_joins(collection: :managed_by).
      where('reviewers.user_id' => user).
      or(where('managers.user_id' => user))
  }
```

And when I run it I get a tokenizer error:

```
$ bundle exec srb tc
app/models/work.rb:33: unexpected token "or" https://srb.help/2001
    33 |      or(where('managers.user_id' => user))
              ^^
Errors: 1
$ bundle exec srb --version
Sorbet typechecker 0.5.5981 git ae42e259185888423552d630cdd48acd86b2e295 debug_symbols=true clean=1
```

https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0A%20%20scope%20%3Aawaiting_review_by%2C%20-%3E(user)%20%7B%0A%20%20%20%20with_state(%3Apending_approval).%0A%20%20%20%20%20%20left_outer_joins(collection%3A%20%3Areviewed_by).%0A%20%20%20%20%20%20left_outer_joins(collection%3A%20%3Amanaged_by).%0A%20%20%20%20%20%20where('reviewers.user_id'%20%3D%3E%20user).%0A%20%20%20%20%20%20or(where('managers.user_id'%20%3D%3E%20user))%0A%20%20%7D

**Comment by jez** [comment]
This is intentional: https://github.com/sorbet/sorbet/issues/2122#issuecomment-552030114

**Comment by jcoyne** [comment]
@jez Understood, but the error message says to report it as a bug. Perhaps a unique error is needed?
