### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by dsisnero** [sorbet/sorbet#4011]
### Problem

Trying to use sorbet in windows but get a Exec format error

ems/sorbet-0.5.6293/bin/srb (Errno::ENOEXEC)
        from F:/windows/scoop/apps/ruby/3.0.0-1/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6293/bin/srb:150:in `<top (required)>'
        from F:/windows/scoop/apps/ruby/current/bin/srb:23:in `load'
        from F:/windows/scoop/apps/ruby/current/bin/srb:23:in `<main>'

**Comment by froydnj** [comment]
Sorbet does not support Windows: https://sorbet.org/docs/faq#what-platforms-does-sorbet-support
