### ISSUE TITLE
Frozen and non-frozen strings handled differently as positional args

### ISSUE THREAD

**Issue by ghiculescu** [sorbet/sorbet#4014]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20def%20foo(arg%2C%20kwarg%3A%20nil)%3B%20end%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20S1%20%3D%20%22test%22%0A%20%20S2%20%3D%20%22test%22.freeze%0A%0A%20%20def%20perform%0A%20%20%20%20foo(%22test%22%2C%20S1)%20%23%20error%0A%20%20%20%20foo(%22test%22%2C%20S2)%20%23%20fine%0A%20%20%20%20foo(%22test%22.freeze%2C%20S1)%20%23%20error%0A%20%20%20%20foo(%22test%22.freeze%2C%20S2)%20%23%20fine%0A%20%20end%0Aend%0A)

```ruby
# typed: true

class A
  def foo(arg, kwarg: nil); end
end

class B < A
  S1 = "test"
  S2 = "test".freeze

  def perform
    foo("test", S1) # error
    foo("test", S2) # fine
    foo("test".freeze, S1) # error
    foo("test".freeze, S2) # fine
  end
end

```

#### Observed output

```
test.rb:13: Too many positional arguments provided for method A#foo. Expected: 1, got: 2 https://srb.help/7004
    13 |    foo("test", S1) # error
            ^^^^^^^^^^^^^^^
    test.rb:5: foo defined here
     5 |  def foo(arg, kwarg: nil); end
          ^^^^^^^^^^^^^^^^^^^^^^^^
    test.rb:13: A#foo has optional keyword arguments. Did you mean to provide a value for kwarg?
    13 |    foo("test", S1) # error
            ^^^^^^^^^^^^^^^

test.rb:15: Too many positional arguments provided for method A#foo. Expected: 1, got: 2 https://srb.help/7004
    15 |    foo("test".freeze, S1) # error
            ^^^^^^^^^^^^^^^^^^^^^^
    test.rb:5: foo defined here
     5 |  def foo(arg, kwarg: nil); end
          ^^^^^^^^^^^^^^^^^^^^^^^^
    test.rb:15: A#foo has optional keyword arguments. Did you mean to provide a value for kwarg?
    15 |    foo("test".freeze, S1) # error
            ^^^^^^^^^^^^^^^^^^^^^^
```

#### Expected behavior

I'd expect every line to error the same. In all cases I'm providing the wrong number of positional arguments.

Note that this works correctly:

```ruby
class A
  def foo(arg, kwarg: nil); end
end

class B < A
  def perform
    foo("test", "test") # error
    foo("test", "test".freeze) # error
    foo("test".freeze, "test") # error
    foo("test".freeze, "test".freeze) # error
  end
end
```

As does this:

```ruby
class A
  def foo(arg, kwarg: nil); end
end

class B < A
  S1 = T.let("test", String)
  S2 = T.let("test".freeze, String)

  def perform
    foo("test", S1) # error
    foo("test", S2) # error
    foo("test".freeze, S1) # error
    foo("test".freeze, S2) # error
  end
end
```

So I guess the issue is that in the original example, `S2` is a `T.untyped`? Even then, should sorbet recognize that it's a positional argument?

**Comment by elliottt** [comment]
The issue is that sorbet can't tell if the last argument was meant to be a keyword args hash, as the method accepts keyword arguments and the last argument is untyped. As you noted, adding a signature resolves the issue, as sorbet is now  able to tell that the last argument is definitely not a hash.

**Comment by jez** [comment]
I think this is simply a result of Sorbet not having a type annotation and thus seeing `T.untyped` for the constant, not a problem with frozen strings.
