### ISSUE TITLE
Confusing error using `T.cast` on ivar

### ISSUE THREAD

**Issue by benbuckman-stripe** [sorbet/sorbet#4017]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20def%20initialize%0A%20%20%20%20%40val%20%3D%20T.cast(0%2C%20Integer)%0A%20%20end%0Aend)

```ruby
# typed: true

class A
  extend T::Sig
  def initialize
    @val = T.cast(0, Integer)
  end
end
```

#### Observed output

```
editor.rb:6: Use T.let to specify the type of constants https://srb.help/5013
     6 |    @val = T.cast(0, Integer)
                   ^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

https://srb.help/5013 should mention the workaround for when `T.cast` is intended:

```ruby
val = T.cast(x, X)
@val = val
```

we might also want to use `addErrorNote` on the error message to suggest something like "if you really meant to use `T.cast`, do this...".

**Comment by jez** [comment]
This is working as expected, and the refactoring to use an intermediate variable is the suggested alternative.

Only `T.let` is used to declare ivar fields, not `T.cast`. To make sure no one accidentally uses `T.cast` thinking that they're declaring an ivar field, Sorbet forces it to be written it in two lines like

```ruby
val = T.cast(x, X)
@val = val
```

The action here should be to make the error message more clear, and to make sure there's documentation that captures the reasoning / workaround.

**Comment by karmakaze** [comment]
I also ran into this and thought it was a bug, but see it's defined behaviour. The case I was dealing with appeared correct (but not following the recommended 2-line convention):
```
sig { params(uri_or_str: T.any(URI, String)).void }
def initialize(uri_or_str)
  if T.unsafe(uri_or_str).is_a?(String)
    @uri_s = uri_or_str
  else
    @uri = T.cast(uri_or_str, URI::Generic)
  end
end
```
*[Don't mind the `T.unsafe` for `.is_a?` which is a separate issue for module types.]*

The alternate workaround
```
    @uri = T.let(T.unsafe(uri_or_str), URI::Generic)
```
could be a 1-line idiom to mean the same thing as the 2-line convention--at which point I don't see the value in enforcing only `T.let` and not `T.cast` for ivar's.

T.let and T.cast each have defined meanings and it's surprising for a special rule to be invoked in an ivar context.
