### ISSUE TITLE
Withhold autocorrects suggesting private methods at public-only callsites

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#4064]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20private%20def%20my_private_method%3B%20end%0Aend%0A%0AA.new.my_private_metho)

```ruby
# typed: true

class A
  private def my_private_method; end
end

A.new.my_private_metho
```

#### Observed output

```
editor.rb:7: Method my_private_metho does not exist on A https://srb.help/7003
     7 |A.new.my_private_metho
        ^^^^^^^^^^^^^^^^^^^^^^
  Got A originating from:
    editor.rb:7:
     7 |A.new.my_private_metho
        ^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:7: Replace with my_private_method
     7 |A.new.my_private_metho
              ^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

If you apply the suggestion with `-a`, or take the code action in your editor, the resulting program will have more errors:

```ruby
# typed: true

class A
  private def my_private_method; end
end

A.new.my_private_method
```

```
editor.rb:7: Non-private call to private method my_private_method on A https://srb.help/7031
     7 |A.new.my_private_method
        ^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:4: Defined in A here
     4 |  private def my_private_method; end
                  ^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20private%20def%20my_private_method%3B%20end%0Aend%0A%0AA.new.my_private_method)

We should not suggest private methods in the "did you mean?" suggestions. (Maybe entirely, which would definitely be easier, or maybe only when the method call site has the `isPrivateOk` flag, though I don't think we currently thread that information down through the places where we would need it to, currently, so it would  be a more invasive change.) I'm fine with either the approximate former solution or the exact latter solution.

- - -

**Comment by froydnj** [comment]
I believe #4363 fixed this issue.
