### ISSUE TITLE
Hovering over `when` displays `===` in IDE

### ISSUE THREAD

**Issue by damolina-stripe** [sorbet/sorbet#4073]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20A%0A%20%20class%20B%0A%20%20end%0Aend%0A%0Asig%20%7Bparams(x%3A%20T.untyped).void%7D%0Adef%20foo(x)%0A%20%20case%20x.class%0A%20%20when%20Integer%0A%20%20%20%201%0A%20%20when%20A%3A%3AB%0A%20%20%20%202%0A%20%20end%0Aend%0A)

```ruby
# typed: true
extend T::Sig

module A
  class B
  end
end

sig {params(x: T.untyped).void}
def foo(x)
  case x.class
  when Integer
    1
  when A::B
    2
  end
end
```

#### Observed output

Hover over `Integer` and you will see it shows `def ===(other); end` as description.  In case of namespaced classes, the last component shows this behavior. On the example, hovering over `A` would correctly point to `module A` but hovering over `B` shows `def ===(other); end` as description.
In VSCode this means navigation is broken, going to `def ===(other); end` in `module.rbi`.

#### Expected behavior

Navigate to correct type (`Integer` or `class B` on example).

- - -

![image](https://user-images.githubusercontent.com/46902661/110702512-7527db80-81a7-11eb-8ba1-556daafc2b3a.png)

**Comment by jvilk-stripe** [comment]
Probably caused by `when` desugaring to `if x.class === Integer` and `===` having the same loc info as `Integer`.
