### ISSUE TITLE
Generic types are not fully recognized for blocks parameters

### ISSUE THREAD

**Issue by itarato** [sorbet/sorbet#4077]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Result%0A%20%20extend(T%3A%3ASig)%0A%20%20extend(T%3A%3AGeneric)%0A%0A%20%20SelfType%20%3D%20type_member%0A%0A%20%20sig%20%7B%20params(blk%3A%20T.proc.params(arg0%3A%20SelfType).void).void%20%7D%0A%20%20def%20map(%26blk)%3B%20end%0Aend%0A%0AT.let(%0A%20%20Result%5BString%5D.new%2C%20%0A%20%20T.any(Result%5BString%5D%2C%20Result%5BInteger%5D)%2C%0A).map%20%7B%20%7Cv%7C%20T.reveal_type(v)%20%7D%20%23%20Suddenly%20all%20possible%20types%20are%20missing%20except%20one%0A%0A%23%20Expected%20v%3A%20T.any(String%2C%20Integer)%0A%23%20Actual%20v%3A%20Integer%0A)

```ruby
class Result
  extend(T::Sig)
  extend(T::Generic)

  SelfType = type_member

  sig { params(blk: T.proc.params(arg0: SelfType).void).void }
  def map(&blk); end
end

T.let(
  Result[String].new, 
  T.any(Result[String], Result[Integer]),
).map { |v| T.reveal_type(v) }
```

#### Observed output

```
Revealed type: Integer
```

#### Expected behavior

```
Revealed type: T.any(String, Integer)
```

**Comment by jez** [comment]
Not sure when, but this has been fixed.
