### ISSUE TITLE
T.proc.bind does not work if the block param is also T.any(...)

### ISSUE THREAD

**Issue by seachel** [sorbet/sorbet#4099]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%0Aend%0A%0Asig%20%7B%20params(arg%3A%20T.any(T.proc.bind(A).void%2C%20T.untyped)).void%20%7D%0Adef%20run(arg)%0Aend)

```ruby
# typed: true

extend T::Sig

class A
end

sig { params(arg: T.any(T.proc.bind(A).void, T.untyped)).void }
def run(arg)
end
```

#### Observed output

```
editor.rb:8: Using bind is not permitted here https://srb.help/5004
     8 |sig { params(arg: T.any(T.proc.bind(A).void, T.untyped)).void }
                                ^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

No error when there's a `T.proc.bind` in a `T.any`.

This is mentioned in the comments in https://github.com/sorbet/sorbet/issues/498 but the fix for that issue did not correct it for `T.proc.bind` in `T.any`.

**Comment by jez** [comment]
This is actually expected behavior. See #4095

**Comment by seachel** [comment]
Thank you! I was hoping to bind a proc but I see that this isn't possible right now.
