### ISSUE TITLE
Better error message when subtyping fails for invariant generic

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#4110]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aextend%20T%3A%3ASig%0A%0Aclass%20InvariantBox%0A%20%20extend%20T%3A%3AGeneric%0A%20%20X%20%3D%20type_member%0Aend%0A%0Asig%20%7Bparams(x%3A%20InvariantBox%5BT.any(Integer%2C%20String)%5D).void%7D%0Adef%20foo(x)%3B%20end%0A%0Aint_box%20%3D%20InvariantBox%5BInteger%5D.new%0Aint_or_string_box%20%3D%20InvariantBox%5BT.any(Integer%2C%20String)%5D.new%0A%0Afoo(int_box)%0Afoo(int_or_string_box))

```ruby
# typed: strict

extend T::Sig

class InvariantBox
  extend T::Generic
  X = type_member
end

sig {params(x: InvariantBox[T.any(Integer, String)]).void}
def foo(x); end

int_box = InvariantBox[Integer].new
int_or_string_box = InvariantBox[T.any(Integer, String)].new

foo(int_box)
foo(int_or_string_box)
```

#### Observed output

```
editor.rb:16: Expected InvariantBox[T.any(Integer, String)] but found InvariantBox[Integer] for argument x https://srb.help/7002
    16 |foo(int_box)
        ^^^^^^^^^^^^
  Expected InvariantBox[T.any(Integer, String)] for argument x of method Object#foo:
    editor.rb:10:
    10 |sig {params(x: InvariantBox[T.any(Integer, String)]).void}
                    ^
  Got InvariantBox[Integer] originating from:
    editor.rb:13:
    13 |int_box = InvariantBox[Integer].new
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

The error message should **specifically** mention that variance is the cause of the problem.

For example:

```
editor.rb:16: Expected InvariantBox[T.any(Integer, String)] but found InvariantBox[Integer] for argument x https://srb.help/7002
    16 |foo(int_box)
        ^^^^^^^^^^^^
  Expected InvariantBox[T.any(Integer, String)] for argument x of method Object#foo:
    editor.rb:10:
    10 |sig {params(x: InvariantBox[T.any(Integer, String)]).void}
                    ^
  Got InvariantBox[Integer] originating from:
    editor.rb:13:
    13 |int_box = InvariantBox[Integer].new
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  The types `Integer` and `T.any(Integer, String)` must be equivalent because `InvariantBox` is invariant in type member `X`
    editor.rb:7: Type member InvariantBox::X was declared as invariant here:
    10 |X = type_member
        ^^^^^^^^^^^^^^^
Errors: 1
```

- - -

**Comment by jez** [comment]
Another test. I'm not sure if we'll be able to provide a better error message for this failure at the same time that we fix the above failure, but in any case I figured I'd leave this here as inspiration:

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3AU%29%0A%20%20.params%28x%3A%20Thing%5BT.type_parameter%28%3AU%29%5D%29%0A%20%20.void%0Aend%0Adef%20thing%28x%29%0Aend%0A%0Aclass%20Thing%0A%20%20extend%20T%3A%3AGeneric%0A%20%20E%20%3D%20type_member%0Aend%0A%0Asig%20%7B%20params%28x%3A%20T.any%28Thing%5BInteger%5D%2C%20Thing%5BString%5D%29%29.void%20%7D%0Adef%20example1%28x%29%0A%20%20thing%28x%29%0A%0A%20%20T.let%28%0A%20%20%20%20x%2C%0A%20%20%20%20Thing%5BT.any%28Integer%2C%20String%29%5D%0A%20%20%29%0Aend%0A%0Asig%20%7B%20params%28x%3A%20Thing%5BT.any%28Integer%2C%20String%29%5D%29.void%20%7D%0Adef%20example2%28x%29%0A%20%20thing%28x%29%0Aend)

```ruby
# typed: true
extend T::Sig

sig do
  type_parameters(:U)
  .params(x: Thing[T.type_parameter(:U)])
  .void
end
def thing(x)
end

class Thing
  extend T::Generic
  E = type_member
end

sig { params(x: T.any(Thing[Integer], Thing[String])).void }
def example1(x)
  thing(x)

  T.let(
    x,
    Thing[T.any(Integer, String)]
  )
end

sig { params(x: Thing[T.any(Integer, String)]).void }
def example2(x)
  thing(x)
end
```

#### Observed output

```
editor.rb:19: Could not find valid instantiation of type parameters for Object#thing https://srb.help/7020
    19 |  thing(x)
          ^^^^^
    editor.rb:9: Object#thing defined here
     9 |def thing(x)
        ^^^^^^^^^^^^
  Found no solution for these constraints:
    T.any(Integer, String) must be a subtype of T.type_parameter(:U) which must be a subtype of T.noreturn

editor.rb:21: Argument does not have asserted type Thing[T.any(Integer, String)] https://srb.help/7007
    21 |  T.let(
    22 |    x,
    23 |    Thing[T.any(Integer, String)]
    24 |  )
  Got T.any(Thing[Integer], Thing[String]) originating from:
    editor.rb:18:
    18 |def example1(x)
                     ^
Errors: 2
```

**Comment by jez** [comment]
Another test case where an error message mentioning that the subtyping failed because of invariance:

#7663

**Comment by neilparikh** [comment]
Done in https://github.com/sorbet/sorbet/pull/7620
