### ISSUE TITLE
Resolv::DNS#getaddresses should return an array

### ISSUE THREAD

**Issue by tophattom** [sorbet/sorbet#4128]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aaddresses%20%3D%20Resolv%3A%3ADNS.new.getaddresses('google.com')%0AT.reveal_type(addresses)%0A)

```ruby
# typed: true

addresses = Resolv::DNS.new.getaddresses('google.com')
T.reveal_type(addresses)
```

#### Observed output

```
editor.rb:4: Revealed type: T.any(Resolv::IPv4, Resolv::IPv6) https://srb.help/7014
     4 |T.reveal_type(addresses)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.any(Resolv::IPv4, Resolv::IPv6) originating from:
    editor.rb:3:
     3 |addresses = Resolv::DNS.new.getaddresses('google.com')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

`addresses` should have type `T::Array[T.any(Resolv::IPv4, Resolv::IPv6)]`. Running the code in a console shows that the result is in fact an array of addresses:
```
[22] pry(main)> addresses = Resolv::DNS.new.getaddresses('google.com')
=> [#<Resolv::IPv4 142.250.74.142>]
[23] pry(main)> addresses.class
=> Array
```

- - -

**Comment by jez** [comment]
👋  https://sorbet.org/docs/faq#it-looks-like-sorbets-types-for-the-stdlib-are-wrong
