### ISSUE TITLE
Inherited methods from classes defined in sibling-gem not recognized

### ISSUE THREAD

**Issue by joeletizia** [sorbet/sorbet#4135]
#### Input
https://github.com/joeletizia/sorbet_example

See this rails app as an example. I believe this is the best way to share the bug since I believe it is directly related to the fact that I'm asserting on classes that are brought in from a sibling gem. I cannot recreate this in sorbet.run.

Steps to reproduce:
1. Clone the repo
2. bundle
3. `cd gems/gem_one/`
4. srb tc

#### Observed output

`srb tc` => 
```
lib/gem_one.rb:8: Method foo does not exist on GemTwo::Child https://srb.help/7003
     8 |    x.foo
            ^^^^^
  Got GemTwo::Child originating from:
    lib/gem_one.rb:7:
     7 |  def baz(x)
```

#### Expected behavior

I would expect sorbet to be able to recognize this inheritance. But, when I look at the `hidden.rbi` definitions for the classes in question, I see this:

```
class GemTwo::Child
  def bar(); end
end

class GemTwo::Child
end

class GemTwo::Parent
  def foo(); end
end

class GemTwo::Parent
end
```
There seems to be no indication that `Child` inherits from `Parent` or that `Parent` defined methods are availble in `Child`. My gut tells me this is due to the fact that I'm crossing the gem boundary. Note that for `MyParent` and `MyChild` which are defined in `GemOne` this problem correctly DOES NOT occur.
- - -

**Comment by jez** [comment]
Have you tried using [tapioca](https://github.com/Shopify/tapioca) instead of `srb init`?

**Comment by joeletizia** [comment]
Hey @jez 

This works. Thank you so much! This may be a good opportunity for a documentation enhancement. I'd love to help if I can, but I'm just starting out with sorbet. Any chance you could point me in a direction that might help the next person. I imagine gems embedded in a rails app may not be a common use case.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
