### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by akimd** [sorbet/sorbet#4165]
Your example page https://sorbet.org/docs/flow-sensitive is about

```
x = maybe_int.nil? && (2 * maybe_int)
```

and I'm pretty sure the author actually meant

```
x = !maybe_int.nil? && (2 * maybe_int)
```

with a not (!nil?).  Alternatively `||` would do.

Cheers!

**Comment by jez** [comment]
Thanks, it looks like this was fixed in #4414.
