### ISSUE TITLE
Sorbet fail to install

### ISSUE THREAD

**Issue by reob-info** [sorbet/sorbet#4168]
I would like to install sorbet, any suggestion to fix it?

PS_ C:\dev\test\ruby\properties> gem install sorbet
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/digest-3.0.0/lib/digest.rb:6: warning: already initialized constant Digest::REQUIRE_MUTEX
C:/Ruby30-x64/lib/ruby/3.0.0/digest.rb:6: warning: previous definition of REQUIRE_MUTEX was here
ERROR:  Could not find a valid gem 'sorbet-static' (= 0.5.6386) (required by 'sorbet' (>= 0)) in any repository
ERROR:  Possible alternatives: urban-static, poe_static, butler_static, draw_static, ecstatic, estatic, bard_static, evestatic, exstatic, go_static

RUBY VERSION: 3.0.0
OS: WINDOWS 10 x64

Thanks.

**Comment by froydnj** [comment]
We do not support Sorbet on Windows.  See https://sorbet.org/docs/faq#what-platforms-does-sorbet-support

You could try using Windows Subsystem for Linux (WSL) and use Sorbet inside WSL.
