### ISSUE TITLE
Runtime error when doing SomeTypeAlias.new

### ISSUE THREAD

**Issue by qaisjp** [sorbet/sorbet#4186]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0ATags%20%3D%20T.type_alias%20%7BT%3A%3AHash%5BString%2C%20String%5D%7D%0Ax%20%3D%20Tags.new%0A)

```ruby
# typed: strict
extend T::Sig

Tags = T.type_alias {T::Hash[String, String]}
x = Tags.new
```

#### Observed output

It type checks, but at runtime

```
NoMethodError: undefined method `new' for #<T::Private::Types::TypeAlias:0x00007feaf7d6c038>
```

#### Expected behavior

It should either work. Or it should not typecheck.

**Comment by elliottt** [comment]
This is redundant with https://github.com/sorbet/sorbet/issues/4172
