### ISSUE TITLE
Segmentation fault with a brand new project.

### ISSUE THREAD

**Issue by thomasdziedzic-census** [sorbet/sorbet#4196]
#### Input

In a blank directory, have the following files:

I'm using macos 11.3 (x86_64)

The Gemfile:

```ruby
source 'https://rubygems.org'

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
```

The Gemfile.lock

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    sorbet (0.5.6398)
      sorbet-static (= 0.5.6398)
    sorbet-runtime (0.5.6398)
    sorbet-static (0.5.6398-universal-darwin-14)

PLATFORMS
  ruby

DEPENDENCIES
  sorbet
  sorbet-runtime

BUNDLED WITH
   2.1.4
```

#### Observed output

I ran `SRB_YES=1 bundle exec srb init &> output.log` and got the following output: 
[output.log](https://github.com/sorbet/sorbet/files/6422792/output.log)

#### Expected behavior

Should not crash.

- - -

And here is the diagnostic report: 
[ruby_2021-05-04-121103_Thomass-MacBook-Pro.crash.txt](https://github.com/sorbet/sorbet/files/6422803/ruby_2021-05-04-121103_Thomass-MacBook-Pro.crash.txt)

**Comment by jez** [comment]
This crash is coming from Ruby itself, not from anything Sorbet is doing. `srb init` does not run any C or C++ code, so it if segfaults it is necessarily a bug upstream with Ruby.

Congrats! You've found a bug in Ruby. Feel free to report a bug using the instructions it mentions in the log output.

**Comment by thomasdziedzic-census** [comment]
Ok, thanks for your time and taking a peek!

**Comment by thomasdziedzic-census** [comment]
Found the issue; it was an actual ruby bug: https://bugs.ruby-lang.org/issues/17780

I downloaded the patch from https://bugs.ruby-lang.org/projects/ruby-master/repository/git/revisions/d8a13e504992a45d52063f7c925408d7aad3595a/diff and ran `rbenv install --force --patch 2.7.3 < ~/Downloads/changeset_rd8a13e504992a45d52063f7c925408d7aad3595a.diff`
