### ISSUE TITLE
Abstract classes should be excluded from exhaustiveness checks

### ISSUE THREAD

**Issue by bmulholland** [sorbet/sorbet#4210]
This is similar to, but simpler than (no sealed classes) e.g. https://github.com/sorbet/sorbet/issues/2572

The scenario described here is somewhat common when using rails STI with an abstract base class.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0Aend%0A%0Aclass%20AImp%20%3C%20A%3B%20end%0A%0Aclass%20BImp%20%3C%20A%3B%20end%0A%0Asig%20%7B%20params(test%3A%20A).void%20%7D%0Adef%20method(test)%0A%20%20case%20test%0A%20%20when%20AImp%0A%20%20%20%20puts%20%22A%22%0A%20%20when%20BImp%0A%20%20%20%20puts%20%22B%22%0A%20%20else%0A%20%20%20%20T.absurd(test)%0A%20%20end%0Aend)

```ruby
# typed: true
extend T::Sig

class A
  extend T::Sig
  extend T::Helpers
  abstract!
end

class AImp < A; end

class BImp < A; end

sig { params(test: A).void }
def method(test)
  case test
  when AImp
    puts "A"
  when BImp
    puts "B"
  else
    T.absurd(test)
  end
end
```

#### Observed output

```
editor.rb:22: Control flow could reach T.absurd because the type A wasn't handled https://srb.help/7026
    22 |    T.absurd(test)
            ^^^^^^^^^^^^^^
  Got A originating from:
    editor.rb:15:
    15 |def method(test)
                   ^^^^
    editor.rb:17:
    17 |  when AImp
               ^^^^
    editor.rb:19:
    19 |  when BImp
               ^^^^
Errors: 1
```

#### Expected behavior

No error: this is an exhaustive check.

Since A is an abstract class, it is not a valid case and should not be expected to be handled. In fact, I would describe an instance of class A existing to be _more_ "absurd" than a new subclass class being added :)

**Comment by froydnj** [comment]
Adding `when A` doesn't mean that `test` must be an instance of exactly `A`, `test` could be a subclass of `A`.  If you modify your example slightly:

```ruby
# typed: true
extend T::Sig

class A
  extend T::Sig
  extend T::Helpers
  abstract!
end

class AImp < A; end

class BImp < A; end

class CImp < A; end

sig { params(test: A).void }
def method(test)
  case test
  when AImp
    puts "A"
  when BImp
    puts "B"
  when A
    puts "Some unknown subclass of A"
  else
    T.absurd(test)
  end
end

method(CImp.new)
```

([sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0Aend%0A%0Aclass%20AImp%20%3C%20A%3B%20end%0A%0Aclass%20BImp%20%3C%20A%3B%20end%0A%0Aclass%20CImp%20%3C%20A%3B%20end%0A%0Asig%20%7B%20params(test%3A%20A).void%20%7D%0Adef%20method(test)%0A%20%20case%20test%0A%20%20when%20AImp%0A%20%20%20%20puts%20%22A%22%0A%20%20when%20BImp%0A%20%20%20%20puts%20%22B%22%0A%20%20when%20A%0A%20%20%20%20puts%20%22Some%20unknown%20subclass%20of%20A%22%0A%20%20else%0A%20%20%20%20T.absurd(test)%0A%20%20end%0Aend%0A%0Amethod(CImp.new)%0A))

and run the program, you get:

```
Some unknown subclass of A
```

The intent may be that `AImp` and `BImp` are the only possible subclasses of `A`, but that fact has not been communicated to Sorbet, so it must assume that there are other potential subclasses.

**Comment by bmulholland** [comment]
Thanks for clarifying. The use case remains: is there any way to get exhaustiveness checks in this scenario? Should I file a feature request instead?

**Comment by froydnj** [comment]
> Thanks for clarifying. The use case remains: is there any way to get exhaustiveness checks in this scenario? Should I file a feature request instead?

Sorbet supports [sealed classes and modules](https://sorbet.org/docs/sealed) for declaring that there are a fixed number of subclasses of a given type.  In the original testcase, declaring `A` as `sealed!` is enough ([sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0A%20%20sealed!%0Aend%0A%0Aclass%20AImp%20%3C%20A%3B%20end%0A%0Aclass%20BImp%20%3C%20A%3B%20end%0A%0Asig%20%7B%20params(test%3A%20A).void%20%7D%0Adef%20method(test)%0A%20%20case%20test%0A%20%20when%20AImp%0A%20%20%20%20puts%20%22A%22%0A%20%20when%20BImp%0A%20%20%20%20puts%20%22B%22%0A%20%20else%0A%20%20%20%20T.absurd(test)%0A%20%20end%0Aend)).

The only caveat is that all the subclasses of the sealed class must appear in the same file as the definition of the sealed class.  The same caveat applies to inclusions of a sealed module.

**Comment by bmulholland** [comment]
Thanks - I had sealed classes filed away in my head as something too advanced for what I'd need. I gave it a try and it looks good - appreciate the help :)
