### ISSUE TITLE
Structs with custom initializers have parameters typed as `NilClass` despite initialize signature

### ISSUE THREAD

**Issue by vinistock** [sorbet/sorbet#4289]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0AConst%20%3D%20Struct.new(%3Asomething%2C%20keyword_init%3A%20true)%20do%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(something%3A%20Integer).void%20%7D%0A%20%20def%20initialize(something%3A%200)%0A%20%20end%0Aend%0A)

```ruby
# typed: true

Const = Struct.new(:something, keyword_init: true) do
  extend T::Sig

  sig { params(something: Integer).void }
  def initialize(something: 0)
  end
end
```

#### Observed output

```
editor.rb:3: Argument does not have asserted type Integer https://srb.help/7007
     3 |Const = Struct.new(:something, keyword_init: true) do
                            ^^^^^^^^^
  Got NilClass originating from:
    editor.rb:3:
     3 |Const = Struct.new(:something, keyword_init: true) do
                            ^^^^^^^^^
Errors: 1
```

#### Expected behavior

The Struct should be type checked considering the types defined in the overridden initializer, but it's considering that the type of the argument is `nil`. Can potentially be related to #4245.

**Comment by jez** [comment]
we should probably just do a naive scan of the body of the struct block to see whether we should emit an `initialize` method at all in the rewriter pass (i.e., if we can cheaply tell that the user has provided their own, don't add an autogenerated one)
