### ISSUE TITLE
IDE: Autocomplete suggestions for modules does not work

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#429]
#### Input / Output

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20Foo%0A%20%20module%20Bar%3A%3ABaaaaz%0A%20%20%20%20A%20%3D%2010%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20Foo%3A%3ABar%3A%3A%0A%20%20%23%20%5E%20Start%20typing%20Baaaaz%3B%20you%20only%20get%20an%20autocomplete%20suggestion%20at%20the%20last%20character%0Aend)

```ruby
# typed: true

module Foo
  module Bar::Baaaaz
    A = 10
  end
end

def main
  Foo::Bar::
  # ^ Start typing Baaaaz; you only get an autocomplete suggestion at the last character
end
```

#### Expected behavior

Typing `B` will provide autocomplete suggestions.

**Comment by jez** [comment]
Closing this to consolidate tracking completion all in one place.
