### ISSUE TITLE
class << self scope doesn't recognize methods from same class Name extend T::Sig

### ISSUE THREAD

**Issue by karmakaze** [sorbet/sorbet#4327]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Name%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20class%20%3C%3C%20self%0A%20%20%20%20sig%20%7Bparams(x%3A%20Integer).void%7D%0A%20%20%20%20def%20foo(x)%0A%20%20%20%20%20%20puts(x%20%2B%201)%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).void%7D%0A%20%20def%20bar(x)%0A%20%20%20%20puts(x%20-%201)%0A%20%20end%0Aend%0A)

```ruby
# typed: true

class Name
  extend T::Sig

  class << self
    sig {params(x: Integer).void}
    def foo(x)
      puts(x + 1)
    end
  end

  sig {params(x: Integer).void}
  def bar(x)
    puts(x - 1)
  end
end
```

#### Observed output

```
# typed: true

class Name
  extend T::Sig

  class << self
    sig {params(x: Integer).void}
    def foo(x)
      puts(x + 1)
    end
  end

  sig {params(x: Integer).void}
  def bar(x)
    puts(x - 1)
  end
end

editor.rb:7: Method sig does not exist on T.class_of(T.class_of(Name)) https://srb.help/7003
     7 |    sig {params(x: Integer).void}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Did you mean:
    https://github.com/sorbet/sorbet/tree/master/rbi/sorbet/t.rbi#L7: T::Sig#sig
     7 |  def sig(arg0=nil, &blk); end
          ^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:7: Method params does not exist on T.class_of(T.class_of(Name)) https://srb.help/7003
     7 |    sig {params(x: Integer).void}
                 ^^^^^^^^^^^^^^^^^^
Errors: 2
```

There are no errors at runtime.

#### Expected behavior

There should be no error when running the Ruby and this is indeed the case indicating that the extend T::Sig methods are in scope inside the `class << self`.

There should be no error when running srb typecheck.

- - -

Work-around is to put the extend T::Sig in each class scope where used even if extend T::Sig already done for the class.
```ruby
class Name
  extend T::Sig

  class << self
    extend T::Sig

    sig {params(x: Integer).void}
    def foo(x)
      puts(x + 1)
    end
  end
  ...
end
```

**Comment by jez** [comment]
Sorbet's error is correct here, as far as I understand. This code raises a NoMethodError when run:

```
❯ ruby foo.rb
Traceback (most recent call last):
        2: from foo.rb:5:in `<main>'
        1: from foo.rb:8:in `<class:Name>'
foo.rb:9:in `singleton class': undefined method `sig' for #<Class:Name> (NoMethodError)
```
