### ISSUE TITLE
Param of Module type (for class include) doesn't have `.is_a?` defined on it.

### ISSUE THREAD

**Issue by karmakaze** [sorbet/sorbet#4329]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20M%3B%20end%0A%0Aclass%20A%0A%20%20include%20M%0Aend%0A%0Asig%20%7Bparams(m%3A%20T.any(M%2C%20String)).void%7D%0Adef%20foo(m)%0A%20%20puts%20m.is_a%3F(M)%0Aend%0A%0Afoo(A.new)%0A)

```ruby
# typed: true
extend T::Sig

module M; end

class A
  include M
end

sig {params(m: T.any(M, String)).void}
def foo(m)
  puts m.is_a?(M)
end

foo(A.new)
```

#### Observed output

```
editor.rb:12: Method is_a? does not exist on M component of T.any(M, String) https://srb.help/7003
    12 |  puts m.is_a?(M)
               ^^^^^^^^^^
  Got T.any(M, String) originating from:
    editor.rb:11:
    11 |def foo(m)
                ^
  Note:
    Did you mean to include Kernel in this module?
  Did you mean:
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L493: Kernel#is_a?
     493 |  def is_a?(arg0); end
            ^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

No errors! Great job.

- - -

When run, the Ruby output shows:
```
true
```

**Comment by karmakaze** [comment]
I believe this can be resolved by using the type `URI::Generic` which is intended as a base class for all URI concrete types.

I thought I'd read somewhere that each URI class should `include URI` so it `.is_a?(URI)`, but it's simpler to ask a `T.any(URI::Generic, String)` if it `.is_a?(URI::Generic)`.

The discrepancy between Ruby execution and Sorbet's static type info exists as reported but has a nice alternative.

How in general, do we handle `include ModuleThing` methods for a type defined as `ModuleThing` (if in fact this is the source of the difference between Ruby runtime and Sorbet)?

**Comment by jez** [comment]
This is working as intended. Sorbet can't know that the module `M` will eventually be mixed into a location that has `.is_a?` defined, because it could also have been mixed into `BasicObject`.

The suggestion error message is the recommended suggestion (put `include Kernel` inside `module M`).

Another suggestion is to use `case m; when M then ...`, because Ruby treats this as a call to `M.===(m)` which is valid no matter what the ancestor hierarchy of `M` is.
