### ISSUE TITLE
LSP: Feature - highlight untyped lines

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#437]
### Problem

If you're working in a Sorbet file that's `# typed: true`, it's hard to tell at-a-glance which lines are untyped (and somewhat unsafe).

### Proposed solution

Support an LSP request that returns info diagnostics for untyped lines, and (potentially) what % of the file is untyped.

Extensions can make this request for the currently open file(s) to always highlight untyped lines that the developer is actively viewing.

The Flow extension for VS Code has this feature; we should examine its implementation.

**Comment by jvilk-stripe** [comment]
Note: For those who want this functionality today, you can temporarily change your file to `# typed: strong` to see what's untyped; they will surface as errors.

**Comment by manhhung741** [comment]
I think this feature will be very impactful! 
I’m anticipating `untyped` is a big issue once people start “trusting” sorbet to catch errors for them.

**Comment by jez** [comment]
Fixed in #6824.
