### ISSUE TITLE
`srb rbi hidden-definitions` may not reflect some modules

### ISSUE THREAD

**Issue by Slike9** [sorbet/sorbet#4388]
#### Input

I have a Rails project with an AR-model:
```ruby
class Account < ActiveRecord::Base
  ...
end
```

#### Observed output

`srb rbi hidden-definitions` does not reflect some modules from Rails in `hidden.rbi`, e.g. `ActiveModel::Validations::NumericalityValidator`.

#### Expected behavior

`ActiveModel::Validations::NumericalityValidator` and other modules from Rails are defined in `hidden.rbi`.

#### The cause of the problem

There is a code in `Sorbet::Private::ConstantLookupCache` (`sorbet` gem), simply adding ancestors of modules to seen entries without processing: https://github.com/sorbet/sorbet/blob/master/gems/sorbet/lib/constant_cache.rb#L206. Such ancestors risk not to be reflected in `hidden.rbi`.

As for our example, `Account` is processed before `ActiveModel::Validations`, because of sorting. On processing `Account`, `ActiveModel::Validations` is added to seen entries, because it's among the ancestors of `Account`. Later, when `ActiveModel::Validations` is met, it won't be processed, as it's marked as seen, so it won't be reflected in `hidden.rbi`.

Is this behavior intentional? Maybe we need to add ancestors for further processing?

Adding the following code
```ruby
if Sorbet::Private::RealStdlib.real_is_a?(ancestor, Module) && Object != ancestor
  go_deeper << [entry, ancestor, name]
end
```
after https://github.com/sorbet/sorbet/blob/master/gems/sorbet/lib/constant_cache.rb#L206, fixes the problem.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
