### ISSUE TITLE
Type restrictions for `type_member` in Modules not enforced on including class

### ISSUE THREAD

**Issue by tushar-stripe** [sorbet/sorbet#4389]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0Aend%0A%0Aclass%20NonFoo%0Aend%0A%0A%0Amodule%20M%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20interface!%0A%0A%20%20X%20%3D%20type_member(upper%3A%20Foo)%0Aend%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20include%20M%0A%0A%20%20X%20%3D%20type_member(fixed%3A%20NonFoo)%0Aend)

```ruby
# typed: true

class Foo
end

class NonFoo
end


module M
  extend T::Sig
  extend T::Generic
  extend T::Helpers

  interface!

  X = type_member(upper: Foo)
end

class A
  extend T::Sig
  extend T::Generic

  include M

  X = type_member(fixed: NonFoo)
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

I would expect `NonFoo` to not be allowed as a type_member `X` in `A` as `M` has specified all types `X` must be descendants of `Foo`, which `NonFoo` is not.
- - -

**Comment by elliottt** [comment]
An error is raised if the parent is a class:

[sorbet.run link](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0Aend%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20X%20%3D%20type_member(upper%3A%20Foo)%0Aend%0A%0Aclass%20A%20%3C%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20X%20%3D%20type_member(fixed%3A%20Integer)%0Aend)
```ruby
# typed: true

class Foo
end

class Parent
  extend T::Sig
  extend T::Generic

  X = type_member(upper: Foo)
end

class A < Parent
  extend T::Sig
  extend T::Generic

  X = type_member(fixed: Integer)
end
```
