### ISSUE TITLE
Dedenter should handle tabs

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#44]
[https://cibot.corp.stripe.com/builds/bui_DvVJhCAadJJ4Ri]

We should do the same thing that ruby does with them.

Originally reported by @dmitry-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1379

**Comment by Morriar** [comment]
@DarkDimius I think I can handle this one if you provide more details.

**Comment by sharpobject** [comment]
I think "the thing that ruby does with them" may mean what Ruby does for `<<~` heredocs. According to [this PR](https://github.com/ruby/ruby/pull/878), Ruby should do whatever `String#strip_heredoc` from ActiveSupport does:
```ruby
# File activesupport/lib/active_support/core_ext/string/strip.rb, line 22
  def strip_heredoc
    gsub(/^#{scan(/^[ \t]*(?=\S)/).min}/, "".freeze)
  end
```

**Comment by sharpobject** [comment]
It looks like this is already fixed as of 2017 by [this commit](https://github.com/sorbet/sorbet/commit/4089820c419a65ee19c826021a05819098d3a9c9). Is that right?

**Comment by jez** [comment]
There's not enough context in the original report to know whether this is fixed or not. Going to close.
