### ISSUE TITLE
Method signatures not accepting types inheriting from generics

### ISSUE THREAD

**Issue by vinistock** [sorbet/sorbet#4413]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20E%20%3D%20type_member(upper%3A%20T.any(String%2C%20Integer))%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20E%20%3D%20type_member(fixed%3A%20Integer)%0Aend%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params(x%3A%20A%5BT.any(String%2C%20Integer)%5D).void%20%7D%0Adef%20foo(x)%0Aend%0A%0Afoo(B.new))

```ruby
# typed: true

class A
  extend T::Generic

  E = type_member(upper: T.any(String, Integer))
end

class B < A
  extend T::Generic

  E = type_member(fixed: Integer)
end

extend T::Sig

sig { params(x: A[T.any(String, Integer)]).void }
def foo(x)
end

foo(B.new)
```

#### Observed output

```
editor.rb:21: Expected A[T.any(String, Integer)] but found B for argument x https://srb.help/7002
    21 |foo(B.new)
            ^^^^^
  Expected A[T.any(String, Integer)] for argument x of method Object#foo:
    editor.rb:17:
    17 |sig { params(x: A[T.any(String, Integer)]).void }
                     ^
  Got B originating from:
    editor.rb:21:
    21 |foo(B.new)
            ^^^^^
Errors: 1
```

#### Expected behavior

I would have expected no error to be reported in this case, since `B` satisfies the constraints imposed by `A[T.any(String, Integer)]`.

**Comment by jez** [comment]
This is working as intended. `class A` has been declared with no variance annotation, which defaults the variance to `invariant`. The type arguments of `A` and `B` do not match exactly, so there is an error.

The error message doesn't mention it, but improving the error message is tracked in another ticket: https://github.com/sorbet/sorbet/issues/4110

You'll notice that widening the type `B` has been fixed to solves the problem:

https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20E%20%3D%20type_member(upper%3A%20T.any(String%2C%20Integer))%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20E%20%3D%20type_member(fixed%3A%20T.any(Integer%2C%20String))%0Aend%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params(x%3A%20A%5BT.any(String%2C%20Integer)%5D).void%20%7D%0Adef%20foo(x)%0Aend%0A%0Afoo(B.new)

as would factoring out `A`'s interface into a module, and using an `:out` generic to make it covariant:

https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20InterfaceA%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20E%20%3D%20type_member(%3Aout%2C%20upper%3A%20T.any(String%2C%20Integer))%0Aend%0A%0Aclass%20B%0A%20%20include%20InterfaceA%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20E%20%3D%20type_member(fixed%3A%20Integer)%0Aend%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params(x%3A%20InterfaceA%5BT.any(String%2C%20Integer)%5D).void%20%7D%0Adef%20foo(x)%0Aend%0A%0Afoo(B.new)
