### ISSUE TITLE
Should a `noreturn` generic be able to get lost to `untyped`?

### ISSUE THREAD

**Issue by itarato** [sorbet/sorbet#4451]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Foo%0A%20%20extend(T%3A%3ASig)%0A%20%20extend(T%3A%3AGeneric)%0A%0A%20%20T1%20%3D%20type_member%0A%20%20T2%20%3D%20type_member%0A%0A%20%20sig%20%7B%20returns(T1)%20%7D%0A%20%20def%20get_t1%3B%20T.unsafe(nil)%3B%20end%0A%0A%20%20sig%20%7B%20returns(T2)%20%7D%0A%20%20def%20get_t2%3B%20T.unsafe(nil)%3B%20end%0Aend%0A%0Asig%20do%0A%20%20params(%0A%20%20%20%20x%3A%20T.all(%0A%20%20%20%20%20%20Foo%5BT.noreturn%2C%20T.noreturn%5D%2C%20%0A%20%20%20%20%20%20Foo%5BT.noreturn%2C%20Integer%5D%2C%0A%20%20%20%20)%2C%0A%20%20).void%0Aend%0Adef%20bar(x)%0A%20%20bar2(x)%0A%20%20bar3(x)%0Aend%0A%0Asig%20%7B%20params(x%3A%20Foo%5BT.untyped%2C%20T.untyped%5D).void%20%7D%0Adef%20bar2(x)%0A%20%20bar3(x)%0Aend%0A%0Asig%20%7B%20params(x%3A%20Foo%5BInteger%2C%20Integer%5D).void%20%7D%0Adef%20bar3(x)%0Aend)

```ruby
class Foo
  extend(T::Sig)
  extend(T::Generic)

  T1 = type_member
  T2 = type_member

  sig { returns(T1) }
  def get_t1; T.unsafe(nil); end

  sig { returns(T2) }
  def get_t2; T.unsafe(nil); end
end

sig do
  params(
    x: T.all(
      Foo[T.noreturn, T.noreturn], 
      Foo[T.noreturn, Integer],
    ),
  ).void
end
def bar(x)
  bar2(x)
  bar3(x)
end

sig { params(x: Foo[T.untyped, T.untyped]).void }
def bar2(x)
  bar3(x)
end

sig { params(x: Foo[Integer, Integer]).void }
def bar3(x)
end
```

#### Observed output

```
editor.rb:28: Expected Foo[Integer, Integer] but found T.all(Foo[T.noreturn, T.noreturn], Foo[T.noreturn, Integer]) for argument x https://srb.help/7002
    28 |  bar3(x)
          ^^^^^^^
  Expected Foo[Integer, Integer] for argument x of method Object#bar3:
    editor.rb:36:
    36 |sig { params(x: Foo[Integer, Integer]).void }
                     ^
  Got T.all(Foo[T.noreturn, T.noreturn], Foo[T.noreturn, Integer]) originating from:
    editor.rb:26:
    26 |def bar(x)
                ^
Errors: 1
```

#### Expected behavior

I expected `bar2` inside `bar` fail, since that is "turning" a `T.noreturn` to a `T.untyped` - which then can be anything. Is that ok?

**Comment by jez** [comment]
> Is that ok?

Yes, `T.untyped` accepts anything and is accepted by everything.

Here is a simpler example.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Foo%0A%20%20extend(T%3A%3ASig)%0A%20%20extend(T%3A%3AGeneric)%0A%0A%20%20T1%20%3D%20type_member%0A%0A%20%20sig%20%7B%20returns(T1)%20%7D%0A%20%20def%20get_t1%3B%20T.unsafe(nil)%3B%20end%0Aend%0A%0Asig%20%7Bparams(x%3A%20Foo%5BT.noreturn%5D).void%7D%0Adef%20bar(x)%0A%20%20bar2(x)%0A%20%20bar3(x)%0Aend%0A%0Asig%20%7B%20params(x%3A%20Foo%5BT.untyped%5D).void%20%7D%0Adef%20bar2(x)%0A%20%20bar3(x)%0Aend%0A%0Asig%20%7B%20params(x%3A%20Foo%5BInteger%5D).void%20%7D%0Adef%20bar3(x)%0Aend%0A%0Abar2(Foo%5BT.noreturn%5D.new)%0Abar2(Foo%5BInteger%5D.new))

```ruby
# typed: true
extend T::Sig

class Foo
  extend(T::Sig)
  extend(T::Generic)

  T1 = type_member

  sig { returns(T1) }
  def get_t1; T.unsafe(nil); end
end

sig {params(x: Foo[T.noreturn]).void}
def bar(x)
  bar2(x)
  bar3(x)
end

sig { params(x: Foo[T.untyped]).void }
def bar2(x)
  bar3(x)
end

sig { params(x: Foo[Integer]).void }
def bar3(x)
end

bar2(Foo[T.noreturn].new)
bar2(Foo[Integer].new)
```

#### Observed output

```
editor.rb:17: Expected Foo[Integer] but found Foo[T.noreturn] for argument x https://srb.help/7002
    17 |  bar3(x)
          ^^^^^^^
  Expected Foo[Integer] for argument x of method Object#bar3:
    editor.rb:25:
    25 |sig { params(x: Foo[Integer]).void }
                     ^
  Got Foo[T.noreturn] originating from:
    editor.rb:15:
    15 |def bar(x)
                ^
Errors: 1
```

^ this is all expected.

**Comment by jez** [comment]
(Note that other gradual static type checkers have the same behavior on this example, like Flow:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAMTjgB4AVAPjAG9UwwBzAUwBcB9VgRgAoBKAFxhytegzAAnNgFcJAOzA850mDCHY5ATz4BuMQF9UhzHDm5WYAEbYJYALyKAHkOJlmAWwAOrTZT73qOgZrCQAmHkddMRCAZgio4wxTcysbUPsnFxJSDV9-O0DomzjIo3QkswtYjIissmV3S2YJPwDRYxDwuWYkV1IPb19+KM6lHqJshqaW4aA
