### ISSUE TITLE
Abstract classes can be instantiated

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#4454]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20abstract!%0Aend%0A%0AFoo.new)

```ruby
# typed: true

class Foo
  extend T::Helpers

  abstract!
end

Foo.new # Should be a static error?
```

#### Observed output

No error.

#### Expected behavior

Sorbet should catch this?

**Comment by jez** [comment]
https://github.com/sorbet/sorbet/pull/2222

^ @XrXr tried implementing this a long time ago. i haven't looked since then, not sure if anything has changed.

**Comment by jez** [comment]
I don't know why #2143 was closed, so may as well keep this issue open.
