### ISSUE TITLE
Fix dead code bug

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#45]
https://sorbet.run/#class%20ModifyWithPlan%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20def%20foo%0A%20%20end%0A%0A%20%20def%20bar%0A%20%20%20%20charge_struct%20%3D%20nil%0A%20%20%20%20if%20foo%0A%20%20%20%20%20%20charge_struct%20%3D%20%22%22%0A%20%20%20%20end%0A%0A%20%20%20%20validation_charge_struct%20%3D%20nil%0A%20%20%20%20if%20!charge_struct%0A%20%20%20%20%20%20validation_charge_struct%20%3D%20%22%22%0A%20%20%20%20end%0A%0A%20%20%20%20if%20charge_struct%0A%20%20%20%20%20%20puts%20%22charge_struct%22%0A%20%20%20%20%20%20if%20validation_charge_struct%0A%20%20%20%20%20%20%20%20puts%20%22validation%22%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend%0A

Comments:
07/Nov/18 4:13 AM;pt;`y` somehow joined between a NilClass and a T.untyped to get a NilClass

Originally reported by @pt-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1378

**Comment by jez** [comment]
Confusing issue, probably dupe with something else.
