### ISSUE TITLE
Sorbet is gradually uninstalling itself from my project via gem upgrades and `srb rbi gems`

### ISSUE THREAD

**Issue by peternixey** [sorbet/sorbet#4556]
I am extremely confused as to how to update gem RBI files with Sorbet. I have tried doing so a number of different ways but the end result is the same: **Sorbet goes through and switches OFF type checking in more and more of my files**. 

I believe this is happening because as sorbet rebuilds RBI files, it also looks at how many new errors are generated and then switches off typechecking in those files which generate a lot of errors. 

However the end result is that because of a simple gem upgrade I either:

a) have to do hours of work to track down what is causing the new errors that Sorbet has found or...
b) leave typechecking switched off in the affected files. I'm really frustrated by this behaviour because it leaves me at an impasse. I can't afford for every bundle update to take hours of Sorbet checking but I can't afford not to update. And so (not very) gradually Sorbet works its way out of my project. 

### Sequence of events

1. Project is building fine, `srb tc` returns no errors
2. Realise that gems are out of date
3. Run Bundle update
4. Receive the following message from Sorbet (uh oh, this doesn't look good...)
````
Post-install message from sorbet:
  Thanks for installing Sorbet! To use it in your project, first run:

    bundle exec srb init

  which will get your project ready to use with Sorbet.
  After that whenever you want to typecheck your code, run:

    bundle exec srb tc

  For more docs see: https://sorbet.org/docs/adopting
````

5. Run `srb tc`
6. Get 1000 new sorbet errors
7. Run `bundle clean`
8. Run `srb rbi gems`
9. Run `srb tc` - a few errors... but now Sorbet has changed almost every one of my files from `typed: true/strong` to `typed: ignore/false`. 

To highlight what just happened, Sorbet's quietly just unwound itself from almost every file in my project. It's up to me to wind it back in.  And with every file that I mark as `typed: true` it turns out there are a slew of errors caused, it seems, by the RBI files not being correctly generated. Errors like this:

````
sorbet/rails-rbi/active_record_relation.rbi:7: type_member type Enumerable::Elem used outside of the class definition https://srb.help/5027
     7 |  sig { params(args: T.untyped).returns(Elem) }
````

### What should I be doing to avoid / fix this? 

I don't feel like I'm an amateur. I'm no Ruby core developer but I've been developing in Ruby and Rails for 10 years, and yet I have no clue how to deal with this stuff. And it happens every time I update gems in my bundle. 

I love the idea of Sorbet and most of the time I love it in practice (I am very excited for when you release the VSCode plugin). However doing a bundle update is like being taken outside the back of the bar by Sorbet and having your lights kicked out. Why is this so hard (and what might I do to fix it)?

Why have so many files gone from passing typechecking just fine to all of a sudden being broken? Is Sorbet unable to generate RBI files / unable to load them from a repository / has Sorbet been *upgraded* so now all of my code is broken? Some error message or explanations would make all the difference but I don't really know where to start.  

Sorbet prides itself on having gradual adoption which is great but in my experience it also comes with sudden and inexplicable host rejection. Increasingly I start to ask the question as to which I value more, typechecking or having a gemset that's up-to-date. I would hope these aren't mutually exclusive things. 

Thank you for any help you can offer.

**Comment by peternixey** [comment]
Ok, I've spent the past two hours unwinding what was going on here and as a result of that I can offer a but more succinct feedback. 

Obviously it's not a good idea to do a bundle update all in one go, so I started breaking it down and updating gem by gem. All was good until I updated either a) Sorbet to the most recent version (`sorbet (newest 0.5.9090, installed 0.5.6401, requested ~> 0.5.6401)` or b) rails to the most recent version (`rails (newest 6.1.4.1, installed 6.1.3.2, requested ~> 6.1)`). At that point the errors all started blowing up in a way that is just beyond what I can reasonably spend time on right now. 

Some of this is presumably an issue with Rails and with the RBI files around Rails. However there are a couple of suggestions that I'd like to make for Sorbet itself:

1. When running `srb rbi gems` It is terrifying that sorbet will quietly switch off typechecking on files iwth a lot of errors. I can understand that on initializing the project but surely it should be opt-in once Sorbet has been initialized. I very nearly checked in almost my entire project with typechecking switched off. I'm sure it would have been caught in code-review but that's a chance I'd rather not take. 
2. As sorbet is improved it catches more and more issues. As a feature request it would be nice if one could opt-into those more sophisticated issue-catching. Maybe Sorbet could print out the issues that are being ignored at the end of each run. So as more things are picked up you can go into a config file and opt-into them as and when your project (and the gems it depends on) are ready to handle them. 

Unfortunately, the only other obvious alternative is simply not to update Sorbet which seems like a very blunt instrument to solve the problem.

**Comment by peternixey** [comment]
Apologies - one last thing (to highlight the issue at hand) - I am currently sitting on a [security vulnerability](https://github.com/advisories/GHSA-2rqw-v265-jf8c) which came out today and requires an updated version of Rails. 

However, if I update rails, the current version of Sorbet I have blows up with errors. 

But if I don't update Rails then the vulnerability remains unpatched. So I've got a trade-off: patch the vulnerablity and switch off type checking or keep type checking and leave the vulnerablity. I'm honestly not sure what the takeaway for you is with this but it's certainly a conundrum.

**Comment by vaporyhumo** [comment]
Hi Peter 👋 . I'll start by saying that I am just another `sorbet` user; I'm in no way affiliated to sorbet nor Stripe, but will try to help you as much as I can. I have too experienced this frustration.

First, let's tackle the recursive disabling behaviour. The first time you run `srb init` none of your files will have any `# typed:` sigils, so sorbet will naturally read them all. Then in the `suggest-typed` phase each file will be anotated with the highest level it can achieve with no errors. This means that some files **might** get a `# typed: ignore` sigil.

Whether this happens at initialization is not really relevant, but whenever there are **some** `# typed: ignore` files, the next time you run `srb rbi update` or `srb init`, sorbet will not even read the file. This means that any constant defined in that file won't be noticed by sorbet, so any other file that references it will get an error, and may be for that reason end up being ignored too, which means the next time the effect will be bigger... so the more ignored files you have, the more possible it is for this loop to happen. This means, try to address as much ignored files **before** updating, raising them to false is enough.

Second, sorbet is updated mostly daily. I can see that you are trying to jump from 0.5.6401 to 0.5.9090, that means probably some months have happened since the last update. Just as rails, or any big/unstable gem, try to update in smaller steps. Maybe not every sorbet release since, but update a few versions and check; do this isolated from any other changes, update sorbet first, then rails, then other things (or whichever order is easier, just not all together).

Sorbet doesn't have a changelog, so it's really hard to track actual changes, most updates won't require you to change anything, some will, so smaller steps will help here.

Other from that, I would like to know if you are using `sorbet-rails` and/or `tapioca`. Most of the community have found easier to manage their projects with `tapioca` rather than using sorbets built in `rbi` commands.

About the security issue, having a vulnerable dependency doesn't necessarily means that you are affected by that vulnerability; take a look at the details of the vulnerability, and if you suspect you might be vulnerable, try to address that first.

I expect to be of some help, please ask further questions if you need.

**Comment by peternixey** [comment]
Hi Rodrigo, 

Thanks so much for taking the time to make such useful suggestions. I actually went back and started doing things much more incrementally (you're right - `bundle update` is a very clumsy way to do things). 

As I did it I discovered that the Rails updates were generating errors not because the new version of rails was a problem but because there were now two versions of Rails sitting on my local system. Running `bundle clean --force` allowed me to flush them and removed the errors. 

Upgrading sorbet was still hard and continued to produce a lot of errors but I tried switching to Tapioca. I've still got a bunch of errors to fix but it was a good suggestion and I think will make life easier. 

WRT the additional help, thank you for offering - if you have any suggestions as to how to fix this RBI issue that came about from Tapioca I'd be delighted to hear them. 

Thanks again,
Peter


### Suggestions for the Sorbet team:

Guys I'd like to reiterate that I'm firstly very grateful for Sorbet.  With that there are a couple of things that could avoid a lot of heartache.

1. Sorbet seems to get really confused when there's more than one version of a gem installed. To avoid unnecessary warnings for users, print a warning at the end of the typechecking when there is more than one version of a gem in the gemfile (/directory) and that cleaning up the gems (`bundle clean`) may fix the issue.
2. On my system, running `srb rbi update` does redo the typechecking setting at the top of files - can easily wipe out typechecking across a project. I'm not sure if I'm just using it incorrectly but it would be much more helpful to suggest files that have an excess of errors and ask the user if they want typechecking switched off for those files. 
3. When upgrading Sorbet it probably shouldn't print out into the terminal that it's just been added to the system (as if it's brand new) - it might be more helpful for it to detect it already exists and suggest an appropriate command for updating RBI files etc. 

Thank you

**Comment by vaporyhumo** [comment]
> WRT the additional help, thank you for offering - [if you have any suggestions as to how to fix this RBI issue that came about from Tapioca](https://stackoverflow.com/questions/69011654/how-to-fix-an-error-in-a-tapioca-generated-rbi-file) I'd be delighted to hear them.

For what I can see you have a problem with the files tapioca generated for the active record DSL. I haven't used those, but instead use `sorbet-rails` for rails related `.rbi` files. [This][1] is how I would approach a relatively small rails app.

[1]: https://vaporyhumo.hashnode.dev/using-tapioca-with-rails

Now on the actual error you are getting, it seems to me that tapioca is treating `ActiveRecord::Associations::CollectionProxy` as a generic class when it is actually not.

I found out that you can treat any class as a generic in a signature, as long as that class has the `.[]` method. Take a look at these examples:
- [faling][2]
- [passing][3]
- [generic][4]

[2]: https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aclass%20Hola%0A%20%20class%20%3C%3C%20self%0A%20%20%20%20extend%20T%3A%3ASig%0A%20%20end%0Aend%0A%0Asig%20%7B%20returns%28Hola%5BInteger%2C%20Integer%5D%29%20%7D%0Adef%20hola%0Aend%0A
[3]: https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aclass%20Hola%0A%20%20class%20%3C%3C%20self%0A%20%20%20%20extend%20T%3A%3ASig%0A%20%20%20%20%0A%20%20%20%20sig%20%7B%20params%28val%3A%20T.untyped%2C%20other%3A%20T.untyped%29.returns%28T.untyped%29%20%7D%0A%20%20%20%20def%20%5B%5D%28val%2C%20other%29%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Asig%20%7B%20returns%28Hola%5BInteger%2C%20Integer%5D%29%20%7D%0Adef%20hola%0Aend%0A%0AT.reveal_type%28hola%29
[4]: https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aclass%20Hola%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%0A%20%20O_Elem%20%3D%20type_member%0Aend%0A%0Asig%20%7B%20returns%28Hola%5BInteger%2C%20Integer%5D%29%20%7D%0Adef%20hola%0A%20%20Hola%5BInteger%2C%20Integer%5D.new%0Aend%0A%0AT.reveal_type%28hola%29

So... there's a definition for `ActiveRecord::Associations::CollectionProxy.[]` that sorbet is missing out.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
