### ISSUE TITLE
Error 5002 has a go link

### ISSUE THREAD

**Issue by soffes** [sorbet/sorbet#4560]
#### Input

Navigate to https://sorbet.org/docs/error-reference#5002

#### Observed output

There's a link to http://go/types/rbi

#### Expected behavior

I'm guessing that should link to https://sorbet.org/docs/rbi

---

Apologies if this is the wrong place for this sort of feedback! Feel free to redirect me if this is the incorrect place.

**Comment by jez** [comment]
Stripe uses different RBI generation tooling, which is why the doc prefaces that link with "If you are at Stripe"

Thanks for the report but this is written as expected.
