### ISSUE TITLE
Runtime error when using `class << self` syntax

### ISSUE THREAD

**Issue by RyanBrushett** [sorbet/sorbet#4566]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20frozen_string_literal%3A%20true%0A%23%20typed%3A%20true%0A%23%20compiled%3A%20true%0A%0Aclass%20Foo%0A%20%20class%20%3C%3C%20self%0A%20%20%20%20def%20bar%0A%20%20%20%20%20%20%22hello%22%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Aputs%20Foo.bar%0A)

```ruby
# frozen_string_literal: true
# typed: true
# compiled: true

class Foo
  class << self
    def bar
      "hello"
    end
  end
end

puts Foo.bar
```

#### Observed output

An error message during compilation:

```
│test/testdata/compiler/classfields.rb:6:in `<class:Foo>': wrong constant name Object<Class:Object> (RuntimeError)
│        from test/testdata/compiler/classfields.rb:5:in `<top (required)>'
│        from /private/var/tmp/bazel/.../com_stripe_ruby_typer/bazel-out/darwin-fastbuild/bin/external/sorbet_ruby_2_7/toolchain/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
│        from /private/var/tmp/bazel/.../com_stripe_ruby_typer/bazel-out/darwin-fastbuild/bin/external/sorbet_ruby_2_7/toolchain/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
│        from /private/var/tmp/bazel/.../com_stripe_ruby_typer/test/patch_require.rb:33:in `require'
│        from /var/folders/vf/wxc53gg16lb269pj4nh29bcr0000gn/T/tmp.eCLDI4mo:1:in `<main>'
```

#### Expected behavior

Compile and execute!

My example is a modified version of the test at [test/testdata/compiler/classfields.rb](https://github.com/sorbet/sorbet/blob/bd1ca6ba27eae7fee3128556220571a4e9ef30ba/test/testdata/compiler/classfields.rb). In that file, the `class << self` example is commented out, uncommenting it demonstrates the error.

Rewriting the example like `def self.bar # ...` allows it to compile happily!

**Comment by froydnj** [comment]
Thanks!  We have a few testcases for this at the moment:

https://github.com/sorbet/sorbet/blob/76f3aac45c74f2804558a911f758e80aaefa02b6/test/testdata/compiler/disabled/selfclass.rb
https://github.com/sorbet/sorbet/blob/76f3aac45c74f2804558a911f758e80aaefa02b6/test/testdata/compiler/disabled/wrong_constants.rb
