### ISSUE TITLE
Investigate why hidden-definitions.rbi is so large for empty project

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#462]
On a project with an empty `Gemfile`, `hidden-definitions.rbi` is 8,000+ lines.

It's possible we should be

- ignoring some of this output
- moving this output into sorbet-typed

This way we can write better / less brittle snapshot tests for things in `hidden-definitions.rbi`.

**Comment by jasnow** [comment]
@jez - Following up on the Slack thread https://app.slack.com/client/TD7FU18HJ/CHN2L03NH/thread/CHN2L03NH-1564025210.101500
I created a ["empty"](https://github.com/jasnow/empty) repo - PR's/questions are welcome.

**Comment by connorshea** [comment]
~4000 lines of the `hidden.rbi` on Ruby 2.6 is from `Gem` aka RubyGems, so we should probably add an rbi file for that to sorbet.

**Comment by connorshea** [comment]
Also, it looks like class and instance methods are generated under separate module/class definitions, which could probably be fixed.

Right now:
```ruby
class BigDecimal
  def clone(); end

  EXCEPTION_NaN = ::T.let(nil, ::T.untyped)
  SIGN_NaN = ::T.let(nil, ::T.untyped)
  VERSION = ::T.let(nil, ::T.untyped)
end

class BigDecimal
  def self.new(*args, **kwargs); end
end
```

What it should be:
```ruby

class BigDecimal
  def clone(); end

  def self.new(*args, **kwargs); end

  EXCEPTION_NaN = ::T.let(nil, ::T.untyped)
  SIGN_NaN = ::T.let(nil, ::T.untyped)
  VERSION = ::T.let(nil, ::T.untyped)
end
```

**Comment by connorshea** [comment]
2280 lines out of 3800 total in `hidden.rbi` now comes from Bundler, so I think we need to either update the sorbet-typed definitions or have Bundler loaded as a 'normal' gem so it gets put into a `bundler.rbi` file.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
