### ISSUE TITLE
Unable to redefine alias method

### ISSUE THREAD

**Issue by FnControlOption** [sorbet/sorbet#4656]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0A%23%20development_tools.rb%0Aclass%20DevelopmentTools%0A%20%20def%20installation_instructions%0A%20%20%20%20%22Install%20Clang%20or%20run%20%60brew%20install%20gcc%60.%22%0A%20%20end%0A%20%20alias%20custom_installation_instructions%20installation_instructions%0Aend%0A%0A%23%20os%2Fmac%2Fdevelopment_tools.rb%0Aclass%20DevelopmentTools%0A%20%20def%20installation_instructions%0A%20%20%20%20%22Install%20the%20Command%20Line%20Tools%3A%20%60xcode-select%20--install%60%22%0A%20%20end%0A%0A%20%20def%20custom_installation_instructions%0A%20%20%20%20%22Install%20GNU's%20GCC%3A%20%60brew%20install%20gcc%22%0A%20%20end%0Aend%0A)

```ruby
# typed: true

# development_tools.rb
class DevelopmentTools
  def installation_instructions
    "Install Clang or run `brew install gcc`."
  end
  alias custom_installation_instructions installation_instructions
end

# os/mac/development_tools.rb
class DevelopmentTools
  def installation_instructions
    "Install the Command Line Tools: `xcode-select --install`"
  end

  def custom_installation_instructions
    "Install GNU's GCC: `brew install gcc"
  end
end
```

#### Observed output

```
editor.rb:8: Redefining the existing method DevelopmentTools#custom_installation_instructions as a method alias https://srb.help/5037
     8 |  alias custom_installation_instructions installation_instructions
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:17: Previous definition
    17 |  def custom_installation_instructions
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

No error

- - -

A workaround for this is to replace

```rb
alias custom_installation_instructions installation_instructions
```

with

```rb
def custom_installation_instructions
  installation_instructions
end
```

**Comment by jez** [comment]
This is working as intended. Sorbet has to see a consistent, static view of all methods in all classes. The behavior of the above program changes depending on whether one file or another file was required.

The suggested solution is as you mention, to change the program to not use `alias` in this case.

**Comment by FnControlOption** [comment]
I'm curious, does Sorbet resolve methods before it resolves method aliases?
