### ISSUE TITLE
`requires_ancestor` can't see class methods

### ISSUE THREAD

**Issue by jflinter** [sorbet/sorbet#4835]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0Aextend%20T%3A%3AHelpers%0A%0Aclass%20AbstractObject%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns%28String%29%20%7D%0A%20%20def%20self.foo%0A%20%20%20%20'foo'%0A%20%20end%0Aend%0A%0Amodule%20Fooable%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20module%20ClassMethods%0A%20%20%20%20extend%20T%3A%3AHelpers%0A%20%20%20%20requires_ancestor%20%7B%20AbstractObject%20%7D%0A%20%20%20%20%23%20requires_ancestor%20%7B%20T.class_of%28AbstractObject%29%20%7D%20%23%20also%20invalid%0A%0A%20%20%20%20def%20bar%0A%20%20%20%20%20%20foo%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20mixes_in_class_methods%28ClassMethods%29%0Aend%0A)

```ruby
# typed: true
extend T::Sig
extend T::Helpers

class AbstractObject
  extend T::Sig

  sig { returns(String) }
  def self.foo
    'foo'
  end
end

module Fooable
  extend T::Helpers

  module ClassMethods
    extend T::Helpers
    requires_ancestor { AbstractObject }
    # requires_ancestor { T.class_of(AbstractObject) } # also invalid

    def bar
      foo
    end
  end

  mixes_in_class_methods(ClassMethods)
end
```

#### Observed output

```
editor.rb:23: Method foo does not exist on Fooable::ClassMethods https://srb.help/7003
    23 |      foo
              ^^^
Errors: 1
```

#### Expected behavior

Typechecking succeeds.
Alternatively, that calling `requires_ancestor { T.class_of(AbstractObject) }` succeeds (and causes typechecking to succeed).

When defining a module that mixes_in_class_methods, it's common to require that including modules have certain class methods defined. But it seems impossible to communicate this to `requires_ancestor`, as that method can't accept types as arguments.

- - -

**Comment by elliottt** [comment]
cc @Morriar

**Comment by Morriar** [comment]
Hey Jack,

It's in our plans to add support for `requires_ancestor { T.class_of(AbstractObject) }`. I'll keep this issue open as a reminder.

Thanks for the report.

**Comment by jflinter** [comment]
Thank you! If there’s anything I can do to help let me know (I’m likely useless on the C++ side of things but have some experience with the Ruby parts of sorbet…).

**Comment by klardotsh** [comment]
Also interested in helping with this however I can, if there's a reasonable path for an outsider to contributing to this. This is a blocker for porting quite a few `ActiveSupport::Concern` implementations over to proper Sorbet interfaces at my org, as far as I can tell so far.
