### ISSUE TITLE
Regression for Tempfile not having flush

### ISSUE THREAD

**Issue by thomasdziedzic-census** [sorbet/sorbet#4895]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0ATempfile.new%28'test'%29.flush)

```ruby
Tempfile.new("hi").flush
```

#### Observed output

```
-e:1: Method flush does not exist on Tempfile https://srb.help/7003
     1 |Tempfile.new("hi").flush
        ^^^^^^^^^^^^^^^^^^^^^^^^
  Got Tempfile originating from:
    -e:1:
     1 |Tempfile.new("hi").flush
        ^^^^^^^^^^^^^^^^^^
```

#### Expected behavior

With sorbet 0.5.9318 This was type checking fine. After upgrading to 0.5.9363 this error shows up. I expect there to be no error.

- - -

I believe this is a regression that might have been introduced with https://github.com/sorbet/sorbet/pull/4863

For now I'll just shim in flush.

**Comment by bmulholland** [comment]
It's not just flush: rewind, binmode, and mtime all used to exist and no longer do:

https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0At%3DTempfile.new%28'test'%29%0At.flush%0At.rewind%0At.mtime%0At.binmode
