### ISSUE TITLE
Tempfile regressions

### ISSUE THREAD

**Issue by bmulholland** [sorbet/sorbet#4899]
Tempfile has many regressions in addition to #4895 - rewind, binmode, and mtime all used to exist and no longer do. Probably more methods are also missing, these are just what my app has - and see https://github.com/sorbet/sorbet/issues/4897

#### Input

As of 0.5.9363:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0At%3DTempfile.new%28'test'%29%0At.flush%0At.rewind%0At.mtime%0At.binmode)

```ruby
t=Tempfile.new('test')
t.flush
t.rewind
t.mtime
t.binmode
```

#### Observed output

```
Method rewind does not exist on Tempfile
```

#### Expected behavior

The methods exist, as they did in 0.5.9318, and as they actually do on runtime.

**Comment by thomasdziedzic-census** [comment]
Note that Tempfile#flush got fixed at https://github.com/sorbet/sorbet/issues/4895 but the rest have not been fixed.

**Comment by jez** [comment]
Closed in #4898

**Comment by Slike9** [comment]
@jez The issue still takes place, see https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0At%3DTempfile.new%28'test'%29%0At.flush%0At.rewind%0At.mtime%0At.binmode.

**Comment by ashkulz** [comment]
We're also missing `#to_path` in our application.

**Comment by bmulholland** [comment]
@jez Please re-open the issue :)

**Comment by ashkulz** [comment]
@bmulholland I just added the missing methods to `sorbet/missing.rbi` at our end :man_shrugging:

**Comment by jez** [comment]
Sorry I had forgotten to push one of the commits to that PR. I've opened #4907 with the missing commit, which will properly fix this.
