### ISSUE TITLE
Prevent use of GenericClass[T.untyped]

### ISSUE THREAD

**Issue by telekid** [sorbet/sorbet#4965]
### Problem
It is very easy to accidentally instantiate a generic class without passing a type parameter, which results in `GenericClass[T.untyped]` (as documented [here](https://sorbet.org/docs/stdlib-generics#:~:text=Inside%20a%20sig%2C%20just%20writing%20Array%20or%20Hash%20will%20be%20treated%20as%20T%3A%3AArray%5BT.untyped%5D%20and%20T%3A%3AHash%5BT.untyped%2C%20T.untyped%5D%20respectively.).) This pokes a rather large hole in Sorbet's type safety for a few reasons:

 * It is easy for consumers of classes with generics to be completely unaware of the presence of type parameters
 * At a glance, `sig { returns(GenericClass) }` is visually identical to `sig { returns(String) }`, but one is safe and the other is not

(It seems likely that I'm missing a restriction that led to this design decision, possibly related to gradual typing.)

### Proposed solution
Add a configuration option that would cause Sorbet to fail to typechecks if a `sig` includes a class containing unspecified type parameters. In future versions of Sorbet, I would expect this to be the default.

**Comment by jez** [comment]
This is already an error:

https://sorbet.org/docs/error-reference#5046

for legacy reasons, it's reported at `# typed: strict` when the generic class is a class defined in the standard library

**Comment by jez** [comment]
https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Box%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member%0Aend%0A%0Asig%20%7Breturns%28Box%29%7D%0Adef%20foo%3B%20Box.new%3B%20end

**Comment by telekid** [comment]
Oh, looks like I hadn't quite isolated my problem. Perhaps in [this playground](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Box%0A%20%20extend%20T%3A%3AGeneric%0A%20%20extend%20T%3A%3ASig%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7B%20params%28value%3A%20Elem%29.void%20%7D%0A%20%20def%20initialize%28value%29%0A%20%20%20%20T.let%28%40value%2C%20Elem%29%0A%20%20%20%20%40value%20%3D%20value%0A%20%20end%0Aend%0A%0Asig%20%7Breturns%28Box%5BString%5D%29%7D%0Adef%20foo%0A%20%20box%20%3D%20Box.new%28123%29%0A%20%20%23%20box%20%3D%20Box%5BString%5D.new%28123%29%0A%20%20T.reveal_type%28box%29%0Aend), the bug that I'm seeing isn't a failure to require an annotation on L18, but rather a failure of L18's `box` instance to infer the `Elem` type parameter's type as `Integer`? Is there a way for me to modify this playground so that it will fail checking without requiring the author to remember to specify the correct type parameter (as on L19)?
