### ISSUE TITLE
Incorrect override detection for interfaces with methods that have the same name as those in Kernel

### ISSUE THREAD

**Issue by jkehres** [sorbet/sorbet#5014]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Interface%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20sig%20%7B%20abstract.params%28foo%3A%20String%2C%20bar%3A%20String%29.void%20%7D%0A%20%20def%20warn%28foo%2C%20bar%29%3B%20end%0Aend%0A%0Aclass%20ConcreteClass%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20include%20Interface%0A%0A%20%20sig%20%7B%20override.params%28foo%3A%20String%2C%20bar%3A%20String%29.void%20%7D%0A%20%20def%20warn%28foo%2C%20bar%29%0A%20%20%20%20%23%20TODO%0A%20%20end%0Aend)

```ruby
# typed: true
module Interface
  extend T::Sig
  extend T::Helpers
  interface!

  sig { abstract.params(foo: String, bar: String).void }
  def warn(foo, bar); end
end

class ConcreteClass
  extend T::Sig
  extend T::Helpers
  include Interface

  sig { override.params(foo: String, bar: String).void }
  def warn(foo, bar)
    # TODO
  end
end
```

#### Observed output

```
editor.rb:17: Override of method Kernel#warn must accept *msg https://srb.help/5035
    17 |  def warn(foo, bar)
          ^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L2717: Base method defined here
    2717 |  def warn(*msg); end
            ^^^^^^^^^^^^^^

editor.rb:17: Override of method Kernel#warn must accept no more than 0 required argument(s) https://srb.help/5035
    17 |  def warn(foo, bar)
          ^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L2717: Base method defined here
    2717 |  def warn(*msg); end
            ^^^^^^^^^^^^^^

editor.rb:17: Return type Sorbet::Private::Static::Void does not match return type of overridden method Kernel#warn https://srb.help/5035
    17 |  def warn(foo, bar)
          ^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L2717: Super method defined here with return type NilClass
    2717 |  def warn(*msg); end
            ^^^^^^^^^^^^^^
Errors: 3
```

#### Expected behavior

Sorbet should understand that `ConcreteClass#warn` is overriding `Interface#warn` and not `Kernel#warn`.

- - -

NOTE: Any method in `Interface` with the same name as one in `Kernel` will cause this problem. I just chose `warn` for this example.

I'm currently using a workaround for this problem. If I have an abstract class implement the interface first then have my concrete class extend the abstract class, Sorbet will correctly detect that my intent is to override `Interface#warn` and not `Kernel#warn`. Here is the same example as before with my workaround:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Interface%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20sig%20%7B%20abstract.params%28foo%3A%20String%2C%20bar%3A%20String%29.void%20%7D%0A%20%20def%20warn%28foo%2C%20bar%29%3B%20end%0Aend%0A%0Aclass%20AbstractClass%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20include%20Interface%0A%20%20abstract!%0Aend%0A%0Aclass%20ConcreteClass%20%3C%20AbstractClass%0A%20%20sig%20%7B%20override.params%28foo%3A%20String%2C%20bar%3A%20String%29.void%20%7D%0A%20%20def%20warn%28foo%2C%20bar%29%0A%20%20%20%20%23%20TODO%0A%20%20end%0Aend)

```ruby
# typed: true
module Interface
  extend T::Sig
  extend T::Helpers
  interface!

  sig { abstract.params(foo: String, bar: String).void }
  def warn(foo, bar); end
end

class AbstractClass
  extend T::Sig
  extend T::Helpers
  include Interface
  abstract!
end

class ConcreteClass < AbstractClass
  sig { override.params(foo: String, bar: String).void }
  def warn(foo, bar)
    # TODO
  end
end
```

**Comment by jez** [comment]
This is by design. If a program contained a sig like this:

```ruby
sig {params(x: Kernel).void}
def foo(x)
  x.warn("1", "2", "3", "4", "5")
end

foo(ConcreteClass.new)
```

This program will type check, but will raise an exception at runtime, because `warn` has an incompatible arity on `ConcreteClass`. The behavior in Sorbet is designed to discourage users from designing problematic APIs like this.

The first suggestion is to pick a different method name. This will work best long term, with few consequences.

The fallback suggestion, if you must use the same name with a conflicting arity, is to explicitly declare that the override is incompatible:

```ruby
  # DISCOURAGED, see notes above and below
  sig { override(allow_incompatible: true).params(foo: String, bar: String).void }
  def warn(foo, bar)
    # TODO
  end
```

This will silence the error you're seeing, but do nothing to solve the problem that if some sig takes a `Kernel` (or in this case, even `Object`, since `Object < Kernel`, which is more common), there can be runtime errors that Sorbet reports no errors for.
