### ISSUE TITLE
Simple sorbet commands result in typechecking being switched off in files and whitewashing of errors

### ISSUE THREAD

**Issue by peternixey** [sorbet/sorbet#5028]
There are a number of commands which result in sorbet changing the typechecking status of files:

For instance running `srb rbi gems` results in the following commits being generated:

![image](https://user-images.githubusercontent.com/168592/147080686-ce38f8cc-ebed-4e51-9065-2270970fe5de.png)

![image](https://user-images.githubusercontent.com/168592/147080703-7297537d-d447-4b70-98d0-4cdc1b8d7b25.png)

I assume this happens because sorbet notices that those files now generate a number of typechecking erorrs. This is an issue which needs to be addressed - those errors need to be fixed. But instead of that what actually happens is this:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/168592/147080919-912185ed-cd65-4e9a-acb9-ba500d0b760e.png">

It looks like everything's cool and so it gets committed and forgotten about. And the value of the typechecking is lost. 

I don't know why Sorbet is configured this way but it's very frustrating. It means that it's really easy for the typechecking to melt away in the project.

**Comment by peternixey** [comment]
hi folks - is there any update on this? Am I doing things wrong? It's a bit frightening that every time I run `srb rbi gems` half of my files get changed to `typed: ignore`. 

Thank you!

**Comment by peternixey** [comment]
@Morriar - thanks for coming back to me so quickly :) I've tried tapioca and it's ended up being even harder still to get working but I have heard good things so will try giving it another shot. For now I'm just freezing sorbet at the last working version!

**Comment by jez** [comment]
Sorbet should never suggest `# typed: ignore` anymore, as of #6164.

In general, we recommend switching to Tapioca:

https://sorbet.org/blog/2022/07/27/srb-tapioca
