### ISSUE TITLE
Restricting where a module can be included?

### ISSUE THREAD

**Issue by Overload119** [sorbet/sorbet#5043]
### Problem

Is there a way, similar to a sealed class except on the module level. Example:

```
class Foo
  def bar
  end
end
```

```
module AddPowerToFoo
  def power
    bar(test) # <-- This will error.
  end 
end
```

I want to restrict or tell AddPowerToFoo that it can only be included in class of type Foo.

**Comment by paracycle** [comment]
I think what you are after is this experimental feature: https://sorbet.org/docs/requires-ancestor
