### ISSUE TITLE
Create a coc.nvim extension

### ISSUE THREAD

**Issue by luisdavim** [sorbet/sorbet#5065]
### Problem

The vscode extension looks great, I'd love to see it as a coc.nvim extension.

### Proposed solution

Convert the vscode extension to a coc extension, https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions

**Comment by jez** [comment]
Hey! It looks like coc.nvim already supports Sorbet

https://github.com/neoclide/coc.nvim/wiki/Language-servers#using-sorbet

**Comment by luisdavim** [comment]
> Hey! It looks like coc.nvim already supports Sorbet
> 
> https://github.com/neoclide/coc.nvim/wiki/Language-servers#using-sorbet

Yeah but that's not really the same as the extension, it has a subset of the features only...
