### ISSUE TITLE
Regression while using Class#subclasses

### ISSUE THREAD

**Issue by ashkulz** [sorbet/sorbet#5144]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%0A%20%20def%20self.hello%3B%20end%0Aend%0Aclass%20B%20%3C%20A%3B%20end%0Aclass%20C%20%3C%20A%3B%20end%0A%0Asig%20{void}%0Adef%20foo%0A%20%20A.subclasses.each(%26%3Ahello)%0Aend%0A)

```ruby
# typed: true
extend T::Sig

class A
  def self.hello; end
end
class B < A; end
class C < A; end

sig {void}
def foo
  A.subclasses.each(&:hello)
end
```

#### Observed output

```
editor.rb:12: Method hello does not exist on Class https://srb.help/7003
    12 |  A.subclasses.each(&:hello)
                             ^^^^^^
  Got Class originating from:
    editor.rb:12:
    12 |  A.subclasses.each(&:hello)
                             ^
Errors: 1
```

#### Expected behavior

This is a regression from #5125 -- the return value should be the instance of the class on which this method is being called, but not really sure if that's possible to do via Sorbet.

Alternatively, I think this should be marked as only available from Ruby 3.1 -- not sure if that's really supported either :man_shrugging: 

- - -

This is also [defined by `activesupport`](https://github.com/chanzuckerberg/sorbet-rails/blob/be36a1083ef0873ac59a5253988fff2f5d4f1824/sorbet/rbi/gems/activesupport.rbi#L619), which is where we're using it from.

**Comment by Morriar** [comment]
👋 Hey Ashish,

Trying to run your snippet with Ruby 3.1 returns an error. Are you sure your example is correct?

```
Error: `each': undefined method `hello' for C:Class (NoMethodError)

A.subclasses.each(&:hello)
            ^^^^^
```

Closing this until we figure what is the expected behaviour here.

**Comment by ashkulz** [comment]
@Morriar I'm sorry, I did a typo -- it should've been `self.hello` in the base class. Can you check now?

**Comment by ashkulz** [comment]
Thanks for fixing this so quickly, @Morriar!
