### ISSUE TITLE
Missing dead code error with .is_a?

### ISSUE THREAD

**Issue by steved-stripe** [sorbet/sorbet#5172]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%20T.let%28%22foo%22%2C%20T.nilable%28String%29%29%0A%0Aclass%20PresentButEmpty%20end%0A%0Az%20%3D%20x.is_a%3F%28PresentButEmpty%29%20%3F%20%22foo%22%20%3A%20%22bar%22%0A%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%20dead%20code%3F)

```ruby
# typed: true

x = T.let("foo", T.nilable(String))

class PresentButEmpty end

z = x.is_a?(PresentButEmpty) ? "foo" : "bar"
#                              ^^^^ dead code?
```

#### Observed output

```
No errors! Great job.
```
#### Expected behavior

I think it should error that "foo" is dead code

**Comment by jez** [comment]
Duplicate of #621
