### ISSUE TITLE
Generic User-Defined Types

### ISSUE THREAD

**Issue by Overload119** [sorbet/sorbet#5220]
### Problem

I noticed documentation [here](https://sorbet.org/docs/stdlib-generics) mentioneding used defined generic types are available. However, I can't find any documentation on how to actually do that.

Is it possible to support something like this:

```rb
class Result[T] < T::Struct
  const :result, T.nilable(T)
  const :message, T.nilable(String)
end
```

### Proposed solution

```rb
class Result[T] < T::Struct
  const :result, T.nilable(T) 
  const :message, T.nilable(String)
end

{ returns(Result[String]) }
def return_string
end
```

**Comment by Overload119** [comment]
It looks like this is kind of supported but not documented. I found some examples in the https://github.com/chanzuckerberg/sorbet-rails/ codebase.

🤔

**Comment by DanielGilchrist** [comment]
You can achieve this using `type_member` 
[Example in Sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Result%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20const%20%3Aresult%2C%20T.nilable%28Elem%29%20%0A%20%20const%20%3Amessage%2C%20T.nilable%28String%29%0Aend%0A%0Asig%20%7B%20returns%28Result%5BString%5D%29%20%7D%0Adef%20return_string%0A%20%20Result%5BString%5D.new%28result%3A%20%22Value%22%2C%20message%3A%20%22Hello%22%29%0Aend%0A%0Ax%20%3D%20return_string%0AT.reveal_type%28x%29%0A%0AResult%5BString%5D.new%28result%3A%205%2C%20message%3A%20%22Wrong%20type%22%29)

There aren't any docs at the moment but there are examples in sorbet.run under the "Examples" dropdown
[sorbet.run "Generic Class" example](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Box%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7Breturns%28Elem%29%7D%0A%20%20attr_reader%20%3Ax%0A%0A%20%20sig%20%7Bparams%28x%3A%20Elem%29.returns%28Elem%29%7D%0A%20%20attr_writer%20%3Ax%0Aend%0A%0ABox%5BInteger%5D.new.x%20%2B%20Box%5BString%5D.new.x)

**Comment by Overload119** [comment]
Thanks - that gets the job done.

https://github.com/sorbet/sorbet/pull/5221/
