### ISSUE TITLE
Missing autocorrect to mark a method final in a final class

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#5225]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20final!%0A%0A%20%20sig%20%7Breturns%28NilClass%29%7D%0A%20%20def%20foo%0A%20%20end%0Aend)

```ruby
# typed: strict

class A
  extend T::Sig
  extend T::Helpers

  final!

  sig {returns(NilClass)}
  def foo
  end
end
```

#### Observed output

```
editor.rb:10: A was declared as final but its method foo was not declared as final https://srb.help/5048
    10 |  def foo
          ^^^^^^^
Errors: 1
```

#### Expected behavior

There should be an autocorrect associated with this error.

- - -

**Comment by froydnj** [comment]
This is #5169 ?
