### ISSUE TITLE
Implement static checks for `implementation`

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#526]
### Problem
Runtime typesystem does more checks on `abstract` & `implementation` than static.
https://sorbet.run/#%23%20typed%3A%20strict%0Amodule%20MyModule%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20sig%20%7Babstract.void%7D%0A%20%20def%20main%3B%20end%0Aend%0A%0Aclass%20MyGoodClass%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20MyModule%0A%0A%20%20sig%20%7Bimplementation.void%7D%0A%20%20def%20main%3B%20end%0Aend%0A%0Aclass%20MyBadClass%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20MyModule%0A%0A%20%20sig%20%7Bvoid%7D%20%23%20runtime%20error%20because%20it's%20not%20marked%20as%20implementation%20%3A(%0A%20%20def%20main%3B%20end%0Aend%0A

is an error in runtime but not in static.

### Proposed solution
Do it in c++

Related #69 
Related: http://go/J9aNQGbw

**Comment by Morriar** [comment]
This issue seems fixed, from your link Sorbet static answers with:

```
editor.rb:24: Method MyBadClass#main implements an abstract method MyModule#main but is not declared with .implementation https://srb.help/5051
    24 |  def main; end
          ^^^^^^^^
    editor.rb:8: defined here
     8 |  def main; end
          ^^^^^^^^
Errors: 1
```
