### ISSUE TITLE
type_parameters does not seem to work with generics

### ISSUE THREAD

**Issue by itarato** [sorbet/sorbet#5268]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Foo%0A%20%20extend%28T%3A%3AGeneric%29%0A%20%20SelfT%20%3D%20type_member%0Aend%0A%0Asig%20%7B%20type_parameters%28%3AX%29.params%28v%3A%20T%3A%3AArray%5BT.type_parameter%28%3AX%29%5D%29.void%20%7D%0Adef%20arr%28v%29%3B%20end%0A%0Asig%20%7B%20type_parameters%28%3AX%29.params%28v%3A%20Foo%5BT.type_parameter%28%3AX%29%5D%29.void%20%7D%0Adef%20gen%28v%29%3B%20end%0A%0Aarr%28%5B1%5D%29%0Agen%28Foo%5BInteger%5D.new%29)

```ruby
class Foo
  extend(T::Generic)
  SelfT = type_member
end

sig { type_parameters(:X).params(v: T::Array[T.type_parameter(:X)]).void }
def arr(v); end

sig { type_parameters(:X).params(v: Foo[T.type_parameter(:X)]).void }
def gen(v); end

arr([1])
gen(Foo[Integer].new) # <- error
```

#### Observed output

```
editor.rb:16: Expected Foo[T.type_parameter(:X)] but found Foo[Integer] for argument v https://srb.help/7002
    16 |gen(Foo[Integer].new)
            ^^^^^^^^^^^^^^^^
  Expected Foo[T.type_parameter(:X)] for argument v of method Object#gen:
    editor.rb:12:
    12 |sig { type_parameters(:X).params(v: Foo[T.type_parameter(:X)]).void }
                                         ^
  Got Foo[Integer] originating from:
    editor.rb:16:
    16 |gen(Foo[Integer].new)
            ^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Expected: `type_parameters` works with non built in generic types: `gen(Foo[Integer].new)` sets `type_parameters(:X)` to `Integer`

Actual: `type_parameters` seems to work correctly with built in generic types only (T::Array, T::Hash, T::Set, etc)

**Comment by jez** [comment]
It's weird that using `:in` makes the error go away, but we think this might in fact be a bug (hard to say for sure until we look  into it).
