### ISSUE TITLE
`T.type_parameter` incorrectly narrowed to `T.noreturn`

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#5308]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters%28%3AV%29%0A%20%20%20%20%20%20.params%28value%3A%20T.nilable%28T.type_parameter%28%3AV%29%29%29%0A%20%20%20%20%20%20.returns%28T.type_parameter%28%3AV%29%29%20%0A%20%20end%0A%20%20def%20self.foo%28value%29%0A%20%20%20%20T.must%28value%29%0A%20%20end%0Aend%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params%28x%3A%20Integer%29.void%20%7D%0Adef%20with_typed_value%28x%29%0A%20%20res%20%3D%20Foo.foo%28x%29%20%23%20returns%20%60Integer%60%0A%20%20T.reveal_type%28res%29%20%23%20error%3A%20Revealed%20type%3A%20Integer%0Aend%0A%0Asig%20%7B%20params%28x%3A%20T.untyped%29.void%20%7D%0Adef%20with_untyped_value%28x%29%0A%20%20res%20%3D%20Foo.foo%28x%29%20%23%20returns%20%60T.noreturn%60%0A%20%20T.reveal_type%28res%29%20%23%20error%3A%20This%20code%20is%20unreachable%0Aend)

```ruby
# typed: true

class Foo
  extend T::Sig

  sig do
    type_parameters(:V)
      .params(value: T.nilable(T.type_parameter(:V)))
      .returns(T.type_parameter(:V)) 
  end
  def self.foo(value)
    T.must(value)
  end
end

extend T::Sig

sig { params(x: Integer).void }
def with_typed_value(x)
  res = Foo.foo(x) # returns `Integer`
  T.reveal_type(res) # error: Revealed type: Integer
end

sig { params(x: T.untyped).void }
def with_untyped_value(x)
  res = Foo.foo(x) # returns `T.noreturn`
  T.reveal_type(res) # error: This code is unreachable
end
```

#### Observed output

When the input is `T.untyped`, the returned type is `T.noreturn`. 

#### Expected behavior

It should return `T.untyped`?

- - -

This seems related to https://github.com/sorbet/sorbet/issues/3461 and https://github.com/sorbet/sorbet/issues/2860.

**Comment by jez** [comment]
Sorry, I duplicated this when opening #5468. There is more context in that issue, so I'm going to close this one. In any case I've started on a prototype for this in #5948.
