### ISSUE TITLE
Call to method nil? on unconstrained generic type T.type_parameter(:T)

### ISSUE THREAD

**Issue by will** [sorbet/sorbet#5336]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%20%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3AT%29%0A%20%20.params%28k%3A%20Symbol%2C%20v%3A%20T.type_parameter%28%3AT%29%29%0A%20%20.void%20%0Aend%0Adef%20add%28k%2C%20v%29%0A%20%20unless%20v.nil%3F%0A%20%20%20%20%23%20add%20to%20hash%0A%20%20end%0Aend%0A%0A)

```ruby
 # typed: strict
extend T::Sig

sig do
  type_parameters(:T)
  .params(k: Symbol, v: T.type_parameter(:T))
  .void 
end
def add(k, v)
  unless v.nil?
    # add to hash
  end
end

```

#### Observed output

```
editor.rb:10: Call to method nil? on unconstrained generic type T.type_parameter(:T) (of Object#add) https://srb.help/7038
    10 |  unless v.nil?
                   ^^^^
  Got T.type_parameter(:T) (of Object#add) originating from:
    editor.rb:9:
     9 |def add(k, v)
                   ^
Errors: 1
```

#### Expected behavior

No error. Some recent change in the last week or so has made this stop type checking, where it had been fine before. I haven't figured out exactly which commit introduced this type checking error.

Basic methods such as `nil?` that are on Object should be allowed for type parameters, as they are on every object.

**Comment by jez** [comment]
This is expected, the same as calls to `is_a?`, and the same as snippets like this:

https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20M%0Aend%0A%0Asig%20%7Bparams%28x%3A%20M%29.void%7D%0Adef%20foo%28x%29%0A%20%20puts%28x.nil%3F%29%0A%20%20puts%28x.is_a%3F%28NilClass%29%29%0Aend

The workaround is to do one of these things:

- use `T.all(Kernel, T.type_parameter(:U))` instead
- use `case x when NilClass`

**Comment by jez** [comment]
https://github.com/sorbet/sorbet/pull/5305 is the PR

**Comment by will** [comment]
Thanks for the workarounds
