### ISSUE TITLE
SelfTypeParam::derivesFrom called when implementing a method on Array

### ISSUE THREAD

**Issue by XrXr** [sorbet/sorbet#538]
#### Input

[→ View on sorbet.run](https://sorbet.run/#class%20Array%0A%20%20def%20foo%0A%20%20%20%20each%20%7B%20%7Ck%2C%20v%7C%20%7D%0A%20%20end%0Aend%0A)

```ruby
class Array
  def foo
    each { |k, v| }
  end
end
```

#### Observed output

```
Exception::raise(): SelfTypeParam::derivesFrom not implemented, not clear what it should do. Let's see this fire first.
```

PS. You need to make some syntax errors on purpose to see the crash message. It looks like the output pane isn't updated when a crash like this happens. Possibly something that should be fixed to facility bug report like this one?

#### Expected behavior

It shouldn't crash.

**Comment by Morriar** [comment]
Seems to be fixed on recent versions.
