### ISSUE TITLE
Bug in Sorbet parser: while inside begin/rescue block

### ISSUE THREAD

**Issue by krschacht** [sorbet/sorbet#5419]
Sorbet is complaining about a parse error, telling me unexpected token on "while", but it's a valid token.

#### Input

```ruby
# typed: strict

module External
    class Tester
        extend T::Sig

        sig { void }
        def self.testme

            begin
                puts "do something"
                while (false) do
                    puts "do something"
                end
            rescue => e
            end
        end
    end
end
```

#### Observed output

```
unexpected token "while"
```

#### Expected behavior

This is correct ruby and "while" executes fine by ruby itself.

**Comment by krschacht** [comment]
To make sorbet happy, I'm working around this by changing this:

```
while (true condition) do
   # ...
end
```

to:

```
loop do
  break unless (true condition)
  # ...
end
```

**Comment by jez** [comment]
Thanks for the report. I've bisected the problem back to #5275 and I've got a change that fixes this locally. I'll put up a PR shortly.
