### ISSUE TITLE
Configurable messages to point to different Slack rooms and/or documentation

### ISSUE THREAD

**Issue by technicalpickles** [sorbet/sorbet#5476]
### Problem

I was trying to replace a method on a class, and got this error:

```
You're trying to replace create on Redacted, but that method exists in a prepended module (Redacted), which we don't currently support. Talk to #dev-productivity for help.
```

I originally assumed this was from code that was in the prepended module, and asked in that channel (which also has `dev` in the name), and someone pointed out this is coming from sorbet actually

https://github.com/sorbet/sorbet/blob/ebe537d200780ff64dab06eaca250b6fda579221/gems/sorbet-runtime/lib/types/private/class_utils.rb#L72-L95

### Proposed solution

I'd propose default linking to public documentation rather than a Slack channel. If an organization has a channnel and/or documentation, it would be nice to be able to configure that as well.

cc @AlexEvanczuk

**Comment by froydnj** [comment]
Yes, I think it makes sense to replace the "Talk to #dev-productivity." bits in `sorbet-runtime` with some kind of `T::Configuration` hook instead; the relevant messages would then check the value set by the hook and insert that if necessary.
