### ISSUE TITLE
Invalid method definitions with ruby 2.7 argument forwarding

### ISSUE THREAD

**Issue by aramgre** [sorbet/sorbet#5479]
Generated gem RBIs have invalid definitions for methods defined with the argument forwarding syntax `def f(...)` introduced in ruby 2.7. This issue was fixed for hidden-definitions in https://github.com/sorbet/sorbet/pull/3422, however `rbi gems` still seems to be affected.

#### Input
Use this Gemfile and run `bundle exec srb init`

```ruby
source "https://rubygems.org"
ruby "2.7.5"
gem "sorbet", "0.5.9763"
gem "rails", "7.0.2.3"
```

#### Observed output

Files under sorbet/rbi/gems have invalid method definitions such as this:
```ruby
  def logger(**, &&); end
```
apparently corresponding to methods defined by rails `delegate` which uses the `...` argument fowarding syntax https://github.com/rails/rails/blob/v7.0.2.3/activesupport/lib/active_support/core_ext/module/delegation.rb#L202
#### Expected behavior

The generated method definitions should be valid:
```ruby
  def logger(*arg0, &arg1); end
```

**Comment by Morriar** [comment]
Not a direct solution to your problem but you should consider using [Tapioca](https://github.com/Shopify/tapioca#tapioca) instead of `srb rbi`. This particular problem as already been fixed and it brings more features as well as RBI generation for DSL such as Rails.

**Comment by aramgre** [comment]
Thanks @Morriar, we have been evaluating both actually. We'll probably land on Tapioca but just thought it would be useful to document this issue.

**Comment by jez** [comment]
Closing in favor of tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
