### ISSUE TITLE
Allow renaming functions to constants

### ISSUE THREAD

**Issue by qaisjp** [sorbet/sorbet#5486]
### Problem

I have some Ruby tests that for various reasons use a function instead of a constant:

```ruby
def origin; "https://example.com"; end

it "does the job" do
  SomeJob.enqueue(origin: origin)
end
```

I want the code to look like:

```ruby
ORIGIN = "https://example.com"

it "does the job"
  SomeJob.enqueue(origin: ORIGIN)
end
```

I tried to rename the function to `ORIGIN`, so that the code would refactor to this (so then I could just change the function to a constant manually):

```ruby
def ORIGIN; "https://example.com"; end

it "does the job"
  SomeJob.enqueue(origin: ORIGIN)
end
```

But the LSP wouldn't let me, saying (sic):

> Method names must begin with an lowercase letter.

### Proposed solution

Remove this check:

https://github.com/sorbet/sorbet/blob/db69c5c127d136d49f206e846cbb986cc9818f2f/main/lsp/requests/rename.cc#L250-L255

It was introduced here, in this pull request by @soam-stripe: https://github.com/sorbet/sorbet/pull/3625/files#diff-673788f6ade0f2b8b34e84f5afec0f8c19459a434b0be1504330afd6e7940c8aR289-R293

**Comment by paracycle** [comment]
Btw, `"Method names must begin with a lowercase letter."` isn't even correct as evidenced by [`Kernel#Array`](https://ruby-doc.org/core-3.1.0/Kernel.html#Array-method) and friends
