### ISSUE TITLE
Generics without a [] shouldn't be valid types

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#56]
Comments:
02/Oct/18 5:29 PM;pt;I think this should just be an error
https://sorbet.run/#extend%20T%3A%3AHelpers%0A%0Asig%20%7Breturns(T%3A%3AHash)%7D%0Adef%20foo%0A%20%20T.unsafe(nil)%0Aend

Originally reported by @pt-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1239

**Comment by marianosimone** [comment]
This is now fixed. At least since https://github.com/sorbet/sorbet/pull/1331
