### ISSUE TITLE
Undefined method, called with a block (proc), is not reported as undefined

### ISSUE THREAD

**Issue by Slike9** [sorbet/sorbet#5605]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Adef%20foo%28%26b%29%0A%20%20%23%20Should%20report%20%22Method%20undefined_method%20does%20not%20exist%22%0A%20%20undefined_method%28%26b%29%0Aend%0A%0Aprc%20%3D%20-%3E%20%7B%7D%0A%23%20Should%20report%20%22Method%20undefined_method%20does%20not%20exist%22%0Aundefined_method%28%26prc%29)

```ruby
# typed: true
extend T::Sig

def foo(&b)
  # Should report "Method undefined_method does not exist"
  undefined_method(&b)
end

prc = -> {}
# Should report "Method undefined_method does not exist"
undefined_method(&prc)
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

```
editor.rb:6: Method undefined_method does not exist on Object https://srb.help/7003
     6 |  undefined_method
          ^^^^^^^^^^^^^^^^

editor.rb:11: Method undefined_method does not exist on T.class_of(<root>) https://srb.help/7003
    11 |undefined_method
        ^^^^^^^^^^^^^^^^
 
Errors: 2
```

- - -

**Comment by jez** [comment]
thanks for the report
