### ISSUE TITLE
Generics in props should work (maybe with some restrictions?)

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#573]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Foo%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3AGeneric%0A%20%20A%20%3D%20type_member%0A%0A%20%20prop%20%3Aaa%2C%20T%3A%3AArray%5BA%5D%0Aend)

```ruby
# typed: true
class Foo < T::Struct
  extend T::Generic
  A = type_member

  prop :aa, T::Array[A]
end
```

#### Observed output

```
Expression does not have a fully-defined type (Did you reference another class's type members?)
```

#### Expected behavior

Works
- - -

Reported by @xton-stripe

**Comment by jez** [comment]
Looks to be fixed. Not sure whe.
