### ISSUE TITLE
VSCode extension fails to start with "Sorbet metrics gathering disabled: Error: command 'sorbet.metrics.getExportedApi' not found"

### ISSUE THREAD

**Issue by pcothenet** [sorbet/sorbet#5736]
#### Input

- Installed sorbet on the project
- Successfully ran `srb init` on the project. `srb tc` passes with no errors
- Installed the VScode extension, it keeps restarting with the error below

I have tried toying with some `"sorbet.lspConfigs"` values, to no avail.

#### Observed output

```
Running Sorbet LSP with:
    bundle exec srb tc --lsp
[Error - 10:12:54 AM] Connection to server got closed. Server will not be restarted.
Sorbet metrics gathering disabled: Error: command 'sorbet.metrics.getExportedApi' not found
```

Executing `bundle exec srb tc --lsp` in the terminal returns no visible errors:
<img width="533" alt="Screen Shot 2022-05-03 at 10 19 40 AM" src="https://user-images.githubusercontent.com/1460006/166505472-729e7d3b-603c-48d6-9044-3ef74750fe61.png">

#### Expected behavior

The VSCode extension starts properly

**Comment by pcothenet** [comment]
OK, it seems that my VS Code was trying to run the language server on a different version of ruby than the one my terminal was using (explaining the discrepancy).

Got it to work by fixing my local versions. I'm still getting `Sorbet metrics gathering disabled: Error: command 'sorbet.metrics.getExportedApi' not found` though, but the extension works.

**Comment by jez** [comment]
This "error" is not an error. Sorbet is merely trying to say that if you'd like to enable metrics gathering, you'd have to define that command.

This log line is confusing, so I've reworded it in #6188.

**Comment by pcothenet** [comment]
Super clear, thank you @jez !
