### ISSUE TITLE
Missing error when constructing instance of generic class

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#5773]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aclass%20Box%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member%0Aend%0A%0Abox%20%3D%20Box.new%20%20%20%20%20%20%23%20missing%20error%20here%0AT.reveal_type%28box%29%20%23%20%60Box%5BT.untyped%5D%60%0A%0Asig%20%7Bparams%28box%3A%20Box%29.void%7D%20%23%20error%20reported%20correctly%20here%0Adef%20example%28box%29%0A%20%20T.reveal_type%28box%29%20%23%20%60Box%5BT.untyped%5D%60%0Aend)

```ruby
# typed: strict
extend T::Sig

class Box
  extend T::Generic
  Elem = type_member
end

box = Box.new      # missing error here
T.reveal_type(box) # `Box[T.untyped]`

sig {params(box: Box).void} # error reported correctly here
def example(box)
  T.reveal_type(box) # `Box[T.untyped]`
end
```

#### Observed output

```
editor.rb:12: Malformed type declaration. Generic class without type arguments Box https://srb.help/5045
    12 |sig {params(box: Box).void} # error reported correctly here
                         ^^^

editor.rb:14: Revealed type: Box[T.untyped] https://srb.help/7014
    14 |  T.reveal_type(box) # `Box[T.untyped]`
          ^^^^^^^^^^^^^^^^^^
  Got Box[T.untyped] originating from:
    editor.rb:13:
    13 |def example(box)
                    ^^^

editor.rb:10: Revealed type: Box[T.untyped] https://srb.help/7014
    10 |T.reveal_type(box) # `Box[T.untyped]`
        ^^^^^^^^^^^^^^^^^^
  Got Box[T.untyped] originating from:
    editor.rb:9:
     9 |box = Box.new      # missing error here
              ^^^^^^^
Errors: 3
```

#### Expected behavior

Sorbet should report an error on `Box.new` because the type argument hasn't been provided, and as such is inferred to `T.untyped`.

- - -

It might be nice to attempt to infer the type members based on the type parameters passed to the function, but it's not clear how hard that would be, and it's always the sort of thing we could relax in the future. Better to start with an error for the time being.

**Comment by paracycle** [comment]
I think this is a duplicate of https://github.com/sorbet/sorbet/issues/4978, right?

**Comment by jez** [comment]
Yep, it's a dup, thanks for finding.
