### ISSUE TITLE
Sorbet defines private method in non-private scope first, causing it to be seen by another library

### ISSUE THREAD

**Issue by joevgreathead** [sorbet/sorbet#5786]
#### Input

~→ View on sorbet.run~

`some_rails_generator.rb`
```ruby
# typed: strict
# frozen_string_literal: true

require "rails/generators"

class SomeRailsGenerator < Rails::Generators::NamedBase
  extend T::Sig
  source_root File.expand_path("../templates", __FILE__)

  sig { void }
  def do_generation_stuff
    puts "Creating a file here"
  end

  private

  sig { void }
  def a_private_method
    puts "Doing private stuff"
  end
end
```

(Credit to @paracycle for originally deriving the root issue here.)

When using Sorbet method signatures in a Rails generator, powered by Thor, private methods are briefly defined in a public scope and then their scope is redefined while [disabling the `method_added` hooks](https://github.com/sorbet/sorbet/blob/2db8204979c789b262c3a5240e5a86cbd4493229/gems/sorbet-runtime/lib/types/private/class_utils.rb#L76-L109), but other libraries `method_added` hooks can not be disabled. This leads a library like Thor to have its `method_added` hook triggered and result in it seeing the method as a public method initially.

#### Observed output

```
$ rails g some_rails a_name
Creating a file here
Could not find command "a_private_method".
```

#### Expected behavior

```
$ rails g some_rails a_name
Creating a file here
```

#### Additional Information

Rails 7.0.3
Thor 1.2.1
sorbet-static-and-runtime 0.5.9964

##### Workaround

Wrapping the methods in a Thor `no_commands` block resolves this.
```ruby
  private

  no_commands do
    sig { void }
    def a_private_method
      puts "Doing private stuff"
    end
  end
```

Removing method signatures also resolves this.
```ruby
  private

  def a_private_method
    puts "Doing private stuff"
  end
```

**Comment by adaedra** [comment]
Hello,

I was bit by this issue earlier, and investigated in a sorbet only environment.

```ruby
# typed: true

require 'sorbet-runtime'

class MethodSpy
  def self.method_added(m)
    puts "#{self.name} => #{self.protected_instance_methods.inspect}"
  end
end

class UncheckedFoo < MethodSpy
  protected
  def bar
  end
end

class Foo < MethodSpy
  extend T::Sig

  protected
  sig { void }
  def bar
  end
end
```

```
UncheckedFoo => [:bar]
Foo => [:bar]
Foo => []
```

The methods are added back in [gems/sorbet-runtime/lib/types/private/class_utils.rb:99](https://github.com/sorbet/sorbet/blob/eedf4a9cc2841077f763b823733e3c38494eb544/gems/sorbet-runtime/lib/types/private/class_utils.rb#L99) and visibility restored after, and as joevgreathead mentioned, `method_added` callbacks from other ancestors are still being called, meaning those checking on method visibility get the wrong information.

Ruby: `3.1.2p20`
Sorbet: 
```
sorbet (0.5.10032)
sorbet-runtime (0.5.10032)
sorbet-static (0.5.10032)
```
