### ISSUE TITLE
Sorbet sigs are lost when redefining methods with metaprogramming

### ISSUE THREAD

**Issue by mrcasals** [sorbet/sorbet#5824]
#### Input

(I tried reproducing it on Sorbet.run without luck 😞)

```ruby
# This class automatically wraps any public method with some tracing code. It
# ignores private methods and special methods (like `initialize`).
class Base
  def self.inherited(subclass)
    #Inject existing methods with tracing code:
    subclass.instance_methods(false).each do |func|
      inject(subclass, func)
    end

    #Override the singletons method_added to ensure all future methods are injected.
    def subclass.method_added(method_name)
      unless @trace_calls_internal
        @trace_calls_internal = true
        Base.inject(self, method_name) #This will call method_added itself, the condition prevents infinite recursion.
        @trace_calls_internal = false
      end
    end
  end

  def self.inject(subclass, method_name)
    subclass.instance_eval do
      #Get the method
      method_object = instance_method(method_name)

      # Check if it's private
      is_private = subclass.private_instance_methods.include?(method_name)

      if !is_private
        # Wrap the method with whatever code we need
        define_method(method_name) do |*args, &block|
          trace do
            method_object.bind(self).call(*args, &block)
          end
        end
      end
    end
  end

  private

  def trace(&block)
    puts "Class name: #{self.class.name}"
    block.call
  end
end

class Example < Base
  exted T::Sig

  def initialize
    @grub = 1
  end

  sig { void }
  def read(arg)
    puts "Reading..."
  end
end

ex1 = Example.new
ex1.read("Sup")
```

#### Observed output

![image](https://user-images.githubusercontent.com/491891/169797719-5f5d387f-9a51-44e6-a686-979301bac5ee.png)

```
An error occurred while loading ./file.rb.
Failure/Error: Rails.application.eager_load!

RuntimeError:
  You called sig twice without declaring a method in between
```

#### Expected behavior

It loads properly.

- - -

So I tried some metaprogramming, I know these are dangerous waters. The metaprogramming code works fine without sorbet: the idea is to be able to automatically wrap an unknown public method name with some tracing code. This works as expected, but when the inheriting class has Sorbet typings, things get wrong. I'm not sure what's going on, but it looks like the method redeclaration is moved so sigs and method declarations are out of order and Sorbet cannot detect the correct sig for the method. I wanted to explore a bit more but I got lost at Sorbet's codebase.

I tried to reproduce it on Sorbet.run but I couldn't 😞

**Comment by paracycle** [comment]
The problem is because you are not calling `super` from inside your `method_added` hook.

That ends up breaking Sorbet runtime, since Sorbet relies on its _own_ `method_added` being called when a method is defined to match the `sig` to the method that follows it. When you don't call `super` from _your_ `method_added` hook, Sorbet's one doesn't run and you get into these mismatched `sig` problems.

**Comment by mrcasals** [comment]
@paracycle oh, thanks! Calling `super` from my own `method_added` seems to solve that particular issue, but now I'm getting a new kind of error:

```
     RuntimeError:
       The declaration for `call` is missing parameter(s): args, block
```

I've checked around and it _could_ be related to #3939, but I don't know enough about Sorbet internals to be able to provide a solution 😞 Any idea?

**Comment by mrcasals** [comment]
Not sure I can do this, because I can't assume what methods and signatures lower classes will have, but will try to work from there! Thanks a lot! ❤️

**Comment by paracycle** [comment]
> Not sure I can do this, because I can't assume what methods and signatures lower classes will have, but will try to work from there! Thanks a lot! ❤️

You can definitely do this dynamically, as I have done this on another gem before: https://github.com/panorama-ed/memo_wise/pull/253

You just need to instantiate a module inside the `inherited` method and `const_set` it under the `subclass` with a given name and prepend it to `subclass`. The rest of your logic will be the same, except for `inject`, which will `const_get` the module and add your method to that module as before.

**Comment by mrcasals** [comment]
Hi!

Thanks for the code! Apparently, the `method_added` call is missing a call to `super`, so I fixed it this way:

```ruby
    def subclass.method_added(method_name)
      super
      Base.inject(self, method_name)
    end
```

After this is solved, I'm facing another error. I'm getting errors saying `wrong number of arguments (given 1, expected 0)` whenever I run `block.call`. Running tests with RSpec points the error to the line that runs `block.call`, but running the same code via the console points to Sorbet again:

```
ArgumentError: wrong number of arguments (given 1, expected 0)
from /srv/app/vendor/cache/ruby/2.7.0/gems/sorbet-runtime-0.5.6300/lib/types/private/methods/signature.rb:184:in `each_args_value_type'
```

Notice how I'm using an outdated version of Sorbet. My project is huge and we're having problems updating because of the `hidden-definitions` but we want to use https://github.com/Shopify/tapioca at some point.

Can you confirm you're seeing the same error using the same Sorbet version? This would help me understand whether it's a matter of updating Sorbet or there's something else in my code that prevents this from working 😄 

I can kinda solve the problem if I change the `module_eval` call to this:

```ruby
    def self.inject(subclass, method_name)
      return if subclass.private_instance_methods.include?(method_name)
      p method_name

      subclass.const_get("TraceModule").module_eval <<~RUBY
        def #{method_name} # The test class I'm using uses a method without any parameters
          trace do
            super
          end
        end
      RUBY
    end
```

I say "kinda" because now in my tests I see the method being called twice. Here's a gist with the code, the tests and the output: https://gist.github.com/mrcasals/c410d49f04b75486f6b8d37a0e26360d

Any idea what might be going on? Could this also be caused by the outdated Sorbet version?

Thank you so much for the time you're putting helping me, it's really appreciated ❤️
