### ISSUE TITLE
trailing dots style with keyword-y names parse error in Sorbet but not Ruby

### ISSUE THREAD

**Issue by BrianHicks** [sorbet/sorbet#5840]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%3A%3ALoaders%3A%3AAssociationLoader.%0A%20%20for%28%3A%3AConventionsCategory%2C%20%3Apathways%29)

```ruby
::Loaders::AssociationLoader.
  for(::ConventionsCategory, :pathways)
```

#### Observed output

```
editor.rb:2: unexpected token "for" https://srb.help/2001
     2 |  for(::ConventionsCategory, :pathways)
          ^^^

editor.rb:2: unexpected token ")" https://srb.help/2001
     2 |  for(::ConventionsCategory, :pathways)
                                              ^
Errors: 2
```

#### Expected behavior

Ruby accepts this code (and code with other keywords like `and` and `then`) in this style, and I expected Sorbet to, too.

**Comment by jez** [comment]
Thanks. This is an intentional decision to not support this syntax. There is more information at the error code

https://sorbet.org/docs/error-reference#2001

**Comment by BrianHicks** [comment]
ahhhh shoot. I read the first paragraph of that error but not the second. 🤦 Sorry for the noise!

**Comment by BrianHicks** [comment]
FWIW I was able to autocorrect this to leading dots in our codebase with rubocop, but we had 5,433 offenses of trailing dots—we had decided to adopt that specific style because leading dots do not work when pasting code to IRB. In our case, I think type checks are way more important than easy copy-paste, but I'll be looking forward to the potential upstreaming mentioned in #1993.

**Comment by jez** [comment]
Note that recent versions of irb support bracketed paste mode, which means irb will detect when the terminal begins and ends a paste event, ignoring any newlines present inside the pasted text.
