### ISSUE TITLE
Ignore direnv files during `srb init`

### ISSUE THREAD

**Issue by offbyone** [sorbet/sorbet#5910]
### Problem

I use [direnv](https://direnv.net/) to manage my project rubygems. That means that under my project I have a `.direnv/ruby/gems` directory where everything is installed. Running `srb init` seems to be trying to parse and require those:

```
...
/Users/offby1/projects/chicago/wellington/.direnv/ruby/gems/aws-sdk-core-3.122.1/lib/aws-sdk-core/json/handler.rb:69: warning: method redefined; discarding old content_type
/Users/offby1/projects/chicago/wellington/.direnv/ruby/gems/aws-sdk-core-3.131.0/lib/aws-sdk-core/json/handler.rb:69: warning: previous definition of content_type was here
/Users/offby1/projects/chicago/wellington/.direnv/ruby/gems/aws-sdk-core-3.122.1/lib/aws-sdk-core/json/handler.rb:73: warning: method redefined; discarding old target
...
``` 

### Proposed solution

Ignore either a predefined list of known directories when scanning, _or_ ignore all files according to the current git ignore settings.

### Other ideas

Having some kind of CLI flag for this would also be sufficient; as far as I can tell, `srb init` doesn't have any of those (certainly it doesn't have a `--help`, so if there are options to control it, I can't find them).

**Comment by vaporyhumo** [comment]
Hey 👋 This can be done following the next instructions:
> you can start by creating and modifying the config file accordingly and then running the whole process. You can acomplish this by running srb rbi config first, and then adding a line like --ignore=db/ to the newly created file at ./sorbet/config.

> For multiple directories you can put one on each line:
```
--dir
.
--ignore=db/
--ignore=vendor/
```

**Comment by froydnj** [comment]
Thanks @vaporyhumo!

Closing this as the necessary functionality already exists.
