### ISSUE TITLE
Unable to override a method with a T::Array[T::Struct] argument with T::Array[StructSubtype]

### ISSUE THREAD

**Issue by thomasdziedzic** [sorbet/sorbet#6000]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20Base%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.params%28a%3A%20T%3A%3AArray%5BT%3A%3AStruct%5D%29.void%20%7D%0A%20%20def%20foo%28a%29%0A%20%20end%0A%0A%20%20sig%20%7B%20abstract.returns%28T%3A%3AStruct%29%20%7D%0A%20%20def%20bar%0A%20%20end%0Aend%0A%0Aclass%20Foo%20%3C%20Base%0A%20%20class%20A%20%3C%20T%3A%3AStruct%0A%20%20end%0A%0A%20%20sig%20%7B%20override.params%28a%3A%20T%3A%3AArray%5BA%5D%29.void%20%7D%0A%20%20def%20foo%28a%29%0A%20%20end%0A%0A%20%20sig%20%7B%20override.returns%28A%29%20%7D%0A%20%20def%20bar%0A%20%20%20%20A.new%0A%20%20end%0Aend)

```ruby
# typed: strict

class Base
  extend T::Helpers
  extend T::Sig
  abstract!

  sig { abstract.params(a: T::Array[T::Struct]).void }
  def foo(a)
  end

  sig { abstract.returns(T::Struct) }
  def bar
  end
end

class Foo < Base
  class A < T::Struct
  end

  sig { override.params(a: T::Array[A]).void }
  def foo(a)
  end

  sig { override.returns(A) }
  def bar
    A.new
  end
end
```

#### Observed output

```
editor.rb:22: Parameter a of type T::Array[Foo::A] not compatible with type of abstract method Base#foo https://srb.help/5035
    22 |  def foo(a)
          ^^^^^^^^^^
    editor.rb:9: The super method parameter a was declared here with type T::Array[T::Struct]
     9 |  def foo(a)
          ^^^^^^^^^^
Errors: 1
```

#### Expected behavior

I would have expected the override for params a to accept a subtype of T::Struct (`A` in this instance) in the T::Array type parameter.

**Comment by jez** [comment]
This is expected behavior, as documented here

https://sorbet.org/docs/override-checking#a-note-on-variance
