### ISSUE TITLE
Allow tests to assert that the resulting output must typecheck

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#601]
### Problem

Right now, we can only test the result of `srb init` via snapshots of the filesystem. This means we can't assert in a test that `srb init` generated valid RBIs, etc.

Also, the `srb tc` part of Sorbet has a non-trivial amount of logic for finding the `sorbet` executable. It's exercised somewhat indirectly via `srb init` itself (for hidden methods, suggest typed, etc.) but it might be nice to ensure that it also works when invoked directly.

### Proposed solution

We should modify the driver to somehow allow for `srb tc` to be run. It's unclear how best to implement this and what interface to present to the test author.

**Comment by Morriar** [comment]
Fixed by #https://github.com/sorbet/sorbet/pull/3357.

From the [documentation](https://github.com/sorbet/sorbet/tree/master/gems/sorbet#writing-tests):

> By default, the test framework only checks the result of srb init. The test.sh script can be used to change that behavior and list the commands that must be ran in the context of the test.
> 
> For example, to test the behavior of srb init then srb tc, the test.sh script will look like this:
> 
> ```
> #!/bin/bash
> bundle exec "$1" init
> bundle exec "$1" tc
> ```
> Where $1 is the path to srb provided by the test framework.

And this behaviour can be controlled:

> The test framework always expects the test.sh script to finish without error. If you want to check the output of a command expected to fail, you can use bash to control what the script should return:
> 
> 
> ```
> #!/bin/bash
> bundle exec "$1" tc || exit 0 # we expect this command to fail
> ```
