### ISSUE TITLE
LSP server requestMethod property breaks Emacs eglot LSP client

### ISSUE THREAD

**Issue by bradleybuda** [sorbet/sorbet#6125]
### Problem

The Sorbet LSP server includes a JSON property, `"requestMethod"`, in its responses which is not included in the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/). 

Emacs' [eglot](https://github.com/joaotavora/eglot) LSP client crashes when processing these response messages because the underlying JSON-RPC library (which comes from [Emacs itself](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/jsonrpc.el)) is strict about parsing responses.

### Proposed solution

A few options, I'm hoping for guidance from the Sorbet team on the best approach:
* My first instinct was to send a patch removing `"requestMethod"` from Sorbet but from scanning #273 it seems like it is being used by Sorbet itself and/or by some Stripe internal tooling, so I think that "just removing it" is unlikely to be the best approach
* Add a switch to Sorbet to disable this behavior and document it for "strict" clients
* Patch emacs and/or eglot to ignore the attribute - I will open an issue on eglot to start this discussion
* Document a workaround here and/or in eglot - right now I'm using a couple of wrapper scripts to post-process the responses

### Current workaround

(pretty hacky, if you're reading this change to match your own sorbet install)

`lsp-wrapper.sh`:
```bash
#!/usr/bin/env bash
SORBET_DIR=~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sorbet-static-0.5.10233-universal-darwin-21/libexec
$SORBET_DIR/sorbet tc --lsp --disable-watchman --enable-all-experimental-lsp-features | ./strip-responses.rb
```

`strip-responses.rb`
```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true
# typed: true

require 'json'

# Filter JSON-RPC responses to strip bad keys
while (header = $stdin.gets("\r\n\r\n"))
  raise "bug: expeted Content-Length got #{header}" unless header =~ /Content-Length: (\d+)/

  content_length = Regexp.last_match(1).to_i

  body = $stdin.read(content_length)
  doc = JSON.parse(body)
  doc.delete('requestMethod')

  # Prepare output message
  new_body = doc.to_json
  new_content_length = new_body.length

  $stdout.write("Content-Length: #{new_content_length}\r\n\r\n#{new_body}")
  $stdout.flush
end
```

To use lsp-wrapper.sh in Emacs:
```elisp
(use-package! eglot
  :config (add-to-list 'eglot-server-programs '(ruby-mode . ("path/to/lsp-wrapper.sh"))))
```

**Comment by jez** [comment]
Unfortunately Sorbet currently requires this property to deserialize untyped JSON into typed C++ structs. Without this field the various “either/or” types in the LSP spec would not deserialize. The last time I checked, the only time Sorbet deserializes its own responses is in the test harness, so it might be possible to add a command line flag to disable sending this field, but it would mean that there is a nontrivial gap between Sorbet as tested vs Sorbet as released.

The JSON parsing part of sorbet is home grown; if you want to try to change how sorbet deserializes JSON into typed structs to remove this restriction, go ahead.

On the other hand, as far as I understand the spec does not explicitly allow nor disallow sending extra fields (please lmk if I’m wrong), and also many other clients (vscode, nvim-lsp, etc.) work fine with these extra fields, so it’s unclear that this is in fact strictly sorbet’s fault.

**Comment by bradleybuda** [comment]
Agreed that the LSP and JSONRPC specs are silent on extra keys - I don't think sorbet is "out of spec" here (nor am I particularly interested in spec-lawyering). Thanks for the context and info - I will follow up with eglot to see if there's an easy workaround on their end, since AFAICT most other LSP clients are happy with sorbet as a server. Thanks!

**Comment by offbyone** [comment]
Eglot's perspective on this is disappointing, but unsurprising: https://github.com/joaotavora/eglot/discussions/1407#discussioncomment-9694310

**Comment by offbyone** [comment]
After some pointers I have come up with a solution that'll allow eglot to understand the results sent back by Sorbet:

```emacs-lisp
(defvar offby1/jsonrpc-2.0-valid-keys '(:jsonrpc :id :method :params :result :error))

(cl-defmethod jsonrpc-convert-from-endpoint ((_conn eglot-lsp-server) lsp-server-message)
           (cl-loop for (key value) on lsp-server-message by 'cddr
                    when (member key offby1/jsonrpc-2.0-valid-keys)
                    collect key and collect value))
```

This strips out all unrecognized keys from the jsonrpc message, returning only the ones that are supported by the subsequent destructuring read in `jsonrpc-connection-receive`.

**Comment by shannoncole** [comment]
@offbyone thanks for that workaround, works like a charm! (I had to pick up `jsonrpc.el` from latest Emacs Git: the version in Emacs 29.3 doesn't have `jsonrpc-convert-from-endpoint` yet.)
