### ISSUE TITLE
Can't use `T.cast` in memoized variable declarations

### ISSUE THREAD

**Issue by vinistock** [sorbet/sorbet#6145]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns%28Integer%29%20%7D%0A%20%20def%20memoized%0A%20%20%20%20%23%20Can't%20memoize%20because%20T.cast%20is%20not%20accepted%0A%20%20%20%20%40var%20%7C%7C%3D%20T.let%28%0A%20%20%20%20%20%20T.cast%28get_number%2C%20Integer%29%2C%0A%20%20%20%20%20%20T.nilable%28Integer%29%0A%20%20%20%20%29%0A%20%20end%0A%0A%20%20sig%20%7B%20returns%28Integer%29%20%7D%0A%20%20def%20memoized2%0A%20%20%20%20return%20%40var%20if%20%40var%0A%0A%20%20%20%20value%20%3D%20T.cast%28get_number%2C%20Integer%29%0A%20%20%20%20%23%20Unreachable%20because%20we%20return%20early%0A%20%20%20%20%40var%20%7C%7C%3D%20T.let%28%0A%20%20%20%20%20%20value%2C%0A%20%20%20%20%20%20T.nilable%28Integer%29%0A%20%20%20%20%29%0A%20%20end%0A%0A%20%20sig%20%7B%20returns%28T.any%28Integer%2C%20Float%29%29%20%7D%0A%20%20def%20get_number%0A%20%20%20%20123%0A%20%20end%0Aend%0A%0A)

```ruby
# typed: strict

class Foo
  extend T::Sig

  sig { returns(Integer) }
  def memoized
    # Can't memoize because T.cast is not accepted
    @var ||= T.let(
      T.cast(get_number, Integer),
      T.nilable(Integer)
    )
  end

  sig { returns(Integer) }
  def memoized2
    return @var if @var

    value = T.cast(get_number, Integer)
    # Unreachable because we return early
    @var ||= T.let(
      value,
      T.nilable(Integer)
    )
  end

  sig { returns(T.any(Integer, Float)) }
  def get_number
    123
  end
end
```

#### Observed output

```
editor.rb:10: Use T.let to specify the type of instance variables https://srb.help/5013
    10 |      T.cast(get_number, Integer),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:10: Replace with T.let(get_number, Integer)
    10 |      T.cast(get_number, Integer),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Note:
    If you really want to use T.cast, assign to an intermediate variable first and then assign that variable to @var

editor.rb:9: The instance variable @var must be declared inside initialize or declared nilable https://srb.help/5005
     9 |    @var ||= T.let(
            ^^^^

editor.rb:9: Redeclaring variable @var with mismatching type https://srb.help/5006
     9 |    @var ||= T.let(
            ^^^^
    editor.rb:9: Previous declaration is here:
     9 |    @var ||= T.let(
            ^^^^

editor.rb:21: This code is unreachable https://srb.help/7006
    21 |    @var ||= T.let(
            ^^^^
    editor.rb:21: This condition was always falsy (NilClass)
    21 |    @var ||= T.let(
            ^^^^
  Got NilClass originating from:
    editor.rb:9:
     9 |    @var ||= T.let(
            ^^^^
    editor.rb:17:
    17 |    return @var if @var
                           ^^^^
Errors: 4
```

#### Expected behavior

Related: https://github.com/sorbet/sorbet/pull/6081

In this particular example, we need to use `T.cast` to narrow the type of the argument passed to `T.let`, so that it doesn't fail when asserting the type. However, this is considered an error and Sorbet directs the developer to extract the `T.cast` into a variable (`memoize` method in the example).

Trying to extract it to a variable also fails in this memoization context (`memoize2`) because the code is then reported as dead, since the type of the instance variable is not nilable.

Should/can we allow the `T.cast` inside the `T.let`? Maybe only in contexts where memoization is involved?

**Comment by jez** [comment]
```ruby
T.let(T.cast(..., Type1), Type2)
```

is equivalent to

```ruby
T.let(T.unsafe(...), Type2)
```

Can you do that instead? This does not seem like a problem unique to `||=` or instance variables, but rather a misuse of `T.cast` entirely.

**Comment by vinistock** [comment]
We can certainly do it. I'm curious to know, why is this considered a misuse, but setting it to a local variable isn't?

**Comment by jez** [comment]
We could make an error message for this, it's just not implemented.

There is precedent for doing the same thing with `T.cast(..., T.untyped)`:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Ax%20%3D%20T.cast%28x%2C%20T.untyped%29)

```ruby
# typed: strict

x = T.cast(x, T.untyped)
```

#### Observed output

```
editor.rb:3: Please use T.unsafe to cast to T.untyped https://srb.help/7015
     3 |x = T.cast(x, T.untyped)
            ^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:3: Replace with T.unsafe(x)
     3 |x = T.cast(x, T.untyped)
            ^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

**Comment by jez** [comment]
I think that we could change the desugaring to make

```ruby
          @var = begin
            ::Sorbet::Private::Static.keep_for_typechecking(::Integer)
            T.cast(<self>.get_number(), Integer)
          end
```

become

```ruby
          <statTemp>$1 = T.cast(<self>.get_number(), Integer)
          @var = begin
            ::Sorbet::Private::Static.keep_for_typechecking(::Integer)
            <statTemp$1>
          end
```

and then the errors would go away.
