### ISSUE TITLE
Sorbet help URLs are rendered as location URI in the hover popups

### ISSUE THREAD

**Issue by timfjord** [sorbet/sorbet#6219]
I've been using Sorbet LSP with Sublime Text and noticed that for some reasons help URLs(e.g. https://srb.help/7003) from the diagnostic hover popup(and probably in other popups too) aren't opened in the browser.

After debugging I realised that help URLs have the following format `location:sorbet@https://srb.help/7003#0,0` and created [a PR](https://github.com/sublimelsp/LSP/pull/2016) to handle them correctly but was advised to open an issue here as this behaviour doesn't seem correct

#### Observed behaviour

Help URLs format is  `location:sorbet@https://srb.help/7003#0,0`

#### Expected behaviour

Help URLs format should be probably just  `https://srb.help/7003` as all other location info seems redundant

**Comment by froydnj** [comment]
Sorbet only ever provides properly formatted URLs for diagnostics.  If sublimelsp has some debugging facilities for the messages received from the LSP server, you should be able to observe the raw messages and verify that.

It looks like there is some code in sublimelsp that formats messages in a very similar way to what you are seeing:

https://github.com/sublimelsp/LSP/blob/20a1d74ad166212cd7cdb264af164b10192990de/plugin/core/views.py#L863-L868

Presumably something is not handling the `location:sorbet@` prefix correctly elsewhere in the codebase?

**Comment by froydnj** [comment]
(Or something is calling `location_to_href` when it really should be calling something else.)

**Comment by timfjord** [comment]
Ok, thanks. It looks like this requires more debigging, but good to know that Sorbet provides only properly formatted URLs
