### ISSUE TITLE
Could not find sorbet-static-0.5.10382-x86_64-linux in any of the sources

### ISSUE THREAD

**Issue by proton** [sorbet/sorbet#6313]
Looks like https://github.com/sorbet/sorbet/issues/2250 is happening again.

As you can see at https://rubygems.org/gems/sorbet-static/versions,
There has been no sorbet static for darwin since August 18:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/97374/187298360-8dad127c-b8f0-4e2f-b9e0-529a07f52142.png">

**Comment by froydnj** [comment]
This is expected; we took the machine that hosted our Darwin builds offline indefinitely, so we had to turn the Darwin builds off (#6266).  We don't have a firm timeframe on when Darwin builds will be back, though we do have a replacement machine coming "soon".

**Comment by jez** [comment]
This is a known problem: #6266 

There has been a problem with the physical machine we use to test and build macOS binaries. It had to come offline immediately, and I can't give a specific timeframe for when we will start publishing macOS binaries once again.

For updates, please join https://sorbet.org/slack.
