### ISSUE TITLE
Incorrect `Loc` when using `:'...'` symbols in props

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#6314]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%20%3C%20T%3A%3AStruct%0A%20%20prop%20%3A'foo'%2C%20Integer%0Aend%0A%0Aa%20%3D%20A.new%28foo%3A%200%29%0Aa.foo%20%3D%20'')

```ruby
# typed: true

class A < T::Struct
  prop :'foo', Integer
end

a = A.new(foo: 0)
a.foo = ''
```

#### Observed output

```
editor.rb:8: Assigning a value to oo that does not match expected type Integer https://srb.help/7002
     8 |a.foo = ''
                ^^
  Got String("") originating from:
    editor.rb:8:
     8 |a.foo = ''
                ^^
Errors: 1
```

#### Expected behavior

Notice how the error message says "Assigning a value to `oo`". It should say "Assigning a value to `foo`".

In debug builds, there's actually an ENFORCE that fails, but that doesn't happen in prod builds.

- - -

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by jez** [comment]
👋 Hey @sreenath-tm I think that @maruth-stripe had already started working on this the day before you commented. Sorry for the mixup.

If you find another issue you'd like to work on, feel free to ask questions about it in the #internals channel at https://sorbet.org/slack

**Comment by sreenath-tm** [comment]
Hi @jez no issues will keep looking for other issues that I can contribute to. Thanks for replying.

**Comment by maruth-stripe** [comment]
closed by https://github.com/sorbet/sorbet/pull/6341
