### ISSUE TITLE
T.noreturn causes no error as result of another method with different return type

### ISSUE THREAD

**Issue by notEthan** [sorbet/sorbet#6326]
A method (`str` in the below example) which implicitly returns the result of a call to a method which returns `T.noreturn` (`willraise` below) should, I think, find a conflict.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28String%29%20%7D%0Adef%20str%0A%20%20willraise%0Aend%0A%0Asig%20%7B%20returns%28T.noreturn%29%20%7D%0Adef%20willraise%0A%20%20raise%0Aend%0A)

```ruby
# typed: strict

extend T::Sig

sig { returns(String) }
def str
  willraise
end

sig { returns(T.noreturn) }
def willraise
  raise
end

```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

I'd expect either an error about unexpected type, or about the expression always raising (as you get from other uses of noreturn). One or both of:
> Expected String but found T.noreturn for method result type

or

> This expression always raises or can never be computed

This also seems to affect assignment, but only when the assignment is the last expression, e.g. [this example assigning from willraise](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28T.noreturn%29%20%7D%0Adef%20willraise%0A%20%20raise%0Aend%0A%0Aa%20%3D%20willraise%0A) or [this example assigning directly from raise](https://sorbet.run/#%23%20typed%3A%20strict%0A%0A0%20%23%20dummy%20expr%3B%20it%20does%20error%20if%20assignment%20is%20the%20first%20expression%0Aa%20%3D%20raise%0A).

I also see that an error is encountered, as expected, when the method uses [explicit rather than implicit return](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28String%29%20%7D%0Adef%20str%0A%20%20return%20willraise%0Aend%0A%0Asig%20%7B%20returns%28T.noreturn%29%20%7D%0Adef%20willraise%0A%20%20raise%0Aend%0A).

**Comment by jez** [comment]
This is working as intended. It’s totally legal for a method to raise unconditionally, and can be useful to mark methods unimplemented.

(this is how all other languages that have something similar to sorbet’s noreturn type work. For example, a direct translation of the program in the issue description to TypeScript also does not have any errors)

**Comment by notEthan** [comment]
Interesting. Thanks for the clarification. In fact I encountered this on a method intended to be marked as unimplemented, and was surprised by the outcome, but the currently-implemented outcome is actually what I want there and "fixing" would mean I have to work around that. So wontfix suits me fine.
