### ISSUE TITLE
Could not find a valid gem 'sorbet-static' (= 0.5.10456) (required by 'sorbet' (>= 0)) in any repository

### ISSUE THREAD

**Issue by JulienCorb** [sorbet/sorbet#6429]
Trying to install sorbet in a rails project running in Docker (alpine) 

Here is the docker image : 

```
# syntax=docker/dockerfile:1
FROM ruby:2.7.6-alpine

# install libraries to support racc
RUN apk add --no-cache --update build-base

# install libpq in order to install pg gem
RUN apk add libpq-dev

# install libraries to support sorbet
RUN apk add \
  git \
  bash \
  ca-certificates \
  wget
ENV GLIBC_RELEASE_VERSION 2.30-r0
RUN wget -nv -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
  wget -nv https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_RELEASE_VERSION}/glibc-${GLIBC_RELEASE_VERSION}.apk && \
  apk add glibc-${GLIBC_RELEASE_VERSION}.apk && \
  rm /etc/apk/keys/sgerrand.rsa.pub && \
  rm glibc-${GLIBC_RELEASE_VERSION}.apk    

# install libraries to support rails credentials
RUN apk add vim

WORKDIR api
COPY Gemfile /api/Gemfile
COPY Gemfile.lock /api/Gemfile.lock
RUN bundle install


# Add a script to be executed every time the container starts.
COPY docker_entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/docker_entrypoint.sh
ENTRYPOINT ["docker_entrypoint.sh"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]
```

The piece of code dedicated to installing libraries to support sorbet comes from [the official doc's FAQ](https://sorbet.org/docs/faq#what-platforms-does-sorbet-support). 

Trying to run `docker-compose build service` runs forever when trying to resolve dependancies at the `bundle install` step. 
Trying to `docker-compose run --rm service sh` and then `gem install sorbet` returns : 
```
ERROR:  Could not find a valid gem 'sorbet-static' (= 0.5.10456) (required by 'sorbet' (>= 0)) in any repository
ERROR:  Possible alternatives: urban-static, poe_static, bard_static, core-state, bard-static
```

**Comment by Liboul** [comment]
Same issue on macOS Monterey with Apple Silicon chip, in a docker container from with the image `ruby:2.7.6-alpine`
Upgrading `bundler` and `RubyGems` fixed the `could not find a valid gem` issue.

```bash
gem update --system
gem install bundler
```

However, I now face another issue, that the CLI is not available, even though the gem is installed and Bundler finds executables for other gems.
```bash
bundle exec srb
bundler: command not found: srb
Install missing gem executables with `bundle install`
```

The missing executable is probably linked to this warning when installing the gem: `Sorbet is not available publically yet. This gem is only a placeholder.`. However, specifying a version leads to the previous issue: `Could not find a valid gem 'sorbet-static'`. I'm guessing it is a platform issue: The docker container uses the "Ruby" platform, and no gem is published for that platform. Not sure how to move forward, if it is possible at all?

**Comment by fcheung** [comment]
Afaik there is no arm version of sorbet (see https://github.com/sorbet/sorbet/issues/4119 for example)

**Comment by fazo96** [comment]
I am having the same issue on both my computers running linux. Both computers are x86_64 but bundler seems to think that the platform is `ruby`.

Attempting to install sorbet will cause 0.4 to be installed which is just a placeholder gem. Forcing the version to be 0.5 causes this error:

```
Bundler could not find compatible versions for gem "sorbet-static":
  In Gemfile:
    sorbet (~> 0.5) was resolved to 0.5.5175, which depends on
      sorbet-static (= 0.5.5175)

Could not find gem 'sorbet-static (= 0.5.5175)' with platform 'ruby', which is required by gem 'sorbet (~> 0.5)', in any of the sources.

The source contains the following gems matching 'sorbet-static (= 0.5.5175)':
  * sorbet-static-0.5.5175-java
  * sorbet-static-0.5.5175-universal-darwin-14
  * sorbet-static-0.5.5175-universal-darwin-15
  * sorbet-static-0.5.5175-universal-darwin-16
  * sorbet-static-0.5.5175-universal-darwin-17
  * sorbet-static-0.5.5175-universal-darwin-18
  * sorbet-static-0.5.5175-universal-darwin-19
  * sorbet-static-0.5.5175-x86_64-linux
```

The output of `bundle platform` is this:

```
Your platform is: x86_64-linux

Your app has gems that work on these platforms:
* ruby

Your Gemfile specifies a Ruby version requirement:
* ruby 3.1.2p20

Your current platform satisfies the Ruby version requirement.

```

Not sure how to proceed and get sorbet to be installed

**Comment by ggalmazor** [comment]
Same as @fazo96 reported happening here:
```
% bundler
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...........
Could not find gem 'sorbet-static (= 0.5.5175)' with platform 'ruby', which is required by gem 'sorbet (~> 0.5)', in rubygems repository https://rubygems.org/ or installed
locally.

The source contains the following gems matching 'sorbet-static (= 0.5.5175)':
  * sorbet-static-0.5.5175-java
  * sorbet-static-0.5.5175-universal-darwin-14
  * sorbet-static-0.5.5175-universal-darwin-15
  * sorbet-static-0.5.5175-universal-darwin-16
  * sorbet-static-0.5.5175-universal-darwin-17
  * sorbet-static-0.5.5175-universal-darwin-18
  * sorbet-static-0.5.5175-universal-darwin-19
  * sorbet-static-0.5.5175-x86_64-linux
```

```
% bundle platform
Your platform is: arm64-darwin-21

Your app has gems that work on these platforms:
* ruby

Your Gemfile does not specify a Ruby version requirement
```

**Comment by Morriar** [comment]
I _think_ you can add the platform to your Gemfile with `bundle lock --add-platform arm64-darwin`.

**Comment by ggalmazor** [comment]
That worked, @Morriar. Thanks!

**Comment by fazo96** [comment]
The underlying issue wasn't that sorbet doesn't publish a linux/arm64 version for me. I am using a linux x86_64 machine but I still had the same error: `Could not find gem 'sorbet-static (= 0.5.5175)' with platform 'ruby', which is required by gem 'sorbet (~> 0.5)', in rubygems repository https://rubygems.org/ or installed locally.`

I was able to resolve it with these steps:

1. run `bundle lock --add-platform x86_64-linux` BEFORE adding sorbet to the gemfile, otherwise this command will fail with the error above
2. open the `Gemfile.lock` with a text editor and search for `PLATFORMS` then delete the `ruby` line from the list
3. add sorbet to the gemfile and run `bundle install`. Finally, this time it will work

To make the Gemfile work on Mac as well it might be needed to run `bundle lock --add-platform universal-darwin-22` as well but I haven't tested this.

**Comment by schoblaska** [comment]
Possibly related, I noticed that when adding the`x86_64-linux` platform to the lock file, bundler doesn't add a platform-specific line for `sorbet-static`. It adds one for nokogiri, and I already have one for `universal-darwin`, so it seems strange to me that bundler doesn't add a line for sorbet-static / x86 as well.

```bash
$ bundle lock --add-platform x86_64-linux                
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Writing lockfile to...

$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index bf1dbc1..4e0e795 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -145,6 +145,8 @@ GEM
     nio4r (2.7.0)
     nokogiri (1.16.2-arm64-darwin)
       racc (~> 1.4)
+    nokogiri (1.16.2-x86_64-linux)
+      racc (~> 1.4)
     packs (0.0.39)
       code_ownership (>= 1.33.0)
       packs-specification
@@ -292,6 +294,7 @@ GEM
 PLATFORMS
   arm64-darwin-22
   arm64-darwin-23
+  x86_64-linux

 DEPENDENCIES
   debug

$ cat Gemfile.lock | grep sorbet-static
      sorbet-static (= 0.5.11238)
    sorbet-static (0.5.11238-universal-darwin)
    sorbet-static-and-runtime (0.5.11238)
      sorbet-static-and-runtime (>= 0.5.10187)
      sorbet-static-and-runtime (>= 0.5.10820)
```

**Comment by KaanOzkan** [comment]
We also ran into this, sometimes RubyGems index doesn't contain the platform specific version. I think it should be fixed now https://rubygems.org/info/sorbet-static

**Comment by Morriar** [comment]
As https://github.com/sorbet/sorbet/issues/6429#issuecomment-1939190977, this seems fixed now. Feel free to reopen if it's not the case.
