### ISSUE TITLE
Allow accessing properties with a `[]` method in `T::Struct` objects

### ISSUE THREAD

**Issue by ryanseys** [sorbet/sorbet#6441]
### Problem

Would be nice to expose the properties of the `T::Struct` objects through a `def [](prop)` method, similar to how `Hash` and `Struct` do in Ruby.

```rb
MyStruct = Struct.new(:hello, keyword_init: true)
my_struct = MyStruct.new(hello: "world")

# Works with Struct
my_struct[:hello] #=> "world"

class MyTStruct < T::Struct
  const :hello, String
end

my_t_struct = MyTStruct.new(hello: "world")

# Doesn't work with T::Struct :(
my_t_struct[:hello] #=> NoMethodError: undefined method `[]' for <MyTStruct hello="world">:MyTStruct
```
 
### Proposed solution

Implement a `def [](prop)` method so that `my_t_struct[:hello]` returns `"world"`

**Comment by sambostock** [comment]
I think this would mean that [`[]` would have to return a union type of all the possible value types](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20Person%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20const%20%3Aname%2C%20String%0A%20%20const%20%3Aage%2C%20Integer%0A%0A%20%20sig%20%7B%20params%28field%3A%20Symbol%29.returns%28T.any%28String%2C%20Integer%29%29%20%7D%0A%20%20def%20%5B%5D%28field%29%0A%20%20%20%20case%20field%0A%20%20%20%20when%20%3Aname%20then%20name%0A%20%20%20%20when%20%3Aage%20then%20age%0A%20%20%20%20else%20raise%20NameError%2C%20%22no%20member%20'%23%7Bfield%7D'%20in%20struct%22%20%23%20To%20match%20Ruby's%20Struct%0A%20%20%20%20end%0A%20%20end%0Aend) (or `T.untyped`)

```ruby
# typed: strict

class Person < T::Struct
  extend T::Sig
  
  const :name, String
  const :age, Integer

  sig { params(field: Symbol).returns(T.any(String, Integer)) }
  def [](field)
    case field
    when :name then name
    when :age then age
    else raise NameError, "no member '#{field}' in struct" # To match Ruby's Struct
    end
  end
end
```

which would defeat the reason for using a Sorbet `T::Struct` over a Ruby `Struct` or a `Hash` (type safety).

**Comment by ryanseys** [comment]
Okey doke.
