### ISSUE TITLE
"Pure" annotation to support flow-sensitive typing

### ISSUE THREAD

**Issue by DanielHeath** [sorbet/sorbet#6459]
### Problem

When using `attr_reader :foo` to hold a nilable type, flow-sensitive typing can't tell that (eg) `obj.foo.strip! unless obj.foo.nil?` is valid.

### Proposed solution

Mark methods generated by `attr_reader` as Pure.

When a method is marked Pure, flow-sensitive typing can narrow the type until any non-Pure method is called.

For instance:
```
unless obj.foo.nil?
  1 + 1
  obj.foo.strip!
end
```
would be valid, but not
```
unless obj.foo.nil?
  obj.foo.strip!
  obj.foo = "hi"
  obj.foo.strip! # <- #foo= is impure, so `obj.foo` is no longer narrowed
end
```

**Comment by jez** [comment]
I’ve written a little bit about why this is at least hard and maybe not possible without a complete rewrite of the type system here:

https://blog.jez.io/syntactic-control-flow/

going to close as “not planned” for the time being. 

in the mean time, we recommend assigning the intermediate result to a variable

**Comment by DanielHeath** [comment]
I'm familiar with the problem space, and that is a good writeup of it :)

It may well be that the internals of sorbet aren't amenable to it (or that you don't think it's a good fit), but I'd like to clarify to make sure.

I'm not familiar with sorbet specifically, but this approach should work for flow-typing systems in general.

In essence:

Add a `Pure` annotation which can apply to `nullary` call signatures. This is part of the signature, so (eg) subclasses can't be impure.

At each conditional, create an additional "flow control" context.

Instead of lasting to the end of the `if..end` block, this additional context would last until the next operation which is not statically `Pure` typed.

Type constraints discovered via `Pure` calls inside a conditional can be used for type narrowing within the new/additional context.

If I understand correctly, this should mostly re-use the existing infrastructure for flow control contexts.
