### ISSUE TITLE
Hi, I'm curious how Sorbet ended up introducing T.nilable

### ISSUE THREAD

**Issue by jays306** [sorbet/sorbet#6503]
Hello 👋 ,
Just have a question regarding T.nilable for my own curiosity.
I'm wondering how sorbet ended up introducing T.nilable.
I have been using sorbet and feel like T.nilable is actually bringing more complexity to my codes
Especially, all types are objects in Ruby and they can be nil..so I feel like checking nil should be conducted by developers' codes in runtime as other static type programming languages do.
What's the reason behind to introduce T.nilable ?
Thanks for your help!

**Comment by jez** [comment]
Checking for the possibility of `nil` catches many kinds of bugs before they have a chance to cause problems. Hope that helps.
