### ISSUE TITLE
Add support for call hierarchies

### ISSUE THREAD

**Issue by kikeenrique** [sorbet/sorbet#6504]
### Problem

Hi,
I develop in ruby from time to time, and I really miss the possibility to search for a function call hierarchy.
From ignorance, would it be feasible to add support for it?

Reference:
[LSP spec Call Hierarchy #468](https://github.com/Microsoft/language-server-protocol/issues/468)

### Proposed solution

I'm sorry not be able to add any.

**Comment by Morriar** [comment]
👋 Hi @kikeenrique,

I think this issue is a duplicate of https://github.com/sorbet/sorbet/issues/2130.
