### ISSUE TITLE
Files are entered twice when an absolute path is passed on the command-line

### ISSUE THREAD

**Issue by varungandhi-src** [sorbet/sorbet#6536]
When an absolute path is passed to srb, it looks like it can end up entering files twice into the GlobalState, one with the relative path, and one with the absolute path.

You should be able to reproduce by running Sorbet on (e.g.) https://github.com/Shopify/shopify-api-ruby (perhaps the [extra `--dir .` in the `sorbet/config`](https://github.com/Shopify/shopify-api-ruby/blob/main/sorbet/config#L1-L2) is relevant, where paths aren't being de-duplicated across arguments?). Put a print statement in `enterFile` to show the file path of the argument, and pass `$PWD` to Sorbet as the directory to type-check (instead of `.` or not passing anything).

**Comment by froydnj** [comment]
Sorbet automatically reads `sorbet/config` as command-line options.  For `shopify-api-ruby`, this file reads:

```
--dir
.
--ignore=test/rest
```

so you are effectively invoking Sorbet as `sorbet $PWD --dir . --ignore=test/rest`, passing the directory twice and getting duplicate paths.
