### ISSUE TITLE
Calling self within an anonymous class is recognized as parent module/class

### ISSUE THREAD

**Issue by AnotherJoSmith** [sorbet/sorbet#6583]
I'm not sure if this is a duplicate of https://github.com/sorbet/sorbet/issues/1010, since it's very similar but that issue refers to inner modules. I figured I'd open this issue anyways and let you folks decide.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20MyModule%0A%20%20extend%20self%0A%20%20%0A%20%20def%20anonymous_class%0A%20%20%20%20Class.new%20do%0A%20%20%20%20%20%20def%20my_method%0A%20%20%20%20%20%20%20%20self.class.name%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend%0A)

```ruby
# typed: true
extend T::Sig

module MyModule
  extend self
  
  def anonymous_class
    Class.new do
      def my_method
        self.class.name
      end
    end
  end
end

```

#### Observed output

```
editor.rb:10: Method class does not exist on MyModule https://srb.help/7003
    10 |        self.class.name
                     ^^^^^
Errors: 1
```

#### Expected behavior

In this case I wouldn't expect there to be an error, since calling self within a `Class.new do` block returns the anonymous class instance.

This seems to be true when inner classes are defined within classes as well. For example I would expect [an error in this case](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20MyClass%0A%20%0A%20%20def%20self.class_method%3B%20end%0A%0A%20%20def%20self.anonymous_class%0A%20%20%20%20Class.new%20do%0A%20%20%20%20%20%20def%20my_method%0A%20%20%20%20%20%20%20%20self.class.class_method%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend%0A).

**Comment by jez** [comment]
Dupe of #1010
