### ISSUE TITLE
Don't convert untyped type_parameters to Bottom

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#66]
https://sorbet.run/#%23%20typed%3A%20true%0A%0A%0A%5B1%2C2%2C3%5D.zip(unknown).map%20do%20%7Citem%2C%20type%7C%0A%20%20type%0A%20%20the_previous_was_bottom_so_this_is_dead%0Aend%0A%0Adef%20unknown%0Aend

Originally reported by @pt-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1107

**Comment by jez** [comment]
Idk when this changed but this doesn't seem to reproduce anymore.
