### ISSUE TITLE
Sorbet believes an instance variable created in `before` in a MiniTest spec is undeclared

### ISSUE THREAD

**Issue by hxu-stripe** [sorbet/sorbet#6662]
#### Input
This involves a test spec that run on Minitest, and I can't seem to create a sorbet.run for it. 

This is my test code using Minitest:
```ruby
describe "something" do
  before do
    @instance_variable = T.let("foo", String)
  end

  it "is ok here" do
    assert_equal "foo", @instance_variable
  end

  [1,2,3].each do |i|
    it "is not ok in a loop" do
      # this gives an error "Use of undeclared variable `@instance_variable`[6002](http://go/e/6002)"
      assert_equal "foo", @instance_variable  
    end
  end
```

#### Observed output

See my inline comment above

#### Expected behavior

`@instance_variable` does exist, and the test passes when you run it, but the compiler seems to get confused by the loop

**Comment by froydnj** [comment]
We resolved this internally; the problem here is using `each` instead of `test_each`.
