### ISSUE TITLE
Rails: Use of `self` in setting class attributes breaks lambdas referencing `self`

### ISSUE THREAD

**Issue by CodingAnarchy** [sorbet/sorbet#6698]
#### Input

```ruby
class Foo < ActiveRecord
    self.table_name = "foobar"

    before_save do
        self.bar = "test"
    end
end
```

#### Observed output

```
Method `bar=` does not exist on `T.class_of(Foo)`
```

#### Expected behavior

There are no Sorbet identified errors in the `before_save` callback lambda function.

- - -

The error on identifying the class of `self` disappears when the lambda is replaced by a method. In other words, the following passes with no errors:

```ruby
class Foo < ActiveRecord
    self.table_name = "foobar"

    before_save :set_bar
    
    def set_bar
        self.bar = "test"
    end
end
```

**Comment by jez** [comment]
This is a typing error in the `before_save` method, not a bug in Sorbet. Feel free to reach out to members of the Sorbet user community on slack (in the #rails channel) to get help.
