### ISSUE TITLE
LSP: Malformed sig error suppressed on fast path

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#671]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer%2C%20z%3A%20Integer).returns(String)%7D%0A%20%20def%20bar(x%2C%20y%2C%20z)%0A%20%20%20%20x.to_s%0A%20%20end%0Aend%0A)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: Integer, z: Integer).returns(String)}
  def bar(x, y, z)
    x.to_s
  end
end

```

Type a space after entering the above to trigger the fast path, and watch the malformed sig error on `y` disappear.

This bug just bit me while working on a Ruby change; I didn't notice the bug until CI failed.

#### Observed output

No error on `y`.

#### Expected behavior

An error on `y`, as it lacks a type annotation.

**Comment by sushain97** [comment]
@jvilk-stripe is this still an issue? I can't seem to replicate.

**Comment by jvilk-stripe** [comment]
Woo hoo, it's fixed! I'll keep this open so we can land a regression test in the `fast_path` tests.
