### ISSUE TITLE
Code incorrectly marked as unreachable

### ISSUE THREAD

**Issue by paddyobrien** [sorbet/sorbet#6718]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%40bar%20%3D%20T.let%28nil%2C%20T.nilable%28String%29%29%0A%0A%20%20def%20no_setter%0A%20%20%20%20%40bar%20%3D%20nil%0A%20%20%20%20set_bar%28%22test%22%29%0A%20%20%20%20if%20%40bar%0A%20%20%20%20%20%20puts%28%22This%20will%20run!%22%29%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20def%20with_setter%0A%20%20%20%20set_bar%28nil%29%0A%20%20%20%20if%20%40bar%0A%20%20%20%20%20%20puts%28%22This%20will%20run!%22%29%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20def%20set_bar%28b%29%0A%20%20%20%20%40bar%20%3D%20b%0A%20%20end%0Aend%0A)

```ruby
# typed: true
class Foo
  extend T::Sig

  @bar = T.let(nil, T.nilable(String))

  def no_setter
    @bar = nil
    set_bar("test")
    if @bar
      puts("This will run!")
    end
  end

  def with_setter
    set_bar(nil)
    if @bar
      puts("This will run!")
    end
  end

  def set_bar(b)
    @bar = b
  end
end

```

#### Observed output

```
editor.rb:11: This code is unreachable https://srb.help/7006
    11 |      puts("This will run!")
              ^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:10: This condition was always falsy (NilClass)
    10 |    if @bar
               ^^^^
  Got NilClass originating from:
    editor.rb:8:
     8 |    @bar = nil
                   ^^^
Errors: 1
```

#### Expected behavior

Code should not be marked as unreachable. Feels like the bias here should be false negatives not false positives!

- - -

**Comment by jez** [comment]
Dupe of #1374
