### ISSUE TITLE
`requires_ancestor` does not find `before_action` from `ApplicationController` despite tapioca's rbi files.

### ISSUE THREAD

**Issue by dewyze** [sorbet/sorbet#6740]
#### Input

I am not sure if this is a sorbet bug, tapioca bug, or user error, but my best guess was maybe sorbet. Tapioca _seems_ to have generated the correct rbi file, but it does not seem to be working correctly.

In short, I have a rails concern where `requires_ancestor { ApplicationController }` is not finding `before_action`.

[Example Rails App](https://github.com/dewyze/concern_example). You can see the error by running `bundle install` and then `bundle exec srb tc`.

Here is the code ([you can see the file here](https://github.com/dewyze/concern_example/blob/main/app/controllers/concerns/my_concern.rb)).

```ruby
# typed: true

module MyConcern
  extend T::Helpers
  extend T::Sig

  extend ActiveSupport::Concern

  requires_ancestor { ApplicationController }

  included do
    before_action(:do_the_thing)
  end

  def do_the_thing
    request.host
  end
end
```

#### Observed output

```
→ bundle exec srb tc
app/controllers/concerns/my_concern.rb:12: Method before_action does not exist on T.class_of(MyConcern) https://srb.help/7003
    12 |    before_action(:do_the_thing)
            ^^^^^^^^^^^^^
Errors: 1
```

There is no error on `request.host`, with request coming from `ApplicationController`.

I have tried using all of these for `requires_ancestor` and they all fail:

- `T.class_of(ApplicationController)`
- `ActionController::Base`
- `AbstractController::Callbacks`
- `AbstractController::Callbacks::ClassMethods`

#### Expected behavior

From my understanding of `requires_ancestor` this should work? Tapioca has added the following:

- https://github.com/dewyze/concern_example/blob/main/sorbet/rbi/dsl/abstract_controller/callbacks.rbi#L10
- https://github.com/dewyze/concern_example/blob/9bfc16aa0467e801ee1cf502ce8489d94a375456/sorbet/rbi/gems/actionpack%407.0.4.2.rbi#L619-L620

Both of those make me think that it should pick up on this?

If this is more of a tapioca error, I'm happy to re-open the issue there.

**Comment by dewyze** [comment]
This is a failure of tapioca, but has already been discussed here: https://github.com/Shopify/tapioca/issues/1304#issuecomment-1346876172

If I were using `def self.included(other)` it would be easier to address because we have a reference to the class we are being included in, however, with the `included do` helper, that is not the case.

Tapioca could guess at it based on if `requires_ancestor` is in the file, but that is error prone/not guaranteed as there could be more than one.

The solution is `T.bind(self, T.class_of(ApplicatonController)` after the `included` line.

**Comment by pvcresin** [comment]
I was having the same problem with the `before_action` in the `included do` as well. Thank you very much!

```ruby
# before
included do
  before_action(:do_the_thing) # error: `before_action` does not exist
end

# after 1
included(T.bind(self, T.class_of(ApplicationController))) do
  before_action(:do_the_thing) # no error!
end

# after 2
sig { params(base: T.class_of(ApplicationController)).void }
def self.included(base)
  base.before_action(:do_the_thing)
end
```
