### ISSUE TITLE
Segfault when returning a `T.let` inside a memoized block setting an instance variable

### ISSUE THREAD

**Issue by dirceu** [sorbet/sorbet#6766]
This one was hard to title and I don't think I did a great job, but check the example below.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28Integer%29%20%7D%0Adef%20foo%0A%20%20%40bar%20%7C%7C%3D%20begin%0A%20%20%20%20x%20%3D%201%0A%20%20%20%20T.let%28x%2C%20Integer%29%0A%20%20%20%20x%20%23%20comment%20this%20to%20segfault%0A%20%20end%0Aend%0A%0Afoo)

```ruby
# typed: true
extend T::Sig

sig { returns(Integer) }
def foo
  @bar ||= begin
    x = 1
    T.let(x, Integer)
  end
end
```

#### Observed output

This causes a segfault.

#### Expected behavior

This is not standard usage and we recommended against placing T.let where it is in the example (i.e. to either remove it completely if it's not needed, or make it wrap the block instead of being the last statement of the block), but this should still not segfault.

cc @nehagarg-shopify

**Comment by dirceu** [comment]
Extra examples:

```ruby
# this doesn't segfault
sig { returns(Integer) }
def foo
  @bar ||= begin
    x = 1
    x
  end
end

# this doesn't segfault
sig { returns(Integer) }
def foo
  begin
    x = 1
    T.let(x, Integer)
  end
end

# this doesn't segfault
sig { returns(Integer) }
def foo
  @bar ||= begin
    x = 1
    T.let(x, Integer)
    x
  end
end

# this segfaults 💥
sig { returns(Integer) }
def foo
  @bar ||= begin
    x = 1
    T.let(1, Integer)
  end
end

# this segfaults 💥
sig { returns(Integer) }
def foo
  @bar ||= begin
    x = 1
    T.let(x, Integer)
  end
end
```

**Comment by jez** [comment]
Thank you for the small report.
