### ISSUE TITLE
Sorbet modifies original Method#parameters method reflections

### ISSUE THREAD

**Issue by Kache** [sorbet/sorbet#6767]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Arequire%20'sorbet-runtime'%0A%0Aextend%20T%3A%3ASig%0A%0Aclass%20Ret%20%3C%20T%3A%3AStruct%0A%20%20const%20%3Aval%2C%20String%0A%20%20const%20%3Amethod_%2C%20Symbol%0A%20%20const%20%3Abinding_%2C%20Binding%0Aend%0A%0Asig%20%7B%20params%28x%3A%20Integer%2C%20y%3A%20Integer%29.returns%28Ret%29%20%7D%0Adef%20foo_sig%28x%2C%20y%29%0A%20%20Ret.new%28val%3A%20x.to_s%20%2B%20y.to_s%2C%20method_%3A%20T.must%28__method__%29%2C%20binding_%3A%20binding%29%0Aend%0A%0Adef%20foo%28x%2C%20y%29%0A%20%20Ret.new%28val%3A%20x.to_s%20%2B%20y.to_s%2C%20method_%3A%20T.must%28__method__%29%2C%20binding_%3A%20binding%29%0Aend%0A%0Aret_sig%20%3D%20foo_sig%282%2C%205%29%0Aret%20%3D%20foo%282%2C%205%29%0A%0Ap%20ret_sig.val%20%3D%3D%20ret.val%20%23%20true%0Ap%20ret.binding_.local_variables%20%3D%3D%20ret.binding_.local_variables%20%23%20true%0A%0A%23%20false%2C%20but%20should%20be%20true%0Ap%20method%28ret_sig.method_%29.parameters%20%3D%3D%20method%28ret.method_%29.parameters%0A%0A%23%20Output%3A%0A%23%20%20%20true%0A%23%20%20%20true%0A%23%20%20%20false%0A%23%20%20%20%5B%5B%3Areq%2C%20%3Aarg0%5D%2C%20%5B%3Areq%2C%20%3Aarg1%5D%2C%20%5B%3Ablock%2C%20%3Ablk%5D%5D%0A%23%20%20%20%5B%5B%3Areq%2C%20%3Ax%5D%2C%20%5B%3Areq%2C%20%3Ay%5D%5D%0A)

```ruby
# typed: true

require 'sorbet-runtime'

extend T::Sig

class Ret < T::Struct
  const :val, String
  const :method_, Symbol
  const :binding_, Binding
end

sig { params(x: Integer, y: Integer).returns(Ret) }
def foo_sig(x, y)
  Ret.new(val: x.to_s + y.to_s, method_: T.must(__method__), binding_: binding)
end

def foo(x, y)
  Ret.new(val: x.to_s + y.to_s, method_: T.must(__method__), binding_: binding)
end

ret_sig = foo_sig(2, 5)
ret = foo(2, 5)

p ret_sig.val == ret.val # true
p ret.binding_.local_variables == ret.binding_.local_variables # true

# false, but should be true
p method(ret_sig.method_).parameters == method(ret.method_).parameters

# Output:
#   true
#   true
#   false
#   [[:req, :arg0], [:req, :arg1], [:block, :blk]]
#   [[:req, :x], [:req, :y]]

```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

Expected `method(method_name).parameters` to be the same in the example above, but it gets modified by Sorbet.

- - -

**Comment by jez** [comment]
This is expected, because `sig` wraps the method in a new method with runtime signature checking.

If you wish to access the original method, you'll want to use `T::Utils.signature_for_method` to get the original parameters.

```ruby
signature = T::Utils.signature_for_method(method(ret_sig.method_))
p signature.parameters == method(ret.method_).parameters         # => true
p signature.method.parameters == method(ret.method_).parameters  # => also true
```
