### ISSUE TITLE
T.type_parameters cannot handle optional argument with nil default ?

### ISSUE THREAD

**Issue by okhwaja** [sorbet/sorbet#6782]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3AU%2C%20%3AV%29%0A%20%20%20%20.params%28%0A%20%20%20%20%20%20default%3A%20T.type_parameter%28%3AU%29%2C%0A%20%20%20%20%20%20blk%3A%20T.proc.returns%28T.type_parameter%28%3AV%29%29%2C%0A%20%20%20%20%29%0A%20%20%20%20.returns%28T.any%28T.type_parameter%28%3AU%29%2C%20T.type_parameter%28%3AV%29%29%29%0Aend%0Adef%20safely%28default%3A%20nil%2C%20%26blk%29%0A%20%20blk.call%0Arescue%20%3D%3E%20e%0A%20%20default%0Aend)

```ruby
# typed: strict
extend T::Sig

sig do
  type_parameters(:U, :V)
    .params(
      default: T.type_parameter(:U),
      blk: T.proc.returns(T.type_parameter(:V)),
    )
    .returns(T.any(T.type_parameter(:U), T.type_parameter(:V)))
end
def safely(default: nil, &blk)
  blk.call
rescue
  default
end
```

#### Observed output

```
editor.rb:12: Argument does not have asserted type T.type_parameter(:U) (of Object#safely) https://srb.help/7007
    12 |def safely(default: nil, &blk)
                            ^^^
  Got NilClass originating from:
    editor.rb:12:
    12 |def safely(default: nil, &blk)
                            ^^^

editor.rb:16: Expected T.any(T.type_parameter(:U) (of Object#safely), T.type_parameter(:V) (of Object#safely)) but found T.nilable(T.any(T.type_parameter(:U) (of Object#safely), T.type_parameter(:V) (of Object#safely))) for method result type https://srb.help/7005
    16 |end
        ^^^
  Expected T.any(T.type_parameter(:U) (of Object#safely), T.type_parameter(:V) (of Object#safely)) for result type of method safely:
    editor.rb:12:
    12 |def safely(default: nil, &blk)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(T.any(T.type_parameter(:U) (of Object#safely), T.type_parameter(:V) (of Object#safely))) originating from:
    editor.rb:12:
    12 |def safely(default: nil, &blk)
                   ^^^^^^^^
    editor.rb:12:
    12 |def safely(default: nil, &blk)
                            ^^^
    editor.rb:13:
    13 |  blk.call
          ^^^^^^^^
    editor.rb:12: Possibly uninitialized (NilClass) in:
    12 |def safely(default: nil, &blk)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

The expected return type is either default or the result of `blk`

```
safely(default: 10) { "asdf" } # --> T.any(Integer, String)
safely { "asdf" }  # --> T.nilable(String)
```

**Comment by jez** [comment]
This is not a bug: Sorbet is correctly flagging that the function might return `nil` if the block raises an exception. 

https://sorbet.run/ace/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters(%3AU%2C%20%3AV)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20default%3A%20T.nilable(T.type_parameter(%3AU))%2C%0A%20%20%20%20%20%20blk%3A%20T.proc.returns(T.type_parameter(%3AV))%2C%0A%20%20%20%20)%0A%20%20%20%20.returns(T.nilable(T.any(T.type_parameter(%3AU)%2C%20T.type_parameter(%3AV))))%0Aend%0Adef%20safely(default%3A%20nil%2C%20%26blk)%0A%20%20blk.call%0Arescue%20%3D%3E%20e%0A%20%20default%0Aend

**Comment by okhwaja** [comment]
thanks for the quick response @jez !

pardon my ignorance, for this method definition
```
def safely(default: nil, &blk)
  blk.call
rescue
  default
end
```

i would expect the following types
```
safely(default: 10) { "asdf" } # --> T.any(Integer, String)
safely { "asdf" }  # --> T.nilable(String)
```

however your recommendation returns
```
T.reveal_type(safely(default: 10) { "asdf" }) # --> T.nilable(T.any(Integer, String)) [UNEXPECTED]
T.reveal_type(safely { "asdf" })) # --> T.nilable(String) [EXPECTED]
```

https://sorbet.run/ace/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters(%3AU%2C%20%3AV)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20default%3A%20T.nilable(T.type_parameter(%3AU))%2C%0A%20%20%20%20%20%20blk%3A%20T.proc.returns(T.type_parameter(%3AV))%2C%0A%20%20%20%20)%0A%20%20%20%20.returns(T.nilable(T.any(T.type_parameter(%3AU)%2C%20T.type_parameter(%3AV))))%0Aend%0Adef%20safely(default%3A%20nil%2C%20%26blk)%0A%20%20blk.call%0Arescue%20%3D%3E%20e%0A%20%20default%0Aend%0A%0A%0AT.reveal_type(safely(default%3A%2010)%20%7B%20%22asdf%22%20%7D)%0AT.reveal_type(safely%20%7B%20%22asdf%22%20%7D)

am i missing something? 🤔
