### ISSUE TITLE
 Fix erroneous error about generics in returns

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#68]
Unsupported use of bare type:

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20AbstractContent%0Aend%0A%0Aclass%20ContentLoader%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Model%20%3D%20type_template(fixed%3A%20AbstractContent)%0A%0A%20%20sig.returns(T%3A%3AArray%5BModel%5D)%0A%20%20def%20load_all_entries%0A%20%20%20%20%5B%5D%0A%20%20end%0Aend

Comments:
28/Aug/18 12:32 AM;pt;currently blocking master rollout without an untyping

17/Oct/18 8:58 PM;tarrh;quick bump on this, I have a similar use-case and hitting the same issue

/redacted/

Originally reported by @pt-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1100.

**Comment by val-stripe** [comment]
I also hit this bug and would like to be notified on update.

**Comment by jez** [comment]
Hey guys I think this might have been magically fixed. Feel free to check.

**Comment by jez** [comment]
This appears to be fixed now. Idk when it was fixed.

**Comment by elliottt** [comment]
After some bisecting, it looks like this was fixed in #1730.
