### ISSUE TITLE
Limited support for overloaded signatures, only with or without a block?

### ISSUE THREAD

**Issue by bdewater** [sorbet/sorbet#6803]
### Problem

I'm aware of https://sorbet.org/docs/error-reference#5040, I looked at how Sorbet currently handles overloads ([here if I'm not mistaken](https://github.com/sorbet/sorbet/blob/36ad4d8679af03eb453635bb5742b113b68215a7/core/types/calls.cc#L329-L330)) and I can see why it's not something the team would want to commit to in it's current form. This is about a common Ruby idiom that feels different than the example given in the docs and might be simpler to allow, so I figured it was worth opening an issue and see what the team thinks.

I've recently run into a few cases where it would've been nice to have two signatures, one for where a block is given and one where that is not the case.

[**Active Record find**](https://api.rubyonrails.org/v7.0/classes/ActiveRecord/FinderMethods.html#method-i-find)
Commonly used as `Post.find(1)` but also accepts an array of IDs, which is why Tapioca generates `T.untyped` return values by default. Despite [documentation](https://github.com/Shopify/tapioca/blob/5a913bc44e00c97fb5f0e81a27c819a899f4a1b3/manual/compiler_activerecordrelations.md?plain=1#L53-L61) this confuses newcomers with some regularity as evidenced by the Sorbet slack questions.

[**ActiveRecord::Batches**](https://api.rubyonrails.org/v7.0/classes/ActiveRecord/Batches.html)
Methods `find_each`, `find_in_batches` and `each_batch` look like [`Array#each`](https://github.com/sorbet/sorbet/blob/36ad4d8679af03eb453635bb5742b113b68215a7/rbi/core/array.rbi#L1165-L1189), but without overloaded signatures need typing with nilable.

```ruby
sig { params(start: T.untyped, finish: T.untyped, batch_size: Integer, error_on_ignore: T.untyped, order: Symbol, block: T.nilable(T.proc.params(object: ::Post).void)).returns(T.nilable(T::Enumerator[::Post])) }
def find_each(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, order: :asc, &block); end
```

Could look like:
```ruby
sig { params(start: T.untyped, finish: T.untyped, batch_size: Integer, error_on_ignore: T.untyped, order: Symbol).returns(T::Enumerator[::Post]) }
sig { params(start: T.untyped, finish: T.untyped, batch_size: Integer, error_on_ignore: T.untyped, order: Symbol, block: T.proc.params(object: ::Post).void).void }
def find_each(start: nil, finish: nil, batch_size: 1000, error_on_ignore: nil, order: :asc, &block); end
```

Signatures for this caused some confusion over at https://github.com/Shopify/tapioca/pull/1417

**ActiveSupport delegated methods**
In a few places Rails has a class that includes Enumerable, but delegates `each` and some other objects to an instance variable that contains the actual data in an array. A couple of examples:
- [ActiveModel::Errors](https://github.com/rails/rails/blob/7c70791470fc517deb7c640bead9f1b47efb5539/activemodel/lib/active_model/errors.rb#L67-L78)
- ActiveRecord::Relation includes [ActiveRecord::Delegation](https://github.com/rails/rails/blob/7c70791470fc517deb7c640bead9f1b47efb5539/activerecord/lib/active_record/relation/delegation.rb#L88-L91) 

This has caused some confusion on our team in cases like these:
```ruby
Post.where(author: "Bart").each do |post|
  # post is untyped
end
```
Using `map` gets typing for free (but is doing needless work) and sometimes using `T.let` is forgotten. With upstream refactoring it could be typed like stdlib `Array#each`.

### Proposed solution

Allow overloaded signatures for `# typed: strict` and up, instead of `# typed: __STDLIB_INTERNAL`, under the following conditions:
- the arguments must be exactly the same, except
- the block argument is specified, or not (so more than 2 sigs would be an error)
- the return types can be different

**Comment by jez** [comment]
I'm still not sure how to support this in source files.

I could _maybe_ see relaxing the constraint on overloads in RBI files. But Sorbet's inference algorithm is not set up to type check the body of a method under two signatures.

**Comment by paracycle** [comment]
Yeah, I think where this would be super helpful is in RBI files for methods that are not defined in the application (since I know that sometimes folks put sigs for application methods in RBI files).

I realize that type-checking methods with bodies with multiple signatures is hard for Sorbet, but pure-interface method definitions having multiple signatures would really help properly type many of the Rails/Active Record constructs more faithfully.

**Comment by amomchilov** [comment]
Here's another example usecase, that appears impossible to type correctly today:

`StatS.distribution`, which forwards to https://rubydoc.info/gems/statsd-instrument/3.5.10/StatsD/Instrument/Client#distribution-instance_method

```ruby
module Statsd
  Tags = T.type_alias { T.any(
    T::Hash[Symbol, String],
    T::Array[String],
  ) }
  
  class << self
    sig do # Overload 1, measure latency of the given block
      type_parameters(:Result)
        .params(
          name: String,
          value: NilClass,
          sample_rate: T.nilable(Float),
          tags: T.nilable(Tags),
          block: T.nilable(T.proc.returns(T.type_parameter(:Result))),
        )
        .returns(T.type_parameter(:Result))
    end
    sig do # Overload 2, provide a value directly
      params(
        name: String,
        value: Numeric,
        sample_rate: T.nilable(Float),
        tags: T.nilable(Tags),
        block: NilClass,
      ).void
    end
    def distribution(name, value = nil, sample_rate: nil, tags: nil, &block); 
  end
end
```

The only workaround I can think of is to define two strongly-typed methods of our own (e.g. `MyStatsD.latency_distribution`, `MyStatsD.distribution`), each with their own sig, which both internally forward on to `StatsD.distribution`
