### ISSUE TITLE
Sporadic `Date#-` type errors: `expected numeric`

### ISSUE THREAD

**Issue by CodingAnarchy** [sorbet/sorbet#6830]
#### Input

In the context of a Rails application (7.0.4.2):

```ruby
sig { params(other_date: Date).returns(Integer) }
def foo(other_date:)
   (Date.current - other_date).to_i
end
```

#### Observed output

Normally runs fine, but sporadically produces `TypeError: expected numeric`. It seems that `sorbet-runtime` occasionally expects the wrong signature for `Date#-`.  `srb tc` shows no errors (as expected). This does not appear to be reproducible deterministically in the console (at least as far as my investigation goes).

#### Expected behavior

No errors on subtracting one `Date` object from another.

**Comment by CodingAnarchy** [comment]
It appears that this error was introduced somewhere when we update to `sorbet-runtime => 0.5.10705` from `0.5.10685`, if that helps confirm or narrow it down at all.

**Comment by jez** [comment]
@CodingAnarchy nothing changed between sorbet-runtime in those versions.

It's likely that you have a bug in your codebase. Sometimes, sporadic type errors can happen when you are using `GC.compact` (or using it indirectly, via some gem) along with other C extension gems that misbehave.

Good luck—these kinds of bugs are hard to track down.
