### ISSUE TITLE
Error assigning bound proc to ivar

### ISSUE THREAD

**Issue by dduugg** [sorbet/sorbet#6843]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20C%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams%28blk%3A%20T.proc.bind%28String%29.void%29.void%20%7D%0A%20%20def%20initialize%28%26blk%29%0A%20%20%20%20%40blk%20%3D%20blk%0A%20%20end%0Aend%0A)

```ruby
# typed: true

class C
  extend T::Sig

  sig {params(blk: T.proc.bind(String).void).void }
  def initialize(&blk)
    @blk = blk
  end
end

```

#### Observed output

```
editor.rb:6: Using bind is not permitted here https://srb.help/5004
     6 |  sig {params(blk: T.proc.bind(String).void).void }
                           ^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

No errors

- - -

A potential workaround is to use `instance_variable_set`:

```ruby
# typed: true

class C
  extend T::Sig

  sig {params(blk: T.proc.bind(String).void).void }
  def initialize(&blk)
    instance_variable_set(:@blk, blk)
  end
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20C%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams%28blk%3A%20T.proc.bind%28String%29.void%29.void%20%7D%0A%20%20def%20initialize%28%26blk%29%0A%20%20%20%20instance_variable_set%28%3A%40blk%2C%20blk%29%0A%20%20end%0Aend%0A)

**Comment by dduugg** [comment]
It's been brought to my attention that this limitation is in the `T.bind` section of the [docs](https://sorbet.org/docs/procs#casting-the-self-type-with-tbind), and silly me only looked at the `T.proc.bind` section in depth. Perhaps the error message could be improved though? Sorbet is normally very good at this, I was surprised to get a message that merely read "not permitted".

**Comment by jez** [comment]
#6848 has more discussion of the eventual solution, and the proper tags.
