### ISSUE TITLE
Sorbet QuickCheck?

### ISSUE THREAD

**Issue by skatenerd** [sorbet/sorbet#6873]
I was wondering if anyone had thought about adding a [QuickCheck](https://en.wikipedia.org/wiki/QuickCheck) type of library on top of Sorbet (or as part of Sorbet).

Now that we have type signatures for Ruby, I'm wondering if it's possible to perform property-based testing:

- Inspect the signature of a given method
- Generate lots of data to match this signature
- Run the method against all of the data
  - In each run, make sure a given rule/property is never violated

Does this seem like a big lift?  I guess the first step would be, examining a given instance/method and programmatically generating the inputs that it would expect to see.

**Comment by jez** [comment]
Feel free to implement something like this as a library. This would not live in Sorbet itself.

**Comment by jez** [comment]
You may wish to chat with other Sorbet users about this on the Sorbet Slack instance: 
https://sorbet.org/slack
