### ISSUE TITLE
Sorbet releases not publishing to rubygems.org

### ISSUE THREAD

**Issue by mgomes** [sorbet/sorbet#6929]
#### Input

Visit https://rubygems.org/gems/sorbet and look at the last published version.

#### Observed output

The last published version is `0.5.10767` from April 11.

#### Expected behavior

I would expect to see version `0.5.10771` which was [published a few minutes ago](https://github.com/sorbet/sorbet/releases).

**Comment by jez** [comment]
Sorry. rubygems.org has repeatedly timed out during our attempt to publish gems, which has complicated our gem publishing pipeline as we attempt to work around the problems on rubygems.org's end.

I have landed two changes which should make this pipeline more reliable:

- #6907
- #6931

and manually re-run the nightly publish job
