### ISSUE TITLE
Could not find gem 'sorbet-static' with platforms 'aarch64-linux',

### ISSUE THREAD

**Issue by Nealsoni00** [sorbet/sorbet#6985]
#### Input

Sorbet Version being fetched: `sorbet 0.5.10805`
Using Docker Desktop: v20.10.22
ARM Mac: Apple M1 Pro running 13.2.1 (22D68)

#### Observed output

```sh
Could not find gem 'sorbet-static' with platforms 'aarch64-linux',
'arm64-darwin-21', 'arm64-darwin-22', 'x86_64-linux' in rubygems repository
https://rubygems.org/ or installed locally.

The source contains the following gems matching 'sorbet-static':
```

#### Expected behavior

Is there a version of Sorbet running on ARM Linux?

**Comment by jez** [comment]
Dupe of #4119
