### ISSUE TITLE
Enumerator is defined as generic but can't be built

### ISSUE THREAD

**Issue by gmalette** [sorbet/sorbet#7]
`::Enumerator` is [defined as a `T::Generic`](https://github.com/stripe/sorbet/blob/c0c74e0900bdef06a5a08049d727ca874c5520cf/rbi/core/enumerator.rbi#L5-L6), so it requires parameterization; one cannot do

```ruby
sig { returns(Enumerator) }
```

However, the `::Enumerator` does not have a `self.[](type)` method, and it does not have a `T::Enumerator` sibling.

Most other generics from the stdlib have a `T::*` sibling to allow defining their type. `Enumerator` probably would need one too (it feels kind of alone right now).

**Comment by jez** [comment]
This was fixed in #915
