### ISSUE TITLE
`requires_ancestor { Class }` stopped working

### ISSUE THREAD

**Issue by Slike9** [sorbet/sorbet#7010]
#### Input

[→ View on sorbet.run](https://sorbet.run/?arg=--enable-experimental-requires-ancestor#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20ClassMethod%0A%20%20extend%20T%3A%3AHelpers%0A%20%20requires_ancestor%20%7B%20Class%20%7D%0Aend%0A)

```ruby
# typed: true
extend T::Sig

module ClassMethod
  extend T::Helpers
  requires_ancestor { Class }
end
```

#### Observed output

```
editor.rb:4: ClassMethod can't require generic ancestor Class (unsupported) https://srb.help/5065
     4 |module ClassMethod
        ^^^^^^^^^^^^^^^^^^
    editor.rb:6: Class is required by ClassMethod here
     6 |  requires_ancestor { Class }
                              ^^^^^
Errors: 1
```

#### Expected behavior

```
No errors!
```

It worked in sorbet 0.5.10804.

- - -

**Comment by jez** [comment]
I can't reproduce this if I edit the sorbet.run to pass the `--enable-experimental-requires-ancestor` flag:

https://sorbet.run/?arg=--enable-experimental-requires-ancestor#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns%28A%29%20%7D%0A%20%20def%20self.create%0A%20%20%20%20new%0A%20%20end%0Aend%0A%0Amodule%20ClassMethods%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20requires_ancestor%20%7B%20T.class_of%28A%29%20%7D%0A%0A%20%20sig%20%7B%20returns%28A%29%20%7D%0A%20%20def%20build%0A%20%20%20%20create%0A%20%20end%0Aend

**Comment by jez** [comment]
sorry, commented on the wrong issue

**Comment by jez** [comment]
This is likely just something we'll have to accept as a limitation of requires_ancestor. It's experimental, which means other non-experimental features take precedence.

You can usually work around this by writing `T.class_of(BasicObject)` or `T.class_of(Object)` instead of `Class`.
