### ISSUE TITLE
abstract! raises ArgumentError exception in sorbet-runtime >= 0.5.10810

### ISSUE THREAD

**Issue by catlee** [sorbet/sorbet#7017]
#### Input

With sorbet-runtime 0.5.10805 this code runs without errors. There are no errors indicated in sorbet.run.

```ruby
# typed: strict
# frozen_string_literal: true

require 'sorbet-runtime'

module M
  class A
    extend(T::Sig)
    extend(T::Helpers)

    abstract!

    @method = T.let(nil, T.nilable(Symbol))

    class << self
      extend(T::Sig)

      sig { returns(T.nilable(Symbol)) }
      attr_reader :method
    end
  end

  class B < A
    extend(T::Sig)
    extend(T::Helpers)
    abstract!
  end
end
```

#### Observed output

Starting with sorbet-runtime 0.5.10810 the code fails with the error 

```
bundle exec ruby test.rb
/home/catlee/.gem/ruby/3.2.2/gems/sorbet-runtime-0.5.10810/lib/types/private/methods/signature.rb:187:in `each_args_value_type': wrong number of arguments (given 1, expected 0) (ArgumentError)

      raise ArgumentError.new("wrong number of arguments (given #{args_length}, expected #{expected_str})")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /home/catlee/.gem/ruby/3.2.2/gems/sorbet-runtime-0.5.10810/lib/types/private/methods/call_validation.rb:201:in `validate_call'
        from /home/catlee/.gem/ruby/3.2.2/gems/sorbet-runtime-0.5.10810/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
        from /home/catlee/.gem/ruby/3.2.2/gems/sorbet-runtime-0.5.10810/lib/types/private/abstract/declare.rb:30:in `declare_abstract'
        from /home/catlee/.gem/ruby/3.2.2/gems/sorbet-runtime-0.5.10810/lib/types/helpers.rb:21:in `abstract!'
        from test.rb:26:in `<class:B>'
        from test.rb:23:in `<module:M>'
        from test.rb:6:in `<main>'
```

#### Expected behavior

This code should run without error. Or at least the error should indicate what I'm doing wrong.

- - -

I think the problem stems from the `attr_reader :method` line. If I rename this to something else, it works fine.

**Comment by jez** [comment]
You should probably not override methods like this which are defined in the Ruby core libraries. In this case, by defining a method called `method`, you override `Object#method` defined by the Ruby VM, which sorbet-runtime needs to call.

I can put up a PR that works around this, but I would urge you to rewrite your code to not override methods like this. sorbet-runtime is not tested against all the ways people could incompatibly override functionality from the Ruby standard library.

**Comment by catlee** [comment]
> You should probably not override methods like this which are defined in the Ruby core libraries. In this case, by defining a method called `method`, you override `Object#method` defined by the Ruby VM, which sorbet-runtime needs to call.
> 
> I can put up a PR that works around this, but I would urge you to rewrite your code to not override methods like this. sorbet-runtime is not tested against all the ways people could incompatibly override functionality from the Ruby standard library.

Yes, 100% agreed. This code has no need to override the builtin Ruby method!
