### ISSUE TITLE
Typecheck regression in 0.5.10837 when using mixes_in_class_methods

### ISSUE THREAD

**Issue by bannable** [sorbet/sorbet#7038]
#### Input

Note: The example does not currently fail on sorbet.run, but does when run with versions 0.5.10837 and higher.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Arequire%20'sorbet-runtime'%0A%0Amodule%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20include%20Kernel%0A%0A%20%20abstract!%0A%0A%20%20module%20ClassMethods%0A%20%20%20%20extend%20T%3A%3ASig%0A%20%20%20%20extend%20T%3A%3AHelpers%0A%0A%20%20%20%20interface!%0A%0A%20%20%20%20sig%20%7B%20abstract.returns%28T%3A%3ABoolean%29%20%7D%0A%20%20%20%20def%20bar%3B%20end%0A%20%20end%0A%0A%20%20mixes_in_class_methods%28ClassMethods%29%0A%0A%20%20sig%28%3Afinal%29%20%7B%20returns%28T%3A%3ABoolean%29%20%7D%0A%20%20def%20bar%0A%20%20%20%20self.class.bar%0A%20%20end%0Aend%0A%0Aclass%20Bar%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20include%20Foo%0A%20%20%0A%20%20sig%20%7B%20override.returns%28T%3A%3ABoolean%29%20%7D%0A%20%20def%20self.bar%0A%20%20%20%20false%0A%20%20end%0Aend%0A%0Aputs%20Bar.bar%0Aputs%20Bar.new.bar)

```ruby
# typed: strict

require 'sorbet-runtime'

module Foo
  extend T::Sig
  extend T::Helpers

  include Kernel

  abstract!

  module ClassMethods
    extend T::Sig
    extend T::Helpers

    interface!

    sig { abstract.returns(T::Boolean) }
    def bar; end
  end

  mixes_in_class_methods(ClassMethods)

  sig(:final) { returns(T::Boolean) }
  def bar
    self.class.bar
  end
end

class Bar
  extend T::Sig

  include Foo
  
  sig { override.returns(T::Boolean) }
  def self.bar
    false
  end
end

puts Bar.bar
puts Bar.new.bar
```

#### Observed output

```
$ bundle exec srb --version
Sorbet typechecker 0.5.10837 git a7cdaa9c196ff1c8284a19ce7781a9d9c2ff37ea debug_symbols=true clean=0
$ bundle exec srb tc --no-config foo.rb
foo.rb:27: Method bar does not exist on T::Class[Foo] https://srb.help/7003
    27 |    self.class.bar
                       ^^^
  Got T::Class[Foo] originating from:
    foo.rb:27:
    27 |    self.class.bar
            ^^^^^^^^^^
Errors: 1
```

Runtime output has no error:
```
$ bundle exec ruby foo.rb
false
false
$
```

#### Expected behavior

Typechecker should not error. Runtime behavior is correct.

```
$ bundle exec srb tc --no-config foo.rb
No errors! Great job.
$ bundle exec srb --version
Sorbet typechecker 0.5.10826 git 50d2db06b2edfc8e852a428976b1e19d54627588 debug_symbols=true clean=0
$

**Comment by jez** [comment]
@bannable we reverted that commit, which is why sorbet.run has no errors. The change was #7030.

The revert commit landed this morning, and will be published to rubygems later this evening (in a few hours).

Note that this code only typechecked before #7030 (and after the revert of #7030) because `self.class` was marked as returning untyped:

https://sorbet.run/#%23%20typed%3A%20strict%0A%0Arequire%20'sorbet-runtime'%0A%0Amodule%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Kernel%0A%0A%20%20sig%20%7B%20returns%28T%3A%3ABoolean%29%20%7D%0A%20%20def%20bar%0A%20%20%20%20self.class.does_not_exist%0A%20%20end%0Aend

In the future, we reserve the right to change Sorbet's RBI definitions to return something that is not `T.untyped`, which would then require that existing code either fix any type errors or use `T.unsafe` to silence them.

**Comment by bannable** [comment]
> @bannable we reverted that commit, which is why sorbet.run has no errors. The change was #7030.
> 
> The revert commit landed this morning, and will be published to rubygems later this evening (in a few hours).
> 
> Note that this code only typechecked before #7030 (and after the revert of #7030) because `self.class` was marked as returning untyped:
> 
> https://sorbet.run/#%23%20typed%3A%20strict%0A%0Arequire%20'sorbet-runtime'%0A%0Amodule%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Kernel%0A%0A%20%20sig%20%7B%20returns%28T%3A%3ABoolean%29%20%7D%0A%20%20def%20bar%0A%20%20%20%20self.class.does_not_exist%0A%20%20end%0Aend
> 
> In the future, we reserve the right to change Sorbet's RBI definitions to return something that is not `T.untyped`, which would then require that existing code either fix any type errors or use `T.unsafe` to silence them.

I hadn't realized the `.class` call was untyped, that's eye-opening. Thanks!
