### ISSUE TITLE
Hashes don't always dedup keys

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#71]
https://sorbet.run/#class%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20do%0A%20%20%20%20%23%20should%20this%20be%20an%20error%3F%0A%20%20%20%20params(arg%3A%20%7Btest%3A%20Integer%2C%20test%3A%20Integer%7D).void%0A%20%20end%0A%20%20def%20my_fun(arg)%0A%20%20end%0A%20%20%0A%20%20sig%20do%0A%20%20%20%20%23%20should%20this%20be%20an%20error%3F%0A%20%20%20%20params(arg%3A%20%7Btest%3A%20Integer%2C%20test%3A%20String%7D).void%0A%20%20end%0A%20%20def%20my_fun2(arg)%0A%20%20end%0A%20%20%0A%20%20def%20run%0A%20%20%20%20my_fun(%7Btest%3A%201%7D)%20%23%20weird%20error%0A%20%20%20%20my_fun(%7Btest%3A%201%2C%20test%3A%202%7D)%20%23%20no%20error%20%3F%0A%20%20%20%20my_fun2(%7Btest%3A%201%2C%20test%3A%20%22foo%22%7D)%20%23%20error%0A%20%20end%0Aend

**Comment by jez** [comment]
Fixed in #3345
