### ISSUE TITLE
RBI shims are ignored for runtime type checking

### ISSUE THREAD

**Issue by DougEdey** [sorbet/sorbet#7116]
#### Input

Note; I can't do this on sorbet.run because from what I can see we need two files

`demo_class.rb`

```ruby
# typed: true
# frozen_string_literal: true

class DemoClass
  extend T::Sig

  def external_method_call
    internal_method_call(val: "String")
  end

  # Uncomment this to make runtime type checking work correctly
  # sig { params(val: Integer).void }
  def internal_method_call(val:)
    puts T.reveal_type(val)
  end
end
```

`sorbet/rbi/shims/demo_class.rbi`
```ruby
# typed: true

class DemoClass
  sig { params(val: Integer).void }
  def internal_method_call(val:); end
end
```

#### Observed output

```ruby
> DemoClass.external_method_call
String
```

#### Expected behavior

I would expect the RBIs to be used for runtime type checking, there's no mention that this isn't true in Sorbet or Tapioca docs (that a few of us have looked for)

If I put the signature in the class itself, then it does find it and error correctly

This is important for us because we're using Tapioca to generate RBIs for methods and they aren't performing runtime type checks

```ruby
/Users/dougedey/.rvm/gems/ruby-3.0.6/gems/sorbet-runtime-0.5.10801/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'val': Expected type Integer, got type String with value "String" (TypeError)
```

**Comment by exterm** [comment]
IMO it would be really valuable to have runtime type checks use RBIs.

Sorbet's inability to infer types across methods means the impact of any type sig on the application through static checking is very localized. Runtime type checking can expand that impact over potentially the whole call stack.

So, using RBIs in runtime type checks would significantly increase the value provided by type sigs, especially in code bases where type signatures are uncommon enough that typed calls don't often follow other typed calls on the call stack.

I'm actually surprised that's not already the case. I wonder if we could just evaluate RBI files as ruby code, thus adding sigs at run time. There's probably a blocker for that with some of the features preventing redefinition of methods and reopening of classes though...

**Comment by jez** [comment]
Thanks for reaching out. It's intentional that RBI files have no runtime impact. To enable runtime checks, the sigs must live in Ruby files, not RBI files.

**Comment by DougEdey** [comment]
> Thanks for reaching out. It's intentional that RBI files have no runtime impact. To enable runtime checks, the sigs must live in Ruby files, not RBI files.

Can I ask why?

**Comment by exterm** [comment]
Seriously though, I'm curious why "It's intentional that RBI files have no runtime impact".
