### ISSUE TITLE
Instance variable is not declared when using `attr_writer` without a return

### ISSUE THREAD

**Issue by ipc103** [sorbet/sorbet#7140]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20Dog%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params%28owner_name%3A%20String%29.void%20%7D%0A%20%20attr_writer%20%3Aowner_name%0Aend)

```ruby
# typed: strict

class Dog
  extend T::Sig

  sig { params(owner_name: String).void }
  attr_writer :owner_name
end
```

#### Observed output

```
editor.rb:7: The instance variable @owner_name must be declared using T.let when specifying # typed: strict https://srb.help/7043
     7 |  attr_writer :owner_name
                       ^^^^^^^^^^
Errors: 1
```

#### Expected behavior

An ivar `@owner_name` should be declared with the `T.nilable(String)` type. 

- - -

Note: the instance variable is declared based on the return type of the method. The following code compiles in strict mode without issue:

```ruby
# typed: strict

class Dog
  extend T::Sig

  sig { params(owner_name: String).returns(T.nilable(String)) }
  attr_writer :owner_name
end
```

However - this doesn't feel quite correct, since the `owner_name=` method technically can't return `nil`. In practice, I think it makes more sense to treat the `attr_writer` as a void method, and set the type of the instance variable to be a nilable of the param type.

❤️ Thanks for looking into this! Please let me know if I can help provide additional context.

**Comment by jez** [comment]
I don't think we can implement this given how Sorbet works currently. Consider this example:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams%28foo%3A%20Integer%29.returns%28Integer%29%7D%0A%20%20attr_writer%20%3Afoo%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%20T.let%280%2C%20Integer%29%0A%20%20end%0Aend)

```ruby
# typed: strict

class A
  extend T::Sig

  sig {params(foo: Integer).returns(Integer)}
  attr_writer :foo

  sig {void}
  def initialize
    @foo = T.let(0, Integer)
  end
end
```

When Sorbet sees the `attr_writer` call, it has to make a decision whether to declare the `@foo` instance variable, and with what type.

Under your proposal, Sorbet should see the `attr_writer` and decide that `@foo` should be initialized as `T.nilable(Integer)`. But then that conflicts and prevents a user from defining a custom constructor that gives `@foo` a more narrow type, like in this `initialize` method that declares `@foo` as `Integer`.

Unfortunately, Sorbet has to make the decision of whether and what type to declare `@foo` with from looking only at the call to `attr_writer`.

**Comment by ipc103** [comment]
Ah, that makes sense. Thanks for the explanation and the fast followup!
