### ISSUE TITLE
Sorbet Crashed: T::Enum with enum = new(nil) 

### ISSUE THREAD

**Issue by danhuynhdev** [sorbet/sorbet#7190]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Test%20%3C%20T%3A%3AEnum%0A%20%20enums%20do%0A%20%20%20%20A%20%3D%20new%28'a'%29%0A%20%20%20%20B%20%3D%20new%28nil%29%0A%20%20end%0Aend)

```ruby
# typed: true

class Test < T::Enum
  enums do
    A = new('a')
    B = new(nil)
  end
end
```

#### Observed output
Sorbet crash with backtrace
```
Exception::raise(): TypePtr::underlying called on non-proxy-type `ClassType`

Backtrace:
  #3 0xc3c623 sorbet::core::TypePtr::underlying()
  #4 0xb46a2f sorbet::rewriter::(anonymous namespace)::collectNewStats()
  #5 0xb45bef sorbet::rewriter::TEnum::run()
  #6 0xb3aa61 sorbet::ast::TreeMapper<>::mapIt()
  #7 0xb3a5d3 sorbet::ast::TreeMapper<>::mapIt()
  #8 0xb3a5d3 sorbet::ast::TreeMapper<>::mapIt()
  #9 0xb39e64 sorbet::rewriter::Rewriter::run()
  #10 0x7a8279 sorbet::realmain::pipeline::indexOne()
  #11 0x7b9427 std::__1::__function::__func<>::operator()()
  #12 0xca9977 std::__1::__function::__func<>::operator()()
  #13 0xca927b std::__1::__function::__func<>::operator()()
  #14 0xca9c3b Joinable::trampoline()
  #15 0x7f0f9b30a609 start_thread
  #16 0x7f0f9b229133 __clone
```

#### Expected behavior

Type check run normally.

- - -

**Comment by danhuynhdev** [comment]
This seems like a regression introduced in this PR #7149, particularly this line https://github.com/sorbet/sorbet/blame/40a70d0acb9f5f5435808e12098693a129add54f/rewriter/TEnum.cc#L139. 

Calling `underlying()` on `nil` is forbidden I guess 🤔

**Comment by jez** [comment]
Thanks for reporting, we should have a fix up shortly.
