### ISSUE TITLE
New: RubyMine Sorbet LSP Plugin

### ISSUE THREAD

**Issue by simoleone** [sorbet/sorbet#7197]
RubyMine/IntelliJ finally support LSP as of the `2023.2` release last week! I created the [RubyMine Sorbet LSP Plugin](https://plugins.jetbrains.com/plugin/22388-sorbet-lsp) which is backed by `srb tc --lsp` under the hood and uses this integration to power Sorbet suggestions and corrections.

I wasn't sure where to put this, but I wanted to make it more discoverable since I think it will be quite useful to many people. Went with a freeform "feedback" issue comment 😄 . Maybe it's something that could go in the README or documentation alongside VSCode. If so let me know and I can make a pull request to update those.

**Comment by jez** [comment]
Hey Simo,

Feel free to send a PR to add this to the community tab of sorbet.org.

https://sorbet.org/en/community
