### ISSUE TITLE
Odd behaviour with `Array#sum` with custom classes

### ISSUE THREAD

**Issue by ghiculescu** [sorbet/sorbet#7204]
#### Input

I am trying to get sorbet to play nicely with the https://github.com/Shopify/money gem. I think there could be issues in both places, but I'm a bit confused by what I'm seeing so wanted to get some more eyes on it...

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Money%0Aend%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20returns%20T%3A%3AArray%5BMoney%5D%20%7D%0A%20%20def%20returns_money_array%0A%20%20%20%20%5BMoney.new%2C%20Money.new%5D%0A%20%20end%0A%0A%20%20sig%20%7B%20returns%20T%3A%3AArray%5BNumeric%5D%20%7D%0A%20%20def%20returns_numeric_array%0A%20%20%20%20%5B1.0%2C%202%5D%0A%20%20end%0Aend%0A%0AT.reveal_type%20A.new.returns_money_array%0AT.reveal_type%20A.new.returns_money_array.sum%0AT.reveal_type%28%5BMoney.new%2C%20Money.new%5D.sum%29%0A%0AT.reveal_type%20A.new.returns_numeric_array%0AT.reveal_type%20A.new.returns_numeric_array.sum%0AT.reveal_type%28%5B1.0%2C%202%5D.sum%29)

```ruby
# typed: true

class Money
end

class A
  extend T::Sig
  sig { returns T::Array[Money] }
  def returns_money_array
    [Money.new, Money.new]
  end

  sig { returns T::Array[Numeric] }
  def returns_numeric_array
    [1.0, 2]
  end
end

T.reveal_type A.new.returns_money_array
T.reveal_type A.new.returns_money_array.sum
T.reveal_type([Money.new, Money.new].sum)

# These all behave as expected.
T.reveal_type A.new.returns_numeric_array
T.reveal_type A.new.returns_numeric_array.sum
T.reveal_type([1.0, 2].sum)
```

#### Observed output

```
editor.rb:19: Revealed type: T::Array[Money] https://srb.help/7014
    19 |T.reveal_type A.new.returns_money_array
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T::Array[Money] originating from:
    editor.rb:19:
    19 |T.reveal_type A.new.returns_money_array
                      ^^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:20: Revealed type: T.any(Integer, Money) https://srb.help/7014
    20 |T.reveal_type A.new.returns_money_array.sum
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.any(Integer, Money) originating from:
    editor.rb:20:
    20 |T.reveal_type A.new.returns_money_array.sum
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:21: Revealed type: Money https://srb.help/7014
    21 |T.reveal_type([Money.new, Money.new].sum)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got Money originating from:
    editor.rb:21:
    21 |T.reveal_type([Money.new, Money.new].sum)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:23: Revealed type: T::Array[Numeric] https://srb.help/7014
    23 |T.reveal_type A.new.returns_numeric_array
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T::Array[Numeric] originating from:
    editor.rb:23:
    23 |T.reveal_type A.new.returns_numeric_array
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:24: Revealed type: Numeric https://srb.help/7014
    24 |T.reveal_type A.new.returns_numeric_array.sum
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got Numeric originating from:
    editor.rb:24:
    24 |T.reveal_type A.new.returns_numeric_array.sum
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:25: Revealed type: T.any(Integer, Float) https://srb.help/7014
    25 |T.reveal_type([1.0, 2].sum)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.any(Integer, Float) originating from:
    editor.rb:25:
    25 |T.reveal_type([1.0, 2].sum)
                      ^^^^^^^^^^^^
Errors: 6
```

#### Expected behavior

I'm pretty confused about both of the types revealed on the money types.

- `A.new.returns_money_array.sum` -> where does the `T.any(Integer` part come from?
- `[Money.new, Money.new].sum` -> this correctly reveals `Money` as the return type, but I don't know how it knows this from the type information in the script.
- I would expect both of those to reveal the same type, because Sorbet should know that `A.new.returns_money_array` is the same type as `[Money.new, Money.new]`. Right?

- - -

**Comment by ghiculescu** [comment]
https://github.com/sorbet/sorbet/blob/40e80809801788f12d3d8c36592dc3308ef4767b/rbi/core/array.rbi#L2923-L2924

**Comment by ghiculescu** [comment]
But that doesn't explain why this doesn't happen for the `Numeric` examples? :/

**Comment by Morriar** [comment]
`T.any(Integer, Numeric)` is collapsed into `Numeric` since `Integer` is a subtype of `Numeric`:

```rb
x = T.let(42, T.any(Integer, Numeric))
T.reveal_type(x) # Numeric
```

[sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%20T.let%2842%2C%20T.any%28Integer%2C%20Numeric%29%29%0AT.reveal_type%28x%29%20%23%20Numeric)

**Comment by ghiculescu** [comment]
Ahh yep that makes sense. Out of curiosity @Morriar does this mean Shopify codebase has heaps of `T::Cast(Foo.all.sum(&:column_that_is_money_type), Money)`?

**Comment by Morriar** [comment]
We indeed cast it when we need to pass it to something that only accepts `Money`. But in most cases we'll rely on flow typing:

```rb
raise SomeError unless input.is_a?(Money)

# here `input` is a `Money`
call_something_that_takes_money(input)
```

**Comment by ghiculescu** [comment]
@paracycle not a Sorbet issue, but that seems to be unreliable unless you're also verifying the contents of the array. See  https://gist.github.com/ghiculescu/ee099513bb11f44ba8f30b5b879eb86c

I'm not sure if that's a `money` bug or a Ruby bug or intended behaviour, but if the latter then it suggests the sig is wrong (to be fair, summing an array and providing a different type as the initial value is not a good idea).
