### ISSUE TITLE
Dynamically defining a class with a `call` method affects unrelated code

### ISSUE THREAD

**Issue by stephenbinns** [sorbet/sorbet#7271]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0A%23%20can%20be%20extending%20any%20type%20here%0AClass.new%28Object%29%20do%0A%20%20def%20call%3B%20end%0Aend%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20params%28%0A%20%20%20%20%20%20block%3A%20T.nilable%28T.proc.params%28object%3A%20T%3A%3AArray%5B%3A%3AFoo%5D%29.void%29%0A%20%20%20%20%29.void%0A%20%20end%0A%20%20def%20method_with_bound_block%28%26block%29%3B%20%20end%0Aend%0A%0Afoo%20%3D%20Foo.new%0Afoo.method_with_bound_block%20do%20%7Cf%7C%0A%20%20puts%20f%0Aend)

```ruby
# typed: true

# can be extending any type here
Class.new(Object) do
  def call; end
end

class Foo
  extend T::Sig

  sig do
    params(
      block: T.nilable(T.proc.params(object: T::Array[::Foo]).void)
    ).void
  end
  def method_with_bound_block(&block);  end
end

foo = Foo.new
foo.method_with_bound_block do |f|
  puts f
end
```

#### Observed output

```
editor.rb:20: This code is unreachable https://srb.help/7006
    20 |foo.method_with_bound_block do |f|
                                        ^
    editor.rb:20: This expression always raises or can never be computed
    20 |foo.method_with_bound_block do |f|
    21 |  puts f
    22 |end
Errors: 1
```

#### Expected behavior

Defining a class in this way seems to change the behaviour of any subsequent calls to methods which use bound blocks to incorrectly flag the block parameters as unreachable.

Without the class being defined the block parameter isn't marked as unreachable as expected. A typical use case of this functionality is in a spec - for example:

```ruby
  describe "for a coach handler" do
    let(:app) do
      Coach::Handler.new(
        Class.new(Coach::Middleware) do
          def call
            [200, {}, []]
          end
        end,
      )
    end
```

Ideally we should either support this use case or be able to flag where the unsupported defines originate from, it can be very difficult to find these in a large codebase.

**Comment by froydnj** [comment]
This is a dup of #3609 (see also #6568 and #6448).
