### ISSUE TITLE
Support for definition structure using extensions

### ISSUE THREAD

**Issue by vanyauhalin** [sorbet/sorbet#7404]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%20%3C%20T%3A%3AStruct%3B%20end%0Aclass%20A%3B%20const%20%3Ac%2C%20String%3B%20end%0Aclass%20A%3B%20%40d%20%3D%20new%28c%3A%20%22%22%29%3B%20end%0A%0Aclass%20B%20%3C%20T%3A%3AStruct%3B%20const%20%3Ac%2C%20String%3B%20end%0Aclass%20B%3B%20%40d%20%3D%20new%28c%3A%20%22%22%29%3B%20end)

```ruby
# typed: true
extend T::Sig

class A < T::Struct; end
class A; const :c, String; end
class A; @d = new(c: ""); end

class B < T::Struct; const :c, String; end
class B; @d = new(c: ""); end
```

#### Observed output

```
editor.rb:6: Too many arguments provided for method A#initialize. Expected: 0, got: 1 https://srb.help/7004
     6 |class A; @d = new(c: ""); end
                          ^^^^^
    editor.rb:4: initialize defined here
     4 |class A < T::Struct; end
        ^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use -a to autocorrect
    editor.rb:6: Delete
     6 |class A; @d = new(c: ""); end
                          ^^^^^
Errors: 1
```

- - -

Not sure if it's a bug or a limitation of Sorbet.

**Comment by froydnj** [comment]
This is a (deliberate) limitation of Sorbet; making this work would require fundamental changes in how Sorbet processes code and as such is very unlikely to happen.
