### ISSUE TITLE
Hardcoded secret: API Key

### ISSUE THREAD

**Issue by HenryFBP** [sorbet/sorbet#7506]
Hey Sorbet folks, looks like there's an API key in this source code. Discovered this while doing research on open-source vulnerabilities. Is this a valid credential? If so, it should be rotated. I'm guessing not, but I wanted to create this issue just in case.

https://github.com/sorbet/sorbet/blob/b1ec9d25f5668efc598933ad8715ec5f2909f4d8/website/siteConfig.js#L189

**Comment by jez** [comment]
This is expected; Algolia DocSearch requires and expects this key to be served to every page that embeds the Algolia search box.
