### ISSUE TITLE
Method arguments in anonymous class with super class are not respected

### ISSUE THREAD

**Issue by st0012** [sorbet/sorbet#7603]
If an anonymous class with a super class redefines a super method with different number of arguments, Sorbet still uses the super method's parameters count for type-checking. This happens on constructor method, instance methods, and class methods.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20def%20initialize%28a%29%0A%20%20end%0A%0A%20%20def%20self.bar%28a%29%3B%20end%0Aend%0A%0Ar%20%3D%20Class.new%28Foo%29%20do%0A%20%20def%20initialize%28a%2C%20b%29%0A%20%20end%0A%0A%20%20def%20self.bar%28a%2C%20b%29%3B%20end%0Aend%0A%0Ar.new%281%2C%202%29%0Ar.bar%281%2C%202%29%0A)

```ruby
# typed: true

class Foo
  def initialize(a)
  end

  def self.bar(a); end
end

r = Class.new(Foo) do
  def initialize(a, b)
  end

  def self.bar(a, b); end
end

r.new(1, 2)
r.bar(1, 2)

```

#### Observed output

```
editor.rb:17: Too many arguments provided for method Foo#initialize. Expected: 1, got: 2 https://srb.help/7004
    17 |r.new(1, 2)
                 ^
    editor.rb:4: initialize defined here
     4 |  def initialize(a)
          ^^^^^^^^^^^^^^^^^
  Autocorrect: Use -a to autocorrect
    editor.rb:17: Delete
    17 |r.new(1, 2)
               ^^^

editor.rb:18: Too many arguments provided for method Foo.bar. Expected: 1, got: 2 https://srb.help/7004
    18 |r.bar(1, 2)
                 ^
    editor.rb:7: bar defined here
     7 |  def self.bar(a); end
          ^^^^^^^^^^^^^^^
  Autocorrect: Use -a to autocorrect
    editor.rb:18: Delete
    18 |r.bar(1, 2)
               ^^^
Errors: 2
```

#### Expected behavior

There should be no `Too many arguments provided for method` errors.

- - -

**Comment by froydnj** [comment]
This works if you assign `Class.new`'s result to a constant name: [sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20def%20initialize%28a%29%0A%20%20end%0A%0A%20%20def%20self.bar%28a%29%3B%20end%0Aend%0A%0AR%20%3D%20Class.new%28Foo%29%20do%0A%20%20def%20initialize%28a%2C%20b%29%0A%20%20end%0A%0A%20%20def%20self.bar%28a%2C%20b%29%3B%20end%0Aend%0A%0AR.new%281%2C%202%29%0AR.bar%281%2C%202%29%0A)

See also #6568 and various linked issues.  I doubt we are ever going to support anonymous classes in their full generality.

**Comment by st0012** [comment]
I see, thanks for the context. 
I just want to mention that needing to assign it to a constant greatly limits anonymous classes' use case as we often do it exactly to avoid creating another constant (e.g. [for test cases](https://github.com/Shopify/ruby-lsp/blob/main/test/requests/code_lens_expectations_test.rb#L155)) 😅
