### ISSUE TITLE
Missing unreachable code error for puts after return

### ISSUE THREAD

**Issue by azdavis-stripe** [sorbet/sorbet#761]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0Asig%20%7B%20returns(Integer)%20%7D%0Adef%20foo%0A%20%20return%203%0A%20%20puts%0Aend%0A)

```ruby
# typed: true
extend T::Sig
sig { returns(Integer) }
def foo
  return 3
  puts
end
```

#### Observed output

No errors.

#### Expected behavior

Unreachable code error on the `puts`.

**Comment by marianosimone** [comment]
I think this is an even more general problem: any code after `return` does not get checked at all.

```
# typed: true
extend T::Sig
sig { returns(Integer) }
def foo
  return 3
  bar # does not complain about this
end
```
