### ISSUE TITLE
`require_relative` causes Duplicate type member Elem 4011 errors

### ISSUE THREAD

**Issue by abitrolly** [sorbet/sorbet#7636]
#### Input

https://sorbet.run doesn't support multi-file examples.

**`lib/lib.rb`**
```ruby
# frozen_string_literal: true

class Foo
  Bar = Struct.new(:x)
end
```

**`lib/baz.rb`**
```ruby
# frozen_string_literal: true

require_relative 'foo'
```

**`lib/qux.rb`**
```ruby
# frozen_string_literal: true

require_relative 'foo'
```

#### Observed output

```sh
$ srb t lib/foo.rb lib/baz.rb lib/qux.rb
./lib/foo.rb:4: Duplicate type member Elem https://srb.help/4011
     4 |  Bar = Struct.new(:x)
          ^^^^^^^^^^^^^^^^^^^^
    lib/foo.rb:4: Also defined here
     4 |  Bar = Struct.new(:x)
          ^^^^^^^^^^^^^^^^^^^^

./lib/foo.rb:4: Duplicate type member Elem https://srb.help/4011
     4 |  Bar = Struct.new(:x)
          ^^^^^^^^^^^^^^^^^^^^
    lib/foo.rb:4: Also defined here
     4 |  Bar = Struct.new(:x)
          ^^^^^^^^^^^^^^^^^^^^

lib/foo.rb:4: Duplicate type member Elem https://srb.help/4011
     4 |  Bar = Struct.new(:x)
          ^^^^^^^^^^^^^^^^^^^^
    ./lib/foo.rb:4: Also defined here
     4 |  Bar = Struct.new(:x)
          ^^^^^^^^^^^^^^^^^^^^

lib/foo.rb:4: Duplicate type member Elem https://srb.help/4011
     4 |  Bar = Struct.new(:x)
          ^^^^^^^^^^^^^^^^^^^^
    ./lib/foo.rb:4: Also defined here
     4 |  Bar = Struct.new(:x)
          ^^^^^^^^^^^^^^^^^^^^
Errors: 4
```

#### Expected behavior

No errors.

- - -

Encountered in the wild in GitLab code https://gitlab.com/gitlab-org/quality/triage-ops/-/merge_requests/2638#note_1747072604

**Comment by jez** [comment]
I cannot reproduce this—I think there are likely more files in your project locally which are being included in your example. Note that by default `srb t` will read the `sorbet/config` file in the current directory, which might include more files or folders in the snippet. Consider using the `--no-config` flag to `srb t` when crafting your test case, or ensure that the `sorbet/config` file does not have unwanted options in it.

Also, Sorbet does not even aware of the string `require_relative` in any C++ file—it completely ignores all `require` and `require_relative` calls, so I think that it can't possibly be the case that a reproducer for the issue you're seeing locally involves `require_relative`:

https://github.com/search?q=repo%3Asorbet%2Fsorbet+require_relative+language%3AC%2B%2B+&type=code

If you manage to reproduce the issue, feel free to open another issue.

**Comment by splattael** [comment]
Thanks @jez :bow: 

I've created https://gitlab.com/splattael/sorbet-repro to reproduce this issue.

Does this reproduction works for you as well? :thinking:

**Comment by froydnj** [comment]
> Note that by default srb t will read the sorbet/config file in the current directory, which might include more files or folders in the snippet. Consider using the --no-config flag to srb t when crafting your test case, or ensure that the sorbet/config file does not have unwanted options in it.

From https://gitlab.com/splattael/sorbet-repro/-/blob/main/sorbet/config?ref_type=heads :

```
--dir
.
```

From the repro instructions:

```
srb tc lib/
```

So you're telling sorbet to find files in `.` and files in `lib/`.  (Sorbet will not deduplicate files.)

@splattael What happens if you run a bare `srb` (letting the config specify the directory to typecheck) or `srb --no-config lib/`?

**Comment by splattael** [comment]
@froydnj 

> So you're telling sorbet to find files in . and files in lib/. (Sorbet will not deduplicate files.)

Running bare `srb tc` works fine :+1: but it's still surprising (from UX perspective) that `srb tc lib` gives errors. Especially as a newcomer to the tool set.
