### ISSUE TITLE
T.self_type not working as a block parameter

### ISSUE THREAD

**Issue by reu** [sorbet/sorbet#7680]
#### Input

Trying to figure out if this is indeed a bug on Sorbet or this is just not supported at all. It seems impossible to type the following method:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%23%20To%20report%20an%20issue%2C%20click%20%22Examples%20%E2%98%B0%20%3E%20Create%20issue%20with%20example%22%0A%0Aclass%20%3A%3AObject%0A%20%20%20%20extend%20T%3A%3ASig%0A%0A%20%20%20%20sig%20do%0A%20%20%20%20%20%20%20%20type_parameters%28%3AU%29%0A%20%20%20%20%20%20%20%20%20%20%20%20.params%28blk%3A%20T.proc.params%28self%3A%20T.self_type%29.returns%28T.type_parameter%28%3AU%29%29%29%0A%20%20%20%20%20%20%20%20%20%20%20%20.returns%28T.nilable%28T.type_parameter%28%3AU%29%29%29%0A%20%20%20%20end%0A%20%20%20%20def%20and_then%28%26blk%29%0A%20%20%20%20%20%20blk.call%28self%29%20unless%20nil%3F%0A%20%20%20%20end%0Aend)

```ruby
# typed: strict
# To report an issue, click "Examples ☰ > Create issue with example"

class ::Object
  extend T::Sig

  sig do
    type_parameters(:U)
      .params(blk: T.proc.params(self: T.self_type).returns(T.type_parameter(:U)))
      .returns(T.nilable(T.type_parameter(:U)))
  end
  def and_then(&blk)
    blk.call(self) unless nil?
  end
end
```

#### Observed output

```
editor.rb:12: Expression does not have a fully-defined type (Did you reference another class's type members?) https://srb.help/7011
    12 |    def and_then(&blk)
                          ^^^
  Note:
    Historically, users seeing this error has represented finding a bug in Sorbet
    (or at least finding a test case for which there could be a better error message).
    Consider searching for similar bugs at https://github.com/sorbet/sorbet/issues
    or reporting a new one.
Errors: 1
```

**Comment by jez** [comment]
Dupe of #6876 / #5632
