### ISSUE TITLE
Overloaded sig isn't matched on T.untyped argument

### ISSUE THREAD

**Issue by bdewater** [sorbet/sorbet#7744]
In https://github.com/Shopify/tapioca/pull/1799 I'm generating overloaded signatures for Active Record methods, and @KaanOzkan and myself are confused by on `T.untyped` argument not matching the expected sig but instead is falling back to the first one.

#### Input

```ruby
# test.rbi
class User
  sig { params(args: T::Array[T.untyped]).returns(T::Enumerable[User]) }
  sig { params(args: T.untyped).returns(User) }
  def find(args); end
end
```

#### Observed output

```ruby
# test.rb
foo = T.let(nil, T.untyped)
bar = T.let([nil], T::Array[T.untyped])

T.reveal_type(User.find(foo)) # T::Enumerable[User]
T.reveal_type(User.find(bar)) # T::Enumerable[User]
```

#### Expected behavior

I was expecting `T.untyped` to match `T.untyped` and pick the second sig for the first example:

```ruby
# test.rb
T.reveal_type(User.find(foo)) # User
T.reveal_type(User.find(bar)) # T::Enumerable[User]
```

**Comment by jez** [comment]
Untyped is a subtype of T::Array[T.untyped], so the first overload is a valid candidate. There are two valid candidates, and so Sorbet chooses the first. This is working as expected.

**Comment by KaanOzkan** [comment]
@jez this came up again recently while generating signatures for more Rails methods. Would you be open to a change that picks the `T.untyped` sig if there are multiple candidates?

**Comment by bdewater** [comment]
Could `T.anything` work since it is not a subtype of all other types?

```rb
# test.rbi
class User
  sig { params(args: T::Array[T.anything]).returns(T::Enumerable[User]) }
  sig { params(args: T.anything).returns(User) }
  def self.find(args); end
end

# test.rb
T.reveal_type(User.find(nil)) # User
T.reveal_type(User.find(1)) # User
T.reveal_type(User.find([nil])) # T::Enumerable[User]
T.reveal_type(User.find([1, 2])) # T::Enumerable[User]

**Comment by paracycle** [comment]
> Could `T.anything` work since it is not a subtype of all other types?
> 
> ```ruby
> # test.rbi
> class User
>   sig { params(args: T::Array[T.anything]).returns(T::Enumerable[User]) }
>   sig { params(args: T.anything).returns(User) }
>   def self.find(args); end
> end
> 
> # test.rb
> T.reveal_type(User.find(nil)) # User
> T.reveal_type(User.find(1)) # User
> T.reveal_type(User.find([nil])) # T::Enumerable[User]
> T.reveal_type(User.find([1, 2])) # T::Enumerable[User]
> ```

@bdewater The problem surfaces when the type passed to `find` is `T.untyped`:
```ruby
# test.rbi
class User
  sig { params(args: T::Array[T.anything]).returns(T::Enumerable[User]) }
  sig { params(args: T.anything).returns(User) }
  def self.find(args); end
end

# test.rb
T.reveal_type User.find(T.unsafe(nil)) # T::Enumerable[User]
T.reveal_type User.find(T.unsafe(1)) # T::Enumerable[User]
T.reveal_type User.find(T.unsafe([nil])) # T::Enumerable[User]
T.reveal_type User.find(T.unsafe([1, 2])) # T::Enumerable[User]
```
