### ISSUE TITLE
Intermittent failures while publishing to RubyGems 

### ISSUE THREAD

**Issue by KaanOzkan** [sorbet/sorbet#7781]
There are failures in "Scheduled nightly RubyGems publish" starting at end of February: https://buildkite.com/sorbet/sorbet/builds?branch=master&state=failed. It's occasionally affecting `sorbet`, `sorbet-static` and `sorbet-static-and-runtime` releases.

Looking at the CI error it's probably being raised from RubyGems [here](https://github.com/rubygems/rubygems/blob/59bc67f40d6f98fb823d2356e5c2835a82a39447/lib/rubygems/package.rb#L62). Which is the constructor of `FormatError`, I think the actual exception is raised while trying to read the `gz` file [here](https://github.com/rubygems/rubygems/blob/59bc67f40d6f98fb823d2356e5c2835a82a39447/lib/rubygems/package.rb#L709-L716).

Since this is happening during verifying it feels like the `gz` file is sometimes corrupt. There are no glaring changes in the `.buildkite/` folder [history](https://github.com/sorbet/sorbet/commits/master/.buildkite).

**Comment by jez** [comment]
I looked into this and I don't know what's causing it. The few times it's happened, I've tried downloading the artifact manually (e.g., `_out_/gems/sorbet-0.5.11303.gem` from the Artifacts tab of the [build-static-release.sh](https://buildkite.com/sorbet/sorbet/builds/30704#018e5f6f-b1c1-4090-86b3-167b9a163c06) job here) and used the command line on my laptop to publish it, and it published with no issue.

I don't know what could be corrupting this file, or whether it is corrupted in the first place.

**Comment by jez** [comment]
I just tried again with the most recent failure. I downloaded [\_out\_/gems/sorbet-0.5.11303.gem](https://buildkite.com/organizations/sorbet/pipelines/sorbet/builds/30704/jobs/018e5f6f-b1c1-4090-86b3-167b9a163c06/artifacts/018e5f7d-9168-4b03-b61c-f13d38b21a52) from the `build-static-release.sh` job, and ran this locally:

```
❯ gem push --verbose sorbet-0.5.11303.gem
GET https://rubygems.org/latest_specs.4.8.gz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/rubygems-update-3.5.7.gemspec.rz
200 OK
Pushing gem to https://rubygems.org...
POST https://rubygems.org/api/v1/gems
200 OK
Successfully registered gem: sorbet (0.5.11303)
```

Which means I don't know at what point it's getting corrupted. Maybe the `buildkite-agent download artifact` command is corrupting it?

**Comment by KaanOzkan** [comment]
Great catch. Since it works locally I wonder if rubygems version is too old in the container. I couldn't find an installation/update command in the pipeline files so I assume it was setup initially and could be outdated.

**Comment by jez** [comment]
Not sure this is fixed yet, reopening until we're sure.

**Comment by jez** [comment]
Last night's build worked, I think that #7787 was the fix.
