### ISSUE TITLE
Return type is not recognized as a subtype of the super method when using requires_ancestor

### ISSUE THREAD

**Issue by lavoiesl** [sorbet/sorbet#7861]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20Interface%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20requires_ancestor%20%7B%20Model%20%7D%0Aend%0A%0Aclass%20Model%0A%20%20include%20Interface%0Aend%0A%0Aclass%20BaseProvider%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.returns%28Model%29%20%7D%0A%20%20def%20object%0A%20%20end%0Aend%0A%0Aclass%20Provider%20%3C%20BaseProvider%0A%20%20sig%20%7B%20override.returns%28Interface%29%20%7D%0A%20%20def%20object%0A%20%20%20%20Model.new%0A%20%20end%0Aend%0A)

```ruby
# typed: true

module Interface
  extend T::Helpers
  interface!

  requires_ancestor { Model }
end

class Model
  include Interface
end

class BaseProvider
  extend T::Helpers
  extend T::Sig
  abstract!

  sig { abstract.returns(Model) }
  def object
  end
end

class Provider < BaseProvider
  sig { override.returns(Interface) }
  def object
    Model.new
  end
end
```

#### Observed output

```
editor.rb:26: Return type Interface does not match return type of abstract method BaseProvider#object https://srb.help/5035
    26 |  def object
          ^^^^^^^^^^
    editor.rb:20: Super method defined here with return type Model
    20 |  def object
          ^^^^^^^^^^
  Note:
    A method's return type must be a subtype of the return type on the super method.
Errors: 1
```

---

Can also be observed with this minimal example:

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20Interface%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20requires_ancestor%20%7B%20Model%20%7D%0Aend%0A%0Aclass%20Model%0A%20%20include%20Interface%0Aend%0A%0Ainterface%20%3D%20T.let%28Model.new%2C%20Interface%29%0Amodel%20%3D%20T.let%28interface%2C%20Model%29)

```ruby
# typed: true

module Interface
  extend T::Helpers

  requires_ancestor { Model }
end

class Model
  include Interface
end

interface = T.let(Model.new, Interface)
model = T.let(interface, Model)
```

#### Observed output

```
editor.rb:14: Argument does not have asserted type Model https://srb.help/7007
    14 |model = T.let(interface, Model)
                ^^^^^^^^^^^^^^^^^^^^^^^
  Got Interface originating from:
    editor.rb:13:
    13 |interface = T.let(Model.new, Interface)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

My understanding is that since `Interface` _must_ be included in a `Model` object, returning an `Interface` should qualify as a `Model`.

**Comment by Morriar** [comment]
This is actually expected, having `Interface.requires_ancestor { Model }` does not mean that `Interface` itself is a subtype of `Model` but that any subtype of `Interface` is a subtype of `Model`.

You can change your example so that `Provider#object` returns a `T.all(Model, Interface)` instead:

```rb
# typed: true

module Interface
  extend T::Helpers
  interface!

  requires_ancestor { Model }
end

class Model
  include Interface
end

class BaseProvider
  extend T::Helpers
  extend T::Sig
  abstract!

  sig { abstract.returns(Model) }
  def object
  end
end

class Provider < BaseProvider
  sig { override.returns(T.all(Model, Interface)) }
  def object
    Model.new
  end
end
```

**Comment by lavoiesl** [comment]
Thank you for the explanation. 

`T.all` works, but considering that in my code, `Model.new` is actually an instance variable, that ends requiring that every annotation leading up to that is also using that `T.all`, which is overly verbose and cumbersome to use.

I hope that, one day, there will be a way to declare such interlocked dependency.
