### ISSUE TITLE
Add compiler flag to specify version of ARM architecture

### ISSUE THREAD

**Issue by maruthgoyal** [sorbet/sorbet#7932]
### Problem
[ARM v8.1a introduced new atomic instructions](https://learn.arm.com/learning-paths/servers-and-cloud-computing/lse/intro/#:~:text=The%20Armv8.,Large%20System%20Extensions%20(LSE).) which have shown better performance and scaling characteristics on [some benchmarks](https://cpufun.substack.com/p/atomics-in-aarch64). Based on the recommendations in the latter we should likely set `-march=armv8.1a` or `-moutline-atomics` (which will pick the instructions to emit based on detected architecture IIUC)

**Comment by jez** [comment]
Pretty sure this was implemented in #7933 but if that's not the case feel free to re-open.
