### ISSUE TITLE
Sorbet doesn't understand constant resolution through inheritance

### ISSUE THREAD

**Issue by XrXr** [sorbet/sorbet#8]
This code prints `2.718`:

```ruby
class A
  E = 2.718
end

class B < A
end

puts B::E
```

But Sorbet thinks it's wrong: https://sorbet.run/#class%20A%0A%20%20E%20%3D%202.718%0Aend%0A%0Aclass%20B%20%3C%20A%0Aend%0A%0Aputs%20B%3A%3AE

**Comment by Morriar** [comment]
Another example here with `include`: https://github.com/sorbet/sorbet/issues/3391

**Comment by jez** [comment]
Documented that Sorbet doesn't support this here:

https://sorbet.org/docs/unsupported#constant-resolution-through-constant-scopes-via-inheritance

closing as unplanned.
