### ISSUE TITLE
Bug with unconditional raise in begin block

### ISSUE THREAD

**Issue by azdavis-stripe** [sorbet/sorbet#802]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Abegin%0A%20%20x%20%3D%203%0A%20%20raise%0Arescue%0A%20%20T.reveal_type(x)%0Aend)

```ruby
# typed: true
begin
  x = 3
  raise
rescue
  T.reveal_type(x)
end
```

#### Observed output

`x: NilClass`

#### Expected behavior

`x: T.nilable(Integer)` as evidence by the runtime behavior:

```
$ irb
>> begin; x = 3; raise; rescue; p x; end
3
=> 3
```

**Comment by DarkDimius** [comment]
Fixed
