### ISSUE TITLE
Add generate annotation command in vs-code extension

### ISSUE THREAD

**Issue by rgevert** [sorbet/sorbet#8024]
### Problem

We are currently adopting sorbet on our project and one of the most repetitive task is to add type annotations to every single method. It would be great to have something that would somewhat automate this

### Proposed solution

I have been working on a vs-code extension of my own to generate those annotations from a single command. Something like this:

https://github.com/sorbet/sorbet/assets/30696955/4e4d1900-e708-467c-a4b5-bdc44ad50104

But I think it would much better to have this feature built in

**Comment by jez** [comment]
https://sorbet.org/docs/sig-suggestion
