### ISSUE TITLE
`darwin-24` support

### ISSUE THREAD

**Issue by builtbyproxy** [sorbet/sorbet#8049]
### Problem

👋 Hey team 👋

I'm apart of the MacOS 15.0 Sequoia Developer Beta and because of this I'm running `darwin-24`. 
Now when I run `bundle install` on my local machine, I get the error that only `darwin-21` -> `darwin-23` are supported. 

![image](https://github.com/user-attachments/assets/a100b752-f3c0-401c-8cd0-50a420ef2724)

This could be a non-issue, set to be fixed by the time 15.0 is stable, however given there are no references to `darwin-24` in this repo I thought I'd ask for an update before 15 ruins some people's days; **Is support for `darwin-24` planned?**

Thanks 👍

**Comment by jez** [comment]
As of this commit:

https://github.com/sorbet/sorbet/commit/d591b38dc7c0d65873a05d03c172444f32540d9d

we started publishing a single sorbet-static gem that works on all macOS versions as long as Rosetta is installed

**Comment by builtbyproxy** [comment]
Hey Jez, thanks for the timely response 🎉 

I have Rosetta installed however am still running into this issue. 
Is there a flag I need to attach to my bundle install or similar to make this work? 

Thanks
