### ISSUE TITLE
LSP starts returning confusing results after file changes occur

### ISSUE THREAD

**Issue by bdewater** [sorbet/sorbet#8134]
One of my co-workers reported this and she's not on the Sorbet Slack where I initially asked about this. Before the history on the Slack disappears, I'm copying over the relevant discussion here so others may find it:

> Bart de Water Jun 20th at 9:28 AM
> I'm experiencing some weirdness coming from Sorbet's LSP at times. It happens pretty regularly for me when changing git branches, but also just now with some regular code editing.
Example: I had a class `Foo::Counter` and changed it to not be namespaced under `Foo` module. Inside VS code the Active Record model and test file gave no errors after making the change and moving the files to comply with Zeitwerk conventions, but when adding a `Counter.increment("id")` to another class inside the `Foo` namespace I got an error: 'Method does not exist on T.class_of(Foo::Counter)'.
> It feels like the file watching mechanism is missing updates? A restart of the Sorbet LSP makes these go away and it's not too bad of a workaround, but if someone knows how to debug/get logging/etc I can try making a bug report at least.

> jez Jun 20th at 7:22 PM
You can pass the `--debug-log-file=/tmp/sorbet-vscode.log` wherever you pass `--lsp`, and that will instruct Sorbet to send all its logs there.
> One thing I’m noticing while working on something unrelated is an error like
> ```
> [2024-06-20 16:19:13.111] [consoleAndFile] [debug] {"version":"2024.05.06.00","error":"watchman::RootResolveError: failed to resolve root: unable to resolve root /Users/jez/sandbox/editor: failed to resolve root: directory /Users/jez/sandbox/editor is not watched"}
> [2024-06-20 16:19:13.111] [consoleAndFile] [debug] Unknown Watchman response:
> {"version":"2024.05.06.00","error":"watchman::RootResolveError: failed to resolve root: unable to resolve root /Users/jez/sandbox/editor: failed to resolve root: directory /Users/jez/sandbox/editor is not watched"}
> ```
> a few people online are suggesting that this might be because of Full Disk Access on macOS, but I’ve tried granting Full Disk Access permission to a ton of things watchman related and that error line persists.

> jez Jun 20th at 7:58 PM
> in my case, it looks like watchman requires some sort of indication of the root_files, which defaults to `.git` and `.hg`
> when I initialized a `.git` folder in my project, it fixed itself. It sounds like that’s not the behavior you’re seeing if you’re seeing these watchman problems on rebases (presumably you’re using git to do the rebases)

> Mark N Jun 21st at 2:47 AM
> I have been having this same problem but was unable to fix it. I often work around it with the "restart sorbet" command in vscode when switching branches or when the dsl gets updated:
>
> > Matthew Arkin Jun 11th at 11:42 PM
> > hmm, you should be able to do `srb tc --lsp --verbose`) and see if any useful output comes from https://github.com/sorbet/sorbet/blob/master/main/lsp/watchman/WatchmanProcess.cc#L106 (we don't use watchman at my gig so I'm out of my element beyond knowing that watchman should be the thing catching this get getting the sorbet-lsp to do the right thing)
> > 
> > Mark N Jun 11th at 11:45 PM
> > Looks like I'm getting an error:
> > `{"version":"2024.05.02.00","error":"watchman::RootResolveError: failed to resolve root: unable to resolve root`
> > probably permissions issues, will try to figure this out on my end

> Vasilis Jun 21st at 6:48 AM
> I am having similar issues as well.
> Since so far I have been lucky and it only has been on a couple of files being (lots of files with errors, but all errors about the same couple of files missing something), I just open the file in the editor and it is fixed (I guess it reads the definitions again when you open the file in the editor)

**Comment by marknuzz** [comment]
@bdewater @jez I finally fixed this by invoking `watchman watch-project .` in the shell at the root of the workspace. I also added a [.watchmanconfig](https://facebook.github.io/watchman/docs/config) file to the root of the project.
