### ISSUE TITLE
Intrinsic for `Array#zip` is wrong when given a block

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#8206]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params%28xs%3A%20T%3A%3AArray%5BInteger%5D%29.void%20%7D%0Adef%20example%28xs%29%0A%20%20res%20%3D%20xs.zip%28xs%29%20do%20%7Czipped%7C%0A%20%20%20%20T.reveal_type%28zipped%29%0A%20%20end%0A%20%20T.reveal_type%28res%29%0Aend)

```ruby
# typed: true
extend T::Sig

sig { params(xs: T::Array[Integer]).void }
def example(xs)
  res = xs.zip(xs) do |zipped|
    T.reveal_type(zipped)
  end
  T.reveal_type(res)
end
```

#### Observed output

```
editor.rb:7: Revealed type: Integer https://srb.help/7014
     7 |    T.reveal_type(zipped)
            ^^^^^^^^^^^^^^^^^^^^^
  Got Integer originating from:
    editor.rb:6:
     6 |  res = xs.zip(xs) do |zipped|
                               ^^^^^^

editor.rb:9: Revealed type: T::Array[[Integer, T.nilable(Integer)]] https://srb.help/7014
     9 |  T.reveal_type(res)
          ^^^^^^^^^^^^^^^^^^
  Got T::Array[[Integer, T.nilable(Integer)]] originating from:
    editor.rb:6:
     6 |  res = xs.zip(xs) do |zipped|
     7 |    T.reveal_type(zipped)
     8 |  end
Errors: 2
```

#### Expected behavior

- `zipped` should have type `[Integer, T.nilable(Integer)] (2-tuple)`
- `res` should have type `nil`

https://docs.ruby-lang.org/en/3.1/Array.html#method-i-zip

- - -

**Comment by ilyailya** [comment]
Fixed in https://github.com/sorbet/sorbet/pull/8229
