### ISSUE TITLE
Specialize "missing a sig" error when the sig is generated

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#833]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20DecisionFields%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3ASig%0A%20%20%20%20%20%20const%20%3Ahas_bad_url%2C%20T%3A%3ABoolean%0A%20%20%20%20%20%20const%20%3Ahas_free_or_reduced_trial%2C%20T%3A%3ABoolean%0A%20%20%20%20%20%20const%20%3Ahas_negative_outcome%2C%20T%3A%3ABoolean%0A%20%20%20%20%20%20const%20%3Ais_outside_us_exclusion%2C%20T%3A%3ABoolean%0A%20%20%20%20%20%20const%20%3Ahas_trial_within_money_back_exclusion%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Ahas_trial_no_payment_details_exclusion%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Ahas_review_on_platform_exclusion%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Ahas_prenotification_plan%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Arequires_payment_method%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Ahas_hidden_disclosures_or_fraud_claims%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Ahas_negative_reputation%2C%20T.nilable(String)%0A%20%20%20%20%20%20const%20%3Ahas_charge_info_clearly_displayed%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Ahas_clear_cancellation%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Ais_physical_product_subscription%2C%20T.nilable(T%3A%3ABoolean)%0A%20%20%20%20%20%20const%20%3Areviewer_note%2C%20T.nilable(String)%0A%0A%20%20%20%20%20%20sig%20%7Bgenerated.returns(T%3A%3AHash%5BSymbol%2C%20T.untyped%5D)%7D%0A%20%20%20%20%20%20def%20to_h%0A%20%20%20%20%20%20%20%20T.unsafe(nil)%0A%20%20%20%20%20%20end%0A%20%20%20%20end)

#### Observed output

```
editor.rb:21: This function does not have a `sig` https://sorbet.org/docs/error-reference#7017
    21 |      def to_h
              ^^^^^^^^
Errors: 1
```

#### Expected behavior

The error in this case should point to the `generated.` builder and say "This function has a generated sig" instead of "this function does not have a sig."

**Comment by jez** [comment]
We removed generated sigs entirely in #2226.
