### ISSUE TITLE
Using to_h with T.all forgets that the value type was a T.all

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#884]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Parent%3B%20end%0Amodule%20Interface%3B%20end%0Aclass%20Child%20%3C%20Parent%0A%20%20include%20Interface%0Aend%0A%0Adef%20bar%0A%20%20x%20%3D%20T.let(%5B%5B%3Achild%2C%20Child.new%5D%5D%2C%20T%3A%3AArray%5B%5BSymbol%2C%20T.all(Parent%2C%20Interface)%5D%5D)%0A%20%20T.reveal_type(x.to_h)%0Aend)

```ruby
# typed: true
extend T::Sig

class Parent; end
module Interface; end
class Child < Parent
  include Interface
end

def bar
  x = T.let([[:child, Child.new]], T::Array[[Symbol, T.all(Parent, Interface)]])
  T.reveal_type(x.to_h)
end
```

#### Observed output

```
editor.rb:12: Revealed type: T::Hash[Symbol, Parent] https://srb.help/7014
    12 |  T.reveal_type(x.to_h)
          ^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:12:
    12 |  T.reveal_type(x.to_h)
                        ^^^^^^
Errors: 1
```

#### Expected behavior

```
editor.rb:12: Revealed type: T::Hash[Symbol, T.all(Parent, Interface)] https://srb.help/7014
    12 |  T.reveal_type(x.to_h)
          ^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:12:
    12 |  T.reveal_type(x.to_h)
                        ^^^^^^
Errors: 1
```

It looks like for some reason our `to_h` intrinsic method drops the fact that the value type was a `T.all`. I haven't confirmed whether this is expected behavior or a bug in the intrinsic method (or something else).

Reported by @akshay-stripe

**Comment by akshay-stripe** [comment]
cc @axyjo

**Comment by jmikkola-stripe** [comment]
The same thing happens with lists:

https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20A%3B%20end%0A%0Amodule%20B%3B%20end%0A%0Asig%20%7Bparams(x%3A%20Integer).returns(T.all(A%2C%20B))%7D%0Adef%20return_ab(x)%0A%20%20return_ab(x)%0Aend%20%0A%0Adef%20main%0A%20%20ab_list%20%3D%20%5B1%2C2%2C3%5D.map%20%7B%7Ci%7C%20return_ab(i)%7D%0A%20%20T.reveal_type(ab_list)%0Aend

**Comment by akb-stripe** [comment]
Here's another example of the issue

https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20WhateverInterface%3B%20end%0Amodule%20WhyInterface%3B%20end%0Amodule%20HelpInterface%3B%20end%0A%0Aclass%20Test%0A%20%20include%20WhateverInterface%0A%20%20include%20WhyInterface%0A%20%20include%20HelpInterface%0Aend%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20Everything%20%3D%20T.type_alias%20do%20%0A%20%20%20%20T.all(%0A%20%20%20%20%20%20WhateverInterface%2C%0A%20%20%20%20%20%20WhyInterface%2C%0A%20%20%20%20%20%20HelpInterface%2C%0A%20%20%20%20)%0A%20%20end%0A%20%20sig%20%7Breturns(T%3A%3AArray%5BEverything%5D)%7D%0A%20%20def%20something%0A%20%20%20%20arr%20%3D%20T.let(%5BTest.new%5D%2C%20T%3A%3AArray%5BEverything%5D)%0A%20%20%20%20results%20%3D%20arr.map%20do%20%7Celem%7C%0A%20%20%20%20%20%20elem%0A%20%20%20%20end%0A%20%20%20%20%23%20this%20is%20a%20type%20error%20because%20the%20returned%20value%20is%20allegedly%20of%20type%20T%3A%3AArray%5BWhateverInterface%5D%0A%20%20%20%20results%0A%20%20end%0Aend%0A

**Comment by jez** [comment]
https://github.com/sorbet/sorbet/blob/b97904fb19df3c4b015d4e0e0073522251d9f42a/infer/environment.cc#L1080-L1081
