### ISSUE TITLE
Duplicating a key in a hash literal should error

### ISSUE THREAD

**Issue by azdavis** [sorbet/sorbet#898]
Related to #885 and #886.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Ax%20%3D%20%7By%3A%203%2C%20y%3A%204%7D%0AT.reveal_type(x))

```ruby
# typed: true
x = {y: 3, y: 4}
T.reveal_type(x)
```

#### Observed output

```
editor.rb:3: Revealed type: {y: Integer(3), y: Integer(4)} https://srb.help/7014
     3 |T.reveal_type(x)
        ^^^^^^^^^^^^^^^^
  From:
    editor.rb:2:
     2 |x = {y: 3, y: 4}
            ^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Error about statically-knowably-duplicate hash keys. This should match the runtime behavior:

```
❯ irb
irb(main):001:0> {y: 3, y: 4}
(irb):1: warning: key :y is duplicated and overwritten on line 1
=> {:y=>4}
```

**Comment by jez** [comment]
Fixed in #3345
