### ISSUE TITLE
module_function should mark instance methods private

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#904]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20M%0A%20%20module_function%0A%20%20def%20foo%3B%20end%0Aend%0A%0AM.foo%0A%0Aclass%20A%0A%20%20include%20M%0Aend%0A%0AA.new.foo)

```ruby
# typed: true

module M
  module_function
  def foo; end
end

M.foo

class A
  include M
end

A.new.foo
```

#### Observed output

No errors are raised, however running the program yields this error:
```
ruby test.rb
test.rb:14:in `<main>': private method `foo' called for #<A:0x00007fbe051c13d8> (NoMethodError)
```

#### Expected behavior

An error should be raised from the send `A.new.foo`, as `foo` is a private method of `A`.

#### Additional analysis

The line `M.foo` will cause the `ENFORCE`
```
inWhat == fromWhat || inWhat.data(ctx)->derivesFrom(ctx, fromWhat) ||
                  fromWhat.data(ctx)->derivesFrom(ctx, inWhat)
```
from `core/types/types.cc:resultTypeAsSeenFrom` to fail, as the owner of the aliased self-method does not appear to be the singleton class of `M`. It seems as though there's something wrong with the implementation of `namer/namer.cc:aliasMethodFunction` (or `namer/namer.cc:aliasMethod`), as this is where the ownership of the alias is setup.

**Comment by jez** [comment]
There is a larger question that Sorbet doesn't statically support checking method visibility. We can't fix this until then.

**Comment by elliottt** [comment]
This has since been fixed as the ModuleFunction.cc pass will introduce instance methods that are marked as `private`.
