### ISSUE TITLE
Make sorbet obey .gitignore

### ISSUE THREAD

**Issue by film42** [sorbet/sorbet#936]
### Problem

I noticed sorbet will attempt to check all ruby files even if they've been ignored in a `.gitignore` file. It would be really nice to exclude these files from sorbet.

As an emacs user I have certain file names excluded in my global `.gitignore`. One of these is a temp file that emacs creates when a file buffer has unsaved changes. When I run sorbet, it attempts to read this file and fails.

```
$ bx srb
app/controllers/.#deploys_controller.rb: File Not Found https://srb.help/1004
Errors: 1
```

### Proposed solution

It would be awesome if sorbet could consult with git to discover valid or exclude ignored ruby files (something like `git ls-files`, but via libgit). Then you could set a project-level sorbet config to disable this if you want to always check ignored files.

I'd be happy to explore adding this behavior, but I figured it's best to start with an open feature request first.

**Comment by DarkDimius** [comment]
We currently try to not have too many mechanisms for ignoring a file.
The one that we have is adding `# typed: ignore` into the file. Could you try it?

**Comment by film42** [comment]
That’s not really possible in this case since the file only exists when I have unsaved changes. I guess this includes a bug too since the temp file could not be read by sorbet. So even if I edited the header before making additional edits, it would still error.

**Comment by ptarjan** [comment]
Thanks for the suggestion. I don't think we're interested in supporting `.gitignore` at this time. May I suggest you put all your temporary emacs files in another folder?
