### ISSUE TITLE
`sorbet init` crashes with a segfault

### ISSUE THREAD

**Issue by BrianHicks** [sorbet/sorbet#945]
I'm trying to get started with sorbet on a big Rails project. I get a segfault from `srb init`. To try getting around it:

1. I temporarily tried adding `# typed: ignore` to all files. Then `srb init` worked!
2. I removed `# typed: ignore` from all my `spec/` files. `srb rbi` worked again.
3. I removed `# typed: ignore` from all my `app/` files. Now it crashes.

Here's a log of the crash, the error file it mentions, and the output of the command it asked me to run to debug: https://gist.github.com/BrianHicks/4a2afce64bf3b1583086dd258f7707ad

I'm going to try and continue to winnow the possible problematic files down in the morning with `typed: ignore` comments. For now, I'd appreciate knowing if that's an OK approach or what else I should try!

P.S. sorry, the issue template does not seem relevant for this issue so I have removed it.

**Comment by ptarjan** [comment]
Thanks for the report. That does indeed look like a segfault! Can you try to find out what file caused it and get a smaller repro? Maybe something like this is helpful

```
$ rm sorbet/config # So you don't include everything
$ find . -type f | xargs -L 1 -t srb tc --error-white-list 1000
```

**Comment by BrianHicks** [comment]
ahhh, that's helpful. Thanks! Here's an [SSCCE](http://www.sscce.org/):

https://sorbet.run/#class%20Foo%0A%20%20self%3A%3AFoo%20%3D%20Struct.new(%3Ax)%0Aend

```ruby
class Foo
  self::Foo = Struct.new(:x)
end
```

These come up in our policy files for some reason! I'm not really sure what's going on there.

```
srb tc --error-white-list 1000 app/policies/unit_diagnostic_policy.rb
/Users/brianhicks/.gem/ruby/2.5.0/gems/sorbet-0.4.4259/bin/srb: line 43:  7778 Segmentation fault: 11  "${sorbet[0]}" "${args[@]}"
```

**Comment by DarkDimius** [comment]
Thank you for a great reproducer!

**Comment by zhulik** [comment]
`srb tc` also crashes on trusty travis-ci VM
```
/home/travis/build/.../vendor/bundle/ruby/2.3.0/gems/sorbet-0.4.4271/bin/srb: line 43: 7404 Segmentation fault (core dumped) "${sorbet[0]}" "${args[@]}"
```
