### ISSUE TITLE
Document usage in "minimal" environments like Alpine

### ISSUE THREAD

**Issue by joho** [sorbet/sorbet#948]
#### Input

Can't sorbet against my development docker container (based on `ruby:2.6-alpine`)

```sh
docker-compose run --rm server srb init
```

#### Observed output

``` 
Starting app_db_1 ... done
The Gemfile's dependencies are satisfied
env: can't execute 'bash': No such file or directory
```
#### Expected behavior

I'd expected a pure rubygem. Not a big deal, I'm modifying the image to include bash, but a quick docs change might improve the onboarding experience.

I'm hoping/assuming the runtime gem will run without bash otherwise I'll need to change the production container too.

**Comment by DarkDimius** [comment]
Hi @joho ,
While `sorbet-runtime` indeed is pure ruby gem, `sorbet-static` is a C++ binary that is linked against glibc(thus won't work on alpine).
You should be able to use `sorbet-runtime` in an alpine environment, though `srb` and `srb tc` will need an environment that has a lot of stuff, bash and glibc included. 

As we don't run alpine or minimal isntances it's hard for us to address this issue.
Would you be willing to contribute a documentation fix as you're exploring it?

**Comment by joho** [comment]
Sure, more than happy to.

Docs are in the `/website` folder?

**Comment by RoryO** [comment]
As an aside, the static checker does not work on Windows for the same reason. There is no `sorbet-static` gem which satisfies. I think linking against mingw-w64 should work a it's a gcc & glib port on windows.

**Comment by DarkDimius** [comment]
@RoryO in order to have windows support, someone will need:
- add a clang8 windows toolchain support to https://github.com/DarkDimius/bazel-toolchain/tree/dp-srb-now;
- setup CI to test & publish on windows.

Stripe doesn't use windows so we'll have to rely on contributors to build this.

**Comment by mmyoji** [comment]
FYI, if you use alpine, install `bash`, `git` and `glibc` beforehand.

See `glibc` installation here https://github.com/sgerrand/alpine-pkg-glibc#installing

I tested this with `ruby:2.6.3-alpine` docker image.

**Comment by DarkDimius** [comment]
@mmyoji thank you! This is great to know!

**Comment by solutus** [comment]
I catch following error when try to run srb tc  on CentOS7. 
```bundle exec  srb typecheck -e 'puts "Hello, world!"'
/home/web/app/vendor/bundle/gems/sorbet-static-0.4.4388-x86_64-linux/libexec/sorbet: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/web/app/vendor/bundle/gems/sorbet-static-0.4.4388-x86_64-linux/libexec/sorbet)
```
CentOS7 has glibc 2.17 and it seems too risky to update this library as it is one of most important libs. Can I use my current OS with sorbet anyhow? 

My configuration:
```rpm -q centos-release
centos-release-7-3.1611.el7.centos.x86_64
```
```
Name        : glibc
Arch        : x86_64
Version     : 2.17
Release     : 260.el7_6.4
```

thanks
