### ISSUE TITLE
Running srb init clobbers magic encoding comment

### ISSUE THREAD

**Issue by scivola** [sorbet/sorbet#952]
`srb init` command inserts a line such as

```rb
# typed: strong
```

at the top of a Ruby script.
If the script has a magic comment such as

```rb
# encoding: UTF-8
```

it becomes as

```rb
# typed: strong
# encoding: UTF-8
```

In the case, the second line does not work as a magic comment, because magic comments should be placed at the top of the script or the next line of the shebang line.

Of course I know that the default script source encoding is UTF-8 from Ruby 2.0.0 and necessity of the magic comment is now low.
However, another script source encoding such as CP932 still be used, and there are some cases such that the magic comment is needed even if the script source encoding is UTF-8 (e.g. when the script is evaluated via `eval` in the environment of some locale in Windows).

**Comment by deepj** [comment]
Many people use `frozen-string` magic comment in their apps or gems

**Comment by ivoanjo** [comment]
Yeah I was bit by this, as my [my gem](https://gitlab.com/ivoanjo/persistent-dmnd) uses the magic comment to allow UTF-8 on Ruby 1.9.3, but this generally breaks any Ruby code that tries to use an alternative encoding on the file:

```bash
$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
$ cat test-without-comment.rb 
# encoding: big5
p "".encoding # => #<Encoding:Big5>
$ ruby test-without-comment.rb 
#<Encoding:Big5>
$ cat test-with-comment.rb 
# typed: false
# encoding: big5
p "".encoding # => #<Encoding:Big5>
$ ruby test-with-comment.rb 
#<Encoding:UTF-8>
```

**Comment by jez** [comment]
Closing this in favor of tapioca.

https://sorbet.org/blog/2022/07/27/srb-tapioca
