### ISSUE TITLE
I love the logo.

### ISSUE THREAD

**Issue by kiding** [sorbet/sorbet#955]
<p align="center">
  <img alt="Sorbet logo" width="200" src="https://github.com/sorbet/sorbet/raw/master/docs/logo/sorbet-logo-purple-sparkles.svg?sanitize=true">
</p>

Not even remotely an issue—I'd love to at least give some appreciation towards the creators of the very cute Sorbet logo. I have around zero knowledge with Ruby at all, but their smile looks so tempting like _"try me."_

Anyways, thanks for the great work. Close this issue whenever you want.

**Comment by jez** [comment]
Thanks! We like it too. The sources are in https://github.com/sorbet/sorbet/tree/master/docs/logo. The trademark policy is here: https://sorbet.org/docs/legal/trademark-policy
