### ISSUE TITLE
Using if without else at end of while loop appears to introduce `nil`

### ISSUE THREAD

**Issue by neil-stripe** [sorbet/sorbet#96]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%200%0Acond%20%3D%20T.unsafe(nil)%0A%0Awhile%20cond%0A%20%20if%20true%0A%20%20%20%20puts%20x%0A%20%20end%0A%20%20%23%20try%20uncommenting%0A%20%20%23%20puts%20nil%0Aend%0A%0Ax.succ)

```ruby
# typed: true

x = 0
cond = T.unsafe(nil)

while cond
  if true
    puts x
  end
  # try uncommenting
  # puts nil
end

x.succ
```

#### Observed output

```
editor.rb:14: Method succ does not exist on NilClass component of T.nilable(Integer) https://srb.help/7003
    14 |x.succ
        ^^^^^^
  Got T.nilable(Integer) originating from:
    editor.rb:3:
     3 |x = 0
            ^
    editor.rb:3: Possibly uninitialized (NilClass) in:
     3 |x = 0
     4 |cond = T.unsafe(nil)
     5 |
     6 |while cond
     7 |  if true
       |...
    10 |  # try uncommenting
    11 |  # puts nil
    12 |end
    13 |
    14 |x.succ
  Autocorrect: Use `-a` to autocorrect
    editor.rb:14: Replace with T.must(x)
    14 |x.succ
        ^
Errors: 1
```

#### Expected behavior

No errors.

- - - - -

Here is the CFG output:

**Without `puts nil`**

<img width="1390" alt="Screen Shot 2021-05-21 at 4 14 55 PM" src="https://user-images.githubusercontent.com/5544532/119206323-b19d7080-ba4f-11eb-943f-e1cd30f40b2a.png">

**With `puts nil`**

<img width="1387" alt="Screen Shot 2021-05-21 at 4 16 49 PM" src="https://user-images.githubusercontent.com/5544532/119206424-f5907580-ba4f-11eb-96a5-e1d68b25b8cc.png">

**Comment by elliottt** [comment]
Fixed in #8291
