### ISSUE TITLE
False positive on unreachable code after is_a

### ISSUE THREAD

**Issue by viraptor** [sorbet/sorbet#966]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20T.any(Integer%2C%20String%2C%20T%3A%3ABoolean)).returns(String)%7D%0A%20%20def%20bar(x)%0A%20%20%20%20return%20x.to_s%20if%20x.is_a%3F%20Numeric%20%7C%7C%20x%20%3D%3D%20true%20%7C%7C%20x%20%3D%3D%20false%0A%20%20%20%20%22foo%22%0A%20%20end%0Aend%0A)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: T.any(Integer, String, T::Boolean)).returns(String)}
  def bar(x)
    return x.to_s if x.is_a? Numeric || x == true || x == false
    "foo"
  end
end
```

#### Observed output

```
editor.rb:7: This code is unreachable https://srb.help/7006
     7 |    return x.to_s if x.is_a? Numeric || x == true || x == false
                                                     ^^^^

editor.rb:7: This code is unreachable https://srb.help/7006
     7 |    return x.to_s if x.is_a? Numeric || x == true || x == false
                                                                  ^^^^^
```

#### Expected behavior

Since the parameter may not be a `Numeric`, the next condition is definitely reachable. There should be no error here.

**Comment by DarkDimius** [comment]
@viraptor AFAIK this is a correct error.
The way this parses in Ruby is 
```
return x.to_s if x.is_a?(Numeric || (x == true) || (x == false))
```

Note that because `Numeric` is truthy, only the first component of || ever gets evaluated.

**Comment by jeffcarbs** [comment]
You need to use parens on the method call to `is_a?`, I don't think it's doing what you're expecting.

```ruby
# Original
x.is_a? Numeric || x == true || x == false

# How ruby treats it
x.is_a?(Numeric || x == true || x == false)

# So you need parens:
x.is_a?(Numeric) || x == true || x == false
```

**Comment by viraptor** [comment]
Sorbet just found some real issue! :D
