### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by Lewiscowles1986** [sorbet/sorbet#970]
I'm not a core contributor but this is in the README.md https://github.com/sorbet/sorbet/blob/8473dfe49e0af9266c1e45b7867a57d417dccd8e/README.md#c-conventions

Be great to track this. Thank you

**Comment by DarkDimius** [comment]
Short version: sorbet has '--web-trace-file=foo.json' argument.
This creates traces that can be viewed in chrome://tracing of Chrome

**Comment by jez** [comment]
The `task` label is for contributors only. We're currently tracking it with that TODO.

Thanks for your interest in Sorbet!
