### ISSUE TITLE
Sorbet does not understand Ruby 2.6's endless range syntax

### ISSUE THREAD

**Issue by kkuchta** [sorbet/sorbet#972]
#### Input

[→ View on sorbet.run](https://sorbet.run/#if%20(3..).include%3F(x)%0A%20%20'yes'%0Aelse%0A%20%20'no'%0Aend)

```ruby
if (3..).include?(x)
  'yes'
else
  'no'
end
```

#### Observed output

```
editor.rb:1: Parse Error: unexpected token: syntax error https://srb.help/2001
     1 |if (3..).include?(x)
```

#### Expected behavior

The code should at least not throw a syntax error, since this is valid ruby 2.6

- - -

It looks like endless ranges (`2..`) don't work.  If ruby 2.6, where they were introduced, isn't officially supported, it might be good to document that somewhere.  Or, if that's already document somewhere and I missed it, ignore me!  :)

**Comment by iliabylich** [comment]
What's the version of sorbet's parser/lexer? Is it supposed to handle the latest version ruby? All of them? (the latter is impossible)
I see that lexer.rl has a bunch of ruby-version-specific checks, but there's only 1 grammar file.
I could help with that

**Comment by iliabylich** [comment]
More errors:
```
meth[] {} # valid starting from 2.5
class A; return; end # invalid starting from 2.5
m [] {} # invalid starting from 2.5

begin; 1; else; 2; end # invalid starting from 2.6
-> do rescue; end # valid starting from 2.6
```

however, it handles some new features of 2.5 (like `meth do; foo; rescue; bar; end`), so I guess current state of parser/lexer is somewhere between 2.5 and 2.6.

**Comment by ptarjan** [comment]
You're right. The state of the version of the parser/lexer used to be "Whatever Stripe uses" and now is "kind of a hybrid". If you want to tackle figuring out what the story is for multiple version support, please do, we haven't really put much thought into it other than kicking it down the road.

If you don't want to shave that yak, we will happily take patches for backwards compatible syntax changes.

Also for context, the original parser was a line-by-line port of the whitequark parser into C++. So keeping it close to that would be helpful so we can incorporate changes from them. (AKA don't go refactor the whole thing for fun please)

**Comment by kkuchta** [comment]
Fair enough!

I imagine that multiple-version support is going to be a thing we'll want to deal with sooner than later.  We can make backwards-compatible fixes to the parser to handle syntax, but we'll still get issues with the stdlib.  Eg `Integer.sqrt(n)` [fails type checking](https://sorbet.run/#Integer.sqrt(0)) because that method was introduced in 2.5.  Likewise, `RubyVM::Env` [fails](https://sorbet.run/#RubyVM%3A%3AEnv.class) because that constant was removed in 2.4.  We could probably rely on syntax additions usually being additive, but that doesn't seem to be the case for stdlib changes.

**Comment by DarkDimius** [comment]
+1 for implementing a superset of syntax all supported versions of Ruby, unless it makes it much harder.
Overall, we haven't found a problem of using unsupported syntax of Ruby to be a widespred issue so it doesn't seem that maintaining multiple parsers for different versions would be worth it.

**Comment by iliabylich** [comment]
@ptarjan @DarkDimius Is there any way to expose parser/lexer and reuse whitequark/parser's test suite? (similar to https://github.com/opal/c_lexer) I've started backporting missing updates and corresponding tests but it's *very* painful

**Comment by ptarjan** [comment]
@iliabylich How would you want it exposed? I pulled in the test suite maybe a year ago here: https://github.com/sorbet/sorbet/tree/master/test/testdata/parser/whitequark . You can use `-p` options to `srb tc` to print out various parts of the pipeline (and that is what is in those `.exp` files)

**Comment by iliabylich** [comment]
Yes, that's what I did locally as well (and it kinda works). It is possible to write tests this way, but it's very hard to debug it when things go wrong. whitequark/parser exposes more internal things after shifting each token (like lexer's state, values of cmdarg/cond/context stacks etc).

Also, every time when I did some changes to `lexer.rl` I had to recompile a lot of files

> How would you want it exposed?

Is it possible to compile an isolated `parser` that takes ruby code via stdin and prints AST? We could try monkeypatching `assert_parses` to do something like `Open3.capture3(parser_executable, 'ruby-code')` under the hood (existing specs don't very complex things like source maps anyway, so we only need the structure of the AST). Maybe this executable could also dump it into something like json?

**Comment by ptarjan** [comment]
You're welcome to send us PRs for those output formats of capturing more
would be helpful. They are internally used so can be changed. So if you
want them to be real JSON you can do that too.

As for the executale

srb tc -p parse-tree-raw -e

Might be close to what you want?

**Comment by iliabylich** [comment]
It's `parse-tree-json`, thanks, I'll try it!

**Comment by iliabylich** [comment]
Quick question on endless ranges: `.rbi` files don't support it. `Range<TBegin, TEnd>` returns `TBegin` from `#begin` method and `TEnd` from `#end` method. Should we update them? Or should we introduce more types for literal-based ranges?
+ `1..2` always has `.begin` and `.end`
+ `a..b` may return `nil` from both methods. 
+ `<whatever>..` always returns `nil` from `.end`

I'll send a PR with updates to AST, should be straightforward after merging https://github.com/sorbet/sorbet/pull/1670, but I don't know what do with types
