### ISSUE TITLE
[WIP] Collecting data for Prerequisites doc page

### ISSUE THREAD

**Issue by jasnow** [sorbet/sorbet#979]
# Problem

Unclear the versions of Ruby and OS's are tested/supported.

# Proposed solution

**Corrections and more information are welcome.**

# Ruby
Appears that we support Ruby 2.4.3 to 2.6.3.
   - Reference: sorbet/.ruby-version file: says "2.4"
   - Reference: third_party/ruby/ruby-2.4.BUILD file

## Mac OS
Appears that we testing for current and last 2 Mac OS versions (Sierra, High Sierra, Mojave)
  - Reference: https://support.apple.com/en-us/HT201686
  - Reference: https://support.apple.com/en-us/HT201222 (See latest OS Update for Sierra 10.12.6 in May 2019)
  - Reference: sorbet/.buildkite/build-static-release.sh (mentioned linux and mac/darwin; 14 to 18)
~~**Question: What does "oldest v8" in sorbet/.buildkite/build-static-release.sh mean?**~~

# Linux
Appears that we test all i686 versions of linux.
  - Reference: sorbet/tools/toolchain/webasm-linux/CROSSTOOL (found i686-linux-gnu)
  -  Reference: sorbet/.bazelrc (found lib/linux/libclang_rt.ubsan_standalone-x86_64")

~~**Question: Any limit of Linux distributions?**~~

## Windows
Appears that we do NOT test on any Windows OS versions.
  - Reference: https://github.com/sorbet/sorbet/issues/948

# After I get answers and feedback, I will create a PR and submit it.

Use "Edit" button on https://sorbet.org/docs/overview page to
create "Prerequisites" tab in left side bar between "Overview" and
"Adopting Sorbet" with "Tested HW/OS Versions" page

The page will contain:
Currently Sorbet is tested to work on
Mac OS ...
and Linux OS (...).
We do not test Sorbet on Windows OS but we welcome community
help with this.

**Corrections and more information are welcome.**

**Comment by jasnow** [comment]
You can assign this issue to me.

**Comment by ptarjan** [comment]
Thanks for your interest in helping here!

We just made our `.gemspec`s prohibit the version of Ruby that it doesn't work on. You can use that as a source of truth.

As for OSes, our build system uses `OSX Mojave` but we publish gems from version 14 to 18 so we expect it to work on older versions since it is a statically linked binary. Similarly for linux we test on ubuntu 18 but expect it to work on almost everything. We do not work on Windows.

**Comment by jasnow** [comment]
@pt-stripe - Thanks for the feedback.

**Comment by jasnow** [comment]
@ptarjan - Where is the .gemspec file you mention above?

**Comment by jasnow** [comment]
Figured out "version 14 to 18" refers to Darwin versions. 
* Reference: https://en.wikipedia.org/wiki/Darwin_(operating_system)

**Comment by jasnow** [comment]
Now that PR  #1007 has been merged, I can close this issue. Thanks to @DarkDimius, @ptarjan, and @jez  for the help on my first PR for this project.
