### ISSUE TITLE
Module / respond_to? as types

### ISSUE THREAD

**Issue by baweaver** [sorbet/sorbet#983]
### Problem

In Ruby, several collection classes implement the `Enumerable` module as a type of contract. There are others around sorting and other ideas, so I'd thought to try and type against them:

```ruby
# typed: true

extend T::Sig

sig { params(list: Enumerable).returns(Integer) }
def sum(list)
  list.reduce(0, :+)
end

def main
  sum([1, 2, 3])
end
```

Granted this is a slightly contrived example, but it still returns an error:

```ruby
editor.rb:5: Malformed type declaration. Generic class without type arguments Enumerable https://srb.help/5004
     5 |sig { params(list: Enumerable).returns(Integer) }
                           ^^^^^^^^^^
Errors: 1
```

Side note: Error 5004 doesn't exist in the documentation.

### Proposed solution

In YARDoc and other "soft" static typing systems in Ruby, modules and `respond_to?` interfaces are accepted as types.

Something could act as an `Enumerable` which would satisfy certain type constraints, or playing off of duck typing a constraint could be satisfied by the fact that a class implements that method.

The above example is how `Enumerable` might work. `respond_to?` would be more interesting, though a potential API would be:

```ruby
sig { params(list: respond_to?(:each)).returns(Integer) }
```

In some Pattern matching implementations I use `respond_to?` to designate an interface to get extra power using `===`, which might look like this:

```
sig do
  params(
    conditions: T::Array[respond_to?(:===)],
    object: T.any
  ).returns(T.boolean) # probably not right
end
def match(conditions, object)
  conditions.all? { |c_name, c_matcher| c_matcher === object.send(c_name) }
end
```

The signature would indicate that there's significance to the `===` on each of the conditions provided, which could be used for some interesting hinting in editors as well. Doubly so if used in conjunction with YARDoc or a similar standard to tie in explanations to that.

**Comment by rafaelfranca** [comment]
This should also work:

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%0Asig%20%7B%20params(list%3A%20T%3A%3AEnumerable%5BObject%5D).returns(Integer)%20%7D%0Adef%20sum(list)%0A%20%20list.reduce(0%2C%20%3A%2B)%0Aend%0Aend%0A%0Adef%20main%0A%20%20A.new.sum(%5B1%2C%202%2C%203%5D)%0Aend

```ruby
# typed: true
class A
  extend T::Sig


sig { params(list: T::Enumerable[Object]).returns(Integer) }
def sum(list)
  list.reduce(0, :+)
end
end

def main
  A.new.sum([1, 2, 3])
end
```

**Comment by ptarjan** [comment]
@rafaelfranca is correct. We expect people who want to type these STDLIB objects that are generics to use their `T::` equivalents.

**Comment by jez** [comment]
For posterity: the specific solution of `responds_to?` as a type is something we are unlikely to **ever** support, because just knowing that a method responds to a name does **not** mean we know it's arity let alone the types of the method parameters themselves.

**Comment by whiny-nil** [comment]
How does one do duck-typing, especially on the core classes?  If I want to write a signature for a method that accepts something that responds to `to_s`, how can I do that?  I understand that if I control the code entirely, I could do this by mixing-in modules, but I don't control the core classes.

**Comment by ric2b** [comment]
What about something like Python's protocols, so we can depend on interfaces?
https://www.python.org/dev/peps/pep-0544/
