### ISSUE TITLE
LSP: no hover on `extend`

### ISSUE THREAD

**Issue by XrXr** [sorbet/sorbet#991]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Mod%0Aend%0A%0Aclass%20A%0A%20%20include(Mod)%0A%20%20extend(Mod)%0Aend%0A)

```ruby
# typed: true
module Mod
end

class A
  include(Mod)
  extend(Mod)
end
```

#### Observed output

(tested on sorbet.run)
No prompt when hovering over `Mod` passed to extend.

#### Expected behavior

Show a prompt like the one shown when hovering over `Mod` in include.

**Comment by jvilk-stripe** [comment]
I've confirmed this issue. Thanks for the report!
