### ISSUE TITLE
Inferred type of argument should be used in returns as well

### ISSUE THREAD

**Issue by viraptor** [sorbet/sorbet#996]
### Problem

Autogenerated signature for the following method:
```
  def bar(x)
    File.dirname(x)
    x
  end
```
is:
```
sig {generated.params(x: String).returns(T.untyped)}
```

But once the argument is resolved to be a `String`, that type becomes the only possible result as well.

### Proposed solution

Use the inferred argument type in the return type as well.
```
sig {generated.params(x: String).returns(String)}
```

**Comment by DarkDimius** [comment]
`generated` signature inference is supposed to be used as a fixed-point computation.
Running it twice on this snippet indeed doesn't infer result type in first run, but it does correctly infer it in the second one.

This is expected behavior.
