### ISSUE TITLE
[README] Broken Link

### ISSUE THREAD

**Issue by JanOwiesniak** [sorbet/sorbet#997]
> If you are at Stripe, you might also want to see http://go/types/internals for docs about Stripe-specific development workflows and historical Stripe context.

The link http://go/types/internals is broken.

**Comment by DarkDimius** [comment]
This is intentional, this link documents Stripe-specific usage and common code patterns with types that only exist in our codebase. Those types are specific to our business domain & our monorepo and thus aren't helpful to others.

**Comment by JanOwiesniak** [comment]
@DarkDimius thanks for clearing this up!
